USE LYCEUM
GO  

--MODIFICADO PARA PUXAR DO HISTORICO - DEMANDA PONTUAL DE ANDRE
--EXEC FTC_SP_csvListaTurmas '2019','1',NULL,NULL,NULL,NULL,NULL  
ALTER PROCEDURE dbo.FTC_SP_csvListaTurmas    
(          
  @P_ANO VARCHAR(4)    
, @P_SEMESTRE VARCHAR(1)    
, @P_FACULDADE VARCHAR(20)    
, @P_TIPO_CURSO VARCHAR(30)      
, @P_CURSO  VARCHAR(20)      
, @P_TURNO  VARCHAR(20)      
, @P_CURRICULO VARCHAR(20)      
)          
AS          
-- [INÍCIO]                  
BEGIN          
      
SET NOCOUNT ON      

	CREATE TABLE #TEMP (
		UNIDADE_ENSINO VARCHAR(10),
		NOME_UNIDADE_ENS VARCHAR(200),
		UNIDADE_FISICA VARCHAR(20),
		NOME_UNIDADE_FIS VARCHAR(200),
		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		SIT_TURMA VARCHAR(30),
		TURMA VARCHAR(40),
		DISCIPLINA VARCHAR(20),
		COD_DOCENTE VARCHAR(20),
		CH_ALOCADA 
		NIVEL VARCHAR(30),
		NOME_DISICPLINA VARCHAR(150),
		CURSO VARCHAR(20),
		NOME_CURSO VARCHAR(100),
		QTD_ALUNOS INT
	)

  INSERT INTO #TEMP      
  SELECT T.UNIDADE_RESPONSAVEL    AS [UNIDADE_ENSINO],    
  UE.NOME_COMP       AS [NOME_UNIDADE_ENS],    
  T.FACULDADE        AS [UNIDADE_FISICA],    
  UF.NOME_COMP       AS [NOME_UNIDADE_FIS],    
  T.ANO         AS [ANO],    
  T.SEMESTRE        AS [SEMESTRE],    
  T.SIT_TURMA        AS [SIT_TURMA],    
  T.TURMA         AS [TURMA],    
  T.DISCIPLINA       AS [DISCIPLINA],    
  isnull(T.NIVEL,'')      AS [NIVEL],    
  LTRIM(RTRIM(D.NOME))         AS [NOME_DISCIPLINA],    
  ISNULL(T.CURSO,'')         AS [CURSO],    
  ISNULL(C.NOME,'')         AS [NOME_CURSO],  
  ISNULL(( SELECT COUNT(DISTINCT M.ALUNO) FROM LY_HISTMATRICULA M   
   WHERE M.TURMA = T.TURMA AND M.DISCIPLINA = T.DISCIPLINA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE AND M.SITUACAO_HIST NOT IN ('Cancelado','Trancado')),0) AS QTD_ALUNOS        
FROM LY_TURMA T    
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = T.DISCIPLINA    
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = T.UNIDADE_RESPONSAVEL    
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE    
LEFT JOIN LY_CURSO C ON C.CURSO = T.CURSO    
WHERE  ((@P_ANO IS NOT NULL AND T.ANO = @P_ANO) OR @P_ANO IS NULL)    
AND ((@P_SEMESTRE IS NOT NULL AND T.SEMESTRE = @P_SEMESTRE) OR @P_SEMESTRE IS NULL)    
AND ((@P_FACULDADE IS NOT NULL AND T.FACULDADE = @P_FACULDADE) OR @P_FACULDADE IS NULL)     
AND ((@P_TIPO_CURSO IS NOT NULL AND C.TIPO = @P_TIPO_CURSO) OR @P_TIPO_CURSO IS NULL)      
AND ((@P_CURSO IS NOT NULL AND T.CURSO = @P_CURSO) OR @P_CURSO IS NULL)    
AND ((@P_TURNO IS NOT NULL AND T.TURNO = @P_TURNO) OR @P_TURNO IS NULL)      
AND ((@P_CURRICULO IS NOT NULL AND T.CURRICULO = @P_CURRICULO) OR @P_CURRICULO IS NULL)       
    



--UPDATE T SET T.QTD_ALUNOS = (SELECT COUNT(DISTINCT M.ALUNO) 
--							FROM LY_MATRICULA M 
--							WHERE M.SUBTURMA1 = T.TURMA 
--							AND M.DISCIPLINA = T.DISCIPLINA 
--							AND M.ANO = T.ANO 
--							AND M.SEMESTRE = T.SEMESTRE
--							AND M.SIT_MATRICULA NOT IN ('Cancelado','Trancado'))
--FROM #TEMP T
--WHERE T.QTD_ALUNOS = 0


SELECT * FROM #TEMP
ORDER BY 1,3,9,8

SET NOCOUNT OFF      
      
END 

delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_SP_csvListaTurmas'
and IDENTIFICACAO_CODIGO = '0002'
go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_SP_csvListaTurmas' NOME
, '0002' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2018-09-18' DATA_CRIACAO
, 'ListaNG - Lista de Turmas por Período Letivo - Correção de Performance (Subturmas)' OBJETIVO
, 'Jéssica Cirqueira' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
go 