USE LYCEUM
GO

UPDATE C
SET USA_SERIE_IDEAL = 'S'
FROM LY_CURSO C
WHERE TIPO = 'GRADUACAO'
AND USA_SERIE_IDEAL = 'N'
GO


UPDATE PM SET PM.SERIE_CALCULO = PM.SERIE_IDEAL
FROM LY_PRE_MATRICULA PM
JOIN LY_ALUNO A ON A.ALUNO = PM.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE (PM.SERIE_IDEAL <> PM.SERIE_CALCULO OR PM.SERIE_CALCULO IS NULL)
AND C.TIPO = 'GRADUACAO'
GO