USE LYCEUM
GO

UPDATE T SET T.FORMULA_MF1 = D.FORMULA_MF1
			, T.FORMULA_MF2 = D.FORMULA_MF2
			, T.FORMULA_CA1 = D.FORMULA_CA1
			, T.FORMULA_CA2 = D.FORMULA_CA2
			, T.CONCEITO_MIN_1 = D.CONCEITO_MIN_1
			, T.CONCEITO_MIN_2 = D.CONCEITO_MIN_2
			, T.CONCEITO_MIN_EX = D.CONCEITO_MIN_EX 
--SELECT t.* 
FROM LY_TURMA T
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = T.DISCIPLINA
JOIN LY_CURSO C ON C.CURSO = T.CURSO
WHERE T.FORMULA_MF1 IS NULL AND T.FORMULA_MF2 IS NULL			--TURMA SEM FORMULAS
AND D.FORMULA_MF1 IS NOT NULL AND D.FORMULA_MF2 IS NOT NULL		--DISCIPLINA POSSUI FORMULAS
AND T.ANO = 2017 AND T.SEMESTRE = 1								--SEMESTRE 2017.1 
AND T.CURSO <> '722'											--QUE NÃO SEJAM DO CURSO DE MEDICINA
AND T.SIT_TURMA = 'Aberta'										--TURMA TEM QUE ESTAR ABERTA
AND C.TIPO = 'GRADUACAO'										--APENAS CURSOS DE GRADUACAO
AND (D.CATEGORIA_ENTURMACAO <> 'DIGITAL' OR D.CATEGORIA_ENTURMACAO IS NULL) --NAO É DISCIPLINA DIGITAL
AND EXISTS (SELECT TOP 1 1 FROM LY_MATRICULA M 
            WHERE M.DISCIPLINA = T.DISCIPLINA 
            AND m.TURMA = t.TURMA 
            AND m.ANO = t.ano 
            AND m.SEMESTRE = t.SEMESTRE) 						--POSSUI ALUNO MATRICULADO
GO