USE LYCEUM
GO

ALTER VIEW VW_MOVIMENTO_CAIXA      
AS      
SELECT A.ALUNO, A.NOME_COMPL, C.RESP, R.TITULAR, C.COBRANCA,         
       LC.LANC_CRED, IC.VALOR, LC.TIPO_PAGAMENTO, LC.TIPO_CRED, LC.BOLETO, LC.DT_CREDITO,       
       CC.USUARIO_LYC, CC.USUARIO_WIN, CC.DATA_ABERTURA, CC.VALOR_ABERTURA, CC.DATA_FECHAMENTO,       
       LC.BANCO, LC.AGENCIA, LC.CONTA_BANCO, LC.SERIE, LC.NUMERO, CC.HORA_ABERTURA, CC.HORA_FECHAMENTO,      
       A.UNIDADE_FISICA, U.NOME_COMP, CUR.FACULDADE, USU.NOME        
FROM LY_ALUNO A           
  JOIN LY_COBRANCA  C ON C.ALUNO  = A.ALUNO           
  JOIN LY_RESP_FINAN R ON C.RESP = R.RESP         
  JOIN LY_ITEM_CRED  IC ON IC.COBRANCA = C.COBRANCA           
  JOIN LY_LANC_CREDITO  LC ON LC.LANC_CRED = IC.LANC_CRED           
  JOIN LY_CONTROLE_CAIXA CC ON CC.ID_ABERTURA = LC.ID_ABERTURA       
  LEFT JOIN LY_UNIDADE_FISICA U ON U.UNIDADE_FIS = A.UNIDADE_FISICA     
  JOIN LY_CURSO CUR ON CUR.CURSO = A.CURSO  
  JOIN HD_USUARIO USU ON USU.USUARIO = CC.USUARIO_LYC  
WHERE IC.TIPODESCONTO IS NULL      
  AND IC.TIPO_ENCARGO IS NULL      
   AND LC.ID_ABERTURA IS NOT NULL  
   AND (LC.TIPO_PAGAMENTO <> 'BANCO' OR (LC.TIPO_PAGAMENTO = 'BANCO' AND LC.BANCO_DEPOSITO IS NOT NULL)) 
   AND ((0 > (SELECT SUM(VALOR) FROM LY_ITEM_CRED WHERE LANC_CRED = IC.LANC_CRED))
	or (0 = (SELECT SUM(VALOR) FROM LY_ITEM_CRED WHERE LANC_CRED = IC.LANC_CRED)
	--or (EXISTS (SELECT 1 FROM LY_ITEM_CRED WHERE LANC_CRED = IC.LANC_CRED AND VALOR < 0 AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL)) 
	AND NOT EXISTS (SELECT 1 FROM VW_LANC_CREDITO_REMOVIDO WHERE LANC_CRED = IC.LANC_CRED)))
 GO
 
 
DELETE FROM LY_CUSTOM_CLIENTE
WHERE NOME = 'VW_MOVIMENTO_CAIXA'
AND IDENTIFICACAO_CODIGO = '0002'
GO

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'VW_MOVIMENTO_CAIXA' NOME
, '0002' IDENTIFICAO_CODIGO
, 'Fabio, Miguel' AUTOR
, CONVERT(VARCHAR(10),GETDATE(),121) DATA_CRIACAO
, 'Correção de VIEW' OBJETIVO
, 'Tesouraria' SOLICITADO_POR
, 'S' ATIVO
, 'Relatório' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO