USE LYCEUM
GO

--select p.end_municipio,p.municipio_nasc, a.ALUNO, a.UNIDADE_FISICA
UPDATE p SET p.MUNICIPIO_NASC = p.END_MUNICIPIO
FROM  LY_PESSOA P
INNER JOIN LY_ALUNO A ON A.PESSOA=P.PESSOA
WHERE 1=1
--AND NOT EXISTS(SELECT 1 FROM   HD_MUNICIPIO MU WHERE MU.MUNICIPIO =P.END_MUNICIPIO)
AND NOT EXISTS  (SELECT 1 FROM   HD_MUNICIPIO MU WHERE MU.MUNICIPIO = P.MUNICIPIO_NASC)
AND (P.MUNICIPIO_NASC IS NULL OR P.MUNICIPIO_NASC = '')
GO