USE LYCEUM
GO


--IDENTIFICANDO CASOS
SELECT ALUNO,LANC_DEB,ANO,SEMESTRE 
INTO LYCEUMTEMP..hd_23624_LY_DESCONTO_DEBITO_23out2018
FROM LY_MATRICULA
WHERE LANC_DEB IS NOT NULL AND SIT_MATRICULA IN ('MATRICULADO','APROVADO','REP NOTA','REP FREQ')
AND EXISTS (SELECT 1 FROM LY_DESCONTO_DEBITO 
            WHERE LANC_DEB = LY_MATRICULA.LANC_DEB 
            AND MOTIVO_DESCONTO ='ESTORNO')
            
--APAGANDO DESCONTOS

DELETE FROM LY_ITEM_LANC 
WHERE LANC_DEB IN (
	SELECT LANC_DEB 
	FROM LY_MATRICULA
	WHERE LANC_DEB IS NOT NULL AND SIT_MATRICULA IN ('MATRICULADO','APROVADO','REP NOTA','REP FREQ')
	AND EXISTS (SELECT 1 FROM LY_DESCONTO_DEBITO 
		        WHERE LANC_DEB = LY_MATRICULA.LANC_DEB 
			    AND MOTIVO_DESCONTO ='ESTORNO')
)
AND MOTIVO_DESCONTO = 'ESTORNO' 

DELETE FROM LY_DESCONTO_DEBITO 
WHERE LANC_DEB IN (
	SELECT LANC_DEB 
	FROM LY_MATRICULA
	WHERE LANC_DEB IS NOT NULL AND SIT_MATRICULA IN ('MATRICULADO','APROVADO','REP NOTA','REP FREQ')
	AND EXISTS (SELECT 1 FROM LY_DESCONTO_DEBITO 
		        WHERE LANC_DEB = LY_MATRICULA.LANC_DEB
			    AND MOTIVO_DESCONTO ='ESTORNO')
	)