USE LYCEUM
GO
--BEGIN TRAN
INSERT INTO HD_PADREL
SELECT 'DomSecGeral', 'Lyceum', HR.GRUPORELAT, HR.RELATORIO FROM HD_RELATORIO HR
WHERE NOT EXISTS (SELECT 1 FROM HD_PADREL HP WHERE HP.RELATORIO = HR.RELATORIO AND HP.PADACES = 'DomSecGeral' )
AND GRUPORELAT IN ('Academico','Financeiro')
--ROLLBACK
GO