USE LYCEUM
GO

UPDATE UDC SET TETO_DESCONTO = 0.150000 
FROM LY_USUARIO_DESC_CONC UDC
JOIN HD_PADUSUARIO P ON p.USUARIO = UDC.USUARIO
WHERE P.PADACES IN ('AtendAlunoFTC')
AND CONVERT(NUMERIC(10,2),UDC.TETO_DESCONTO) >= 0.07 
AND CONVERT(NUMERIC(10,2),UDC.TETO_DESCONTO) <= 0.14