USE LYCEUM
GO


select *
into #HD_TABELAITEM
FROM HD_TABELAITEM WHERE TABELA = 'CentroCusto' and 1 = 0

GO

 

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07001','ADMINISTRACAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07002','CIENCIAS CONTABEIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07003','DIREITO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07004','JORNALISMO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07005','PEDAGOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07006','PUBLICIDADE E PROPAGANDA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07007','TURISMO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07008','CINEMA E VIDEO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07009','CIENCIAS ECONOMICAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07010','RADIO E TV')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07011','HIPERMIDIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','07012','RELACOES PUBLICAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08001','BIOMEDICINA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08002','CIENCIAS BIOLOGICAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08003','EDUCACAO FISICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08004','ENFERMAGEM')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08005','FARMACIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08006','FISIOTERAPIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08007','MEDICINA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08008','MEDICINA VETERINARIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08009','NUTRICAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08010','ODONTOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','08011','PSICOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09001','ENGENHARIA AMBIENTAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09002','ENGENHARIA CIVIL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09003','ENGENHARIA DE PRODUCAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09004','ENGENHARIA DE PRODUCAO QUIMICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09005','ENGENHARIA ELETRICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09006','ENGENHARIA ELETRICA - AUTOMACAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09007','ENGENHARIA ELETRICA - TELECOMUNICACAO E COMPUTACAO ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09008','ENGENHARIA MECATRONICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09009','ENGENHARIA QUIMICA - PETROLEO E GAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09010','CIENCIAS AERONAUTICAS - (PILOTO COMERCIAL)')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09011','DESIGN DE PRODUTO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09012','DESIGN MODA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09013','SISTEMAS DE INFORMACAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','09014','ARQUITETURA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10001','EDUCACAO FISICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10002','PEDAGOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10003','BIOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10004','CIENCIAS NATURAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10005','GEOGRAFIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10006','HISTORIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10007','LETRAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10008','MATEMATICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10009','NORMAL SUPERIOR/SERIES INICIAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10010','FISICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','10011','QUIMICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','11001','OUVINTES')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15001','ANALISES CLINICAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15002','ATIVIDADE FISICA E SAUDE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15003','AUDITORIA DOS SERVICOS EM SAUDE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15004','AUDITORIA EM SAUDE ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15005','AVALIACAO PSICOLOGICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15006','CIENCIAS DO ESPORTE COM HABILITACAO EM PROMOCAO, REABILITACAO E RECUPERACAO DA SAUDE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15007','EDUCACAO NUTRICIONAL COM ENFASE EM SAUDE PUBLICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15008','ENDODONTIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15009','ENFERMAGEM DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15010','ENFERMAGEM EM CARD E HEMODIN')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15011','ENFERMAGEM EM ESTOMATERAPIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15012','ENFERMAGEM EM ONCOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15013','ENFERMAGEM EM UTI NEONATAL E PEDIATRICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15014','ENFERMAGEM NA URGENCIA E EMERGENCIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15015','ENFERMAGEM NA URGENCIA, EMERGENCIA E UTI')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15017','ENFERMAGEM OBSTETRICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15018','ENFERMAGEM UTI - ADULTO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15019','FARMACIA CLINICA E ATENCAO FARMACEUTICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15020','FARMACIA HOSPITALAR')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15021','FISIOLOGIA DO EXERCICIO: AVALIACAO E PRESCRICAO DE EXERCICIOS PARA GRUPOS ESPECIAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15022','FISIOTERAPIA DERMATOFUNCIONAL E ESTETICA COSMETOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15023','FISIOTERAPIA HOSP ENT ORTOPED')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15024','FISIOTERAPIA INTENSIVA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15025','FISIOTERAPIA ORTOPEDICA E TRAUMA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15026','IMPLANTODONTIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15027','NEUROPSICOLOGICA E EDUCACAO ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15028','NUTRICAO CLINICA E FUNCIONAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15029','ONCOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15030','ORTODONTIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15031','PROTESE DENTARIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15032','PSICOLOGIA DO TRANSITO E DA MOBILIDADE HUMANA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15033','PSICOLOGIA ORGANIZ E DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15034','PSICOPEDAGOGIA CLINICA, HOSPITALAR E INSTITUCIONAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15035','SAUDE COLETIVA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15036','SAUDE COLETIVA – HABILITACAO SANITARISTA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15037','SAUDE COLETIVA COM ENFASE EM PSF ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15038','SAUDE DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15039','SAUDE DO TRABALHO E ENFERMAGEM DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15040','SAUDE ESTETICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15041','SAUDE MATERNO INFANTIL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15042','SAUDE MENTAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15043','SAUDE MENTAL COM ENFASE EM DEPENDENCIA QUIMICA, FAMILIA E COMUNIDADE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15044','SAUDE MENTAL E CONTEXTO SOCIAL: ATENCAO AOS USUARIOS DE SUBST. PSIC.')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15045','TREINAMENTO FUNCIONAL: DA REABILITACAO AO TREINAMENTO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15046','UTI ADULTO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15047','EDUCACAO, QUALIDADE DE VIDA E SAUDE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15048','ADMINISTRACAO HOSPITALAR')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','15049','BIOLOGIA MOLECULAR DAS DOENCAS E TERAPIAS CELULARES')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16001','AUDITORIA E PERICIA AMBIENTAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16002','AUDITORIA E PERICIA CONTABIL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16003','COACHING E GESTAO DE CARREIRAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16004','COMUNICACAO E MARKETING EM REDES SOCIAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16005','COMUNICACAO E MARKETING ESTRATEGICO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16006','COMUNICACAO, MKT E MIDIAS INTERATIVAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16007','CONTROLADORIA E FINANCAS ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16008','ESTETICA E COSMETOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16009','GESTAO AMBIENTAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16010','GESTAO DE EMPREENDIMENTOS CRIATIVOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16011','GESTAO DE MARKETING ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16012','GESTAO DE PESSOAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16013','GESTAO DE PESSOAS COM ENFASE EM PSICOLOGIA ORGANIZACIONAL ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16014','GESTAO DE PROJETOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16015','GESTAO DE TECNOLOGIA DA INFORMACAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16016','GESTAO DE UNIDADES DE ALIMENTACAO E NUTRICAO COM ENFASE EM MERENDA ESCOLAR E GASTRONOMIA ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16017','GESTAO EM SAUDE E SEGURANCA NO TRABALHO ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16018','GESTAO ESTRATEGICA EM LOGISTICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16019','GESTAO ESTRATEGICA EMPRESARIAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16020','GESTAO FISCAL E TRIBUTARIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16021','GESTAO PUBLICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16022','GESTAO PUBLICA E GOVERNAMENTAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16023','LOGISTICA EMPRESARIAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16024','MARKETING ESTRATEGICO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16025','PLANEJAMENTO, GESTAO E CONTROLE DE OBRAS ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16026','PLANEJAMENTO E CONSULTORIA EM TURISMO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16027','CONTABILIDADE GERENCIAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16028','GESTAO RECURSOS HUMANOS ETICA E COMUNICACAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16029','GESTAO DE AGRONEGOCIOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16030','ADMINISTRACAO E ORGANIZACAO DE EVENTOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16031','GESTAO DA INFORMACAO PARA MULTIMEIOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16032','GESTAO IMOBILIARIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16033','GESTAO ESTRATEGICA DE COMUNICACAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','16034','LIDERANCA ESTRATEGICA E COACHING')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17001','DOCENCIA DO ENSINO SUPERIOR')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17002','EDUCACAO INCLUSIVA E ESPECIAL COM ENFASE EM LIBRAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17003','EDUCACAO INCLUSIVA E POLITICAS PUBLICAS ')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17004','METODOLOGIA DO ENSINO SUPERIOR')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17005','PRATICAS PSICOSSOCIAIS E EDUCACAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17006','PSICOPEDAGOGIA CLINICA, HOSPITALAR E INSTITUCIONAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17007','SERVICOS SOCIAIS, SEG SOCIAL E POLITICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17008','GESTAO EDUCACIONAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17009','PEDAGOGIAS DIFERENCIADAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17010','COMPETENCIAS EDUCACIONAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17011','MAGISTERIO DO ENSINO FUNDAMENTAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','17012','METODOLOGIA ENSINO DE FILOSOFIA E SOCIOL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18001','DIREITO ADMINISTRATIVO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18002','DIREITO DO TRABALHO E PROCESSO DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18003','DIREITO E PRATICAS TRABALHISTAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18004','DIREITO MATERIAL E PROCESSUAL DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18005','DIREITO MILITAR E SEGURANCA PUBLICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18006','DIREITO PENAL E CRIMINOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18007','DIREITO PUBLICO E PRIVADO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18008','MEDIACAO DE CONFLITOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18009','PERICIA EM ACIDENTES DE TRANSITO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18010','DIREITO TRIBUTARIO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18011','DIREITO PROCESSUAL CIVIL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','18012','DIREITOS HUMANOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19001','SEGURANCA DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19002','MIDIAS E REDES SOCIAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19003','ENGENHARIA DE SEGURANCA DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19004','GOVERNANCA DE TI')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19005','DESENVOLVIMENTO DE SISTEMAS PARA WEB')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19006','ENGENHARIA DAS ESTRUTURAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19007','ENGENHARIA DE AVALIACOES E PERICIAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19008','GESTAO DO MEIO AMBIENTE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19009','RECUPERACAO DE AREAS DEGRADADAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','19010','PERICIA E ACIDENTE DE TRANSITO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20001','GESTAO DE CONTEUDOS EM MIDIAS SOCIAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20002','CAPTACAO DE RECURSOS PARA PROJETOS CULTURAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20003','DIREITO ALTERNATIVO E VISAO CRITICA DO DIREITO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20004','CURSO PRATICO CONTABIL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20005','GRUPO DE CRESCIMENTO EM EDUCACAO EMOCIONAL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20006','EDUCACAO ESPECIAL E INCLUSIVA COM ENFASE EM PEDAGOGIA HOSPITALAR')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20007','DIREITO DE FAMILIA SOBE UM OLHAR PRATICO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20008','MASSOTERAPIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','20009','EXTENSAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21001','ANALISE E DESENVOLVIMENTO DE SISTEMAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21002','DESIGN DE INTERIORES')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21003','DESIGN DE PRODUCAO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21004','GASTRONOMIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21005','GESTAO DE RECURSOS HUMANOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21006','GESTAO FINANCEIRA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21007','GESTAO PUBLICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21008','LOGISTICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21009','NEGOCIOS IMOBILIARIOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21010','RADIOLOGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','21011','SEGURANCA DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','22001','BIOENERGIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23001','AGENTE COMUNITARIO DE SAUDE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23002','ENFERMAGEM')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23003','GERENCIA DE SAUDE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23004','INFORMATICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23005','INFORMATICA PARA INTERNET')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23006','LOGISTICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23007','MEIO AMBIENTE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23008','NUTRICAO E DIETETICA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23009','REABILITACAO DE DEPENDENTES QUIMICOS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','23010','VIGILANCIA DE SAUDE')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','30002','EAD - DISCIPLINAS DIGITAIS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','30003','EAD - CURSO DE GEOGRAFIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','30004','EAD - CURSO DE HISTORIA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','30005','EAD - CURSO DE LETRAS')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','30006','EAD - CURSO DE SEGURANCA DO TRABALHO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','50001','EDUCACAO INFANTIL')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','50002','ENSINO FUNDAMENTAL I')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','50003','ENSINO FUNDAMENTAL II')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','50004','ENSINO MEDIO')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','60001','CURSO DE INGLES')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','91001','RECEITAS FINANCEIRA')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','91007','FUNDAÇÃO FTC')

INSERT INTO #HD_TABELAITEM VALUES ('CentroCusto','91008','ACADEMIA')

 

 

UPDATE HT SET HT.DESCR = T.DESCR
FROM HD_TABELAITEM HT 
JOIN #HD_TABELAITEM T ON T.ITEM = HT.ITEM
WHERE HT.TABELA = 'CentroCusto'
GO
