USE LYCEUM
GO
 
UPDATE P SET P.NOTA_MAX = 10
FROM ly_prova P
JOIN LY_TURMA T ON T.DISCIPLINA = P.DISCIPLINA AND T.TURMA = P.TURMA AND T.ANO = P.ANO AND T.SEMESTRE = T.SEMESTRE 
WHERE 1=1
AND T.ANO = 2016 AND T.SEMESTRE = 0
AND T.FACULDADE IN ('DOM-SSA','DOM-JEQ','DOM-VIC')
GO

UPDATE T SET T.CONCEITO_MIN_1 = 6, T.CONCEITO_MIN_2 = 5, T.CONCEITO_MIN_EX = 0, T.FORMULA_MF2 = 'PF', T.FORMULA_CA2 = 'PF'
FROM LY_TURMA T 
WHERE 1=1
AND T.ANO = 2016 AND T.SEMESTRE = 0
AND T.FACULDADE IN ('DOM-SSA','DOM-JEQ','DOM-VIC')
GO