USE LYCEUM
GO    
    
CREATE VIEW VW_FTC_REGRA_ARRASTO_BOLETO    
AS     
SELECT ALUNO     
FROM LY_ALUNO A    
JOIN LY_CURSO C    
    ON A.CURSO = C.CURSO    
WHERE C.TIPO NOT IN ('ENS BASICO','LINGUAS')    
--AND A.SIT_ALUNO = 'Ativo' 
GO


DELETE FROM LY_CUSTOM_CLIENTE
WHERE NOME = 'VW_FTC_REGRA_ARRASTO_BOLETO'
AND IDENTIFICACAO_CODIGO = '0001'
GO


INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'VW_FTC_REGRA_ARRASTO_BOLETO' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2017-03-31' DATA_CRIACAO
, 'Alteração na regra de arrasto' OBJETIVO
, 'André Britto' SOLICITADO_POR
, 'S' ATIVO
, 'VIEW' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO   