--DROP TABLE #TEMP1

USE LYCEUM
GO

SELECT C.PESSOA, C.CPF, C.CANDIDATO, C.CONCURSO
INTO #TEMP1
FROM LY_CANDIDATO C
WHERE 1 = 1 
AND C.CPF IN (
    SELECT P.CPF FROM LY_PESSOA P
    WHERE 1=1
    GROUP BY P.CPF
    HAVING COUNT(P.PESSOA) >1
)

--SELECT P.PESSOA, C.CANDIDATO
UPDATE C SET C.PESSOA = P.PESSOA
FROM LY_CANDIDATO C
JOIN LY_PESSOA P ON P.CPF = C.CPF
WHERE 1 = 1
AND P.PESSOA NOT IN (SELECT T.PESSOA FROM #TEMP1 T)
AND C.CANDIDATO IN (SELECT T.CANDIDATO FROM #TEMP1 T)


SELECT P.*,T.PESSOA AS PESSOA_DELETADA
INTO LYCEUMTEMP..ly_pessoa_duplic_02fev2017
FROM LY_PESSOA P
JOIN #TEMP1 T ON T.PESSOA = P.PESSOA

--SELECT * 
DELETE FROM LY_FL_PESSOA 
WHERE PESSOA IN (SELECT PESSOA FROM #TEMP1)

DELETE FROM LY_PESSOA
WHERE PESSOA IN (SELECT PESSOA FROM #TEMP1)
AND PESSOA NOT IN (SELECT PESSOA FROM LY_CANDIDATO WHERE PESSOA IN (SELECT PESSOA FROM #TEMP1))
AND PESSOA NOT IN (SELECT PESSOA FROM LY_RESP_FINAN WHERE PESSOA IN (SELECT PESSOA FROM #TEMP1))
AND PESSOA NOT IN (SELECT PESSOA FROM LY_RELACIONAMENTO_PESSOA WHERE PESSOA IN (SELECT PESSOA FROM #TEMP1))
AND PESSOA NOT IN (SELECT PESSOA FROM LY_ALUNO WHERE PESSOA IN (SELECT PESSOA FROM #TEMP1))






SELECT * FROM #temp1 ORDER BY 1
SELECT * FROM ly_pessoa WHERE PESSOA = '10670'