USE LYCEUM
GO

UPDATE lrp
SET lrp.ON_LINE = 'S'
FROM LY_RELACIONAMENTO_PESSOA lrp 
WHERE lrp.PESSOA IN (SELECT PESSOA FROM LY_ALUNO A,LY_CURSO C WHERE A.CURSO = C.CURSO AND C.TIPO = 'ENS BASICO')
AND lrp.ON_LINE = 'N'
GO