use LYCEUM
go

--exec FTC_SP_csvConferePreEMatr '2016',null, NULL, null, null, null, NULL, NULL, 'T'
--exec FTC_SP_csvConferePreEMatr '2016',null, NULL, null, null, null, NULL, NULL, 'S'
--exec FTC_SP_csvConferePreEMatr '2016',null, NULL, null, null, null, NULL, NULL, 'N'
--exec FTC_SP_csvConferePreEMatr '2016',null, NULL, null, null, null, NULL, NULL, NULL

/*

select * from (
			select * 
			from LY_PRE_MATRICULA PM
			JOIN LY_ALUNO A
			JOIN LY_CURSO c
			join LY_DISCIPLINA d
			 
			union
			select 
			from LY_MATRICULA PM
			JOIN LY_ALUNO A
			JOIN LY_CURSO c
			join LY_DISCIPLINA d)
			 
			Sugestão de filtros
			•         Unidade Ensino (pega no curso)
			•         Unidade Física (Pega no aluno)
			•         Curso
			•         Turno
			•         currículo (pega no aluno)
			•         Sit_matricula (montar  Pre-matricula + distinct do campo na ly_matricula )
			•         Sem turma (S ou N)

*/




IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE name = 'FTC_SP_csvConferePreEMatr' AND type = 'P')
DROP PROCEDURE FTC_SP_csvConferePreEMatr
GO

CREATE PROCEDURE dbo.FTC_SP_csvConferePreEMatr   
(    
	@p_ano				T_ANO,
	@p_semestre			T_Semestre2,
	@p_unidade_ensino	T_codigo,
	@p_tipo_curso		T_codigo,
	@p_curso			T_codigo,
	@p_turno			T_codigo,
	@p_curriculo		T_codigo,	
	@p_sit_matricula	T_codigo,
	@p_tem_turma		varchar(1)
)    
AS    
-- [INÍCIO]            
BEGIN    

--## Zerar variavel se vier com branco
If @p_sit_matricula = 'TODAS'
	set @p_sit_matricula = null


SET NOCOUNT ON

select  
				TIPO,
				ALUNO,
				NOME_ALUNO,
				CURSO,
				NOME_CURSO,
				ISNULL(TIPO_CURSO,'')					AS TIPO_CURSO,
				ISNULL(FACULDADE,'')					AS UNIDADE_ENSINO,
				ISNULL(NOME_UNIDADE_ENSINO,'')			as NOME_UNIDADE_ENSINO,
				TURNO,
				CURRICULO,
				ISNULL(CONVERT(VARCHAR,SERIE),'')		AS SERIE_ALUNO,
				DISCIPLINA,
				NOME_DISCIPLINA,
				ANO,
				SEMESTRE,
				ISNULL(TURMA,'')						AS TURMA,
				ISNULL(SUBTURMA1,'')					AS SUBTURMA1,
				ISNULL(SUBTURMA2,'')					AS SUBTURMA2,
				ISNULL(SIT_DETALHE,'')					AS SIT_DETALHE,
				ISNULL(SIT_MATRICULA,'')				AS SIT_MATRICULA,
				ISNULL(CONVERT(VARCHAR,SERIE_IDEAL),'') AS SERIE_IDEAL_DISCIPLINA,
				ISNULL(CONFIRMADA,'')					AS CONFIRMADA,
				ISNULL(DISPENSADA,'')					AS DISPENSADA,
				ISNULL(CONVERT(VARCHAR,DT_INSERCAO,103),'')		AS DATA_INSERCAO,
				ISNULL(CONVERT(VARCHAR,DT_ULTALT,103),'')			AS DATA_ULTIMA_ALTERACAO,
				ISNULL(CONVERT(VARCHAR,DT_CONFIRMACAO,103),'')		AS DATA_CONFIRMACAO,
				ISNULL(CONVERT(VARCHAR,DT_MATRICULA,103),'')		AS DATA_MATRICULA,
				ISNULL(DISPENSADA,'')					AS GRUPO_ELETIVA,
				ISNULL(CONVERT(VARCHAR,LANC_DEB),'')	AS LANC_DEB,
				ISNULL(MANUAL,'')						AS MANUAL,
				ISNULL(OBS,'')							AS OBS,
				ISNULL(MENS_ERRO,'')					AS MENS_ERRO 
INTO #TEMP_MATRICULA
from (
			SELECT 
				'PRÉ-MATRÍCULA' AS TIPO,
				A.ALUNO,
				A.NOME_COMPL	AS NOME_ALUNO,
				A.CURSO,
				C.NOME			AS NOME_CURSO,
				C.TIPO			AS TIPO_CURSO,
				C.FACULDADE,
				ue.NOME_COMP	as NOME_UNIDADE_ENSINO,
				A.TURNO,
				A.CURRICULO,
				A.SERIE,
				PM.DISCIPLINA,
				D.NOME			AS NOME_DISCIPLINA,
				PM.ANO,
				PM.SEMESTRE,
				PM.TURMA,
				PM.SUBTURMA1,
				PM.SUBTURMA2,
				PM.SIT_DETALHE,
				'Pré-Matriculado'		AS SIT_MATRICULA,
				PM.SERIE_IDEAL,
				PM.CONFIRMADA,
				PM.DISPENSADA,
				PM.DT_INSERCAO,
				PM.DT_ULTALT,
				PM.DT_CONFIRMACAO,
				null AS dt_matricula,
				PM.GRUPO_ELETIVA,
				PM.LANC_DEB,
				PM.MANUAL,
				PM.OBS,
				PM.MENS_ERRO 
			from LY_PRE_MATRICULA PM
			JOIN VW_ALUNO A
				on pm.aluno = a.aluno
			JOIN VW_CURSO c
				on a.CURSO = c.curso
			join LY_DISCIPLINA d
				on pm.DISCIPLINA = d.DISCIPLINA
			LEFT JOIN VW_UNIDADE_ENSINO ue 
				ON c.FACULDADE = ue.FACULDADE
			WHERE 1 = 1
			and pm.ano		= @p_ano
			and pm.SEMESTRE	= isnull(@p_semestre,semestre)
			AND C.FACULDADE = ISNULL(@P_UNIDADE_ENSINO,C.FACULDADE)
			AND C.TIPO		= ISNULL(@P_TIPO_CURSO, C.TIPO)
			AND A.CURSO		= ISNULL(@P_CURSO,A.CURSO)
			AND A.TURNO		= ISNULL(@P_TURNO,A.TURNO)
			AND A.CURRICULO = ISNULL(@p_curriculo,A.CURRICULO)

			union ALL
			
			SELECT 
				'MATRÍCULA' AS TIPO,
				A.ALUNO,
				A.NOME_COMPL	AS NOME_ALUNO,
				A.CURSO,
				C.NOME			AS NOME_CURSO,
				C.TIPO			AS TIPO_CURSO,
				C.FACULDADE,
				ue.NOME_COMP	as NOME_UNIDADE_ENSINO,
				A.TURNO,
				A.CURRICULO,
				A.SERIE,
				M.DISCIPLINA,
				D.NOME			AS NOME_DISCIPLINA,
				M.ANO,
				M.SEMESTRE,
				M.TURMA,
				M.SUBTURMA1,
				M.SUBTURMA2,
				M.SIT_DETALHE,
				m.SIT_MATRICULA,
				NULL				AS SERIE_IDEAL,
				NULL				AS CONFIRMADA,
				NULL				AS DISPENSADA,
				M.DT_INSERCAO,
				M.DT_ULTALT,
				NULL				AS DT_CONFIRMACAO,
				M.DT_MATRICULA,
				M.GRUPO_ELETIVA,
				M.LANC_DEB,
				NULL				AS MANUAL,
				M.OBS,
				NULL				AS MENS_ERRO 
			from LY_MATRICULA M
			JOIN VW_ALUNO A
				on m.aluno = a.aluno
			JOIN VW_CURSO c
				on a.CURSO = c.curso
			join LY_DISCIPLINA d
				on m.DISCIPLINA = d.DISCIPLINA
			LEFT JOIN VW_UNIDADE_ENSINO ue 
				ON c.FACULDADE = ue.FACULDADE
			WHERE 1 = 1
			and m.ano		= @p_ano
			and m.SEMESTRE	= isnull(@p_semestre,semestre)
			AND C.FACULDADE = ISNULL(@P_UNIDADE_ENSINO,C.FACULDADE)
			AND C.TIPO		= ISNULL(@P_TIPO_CURSO, C.TIPO)
			AND A.CURSO		= ISNULL(@P_CURSO,A.CURSO)
			AND A.TURNO		= ISNULL(@P_TURNO,A.TURNO)
			AND A.CURRICULO = ISNULL(@p_curriculo,A.CURRICULO)

) A
WHERE 1 = 1
AND TIPO	= ISNULL(@p_sit_matricula,tipo)		


IF @p_tem_turma = 'S'
	BEGIN
		SELECT * FROM #TEMP_MATRICULA
		WHERE TURMA <> ''
		order by UNIDADE_ENSINO, curso, turno, CURRICULO, SERIE_ALUNO
	END
ELSE
	IF @p_tem_turma = 'N'
		BEGIN
			SELECT * FROM #TEMP_MATRICULA
			WHERE TURMA = ''
			order by UNIDADE_ENSINO, curso, turno, CURRICULO, SERIE_ALUNO
		END
	ELSE 
		BEGIN
			SELECT * FROM #TEMP_MATRICULA
			order by UNIDADE_ENSINO, curso, turno, CURRICULO, SERIE_ALUNO
		END

SET NOCOUNT OFF

END            
-- [FIM]    
GO  


--##
--## PARAMETRIZAÇÃO/CADASTRO DA LISTA NO LYCEUM
--##

DECLARE @V_CONSULTA_DINAMICA INT
DECLARE @V_NOME_CONSULTA_DINAMICA varchar(100)

-- Colocar nome da lista (que será apresentada no combo)
set @V_NOME_CONSULTA_DINAMICA ='Custom - Validação Pré-Matrícula e Matrícula'

-- Consulta ID da Lista
SELECT @V_CONSULTA_DINAMICA = ID FROM LY_CONSULTA_DINAMICA WHERE TITULO = @V_NOME_CONSULTA_DINAMICA

-- armazena padrões de acesso
SELECT PADACES
INTO #TEMP_CONSULTA_DINAMICA
FROM LY_CONSULTA_DINAMICA_PADACES WHERE ID = @V_CONSULTA_DINAMICA


DELETE LY_CONSULTA_DINAMICA_PADACES WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA

BEGIN

IF NOT EXISTS(SELECT 1 FROM LY_CONSULTA_DINAMICA C WHERE C.TITULO = @V_NOME_CONSULTA_DINAMICA)
INSERT INTO LY_CONSULTA_DINAMICA(TITULO, TIPO, STORED_PROCEDURE)
VALUES(@V_NOME_CONSULTA_DINAMICA,'CSV','sp:FTC_SP_csvConferePreEMatr(@p_ano@,@p_semestre@,@p_unidade_ensino@,@p_tipo_curso@,@p_curso@,@p_turno@,@p_curriculo@,@p_sit_matricula@,@p_tem_turma@)')

SET @V_CONSULTA_DINAMICA = @@IDENTITY

-- Insere padrões de acesso
INSERT INTO LY_CONSULTA_DINAMICA_PADACES (ID_CONSULTA_DINAMICA, PADACES)
SELECT @V_CONSULTA_DINAMICA, PADACES FROM #TEMP_CONSULTA_DINAMICA

-- Insere parametros

	--@p_ano				T_ANO,
	--@p_semestre			T_Semestre2,
	--@p_unidade_ensino	T_codigo,
	--@p_tipo_curso		T_codigo,
	--@p_curso			T_codigo,
	--@p_turno			T_codigo,
	--@p_curriculo		T_codigo,	
	--@p_sit_matricula	T_codigo,
	--@p_tem_turma		varchar(1)

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 1, 'p_ano', 5, 'Ano', 'S', 'SELECT DISTINCT ANO AS CODIGO, (''ANO: '' + convert(varchar,ANO)) AS DESCRICAO FROM LY_PERIODO_LETIVO ORDER BY ANO DESC', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 2, 'p_semestre', 5, 'Período', 'N', 'SELECT DISTINCT PERIODO AS CODIGO, (''PERÍODO: '' + convert(varchar,PERIODO)) AS DESCRICAO FROM LY_PERIODO_LETIVO WHERE ANO = ISNULL(@p_ano@,ANO) ORDER BY PERIODO', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 3, 'p_unidade_ensino', 5, 'Unidade Ensino', 'N', 'Select unidade_ens as codigo, nome_comp as descricao from ly_unidade_ensino order by unidade_ens', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 4, 'p_tipo_curso', 5, 'Tipo de Curso', 'N', 'Select tipo as codigo, descricao from ly_tipo_curso order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 5, 'p_curso', 5, 'Curso', 'N', 'Select Curso as codigo, nome as descricao from ly_curso where tipo = isnull(@p_tipo_curso@,tipo) order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 6, 'p_turno', 5, 'Turno', 'N', 'Select turno as codigo, descricao from ly_turno order by turno', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 7, 'p_curriculo', 5, 'Curriculo', 'N', 'Select Curriculo as CODIGO, (''Currículo: '' + convert(varchar,Curriculo)) AS DESCRICAO FROM LY_curriculo WHERE curso = ISNULL(@p_curso@,curso) AND turno = ISNULL(@p_turno@,turno) and dt_extincao is null ORDER BY curriculo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 8, 'p_sit_matricula', 5, 'Situação Matrícula', 'N', 'Select ''TODAS'' as codigo, ''TODAS'' as descricao union select ''PRÉ-MATRÍCULA'' as codigo, ''PRÉ-MATRÍCULA'' as descricao union select ''MATRÍCULA'' as codigo, ''MATRÍCULA'' as descricao order by 1 desc', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 9, 'p_tem_turma', 5, 'Tem Turma', 'N', 'Select ''T''  as codigo, ''TODOS OS CASOS'' as descricao union select ''S'' as codigo, ''SIM'' as descricao union select ''N'' as codigo, ''NÃO'' as descricao order by 1', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

--SELECT * FROM LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA
--SELECT * FROM LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA

drop table  #TEMP_CONSULTA_DINAMICA

END
GO

delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_SP_csvConferePreEMatr'
and IDENTIFICACAO_CODIGO = 'LISTA NG'
go


INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_SP_csvConferePreEMatr' NOME
, 'LISTA NG' IDENTIFICAO_CODIGO
, 'Raul' AUTOR
, '2016-09-14' DATA_CRIACAO
, 'Lista NG - Consulta de Pré-Matrícula e Matrícula' As OBJETIVO
, '' SOLICITADO_POR
, 'S' ATIVO
, 'LISTA NG' TIPOCOMPONENTE
, 'FTC' TIPO
, 'FTC' CLIENTE
go
