--SELECT C.CURSO+' - '+C.NOME AS CURSO,S.TURNO,S.SERIE,S.DESCRICAO,S.SERVICO,S.SERVICO_CRED,S.CURRICULO,UE.NOME_COMP,G.DISCIPLINA,D.CREDITOS FROM LY_SERIE S
--JOIN LY_CURSO C ON C.CURSO=S.CURSO
--JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS=C.FACULDADE
--JOIN LY_GRADE G ON G.CURRICULO=S.CURRICULO AND G.CURSO=S.CURSO AND G.TURNO=S.TURNO AND G.SERIE_IDEAL=S.SERIE
--JOIN LY_DISCIPLINA D ON D.DISCIPLINA=G.DISCIPLINA AND D.FACULDADE=C.FACULDADE
--WHERE S.SERVICO IS NULL AND S.SERVICO_CRED IS  NULL
--AND C.ATIVO='S'
--AND C.NOME NOT LIKE'Pronatec%'


--SELECT	C.FACULDADE AS UNIDADE,C.CURSO, S.TURNO,C.NOME AS NOME_CURSO,  C.TIPO AS TIPO_CURSO, 
--		CU.CURRICULO, CU.OBS AS DESCRICAO_CURRICULO, S.SERIE,S.SERVICO_CRED FROM LY_SERIE S
--JOIN LY_CURRICULO CU ON CU.CURSO = S.CURSO AND CU.CURRICULO = S.CURRICULO AND CU.TURNO = S.TURNO
--JOIN LY_CURSO C ON C.CURSO = CU.CURSO 
--WHERE 1=1 
--AND S.SERVICO_CRED IS NULL
--AND CU.DT_EXTINCAO IS NULL
--AND C.ATIVO = 'S'
--AND C.TIPO = 'GRADUACAO'
--AND EXISTS (SELECT 1 FROM VW_MATRICULA_E_PRE_MATRICULA VW JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO WHERE A.CURSO = CU.CURSO AND A.CURRICULO = CU.CURRICULO AND A.TURNO = CU.TURNO)
--ORDER BY 1,2,8

SELECT	C.FACULDADE AS UNIDADE,C.CURSO, S.TURNO,C.NOME AS NOME_CURSO, C.TIPO AS TIPO_CURSO, 
		CU.CURRICULO, CU.OBS AS DESCRICAO_CURRICULO, S.SERIE,S.SERVICO_CRED,
		SP.ANO, SP.PERIODO,SP.CUSTO_UNITARIO
FROM LY_SERIE S
JOIN LY_CURRICULO CU ON CU.CURSO = S.CURSO AND CU.CURRICULO = S.CURRICULO AND CU.TURNO = S.TURNO
JOIN LY_CURSO C ON C.CURSO = CU.CURSO
JOIN LY_VALOR_SERV_PERIODO SP ON S.SERVICO_CRED = SP.SERVICO
WHERE 1=1 
AND S.SERVICO_CRED IS NOT NULL
AND CU.DT_EXTINCAO IS NULL
AND C.ATIVO = 'S'
AND C.TIPO = 'GRADUACAO'
AND SP.ANO ='2018'
AND SP.PERIODO ='2'
AND NOT EXISTS (SELECT 1 FROM LY_VALOR_SERV_PERIODO V WHERE V.SERVICO = S.SERVICO_CRED AND V.ANO = 2017 AND V.PERIODO = 1)
AND EXISTS (SELECT 1 FROM VW_MATRICULA_E_PRE_MATRICULA VW JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO WHERE A.CURSO = CU.CURSO AND A.CURRICULO = CU.CURRICULO AND A.TURNO = CU.TURNO)
ORDER BY 1,2,8