
SELECT a.aluno, 
		a.NOME_COMPL, 
		a.SERIE AS SERIE_ALUNO, 
		pm.DISCIPLINA, 
		D.CREDITOS,
		pm.SERIE_IDEAL AS SERIE_PRE_MATRICULA, 
		G.SERIE_IDEAL AS SERIE_EQUIVALENTE, 
		ISNULL((SELECT CUSTO_UNITARIO FROM LY_VALOR_SERV_PERIODO v
		JOIN LY_SERIE s ON s.SERVICO_CRED = v.SERVICO 
		 WHERE V.ANO = PM.ANO AND V.PERIODO = PM.SEMESTRE AND S.CURSO = A.CURSO 
		 AND S.CURRICULO = A.CURRICULO AND S.TURNO = A.TURNO AND S.SERIE = PM.SERIE_CALCULO),0) AS VALOR_SERV_PERIODO_PRE_MAT,
		ISNULL((SELECT CUSTO_UNITARIO FROM LY_VALOR_SERV_PERIODO v
		JOIN LY_SERIE s ON s.SERVICO_CRED = v.SERVICO 
		 WHERE V.ANO = PM.ANO AND V.PERIODO = PM.SEMESTRE AND S.CURSO = A.CURSO 
		 AND S.CURRICULO = A.CURRICULO AND S.TURNO = A.TURNO AND S.SERIE = PM.SERIE_CALCULO),0)*D.CREDITOS AS VALOR_DISCIPLINA_PRE_MAT,
		ISNULL((SELECT CUSTO_UNITARIO FROM LY_VALOR_SERV_PERIODO v
		JOIN LY_SERIE s ON s.SERVICO_CRED = v.SERVICO 
		 WHERE V.ANO = PM.ANO AND V.PERIODO = PM.SEMESTRE AND S.CURSO = A.CURSO 
		 AND S.CURRICULO = A.CURRICULO AND S.TURNO = A.TURNO AND S.SERIE = G.SERIE_IDEAL),0) AS VALOR_SERV_PERIODO_GRADE,
		 ISNULL((SELECT CUSTO_UNITARIO FROM LY_VALOR_SERV_PERIODO v
		JOIN LY_SERIE s ON s.SERVICO_CRED = v.SERVICO 
		 WHERE V.ANO = PM.ANO AND V.PERIODO = PM.SEMESTRE AND S.CURSO = A.CURSO 
		 AND S.CURRICULO = A.CURRICULO AND S.TURNO = A.TURNO AND S.SERIE = G.SERIE_IDEAL),0)*D.CREDITOS AS VALOR_DISCIPLINA_GRADE
FROM LY_PRE_MATRICULA pm
JOIN LY_ALUNO a ON a.ALUNO = pm.ALUNO
JOIN LY_GRADE G ON G.FORMULA_EQUIV LIKE '%'+PM.DISCIPLINA+'%' AND G.CURSO = A.CURSO AND G.CURRICULO = A.CURRICULO AND G.TURNO = A.TURNO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = PM.DISCIPLINA
WHERE 1 = 1
AND pm.DISCIPLINA NOT IN (SELECT g.DISCIPLINA FROM ly_grade g WHERE g.CURSO = a.CURSO AND g.TURNO = a.TURNO AND g.CURRICULO = a.CURRICULO)
AND pm.DISCIPLINA NOT IN (SELECT g.DISCIPLINA FROM LY_GRADE_ELETIVAS g WHERE g.CURSO = a.CURSO AND g.TURNO = a.TURNO AND g.CURRICULO = a.CURRICULO)
AND pm.SERIE_IDEAL <> G.SERIE_IDEAL 
ORDER BY 1