SELECT	VW.ANO, 
		VW.SEMESTRE,
		A.ALUNO,
		A.CURSO,
		A.TURNO,
		A.CURRICULO,
		A.NOME_COMPL, 
		A.SERIE AS SERIE_ALUNO,
		G.SERIE_IDEAL AS SERIE_GRADE, 
		VW.SERIE_CALCULO, 
		A.UNIDADE_FISICA, 
		VW.DISCIPLINA,
		ISNULL((SELECT TOP 1 'S' FROM LY_GRADE WHERE FORMULA_EQUIV LIKE '%'+VW.DISCIPLINA+'%' AND CURSO = A.CURSO AND CURRICULO = A.CURRICULO AND TURNO = A.TURNO),'N') AS EQUIVALENTE, 
		VW.TURMA, 
		VW.SIT_MATRICULA, 
		VW.SIT_DETALHE 
FROM VW_MATRICULA_E_PRE_MATRICULA VW
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
JOIN LY_GRADE G ON (G.DISCIPLINA = VW.DISCIPLINA OR G.FORMULA_EQUIV LIKE '%'+VW.DISCIPLINA+'%') AND G.CURSO = A.CURSO AND G.CURRICULO = A.CURRICULO AND G.TURNO = A.TURNO
WHERE VW.SERIE_CALCULO <> G.SERIE_IDEAL