USE LYCEUM
GO

UPDATE TD SET TD.NUM_FUNC = '825' 
FROM LY_TURMA_DOCENTE TD
JOIN LY_TURMA T ON T.DISCIPLINA = TD.DISCIPLINA AND T.ANO = TD.ANO AND T.SEMESTRE = TD.PERIODO AND T.TURMA = TD.TURMA
WHERE TD.NUM_FUNC = '1' AND TD.ano = 2017 AND TD.PERIODO = 1
AND T.FACULDADE IN ('FTC-JEQ','FTC-VIC','FTC-FSA','FTC-SSA','FTC-ITA','FCS')
GO

UPDATE T SET T.NUM_FUNC = '825' 
FROM LY_TURMA T WHERE T.NUM_FUNC = '1' AND T.ano = 2017 AND T.SEMESTRE = 1
AND FACULDADE IN ('FTC-JEQ','FTC-VIC','FTC-FSA','FTC-SSA','FTC-ITA','FCS')
GO