SELECT *
INTO lyceumtemp..ly_h_cursos_concl_10jan2017
	FROM LY_H_CURSOS_CONCL HC WHERE HC.MOTIVO = 'ABANDONO' AND HC.CAUSA_ENCERR = 'MIGRACAO'
	AND EXISTS (SELECT 1 FROM LY_HISTMATRICULA H WHERE HC.ALUNO = H.ALUNO AND H.ANO = '2016' AND H.SEMESTRE = '0')

SELECT ALUNO
INTO #TEMP
FROM LY_H_CURSOS_CONCL HC WHERE HC.MOTIVO = 'ABANDONO' AND HC.CAUSA_ENCERR = 'MIGRACAO'
AND EXISTS (SELECT 1 FROM LY_HISTMATRICULA H WHERE HC.ALUNO = H.ALUNO AND H.ANO = '2016' AND H.SEMESTRE = '0')


DELETE 
FROM LY_H_CURSOS_CONCL HC WHERE HC.MOTIVO = 'ABANDONO' AND HC.CAUSA_ENCERR = 'MIGRACAO'
AND EXISTS (SELECT 1 FROM LY_HISTMATRICULA H WHERE HC.ALUNO = H.ALUNO AND H.ANO = '2016' AND H.SEMESTRE = '0')

UPDATE A
SET A.SIT_ALUNO = 'Ativo'
--SELECT *
FROM LY_ALUNO A
WHERE A.ALUNO IN (SELECT ALUNO FROM #temp)