USE LYCEUM
GO

BEGIN

DECLARE @CURSOR VARCHAR(5) = 'S'

IF (@CURSOR = 'S')
BEGIN

	DECLARE
		 @ID INTEGER
		,@ALUNO VARCHAR(60)
		,@SERIE INTEGER
		,@DISCIPLINA VARCHAR(20)
		,@SUBTURMA1 VARCHAR(20)
		,@SUBTURMA2 VARCHAR(20)
		,@TURMA VARCHAR(50)
		,@CREDITOS INTEGER
		,@SESSAO VARCHAR(40) = (SELECT concat(9,@@SPID))
		,@DT_INSERT DATETIME = GETDATE()
		,@ANO VARCHAR(4) = '2020'
		,@SEM VARCHAR(2) = '2'

	-- ID DA SESSAO PARA REVISAR NA TABELA DO LYCEUM
	--SELECT @SESSAO ID_SESSAO

	-- CURSOR PARA PERCORRER OS NOMES DOS OBJETOS 
	DECLARE CURSOR_OBJECTS CURSOR FOR

	-- #################### CRIA A LISTA DE ALUNOS QUE SERÁ INSERIDA #################### --

		SELECT distinct ALUNO FROM (
			SELECT 		
				A.ALUNO,
				SUBSTRING(S.DISCIPLINA_FAKE,4,LEN(S.DISCIPLINA_FAKE)) OPCH,
				SUM(S.CREDITOS) CREDITOS
				--,(SUM(S.CREDITOS) / CAST(REPLACE(DISCIPLINA_FAKE,'MF_','') AS INT)) * 100 AS PERC
				--,(CAST(REPLACE(DISCIPLINA_FAKE,'MF_','') AS INT) - SUM(S.CREDITOS)) AS DIF
			FROM
				LYCEUMINTEGRACAO..FTC_SUGESTAO_PRE_MAT S
				INNER JOIN LY_ALUNO A ON A.ALUNO = S.ALUNO
				INNER JOIN LY_CURSO C ON C.CURSO = A.CURSO
				INNER JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
			WHERE 
				1 = 1			
				AND s.ENVIADO IS NULL
				AND S.ANO = '2020'
				AND S.SEMESTRE = '2'	
			GROUP BY A.ALUNO, S.DISCIPLINA_FAKE
		) T
		--WHERE PERC >= 100	-- 6.282
		--WHERE DIF  <= 60 
		ORDER BY ALUNO DESC
		
	-- ABRINDO CURSOR PARA LEITURA
	OPEN CURSOR_OBJECTS

	-- LENDO A PRÓXIMA LINHA
	FETCH NEXT FROM CURSOR_OBJECTS INTO @ALUNO 

	-- PERCORRENDO LINHAS DO CURSOR (ENQUANTO HOUVEREM)
	WHILE @@FETCH_STATUS = 0
	BEGIN
	
	    --set @SESSAO = (CAST(@@spid AS VARCHAR(10))+'_'+@ALUNO)    
		--TRUNCATE TABLE LYCEUM..LY_PROCESSA_MATRICULA_GRUPO	
		
		-- GRAVA LOG DA PREMATRICULA
		INSERT INTO LOG_FTC.LYCEUM.LY_PRE_MATRICULA_SUGESTAO (OPERACAO,DT_OPERACAO,USUARIO_APLICACAO,USUARIO_BD,ALUNO,DISCIPLINA,ANO,SEMESTRE,TURMA,SUBTURMA1,SUBTURMA2,SERIE_IDEAL,MENS_ERRO,LANC_DEB,CONFIRMADA,DISPENSADA,MANUAL,DT_ULTALT,COBRANCA_SEP,SERIE_CALCULO,DT_INSERCAO,DT_CONFIRMACAO,SIT_DETALHE,GRUPO_ELETIVA,NUM_CHAMADA,CONFIRMACAO_LIDER,OPCAO,DISCIPLINA_SUBST,TURMA_SUBST,ALOCADO,OBS,ACEITE_ONLINE,CHAVE,LOTE_ENTURMACAO,PLANO_PAGTO_PAD_ESP,FL_FIELD_01,FL_FIELD_02,FL_FIELD_03,FL_FIELD_04,FL_FIELD_05,FL_FIELD_06,FL_FIELD_07,FL_FIELD_08,FL_FIELD_09,FL_FIELD_10)
		SELECT 'I',@DT_INSERT,null,'Lyceum',ALUNO,DISCIPLINA,ANO,SEMESTRE,TURMA,SUBTURMA1,SUBTURMA2,SERIE_IDEAL,MENS_ERRO,LANC_DEB,CONFIRMADA,DISPENSADA,MANUAL,DT_ULTALT,COBRANCA_SEP,SERIE_CALCULO,DT_INSERCAO,DT_CONFIRMACAO,SIT_DETALHE,GRUPO_ELETIVA,NUM_CHAMADA,CONFIRMACAO_LIDER,OPCAO,DISCIPLINA_SUBST,TURMA_SUBST,ALOCADO,OBS,ACEITE_ONLINE,CHAVE,LOTE_ENTURMACAO,PLANO_PAGTO_PAD_ESP,FL_FIELD_01,FL_FIELD_02,FL_FIELD_03,FL_FIELD_04,FL_FIELD_05,FL_FIELD_06,FL_FIELD_07,FL_FIELD_08,FL_FIELD_09,FL_FIELD_10 
		FROM LYCEUM..LY_PRE_MATRICULA WHERE ALUNO = @ALUNO AND ANO = '2020' AND SEMESTRE = '2' AND DISCIPLINA LIKE 'MF[_]%'
			   
		--INSERT PREMATRICULAS COM AS DISCIPLINAS DA SUGESTÃO
		INSERT INTO LYCEUM..LY_PROCESSA_MATRICULA_GRUPO
			(
				SESSAO_ID, DISCIPLINA, TURMA, ANO, SEMESTRE, SUBTURMA1, SUBTURMA2, SIT_MATRICULA, SIT_DETALHE, OBS, MATRICULANOVA, SERIE_IDEAL
				, SERIE_CALCULO, COBRANCA_SEP, DT_INSERCAO, DT_MATRICULA, ALOCADO, CONTEXTO, VERMAXREPROVACAO, VERVAGA, VERGRADE, VERHORARIO
				, VERPREREQ, VERLIMITESCREDITOS, VERDISCIPADAP, VERPLANOESTUDO, VERCARGAHORARIA, ACEITE_ONLINE, VERGRUPO, CONFIRMADA, DISPENSADA
			)
		SELECT distinct
			@SESSAO SESSAO_ID
			,ST.DISCIPLINA 
			,ST.TURMA 
			,ST.ANO
			,ST.SEMESTRE
			,CASE WHEN SUBTURMA1 = '' THEN NULL ELSE ST.SUBTURMA1  END SUBTURMA1 
			,CASE WHEN SUBTURMA2 = '' THEN NULL ELSE ST. SUBTURMA2 END SUBTURMA2 
			,'Pré-Matriculado' SIT_MATRICULA
			,'Curricular' SIT_DETALHE
			,('SUGESTÃO AUTOMATICA - REMATRICULA 2020.2 ' + '. Créditos: ' + CAST(SUBSTRING(St.DISCIPLINA_FAKE,4,LEN(St.DISCIPLINA_FAKE)) AS VARCHAR(6))) + ' - Perc >= 100' OBS
			,'S' MATRICULANOVA
			,ST.SERIE SERIE_IDEAL
			,ST.SERIE SERIE_CALCULO
			,'N' COBRANCA_SEP
			,GETDATE() DT_INSERCAO
			,GETDATE() DT_MATRICULA
			,'S' ALOCADO
			,'Matricula pela Internet' CONTEXTO
			,'N' VERMAXREPROVACAO
			,'N' VERVAGA
			,'N' VERGRADE
			,'N' VERHORARIO
			,'N' VERPREREQ
			,'N' VERLIMITESCREDITOS
			,'N' VERDISCIPADAP
			,'N' VERPLANOESTUDO
			,'N' VERCARGAHORARIA
			,'S' ACEITE_ONLINE
			,'N' VERGRUPO
			,'N' CONFIRMADA
			,'N' DISPENSADA
		FROM LYCEUMINTEGRACAO..FTC_SUGESTAO_PRE_MAT ST 
		WHERE 1 = 1
			AND ALUNO = @ALUNO 
			AND ENVIADO IS NULL	
			AND ANO = '2020'
			AND SEMESTRE = '2'
			-- SelecaoTurmaCursados
			AND (
				NOT EXISTS (
					SELECT TOP 1
						1
					FROM LYCEUM..LY_PRE_MATRICULA
					WHERE 1 = 1
						AND ALUNO = ST.ALUNO						
						AND ANO = ST.ANO
						AND SEMESTRE = ST.SEMESTRE						
						AND DISCIPLINA NOT LIKE 'MF[_]%'	
						--AND SUBTURMA1 = ST.SUBTURMA1
						--AND DISCIPLINA = ST.DISCIPLINA 
						--AND TURMA = ST.TURMA
				)
				AND NOT EXISTS (
					SELECT TOP 1
						1
					FROM LYCEUM..LY_MATRICULA
					WHERE 1 = 1
						AND ALUNO = ST.ALUNO						
						AND ANO = ST.ANO
						AND SEMESTRE = ST.SEMESTRE
						--AND TURMA = ST.TURMA
						--AND SUBTURMA1 = ST.SUBTURMA1
						--AND DISCIPLINA = ST.DISCIPLINA 
				)
			)
			 --SelecaoTurmaPreMatriculados
			AND NOT EXISTS (
				SELECT TOP 1
					1
				FROM LYCEUM..LY_HISTMATRICULA M
				WHERE 1 = 1
					AND ALUNO = ST.ALUNO
					AND DISCIPLINA = ST.DISCIPLINA 
					AND SITUACAO_HIST IN ('APROVADO', 'DISPENSADO')
			)
						
			-- PROCESSA REMATRICULA DISCIPLNAS SUGESTÃO
			EXEC LYCEUM..PROCESSA_MATRICULA_GRUPO @SESSAO, @ALUNO, '2020', '2', 'MATRICULA PELA INTERNET', 'S', 'N', 'N', 'N', NULL;
				
			-- SE EXISTIR NA PREMATRICULA
			IF ( SELECT COUNT(1) FROM LYCEUM..LY_PRE_MATRICULA P WHERE P.ALUNO = @ALUNO  AND ANO = '2020' AND SEMESTRE = '2' AND DISCIPLINA NOT LIKE 'MF[_]%' ) > 0 BEGIN
				
				-- SET SUGESTÃO COMO ENVIADO
				UPDATE M SET M.ENVIADO = GETDATE() FROM LYCEUMINTEGRACAO..FTC_SUGESTAO_PRE_MAT M WHERE ALUNO = @ALUNO AND ANO = '2020' AND SEMESTRE = '2'
			
				-- REMOVE PREMATRICULA FAKE
				DELETE LYCEUM..LY_PRE_MATRICULA WHERE ALUNO = @ALUNO AND ANO = '2020' AND SEMESTRE = '2' AND DISCIPLINA LIKE 'MF[_]%'	

				-- CALCULA CALCULO E RECALCULO
				--EXEC LYCEUM..CALCULO_RECALCULO_ALUNO @SESSAO, @aluno ,@ANO, @SEM, 'S','S','N', NULL, 'pt-BR', 'N'

			END
			ELSE
				BEGIN
					insert into  LOG_FTC.LYCEUM.Log_Erros_Migracao_Sugestao ( mensagem, aluno, dt_inclusao )
					select mensagem, @ALUNO as aluno, getdate()  dt_inclusao from zzCRO_Erros where spid = @SESSAO
				END
									

		-- LENDO A PRÓXIMA LINHA
		FETCH NEXT FROM CURSOR_OBJECTS INTO @ALUNO 

	END

	-- FECHANDO CURSOR PARA LEITURA
	CLOSE CURSOR_OBJECTS

	-- DESALOCANDO O CURSOR
	DEALLOCATE CURSOR_OBJECTS

END


--sp_helptext VALIDA_MATRICULA
--sp_helptext VALIDA_MATRICULA_GRUPO
-- sp_helptext DISCIP_EQUIVAL_CURSADA

END