USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.Relat_P_A_Curso'))
   exec('CREATE PROCEDURE [dbo].[Relat_P_A_Curso] AS BEGIN SET NOCOUNT OFF; END')
GO   

ALTER PROCEDURE [dbo].[Relat_P_A_Curso](  
@p_tipo VARCHAR(20),  
@p_unidade VARCHAR(20)
)  
  
AS  
BEGIN  
  
SELECT DISTINCT CURSO AS CODIGO, (CURSO + ' - ' + NOME) AS DESCR   
  FROM VW_CURSO  
  WHERE TIPO = CASE WHEN @p_tipo IS NULL THEN TIPO ELSE @p_tipo END   
    AND FACULDADE = CASE WHEN @p_unidade IS NULL THEN FACULDADE ELSE @p_unidade END  
	AND TIPO IN ('GRADUACAO','TECNOLOGO','MESTRADO') AND ATIVO = 'S'
  UNION  
  SELECT NULL AS CODIGO, 'TODOS' AS DESCR 
  ORDER BY 2 
END  