USE LYCEUM
GO
  
--EXEC Relat_P_A_Docente 'Avaliação Docente I','AVALDOCENTE1_20171'

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.Relat_P_A_Docente'))
   exec('CREATE PROCEDURE [dbo].[Relat_P_A_Docente] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE [dbo].[Relat_P_A_Docente]  
(
	@p_aplicacao VARCHAR(50)
	,@p_avaliacaoq VARCHAR(50)
	,@p_curso VARCHAR(20)
) 
AS  
BEGIN  

SELECT DISTINCT CODIGO, CODIGO4 
INTO #TEMP
FROM LY_QUESTAO_APLICADA
WHERE TIPO_QUESTIONARIO = @p_avaliacaoq AND APLICACAO = @p_aplicacao
  
IF @p_avaliacaoq IN ('Avaliação Docente I','Avaliação DocenteIII','Av Docente M II','Av Docente M I','Av Institucional I','Av Institucional II','Av Institucional III')
BEGIN

SELECT D.NUM_FUNC AS CODIGO, (CONVERT(VARCHAR(15), D.NUM_FUNC) + ' - ' + D.NOME_COMPL) AS DESCR  
FROM LY_DOCENTE D 
WHERE 1=1
AND EXISTS (SELECT 1 FROM #TEMP WHERE CONVERT(VARCHAR(15),CODIGO) = CONVERT(VARCHAR(15),D.NUM_FUNC) OR CONVERT(VARCHAR(15),CODIGO4) = CONVERT(VARCHAR(15),D.NUM_FUNC))
UNION  
SELECT NULL AS CODIGO, 'TODOS' AS DESCR  
ORDER BY 2
END 

IF @p_avaliacaoq IN ('Avaliação Docente II','Avaliação DocenteIV')
BEGIN

SELECT D.NUM_FUNC AS CODIGO, (CONVERT(VARCHAR(15), D.NUM_FUNC) + ' - ' + D.NOME_COMPL) AS DESCR  
FROM LY_DOCENTE D 
JOIN LY_COORDENACAO C ON C.NUM_FUNC = D.NUM_FUNC
WHERE 1=1
AND EXISTS (SELECT 1 FROM #TEMP WHERE CONVERT(VARCHAR(15),CODIGO) = CONVERT(VARCHAR(15),D.NUM_FUNC) OR CONVERT(VARCHAR(15),CODIGO4) = CONVERT(VARCHAR(15),D.NUM_FUNC))
AND C.CURSO = ISNULL(@p_curso,C.CURSO)
UNION  
SELECT NULL AS CODIGO, 'TODOS' AS DESCR  
ORDER BY 2
END 


DROP TABLE #TEMP
  
END  