--DELETE FROM LY_RESPOSTA  WHERE TIPO_QUESTIONARIO = 'Avaliação DocenteIV' AND QUESTIONARIO = 'COORDENADORXDISCENTE' AND APLICACAO = 'AVALDOCENTE4_20171'
--DELETE FROM  LY_QUESTAO_APLICADA WHERE TIPO_QUESTIONARIO = 'Avaliação DocenteIII' AND TIPO_OBJETO = 'DOCENTE'
--DELETE FROM LY_RESPOSTA WHERE TIPO_QUESTIONARIO = 'Avaliação DocenteIII' AND QUESTIONARIO = 'Docente X Coordenado'
--DELETE FROM LY_RESPOSTA  WHERE TIPO_QUESTIONARIO = 'Avaliação Docente II' AND QUESTIONARIO = 'Coordenador x Docent' AND APLICACAO = 'Avaliação Docente'
--DELETE FROM LY_RESPOSTA WHERE APLICACAO = 'AVALDOCENTE2_20171' ORDER BY CODIGO, CHAVE_RESP
--DELETE FROM LY_RESPOSTA  WHERE TIPO_QUESTIONARIO = 'Avaliação DocenteIII' AND QUESTIONARIO = 'DOCENTEXCOORD_20171'
--DELETE FROM LY_PARTICIPACAO_QUEST WHERE APLICACAO = 'AVALDOCENTE1_20171' AND DATA_PART IS NULL
--DELETE FROM LY_QUESTAO_APLICADA
--WHERE NOT EXISTS (SELECT 1 FROM LY_PARTICIPACAO_QUEST PQ WHERE APLICACAO = PQ.APLICACAO AND PAR_CODIGO = PQ.CODIGO AND APLICACAO = 'AVALDOCENTE1_20171')
--AND APLICACAO = 'AVALDOCENTE1_20171'
SELECT * FROM LY_APLIC_QUESTIONARIO laq WHERE TIPO_QUESTIONARIO = 'Avaliação Docente II' AND laq.QUESTIONARIO = 'Coordenador x Docent' 

SELECT * FROM LY_PARTICIPACAO_QUEST  WHERE TIPO_QUESTIONARIO = 'Avaliação DocenteIII' AND QUESTIONARIO = 'DOCENTEXCOORD_20171' AND DATA_PART IS NOT NULL

select * FROM LY

--1108
select * from LY_DOCENTE WHERE NUM_FUNC = '1108'
select DISTINCT TIPO_QUESTIONARIO, QUESTIONARIO, APLICACAO, QUESTAO, AVALIADO, AVALIADOR from LY_RESPOSTA_AUX WHERE APLICACAO = 'AVALDOCENTE2_20171' AND AVALIADO = '1108' AND QUESTAO = '5'
select DISTINCT TIPO_QUESTIONARIO, QUESTIONARIO, APLICACAO, QUESTAO, CODIGO AS AVALIADO, RESPOSTA AS AVALIADOR from LY_RESPOSTA WHERE APLICACAO = 'AVALDOCENTE2_20171' AND CODIGO = '1108' AND QUESTAO = '5'
ORDER BY 6,5,4

select * from LY_RESPOSTA_AUX A 
WHERE A.APLICACAO = 'AVALDOCENTE2_20171' 
AND QUESTAO NOT IN (SELECT QUESTAO FROM LY_RESPOSTA WHERE CODIGO = A.AVALIADO AND APLICACAO = 'AVALDOCENTE2_20171')

select * from LY_COORDENACAO WHERE CURSO = '3013'

SELECT * FROM LY_PARTICIPACAO_QUEST WHERE CODIGO = '011040755'
SELECT * FROM LY_QUESTAO_APLICADA 

SELECT DISTINCT A.ALUNO  
FROM LY_ALUNO A 
JOIN LY_CURSO C ON C.CURSO = a.CURSO 
WHERE A.SIT_ALUNO = 'Ativo' 
AND C.TIPO IN ('GRADUACAO','TECNOLOGO') 
AND EXISTS (SELECT 1 FROM LY_MATRICULA VW WHERE VW.ALUNO = A.ALUNO)

SELECT DISTINCT D.NUM_FUNC 
FROM LY_DOCENTE D 
JOIN LY_DOCENTE_UNIDADE DU ON DU.NUM_FUNC = DU.NUM_FUNC 
JOIN LY_CURSO C ON C.FACULDADE = DU.FACULDADE 
JOIN LY_COORDENACAO CO ON CO.NUM_FUNC = D.NUM_FUNC 
WHERE D.ATIVO = 'S' AND D.DT_DEMISSAO IS NULL AND D.NUM_FUNC NOT IN ('1','388') 
AND C.TIPO IN ('GRADUACAO','TECNOLOGO') AND C.ATIVO = 'S'

SELECT DISTINCT D.NUM_FUNC 
FROM LY_DOCENTE D 
JOIN LY_DOCENTE_UNIDADE DU ON DU.NUM_FUNC = DU.NUM_FUNC 
JOIN LY_CURSO C ON C.FACULDADE = DU.FACULDADE 
WHERE D.ATIVO = 'S' 
AND D.DT_DEMISSAO IS NULL 
AND D.NUM_FUNC NOT IN ('1','388') AND C.TIPO IN ('GRADUACAO','TECNOLOGO')

--coordenadores do curso do aluno
SELECT DISTINCT CO.NUM_FUNC  
FROM LY_ALUNO A, LY_MATRICULA M, LY_CURSO C, LY_COORDENACAO CO, LY_DOCENTE D   
WHERE A.ALUNO = M.ALUNO  AND D.NUM_FUNC = CO.NUM_FUNC AND C.CURSO = A.CURSO  
AND CO.NUM_FUNC NOT IN ('1','388')  AND CO.CURSO = C.CURSO  
AND D.DT_DEMISSAO IS NULL 
AND D.ATIVO = 'S' AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND M.ALUNO = '%%CHAVE1'

--docentes que lecionam para o aluno NAO UTILIZADO
SELECT DISTINCT T.NUM_FUNC 
FROM LY_TURMA T, LY_MATRICULA M, LY_CURSO C  
WHERE T.ANO = M.ANO  AND T.SEMESTRE = M.SEMESTRE  
AND T.DISCIPLINA = M.DISCIPLINA  AND T.TURMA = M.TURMA  
AND T.NUM_FUNC NOT IN ('1','388') AND T.CURSO = C.CURSO 
AND C.TIPO IN ('GRADUACAO','TECNOLOGO') 
AND M.ALUNO = '162040001'

--docentes que leiconam para o aluno CORRETO
SELECT DISTINCT T.DISCIPLINA,T.NUM_FUNC, T.TURMA, T.ANO, T.SEMESTRE 
FROM LY_TURMA T, LY_MATRICULA M, LY_CURSO C  
WHERE T.ANO = M.ANO  AND T.SEMESTRE = M.SEMESTRE  
AND T.DISCIPLINA = M.DISCIPLINA  
AND T.TURMA = M.TURMA  
AND T.NUM_FUNC NOT IN ('1','388') 
AND T.CURSO = C.CURSO 
AND C.TIPO IN ('GRADUACAO','TECNOLOGO') 
AND M.ALUNO = '162040001'

--coordenadores que coordenam cursos das turmas que o docente leciona
SELECT DISTINCT C.NUM_FUNC  
FROM LY_COORDENACAO C  
JOIN LY_DOCENTE D ON D.NUM_FUNC = C.NUM_FUNC   
JOIN LY_TURMA T ON T.CURSO = C.CURSO  
JOIN LY_CURSO CUR ON CUR.CURSO = T.CURSO 
JOIN LY_MATRICULA M ON M.ANO = T.ANO AND m.SEMESTRE = T.SEMESTRE AND M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA 
WHERE D.ATIVO = 'S'  
AND C.NUM_FUNC <> T.NUM_FUNC
AND T.NUM_FUNC NOT IN ('1','388') 
AND D.DT_DEMISSÃO IS NULL  
AND CUR.TIPO IN ('GRADUACAO','TECNOLOGO')   
AND T.NUM_FUNC = '943'

SELECT * FROM LY_COORDENACAO lc
WHERE EXISTS (SELECT 1 FROM LY_TURMA T WHERE T.CURSO = lc.CURSO AND t.NUM_FUNC = lc.NUM_FUNC)
ORDER BY 2


--docentes que lecionam em turmas-disciplinas do coordenador

SELECT DISTINCT T.DISCIPLINA,T.NUM_FUNC, T.TURMA, T.ANO, T.SEMESTRE  
FROM LY_TURMA T, LY_CURSO C, LY_COORDENACAO CO, LY_MATRICULA M   
WHERE T.ANO = M.ANO AND T.SEMESTRE = M.SEMESTRE AND T.DISCIPLINA = M.DISCIPLINA   AND T.TURMA = M.TURMA   
AND T.NUM_FUNC NOT IN ('1','388')  AND T.CURSO = C.CURSO AND C.CURSO = CO.CURSO AND T.NUM_FUNC <> CO.NUM_FUNC 
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  AND CO.NUM_FUNC = '761'