
SELECT * 
FROM LY_PESSOA P
WHERE 1=1 
AND PESSOA IN (SELECT DISTINCT pessoa FROM LY_CANDIDATO WHERE CANDIDATO LIKE 'CAN-%')
AND NOT EXISTS (SELECT 1 FROM LY_ALUNO A WHERE A.PESSOA = P.PESSOA )
AND (SELECT COUNT(*) FROM LY_PESSOA P1 WHERE P.CPF = P1.CPF) > 1
ORDER BY 3