USE LYCEUM
GO

DISABLE TRIGGER CRO_Ly_turma_Update ON LY_TURMA
GO

UPDATE T
SET DISCIPLINA = UPPER(DISCIPLINA)
FROM LY_TURMA T
WHERE UPPER(DISCIPLINA) COLLATE Latin1_General_CS_AS <> DISCIPLINA
GO

ENABLE TRIGGER CRO_Ly_turma_Update ON LY_TURMA
GO