USE LYCEUM
GO

DELETE FROM LY_CAR
WHERE EXISTS (SELECT 1 FROM LY_COBRANCA C
WHERE C.COBRANCA = LY_CAR.COBRANCA AND DATA_DE_FATURAMENTO IS NULL
--AND C.DATA_DE_VENCIMENTO >= '2017-06-01'     
--AND C.DATA_DE_VENCIMENTO <= '2017-06-30'
AND NOT EXISTS (SELECT 1 from LY_MOVIMENTO_TEMPORAL where ID1 = CONVERT(varchar,C.COBRANCA)) 
AND EXISTS (SELECT 1 from LY_CAR where cobranca = C.COBRANCA))
GO