--INSERT INTO BI_ACOMP_MATR
SELECT 		ANO,
		SEMESTRE,
		UNIDADE_ENSINO_ALUNO,
		NOME_UNIDADE_ENSINO_ALUNO,
		TIPO_CURSO,
		CURSO,
		NOME_CURSO,
		SERIE,
		TURNO,
		CONCURSO,
		DESC_CONCURSO,
		TIPO_ALUNO,
		TIPO_INGRESSO,
		TIPO_FINAN,
		PAGO,
		NAO_PAGO,
		BOLSISTA,
		DATA_PAGAMENTO,
		SIT_MATRICULA,
		DATA_MATRICULA,
		DATA_CANCELAMENTO,
		ORIGEM_MATRICULA,
		DATA_INGRESSO,
		ALUNO,
		CPF,
		NOME_ALUNO,
		CURRICULO,
		DATA_NASC,
		RG,
		E_MAIL,
		ENDERECO,
		NUMERO,
		COMPLEMENTO,
		CEP,
		BAIRRO,
		CIDADE,
		ESTADO,
		DDD_FONE,
		FONE,
		DDD_CELULAR,
		CELULAR,
		CONTRATO_ACEITO,
		BOLSAS,
		DATA_MATRICULA_ORC,
		CANDIDATO
		FROM BI_ACOMP_MATR_HIST
		WHERE ANO = 2020 AND SEMESTRE = 1 AND DATA_HIST BETWEEN '2020-02-29' AND '2020-03-01'

		
		DELETE FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 2
		SELECT * FROM BI_ACOMP_MATR_HIST WHERE ANO = 2019 AND SEMESTRE = 2 AND DATA_HIST BETWEEN '2019-12-12' AND '2019-12-13'

				SELECT DISTINCT DATA_HIST FROM BI_ACOMP_MATR_HIST WHERE ANO = 2019 AND SEMESTRE = 2 ORDER BY 1 DESC