SELECT DISTINCT cpf,teleitor_num,TELEITOR_ZONA,TELEITOR_SECAO, * 
FROM ly_pessoa 
WHERE NOME_COMPL LIKE '%Marivaldo Leite Nascimento%'

SELECT DISTINCT * 
FROM LY_ALUNO 
WHERE NOME_COMPL LIKE '%Suse Cleide Lopes Santos%'

SELECT * FROM LY_HISTMATRICULA lh WHERE lh.ALUNO = '042030372'

SELECT * FROM LY_CURSO WHERE CURSO IN ('372','2079','291')

SELECT * FROM ly_aluno WHERE pessoa = '77455'

SELECT CPF,COD_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Suse Cleide Lopes Santos%'
SELECT ANO,SEMESTRE,* FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '839496' --AND ANO = '2016' AND SEMESTRE = '1'
ORDER BY 1,2


SELECT  VALOR_BRUTO, VALOR_ITEM_ADICIONAL, VALOR_MULTA, VALOR_JUROS_TOTAL, VALOR_DESCONTO, VALOR_BOLSA1, VALOR_ACERTO,  VALOR_PAGO, VALOR_ACORDADO, TIPO_ACERTO ,* 
FROM VIRTUALCLASS..TBL_FINANCEIRO 
WHERE ALUNO = '969767' AND PERIODO_LETIVO = '20161'
--AND TIPO_ACERTO = 'ACORDO' 
ORDER BY MES

SELECT VALOR_BRUTO, VALOR_MULTA, VALOR_JUROS_TOTAL, VALOR_DESCONTO, VALOR_BOLSA1, VALOR_ACERTO,  VALOR_PAGO, VALOR_ACORDADO, TIPO_ACERTO ,* 
FROM MIGRACAO..TBL_FINANCEIRO 
WHERE CODIGO_ALUNO_VIRTUAL = '62951' AND PERIODO_LETIVO = '20161' AND LANC_DEB IN ('3271490','3271491')

ORDER BY MES


SELECT * FROM LY_ITEM_LANC WHERE LANC_DEB IN ('3271490','3271491')
SELECT * FROM LY_ITEM_CRED WHERE LANC_CRED IN ('2459075','2459076')

SELECT VALOR_BRUTO, VALOR_ACERTO,  VALOR_PAGO, VALOR_ACORDADO, TIPO_ACERTO 
FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE TIPO_ACERTO = 'ACORDO'