USE LYCEUM
GO

-- ## DETERMINANDO CASOS ## --

SELECT ALUNO, ANO, PERIODO, ID_CONTRATO_ALUNO AS CHAVE, CONTRATO_ACEITO, DATA_ACEITE, OFERTA_DE_CURSO 
INTO #TEMP1 --DROP TABLE #TEMP1
FROM LY_CONTRATO_ALUNO
WHERE ANO = 2017 AND PERIODO = 2 AND CONTRATO_ACEITO IS NOT NULL AND DATA_ACEITE < '2017-09-13'
GO


SELECT CA.ALUNO, CA.ANO, CA.PERIODO, CAI.ID_CONTRATO_ALUNO AS CHAVE, CAI.IMAGEM, CAI.CODIGO_HASH 
INTO #TEMP2 --DROP TABLE #TEMP2
FROM LY_CONTRATO_ALUNO_IMG CAI
JOIN LY_CONTRATO_ALUNO CA ON CA.ID_CONTRATO_ALUNO = CAI.ID_CONTRATO_ALUNO
WHERE CA.ANO = 2017 AND CA.PERIODO = 2 AND CA.CONTRATO_ACEITO IS NOT NULL AND CA.DATA_ACEITE < '2017-09-13'
GO

-- ##  INSERINDO OS CONTRATOS NAS TABELAS DE REMOÇÂO ## --

INSERT INTO LY_CONTRATO_REMOVIDO 
SELECT ALUNO, ANO, PERIODO, CHAVE, CONTRATO_ACEITO, DATA_ACEITE, OFERTA_DE_CURSO FROM #TEMP1
GO

INSERT INTO LY_CONTR_ALU_IMG_REMOV
SELECT ALUNO, ANO, PERIODO, CHAVE, IMAGEM, CODIGO_HASH FROM #TEMP2
GO

-- ##  DELETANDO OS CONTRATOS DAS TABELAS  ## --

DELETE FROM LY_CONTRATO_ALUNO_IMG
WHERE ID_CONTRATO_ALUNO IN (SELECT CHAVE FROM #TEMP2)
GO

DELETE FROM LY_CONTRATO_ALUNO
WHERE ID_CONTRATO_ALUNO IN (SELECT CHAVE FROM #TEMP1)
GO
