USE LYCEUM
GO

--EXEC Relat_P_TurmaPref NULL,NULL

ALTER PROCEDURE [dbo].[Relat_P_TurmaPref]  
(  
   @p_unidade VARCHAR(20)
   ,@p_curso VARCHAR(20)  
)  
  
AS  
BEGIN  
  
SELECT DISTINCT TURMA_PREF AS CODIGO, (CASE WHEN TURMA_PREF IS NULL THEN 'TODAS' ELSE TURMA_PREF END) AS DESCR  
FROM VW_ALUNO  A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE A.CURSO = CASE WHEN @p_curso IS NULL THEN A.CURSO ELSE @p_curso END 
	AND C.FACULDADE = CASE WHEN @p_unidade IS NULL THEN C.FACULDADE ELSE @p_unidade END
ORDER BY TURMA_PREF  
  
END  