USE LYCEUM
GO

--EXEC FTC_csvControleDocenteAulasSemanais '2017','2','FCS',NULL
  
ALTER PROCEDURE dbo.FTC_csvControleDocenteAulasSemanais      
 @P_ANO    T_ANO    
,@P_SEMESTRE  T_SEMESTRE2    
,@P_FACULDADE  T_CODIGO  
,@P_DOCENTE   T_CODIGO    
AS        
BEGIN       
    
  /*  
  *   
  *   
  *   
  * ALTERADO POR MIGUEL EM 10/11/2016 PARA ATENDER SOLICITAÇÃO DE SIMONE OLIVEIRA - CONTROLADORIA  
  * ACRESCENTADO NOVOS CAMPOS NA LISTA NG DETALHADA.  
  *   
  *   
  *   
  * */  
      
  SELECT      
   ISNULL (T.NUM_FUNC,0)        AS NUM_FUNC    
  ,ISNULL (D.NOME_COMPL,'')    AS NOME_COMPL   
  ,ISNULL (D.CPF,0) AS CPF  
  ,ISNULL (T.CURSO,'') AS CURSO  
  ,ISNULL (C.NOME,'') AS NOME_CURSO  
  ,ISNULL (T.TURNO,'') AS TURNO  
  ,ISNULL (T.CURRICULO,'') AS CURRICULO  
  ,ISNULL(T.SERIE,0) AS SERIE
  ,T.SIT_TURMA  
  ,ISNULL (T.TURMA,'')     AS TURMA    
  ,ISNULL (T.DISCIPLINA,'')    AS DISCIPLINA    
  ,DI.NOME_COMPL AS  NOME_DISCIPLINA  
  ,ISNULL (T.ANO,'')      AS ANO    
  ,ISNULL (T.SEMESTRE,'')     AS SEMESTRE    
  ,ISNULL (T.FACULDADE,'')    AS FACULDADE    
  ,DI.AULAS_SEMANAIS      AS CH_SEMANAL  
  ,AD.DIA_SEMANA
  ,HA.QTDE_AULA AS QUANTIDADE  
  ,CONVERT(VARCHAR(05),HA.HORAINI_AULA,108) AS HORARIO_AULA   
  ,ISNULL((SELECT COUNT(*) FROM VW_MATRICULA_E_PRE_MATRICULA M WHERE M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE AND M.SIT_MATRICULA NOT IN ('Cancelado','Trancado')),0) AS QTD_ALUNOS  
  ,ISNULL(TD.OBSERVACAO,'') AS OBS_DOCENTE_TURMA  
  FROM LY_TURMA T  
   LEFT JOIN LY_CURSO C ON T.CURSO = C.CURSO
   INNER JOIN LY_DOCENTE D  ON D.NUM_FUNC  = T.NUM_FUNC  
   INNER JOIN LY_TURMA_DOCENTE TD ON TD.NUM_FUNC = D.NUM_FUNC AND TD.DISCIPLINA = T.DISCIPLINA AND TD.TURMA = T.TURMA AND TD.ANO = T.ANO AND TD.PERIODO = T.SEMESTRE    
   INNER JOIN LY_DISCIPLINA DI ON DI.DISCIPLINA = T.DISCIPLINA   
   LEFT JOIN LY_AULA_DOCENTE AD ON AD.TURMA = T.TURMA AND AD.TURNO = T.TURNO AND AD.DISCIPLINA = T.DISCIPLINA AND AD.ANO = T.ANO AND AD.SEMESTRE = T.SEMESTRE  
   LEFT JOIN LY_HOR_AULA HA ON HA.AULA = AD.AULA AND HA.DIA_SEMANA = AD.DIA_SEMANA AND HA.TURNO = AD.TURNO AND HA.FACULDADE = AD.FACULDADE AND HA.DISCIPLINA = T.DISCIPLINA AND HA.TURMA = T.TURMA AND HA.ANO = T.ANO AND HA.SEMESTRE = T.SEMESTRE
  WHERE 1=1
AND (@P_ANO IS NOT NULL AND T.ANO = @P_ANO)  
AND (@P_SEMESTRE IS NOT NULL AND T.SEMESTRE = @P_SEMESTRE)  
AND ((@P_FACULDADE IS NOT NULL AND T.FACULDADE = @P_FACULDADE) OR @P_FACULDADE IS NULL)
AND ((@P_DOCENTE IS NOT NULL AND T.NUM_FUNC = @P_DOCENTE) OR @P_DOCENTE IS NULL)    
   
ORDER BY 1,2,4,3     
    
SET NOCOUNT OFF    
    
  
 END                