USE LYCEUM
GO

--EXEC FTC_SP_csvSituacaoAlunos '2017','2','04','GRADUACAO',NULL,NULL,NULL
  
ALTER PROCEDURE dbo.FTC_SP_csvSituacaoAlunos       
(        
  @P_ANO VARCHAR(4)  
, @P_SEMESTRE VARCHAR(1)  
, @P_FACULDADE VARCHAR(20)  
, @P_TIPO_CURSO VARCHAR(20)    
, @P_CURSO  VARCHAR(20)    
, @P_TURNO  VARCHAR(20)    
, @P_CURRICULO VARCHAR(20)    
)        
AS        
-- [INÍCIO]                
BEGIN        
    
SET NOCOUNT ON    
    
  SELECT     
    PM.ANO                  AS [ANO],   
	PM.SEMESTRE             AS [SEMESTRE],   
     C.CURSO                AS [CURSO],    
     C.NOME                 AS [NOME_CURSO],   
     A.CURRICULO            AS [CURRICULO],   
     A.TURNO                AS [TURNO],  
     A.SERIE                AS [SERIE_ALUNO],   
     C.FACULDADE            AS [UNIDADE_ENSINO_ALUNO],   
     UE.NOME_COMP           AS [NOME_UNIDADE_ENSINO_ALUNO],   
     PM.SIT_MATRICULA       AS [SIT_MATRICULA],  
     A.ANO_INGRESSO         AS [ANO_INGRESSO],  
     A.SEM_INGRESSO         AS [SEM_INGRESSO],  
     A.TIPO_INGRESSO        AS [TIPO_INGRESSO],   
     A.ALUNO                AS [ALUNO],   
     PES.NOME_COMPL         AS [NOME_ALUNO],  
     PES.CPF				AS [CPF],  
     PES.RG_NUM             AS [RG],
	 PES.DT_NASC			AS [DATA_NASCIMENTO],   
     A.ANOCONCL_2G          AS [ANO_CONCLUSAO_2G],   
     PES.E_MAIL             AS [E_MAIL],  
     PES.ENDERECO           AS [ENDERECO],  
	PES.END_NUM             AS [NUMERO],  
	ISNULL(PES.END_COMPL,'')           AS [COMPLEMENTO],  
	PES.CEP                 AS [CEP],  
	PES.BAIRRO              AS [BAIRRO],  
	HM.NOME                 AS [CIDADE],  
	HM.UF                   AS [ESTADO],   
	PES.FONE                AS [FONE],   
     PES.CELULAR            AS [CELULAR],   
     ISNULL(T.CURSO,'')              AS [CURSO_TURMA],  
     ISNULL((SELECT TOP 1 NOME FROM LY_CURSO C1 WHERE C1.CURSO = T.CURSO),'')     AS NOME_CURSO_TURMA,   
              PM.DISCIPLINA                AS [DISCIPLINA],   
	D.CREDITOS AS [CARGA_HORARIA_DISCIPLINA],
     D.NOME                 AS [NOME_DISCIPLINA],   
     ISNULL(PM.TURMA,'')              AS [TURMA],  
     --ROUND(ISNULL(LVSP.CUSTO_UNITARIO*D.CREDITOS,0),2)       AS [VALOR_DISCIPLINA],  
	 ISNULL(LD.VALOR,0) AS [VALOR_DISCIPLINA],
     ISNULL(T.UNIDADE_RESPONSAVEL,'')           AS [UNIDADE_ENSINO_TURMA],   
     ISNULL(T.NUM_FUNC,0)              AS [COD_DOCENTE_TURMA],  
     ISNULL(DOC.NOME_COMPL,'')             AS [NOME_DOCENTE_TURMA],  
     PM.CONFIRMADA                AS [CONFIRMADA],  
              A.SIT_ALUNO                AS [SIT_ALUNO],  
   ISNULL((SELECT TOP 1 'S'     
   FROM LY_ITEM_LANC IL  
   JOIN LY_LANC_DEBITO LD    
   ON IL.LANC_DEB = LD.LANC_DEB     
   JOIN VW_COBRANCA C    
   ON IL.COBRANCA = C.COBRANCA  
   JOIN LY_COBRANCA CC  
   ON CC.COBRANCA = C.COBRANCA    
   LEFT JOIN LY_ITEM_CRED IC     
   ON IC.COBRANCA = C.COBRANCA    
   WHERE LD.ALUNO = PM.ALUNO    
   AND LD.ANO_REF = PM.ANO    
   AND LD.PERIODO_REF = PM.SEMESTRE    
   AND C.VALOR <= 1    
   AND LD.LANC_DEB = ISNULL(PM.LANC_DEB,LD.LANC_DEB)     
   AND LD.CODIGO_LANC IN ('MS','MS_EB')  
   AND CC.ESTORNO = 'N'  
   GROUP BY IL.COBRANCA),'N')              AS [PAGO],   
    ISNULL(CA.CONTRATO_ACEITO,'X')           AS [CONTRATO_ACEITO],
	ISNULL((SELECT TOP 1 'S' FROM LY_NOTA WHERE ANO = PM.ANO AND SEMESTRE = PM.SEMESTRE AND DISCIPLINA = PM.DISCIPLINA AND TURMA = PM.TURMA AND ALUNO = PM.ALUNO),'N') AS TEM_NOTA  
FROM (SELECT ANO, SEMESTRE, DISCIPLINA, TURMA, ALUNO, SIT_MATRICULA, LANC_DEB, DT_ULTALT , SERIE_CALCULO, COBRANCA_SEP, SIT_DETALHE, GRUPO_ELETIVA , DT_INSERCAO, 'S' AS CONFIRMADA  
FROM VW_MATRICULA_E_PRE_MATRICULA  
UNION  
SELECT ANO, SEMESTRE, DISCIPLINA, TURMA, ALUNO, SITUACAO_HIST AS SIT_MATRICULA, LANC_DEB, DT_ULTALT, SERIE AS SERIE_CALCULO, COBRANCA_SEP, SIT_DETALHE, GRUPO_ELETIVA, DT_MATRICULA AS DT_INSERCAO, 'S' CONFIRMADA  
FROM LY_HISTMATRICULA  
) PM   
JOIN LY_ALUNO A       -- PARA JOIN COM CURSO  
 ON PM.ALUNO = A.ALUNO  
JOIN LY_PESSOA PES  
    ON PES.PESSOA = A.PESSOA  
JOIN LY_CURSO C       -- PARA SABER NOME DO CURSO E JOIN COM UNIDADE ENSINO  
 ON A.CURSO = C.CURSO  
JOIN LY_DISCIPLINA D  
 ON PM.DISCIPLINA = D.DISCIPLINA  
JOIN LY_UNIDADE_ENSINO UE    -- PARA SABER NOME UNIDADE ENSINO  
 ON C.FACULDADE = UE.UNIDADE_ENS  
JOIN LY_TURMA T   
 ON T.TURMA = PM.TURMA AND T.DISCIPLINA = PM.DISCIPLINA AND T.ANO = PM.ANO AND T.SEMESTRE = PM.SEMESTRE  
JOIN HD_MUNICIPIO HM  
 ON HM.MUNICIPIO = PES.END_MUNICIPIO  
JOIN LY_DOCENTE DOC   
 ON DOC.NUM_FUNC = T.NUM_FUNC  
--JOIN LY_SERIE LS   
-- ON LS.CURSO = A.CURSO AND LS.TURNO = A.TURNO AND LS.CURRICULO = A.CURRICULO AND LS.SERIE = ISNULL(PM.SERIE_CALCULO,(SELECT MIN(SERIE_IDEAL) FROM LY_GRADE G WHERE G.CURSO = LS.CURSO AND G.CURRICULO = LS.CURRICULO AND G.TURNO = LS.TURNO AND (G.DISCIPLINA = PM.DISCIPLINA OR G.FORMULA_EQUIV LIKE '%'+PM.DISCIPLINA+'%')))  
LEFT JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = PM.LANC_DEB
--LEFT JOIN LY_VALOR_SERV_PERIODO LVSP   
-- ON LVSP.SERVICO = LS.SERVICO_CRED AND LVSP.ANO = PM.ANO AND LVSP.PERIODO = PM.SEMESTRE  
LEFT JOIN LY_CONTRATO_ALUNO CA   
 ON CA.ALUNO = PM.ALUNO AND CA.ANO = PM.ANO AND CA.PERIODO = PM.SEMESTRE  
WHERE 1=1  
AND (@P_ANO IS NOT NULL AND PM.ANO = @P_ANO)  
AND (@P_SEMESTRE IS NOT NULL AND PM.SEMESTRE = @P_SEMESTRE)  
AND (@P_FACULDADE IS NOT NULL AND C.FACULDADE = @P_FACULDADE)   
AND (@P_TIPO_CURSO IS NOT NULL AND C.TIPO = @P_TIPO_CURSO)    
AND ((@P_CURSO IS NOT NULL AND C.CURSO = @P_CURSO) OR @P_CURSO IS NULL)  
AND ((@P_TURNO IS NOT NULL AND A.TURNO = @P_TURNO) OR @P_TURNO IS NULL)    
AND ((@P_CURRICULO IS NOT NULL AND A.CURRICULO = @P_CURRICULO) OR @P_CURRICULO IS NULL)     
   
    
ORDER BY C.FACULDADE, UE.NOME_COMP, C.CURSO, C.NOME  
    
    
SET NOCOUNT OFF    
    
END                

--SELECT * FROM LY_CUSTOM_CLIENTE WHERE NOME = 'FTC_SP_csvSituacaoAlunos'
DELETE FROM LY_CUSTOM_CLIENTE    
where NOME = 'FTC_SP_csvSituacaoAlunos'    
and IDENTIFICACAO_CODIGO = '0004' 
GO

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_SP_csvSituacaoAlunos' NOME
, '0004' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2018-01-11' DATA_CRIACAO
, 'ListaNG - Situação Alunos Macro - Acréscimo de Campos' OBJETIVO
, 'Natanael- Coordenação de Curso' SOLICITADO_POR
, 'S' ATIVO
, 'LISTA NG' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO 