USE LYCEUM
GO

SELECT C.FACULDADE AS COD_UNIDADE, UE.NOME_COMP AS NOME_UNIDADE, C.CURSO, C.NOME AS NOME_CURSO, A.ALUNO, A.NOME_COMPL, CONCAT(HC.ANO_ENCERRAMENTO,HC.SEM_ENCERRAMENTO) AS PERIODO_ENCERRAMENTO, ISNULL(P.CELULAR,'') AS CELULAR, ISNULL(P.E_MAIL,'') AS EMAIL
FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_H_CURSOS_CONCL HC ON HC.ALUNO = A.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
WHERE 1=1
AND A.SIT_ALUNO = 'Concluido'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
ORDER BY 1,3,7