USE LYCEUM
GO

SELECT DISTINCT A.UNIDADE_FISICA, UF.NOME_COMP, A.CURSO, C.NOME, A.TIPO_INGRESSO, A.ALUNO, A.NOME_COMPL, ISNULL(HF.OUTRA_FACULDADE,'NF')AS INST_ANTERIOR, ISNULL(I.NOME_COMP,'NÃO INFORMADO') AS DESCR_INST_ANTERIOR
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
LEFT JOIN LY_HIST_FACULDADE HF ON HF.ALUNO = A.ALUNO
LEFT JOIN LY_INSTITUICAO I ON I.OUTRA_FACULDADE = HF.OUTRA_FACULDADE
WHERE TIPO_INGRESSO IN ('MatriculaEspecial','TransferenciaExterna')
AND ANO_INGRESSO = 2019
AND SEM_INGRESSO = 1
AND I.NOME_COMP LIKE '%BRASIL%'
AND SIT_ALUNO <> 'Cancelado'
ORDER BY 1,3
