select DISTINCT A.UNIDADE_FISICA,
A.CURSO, C.NOME, A.ALUNO, P.E_MAIL, P.CPF,VW.DISCIPLINA,D.NOME, VW.TURMA, VW.DT_INSERCAO
from LY_ALUNO A 
JOIN VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = A.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = VW.DISCIPLINA
WHERE 1=1--A.ANO_INGRESSO = 2018 AND A.SEM_INGRESSO = 1
AND VW.ANO = 2018 AND VW.SEMESTRE = 1
AND VW.TURMA IS NULL
AND A.UNIDADE_FISICA NOT IN ('OTE-JUA','OTE-PET', 'OTE-SP')
AND VW.DISCIPLINA IN 
('143699',
'143921',
'143922',
'143924',
'146632',
'147912',
'UDI412')
AND A.ALUNO NOT IN (SELECT TOP 1 1 FROM EADBOX..Matricula WHERE aluno = A.ALUNO AND disciplina = VW.DISCIPLINA AND ano = 2018 and semestre = 1 and matricula_eadbox is null)
AND A.SIT_ALUNO = 'Ativo' AND VW.SIT_MATRICULA not in ('Cancelado','Trancado')
--and A.ALUNO = '162060143'
ORDER BY 1,3,5