USE LYCEUM
GO

SELECT A.UNIDADE_FISICA
	, UF.NOME_COMP
	, C.TIPO
	, A.CURSO
	, C.NOME
	, A.SIT_ALUNO
	, A.ALUNO
	, A.NOME_COMPL
	,P.E_MAIL AS E_MAIL
	,ISNULL(P.DDD_FONE_CELULAR,P.DDD_FONE) AS DDD
	,ISNULL(P.FONE,'') AS FONE
	,ISNULL(P.CELULAR,'') AS CELULAR
	,ISNULL((SELECT TOP 1 'S' FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND SITUACAO_HIST NOT IN ('Trancado','Cancelado')),'N') AS POSSUI_HISTORICO
	,ISNULL((SELECT COUNT(DISTINCT CONCAT(ANO,SEMESTRE)) FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND SITUACAO_HIST NOT IN ('Trancado','Cancelado')),0) AS QTD_PERIODOS_ESTUDADOS
--INTO #TEMP
FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
WHERE A.SIT_ALUNO <> 'Ativo'-- AND A.CURSO IN ('722','354')
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
ORDER BY 1,4