

USE FTC_DATAMART
GO

SELECT ANO,SEMESTRE,ALUNO, TIPO_FINAN
FROM BI_REMATRICULA BI
WHERE BI.TIPO_FINAN NOT IN ('PROUNI INTEGRAL','PROIES')
AND EXISTS (SELECT TOP 1 1 
			FROM BI_REMATRICULA BI2 
			WHERE BI2.ALUNO = BI.ALUNO AND BI2.TIPO_FINAN IN ('PROUNI INTEGRAL','PROIES') AND CONCAT(BI.ANO,BI.SEMESTRE) > CONCAT(BI2.ANO,BI2.SEMESTRE))

SELECT ANO, SEMESTRE,TIPO_FINAN,STATUS_FTC FROM BI_REMATRICULA WHERE ALUNO = '181050960' ORDER BY 1,2

DECLARE @p_ano VARCHAR(4) = '2017'
DECLARE @p_semestre VARCHAR(2) = '1'
DECLARE @p_aluno VARCHAR(20) = '171031126'

--UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
SELECT *
FROM BI_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_100','PROUNI100') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND (B.ANOINI IS NULL OR B.ANOINI <= (SELECT YEAR(DT_INICIO) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)) 
--AND (B.MESINI IS NULL OR B.MESINI <= (SELECT MONTH(DT_INICIO) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)) 
AND (B.ANOFIM IS NULL OR B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)) 
AND (B.MESFIM IS NULL OR B.MESFIM <= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)))
AND BI.ALUNO = @p_aluno




DECLARE @p_ano VARCHAR(4) = '2017'
DECLARE @p_semestre VARCHAR(2) = '1'
DECLARE @p_aluno VARCHAR(20) = '171040967'


--UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
SELECT *
FROM BI_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_100','PROUNI100') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND (B.DATA_CANCEL IS NULL OR B.DATA_CANCEL > BI.DATA_PERIODO)
AND (B.ANOINI <= (SELECT YEAR(DT_INICIO) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)) 
--AND (B.MESINI IS NULL OR B.MESINI <= (SELECT MONTH(DT_INICIO) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)) 
--AND (B.MESFIM IS NULL OR B.MESFIM <= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)))
)AND BI.ALUNO = @p_aluno


SELECT * FROM LYCEUM..LY_TIPO_BOLSA WHERE TIPO_BOLSA = 'PROIES100'


SELECT * FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = 2018

SELECT COUNT(ALUNO),ANO,SEMESTRE,TIPO_FINAN
FROM BI_REMATRICULA
WHERE ANO = 2019
AND SEMESTRE = 1
AND TIPO_FINAN IN ('PROUNI INTEGRAL','PROIES')
GROUP BY ANO, SEMESTRE, TIPO_FINAN


SELECT TIPO_FINAN,* FROM BI_REMATRICULA WHERE ANO = 2017 AND SEMESTRE = 1 
AND CPF IN (SELECT * FROM #TEMP) ORDER BY CPF

SELECT CPF FROM #TEMP
EXCEPT
SELECT CPF FROM BI_REMATRICULA WHERE ANO = 2017 AND SEMESTRE = 1  

select * FROM LYCEUM..LY_ALUNO A
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
AND P.CPF = '86232222539'

SELECT * FROM LYCEUM..LY_PERIODO_LETIVO 

SELECT TIPO_FINAN,* FROM BI_REMATRICULA WHERE ALUNO = '172290245' ORDER BY 2,3

SELECT * FROM LYCEUM..LY_BOLSA WHERE ALUNO IN (SELECT ALUNO FROM BI_REMATRICULA WHERE TIPO_FINAN = 'PROUNI INTEGRAL' AND STATUS_FTC IN ('PRE-MATRICULADO PAGO','MATRICULADO PAGO','MATRICULADO NAO-PAGO') AND ANO = 2019 AND SEMESTRE = 1)