USE LYCEUM
GO

SELECT CURSO, FACULDADE, NOME
INTO #TEMP_CURSO --DROP TABLE #TEMP_CURSO
FROM LY_CURSO 
WHERE (NOME LIKE '%FARMACIA%' OR NOME LIKE '%BIOMEDICINA%') 
AND TIPO = 'GRADUACAO'

UPDATE #TEMP_CURSO SET NOME = 'Biomedicina' WHERE NOME LIKE '%Biomedicina%'
UPDATE #TEMP_CURSO SET NOME = 'Farmácia' WHERE NOME LIKE '%Farmácia%'

SELECT A.*,C.NOME
INTO #TEMP_ALUNOS --DROP TABLE #TEMP_ALUNOS
FROM LY_ALUNO A 
JOIN #TEMP_CURSO C ON C.CURSO = A.CURSO
WHERE SIT_ALUNO = 'Concluido'

INSERT INTO #TEMP_ALUNOS
SELECT A.*,C.NOME
FROM LY_ALUNO A 
JOIN #TEMP_CURSO C ON C.CURSO = A.CURSO
WHERE SIT_ALUNO IN ('Ativo','Inconcluido')
AND LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(ALUNO,'N') = 0

SELECT A.ALUNO, HM.ANO, HM.SEMESTRE, HM.DISCIPLINA, A.NOME
INTO #TEMP_HISTORICO --DROP TABLE #TEMP_HISTORICO
FROM LY_HISTMATRICULA HM
JOIN #TEMP_ALUNOS A ON A.ALUNO = HM.ALUNO
AND HM.SITUACAO_HIST IN ('Aprovado','Dispensado')

--SELECT *,C.NOME 
--FROM LY_CURRICULO CU
--JOIN #TEMP_CURSO C ON C.CURSO = CU.CURSO
--AND DT_EXTINCAO IS NULL
--AND ANO_INI = 2018 AND SEM_INI = 2

--BIOMED
SELECT DISCIPLINA, FORMULA_EQUIV, CURSO, TURNO, CURRICULO, 'Biomedicina' AS NOME
INTO #TEMP_GRADE --DROP TABLE #TEMP_GRADE
FROM LY_GRADE
WHERE CURSO = '3012' AND TURNO = 'N' AND CURRICULO = '201901'

--EXEC FTC_DESMEMBRA_EQUIVALENCIAS '3012','M','201901'

--FARMACIA
INSERT INTO #TEMP_GRADE
SELECT DISCIPLINA, FORMULA_EQUIV, CURSO, TURNO, CURRICULO, 'Farmácia' AS NOME
FROM LY_GRADE
WHERE CURSO = '3014' AND TURNO = 'N' AND CURRICULO = '201802'


--EXEC FTC_DESMEMBRA_EQUIVALENCIAS '290','M','201802'


SELECT A.ALUNO, COUNT(G.DISCIPLINA) QTD_DISCIPLINAS
INTO #TEMP_QTD --DROP TABLE #TEMP_QTD
FROM #TEMP_ALUNOS A
JOIN #TEMP_GRADE G ON G.NOME <> A.NOME
WHERE G.DISCIPLINA NOT IN (SELECT G1.DISCIPLINA 
							FROM #TEMP_HISTORICO H
							JOIN #TEMP_GRADE G1 ON G1.CURSO = G.CURSO AND G1.TURNO = G.TURNO AND G1.CURRICULO = G.CURRICULO 
							WHERE ((G.DISCIPLINA = H.DISCIPLINA) OR (H.DISCIPLINA = G.FORMULA_EQUIV) OR (G.FORMULA_EQUIV LIKE '%'+H.DISCIPLINA+'%')) AND H.ALUNO = A.ALUNO
							)--AND G.NOME <> A.NOME)
--AND A.ALUNO = '041042566'
--AND G.FORMULA_EQUIV LIKE '%145849%'
GROUP BY A.ALUNO,G.NOME

ALTER TABLE #TEMP_QTD
	ADD PERC_A_CUMPRIR DECIMAL(10,4)

UPDATE Q SET Q.PERC_A_CUMPRIR = Q.QTD_DISCIPLINAS/CASE WHEN A.NOME = 'Biomedicina' THEN 69.00 ELSE 51.00 END
FROM #TEMP_QTD Q
JOIN #TEMP_ALUNOS A ON A.ALUNO = Q.ALUNO


SELECT	UF.UNIDADE_FIS AS COD_UNIDADE
		,UF.NOME_COMP AS NOME_UNIDADE
		,C.CURSO AS COD_CURSO
		,C.NOME AS NOME_CURSO
		,Q.QTD_DISCIPLINAS
		,Q.PERC_A_CUMPRIR
		,(SELECT MAX(CONCAT(HM.ANO,'/',HM.SEMESTRE)) FROM #TEMP_HISTORICO HM WHERE HM.ALUNO = A.ALUNO) AS ULTIMO_PERIODO_CURSADO
		,A.ALUNO
		,ISNULL(P.DDD_FONE,'') AS DDD_FONE
		,ISNULL(P.FONE,'') AS FONE
		,ISNULL(P.DDD_FONE_CELULAR,'') AS DDD_FONE_CELULAR
		,ISNULL(P.CELULAR,'') AS CELULAR
		,ISNULL(P.E_MAIL,'') AS E_MAIL
FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN #TEMP_QTD Q ON Q.ALUNO = A.ALUNO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
JOIN LY_CURSO C ON C.CURSO = A.CURSO



--SELECT A.ALUNO, COUNT(G.FORMULA_EQUIV) QTD_DISCIPLINAS_EQUIV
--FROM #TEMP_ALUNOS A
--JOIN #TEMP_GRADE G ON G.NOME <> A.NOME
--WHERE G.FORMULA_EQUIV NOT IN (SELECT G1.FORMULA_EQUIV 
--							FROM #TEMP_HISTORICO H
--							JOIN #TEMP_GRADE G1 ON G1.CURSO = G.CURSO AND G1.TURNO = G.TURNO AND G1.CURRICULO = G.CURRICULO 
--							WHERE CONTAINS(G1.FORMULA_EQUIV,'') AND H.ALUNO = A.ALUNO
--							)--AND G.NOME <> A.NOME)
--AND A.ALUNO = '041042566'
----AND G.FORMULA_EQUIV LIKE '%145849%'
--GROUP BY A.ALUNO

--SELECT DISCIPLINA FROM LY_HISTMATRICULA WHERE ALUNO = '041042566' AND SITUACAO_HIST IN ('Aprovado','Dispensado') ORDER BY 1
--SELECT * FROM LY_ALUNO WHERE ALUNO = '041042566'
--3012	M	201901 BIOMED
--290	M	201802 FARMAC
--SELECT * FROM LYCEUMINTEGRACAO..DISCIPLINA_EQUIV WHERE CURSO = '290' AND TURNO = 'M' AND CURRICULO = '201802'
--select * FROM FTC_DATAMART..BI_REMATRICULA WHERE ALUNO = '101041536' ORDER BY 1,2
--SELECT DISTINCT SITUACAO_HIST FROM LY_HISTMATRICULA