use lyceum
go

--DROP TABLE #TEMP_COMP

select COUNT(VW.COBRANCA) AS QTD_COMPETENCIA, VW.ALUNO, CAST(0.00 AS DECIMAL(10,2)) AS VALOR_DIVIDA, CAST(0.00 AS DECIMAL(10,2)) AS VALOR_COBRANCAS_GERADAS 
INTO #TEMP_COMP
FROM VW_COBRANCA VW
JOIN LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
JOIN LY_CURSO CUR ON CUR.CURSO = A.CURSO
JOIN FTC_DATAMART..BI_REMATRICULA BI ON BI.ALUNO = VW.ALUNO AND BI.ANO = 2019 AND BI.SEMESTRE = 1
WHERE C.NUM_COBRANCA = 1
AND VW.ANO = 2019
AND VW.MES BETWEEN 1 AND 6
AND CUR.TIPO IN ('GRADUACAO','TECNOLOGO')
--AND BI.TIPO_FINAN = 'FIES'
AND VW.ESTORNO = 'N'
AND BI.STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NAO-PAGO','PRE-MATRICULADO PAGO')
GROUP BY VW.ALUNO
HAVING COUNT(VW.COBRANCA) < 6

--VALOR DIVIDA

UPDATE T SET T.VALOR_DIVIDA = (SELECT SUM(LD.VALOR)
							   FROM LY_LANC_DEBITO LD 
							   WHERE LD.ALUNO = T.ALUNO 
							   AND LD.ANO_REF = 2019 
							   AND LD.PERIODO_REF =1 
							   AND LD.CODIGO_LANC = 'MS')
FROM #TEMP_COMP T


-- VALOR COBRANCAS GERADAS

UPDATE T SET T.VALOR_COBRANCAS_GERADAS = (SELECT SUM(IL.VALOR)
							   FROM LY_LANC_DEBITO LD 
							   JOIN LY_ITEM_LANC IL ON IL.LANC_DEB = LD.LANC_DEB
							   WHERE LD.ALUNO = T.ALUNO 
							   AND LD.ANO_REF = 2019 
							   AND LD.PERIODO_REF =1 
							   AND LD.CODIGO_LANC = 'MS'
							   AND IL.NUM_BOLSA IS NULL
							   AND ITEM_ESTORNADO IS NULL)
FROM #TEMP_COMP T

SELECT sum(T.VALOR_DIVIDA)-sum(T.VALOR_COBRANCAS_GERADAS) FROM #TEMP_COMP T
--WHERE EXISTS (SELECT TOP 1 1 FROM VW_COBRANCA VW WHERE VW.ALUNO = T.ALUNO AND CONCAT(ANO,MES) = '20196')
WHERE VALOR_DIVIDA <> VALOR_COBRANCAS_GERADAS



SELECT SUM(IL.VALOR)
							   FROM LY_LANC_DEBITO LD 
							   JOIN LY_ITEM_LANC IL ON IL.LANC_DEB = LD.LANC_DEB
							   JOIN #TEMP_COMP T ON T.ALUNO = IL.ALUNO
							   WHERE LD.ALUNO = T.ALUNO 
							   AND LD.ANO_REF = 2019 
							   AND LD.PERIODO_REF =1 
							   AND LD.CODIGO_LANC = 'MS'
							   AND IL.NUM_BOLSA IS NULL
							   AND ITEM_ESTORNADO IS NULL
							   AND IL.PARCELA = 6 
							   AND T.VALOR_DIVIDA <> T.VALOR_COBRANCAS_GERADAS
