USE FTC_DATAMART
GO

select ANO_INGRESSO, SEM_INGRESSO, COUNT(ALUNO) QTD_INGRESSANTES 
FROM BI_REMATRICULA WHERE CURSO = '354' AND TIPO_ALUNO = 'CALOURO'
GROUP BY ANO_INGRESSO, SEM_INGRESSO
ORDER BY 1,2

select ANO, SEMESTRE, COUNT(ALUNO) QTD_INGRESSANTES 
FROM BI_REMATRICULA WHERE CURSO = '354' AND STATUS_FTC = 'CONCLUIDO'
GROUP BY ANO, SEMESTRE
ORDER BY 1,2

SELECT BI.ALUNO, BI.ANO_INGRESSO, BI.SEM_INGRESSO, COUNT(CONCAT(BI.ANO,BI.SEMESTRE)) QTD_PERIODOS
INTO #TEMP_ALUNOS
FROM BI_REMATRICULA BI
WHERE BI.STATUS_FTC NOT IN ('EVADIDO','CANCELADO','TRANSFERIDO','TRANCADO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA WHERE ALUNO = BI.ALUNO AND STATUS_FTC = 'CONCLUIDO')
GROUP BY BI.ALUNO, BI.ANO_INGRESSO, BI.SEM_INGRESSO


SELECT * FROM BI_REMATRICULA WHERE ALUNO = '081030224'
ORDER BY 1,2
