--#TEMP ALUNOS Q ESTAO NA PLANILHA E NO BI
--#CPF ALUNOS QUE ESTAO NA PLANILHA
--#TEMP3 ALUNOS QUE ESTAO NO BI COMO FIES OU FIES + PROUNI


SELECT * INTO #TEMP3 FROM BI_REMATRICULA
WHERE ANO = 2018 AND SEMESTRE = 2 
AND TIPO_FINAN IN ('FIES','FIES+PROUNI')

SELECT CPF INTO #TEMP FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2
AND CPF IN (SELECT CPF FROM #CPF)


SELECT CPF INTO #TEMP4 FROM #TEMP3
EXCEPT
SELECT CPF FROM #CPF


SELECT * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND ALUNO IN (
SELECT DISTINCT ALUNO FROM LYCEUM..LY_BOLSA WHERE ALUNO IN (
SELECT ALUNO FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND CPF IN (SELECT CPF FROM #TEMP4))
AND ANOINI = 2018 AND MESINI BETWEEN 7 AND 12
AND TIPO_BOLSA LIKE '%FIES%'
AND DATA_CANCEL IS NULL
)

SELECT * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND ALUNO IN (
SELECT DISTINCT ALUNO FROM LYCEUM..LY_BOLSA WHERE ALUNO IN (
SELECT ALUNO FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND CPF IN (SELECT CPF FROM #TEMP4))
AND ANOINI = 2018 AND MESINI BETWEEN 7 AND 12
AND TIPO_BOLSA LIKE '%FIES%'
AND DATA_CANCEL IS NOT NULL)


SELECT * FROM LYCEUM..LY_BOLSA WHERE ALUNO IN (
SELECT ALUNO FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND CPF IN (SELECT CPF FROM #TEMP4))
AND ANOINI = 2018 AND MESINI BETWEEN 7 AND 12
AND TIPO_BOLSA LIKE '%FIES%'
AND DATA_CANCEL IS NULL