SELECT DISTINCT  
 SS.SOLICITACAO
 ,BI.NOME_UNIDADE_ENSINO_ALUNO
 ,BI.TIPO_CURSO
 ,BI.NOME_CURSO
,SS.ALUNO
,CONVERT(VARCHAR(10),SS.DATA,103) AS DATA_ABERTURA
,IIF(A.STATUS = 'Deferido','S','N') AS DEFERIDO
,CONVERT(VARCHAR(10),A.DATA,103)AS DATA_ANDAMENTO
,CONVERT(VARCHAR(10),H.DT_ENCERRAMENTO,103) AS DATA_ENCERRAMENTO
--,CONVERT(VARCHAR(10),SS.DATA,103) AS DATA_ABERTURA
--,CONVERT(VARCHAR(10),A.DATA,103) AS DATA_ANDAMENTO
--,ISNULL(CONVERT(VARCHAR(10),H.DT_ENCERRAMENTO,103),'') AS DATA_ENCERRAMENTO
,A.STATUS
,ISS.SERVICO
--,CAST(0 AS INT) AS DIF_DIAS
INTO #TEMP --DROP TABLE #TEMP
FROM  LYCEUM..LY_SOLICITACAO_SERV SS
LEFT JOIN LYCEUM..LY_ITENS_SOLICIT_SERV ISS ON ISS.SOLICITACAO = SS.SOLICITACAO
JOIN LYCEUM..LY_TABELA_SERVICOS TS ON TS.SERVICO = ISS.SERVICO
LEFT JOIN LYCEUM..LY_ANDAMENTO A ON A.SERVICO = ISS.SERVICO AND A.SOLICITACAO = SS.SOLICITACAO AND A.STATUS NOT IN ('Executado','Cancelado')
JOIN BI_ACOMP_MATR BI ON BI.ALUNO = SS.ALUNO
LEFT JOIN LYCEUM..LY_H_CURSOS_CONCL H ON H.ALUNO = SS.ALUNO
--WHERE ISS.SERVICO IN ('AOL_TRANMAT_VET','AOL_TRANMAT','AOL_TRANMATMED')
WHERE ISS.SERVICO IN ('AOL_CANCM','AOL_CANCM_VET','AOL_CANCONV','AOL_CANCUNI','AOL_CANFOR','AOL_TRANMAT','AOL_TRANMAT_VET','AOL_TRANMATMED','AOL_TRANSFEXT','AOL_TRANSFEXT_VET')
AND BI.ANO = 2019 AND BI.SEMESTRE = 1 AND BI.TIPO_ALUNO = 'CALOURO'
AND SS.DATA > '2018-11-01'
AND BI.PAGO = 1


UPDATE #TEMP SET DIF_DIAS = DATEDIFF(DAY,DATA_ABERTURA,DATA_ANDAMENTO)

DELETE T FROM #TEMP T
WHERE EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ANDAMENTO A WHERE A.SOLICITACAO = T.SOLICITACAO AND A.STATUS = 'Cancelado')


SELECT * 
FROM #TEMP 
WHERE DEFERIDO = 'S'
AND DATA_ENCERRAMENTO IS NOT NULL
ORDER BY 8 DESC,2,4
