

--ANTECIPAÇÃO SIM OU NAO
UPDATE T SET T.ANTECIP_FINAN = 'S', T.TIPO_ANTECIP = X.TIPO_PAGAMENTO, T.DT_ANTECIP = CONVERT(VARCHAR(10),X.DATA,103), T.VALOR_ATENCIP = X.VALOR
FROM BI_REMATRICULA T
JOIN (SELECT DISTINCT A.ALUNO,LD.ANO_REF, LD.PERIODO_REF, LC.TIPO_PAGAMENTO, LC.DATA, (SELECT SUM(VALOR)*-1 FROM LYCEUM..LY_ITEM_CRED IC 
			JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
			WHERE C.ALUNO = A.ALUNO 
			AND CONVERT(VARCHAR(10),IC.DATA,103) = CONVERT(VARCHAR(10),LP.DATA,103)
			AND IC.TIPO_ENCARGO IS NULL
			AND IC.TIPODESCONTO IS NULL
			AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC2 WHERE IC2.LANC_CRED = IC.LANC_CRED AND IC2.ITEM_ESTORNADO IS NOT NULL)
			) AS VALOR
		FROM LYCEUM..LY_ITEM_CRED LP
		JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = LP .LANC_CRED
		JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
		JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
		JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
		JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
		WHERE C.NUM_COBRANCA = 1 AND C.ESTORNO = 'N' AND C.DT_ESTORNO IS NULL
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC WHERE IC.LANC_CRED = LP.LANC_CRED AND IC.ITEM_ESTORNADO IS NOT NULL)) X ON X.ALUNO = T.ALUNO AND X.ANO_REF = T.ANO AND T.SEMESTRE = X.PERIODO_REF
WHERE X.DATA < T.DATA_PERIODO AND T.TIPO_ALUNO = 'VETERANO'
		

--DATA DA ANTECIPAÇÃO

UPDATE T SET T.DT_ANTECIP = (SELECT MIN(CONVERT(VARCHAR(10),LP.DATA,103)) FROM LYCEUM..FTC_VW_LANCAMENTOS_PAGAMENTOS LP
			  JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
			  JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
			  JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
			  JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
			  WHERE LP.DATA < T.DATA_PERIODO
			  AND LP.LANC_CRED IS NOT NULL
			  AND C.NUM_COBRANCA = 1
			  AND A.ALUNO = T.ALUNO
			  AND LD.ANO_REF = T.ANO
			  AND LD.PERIODO_REF = T.SEMESTRE
			  )
FROM BI_REMATRICULA T
WHERE ANTECIP_FINAN = 'S'

--VALOR DA ANTECIPAÇÃO
UPDATE BI2 SET BI2.VALOR_ATENCIP = (select SUM(IC.VALOR) *-1
FROM LYCEUM..LY_ITEM_CRED IC 
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
JOIN BI_REMATRICULA BI ON BI.ALUNO = C.ALUNO
WHERE C.ALUNO = BI.ALUNO
AND C.ANO = BI.ANO AND C.MES BETWEEN CASE WHEN BI.SEMESTRE = 1 THEN 1 ELSE 7 END AND CASE WHEN BI.SEMESTRE = 1 THEN 6 ELSE 12 END
AND C.NUM_COBRANCA = 1 AND IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
AND BI.ANO = BI2.ANO AND BI.SEMESTRE = BI2.SEMESTRE
AND BI.ALUNO = BI2.ALUNO
AND IC.DATA < BI.DATA_PERIODO
)
FROM BI_REMATRICULA BI2
WHERE ANTECIP_FINAN = 'S'



select top 50 *
--select SUM(IC.VALOR) *-1
FROM LYCEUM..LY_ITEM_CRED IC 
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
JOIN BI_REMATRICULA BI ON BI.ALUNO = C.ALUNO
WHERE C.ALUNO = BI.ALUNO
AND C.ANO = BI.ANO AND C.MES BETWEEN CASE WHEN BI.SEMESTRE = 1 THEN 1 ELSE 7 END AND CASE WHEN BI.SEMESTRE = 1 THEN 6 ELSE 12 END
AND C.NUM_COBRANCA = 1 AND IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
AND BI.ANO = 2019 AND BI.SEMESTRE = 1
--AND BI.ALUNO = '181070039'
AND IC.DATA < BI.DATA_PERIODO

--select SUM(IC.VALOR) *-1
select *
FROM LYCEUM..LY_ITEM_CRED IC 
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
JOIN BI_REMATRICULA BI ON BI.ALUNO = C.ALUNO
WHERE C.ALUNO = BI.ALUNO
AND C.ANO = BI.ANO AND C.MES BETWEEN CASE WHEN BI.SEMESTRE = 1 THEN 1 ELSE 7 END AND CASE WHEN BI.SEMESTRE = 1 THEN 6 ELSE 12 END
AND C.NUM_COBRANCA = 1 AND IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
AND BI.ANO = '2019' AND BI.SEMESTRE = '1'
AND BI.ALUNO = '182030128'
AND IC.DATA < BI.DATA_PERIODO



/*
182030128
181051023
181050870
182050110
181041463
142040183
161050143
*/

SELECT DISTINCT A.ALUNO
		, LD.ANO_REF
		, LD.PERIODO_REF
		, C.NUM_COBRANCA
		, LC.TIPO_PAGAMENTO
		, LC.DATA
		, (SELECT SUM(VALOR)*-1 FROM LYCEUM..LY_ITEM_CRED IC 
			JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
			WHERE C.ALUNO = A.ALUNO 
			AND CONVERT(VARCHAR(10),IC.DATA,103) = CONVERT(VARCHAR(10),LC.DATA,103)
			AND IC.TIPO_ENCARGO IS NULL
			AND IC.TIPODESCONTO IS NULL
			AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC2 WHERE IC2.LANC_CRED = LP.LANC_CRED AND IC2.ITEM_ESTORNADO IS NOT NULL))
		FROM LYCEUM..LY_ITEM_CRED LP
		JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = LP .LANC_CRED
		JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
		JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
		JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
		JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
		WHERE C.ALUNO = '152040085'
		AND LD.ANO_REF = 2019 AND LD.PERIODO_REF = 1
		AND C.NUM_COBRANCA = 1
		AND LC.DATA < '2019-01-01'
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC WHERE IC.LANC_CRED = LP.LANC_CRED AND IC.ITEM_ESTORNADO IS NOT NULL)
		--GROUP BY A.ALUNO, LD.ANO_REF, LD.PERIODO_REF, C.NUM_COBRANCA, LC.TIPO_PAGAMENTO, LC.DATA, LP.LANC_CRED, C.COBRANCA

		select * FROM BI_REMATRICULA WHERE ANTECIP_FINAN = 'S' AND ANO = 2019 AND SEMESTRE = 1 AND ALUNO = '171040080'
		

		select * FROM LYCEUM..LY_ITEM_CRED WHERE LANC_CRED = '3080623' AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
		select * FROM LYCEUM..LY_COBRANCA WHERE COBRANCA = '5853685'


		SELECT SUM(VALOR)*-1 FROM LYCEUM..LY_ITEM_CRED IC 
			JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
			WHERE C.ALUNO = '152040085'
			AND CONVERT(VARCHAR(10),IC.DATA,103) = CONVERT(VARCHAR(10),'29/10/2018',103)
			AND IC.TIPO_ENCARGO IS NULL
			AND IC.TIPODESCONTO IS NULL
			AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC WHERE IC.LANC_CRED = LP.LANC_CRED AND IC.ITEM_ESTORNADO IS NOT NULL)


		SELECT SUM(VALOR)*-1 FROM LYCEUM..LY_ITEM_CRED IC 
			JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
			WHERE C.ALUNO = '152040085'
			AND IC.DATA BETWEEN '2018-10-29' AND '2018-10-30'
			AND IC.TIPO_ENCARGO IS NULL
			AND IC.TIPODESCONTO IS NULL
			AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC2 WHERE IC2.LANC_CRED = IC.LANC_CRED AND IC2.ITEM_ESTORNADO IS NOT NULL)

			SELECT CAST('2018-10-29 10:59:10.487' AS VARCHAR(10))
			SELECT CONVERT(VARCHAR(10),'2018-10-29 10:59:10.487',103)