--BEGIN TRANSACTION

DELETE LPD FROM LY_NOTA LPD
JOIN LY_TURMA T ON T.DISCIPLINA = LPD.DISCIPLINA
JOIN LY_CURSO C ON C.CURSO = T.CURSO
WHERE C.FACULDADE IN ('52')
AND (T.CURSO LIKE '5_EF%' OR T.CURSO LIKE '5_EM%')
GO

--COMMIT
--ROLLBACK