SELECT	DISTINCT 
		ANO, 
		SEMESTRE, 
		STATUS_FTC, 
		NOME_UNIDADE_ENSINO_ALUNO, 
		NOME_CURSO, 
		ALUNO, 
		SERIE_CALCULADA AS SERIE,
		SOLICITOU_PLANO,
		SOLICITOU_HIST,
		QTD_INADIMP, 
		INDICE_REPROVACAO, 
		PERC_FALTAS,
		BOLSISTA,
		TURNO,
		TIPO_FINAN,
		TIPO_INGRESSO,
		VALOR_MENSALIDADE,
		ANTECIP_FINAN,
		P.RENDA_MENSAL,
		P.DT_NASC,
		P.SEXO,
		P.COR_RACA,
		P.EST_CIVIL,
		P.CONTRIBUI_RENDA
FROM BI_REMATRICULA BI
JOIN LYCEUM..LY_PESSOA P ON P.CPF = BI.CPF
WHERE ANO >= 2018
--AND STATUS_FTC IN ('EVADIDO','CANCELADO','TRANSFERIDO','TRANCADO')
AND SERIE_CALCULADA > 1


SELECT DISTINCT PERC_FALTAS FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1

SELECT DISTINCT PERC_PRESENCA FROM LYCEUM..LY_HISTMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1
AND SITUACAO_HIST NOT IN ('Dispensado','Trancado','Cancelado') 

SELECT AVG(0.02)