USE FTC_DATAMART
GO

CREATE TABLE BASE_CEP --DROP TABLE BASE_CEP
(
	UF VARCHAR(2),
	MUNICIPIO VARCHAR(100),
	BAIRRO VARCHAR(100),
	CEP VARCHAR(9),
	CODIGO_IBGE VARCHAR(15),
	CODIGO_LYCEUM VARCHAR(20)
)

SELECT DISTINCT  M.UF, M.NOME AS MUNICIPIO, ISNULL(B.NOME,'') AS BAIRRO, MIN(TRL.CEP) AS CEP, M.CODIGO_IBGE, M.MUNICIPIO AS CODIGO_LYCEUM
INTO #TEMP_CEP --DROP TABLE #TEMP_CEP
FROM LYCEUM..HD_TRECHO_LOGRADOURO TRL
JOIN LYCEUM..HD_LOGRADOURO L ON L.LOGRADOURO = TRL.LOGRADOURO
JOIN LYCEUM..HD_TIPO_LOGRADOURO TPL ON TPL.TIPO_LOGR = L.TIPO_LOGR
JOIN LYCEUM..HD_BAIRRO B ON B.BAIRRO = TRL.BAIRRO
RIGHT JOIN LYCEUM..HD_MUNICIPIO M ON M.MUNICIPIO = TRL.MUNICIPIO
GROUP BY M.UF,M.NOME, B.NOME,M.CODIGO_IBGE,M.MUNICIPIO

UPDATE T SET T.CEP = M.CEP
FROM #TEMP_CEP T
JOIN LYCEUM..HD_MUNICIPIO M ON M.NOME = T.MUNICIPIO AND M.UF = T.UF AND T.CODIGO_LYCEUM = M.MUNICIPIO
WHERE T.CEP IS NULL AND T.BAIRRO = ''

UPDATE T SET T.CODIGO_IBGE = '0000000'
FROM #TEMP_CEP T
WHERE T.CODIGO_IBGE IS NULL


UPDATE T SET T.BAIRRO= T.MUNICIPIO
FROM #TEMP_CEP T
WHERE T.BAIRRO IS NULL OR T.BAIRRO = ''

DELETE FROM #TEMP_CEP WHERE CEP IS NULL

INSERT INTO BASE_CEP
SELECT * FROM #TEMP_CEP
ORDER BY 1,2,3

SELECT DISTINCT BI.BAIRRO, B.BAIRRO FROM BI_REMATRICULA BI
JOIN BASE_CEP B ON B.CEP = BI.CEP
WHERE B.CODIGO_LYCEUM = '00988'