USE FTC_DATAMART
GO

--EXEC BI_AUX_DMP_CURSOS_JOB 

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_AUX_DMP_CURSOS_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_AUX_DMP_CURSOS_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_AUX_DMP_CURSOS_JOB
        
-- [INÍCIO]                    
AS  

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_AUX_DMP_CURSOS'))   
BEGIN
	DROP TABLE BI_AUX_DMP_CURSOS
END

ELSE 

BEGIN
CREATE TABLE BI_AUX_DMP_CURSOS
(
	NOME_CURSO VARCHAR(200)
)

INSERT INTO BI_AUX_DMP_CURSOS
SELECT DISTINCT NOME_CURSO FROM BI_DMP2
UNION
SELECT DISTINCT NOME_CURSO FROM BI_AUX_DMP_METAS ORDER BY 1

END