USE FTC_DATAMART
GO

--EXEC BI_ACOMP_MATR_JOB 2020,1

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_ACOMP_MATR_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_ACOMP_MATR_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_ACOMP_MATR_JOB
(            
  @p_ano VARCHAR(4)
, @p_semestre VARCHAR(2) 

)            
AS            
-- [INÍCIO]                    
BEGIN    

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_ACOMP_MATR'))   
BEGIN
	DELETE FROM BI_ACOMP_MATR WHERE ANO = @p_ano AND SEMESTRE = @p_semestre
END        

ELSE
BEGIN        
CREATE TABLE BI_ACOMP_MATR --DROP TABLE BI_ACOMP_MATR
(
	[ANO] VARCHAR(4),
	[SEMESTRE] VARCHAR(2),
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(20),
	[NOME_UNIDADE_ENSINO_ALUNO] VARCHAR(100),
	[TIPO_CURSO] VARCHAR(50),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR(100),
	[SERIE] NUMERIC(10),
	[TURNO] VARCHAR(20),
	[CONCURSO] VARCHAR(20),
	[DESC_CONCURSO] VARCHAR(100),
	[TIPO_ALUNO] VARCHAR(50),
	[TIPO_INGRESSO] VARCHAR(50),
	[TIPO_FINAN] VARCHAR(50),
	[PAGO] NUMERIC(10),
	[NAO_PAGO] NUMERIC(10),
	[BOLSISTA] VARCHAR(1),
	[DATA_PAGAMENTO] DATETIME,
	[SIT_MATRICULA] VARCHAR(20),
	[DATA_MATRICULA] DATETIME,
	[DATA_CANCELAMENTO] DATETIME,
	[ORIGEM_MATRICULA] VARCHAR(50),
	[DATA_INGRESSO] DATETIME,
	[ALUNO] VARCHAR(20),
	[CPF] VARCHAR(20),
	[NOME_ALUNO] VARCHAR(100),
	[CURRICULO] VARCHAR(20),
	[DATA_NASC] DATETIME,
	[RG] VARCHAR(20),
	[E_MAIL] VARCHAR(100),
	[ENDERECO] VARCHAR(50),
	[NUMERO] VARCHAR(20),
	[COMPLEMENTO] VARCHAR(50),
	[CEP] VARCHAR(9),
	[BAIRRO] VARCHAR(50),
	[CIDADE] VARCHAR(100),
	[ESTADO] VARCHAR(2),
	[DDD_FONE] VARCHAR(3),
	[FONE] VARCHAR(30),
	[DDD_CELULAR] VARCHAR(3),
	[CELULAR] VARCHAR(30),
	[CONTRATO_ACEITO] VARCHAR(1),
	[BOLSAS] VARCHAR(100),
	[DATA_MATRICULA_ORC] VARCHAR(10),
	[CANDIDATO] VARCHAR(50),
	[TIPO_CREDITO] VARCHAR(50),
	[DATA_VENCIMENTO] DATETIME,
	[DATA_VENCIMENTO_ORI] DATETIME,
	[TIPO_PAGAMENTO] VARCHAR(50)

)
END


--CRIACAO DA TABELA ESPELHO PRE INSERT NA FISICA

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.TEMP_ALUNOS'))   
BEGIN
	DROP TABLE TEMP_ALUNOS
END  

CREATE TABLE TEMP_ALUNOS --DROP TABLE TEMP_ALUNOS
(
	[ANO] VARCHAR(4),
	[SEMESTRE] VARCHAR(2),
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(20),
	[NOME_UNIDADE_ENSINO_ALUNO] VARCHAR(100),
	[TIPO_CURSO] VARCHAR(50),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR(100),
	[SERIE] NUMERIC(10),
	[TURNO] VARCHAR(20),
	[CONCURSO] VARCHAR(20),
	[DESC_CONCURSO] VARCHAR(100),
	[TIPO_ALUNO] VARCHAR(50),
	[TIPO_INGRESSO] VARCHAR(50),
	[TIPO_FINAN] VARCHAR(50),
	[PAGO] NUMERIC(10),
	[NAO_PAGO] NUMERIC(10),
	[BOLSISTA] VARCHAR(1),
	[DATA_PAGAMENTO] DATETIME,
	[SIT_MATRICULA] VARCHAR(20),
	[DATA_MATRICULA] DATETIME,
	[DATA_CANCELAMENTO] DATETIME,
	[ORIGEM_MATRICULA] VARCHAR(50),
	[DATA_INGRESSO] DATETIME,
	[ALUNO] VARCHAR(20),
	[CPF] VARCHAR(20),
	[NOME_ALUNO] VARCHAR(100),
	[CURRICULO] VARCHAR(20),
	[DATA_NASC] DATETIME,
	[RG] VARCHAR(20),
	[E_MAIL] VARCHAR(100),
	[ENDERECO] VARCHAR(50),
	[NUMERO] VARCHAR(20),
	[COMPLEMENTO] VARCHAR(50),
	[CEP] VARCHAR(9),
	[BAIRRO] VARCHAR(50),
	[CIDADE] VARCHAR(100),
	[ESTADO] VARCHAR(2),
	[DDD_FONE] VARCHAR(3),
	[FONE] VARCHAR(30),
	[DDD_CELULAR] VARCHAR(3),
	[CELULAR] VARCHAR(30),
	[CONTRATO_ACEITO] VARCHAR(1),
	[BOLSAS] VARCHAR(100),
	[DATA_MATRICULA_ORC] VARCHAR(10),
	[CANDIDATO] VARCHAR(50),
	[TIPO_CREDITO] VARCHAR(50),
	[DATA_VENCIMENTO] DATETIME,
	[DATA_VENCIMENTO_ORI] DATETIME,
	[TIPO_PAGAMENTO] VARCHAR(50)

)


--ALIMENTANDO TEMPORARIA COM TODOS OS ALUNOS DO FILTRO
	INSERT INTO TEMP_ALUNOS
	SELECT  DISTINCT  
		PM.ANO								AS [ANO],    
		PM.SEMESTRE							AS [SEMESTRE],
		 C.FACULDADE						AS [UNIDADE_ENSINO_ALUNO],       
		 A.UNIDADE_FISICA					AS [NOME_UNIDADE_ENSINO_ALUNO],
		 C.TIPO								AS [TIPO_CURSO],      
		 C.CURSO							AS [CURSO],        
		 C.NOME								AS [NOME_CURSO],
		 A.SERIE							AS [SERIE],
		 A.TURNO							AS [TURNO],
		 A.CONCURSO							AS [CONCURSO],
		 ISNULL(CON.DESCRICAO,'')			AS [DESC_CONCURSO],
		 CASE WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < CONCAT(@p_ano,@p_semestre) THEN 'VETERANO' ELSE 'CALOURO' END AS TIPO_ALUNO,     
		A.TIPO_INGRESSO ,    
		NULL							AS [TIPO_FINAN],
		 1								AS [PAGO],
		 0								AS [NAO_PAGO],
		 'N' AS [BOLSISTA],
		 (SELECT MIN(IC.DATA)
				FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA 
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IC.COBRANCA AND VW.COBRANCA = IL.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL AND IC.ITEM_ESTORNADO IS NULL
				AND VW.VALOR <=1
				AND VW.ALUNO = A.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre			
				)					AS [DATA_PAGAMENTO],
		 'Sem-Matrícula' AS [SIT_MATRICULA],
		 (SELECT MIN(DT_INSERCAO) FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre) AS [DATA_MATRICULA],
		 NULL AS DATA_CANCELAMENTO,
		 CASE WHEN PM2.OBS IS NULL OR RTRIM(LTRIM(PM2.OBS)) = '' THEN 'Secretaria' ELSE 'Aluno Online' END AS [ORIGEM_MATRICULA],
		 A.DT_INGRESSO AS [DATA_INGRESSO],
		 PM.ALUNO,
		 P.CPF,
		 A.NOME_COMPL			AS [NOME_ALUNO],
		 A.CURRICULO,
		 P.DT_NASC				AS [DATA_NASC],
		 P.RG_NUM				AS [RG],     
		 P.E_MAIL               AS [E_MAIL],    
		 P.ENDERECO             AS [ENDERECO],    
		 P.END_NUM              AS [NUMERO],    
		 P.END_COMPL            AS [COMPLEMENTO],    
		 P.CEP					AS [CEP],    
		 P.BAIRRO				AS [BAIRRO],  
		 HM.NOME                AS [CIDADE],    
		 HM.UF					AS [ESTADO],     
		 ISNULL(P.DDD_FONE,'')				AS [DDD_FONE],
		 ISNULL(P.FONE,'')                 AS [FONE], 
		 ISNULL(P.DDD_FONE_CELULAR,'')		AS [DDD_CELULAR],    
		 ISNULL(P.CELULAR,'')                AS [CELULAR],
		 ISNULL((SELECT TOP 1 CONTRATO_ACEITO FROM LYCEUM..LY_CONTRATO_ALUNO WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND PERIODO = @p_semestre),'N') AS [CONTRATO_ACEITO],
		 '' AS [BOLSAS],
		 '' AS [DATA_MATRICULA_ORC],
		 A.CANDIDATO						AS [CANDIDATO],
		 '' AS TIPO_CREDITO,
		 '' AS DATA_VENCIMENTO,
		 '' AS DATA_VENCIMENTO_ORI,
		 '' AS TIPO_PAGAMENTO
	FROM LYCEUM..LY_ALUNO A 
	JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA            
	JOIN LYCEUM..VW_MATRICULA_E_PRE_MATRICULA PM ON PM.ALUNO = A.ALUNO
	LEFT JOIN LYCEUM..LY_PRE_MATRICULA PM2 ON PM2.ALUNO = PM.ALUNO AND PM2.ANO = PM.ANO AND PM2.SEMESTRE = PM.SEMESTRE AND PM2.DISCIPLINA = PM.DISCIPLINA AND PM2.TURMA = PM.TURMA
	JOIN LYCEUM..LY_CURSO C ON A.CURSO = C.CURSO AND C.TIPO NOT IN ('POS-GRADUACAO','EXTENSAO')
	JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON C.FACULDADE = UE.UNIDADE_ENS
	JOIN LYCEUM..HD_MUNICIPIO HM ON HM.MUNICIPIO = P.END_MUNICIPIO 
	LEFT JOIN LYCEUM..LY_CONCURSO CON ON CON.CONCURSO = A.CONCURSO
	WHERE 1=1 
	AND (EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB	/*PAGAMENTO REAL NUMA COBRANÇA DE MENSALIDADE*/
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = PM.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo'))

		OR EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = PM.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1			/*BOLSA 100%  NO PERIODO LETIVO EM UMA DAS PARCELAS DO TIPO ABAIXO*/
					AND (B.ANOINI >= YEAR(GETDATE()) 
					AND B.TIPO_BOLSA IN ('IMES','BF PCD','PARES','BAFFFTC','BINCRH')
					AND (B.MESINI = CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END))
					
					)
		OR EXISTS (SELECT TOP 1 1 AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = PM.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM = @p_ano) 
					AND (B.MESFIM = CASE WHEN @p_semestre = 1 THEN 6 ELSE 12 END)
					)

		OR EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = A.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1		/*BOLSA 100% SEM FIM*/
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL)
		
		OR EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B 
					WHERE 1=1
					AND (B.TIPO_BOLSA = 'CREDEDUC' OR B.TIPO_BOLSA LIKE '%QUERO%' OR B.TIPO_BOLSA LIKE '%EDUCA%')
					AND B.ALUNO = PM.ALUNO
					AND B.DATA_CANCEL IS NULL			/*BOLSA ESPECIFICA CREDEDUC/QUEROBOLSA/EDUCAMAIS - NÃO CANCELADA E EM VIGÊNCIA*/
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL)
					
				)
		

--BOLSA FIES TEMP *SOLICITADO POR ANDRÉ BRITTO / ANA PAULA GOMES em 25/03/2019*
	OR EXISTS (SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = A.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
					)

		OR EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO			/*CONTRAFO FIES NO PERÍODO*/
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = A.ALUNO)					
					
		OR EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS','SM','MS_EB')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = A.ALUNO
					AND VW.ANO = @p_ano
					AND VW.ESTORNO = 'N'
					AND (IL.DESCRICAO LIKE '%Acerto%' OR IL.DESCRICAO LIKE '%Restitu%')
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11') THEN 6 WHEN @p_semestre IN ('2','22') THEN 12 ELSE 12 END 		
					AND VW.VALOR <= 0)
		OR EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B
					JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
					WHERE TB.GRUPO_BOLSA =  'PROUNI'
					AND B.ALUNO = A.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL))
		OR EXISTS (SELECT TOP 1 1 AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = A.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
		OR EXISTS (	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = A.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
		)
	AND ((@p_ano IS NOT NULL AND PM.ANO = @p_ano) OR @p_ano IS NULL)        
	AND ((@p_semestre IS NOT NULL AND PM.SEMESTRE = @p_semestre)  OR @p_semestre IS NULL)       

UNION ALL

    SELECT DISTINCT     
	PM.ANO								AS [ANO],    
	PM.SEMESTRE							AS [SEMESTRE],
     C.FACULDADE						AS [UNIDADE_ENSINO_ALUNO],       
     A.UNIDADE_FISICA					AS [NOME_UNIDADE_ENSINO_ALUNO],
	 C.TIPO								AS [TIPO_CURSO],      
     C.CURSO							AS [CURSO],        
     C.NOME								AS [NOME_CURSO],       
	 A.SERIE							AS [SERIE],
     A.TURNO							AS [TURNO],
	 A.CONCURSO							AS [CONCURSO],
	ISNULL(CON.DESCRICAO,'')			AS [DESC_CONCURSO],
	CASE WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < CONCAT(@p_ano,@p_semestre) THEN 'VETERANO' ELSE 'CALOURO' END AS TIPO_ALUNO,     
	A.TIPO_INGRESSO , 
	NULL							AS [TIPO_FINAN],
	 0								AS [PAGO],
	 1								AS [NAO_PAGO],
	 'N' AS [BOLSISTA],
	 NULL							AS [DATA_PAGAMENTO],
	 'Sem-Matrícula' AS [SIT_MATRICULA],
	 (SELECT MIN(DT_INSERCAO) FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre) AS [DATA_MATRICULA],
	 NULL AS DATA_CANCELAMENTO,
	 CASE WHEN PM2.OBS IS NULL OR RTRIM(LTRIM(PM2.OBS)) = '' THEN 'Secretaria' ELSE 'Aluno Online' END AS [ORIGEM_MATRICULA],
	 A.DT_INGRESSO AS [DATA_INGRESSO],
	 PM.ALUNO,
	 P.CPF,
	 A.NOME_COMPL AS NOME_ALUNO,
	 A.CURRICULO,
	 P.DT_NASC			AS [DATA_NASC],
     P.RG_NUM                AS [RG],     
     P.E_MAIL                AS [E_MAIL],    
     P.ENDERECO                AS [ENDERECO],    
     P.END_NUM                AS [NUMERO],    
     P.END_COMPL            AS [COMPLEMENTO],    
     P.CEP					AS [CEP],    
     P.BAIRRO			AS [BAIRRO],  
     HM.NOME                 AS [CIDADE],    
     HM.UF                  AS [ESTADO], 
	ISNULL(P.DDD_FONE,'')				AS [DDD_FONE],
	ISNULL(P.FONE,'')                 AS [FONE], 
	ISNULL(P.DDD_FONE_CELULAR,'')		AS [DDD_CELULAR],    
	ISNULL(P.CELULAR,'')                AS [CELULAR],
	 ISNULL((SELECT TOP 1 CONTRATO_ACEITO FROM LYCEUM..LY_CONTRATO_ALUNO WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND PERIODO = @p_semestre),'N') AS [CONTRATO_ACEITO],
	 '' AS [BOLSAS],
	 '' AS [DATA_MATRICULA_ORC],
	A.CANDIDATO	AS [CANDIDATO],
	'' AS TIPO_CREDITO,
	'' AS DATA_VENCIMENTO,
	'' AS DATA_VENCIMENTO_ORI,
	'' AS TIPO_PAGAMENTO
FROM LYCEUM..LY_ALUNO A
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA             
JOIN LYCEUM..VW_MATRICULA_E_PRE_MATRICULA PM ON PM.ALUNO = A.ALUNO 
LEFT JOIN LYCEUM..LY_PRE_MATRICULA PM2 ON PM2.ALUNO = PM.ALUNO AND PM2.ANO = PM.ANO AND PM2.SEMESTRE = PM.SEMESTRE AND PM2.DISCIPLINA = PM.DISCIPLINA AND PM2.TURMA = PM.TURMA     
JOIN LYCEUM..LY_CURSO C ON A.CURSO = C.CURSO AND C.TIPO NOT IN ('POS-GRADUACAO','EXTENSAO')
JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON C.FACULDADE = UE.UNIDADE_ENS
JOIN LYCEUM..HD_MUNICIPIO HM ON HM.MUNICIPIO = P.END_MUNICIPIO 
LEFT JOIN LYCEUM..LY_CONCURSO CON ON CON.CONCURSO = A.CONCURSO
WHERE 1=1 
AND (NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = PM.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo'))
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = PM.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1			/*BOLSA 100%  NO PERIODO LETIVO EM UMA DAS PARCELAS DO TIPO ABAIXO*/
					AND (B.ANOINI >= YEAR(GETDATE()) 
					AND B.TIPO_BOLSA IN ('IMES','BF PCD','PARES','BAFFFTC','BINCRH')
					AND (B.MESINI = CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END))
					)
		AND NOT EXISTS (SELECT TOP 1 1 AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = PM.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM = @p_ano) 
					AND (B.MESFIM = CASE WHEN @p_semestre = 1 THEN 6 ELSE 12 END)
					)

		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B 
					WHERE 1=1
					AND (B.TIPO_BOLSA = 'CREDEDUC' OR B.TIPO_BOLSA LIKE '%QUERO%' OR B.TIPO_BOLSA LIKE '%EDUCA%')
					AND B.ALUNO = PM.ALUNO
					AND B.DATA_CANCEL IS NULL			/*BOLSA ESPECIFICA CREDEDUC/QUEROBOLSA/EDUCAMAIS - NÃO CANCELADA E EM VIGÊNCIA*/
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL)
					
				)
		
		--BOLSA FIES TEMP *SOLICITADO POR ANDRÉ BRITTO / ANA PAULA GOMES em 25/03/2019*
	AND NOT EXISTS (SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = A.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
					)

		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = A.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL)

		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = A.ALUNO)	
					
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS','MS_EB','SM')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = A.ALUNO
					AND VW.ANO = @p_ano
					AND VW.ESTORNO = 'N'
					AND (IL.DESCRICAO LIKE '%Acerto%' OR IL.DESCRICAO LIKE '%Restitu%')
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11') THEN 6 WHEN @p_semestre IN ('2','22') THEN 12 ELSE 12 END 		
					AND VW.VALOR <= 0)
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_BOLSA B
					JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
					WHERE TB.GRUPO_BOLSA =  'PROUNI'
					AND B.ALUNO = A.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL))
		AND NOT EXISTS (SELECT TOP 1 1 AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = A.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
		AND NOT EXISTS (SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = A.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
		)
AND ((@p_ano IS NOT NULL AND PM.ANO = @p_ano) OR @p_ano IS NULL)        
AND ((@p_semestre IS NOT NULL AND PM.SEMESTRE = @p_semestre)  OR @p_semestre IS NULL)        

ORDER BY C.FACULDADE, C.CURSO 



--REINGRESSO

UPDATE T SET T.TIPO_ALUNO = 'REINGRESSO'
FROM TEMP_ALUNOS T
WHERE T.TIPO_ALUNO = 'CALOURO' AND T.TIPO_INGRESSO = 'Reingresso'


--ATUALIZANDO OS ALUNOS QUE POSSUEM SECRETARIA E ALUNO ONLINE

	DELETE T1 FROM TEMP_ALUNOS T1 
	WHERE T1.ORIGEM_MATRICULA = 'Secretaria'
	AND EXISTS ( SELECT TOP 1 1 
				 FROM TEMP_ALUNOS T2 
				 WHERE T2.ALUNO = T1.ALUNO
				 AND T2.ORIGEM_MATRICULA = 'Aluno Online'
				)

--MATRICULA /  PRE-MATRICULA / CANCELADOS

--DEFININDO BOLSISTAS
UPDATE T SET T.BOLSISTA = 'S'
FROM TEMP_ALUNOS T
JOIN LYCEUM..LY_PERIODO_LETIVO PL ON PL.ANO = T.ANO AND PL.PERIODO = T.SEMESTRE
WHERE EXISTS (SELECT TOP 1 1  FROM LYCEUM..LY_BOLSA B 
				WHERE B.ALUNO = T.ALUNO 
				AND B.DATA_CANCEL IS NULL 
				AND (CONCAT(B.ANOFIM,B.MESFIM) <= (CASE @p_semestre WHEN 1 THEN CONCAT(@p_ano,'6') ELSE CONCAT(@p_ano,'12') END) OR B.ANOFIM IS NULL)
)

UPDATE T SET SIT_MATRICULA = 'Cancelado'
FROM TEMP_ALUNOS T
WHERE EXISTS (SELECT 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW 
			WHERE VW.ALUNO = T.ALUNO AND VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE
			AND VW.SIT_MATRICULA IN ('Cancelado'))
			AND T.SIT_MATRICULA = 'Sem-Matrícula'

UPDATE T SET SIT_MATRICULA = 'Trancado'
FROM TEMP_ALUNOS T
WHERE EXISTS (SELECT 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW 
			WHERE VW.ALUNO = T.ALUNO AND VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE
			AND VW.SIT_MATRICULA IN ('Trancado'))
		AND T.SIT_MATRICULA = 'Sem-Matrícula'

UPDATE T SET SIT_MATRICULA = 'Trancado'
FROM TEMP_ALUNOS T
WHERE EXISTS (SELECT 1 FROM LYCEUM..LY_TRANCAMENTO VW 
			WHERE VW.ALUNO = T.ALUNO AND VW.ANO_TRANC = T.ANO AND VW.SEM_TRANC = T.SEMESTRE)

UPDATE T SET SIT_MATRICULA = 'Dispensado'
FROM TEMP_ALUNOS T
WHERE EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW 
			WHERE VW.ALUNO = T.ALUNO AND VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE
			AND VW.SIT_MATRICULA = 'Dispensado')


UPDATE T SET SIT_MATRICULA = 'Pre-Matric'
FROM TEMP_ALUNOS T
WHERE EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW 
			WHERE VW.ALUNO = T.ALUNO AND VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE
			AND VW.SIT_MATRICULA = 'Pre-Matriculado')

UPDATE T SET SIT_MATRICULA = 'Matriculado'
FROM TEMP_ALUNOS T
WHERE EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW 
			WHERE VW.ALUNO = T.ALUNO AND VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE
			AND VW.SIT_MATRICULA = 'Matriculado')
					
	

--ATUALIZANDO ORIGEM_MATRICULA PARA ALUNOS MATRICULADOS

	UPDATE T1 SET T1.ORIGEM_MATRICULA = 'Efetivado'
	FROM TEMP_ALUNOS T1 WHERE SIT_MATRICULA IN ('Matriculado','Aprovado','Rep Falta','Rep Nota','Trancado','Dispensado')

--DEFININDO TIPO_FINAN

	UPDATE BI SET BI.TIPO_FINAN = 'FIES'
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	select TOP 1 1 
	FROM LYCEUM..LY_BOLSA B
	JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
	WHERE B.ALUNO = BI.ALUNO
	AND TB.GRUPO_BOLSA = 'FIES' 
	AND B.DATA_CANCEL IS NULL 
	AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
	AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
	)
	AND TIPO_FINAN IS NULL

	
	UPDATE BI SET BI.TIPO_FINAN = 'FIES' 
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	SELECT TOP 1 1 
	FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
	WHERE PPP.RESP = 'FIES' --RESP FIES
	AND PPP.ALUNO = BI.ALUNO
	AND PPP.PERCENT_DIVIDA_ALUNO > 0
	AND PPP.ANO = @p_ano
	AND PPP.PERIODO = @p_semestre)


	UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	select TOP 1 1 
	FROM LYCEUM..LY_BOLSA B
	JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
	WHERE B.ALUNO = BI.ALUNO
	AND B.TIPO_BOLSA IN ('PROUNI_50','PROUNI50') 
	AND TB.GRUPO_BOLSA = 'PROUNI'
	AND B.DATA_CANCEL IS NULL
	AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
	AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
	)

	
UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
FROM TEMP_ALUNOS BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO = 0.5000
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)

	UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	select TOP 1 1 
	FROM LYCEUM..LY_BOLSA B
	JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
	WHERE B.ALUNO = BI.ALUNO
	AND B.TIPO_BOLSA IN ('PROUNI_100','PROUNI100') 
	AND TB.GRUPO_BOLSA = 'PROUNI'
	AND B.DATA_CANCEL IS NULL 
	AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
	AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
	)
	
	
	UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	select TOP 1 1 
	FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
						WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
						AND PPP.ALUNO = BI.ALUNO
						AND PPP.PERCENT_DIVIDA_ALUNO = 1.0000
						AND PPP.ANO = @p_ano
						AND PPP.PERIODO = @p_semestre)

	UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	select TOP 1 1 
	FROM LYCEUM..LY_BOLSA B
	JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
	WHERE B.ALUNO = BI.ALUNO
	AND B.TIPO_BOLSA = 'PROIES100'
	AND TB.GRUPO_BOLSA = 'PROIES' 
	AND B.DATA_CANCEL IS NULL 
	AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
	AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
	)

	UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	select TOP 1 1 
	FROM  LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = BI.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo')
				AND LC.TIPO_PAGAMENTO = 'Especial' AND LC.TIPO_CRED = 'PROIES')

	UPDATE BI SET BI.TIPO_FINAN = 'FIES+PROUNI'
	FROM TEMP_ALUNOS BI WHERE EXISTS (
	select TOP 1 1 
	FROM LYCEUM..LY_BOLSA B
	JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
	WHERE B.ALUNO = BI.ALUNO
	AND TB.GRUPO_BOLSA = 'FIES' 
	AND B.DATA_CANCEL IS NULL 
	AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
	AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
	)

	AND TIPO_FINAN LIKE 'PRO%'

	UPDATE TEMP_ALUNOS SET TIPO_FINAN = 'PAGANTES'
	WHERE TIPO_FINAN IS NULL

---- APOS EFETIVAÇÃO DE MATRICULA, SETAR ALUNOS NÃO-PAGOS COMO PAGOS E APAGAR OS DUPLICADOS (PAGO E NAO PAGO)
	
--	UPDATE TEMP_ALUNOS SET PAGO = 1, NAO_PAGO = 0
--	WHERE SIT_MATRICULA = 'Matriculado' AND ORIGEM_MATRICULA = 'Efetivado'

	DELETE T FROM TEMP_ALUNOS T WHERE T.PAGO = 0 AND EXISTS (SELECT TOP 1 1 FROM TEMP_ALUNOS T1 WHERE T1.PAGO = 1 AND T1.ALUNO = T.ALUNO AND T1.ANO = T.ANO AND T1.SEMESTRE = T.SEMESTRE)

	--DELETE T FROM TEMP_ALUNOS T WHERE T.PAGO = 1 AND T.DATA_PAGAMENTO IS NULL AND EXISTS (SELECT TOP 1 1 FROM TEMP_ALUNOS T1 WHERE T1.PAGO = 1 AND T1.ALUNO = T.ALUNO AND T1.ANO = T.ANO AND T1.SEMESTRE = T.SEMESTRE AND T.DATA_PAGAMENTO IS NOT NULL)

-- ATRIBUINDO DATA DE CANCELAMENTO PARA OS CANCELADOS

	UPDATE T SET T.DATA_CANCELAMENTO = (SELECT TOP 1 HCC.DT_ENCERRAMENTO 
										FROM LYCEUM..LY_H_CURSOS_CONCL HCC
										WHERE HCC.ALUNO = T.ALUNO
										AND HCC.ANO_ENCERRAMENTO = @p_ano 
										AND HCC.SEM_ENCERRAMENTO = @p_semestre
										AND HCC.DT_REABERTURA IS NULL
										)
	FROM TEMP_ALUNOS T
	WHERE T.SIT_MATRICULA = 'Cancelado'

-- SANEAMENTO DATA CANCELAMENTO
	UPDATE TEMP_ALUNOS SET DATA_CANCELAMENTO = '2019-02-13'
	WHERE DATA_CANCELAMENTO = '2109-02-13'

	UPDATE TEMP_ALUNOS SET DATA_CANCELAMENTO = (SELECT DT_INICIO FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) 
	WHERE DATA_CANCELAMENTO IS NULL  AND SIT_MATRICULA = 'Cancelado'

-- SANEAMENTO ALUNOS CANCELADOS MANUALMENTE
	UPDATE T SET SIT_MATRICULA = 'Cancelado'
	FROM TEMP_ALUNOS T
	JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = T.ALUNO
	WHERE A.SIT_ALUNO = 'Cancelado'

-- SANEAMENTO CALOUROS PETROLINA DIREITO

	UPDATE T SET TIPO_ALUNO = 'CALOURO', TIPO_INGRESSO = 'Vestibular'
	FROM TEMP_ALUNOS T
	WHERE T.NOME_UNIDADE_ENSINO_ALUNO = 'OTE-PET' AND T.CURSO = '4018'
	AND T.ANO = 2019 AND T.SEMESTRE = 1

--	REINGRESSO

UPDATE T SET T.TIPO_ALUNO = 'REINGRESSO'
FROM TEMP_ALUNOS T
WHERE T.TIPO_ALUNO = 'CALOURO' AND T.TIPO_INGRESSO = 'Reingresso'


-- LISTA DE BOLSAS CADASTRADAS PRO ALUNO
	UPDATE T SET BOLSAS = STUFF((SELECT DISTINCT ',' + B.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..LY_BOLSA B
                        WHERE 1=1
						AND (B.ANOFIM >= @p_ano OR B.ANOFIM IS NULL) AND (B.MESFIM >= CASE @p_semestre WHEN 1 THEN 6 ELSE 12 END OR B.MESFIM IS NULL OR (B.MESINI = B.MESFIM AND B.ANOINI = B.ANOFIM))
						AND B.DATA_CANCEL IS NULL
                        AND B.ALUNO = T.ALUNO
                        FOR XML PATH('') 
                        ), 1, 1, '' )
	FROM TEMP_ALUNOS T
	 
-- UPDATE DATA DE MATRICULA PARA O ORÇAMENTO

	UPDATE T SET T.DATA_MATRICULA_ORC = CONVERT(VARCHAR(10),T.DATA_MATRICULA,103)
	FROM TEMP_ALUNOS T

	UPDATE T SET T.DATA_MATRICULA_ORC = CASE WHEN @p_semestre = '1' 
										THEN CONVERT(VARCHAR(10),'20/04/'+@p_ano,103) 
										ELSE CONVERT(VARCHAR(10),'30/09/'+@p_ano,103) END
	FROM TEMP_ALUNOS T
	WHERE CONVERT(VARCHAR(10),T.DATA_MATRICULA,103) > CASE WHEN @p_semestre = '1' THEN CONVERT(VARCHAR(10),'20/04/'+@p_ano,103) ELSE CONVERT(VARCHAR(10),'30/09/'+@p_ano,103) END

	
	UPDATE T SET T.DATA_MATRICULA_ORC = CASE WHEN @p_semestre = '1' 
										THEN CONVERT(VARCHAR(10),'01/01/'+@p_ano,103) 
										ELSE CONVERT(VARCHAR(10),'01/06/'+@p_ano,103) END
	FROM TEMP_ALUNOS T
	WHERE CONVERT(VARCHAR(10),T.DATA_MATRICULA,103) < CASE WHEN @p_semestre = '1' THEN CONVERT(VARCHAR(10),'01/01/'+@p_ano,103) ELSE CONVERT(VARCHAR(10),'01/06/'+@p_ano,103) END

--ALUNOS CONCLUINTES

CREATE TABLE TEMP_CONCLUINTES
(
	CURSO VARCHAR(20),
	TURNO VARCHAR(1),
	CURRICULO VARCHAR(30),
	TIPO_CURSO VARCHAR(50),
	QTD_SEMESTRES INT,
	CALCULA_CONCL VARCHAR(1)

)

INSERT INTO TEMP_CONCLUINTES
SELECT DISTINCT CURSO, TURNO, CURRICULO, TIPO_CURSO, 0 AS QTD_SEMESTRES, 'N' AS CALCULA_CONCL
FROM TEMP_ALUNOS

UPDATE C SET C.QTD_SEMESTRES = (SELECT MAX(SERIE_IDEAL) 
								FROM LYCEUM..LY_GRADE G 
								WHERE G.CURSO = C.CURSO 
								AND G.CURRICULO = C.CURRICULO
								AND G.TURNO = C.TURNO
								)
FROM TEMP_CONCLUINTES C

UPDATE TEMP_CONCLUINTES SET CALCULA_CONCL = 'S'
WHERE QTD_SEMESTRES > (CASE WHEN TIPO_CURSO = 'GRADUACAO' THEN 5 WHEN TIPO_CURSO = 'TECNOLOGO' THEN 3 ELSE 8 END)


UPDATE T SET T.TIPO_ALUNO = T.TIPO_ALUNO+'-CONCLUINTE'
FROM TEMP_ALUNOS T
JOIN TEMP_CONCLUINTES C ON C.CURRICULO = T.CURRICULO AND C.CURSO = T.CURSO AND C.TURNO = T.TURNO
WHERE LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(T.ALUNO,'S') = 0
AND C.CALCULA_CONCL = 'S'


DROP TABLE TEMP_CONCLUINTES

UPDATE T SET T.TIPO_ALUNO = BI.TIPO_ALUNO
FROM TEMP_ALUNOS T
JOIN BI_REMATRICULA BI ON BI.ANO = T.ANO AND BI.SEMESTRE = T.SEMESTRE AND BI.ALUNO = T.ALUNO
WHERE BI.TIPO_ALUNO IN ('REINGRESSO','REINGRESSO-CONCLUINTE')



--TIPO_PAGAMENTO,TIPO_CREDITO, DATA_VENCIMENTO, DATA_VENCIMENTO_ORI

UPDATE T SET T.TIPO_PAGAMENTO = (
				SELECT TOP 1 LC.TIPO_PAGAMENTO
				FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA 
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IC.COBRANCA AND VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL AND IC.ITEM_ESTORNADO IS NULL
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_ALUNOS T
WHERE T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = ''

UPDATE T SET T.TIPO_PAGAMENTO = (
				SELECT TOP 1 'ACERTO/ACORDO'
				FROM LYCEUM..LY_ITEM_LANC IL  
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('Acerto','Acordo')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND (IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END OR IL.PARCELA IS NULL)

), T.TIPO_CREDITO = (
				SELECT TOP 1 'ACERTO/ACORDO'
				FROM LYCEUM..LY_ITEM_LANC IL  
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('Acerto','Acordo')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND (IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END OR IL.PARCELA IS NULL)

)
FROM TEMP_ALUNOS T
WHERE T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = ''
AND PAGO = 1


UPDATE T SET T.TIPO_CREDITO = (
				SELECT TOP 1 LC.TIPO_CRED
				FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA 
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IC.COBRANCA AND VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL AND IC.ITEM_ESTORNADO IS NULL
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_ALUNOS T
WHERE T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = ''
AND PAGO = 1

UPDATE T SET T.DATA_VENCIMENTO = (
				SELECT MIN(VW.DATA_DE_VENCIMENTO)
				FROM LYCEUM..VW_COBRANCA VW 
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_ALUNOS T


UPDATE T SET T.DATA_VENCIMENTO_ORI = (
				SELECT MIN(C.DATA_DE_VENCIMENTO_ORIG)
				FROM LYCEUM..VW_COBRANCA VW 
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_ALUNOS T


UPDATE T SET T.TIPO_CREDITO = 'PROUNI', T.TIPO_PAGAMENTO = 'BOLSA'
FROM TEMP_ALUNOS T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN IN ('PROUNI INTEGRAL','PROUNI PARCIAL')
AND T.PAGO = 1

UPDATE T SET T.TIPO_CREDITO = 'PROIES', T.TIPO_PAGAMENTO = 'BOLSA'
FROM TEMP_ALUNOS T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN IN ('PROIES')
AND T.PAGO = 1

UPDATE T SET T.TIPO_CREDITO = 'FIES', T.TIPO_PAGAMENTO = 'BOLSA'
FROM TEMP_ALUNOS T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN = 'FIES'
AND T.PAGO = 1

UPDATE T SET T.TIPO_CREDITO = 'CAMPANHA', T.TIPO_PAGAMENTO = 'DESCONTO'
FROM TEMP_ALUNOS T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN = 'PAGANTES'
AND T.PAGO = 1

UPDATE T SET T.TIPO_CREDITO = 'NÃO-PAGO', T.TIPO_PAGAMENTO = 'NÃO-PAGO'
FROM TEMP_ALUNOS T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.PAGO = 0



	--INSERT NA TABELA FISICA
	INSERT INTO BI_ACOMP_MATR
	SELECT DISTINCT
		ANO,
		SEMESTRE,
		UNIDADE_ENSINO_ALUNO,
		NOME_UNIDADE_ENSINO_ALUNO,
		TIPO_CURSO,
		CURSO,
		NOME_CURSO,
		SERIE,
		TURNO,
		CONCURSO,
		DESC_CONCURSO,
		TIPO_ALUNO,
		TIPO_INGRESSO,
		TIPO_FINAN,
		PAGO,
		NAO_PAGO,
		BOLSISTA,
		DATA_PAGAMENTO,
		SIT_MATRICULA,
		DATA_MATRICULA,
		DATA_CANCELAMENTO,
		ORIGEM_MATRICULA,
		DATA_INGRESSO,
		ALUNO,
		CPF,
		NOME_ALUNO,
		CURRICULO,
		DATA_NASC,
		RG,
		E_MAIL,
		ENDERECO,
		NUMERO,
		COMPLEMENTO,
		CEP,
		BAIRRO,
		CIDADE,
		ESTADO,
		DDD_FONE,
		FONE,
		DDD_CELULAR,
		CELULAR,
		CONTRATO_ACEITO,
		BOLSAS,
		DATA_MATRICULA_ORC,
		CANDIDATO,
		TIPO_CREDITO,
		DATA_VENCIMENTO,
		DATA_VENCIMENTO_ORI,
		TIPO_PAGAMENTO
	FROM TEMP_ALUNOS

DROP TABLE TEMP_ALUNOS
        
END                  

-- [FIM]          
