CREATE TABLE BI_AUX_DMP_DIA_CAMPANHA
(
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	DATA_INI_CAMPANHA VARCHAR(10)
)

INSERT INTO BI_AUX_DMP_DIA_CAMPANHA
VALUES ('2017','2','15/04/2017')

INSERT INTO BI_AUX_DMP_DIA_CAMPANHA
VALUES ('2018','2','04/05/2018')

INSERT INTO BI_AUX_DMP_DIA_CAMPANHA
VALUES ('2019','2','15/04/2019')

INSERT INTO BI_AUX_DMP_DIA_CAMPANHA
VALUES ('2019','1','15/09/2018')

INSERT INTO BI_AUX_DMP_DIA_CAMPANHA
VALUES ('2020','1','15/09/2019')




SELECT	R.ANO,
		R.SEMESTRE,
		UNIDADE_FISICA_ALUNO,
		UNIDADE_ENSINO_ALUNO,
		CURSO,
		NOME_CURSO,
		TURNO,
		ALUNO,
		TIPO_FINAN,
		TIPO_ALUNO,
		TIPO_INGRESSO,
		DATA_PERIODO,
		DATA_MATRICULA,
		DATEDIFF(DAY,CONVERT(DATETIME,A.DATA_INI_CAMPANHA,103),CONVERT(DATETIME,DATA_MATRICULA,103)) AS DIA_CAMPANHA,
		0.00 AS VALOR_DIVIDA,
		0.00 AS VALOR_BOLSA,
		0.00 AS VALOR_BOLSA_SEM_ISENCAO,
		0.00 AS DMP,
		0.00 AS DMP_SEM_ISENCAO
FROM BI_REMATRICULA R
JOIN BI_AUX_DMP_DIA_CAMPANHA  A ON A.ANO = R.ANO AND A.SEMESTRE = R.SEMESTRE
WHERE R.ANO = 2018
AND R.SEMESTRE = 2
AND TIPO_ALUNO IN ('CALOURO','REINGRESSO')
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NAO-PAGO','PRE-MATRICULADO PAGO')