USE FTC_DATAMART
GO


--SELECT DISTINCT ANO, SEMESTRE  FROM BI_REMATRICULA ORDER BY ANO, SEMESTRE
--EXEC BI_ALUNOS_UNIDADE_JOB 2012,0

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_ALUNOS_UNIDADE_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_ALUNOS_UNIDADE_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_ALUNOS_UNIDADE_JOB
(
	@p_ano VARCHAR(4),
	@p_semestre VARCHAR(2)
)      
AS            
-- [INÍCIO]                    
BEGIN  

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_ALUNOS_UNIDADE'))   
BEGIN
	DELETE FROM BI_ALUNOS_UNIDADE WHERE PERIODO_LETIVO = CONCAT(@p_ano,'/',@p_semestre)
END

ELSE 
BEGIN
	CREATE TABLE BI_ALUNOS_UNIDADE  --DROP TABLE BI_ALUNOS_UNIDADE
	(
		[PERIODO_LETIVO] VARCHAR(7),
		[UNIDADE_ENSINO_ALUNO]	VARCHAR(50),
		[TIPO_CURSO] VARCHAR(50),
		[CENTRO_DE_CUSTO] VARCHAR(20),
		[DESCR_CENTRO_CUSTO] VARCHAR(200),
		[CURSO] VARCHAR(20),
		[NOME_CURSO] VARCHAR (200),
		[ALUNO] VARCHAR (20),
	)   
END

CREATE TABLE TEMP_BI_ALUNOS_UNIDADE 
(
	[PERIODO_LETIVO] VARCHAR(7),
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(50),
	[TIPO_CURSO] VARCHAR(50),
	[CENTRO_DE_CUSTO] VARCHAR(20),
	[DESCR_CENTRO_CUSTO] VARCHAR(200),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR (200),
	[ALUNO] VARCHAR (20),
	
	
)   
--GRADUACAO
	INSERT INTO TEMP_BI_ALUNOS_UNIDADE
	SELECT DISTINCT (CONCAT(@p_ano,'/',@p_semestre)) AS PERIODO_LETIVO,
			CASE BI.UNIDADE_FISICA_ALUNO
				WHEN 'DOM-JEQ' THEN 'DOM - JEQUIÉ'
				WHEN 'DOM-PET' THEN 'DOM - PETROLINA'
				WHEN 'DOM-SSA' THEN 'DOM - SALVADOR'
				WHEN 'DOM-VIC' THEN 'DOM - VITÓRIA'
				WHEN 'FCS' THEN 'FACULDADE DA CIDADE'
				WHEN 'FFTC' THEN 'FUNDAÇÃO'
				WHEN 'FTC-FSA' THEN  'FTC - FEIRA DE SANTANA'
				WHEN 'FTC-IGT' THEN  'FTC - SALVADOR'
				WHEN 'FTC-ITA' THEN  'FTC - ITABUNA'
				WHEN 'FTC-JEQ' THEN  'FTC - JEQUIE'
				WHEN 'FTC-SSA' THEN 'FTC - SALVADOR'
				WHEN 'FTC-VIC' THEN 'FTC - VITORIA DA CONQUISTA'
				WHEN 'OTE-JUA' THEN 'OTE - JUAZEIRO'
				WHEN 'OTE-PET' THEN 'OTE - PETROLINA'
				WHEN 'OTE-SP' THEN 'OTE - SÃO PAULO'
				WHEN 'POLO-CEN' THEN 'FTC - EAD'
				WHEN 'POLO-FSA' THEN 'FTC - EAD'
				WHEN 'POLO-ITA' THEN 'FTC - EAD'
				WHEN 'POLO-JEQ' THEN 'FTC - EAD'
				WHEN 'POLO-JUA' THEN 'FTC - EAD'
				WHEN 'POLO-PAR' THEN 'FTC - EAD'
				WHEN 'POLO-PET' THEN 'FTC - EAD'
				WHEN 'POLO-VIC' THEN 'FTC - EAD'
				WHEN 'POLO-CEN' THEN 'FTC - EAD'
				WHEN 'THINK-FCS' THEN 'DOM - SALVADOR'
				WHEN 'THINK-SSA' THEN 'DOM - SALVADOR'
				WHEN 'THINK-FSA' THEN 'DOM - SALVADOR'
				END AS UNIDADE_ENSINO_ALUNO,
			CASE BI.TIPO_CURSO
				WHEN 'GRADUACAO' THEN 'GRADUACAO SUPERIOR'
				WHEN 'TECNOLOGO' THEN 'GRADUACAO SUPERIOR'
				WHEN 'ENS BASICO' THEN 'ENSINO'
				WHEN 'ENS INFANTIL' THEN 'ENSINO'
				WHEN 'EXTENSAO ENS BASICO' THEN 'ENSINO'
				ELSE BI.TIPO_CURSO
				END AS TIPO_CURSO,
			(SELECT TOP 1 ISNULL(CCUSTO.CENTRO_DE_CUSTO,'')  FROM  LYCEUM..LY_CENTRO_DE_CUSTO CCUSTO WHERE CCUSTO.CURSO=CC.CURSO) [CENTRO_DE_CUSTO],
			ISNULL(TI.DESCR,'') AS [DESCR_CENTRO_CUSTO],
			BI.CURSO,
			BI.NOME_CURSO,
			BI.ALUNO  
	FROM BI_REMATRICULA BI
	LEFT JOIN LYCEUM..LY_CENTRO_DE_CUSTO CC ON CC.CURSO = BI.CURSO
	LEFT JOIN LYCEUM..HD_TABELAITEM TI ON TI.ITEM = CC.CENTRO_DE_CUSTO AND TABELA = 'CentroCusto'
	WHERE	BI.STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') AND BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
	

--DEMAIS NEGOCIOS

	INSERT INTO TEMP_BI_ALUNOS_UNIDADE
	SELECT DISTINCT (CONCAT(@p_ano,'/',@p_semestre)) AS PERIODO_LETIVO,
			CASE A.UNIDADE_FISICA
				WHEN 'DOM-JEQ' THEN 'DOM - JEQUIÉ'
				WHEN 'DOM-PET' THEN 'DOM - PETROLINA'
				WHEN 'DOM-SSA' THEN 'DOM - SALVADOR'
				WHEN 'DOM-VIC' THEN 'DOM - VITÓRIA'
				WHEN 'FCS' THEN 'FACULDADE DA CIDADE'
				WHEN 'FFTC' THEN 'FUNDAÇÃO'
				WHEN 'FTC-FSA' THEN  'FTC - FEIRA DE SANTANA'
				WHEN 'FTC-IGT' THEN  'FTC - SALVADOR'
				WHEN 'FTC-ITA' THEN  'FTC - ITABUNA'
				WHEN 'FTC-JEQ' THEN  'FTC - JEQUIE'
				WHEN 'FTC-SSA' THEN 'FTC - SALVADOR'
				WHEN 'FTC-VIC' THEN 'FTC - VITORIA DA CONQUISTA'
				WHEN 'OTE-JUA' THEN 'OTE - JUAZEIRO'
				WHEN 'OTE-PET' THEN 'OTE - PETROLINA'
				WHEN 'OTE-SP' THEN 'OTE - SÃO PAULO'
				WHEN 'POLO-CEN' THEN 'FTC - EAD'
				WHEN 'POLO-FSA' THEN 'FTC - EAD'
				WHEN 'POLO-ITA' THEN 'FTC - EAD'
				WHEN 'POLO-JEQ' THEN 'FTC - EAD'
				WHEN 'POLO-JUA' THEN 'FTC - EAD'
				WHEN 'POLO-PAR' THEN 'FTC - EAD'
				WHEN 'POLO-PET' THEN 'FTC - EAD'
				WHEN 'POLO-VIC' THEN 'FTC - EAD'
				WHEN 'POLO-CEN' THEN 'FTC - EAD'
				WHEN 'THINK-FCS' THEN 'DOM - SALVADOR'
				WHEN 'THINK-SSA' THEN 'DOM - SALVADOR'
				WHEN 'THINK-FSA' THEN 'DOM - SALVADOR'
				END AS UNIDADE_ENSINO_ALUNO,
			CASE C.TIPO
				WHEN 'GRADUACAO' THEN 'GRADUACAO SUPERIOR'
				WHEN 'TECNOLOGO' THEN 'GRADUACAO SUPERIOR'
				WHEN 'ENS BASICO' THEN 'ENSINO'
				WHEN 'ENS INFANTIL' THEN 'ENSINO'
				WHEN 'EXTENSAO ENS BASICO' THEN 'ENSINO'
				ELSE C.TIPO
				END AS TIPO_CURSO,
			(SELECT TOP 1 ISNULL(CCUSTO.CENTRO_DE_CUSTO,'')  FROM  LYCEUM..LY_CENTRO_DE_CUSTO CCUSTO WHERE CCUSTO.CURSO=CC.CURSO) [CENTRO_DE_CUSTO],
			ISNULL(TI.DESCR,'') AS [DESCR_CENTRO_CUSTO],
			A.CURSO,
			C.NOME AS NOME_CURSO,
			A.ALUNO  
	FROM LYCEUM..LY_ALUNO A
	JOIN LYCEUM..LY_CURSO C ON C.CURSO = A.CURSO
	LEFT JOIN LYCEUM..LY_CENTRO_DE_CUSTO CC ON CC.CURSO = C.CURSO
	LEFT JOIN LYCEUM..HD_TABELAITEM TI ON TI.ITEM = CC.CENTRO_DE_CUSTO AND TABELA = 'CentroCusto'
	WHERE	EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA 
					WHERE ALUNO = A.ALUNO AND SIT_MATRICULA NOT IN ('Cancelado','Trancado','Dispensado','Pre-Matriculado') AND ANO = @p_ano AND SEMESTRE = @p_semestre)	
			AND NOT EXISTS (SELECT TOP 1 1 FROM TEMP_BI_ALUNOS_UNIDADE WHERE ALUNO = A.ALUNO)
			AND NOT EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre)

	INSERT INTO BI_ALUNOS_UNIDADE
	SELECT	DISTINCT
			PERIODO_LETIVO,
			UNIDADE_ENSINO_ALUNO,
			TIPO_CURSO,
			CENTRO_DE_CUSTO,
			DESCR_CENTRO_CUSTO,
			CURSO,
			NOME_CURSO,
			ALUNO
	FROM TEMP_BI_ALUNOS_UNIDADE
	
	DROP TABLE TEMP_BI_ALUNOS_UNIDADE


END
	