DECLARE @p_ano VARCHAR(4) = '2020'
DECLARE @p_semestre VARCHAR(2) = '1'

--11.0 CALCULANDO A SERIE_CALCULDADA
UPDATE T
	SET T.SERIE_CALCULADA = (SELECT COUNT(DISTINCT CONCAT(HM.ANO,HM.SEMESTRE))+1 
							FROM LYCEUM..LY_HISTMATRICULA HM 
							WHERE T.ALUNO = HM.ALUNO 
							AND CONCAT(HM.ANO,HM.SEMESTRE) < CONCAT(@p_ano,@p_semestre)
							AND HM.SITUACAO_HIST NOT IN ('Cancelado','Dispensado'))
	FROM BI_REMATRICULA T
	WHERE 1=1--T.TIPO_ALUNO IN ('VETERANO','VETERANO-COCLUINTE')
	AND T.ANO = @p_ano AND T.SEMESTRE = @p_semestre
	

--11.1 TODO CALOURO DEVE SER TRATADO COM SERIE_CALCULADA = 1
UPDATE T
	SET T.SERIE_CALCULADA = 1
	FROM BI_REMATRICULA T
	WHERE T.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE','REINGRESSO','REINGRESSO-CONCLUINTE')
		AND T.ANO = @p_ano AND T.SEMESTRE = @p_semestre


--12.0 TRATAMENTO PARA SERIE CALCULADA MAIOR QUE O MAXIMO DE SEMESTRES
UPDATE T
	SET T.SERIE_CALCULADA = (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)
	FROM BI_REMATRICULA T
	JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = T.ALUNO
	WHERE T.SERIE_CALCULADA > (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)
	AND T.TIPO_ALUNO IN ('VETERANO','VETERANO-CONCLUINTE')
		AND T.ANO = @p_ano AND T.SEMESTRE = @p_semestre