USE FTC_DATAMART
GO

--DROP TABLE BI_ACOMP_MATR_POS_HIST

CREATE TABLE BI_ACOMP_MATR_POS_HIST (
	[DATA_HIST] DATETIME,
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(20),
	[NOME_UNIDADE_ENSINO_ALUNO] VARCHAR(100),
	[TIPO_CURSO] VARCHAR(50),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR(100),
	[TURMA_PREFERENCIAL] VARCHAR(20),
	[TURNO] VARCHAR(20),
	[PERIODO_INGRESSO] VARCHAR(10),
	[TIPO_ALUNO] VARCHAR(50),
	[PAGO] NUMERIC(10),
	[NAO_PAGO] NUMERIC(10),
	[ALUNO] VARCHAR(20),
	[CPF] VARCHAR(20),
	[NOME_ALUNO] VARCHAR(100),
	[CURRICULO] VARCHAR(20),
	[SIT_ALUNO] VARCHAR(30),
	[DT_INGRESSO] DATETIME,
	[DT_INSERCAO] DATETIME,
	[SIT_MATRICULA] VARCHAR(20),
	[RG] VARCHAR(20),
	[E_MAIL] VARCHAR(100),
	[ENDERECO] VARCHAR(50),
	[NUMERO] VARCHAR(20),
	[COMPLEMENTO] VARCHAR(50),
	[CEP] VARCHAR(9),
	[BAIRRO] VARCHAR(50),
	[CIDADE] VARCHAR(100),
	[ESTADO] VARCHAR(2),
	[DDD_FONE] VARCHAR(3),
	[FONE] VARCHAR(30),
	[DDD_CELULAR] VARCHAR(3),
	[CELULAR] VARCHAR(30)

)
	