USE FTC_DATAMART
GO

--EXEC BI_BB_ACESSO_JOB 2020,1
--DROP TABLE BI_DMP2
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_BB_ACESSO_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_BB_ACESSO_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_BB_ACESSO_JOB
(				
  @p_ano VARCHAR(4)      
, @p_semestre VARCHAR(2)      

)            
AS            
-- [INÍCIO]                    
BEGIN  

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_BB_ACESSO_ALUNO'))   
BEGIN
	DELETE FROM BI_BB_ACESSO_ALUNO WHERE ANO = @p_ano AND SEMESTRE = @p_semestre AND DATA_CARGA =  CONVERT(VARCHAR(10),GETDATE(),23)
END

ELSE

BEGIN
	CREATE TABLE BI_BB_ACESSO_ALUNO ( --DROP TABLE BI_BB_ACESSO_ALUNO

		DATA_CARGA VARCHAR(10),
		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		UNIDADE_ENSINO_ALUNO VARCHAR(20),
		NOME_UNIDADE_ENSINO_ALUNO VARCHAR(200),
		UNIDADE_FISICA_ALUNO VARCHAR(20),
		TIPO_CURSO VARCHAR(50),
		CURSO VARCHAR(20),
		TURNO VARCHAR(1),
		CURRICULO VARCHAR(30),
		NOME_CURSO VARCHAR(200),
		TIPO_ALUNO VARCHAR(50),
		TIPO_FINAN VARCHAR(50),
		FINAN VARCHAR(20),
		STATUS_FTC VARCHAR(50),
		CPF_ALUNO VARCHAR(11),
		ALUNO VARCHAR(20),
		NOME_ALUNO VARCHAR(100),
		TURMA VARCHAR(50),
		DISCIPLINA VARCHAR(30),
		NOME_DISCIPLINA VARCHAR(200),
		SIT_MATRICULA_DISC VARCHAR(30),
		SIT_TURMA VARCHAR(30),
		DT_INICIO_TURMA VARCHAR(10),
		DT_FIM_TURMA VARCHAR(10),
		NUM_FUNC VARCHAR(20),
		NOME_DOCENTE VARCHAR(150),
		CPF_DOCENTE VARCHAR(11),
		NIVEL_TURMA VARCHAR(30),
		AULAS_PREVISTAS NUMERIC(10,2),
		ULTIMO_LOGIN DATETIME,
		ULTIMO_ACESSO_TURMA DATETIME,
		DIAS_AULA VARCHAR(100),
		CENTRO_DE_CUSTO VARCHAR(50),
		CENTRO_DE_CUSTO_DESC VARCHAR(100)
	)

END

	INSERT INTO BI_BB_ACESSO_ALUNO
	SELECT
		CONVERT(VARCHAR(10),GETDATE(),23) AS DATA_CARGA,
		T.ANO,
		T.SEMESTRE,
		'' AS UNIDADE_ENSINO_ALUNO,
		'' AS NOME_UNIDADE_ENSINO_ALUNO,
		'' AS UNIDADE_FISICA_ALUNO,
		'' AS TIPO_CURSO,
		'' AS CURSO,
		'' AS TURNO,
		'' AS CURRICULO,
		'' AS NOME_CURSO,
		'' AS TIPO_ALUNO,
		'' AS TIPO_FINAN,
		'' AS FINAN,
		'' AS STATUS_FTC,
		E.external_person_key AS CPF,
		E.lyceum_aluno AS ALUNO,
		'' AS NOME_ALUNO,
		VW.TURMA,
		VW.DISCIPLINA,
		D.NOME AS NOME_DICIPLINA,
		VW.SIT_MATRICULA AS SIT_MATRICULA_DISC,
		T.SIT_TURMA,
		CONVERT(VARCHAR(10),T.DT_INICIO,23) AS DT_INICIO_TURMA,
		CONVERT(VARCHAR(10),T.DT_FIM,23) AS DT_FIM_TURMA,
		DO.NUM_FUNC AS NUM_FUNC,
		DO.NOME_COMPL AS NOME_DOCENTE,
		DO.CPF AS CPF_DOCENTE,
		T.NIVEL,
		T.AULAS_PREVISTAS,
		SBA.LAST_LOGIN_DATE AS ULTIMO_LOGIN,
		SBA.LAST_ACCESS_DATE AS ULTIMO_ACESSO_TURMA,
		NULL AS DIAS_AULA,
		NULL AS CENTRO_DE_CUSTO,
		NULL AS CENTRO_DE_CUSTO_DESC
	FROM BLACKBOARD..ENROLLMENTS E 
	JOIN BLACKBOARD..SA_BB_ACESSO SBA ON SBA.COURSE_ID = E.external_course_key AND SBA.USER_ID = E.external_person_key
	JOIN LYCEUM..LY_TURMA T ON T.TURMA = E.LYCEUM_TURMA AND T.DISCIPLINA = E.LYCEUM_DISCIPLINA AND T.ANO = E.LYCEUM_ANO AND T.SEMESTRE = E.LYCEUM_SEMESTRE
	JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA = T.DISCIPLINA
	JOIN LYCEUM..LY_DOCENTE DO ON DO.NUM_FUNC = T.NUM_FUNC
	JOIN LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE AND VW.DISCIPLINA = T.DISCIPLINA AND VW.TURMA = T.TURMA AND VW.ALUNO = E.LYCEUM_ALUNO
	WHERE 1=1
	AND SBA.PERIODO_LETIVO = CONCAT(@p_ano,'/',@p_semestre)
	AND SBA.ROLE = 'S'

	--INSERINDO INFORMAÕES DO BI

	UPDATE BBAA SET BBAA.UNIDADE_ENSINO_ALUNO = R.UNIDADE_ENSINO_ALUNO,
					BBAA.NOME_UNIDADE_ENSINO_ALUNO = R.NOME_UNIDADE_ENSINO_ALUNO,
					BBAA.UNIDADE_FISICA_ALUNO = R.UNIDADE_FISICA_ALUNO,
					BBAA.TIPO_CURSO = R.TIPO_CURSO,
					BBAA.CURSO = R.CURSO,
					BBAA.TURNO = R.TURNO,
					BBAA.CURRICULO = R.CURRICULO,
					BBAA.NOME_CURSO = R.NOME_CURSO,
					BBAA.TIPO_ALUNO = R.TIPO_ALUNO,
					BBAA.TIPO_FINAN = R.TIPO_FINAN,
					BBAA.STATUS_FTC = R.STATUS_FTC,
					BBAA.NOME_ALUNO = R.NOME_ALUNO
	FROM BI_BB_ACESSO_ALUNO BBAA
	JOIN BI_REMATRICULA R ON R.ALUNO = BBAA.ALUNO AND R.ANO = BBAA.ANO AND R.SEMESTRE = BBAA.SEMESTRE

	--INSERINDO DIAS DE AULA DAS TURMAS

	UPDATE BBAA SET BBAA.DIAS_AULA = STUFF(
											(SELECT DISTINCT '/' + CONVERT(VARCHAR(1),HA.DIA_SEMANA) AS [text()]
											FROM  LYCEUM..LY_HOR_AULA HA
											WHERE 1=1
											AND HA.ANO = BBAA.ANO 
											AND HA.SEMESTRE = BBAA.SEMESTRE 
											AND HA.TURMA = BBAA.TURMA 
											AND HA.DISCIPLINA = BBAA.DISCIPLINA
											FOR XML PATH('') 
											), 1, 1, '' 
										)
	FROM BI_BB_ACESSO_ALUNO BBAA
	WHERE 1=1 
	AND BBAA.ANO = @p_ano 
	AND BBAA.SEMESTRE = @p_semestre
	AND BBAA.DATA_CARGA = CONVERT(VARCHAR(10),GETDATE(),23)


	--INSERINDO CENTRO DE CUSTO

	UPDATE BBAA SET BBAA.CENTRO_DE_CUSTO = (	
											SELECT TOP 1 VW.CENTRO_DE_CUSTO 
											FROM LYCEUM..VW_CENTRO_DE_CUSTO VW
											WHERE VW.CURSO = BBAA.CURSO
										)
	FROM BI_BB_ACESSO_ALUNO BBAA
	WHERE 1=1 
	AND BBAA.ANO = @p_ano 
	AND BBAA.SEMESTRE = @p_semestre
	AND BBAA.DATA_CARGA = CONVERT(VARCHAR(10),GETDATE(),23)
	
	UPDATE BBAA SET BBAA.CENTRO_DE_CUSTO_DESC = (	
											SELECT TOP 1 HD.DESCR
											FROM HADES..HD_TABELAITEM HD
											WHERE HD.ITEM = BBAA.CENTRO_DE_CUSTO
											AND HD.TABELA = 'CentroCusto'
										)
	FROM BI_BB_ACESSO_ALUNO BBAA
	WHERE 1=1 
	AND BBAA.ANO = @p_ano 
	AND BBAA.SEMESTRE = @p_semestre
	AND BBAA.DATA_CARGA = CONVERT(VARCHAR(10),GETDATE(),23)

	DELETE FROM BI_BB_ACESSO_ALUNO WHERE UNIDADE_ENSINO_ALUNO = '' AND ANO = @p_ano AND SEMESTRE = @p_semestre




IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_BB_ACESSO_DOCENTE'))   
BEGIN
	DELETE FROM BI_BB_ACESSO_DOCENTE WHERE ANO = @p_ano AND SEMESTRE = @p_semestre AND DATA_CARGA =  CONVERT(VARCHAR(10),GETDATE(),23)
END

ELSE

BEGIN
	CREATE TABLE BI_BB_ACESSO_DOCENTE ( --DROP TABLE BI_BB_ACESSO_DOCENTE

		DATA_CARGA VARCHAR(10),
		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		UNIDADE_ENSINO VARCHAR(20),
		NOME_UNIDADE_ENSINO VARCHAR(200),
		UNIDADE_FISICA VARCHAR(20),
		TIPO_CURSO VARCHAR(50),
		CURSO VARCHAR(20),
		TURNO VARCHAR(1),
		CURRICULO VARCHAR(30),
		NOME_CURSO VARCHAR(200),
		TURMA VARCHAR(50),
		DISCIPLINA VARCHAR(30),
		NOME_DISCIPLINA VARCHAR(200),
		SIT_TURMA VARCHAR(30),
		DT_INICIO_TURMA VARCHAR(10),
		DT_FIM_TURMA VARCHAR(10),
		NUM_FUNC VARCHAR(20),
		NOME_DOCENTE VARCHAR(150),
		CPF_DOCENTE VARCHAR(11),
		NIVEL_TURMA VARCHAR(30),
		AULAS_PREVISTAS NUMERIC(10,2),
		ULTIMO_LOGIN DATETIME,
		ULTIMO_ACESSO_TURMA DATETIME,		
		DIAS_AULA VARCHAR(100),
		CENTRO_CUSTO VARCHAR(50),
		CENTRO_CUSTO_DESC VARCHAR(100)
	)

END

INSERT INTO BI_BB_ACESSO_DOCENTE
	SELECT
		CONVERT(VARCHAR(10),GETDATE(),23) AS DATA_CARGA,
		T.ANO,
		T.SEMESTRE,
		T.UNIDADE_RESPONSAVEL AS UNIDADE_ENSINO,
		UE.NOME_COMP AS NOME_UNIDADE_ENSINO,
		T.FACULDADE AS UNIDADE_FISICA,
		C.TIPO AS TIPO_CURSO,
		T.CURSO,
		T.TURNO,
		T.CURRICULO,
		C.NOME AS NOME_CURSO,
		T.TURMA,
		T.DISCIPLINA,
		D.NOME AS NOME_DICIPLINA,
		T.SIT_TURMA,
		CONVERT(VARCHAR(10),T.DT_INICIO,23) AS DT_INICIO_TURMA,
		CONVERT(VARCHAR(10),T.DT_FIM,23) AS DT_FIM_TURMA,
		DO.NUM_FUNC AS NUM_FUNC,
		DO.NOME_COMPL AS NOME_DOCENTE,
		E.external_person_key AS  CPF_DOCENTE,
		T.NIVEL,
		T.AULAS_PREVISTAS,
		SBA.LAST_LOGIN_DATE AS ULTIMO_LOGIN,
		SBA.LAST_ACCESS_DATE AS ULTIMO_ACESSO_TURMA,
		NULL AS DIAS_AULA,
		NULL AS CENTRO_DE_CUSTO,
		NULL AS CENTRO_DE_CUSTO_DESC
	FROM BLACKBOARD..ENROLLMENTS E 
	JOIN BLACKBOARD..SA_BB_ACESSO SBA ON SBA.COURSE_ID = E.external_course_key AND SBA.USER_ID = E.external_person_key
	JOIN LYCEUM..LY_TURMA T ON T.TURMA = E.LYCEUM_TURMA AND T.DISCIPLINA = E.LYCEUM_DISCIPLINA AND T.ANO = E.LYCEUM_ANO AND T.SEMESTRE = E.LYCEUM_SEMESTRE
	JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA = T.DISCIPLINA
	JOIN LYCEUM..LY_DOCENTE DO ON DO.NUM_FUNC = T.NUM_FUNC AND DO.CPF = E.external_person_key
	JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = T.UNIDADE_RESPONSAVEL
	JOIN LYCEUM..LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE
	LEFT JOIN LYCEUM..LY_CURSO C ON C.CURSO = T.CURSO
	WHERE 1=1
	AND SBA.PERIODO_LETIVO = CONCAT(@p_ano,'/',@p_semestre)
	AND SBA.ROLE <> 'S'

	

	--INSERINDO DIAS DE AULA DAS TURMAS

	UPDATE BBAD SET BBAD.DIAS_AULA = STUFF(
											(SELECT DISTINCT '/' + CONVERT(VARCHAR(1),HA.DIA_SEMANA) AS [text()]
											FROM  LYCEUM..LY_HOR_AULA HA
											WHERE 1=1
											AND HA.ANO = BBAD.ANO 
											AND HA.SEMESTRE = BBAD.SEMESTRE 
											AND HA.TURMA = BBAD.TURMA 
											AND HA.DISCIPLINA = BBAD.DISCIPLINA
											FOR XML PATH('') 
											), 1, 1, '' 
										)
	FROM BI_BB_ACESSO_DOCENTE BBAD
	WHERE 1=1 
	AND BBAD.ANO = @p_ano 
	AND BBAD.SEMESTRE = @p_semestre
	AND BBAD.DATA_CARGA = CONVERT(VARCHAR(10),GETDATE(),23)


	--INSERINDO CENTRO DE CUSTO

	UPDATE BBAD SET BBAD.CENTRO_DE_CUSTO = (	
											SELECT TOP 1 VW.CENTRO_DE_CUSTO 
											FROM LYCEUM..VW_CENTRO_DE_CUSTO VW
											WHERE VW.CURSO = EDSF.CURSO
										)
	FROM BI_BB_ACESSO_DOCENTE BBAD
	JOIN LYCEUMINTEGRACAO..FTC_ENQUADRAMENTO_DOCENTE_SUMARIO_FECHAMENTO EDSF ON EDSF.NUM_FUNC = BBAD.NUM_FUNC AND EDSF.FACULDADE = BBAD.UNIDADE_FISICA AND EDSF.CURSO <> ''
	WHERE 1=1 
	AND BBAD.ANO = @p_ano 
	AND BBAD.SEMESTRE = @p_semestre
	AND BBAD.DATA_CARGA = CONVERT(VARCHAR(10),GETDATE(),23)
	
	
	UPDATE BBAD SET BBAD.CENTRO_DE_CUSTO_DESC = (	
											SELECT TOP 1 HD.DESCR
											FROM HADES..HD_TABELAITEM HD
											WHERE HD.ITEM = BBAD.CENTRO_DE_CUSTO
											AND HD.TABELA = 'CentroCusto'
										)
	FROM BI_BB_ACESSO_DOCENTE BBAD
	WHERE 1=1 
	AND BBAD.ANO = @p_ano 
	AND BBAD.SEMESTRE = @p_semestre
	AND BBAD.DATA_CARGA = CONVERT(VARCHAR(10),GETDATE(),23)

	
END
-- [FIM]