
USE FTC_DATAMART
GO

--EXEC BI_CH_DOCENTE_JOB

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_CH_DOCENTE_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_CH_DOCENTE_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_CH_DOCENTE_JOB
AS
-- [INÍCIO]                    
BEGIN  

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_CH_DOCENTE'))   
BEGIN
	DROP TABLE BI_CH_DOCENTE
END

CREATE TABLE BI_CH_DOCENTE 
(
	[ANO] VARCHAR(4),
	[SEMESTRE] VARCHAR(2),
	[UNIDADE_FISICA]	VARCHAR(20),
	[NOME_UNIDADE_FISICA] VARCHAR(100),
	[CPF] VARCHAR(20),
	[NOME_DOCENTE] VARCHAR(100),
	[CH_SEMESTRE] NUMERIC
		
)       


INSERT INTO BI_CH_DOCENTE
SELECT        
  T.ANO,
  T.SEMESTRE,
  T.FACULDADE AS UNIDADE_FISICA,
  UF.NOME_COMP AS NOME_UNIDADE_FISICA,
  D.CPF,
  D.NOME_COMPL AS NOME_DOCENTE,
  ISNULL(SUM(HA.QTDE_AULA),0) AS CH_SEMESTRE    
  FROM LYCEUM..LY_TURMA T    
   INNER JOIN LYCEUM..LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE
   INNER JOIN LYCEUM..LY_DOCENTE D  ON D.NUM_FUNC  = T.NUM_FUNC 
   LEFT JOIN LYCEUM..LY_AULA_DOCENTE AD ON AD.TURMA = T.TURMA AND AD.TURNO = T.TURNO AND AD.DISCIPLINA = T.DISCIPLINA AND AD.ANO = T.ANO AND AD.SEMESTRE = T.SEMESTRE       
   LEFT JOIN LYCEUM..LY_HOR_AULA HA ON HA.AULA = AD.AULA AND HA.DIA_SEMANA = AD.DIA_SEMANA AND HA.TURNO = AD.TURNO AND HA.FACULDADE = AD.FACULDADE AND HA.DISCIPLINA = T.DISCIPLINA AND HA.TURMA = T.TURMA AND HA.ANO = T.ANO AND HA.SEMESTRE = T.SEMESTRE
   WHERE CPF IS NOT NULL
   GROUP BY T.ANO,T.SEMESTRE,T.FACULDADE,UF.NOME_COMP,D.CPF,D.NOME_COMPL
   ORDER BY 1,2,3,6

--[FIM]
END
GO