USE FTC_DATAMART
GO

--DROP TABLE BI_CURSOS_META

CREATE TABLE BI_CURSOS_META
(
	NOME_CURSO VARCHAR(100),
	META INT,
	TIPO_CURSO VARCHAR(30),
	TIPO_ALUNO VARCHAR(30),
	TURNO VARCHAR(1),
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	PERIODO_LETIVO VARCHAR(10)
)

INSERT INTO BI_CURSOS_META
SELECT	NOME_CURSO,
		SUM(METAS) AS META,
		TIPO_CURSO,
		TIPO_ALUNO,
		TURNO,
		ANO,
		SEMESTRE,
		CONCAT(ANO,'/',SEMESTRE) AS PERIODO_LETIVO
FROM BI_METAS
GROUP BY NOME_CURSO, TIPO_CURSO, ANO, SEMESTRE, TIPO_ALUNO,TURNO