USE FTC_DATAMART
GO

DECLARE @p_ano VARCHAR(4)
DECLARE @p_semestre VARCHAR(2)

SET @p_ano = '2019'
SET @p_semestre = '1'

/*

AÇOES:

1- Carregar base com alunos calouros matriculados no período a ser comparado
2- Calcular valor da dívida bruta de cada aluno e dividir por 6
3- Verficar quantas parcelas de isenção o aluno possui
3.1- Verificar quanto de isenção o aluno possui
4- Verificar quantas parcelas sem isenção o aluno possui
4.1. Verificar o valor de bolsa restante o aluno possui
5- Aplicar bolsa de isençao as parcelas correspondentes
6- Aplicar bolsas restantes nas parcelas restantes
7- Calcular todo o desconto ponderado com isenção: (soma de parcelas com isençao e sem isenção) dividido pelo (valor bruto da dívida)
8- Calcular o desconto ponderado sem isenção: (soma de parcelas sem isenção) dividido pelo (valor bruto correspondente as parcelas sem isenção)

*/

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_DMP2'))   
BEGIN
	DELETE FROM BI_DMP2 WHERE ANO = @p_ano AND SEMESTRE = @p_semestre
END

ELSE 

CREATE TABLE BI_DMP2 --DROP TABLE BI_DMP2
(
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	UNIDADE_FISICA VARCHAR(20),
	UNIDADE_ENSINO VARCHAR(20),
	CURSO VARCHAR(20),
	NOME_CURSO VARCHAR(200),
	CURRICULO VARCHAR(100),
	TURNO VARCHAR(1),
	ALUNO VARCHAR(20),
	TIPO_FINAN VARCHAR(30),
	TIPO_ALUNO VARCHAR(30),
	TIPO_INGRESSO VARCHAR(30),
	DATA_MATRICULA VARCHAR(10),
	DIA_CAMPANHA INT,
	VALOR_DIVIDA DECIMAL(10,2),
	VALOR_PARCELA DECIMAL (10,2),
	VALOR_PARCELA_ISENCAO DECIMAL(10,2),
	VALOR_PARCELA_SEM_ISENCAO DECIMAL(10,2),
	VALOR_BOLSA_ISENCAO DECIMAL(10,2),
	VALOR_BOLSA_SEM_ISENCAO DECIMAL(10,2),
	QTD_PARCELAS_ISENCAO INT,
	QTD_PARCELAS_SEM_ISENCAO INT,
	DMP DECIMAL(10,2),
	DMP_SEM_ISENCAO DECIMAL(10,2),
	RENUNCIA DECIMAL(10,2),
	RENUNCIA_POTENCIAL DECIMAL(10,2),
	BOLSAS VARCHAR(200)
	 
)

--Carregar tabela com alunos calouros matriculados no período
INSERT INTO BI_DMP2
SELECT	R.ANO,
		R.SEMESTRE,
		UNIDADE_FISICA_ALUNO AS UNIDADE_FISICA,
		UNIDADE_ENSINO_ALUNO AS UNIDADE_ENSINO,
		CURSO,
		NOME_CURSO,
		CURRICULO,
		TURNO,
		ALUNO,
		NOME_ALUNO,
		FINAN AS PAGO,
		TIPO_FINAN,
		TIPO_ALUNO,
		TIPO_INGRESSO,
		DATA_MATRICULA,
		DATEDIFF(DAY,CONVERT(DATETIME,A.DATA_INI_CAMPANHA,103),CONVERT(DATETIME,DATA_MATRICULA,103))+1 AS DIA_CAMPANHA,
		0.00 AS VALOR_DIVIDA,
		0.00 AS VALOR_PARCELA,
		0.00 AS VALOR_PARCELA_ISENCAO,
		0.00 AS VALOR_PARCELA_SEM_ISENCAO,
		0.00 AS VALOR_BOLSA_ISENCAO,
		0.00 AS VALOR_BOLSA_SEM_ISENCAO,
		0 AS QTD_PARCELAS_ISENCAO,
		0 AS QTD_PARCELAS_SEM_ISENCAO,
		0.00 AS DMP,
		0.00 AS DMP_SEM_ISENCAO,
		0.00 AS RENUNCIA,
		0.00 AS RENUNCIA_POTENCIAL,
		''  AS BOLSAS
FROM BI_REMATRICULA R
JOIN BI_AUX_DMP_DIA_CAMPANHA  A ON A.ANO = R.ANO AND A.SEMESTRE = R.SEMESTRE
WHERE R.ANO = @p_ano
AND R.SEMESTRE = @p_semestre
AND TIPO_ALUNO IN ('CALOURO','REINGRESSO','CALOURO-CONCLUINTE','REINGRESSO-CONCLUINTE')
AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND TIPO_INGRESSO NOT IN ('TransferenciaInterna','Ouvintes')
AND TIPO_FINAN IN ('FIES','PAGANTES')



--Atualizar valor da dívida bruta no semestre
UPDATE B SET B.VALOR_DIVIDA = (SELECT ISNULL(SUM(LD.VALOR),0.00) 
					FROM LYCEUM..LY_LANC_DEBITO LD
					WHERE LD.ALUNO = B.ALUNO
					AND LD.ANO_REF = B.ANO
					AND LD.PERIODO_REF = B.SEMESTRE
					AND LD.CODIGO_LANC IN ('MS','SM')
					AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno'))
FROM BI_DMP2 B
WHERE B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre


--Atualizar valor bruto da parcela
UPDATE B SET B.VALOR_PARCELA = B.VALOR_DIVIDA/6
FROM BI_DMP2 B
WHERE B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre


--Verificar quantas parcelas de bolsa-isenção o aluno possui

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.TEMP_BOLSA'))   
BEGIN
	DROP TABLE TEMP_BOLSA
END

CREATE TABLE TEMP_BOLSA
(
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	TIPO_BOLSA VARCHAR(50),
	PERC_VALOR VARCHAR(20),
	VALOR DECIMAL(10,2),
	ALUNO VARCHAR(20),
	ISENCAO VARCHAR(1),
	QTD_PARCELAS INT

)

INSERT INTO TEMP_BOLSA
SELECT	@p_ano AS ANO,
		@p_semestre AS SEMESTRE,
		B.TIPO_BOLSA,
		B.PERC_VALOR,
		B.VALOR,
		B.ALUNO,
		'S' AS ISENCAO,
		(ISNULL(B.MESFIM,CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END) - B.MESINI)+1 AS QTD_PARCELAS
FROM LYCEUM..LY_BOLSA B
JOIN BI_DMP2 D ON D.ALUNO = B.ALUNO
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE 1=1
AND B.DATA_CANCEL IS NULL
AND B.TIPO_BOLSA NOT LIKE '%PROIES%'
AND B.TIPO_BOLSA NOT LIKE '%PROUNI%'
AND B.TIPO_BOLSA NOT LIKE '%FIES%'
AND B.ANOINI = @p_ano
AND B.MESINI >= CASE WHEN @p_semestre = '1' THEN 1 ELSE 7 END
AND B.ANOFIM = ISNULL(@p_ano,B.ANOFIM)
AND B.MESFIM <= CASE WHEN @p_semestre = '1' THEN ISNULL(3,6) ELSE ISNULL(9,12) END


INSERT INTO TEMP_BOLSA
SELECT	@p_ano AS ANO,
		@p_semestre AS SEMESTRE,
		B.TIPO_BOLSA,
		B.PERC_VALOR,
		B.VALOR,
		B.ALUNO,
		'N' AS ISENCAO,
		(ISNULL(B.MESFIM,CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END) - B.MESINI)+1 AS QTD_PARCELAS
FROM LYCEUM..LY_BOLSA B
JOIN BI_DMP2 D ON D.ALUNO = B.ALUNO 
WHERE 1=1
AND B.DATA_CANCEL IS NULL
AND B.ANOINI = @p_ano
AND B.MESINI >= CASE WHEN @p_semestre = '1' THEN 1 ELSE 7 END
AND (B.ANOFIM = @p_ano OR B.ANOFIM IS NULL)
AND (B.MESFIM <= CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END OR MESFIM IS NULL)
AND NOT EXISTS (SELECT TOP 1 1 FROM TEMP_BOLSA B1 WHERE B1.ALUNO = B.ALUNO AND B1.ANO = @p_ano 
				AND B1.SEMESTRE = @p_semestre AND B1.ISENCAO = 'S' AND B1.TIPO_BOLSA = B.TIPO_BOLSA 
				AND B1.PERC_VALOR = B.PERC_VALOR AND B1.VALOR = B.VALOR)


UPDATE B SET	B.QTD_PARCELAS_ISENCAO = BO.QTD_PARCELAS, 
				B.VALOR_PARCELA_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_PARCELA - BO.VALOR ELSE B.VALOR_PARCELA*(1-BO.VALOR) END,
				B.VALOR_BOLSA_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN BO.VALOR ELSE B.VALOR_PARCELA*BO.VALOR END
FROM BI_DMP2 B
JOIN TEMP_BOLSA BO ON BO.ALUNO = B.ALUNO AND BO.ANO = B.ANO AND BO.SEMESTRE = B.SEMESTRE
WHERE BO.ISENCAO = 'S'


UPDATE B SET	B.QTD_PARCELAS_SEM_ISENCAO = BO.QTD_PARCELAS, 
				B.VALOR_PARCELA_SEM_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_PARCELA - BO.VALOR ELSE B.VALOR_PARCELA*(1-BO.VALOR) END,
				B.VALOR_BOLSA_SEM_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN BO.VALOR ELSE B.VALOR_PARCELA*BO.VALOR END
FROM BI_DMP2 B
JOIN TEMP_BOLSA BO ON BO.ALUNO = B.ALUNO AND BO.ANO = B.ANO AND BO.SEMESTRE = B.SEMESTRE
WHERE BO.ISENCAO = 'N'

UPDATE B SET DMP = 1-((VALOR_PARCELA_ISENCAO*QTD_PARCELAS_ISENCAO + VALOR_PARCELA_SEM_ISENCAO*QTD_PARCELAS_SEM_ISENCAO)/VALOR_DIVIDA)
FROM BI_DMP2 B
WHERE B.VALOR_DIVIDA > 0.00
AND QTD_PARCELAS_ISENCAO > 0
AND B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre

UPDATE B SET DMP_SEM_ISENCAO = 1-((VALOR_PARCELA_SEM_ISENCAO*QTD_PARCELAS_SEM_ISENCAO)/(VALOR_PARCELA*QTD_PARCELAS_SEM_ISENCAO))
FROM BI_DMP2 B
WHERE VALOR_PARCELA > 0.00
AND QTD_PARCELAS_SEM_ISENCAO > 0
AND B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre

UPDATE B SET VALOR_PARCELA_ISENCAO = VALOR_PARCELA
FROM BI_DMP2 B 
WHERE B.DMP = 0.00
AND B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre

UPDATE B SET VALOR_PARCELA_SEM_ISENCAO = VALOR_PARCELA
FROM BI_DMP2 B 
WHERE B.DMP_SEM_ISENCAO = 0.00
AND B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre


UPDATE BI_DMP2 SET DIA_CAMPANHA = 1
WHERE DIA_CAMPANHA < 1
AND ANO = @p_ano
AND SEMESTRE = @p_semestre


UPDATE D SET D.RENUNCIA = ((D.VALOR_PARCELA-D.VALOR_PARCELA_ISENCAO)*D.QTD_PARCELAS_ISENCAO) + ((D.VALOR_PARCELA - D.VALOR_PARCELA_SEM_ISENCAO)*D.QTD_PARCELAS_SEM_ISENCAO)
FROM BI_DMP2 D
WHERE D.ANO = @p_ano
AND D.SEMESTRE = @p_semestre


UPDATE D SET D.RENUNCIA_POTENCIAL = D.RENUNCIA + ((D.VALOR_PARCELA - D.VALOR_PARCELA_SEM_ISENCAO)*6)*(SELECT MAX(G.SERIE_IDEAL)-1 FROM LYCEUM..LY_GRADE G WHERE G.CURSO = D.CURSO AND G.CURRICULO = D.CURRICULO AND D.TURNO = G.TURNO)
FROM BI_DMP2 D
WHERE D.ANO = @p_ano
AND D.SEMESTRE = @p_semestre

UPDATE BI_DMP2 SET RENUNCIA_POTENCIAL = 0.00 WHERE RENUNCIA = 0.00
AND ANO = @p_ano
AND SEMESTRE = @p_semestre


-- LISTA DE BOLSAS CADASTRADAS PRO ALUNO
	UPDATE T SET T.BOLSAS = STUFF((SELECT DISTINCT ',' + B.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..LY_BOLSA B
                        WHERE 1=1
						AND B.TIPO_BOLSA NOT LIKE '%FIES%'
						AND (B.ANOFIM >= @p_ano OR B.ANOFIM IS NULL) AND (B.MESFIM >= CASE @p_semestre WHEN 1 THEN 6 ELSE 12 END OR B.MESFIM IS NULL OR (B.MESINI = B.MESFIM AND B.ANOINI = B.ANOFIM))
						AND B.DATA_CANCEL IS NULL
                        AND B.ALUNO = T.ALUNO
                        FOR XML PATH('') 
                        ), 1, 1, '' )
	FROM BI_DMP2 T
	WHERE T.ANO = @p_ano AND T.SEMESTRE = @p_semestre


	DROP TABLE TEMP_BOLSA