USE FTC_DATAMART
GO

--EXEC BI_DMP_JOB 2020,1
--DROP TABLE BI_DMP2
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_DMP_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_DMP_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_DMP_JOB
(				
  @p_ano VARCHAR(4)      
, @p_semestre VARCHAR(2)      

)            
AS            
-- [INÍCIO]                    
BEGIN  

/*

AÇOES:

1- Carregar base com alunos calouros matriculados no período a ser comparado
2- Calcular valor da dívida bruta de cada aluno e dividir por 6
3- Verficar quantas parcelas de isenção o aluno possui
3.1- Verificar quanto de isenção o aluno possui
4- Verificar quantas parcelas sem isenção o aluno possui
4.1. Verificar o valor de bolsa restante o aluno possui
5- Aplicar bolsa de isençao as parcelas correspondentes
6- Aplicar bolsas restantes nas parcelas restantes
7- Calcular todo o desconto ponderado com isenção: (soma de parcelas com isençao e sem isenção) dividido pelo (valor bruto da dívida)
8- Calcular o desconto ponderado sem isenção: (soma de parcelas sem isenção) dividido pelo (valor bruto correspondente as parcelas sem isenção)

*/
	
IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_DMP2'))   
BEGIN
	DELETE FROM BI_DMP2 WHERE ANO = @p_ano AND SEMESTRE = @p_semestre
END    

ELSE
BEGIN

CREATE TABLE BI_DMP2 --DROP TABLE BI_DMP2
(
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	UNIDADE_FISICA VARCHAR(20),
	UNIDADE_ENSINO VARCHAR(20),
	CURSO VARCHAR(20),
	NOME_CURSO VARCHAR(200),
	CURRICULO VARCHAR(100),
	TURNO VARCHAR(1),
	ALUNO VARCHAR(20),
	NOME_ALUNO VARCHAR(200),
	PAGO VARCHAR(20),
	TIPO_FINAN VARCHAR(30),
	TIPO_ALUNO VARCHAR(30),
	TIPO_INGRESSO VARCHAR(30),
	DATA_MATRICULA VARCHAR(10),
	DIA_CAMPANHA INT,
	VALOR_DIVIDA DECIMAL(10,2),
	VALOR_PARCELA DECIMAL (10,2),
	VALOR_PARCELA_ISENCAO DECIMAL(10,2),
	VALOR_PARCELA_SEM_ISENCAO DECIMAL(10,2),
	VALOR_BOLSA_ISENCAO DECIMAL(10,2),
	VALOR_BOLSA_SEM_ISENCAO DECIMAL(10,2),
	QTD_PARCELAS_ISENCAO INT,
	QTD_PARCELAS_SEM_ISENCAO INT,
	DMP DECIMAL(10,3),
	DMP_SEM_ISENCAO DECIMAL(10,3),
	RENUNCIA DECIMAL(10,2),
	RENUNCIA_POTENCIAL DECIMAL(10,2),
	BOLSAS VARCHAR(200)
	 
)

--Carregar tabela com alunos calouros matriculados no período
INSERT INTO BI_DMP2
SELECT	R.ANO,
		R.SEMESTRE,
		UNIDADE_FISICA_ALUNO,
		UNIDADE_ENSINO_ALUNO,
		CURSO,
		NOME_CURSO,
		CURRICULO,
		TURNO,
		ALUNO,
		NOME_ALUNO,
		FINAN AS PAGO,
		TIPO_FINAN,
		TIPO_ALUNO,
		TIPO_INGRESSO,
		CONVERT(VARCHAR(10),DATA_MATRICULA,103) AS DATA_MATRICULA,
		DATEDIFF(DAY,CONVERT(DATETIME,A.DATA_INI_CAMPANHA,103),CONVERT(DATETIME,DATA_MATRICULA,103))+1 AS DIA_CAMPANHA,
		0.00 AS VALOR_DIVIDA,
		0.00 AS VALOR_PARCELA,
		0.00 AS VALOR_PARCELA_ISENCAO,
		0.00 AS VALOR_PARCELA_SEM_ISENCAO,
		0.00 AS VALOR_BOLSA_ISENCAO,
		0.00 AS VALOR_BOLSA_SEM_ISENCAO,
		0 AS QTD_PARCELAS_ISENCAO,
		0 AS QTD_PARCELAS_SEM_ISENCAO,
		0.000 AS DMP,
		0.000 AS DMP_SEM_ISENCAO,
		0.00 AS RENUNCIA,
		0.00 AS RENUNCIA_POTENCIAL,  
		'' AS BOLSAS  
FROM BI_REMATRICULA R
JOIN BI_AUX_DMP_DIA_CAMPANHA  A ON A.ANO = R.ANO AND A.SEMESTRE = R.SEMESTRE
WHERE R.ANO = @p_ano
AND R.SEMESTRE = @p_semestre
AND TIPO_ALUNO IN ('CALOURO','REINGRESSO','CALOURO-CONCLUINTE','REINGRESSO-CONCLUINTE')
AND TIPO_INGRESSO NOT IN ('TransferenciaInterna','Ouvinte')
AND R.STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND R.TIPO_FINAN IN ('FIES','PAGANTES')
AND R.TIPO_CURSO IN ('GRADUACAO','TECNOLOGO')


END 


--Atualizar valor da dívida bruta no semestre
UPDATE B SET B.VALOR_DIVIDA = (SELECT ISNULL(SUM(LD.VALOR),0.00) 
					FROM LYCEUM..LY_LANC_DEBITO LD
					WHERE LD.ALUNO = B.ALUNO
					AND LD.ANO_REF = B.ANO
					AND LD.PERIODO_REF = B.SEMESTRE
					AND LD.CODIGO_LANC IN ('MS','SM')
					AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno'))
FROM BI_DMP2 B
WHERE B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre


--Atualizar valor bruto da parcela
UPDATE B SET B.VALOR_PARCELA = B.VALOR_DIVIDA/6
FROM BI_DMP2 B
WHERE B.ANO = @p_ano
AND B.SEMESTRE = @p_semestre


--Verificar quantas parcelas de bolsa-isenção o aluno possui

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.TEMP_BOLSA'))   
BEGIN
	DROP TABLE TEMP_BOLSA
END

CREATE TABLE TEMP_BOLSA
(
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	TIPO_BOLSA VARCHAR(50),
	PERC_VALOR VARCHAR(20),
	VALOR DECIMAL(10,2),
	ALUNO VARCHAR(20),
	ISENCAO VARCHAR(1),
	QTD_PARCELAS INT,
	NUM_BOLSA INT,
	ANOINI VARCHAR(4),
	ANOFIM VARCHAR(4),
	MESINI VARCHAR(2),
	MESFIM VARCHAR(2),
	ACUMULA VARCHAR(1)

)

INSERT INTO TEMP_BOLSA
SELECT	@p_ano AS ANO,
		@p_semestre AS SEMESTRE,
		B.TIPO_BOLSA,
		B.PERC_VALOR,
		CONVERT(DECIMAL(10,2),B.VALOR) AS VALOR,
		B.ALUNO,
		'S' AS ISENCAO,
		(ISNULL(B.MESFIM,CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END) - B.MESINI)+1 AS QTD_PARCELAS,
		NUM_BOLSA,
		B.ANOINI,
		B.ANOFIM,
		B.MESINI,
		B.MESFIM,
		'N' AS ACUMULA
FROM LYCEUM..LY_BOLSA B
JOIN BI_DMP2 D ON D.ALUNO = B.ALUNO
WHERE 1=1
AND B.DATA_CANCEL IS NULL
AND B.TIPO_BOLSA NOT LIKE '%PROIES%'
AND B.TIPO_BOLSA NOT LIKE '%PROUNI%'
AND B.TIPO_BOLSA NOT LIKE '%FIES%'
AND B.ANOINI = @p_ano
AND B.MESINI >= CASE WHEN @p_semestre = '1' THEN 1 ELSE 7 END
AND B.ANOFIM = ISNULL(@p_ano,B.ANOFIM)
AND B.MESFIM <= CASE WHEN @p_semestre = '1' THEN ISNULL(3,6) ELSE ISNULL(9,12) END /*até então, bolsas de isenção eram no máximo até o 3*/


INSERT INTO TEMP_BOLSA
SELECT	@p_ano AS ANO,
		@p_semestre AS SEMESTRE,
		B.TIPO_BOLSA,
		B.PERC_VALOR,
		CONVERT(DECIMAL(10,2),B.VALOR) AS VALOR,
		B.ALUNO,
		'N' AS ISENCAO,
		(ISNULL(B.MESFIM,CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END) - B.MESINI)+1 AS QTD_PARCELAS,
		NUM_BOLSA,		
		B.ANOINI,
		B.ANOFIM,
		B.MESINI,
		B.MESFIM,
		'N' AS ACUMULA
FROM LYCEUM..LY_BOLSA B
JOIN BI_DMP2 D ON D.ALUNO = B.ALUNO 
WHERE 1=1
AND B.DATA_CANCEL IS NULL
AND B.ANOINI = @p_ano
AND B.MESINI >= CASE WHEN @p_semestre = '1' THEN 1 ELSE 7 END
AND (B.ANOFIM = @p_ano OR B.ANOFIM IS NULL)
AND B.TIPO_BOLSA NOT LIKE '%FIES%'
--AND (B.MESFIM <= CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END OR B.MESFIM IS NULL)
AND NOT EXISTS (SELECT TOP 1 1 FROM TEMP_BOLSA B1 WHERE B1.ALUNO = B.ALUNO AND B1.ANO = @p_ano 
				AND B1.SEMESTRE = @p_semestre AND B1.ISENCAO = 'S' AND B1.TIPO_BOLSA = B.TIPO_BOLSA 
				AND B1.PERC_VALOR = B.PERC_VALOR AND CONVERT(DECIMAL(10,2),B1.VALOR) = CONVERT(DECIMAL(10,2),B.VALOR) AND B1.NUM_BOLSA = B.NUM_BOLSA)


		UPDATE T1 SET T1.ACUMULA = 'S'
		FROM TEMP_BOLSA T1
		WHERE EXISTS (	SELECT TOP 1 1 
						FROM TEMP_BOLSA T2 
						WHERE T2.ALUNO = T1.ALUNO 
						AND T2.ISENCAO = T1.ISENCAO 
						AND T2.ANOINI = T1.ANOINI 
						AND T2.MESINI = T1.MESINI 
						AND T2.NUM_BOLSA <> T1.NUM_BOLSA  )

		DELETE FROM TEMP_BOLSA WHERE VALOR = 0.00

		--DELETE T2 FROM TEMP_BOLSA T2 WHERE 1=1
		--AND T2.ISENCAO = 'S'
		--AND 		EXISTS (SELECT TOP 1 1 
		--				FROM TEMP_BOLSA T1 
		--				WHERE T2.ALUNO = T1.ALUNO 
		--				AND T2.ISENCAO = T1.ISENCAO 
		--				AND T2.ANOINI = T1.ANOINI 
		--				AND T2.MESINI = T1.MESINI 
		--				AND T2.NUM_BOLSA = T1.NUM_BOLSA
		--				AND T1.ISENCAO = 'N')

		UPDATE BI_DMP2 SET VALOR_PARCELA_ISENCAO = VALOR_PARCELA WHERE ANO = @p_ano AND SEMESTRE = @p_semestre 
		UPDATE BI_DMP2 SET VALOR_PARCELA_SEM_ISENCAO = VALOR_PARCELA WHERE ANO = @p_ano AND SEMESTRE = @p_semestre
		
		UPDATE T SET T.MESFIM = CASE T.SEMESTRE WHEN 1 THEN 6 ELSE 12 END
		FROM TEMP_BOLSA T
		WHERE T.MESFIM > CASE T.SEMESTRE WHEN 1 THEN 6 ELSE 12 END


		DELETE FROM TEMP_BOLSA WHERE MESINI > MESFIM

		UPDATE T SET T.QTD_PARCELAS = (CONVERT(INT,T.MESFIM) - CONVERT(INT,T.MESINI)) + 1
		FROM TEMP_BOLSA T
		WHERE T.QTD_PARCELAS > 6		
			   

		DECLARE @p_tipo_bolsa VARCHAR(50), @p_perc_valor VARCHAR(20), @p_valor DECIMAL(10,2), @p_aluno VARCHAR(20), @p_qtd_parcelas INT, @p_num_bolsa INT, @p_anoini VARCHAR(4), @p_mesini VARCHAR(2), @p_acumula VARCHAR(1)
		DECLARE cursor1 CURSOR FOR
		SELECT DISTINCT TIPO_BOLSA, PERC_VALOR, VALOR, ALUNO, QTD_PARCELAS, NUM_BOLSA, ANOINI, MESINI,ACUMULA
		FROM TEMP_BOLSA
		WHERE ISENCAO = 'S' AND ACUMULA = 'S'
		ORDER BY ALUNO,ANOINI,MESINI,NUM_BOLSA
				
		OPEN cursor1

		FETCH NEXT FROM cursor1 INTO @p_tipo_bolsa, @p_perc_valor, @p_valor, @p_aluno, @p_qtd_parcelas, @p_num_bolsa, @p_anoini, @p_mesini, @p_acumula

		WHILE @@FETCH_STATUS = 0
		BEGIN

			UPDATE B SET	B.QTD_PARCELAS_ISENCAO = B.QTD_PARCELAS_ISENCAO+@p_qtd_parcelas, 
							B.VALOR_PARCELA_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_PARCELA_ISENCAO - BO.VALOR ELSE B.VALOR_PARCELA_ISENCAO*(1-BO.VALOR) END,
							B.VALOR_BOLSA_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN BO.VALOR ELSE B.VALOR_PARCELA*BO.VALOR END
			FROM BI_DMP2 B
			JOIN TEMP_BOLSA BO ON BO.TIPO_BOLSA = @p_tipo_bolsa AND BO.PERC_VALOR = @p_perc_valor AND BO.VALOR = @p_valor AND BO.ALUNO = @p_aluno AND BO.NUM_BOLSA = @p_num_bolsa
			WHERE BO.ISENCAO = 'S' AND BO.ACUMULA =  'S' AND B.ALUNO = @p_aluno
		

		FETCH NEXT FROM cursor1 INTO @p_tipo_bolsa, @p_perc_valor, @p_valor, @p_aluno, @p_qtd_parcelas, @p_num_bolsa, @p_anoini, @p_mesini, @p_acumula
		
		END
		CLOSE cursor1
		DEALLOCATE cursor1



		DECLARE @p_tipo_bolsa1 VARCHAR(50), @p_perc_valor1 VARCHAR(20), @p_valor1 DECIMAL(10,2), @p_aluno1 VARCHAR(20), @p_qtd_parcelas1 INT, @p_num_bolsa1 INT, @p_anoini1 VARCHAR(4), @p_mesini1 VARCHAR(2),@p_acumula1 VARCHAR(1) 
		DECLARE cursor2 CURSOR FOR
		SELECT DISTINCT TIPO_BOLSA, PERC_VALOR, VALOR, ALUNO, QTD_PARCELAS, NUM_BOLSA, ANOINI, MESINI, ACUMULA
		FROM TEMP_BOLSA
		WHERE ISENCAO = 'N' AND ACUMULA = 'S'
		ORDER BY ALUNO,ANOINI,MESINI,NUM_BOLSA
				
		OPEN cursor2

		FETCH NEXT FROM cursor2 INTO @p_tipo_bolsa1, @p_perc_valor1, @p_valor1, @p_aluno1, @p_qtd_parcelas1, @p_num_bolsa1, @p_anoini1, @p_mesini1, @p_acumula1

		WHILE @@FETCH_STATUS = 0
		BEGIN

			UPDATE B SET	B.QTD_PARCELAS_SEM_ISENCAO = @p_qtd_parcelas1,
							B.VALOR_PARCELA_SEM_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_PARCELA_SEM_ISENCAO - BO.VALOR ELSE B.VALOR_PARCELA_SEM_ISENCAO*(1-BO.VALOR) END,
							B.VALOR_BOLSA_SEM_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN BO.VALOR ELSE B.VALOR_PARCELA*BO.VALOR END
			FROM BI_DMP2 B
			JOIN TEMP_BOLSA BO ON BO.TIPO_BOLSA = @p_tipo_bolsa1 AND BO.PERC_VALOR = @p_perc_valor1 AND BO.VALOR = @p_valor1 AND BO.NUM_BOLSA = @p_num_bolsa1
			WHERE BO.ISENCAO = 'N' AND BO.ACUMULA = 'S' AND B.ALUNO = @p_aluno1

			
		FETCH NEXT FROM cursor2 INTO @p_tipo_bolsa1, @p_perc_valor1, @p_valor1, @p_aluno1, @p_qtd_parcelas1, @p_num_bolsa1,@p_anoini1, @p_mesini1, @p_acumula1
		END
		CLOSE cursor2

		DEALLOCATE cursor2

		UPDATE BI_DMP2 SET VALOR_PARCELA_ISENCAO = 0.00 WHERE ANO = @p_ano AND SEMESTRE = @p_semestre  AND VALOR_PARCELA_ISENCAO = VALOR_PARCELA
		UPDATE BI_DMP2 SET VALOR_PARCELA_SEM_ISENCAO = 0.00 WHERE ANO = @p_ano AND SEMESTRE = @p_semestre AND VALOR_PARCELA_SEM_ISENCAO = VALOR_PARCELA

		DECLARE @p_tipo_bolsa2 VARCHAR(50), @p_perc_valor2 VARCHAR(20), @p_valor2 DECIMAL(10,2), @p_aluno2 VARCHAR(20), @p_qtd_parcelas2 INT, @p_num_bolsa2 INT,@p_anoini2 VARCHAR(4), @p_mesini2 VARCHAR(2), @p_acumula2 VARCHAR(1)
		DECLARE cursor3 CURSOR FOR
		SELECT DISTINCT TIPO_BOLSA, PERC_VALOR, VALOR, ALUNO, QTD_PARCELAS, NUM_BOLSA, ANOINI, MESINI, ACUMULA
		FROM TEMP_BOLSA
		WHERE ISENCAO = 'S' AND ACUMULA = 'N'
		ORDER BY ALUNO,ANOINI,MESINI,NUM_BOLSA
				
		OPEN cursor3

		FETCH NEXT FROM cursor3 INTO @p_tipo_bolsa2, @p_perc_valor2, @p_valor2, @p_aluno2, @p_qtd_parcelas2, @p_num_bolsa2, @p_anoini2, @p_mesini2, @p_acumula2

		WHILE @@FETCH_STATUS = 0
		BEGIN

			UPDATE B SET	B.QTD_PARCELAS_ISENCAO = B.QTD_PARCELAS_ISENCAO+@p_qtd_parcelas2, 
							B.VALOR_PARCELA_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_PARCELA_ISENCAO + (B.VALOR_PARCELA - BO.VALOR) ELSE B.VALOR_PARCELA_ISENCAO + (B.VALOR_PARCELA*(1-BO.VALOR)) END,
							B.VALOR_BOLSA_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN BO.VALOR ELSE B.VALOR_PARCELA*BO.VALOR END
			FROM BI_DMP2 B
			JOIN TEMP_BOLSA BO ON BO.TIPO_BOLSA = @p_tipo_bolsa2 AND BO.PERC_VALOR = @p_perc_valor2 AND BO.VALOR = @p_valor2 AND BO.ALUNO = @p_aluno2 AND BO.NUM_BOLSA = @p_num_bolsa2
			WHERE BO.ISENCAO = 'S' AND BO.ACUMULA =  'N' AND B.ALUNO = @p_aluno2
		

		FETCH NEXT FROM cursor3 INTO @p_tipo_bolsa2, @p_perc_valor2, @p_valor2, @p_aluno2, @p_qtd_parcelas2, @p_num_bolsa2, @p_anoini2, @p_mesini2, @p_acumula2
		
		END
		CLOSE cursor3
		DEALLOCATE cursor3



		DECLARE @p_tipo_bolsa3 VARCHAR(50), @p_perc_valor3 VARCHAR(20), @p_valor3 DECIMAL(10,2), @p_aluno3 VARCHAR(20), @p_qtd_parcelas3 INT, @p_num_bolsa3 INT, @p_anoini3 VARCHAR(4), @p_mesini3 VARCHAR(2), @p_acumula3 VARCHAR(1) 
		DECLARE cursor4 CURSOR FOR
		SELECT DISTINCT TIPO_BOLSA, PERC_VALOR, VALOR, ALUNO, QTD_PARCELAS, NUM_BOLSA,ANOINI, MESINI, ACUMULA
		FROM TEMP_BOLSA
		WHERE ISENCAO = 'N' AND ACUMULA = 'N'
		ORDER BY ALUNO,ANOINI,MESINI,NUM_BOLSA
				
		OPEN cursor4

		FETCH NEXT FROM cursor4 INTO @p_tipo_bolsa3, @p_perc_valor3, @p_valor3, @p_aluno3, @p_qtd_parcelas3, @p_num_bolsa3,@p_anoini3, @p_mesini3, @p_acumula3

		WHILE @@FETCH_STATUS = 0
		BEGIN

			UPDATE B SET	B.QTD_PARCELAS_SEM_ISENCAO = @p_qtd_parcelas3,
							B.VALOR_PARCELA_SEM_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_PARCELA_SEM_ISENCAO + (B.VALOR_PARCELA - BO.VALOR) ELSE B.VALOR_PARCELA_SEM_ISENCAO + (B.VALOR_PARCELA*(1-BO.VALOR)) END,
							B.VALOR_BOLSA_SEM_ISENCAO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN BO.VALOR ELSE B.VALOR_PARCELA*BO.VALOR END
			FROM BI_DMP2 B
			JOIN TEMP_BOLSA BO ON BO.TIPO_BOLSA = @p_tipo_bolsa3 AND BO.PERC_VALOR = @p_perc_valor3 AND BO.VALOR = @p_valor3 AND BO.ALUNO = @p_aluno3 AND BO.NUM_BOLSA = @p_num_bolsa3
			WHERE BO.ISENCAO = 'N' AND BO.ACUMULA = 'N' AND B.ALUNO = @p_aluno3

			
		FETCH NEXT FROM cursor4 INTO @p_tipo_bolsa3, @p_perc_valor3, @p_valor3, @p_aluno3, @p_qtd_parcelas3, @p_num_bolsa3, @p_anoini3, @p_mesini3, @p_acumula3
		END
		CLOSE cursor4
		DEALLOCATE cursor4




UPDATE B SET DMP = 1-(((VALOR_PARCELA_ISENCAO*QTD_PARCELAS_ISENCAO) + (VALOR_PARCELA_SEM_ISENCAO*QTD_PARCELAS_SEM_ISENCAO))/VALOR_DIVIDA)
FROM BI_DMP2 B
WHERE B.VALOR_DIVIDA > 0.00
AND B.QTD_PARCELAS_ISENCAO > 0
AND B.ANO = @p_ano AND B.SEMESTRE = @p_semestre

UPDATE B SET DMP_SEM_ISENCAO = 1-((VALOR_PARCELA_SEM_ISENCAO*QTD_PARCELAS_SEM_ISENCAO)/(VALOR_PARCELA*QTD_PARCELAS_SEM_ISENCAO))
FROM BI_DMP2 B
WHERE B.VALOR_PARCELA > 0.00
AND B.QTD_PARCELAS_SEM_ISENCAO > 0
AND B.ANO = @p_ano AND B.SEMESTRE = @p_semestre

--UPDATE B SET B.VALOR_PARCELA_ISENCAO = B.VALOR_PARCELA, B.DMP_SEM_ISENCAO = 0.00
--FROM BI_DMP2 B 
--WHERE B.TIPO_FINAN = 'FIES'

UPDATE B SET B.VALOR_PARCELA_ISENCAO = B.VALOR_PARCELA
FROM BI_DMP2 B 
WHERE B.DMP = 0.00 AND B.ANO = @p_ano AND B.SEMESTRE = @p_semestre

UPDATE B SET B.VALOR_PARCELA_ISENCAO = 0.00
FROM BI_DMP2 B 
WHERE B.VALOR_PARCELA_ISENCAO < 0.00 AND B.ANO = @p_ano AND B.SEMESTRE = @p_semestre


UPDATE B SET B.VALOR_PARCELA_SEM_ISENCAO = B.VALOR_PARCELA
FROM BI_DMP2 B 
WHERE B.DMP_SEM_ISENCAO = 0.00 AND B.ANO = @p_ano AND B.SEMESTRE = @p_semestre

UPDATE B SET B.VALOR_PARCELA_SEM_ISENCAO = 0.00
FROM BI_DMP2 B 
WHERE B.VALOR_PARCELA_SEM_ISENCAO < 0.00 AND B.ANO = @p_ano AND B.SEMESTRE = @p_semestre


UPDATE BI_DMP2 SET DIA_CAMPANHA = 1
WHERE DIA_CAMPANHA < 1
AND ANO = @p_ano
AND SEMESTRE = @p_semestre
OR DIA_CAMPANHA IS NULL

UPDATE D SET D.RENUNCIA = ((D.VALOR_PARCELA-D.VALOR_PARCELA_ISENCAO)*D.QTD_PARCELAS_ISENCAO) + ((D.VALOR_PARCELA - D.VALOR_PARCELA_SEM_ISENCAO)*D.QTD_PARCELAS_SEM_ISENCAO)
FROM BI_DMP2 D
WHERE D.ANO = @p_ano AND D.SEMESTRE = @p_semestre


UPDATE D SET D.RENUNCIA_POTENCIAL = D.RENUNCIA + ((D.VALOR_PARCELA - D.VALOR_PARCELA_SEM_ISENCAO)*6)*(SELECT MAX(G.SERIE_IDEAL)-1 FROM LYCEUM..LY_GRADE G WHERE G.CURSO = D.CURSO AND G.CURRICULO = D.CURRICULO AND D.TURNO = G.TURNO)
FROM BI_DMP2 D
WHERE  D.ANO = @p_ano AND D.SEMESTRE = @p_semestre


UPDATE BI_DMP2 SET RENUNCIA_POTENCIAL = 0.00 WHERE RENUNCIA = 0.00 AND ANO = @p_ano AND SEMESTRE = @p_semestre

UPDATE BI_DMP2 SET DMP = DMP_SEM_ISENCAO WHERE DMP_SEM_ISENCAO > DMP AND ANO = @p_ano AND SEMESTRE = @p_semestre

UPDATE BI_DMP2 SET DMP = 0.00 WHERE DMP < 0.00 AND ANO = @p_ano AND SEMESTRE = @p_semestre

UPDATE BI_DMP2 SET DMP_SEM_ISENCAO = 0.00 WHERE DMP_SEM_ISENCAO < 0.00 AND ANO = @p_ano AND SEMESTRE = @p_semestre


-- LISTA DE BOLSAS CADASTRADAS PRO ALUNO
	UPDATE T SET T.BOLSAS = STUFF((SELECT DISTINCT ',' + B.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..LY_BOLSA B
                        WHERE 1=1
						AND B.TIPO_BOLSA NOT LIKE '%FIES%'
						AND (B.ANOFIM >= @p_ano OR B.ANOFIM IS NULL) AND (B.MESFIM >= CASE @p_semestre WHEN 1 THEN 6 ELSE 12 END OR B.MESFIM IS NULL OR (B.MESINI = B.MESFIM AND B.ANOINI = B.ANOFIM))
						AND B.DATA_CANCEL IS NULL
                        AND B.ALUNO = T.ALUNO
                        FOR XML PATH('') 
                        ), 1, 1, '' )
	FROM BI_DMP2 T
	WHERE T.ANO = @p_ano AND T.SEMESTRE = @p_semestre

--SANEAMENTO NOMES DE CURSO

UPDATE BI_DMP2 SET NOME_CURSO = 'Engenharia Elétrica - Automação' WHERE NOME_CURSO = 'Engenharia Elétrica Automação'
UPDATE BI_DMP2 SET NOME_CURSO = 'Administração FGV' WHERE NOME_CURSO = 'Administração - FGV'
UPDATE BI_DMP2 SET NOME_CURSO = 'Direito' WHERE NOME_CURSO = 'Bacharel em Direito'
UPDATE BI_DMP2 SET NOME_CURSO = 'Ciências Aeronáuticas' WHERE NOME_CURSO = 'Ciências Aeronáuticas - Piloto Comercial'
UPDATE BI_DMP2 SET NOME_CURSO = 'Ciências Contábeis' WHERE NOME_CURSO = 'Ciências Contábeis (Noturno) CESUFS'
UPDATE BI_DMP2 SET NOME_CURSO = 'Cinema e Vídeo' WHERE NOME_CURSO = 'Comunicação Social - Cinema e Vídeo'
UPDATE BI_DMP2 SET NOME_CURSO = 'Jornalismo' WHERE NOME_CURSO = 'Comunicação Social - Jornalismo' OR NOME_CURSO = 'Comunicação Social com Habilitação em Jornalismo'
UPDATE BI_DMP2 SET NOME_CURSO = 'Design de Interiores' WHERE NOME_CURSO = 'Curso Superior de Tecnologia em DESIGN DE INTERIORES'
UPDATE BI_DMP2 SET NOME_CURSO = 'Psicologia' WHERE NOME_CURSO = 'Psicologia - Formação de Psicólogo'
UPDATE BI_DMP2 SET NOME_CURSO = 'Publicidade e Propaganda' WHERE NOME_CURSO = 'Comunicação Social - Publicidade e Propaganda' OR NOME_CURSO = 'Comunicação Social com Habilitação em Publicidade e Propaganda'
UPDATE BI_DMP2 SET NOME_CURSO = 'Gestão de Recursos Humanos' WHERE NOME_CURSO = 'Tecnológico em Gestão de Recursos Humanos'
UPDATE BI_DMP2 SET NOME_CURSO = 'Gestão Financeira' WHERE NOME_CURSO = 'Tecnológico em Gestão Financeira'
UPDATE BI_DMP2 SET NOME_CURSO = 'Logística' WHERE NOME_CURSO = 'Tecnológico em Logística'
UPDATE BI_DMP2 SET NOME_CURSO = 'Radiologia' WHERE NOME_CURSO = 'Tecnológico em Radiologia' OR NOME_CURSO = 'Tecnólogo em Radiologia'
UPDATE BI_DMP2 SET NOME_CURSO = 'Estética e Cosmética' WHERE NOME_CURSO = 'Tecnólogo em Estética e Cosmética' 

END