USE LYCEUMINTEGRACAO
GO

--DELETE FROM BI_EVASAO
--DROP TABLE BI_EVASAO

IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'LYCEUMINTEGRACAO' 
                 AND  TABLE_NAME = 'BI_EVASAO'))
BEGIN

CREATE TABLE BI_EVASAO
(
	COD_UNIDADE_FISICA T_CODIGO,
	NOME_UNIDADE_FISICA T_ALFALARGE,
	TIPO_CURSO T_CODIGO,
	COD_CURSO T_CODIGO,
	NOME_CURSO T_ALFALARGE,
	CURRICULO T_CODIGO,
	TURNO T_CODIGO,
	TIPO_INGRESSO T_CODIGO,
	ANO_INGRESSO T_ANO,
	SEM_INGRESSO T_SEMESTRE,
	ALUNO T_CODIGO,
	NOME_ALUNO T_ALFALARGE,
	DT_ENCERRAMENTO T_DATA,
	ANO_ENCERRAMENTO T_ANO,
	SEM_ENCERRAMENTO T_SEMESTRE,
	MOTIVO_ENCERRAMENTO T_CODIGO	
)
END
GO
