USE FTC_DATAMART
GO
/*STATUS_FTC
SERIE_CALCULADA
SERIE_INTEGRALIZADA
CPF_ALUNO
DADOS_DE_CONTATO
*/
--EXEC BI_FINANCEIRO_JOB

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_FINANCEIRO_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_FINANCEIRO_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 
 
ALTER PROCEDURE dbo.BI_FINANCEIRO_JOB       
         
AS            
-- [INÍCIO]                    
BEGIN  

--CRIANDO TABELA PARA O BI
IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_FINANCEIRO'))   
BEGIN
	DROP TABLE BI_FINANCEIRO
END

	CREATE TABLE BI_FINANCEIRO
	(
		LANC_CRED NUMERIC,
		TIPO_COBRANCA VARCHAR(50),
		COBRANCA NUMERIC,
		COBRANCA_ESTORNADA VARCHAR(1),
		DATA_ESTORNO DATETIME,
		TIPO_PAGAMENTO VARCHAR(30),
		TIPO_CREDITO VARCHAR(20),
		COD_UNIDADE VARCHAR(20),
		TIPO_CURSO VARCHAR(30),
		COD_CURSO VARCHAR(20),
		NOME_CURSO VARCHAR(200),
		ALUNO VARCHAR(20),
		RESPONSAVEL VARCHAR(20),
		DATA_FATURAMENTO DATETIME,
		DATA_REF DATETIME,
		DATA_CONTABIL DATETIME,
		DATA_VENCIMENTO DATETIME,
		DATA_PAGAMENTO DATETIME,
		DATA_RECEBIMENTO DATETIME,
		TIPO_BOLSA VARCHAR(100),
		VALOR_BRUTO DECIMAL(10,2),
		VALOR_LIQUIDO DECIMAL(10,2),
		BOLSA DECIMAL(10,2),
		MULTA DECIMAL(10,2),
		PERDEBOLSA DECIMAL(10,2),
		JUROS DECIMAL(10,2),
		DESCONTOS DECIMAL(10,2),
		VALOR_ESTORNO DECIMAL(10,2),
		VALOR_PAGO DECIMAL(10,2),
		SALDO DECIMAL(10,2),
		PAGO VARCHAR(1),
		VENCIDA VARCHAR(1),
		PERIODO_LETIVO VARCHAR(7),
		AGING VARCHAR(30),
		TIPO_FINAN VARCHAR(30),
		BOLSISTA VARCHAR(1)
	)


	END

	INSERT INTO BI_FINANCEIRO
	SELECT	DISTINCT
		LC.LANC_CRED,
		CASE C.NUM_COBRANCA  
			WHEN 1 THEN 'MENSALIDADE'  
            WHEN 2 THEN 'SERVICO'  
            WHEN 3 THEN 'ACORDO'  
            WHEN 4 THEN 'OUTROS'  
            WHEN 5 THEN 'CHEQUE DEVOLVIDO'  
			ELSE NULL END AS TIPO_COBRANCA, 
		VW.COBRANCA,
		ISNULL(C.ESTORNO,'') AS COBRANCA_ESTORNADA,
		C.DT_ESTORNO AS DATA_ESTORNO,
		ISNULL(LC.TIPO_PAGAMENTO,'') AS TIPO_PAGAMENTO,
		ISNULL(LC.TIPO_CRED,'') AS TIPO_CREDITO,
		ISNULL(C.UNID_FISICA,'') AS COD_UNIDADE,
		CUR.TIPO AS TIPO_CURSO,
		C.CURSO AS COD_CURSO,
		CUR.NOME AS NOME_CURSO,
		VW.ALUNO, 
		VW.RESP AS RESPONSAVEL,
		C.DATA_DE_FATURAMENTO AS DATA_FATURAMENTO,
		CONVERT(DATETIME, '01-' + STR(VW.MES_REF) + '-' + STR(VW.ANO_REF), 105) AS DATA_REF,  
		--(SELECT MAX(CONVERT(DATETIME,VW.DATACONTAB,105)) FROM LYCEUM..AY_VW_FATURAMENTO AY WHERE AY.COBRANCA = VW.COBRANCA)  AS DATA_CONTABIL,
		X.DATA_CONTABIL,
		CONVERT(DATETIME,C.DATA_DE_VENCIMENTO,105) AS DATA_VENCIMENTO,
		CONVERT(DATETIME,LC.DT_CREDITO,105) AS DATA_PAGAMENTO,
		CONVERT(DATETIME,LC.DATA,105) AS DATA_RECEBIMENTO,
		STUFF((SELECT DISTINCT ',' + VW1.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..AY_VW_FATURAMENTO VW1
                        WHERE
                        VW1.COBRANCA = VW.COBRANCA AND VW1.TIPO_BOLSA IS NOT NULL
                        FOR XML PATH('') 
                        ), 1, 1, '' ) AS TIPO_BOLSA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LYCEUM..LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA AND IL.ITEM_ESTORNADO IS NULL AND IL.NUM_BOLSA IS NULL) AS VALOR_BRUTO,
		(SELECT ISNULL(SUM(VALOR),0) FROM LYCEUM..LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA AND IL.ITEM_ESTORNADO IS NULL) AS VALOR_LIQUIDO,
		(SELECT ISNULL(SUM(VALOR),0)*-1 FROM LYCEUM..LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA AND IL.ITEM_ESTORNADO IS NULL AND IL.NUM_BOLSA IS NOT NULL) AS BOLSA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LYCEUM..LY_ITEM_CRED IC1 WHERE IC1.COBRANCA = VW.COBRANCA AND IC1.TIPO_ENCARGO = 'MULTA') AS MULTA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LYCEUM..LY_ITEM_CRED IC4 WHERE IC4.COBRANCA = VW.COBRANCA AND IC4.TIPO_ENCARGO = 'PERDEBOLSA') AS PERDEBOLSA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LYCEUM..LY_ITEM_CRED IC2 WHERE IC2.COBRANCA = VW.COBRANCA AND IC2.TIPO_ENCARGO = 'JUROS') AS JUROS,
		(SELECT ISNULL(SUM(VALOR),0)*-1 FROM LYCEUM..LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = VW.COBRANCA AND IC3.TIPODESCONTO IN ('Acréscimo','Concedido','DescBanco','PagtoAntecipado')) AS DESCONTOS,
		(SELECT ISNULL(SUM(VALOR),0) FROM LYCEUM..LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA AND IL.ITEM_ESTORNADO IS NOT NULL) AS VALOR_ESTORNO,
		(SELECT ISNULL(SUM(VALOR),0) FROM LYCEUM..LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = VW.COBRANCA AND IC3.TIPODESCONTO IS NULL AND IC3.TIPO_ENCARGO IS NULL)*-1 AS VALOR_PAGO,
		C1.VALOR AS SALDO,
		'N' AS PAGO,
		'N' AS VENCIDA,
		'' AS PERIODO_LETIVO,
		'' AS AGING,
		'' AS TIPO_FINAN,
		'N' AS BOLSISTA
FROM LYCEUM..AY_VW_FATURAMENTO VW
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
JOIN LYCEUM..VW_COBRANCA C1 ON C1.COBRANCA= C.COBRANCA
JOIN LYCEUM..LY_CURSO CUR ON CUR.CURSO = VW.CURSO
LEFT JOIN (	SELECT MIN(DATACONTAB) AS DATA_CONTABIL, COBRANCA 
			FROM LYCEUM..AY_VW_FATURAMENTO
			GROUP BY COBRANCA
				) X ON X.COBRANCA = VW.COBRANCA
LEFT JOIN LYCEUM..LY_ITEM_CRED IC ON IC.COBRANCA = C.COBRANCA
LEFT JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
WHERE  1=1

-- AJUSTE UNIDADES EM BRANCO OU NULL
UPDATE B
	SET COD_UNIDADE = 'SEM-UNIDADE'
FROM BI_FINANCEIRO B
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = B.ALUNO
WHERE B.COD_UNIDADE IS NULL OR B.COD_UNIDADE = ''
--AJUSTE COBRANÇAS PAGAS

UPDATE BI_FINANCEIRO
	SET PAGO = 'S'
	WHERE DATA_PAGAMENTO IS NOT NULL AND DATA_RECEBIMENTO IS NOT NULL


--AJUSTE COBRANÇAS VENCIDAS 

UPDATE BI_FINANCEIRO
	SET VENCIDA = 'S'
	WHERE PAGO = 'N'
		AND DATA_VENCIMENTO < GETDATE()


-- DEFININDO BOLSISTAS
--UPDATE T SET T.BOLSISTA = 'S'
--FROM BI_FINANCEIRO T 
--WHERE EXISTS (SELECT TOP 1 1  FROM LYCEUM..LY_BOLSA B 
--				WHERE B.ALUNO = T.ALUNO 
--				AND B.DATA_CANCEL IS NULL 
--				AND (CONCAT(B.ANOINI,B.MESINI) >= CONCAT(YEAR(T.DATA_REF),MONTH(T.DATA_REF))
--				AND (CONCAT(B.ANOFIM,B.MESFIM) <= CONCAT(YEAR(T.DATA_REF),MONTH(T.DATA_REF)) OR B.ANOFIM IS NULL)
--)

UPDATE T SET T.BOLSISTA = 'S'
FROM BI_FINANCEIRO T 
WHERE T.BOLSA > 0

--APAGANDO SALDOS VENCIDOS *ROTINA REMOVIDA EM 02/06/2020 MEDIANTE VALIDAÇÃO DO FINANCEIRO (NELSON ALBUQUERQUE)
--DELETE FROM BI_FINANCEIRO
--	WHERE VENCIDA = 'S'
--	AND PAGO = 'N'
--	AND SALDO < 0


--INSERIR PERIODO LETIVO DA COBRANÇA
UPDATE BI
	SET BI.PERIODO_LETIVO = CONCAT(LD.ANO_REF,'/',LD.PERIODO_REF)
	FROM BI_FINANCEIRO BI
	JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = BI.COBRANCA
	JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB



--INSERIR AGING EM COBRANÇAS VENCIDAS

UPDATE BI
	SET BI.AGING = CASE
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) <= 30 THEN '01. Até 30 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN '02. de 31 a 60 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN '03. de 61 a 90 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 91 AND 180 THEN '04. de 91 a 180 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 181 AND 365 THEN '05. de 181 a 365 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) > 365 THEN '06. Acima de 365 dias'  
			ELSE NULL END  
	FROM BI_FINANCEIRO BI
	WHERE BI.VENCIDA = 'S'

--DEFININDO TIPO_FINAN
UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_50','PROUNI50') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO = 0.5000
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO)

UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
SELECT TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_100','PROUNI100') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO = 1.0000
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO)


UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA = 'PROIES100'
AND TB.GRUPO_BOLSA = 'PROIES' 
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM  LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				WHERE 1=1 
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND CONCAT(LD.ANO_REF,'/',LD.PERIODO_REF) = BI.PERIODO_LETIVO
				AND LD.ALUNO = BI.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo')
				AND LC.TIPO_PAGAMENTO = 'Especial' AND LC.TIPO_CRED = 'PROIES')
				


UPDATE BI SET BI.TIPO_FINAN = 'FIES'
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND TB.GRUPO_BOLSA = 'FIES' 
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'FIES' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO)
					


UPDATE BI SET BI.TIPO_FINAN = 'FIES+PROUNI'
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND TB.GRUPO_BOLSA = 'FIES' 
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND BI.TIPO_FINAN <> 'FIES'
AND TIPO_FINAN IS NOT NULL AND TIPO_FINAN <> ''

UPDATE BI SET BI.TIPO_FINAN = 'FIES+PROUNI' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO
AND BI.TIPO_FINAN LIKE '%PROUNI%')

UPDATE BI_FINANCEIRO SET TIPO_FINAN = 'PAGANTES'
WHERE (TIPO_FINAN IS NULL OR TIPO_FINAN = '')

--UPDATE BI_FINANCEIRO SET TIPO_FINAN = 'BOLSISTA'
--WHERE TIPO_FINAN = 'PAGANTES' AND BOLSISTA = 'S'

--SANEAMENTO DE NOMES DE CURSOS
UPDATE BI_FINANCEIRO  SET NOME_CURSO = 'Direito' WHERE NOME_CURSO = 'Bacharel em Direito'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Biomedicina' WHERE NOME_CURSO = 'Biomedicina - ITA'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Ciências Contábeis' WHERE NOME_CURSO = 'Ciências Contábeis (Noturno) CESUFS'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Ciências Econômicas' WHERE NOME_CURSO = 'Ciências Econômicas (Noturno- CESUFS)'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Administração' WHERE NOME_CURSO LIKE '%Administração%' AND TIPO_CURSO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP')
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Comunicação Social - Jornalismo' WHERE NOME_CURSO = 'Comunicação Social com Habilitação em Jornalismo'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Comunicação Social - Publicidade e Propaganda' WHERE NOME_CURSO = 'Comunicação Social com Habilitação em Publicidade e Propaganda'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Tecnológico em Segurança no Trabalho' WHERE NOME_CURSO = 'Segurança do Trabalho'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Tecnológico em Radiologia' WHERE NOME_CURSO = 'Tecnólogo em Radiologia'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Psicologia' WHERE NOME_CURSO = 'Psicologia - Formação de Psicólogo'