USE FTC_DATAMART
GO
/*STATUS_FTC
SERIE_CALCULADA
SERIE_INTEGRALIZADA
CPF_ALUNO
DADOS_DE_CONTATO
*/
--EXEC BI_FINANCEIRO_JOB

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_FINANCEIRO_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_FINANCEIRO_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 
 
ALTER PROCEDURE dbo.BI_FINANCEIRO_JOB       
         
AS            
-- [INÍCIO]                    
BEGIN  

--CRIANDO TABELA PARA O BI
IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_FINANCEIRO'))   
BEGIN
	DROP TABLE BI_FINANCEIRO
END

	CREATE TABLE BI_FINANCEIRO
	(
		LANC_CRED NUMERIC,
		TIPO_COBRANCA VARCHAR(50),
		COBRANCA NUMERIC,
		COBRANCA_ESTORNADA VARCHAR(1),
		DATA_ESTORNO DATETIME,
		TIPO_PAGAMENTO VARCHAR(30),
		TIPO_CREDITO VARCHAR(20),
		COD_UNIDADE VARCHAR(20),
		TIPO_CURSO VARCHAR(30),
		COD_CURSO VARCHAR(20),
		NOME_CURSO VARCHAR(200),
		ALUNO VARCHAR(20),
		RESPONSAVEL VARCHAR(20),
		DATA_FATURAMENTO DATETIME,
		DATA_REF DATETIME,
		DATA_CONTABIL DATETIME,
		DATA_VENCIMENTO DATETIME,
		DATA_PAGAMENTO DATETIME,
		DATA_RECEBIMENTO DATETIME,
		TIPO_BOLSA VARCHAR(100),
		VALOR_BRUTO DECIMAL(10,2),
		BOLSA DECIMAL(10,2),
		ENCARGOS DECIMAL(10,2),
		DESCONTOS DECIMAL(10,2),
		CANCELAMENTOS DECIMAL(10,2),
		ESTORNOS DECIMAL(10,2),
		VALOR_PAGO DECIMAL(10,2),
		SALDO DECIMAL(10,2),
		PAGO VARCHAR(1),
		VENCIDA VARCHAR(1),
		PERIODO_LETIVO VARCHAR(7),
		AGING VARCHAR(30),
		TIPO_FINAN VARCHAR(30),
		BOLSISTA VARCHAR(1),
		STATUS_FTC VARCHAR(30),
		SERIE_CALCULADA INT,
		SERIE_INTEGRALIZADA INT,
		CPF_ALUNO VARCHAR(11),
		E_MAIL VARCHAR(100),
		DDD VARCHAR(10),
		FONE VARCHAR(30),
		CELULAR VARCHAR(30)
		
	)


	END

	INSERT INTO BI_FINANCEIRO
	SELECT	DISTINCT
		LC.LANC_CRED,
		CASE C.NUM_COBRANCA  
			WHEN 1 THEN 'MENSALIDADE'  
            WHEN 2 THEN 'SERVICO'  
            WHEN 3 THEN 'ACORDO'  
            WHEN 4 THEN 'OUTROS'  
            WHEN 5 THEN 'CHEQUE DEVOLVIDO'  
			ELSE NULL END AS TIPO_COBRANCA, 
		VW.COBRANCA,
		ISNULL(C.ESTORNO,'') AS COBRANCA_ESTORNADA,
		C.DT_ESTORNO AS DATA_ESTORNO,
		ISNULL(LC.TIPO_PAGAMENTO,'') AS TIPO_PAGAMENTO,
		ISNULL(LC.TIPO_CRED,'') AS TIPO_CREDITO,
		ISNULL(C.UNID_FISICA,'') AS COD_UNIDADE,
		CUR.TIPO AS TIPO_CURSO,
		C.CURSO AS COD_CURSO,
		CUR.NOME AS NOME_CURSO,
		VW.ALUNO, 
		VW.RESP AS RESPONSAVEL,
		C.DATA_DE_FATURAMENTO AS DATA_FATURAMENTO,
		CONVERT(DATETIME, '01-' + STR(VW.MES_REF) + '-' + STR(VW.ANO_REF), 105) AS DATA_REF,  
		--(SELECT MAX(CONVERT(DATETIME,VW.DATACONTAB,105)) FROM LYCEUM..AY_VW_FATURAMENTO AY WHERE AY.COBRANCA = VW.COBRANCA)  AS DATA_CONTABIL,
		X.DATA_CONTABIL,
		CONVERT(DATETIME,C.DATA_DE_VENCIMENTO,105) AS DATA_VENCIMENTO,
		CONVERT(DATETIME,LC.DT_CREDITO,105) AS DATA_PAGAMENTO,
		CONVERT(DATETIME,LC.DATA,105) AS DATA_RECEBIMENTO,
		STUFF((SELECT DISTINCT ',' + VW1.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..AY_VW_FATURAMENTO VW1
                        WHERE
                        VW1.COBRANCA = VW.COBRANCA AND VW1.TIPO_BOLSA IS NOT NULL
                        FOR XML PATH('') 
                        ), 1, 1, '' ) AS TIPO_BOLSA,
		(SELECT ISNULL(SUM(RA2.VALOR),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA.CODIGO_LANC = RA2.CODIGO_LANC AND RA2.EVENTO_NUM IN (1,4,28,30,31,32)) AS VALOR_BRUTO,
		(SELECT ISNULL(SUM(RA2.VALOR_SINAL),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA.CODIGO_LANC = RA2.CODIGO_LANC AND RA2.EVENTO_NUM IN (2,1002,63,1063) ) AS BOLSA,
		(SELECT ISNULL(SUM(RA2.VALOR_SINAL),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA2.EVENTO_NUM IN (54,59,1054,1059)) AS ENCARGOS,
		(SELECT ISNULL(SUM(RA2.VALOR_SINAL),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA.CODIGO_LANC = RA2.CODIGO_LANC AND RA2.EVENTO_NUM IN (33,1033) AND MOTIVO_DESCONTO <> 'PlanoPagamento') AS DESCONTOS,
		(SELECT ISNULL(SUM(RA2.VALOR_SINAL),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA.CODIGO_LANC = RA2.CODIGO_LANC AND RA2.EVENTO_NUM IN (33,1033) AND MOTIVO_DESCONTO = 'PlanoPagamento' ) AS CANCELAMENTOS,
		(SELECT ISNULL(SUM(RA2.VALOR_SINAL),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA.CODIGO_LANC = RA2.CODIGO_LANC AND RA2.EVENTO_NUM IN (1001,1004,1028,1030,1031,1032)) AS ESTORNOS,
		(SELECT ISNULL(SUM(RA2.VALOR_SINAL),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA2.EVENTO_NUM IN (12,16,17,18,23,24,50,51,1012,1016,1017,1018,1023,1024,1050,1051)) AS VALOR_PAGO,
		(SELECT ISNULL(SUM(RA2.VALOR_SINAL),0) FROM LYCEUM..AY_RESUMO_ATO RA2 WHERE RA2.COBRANCA = C.COBRANCA AND RA2.EVENTO_NUM NOT IN (49,1049)) AS SALDO,
		'N' AS PAGO,
		'N' AS VENCIDA,
		'' AS PERIODO_LETIVO,
		'' AS AGING,
		'' AS TIPO_FINAN,
		'N' AS BOLSISTA,
		'' AS STATUS_FTC,
		0 AS SERIE_CALCULADA,
		0 AS SERIE_INTEGRALIZADA,
		P.CPF AS CPF_ALUNO,
		P.E_MAIL,
		ISNULL(P.DDD_FONE_CELULAR,P.DDD_FONE) AS DDD,
		ISNULL(P.FONE,'') AS FONE,
		ISNULL(P.CELULAR,'') AS CELULAR
FROM LYCEUM..AY_VW_FATURAMENTO VW
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
JOIN LYCEUM..VW_COBRANCA C1 ON C1.COBRANCA= C.COBRANCA
JOIN LYCEUM..LY_CURSO CUR ON CUR.CURSO = VW.CURSO
JOIN LYCEUM..AY_RESUMO_ATO RA ON RA.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN (	SELECT MIN(DATACONTAB) AS DATA_CONTABIL, COBRANCA 
			FROM LYCEUM..AY_VW_FATURAMENTO
			GROUP BY COBRANCA
				) X ON X.COBRANCA = VW.COBRANCA
LEFT JOIN LYCEUM..LY_ITEM_CRED IC ON IC.COBRANCA = C.COBRANCA
LEFT JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
WHERE  1=1
AND VW.UNIDADE_FISICA IN ('FTC-SSA','FTC-ITA')

-- AJUSTE UNIDADES EM BRANCO OU NULL
UPDATE B
	SET COD_UNIDADE = 'SEM-UNIDADE'
FROM BI_FINANCEIRO B
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = B.ALUNO
WHERE B.COD_UNIDADE IS NULL OR B.COD_UNIDADE = ''
--AJUSTE COBRANÇAS PAGAS

UPDATE BI_FINANCEIRO
	SET PAGO = 'S'
	WHERE DATA_PAGAMENTO IS NOT NULL AND DATA_RECEBIMENTO IS NOT NULL


--AJUSTE COBRANÇAS VENCIDAS 

UPDATE BI_FINANCEIRO
	SET VENCIDA = 'S'
	WHERE PAGO = 'N'
		AND DATA_VENCIMENTO < GETDATE()


-- DEFININDO BOLSISTAS
--UPDATE T SET T.BOLSISTA = 'S'
--FROM BI_FINANCEIRO T 
--WHERE EXISTS (SELECT TOP 1 1  FROM LYCEUM..LY_BOLSA B 
--				WHERE B.ALUNO = T.ALUNO 
--				AND B.DATA_CANCEL IS NULL 
--				AND (CONCAT(B.ANOINI,B.MESINI) >= CONCAT(YEAR(T.DATA_REF),MONTH(T.DATA_REF))
--				AND (CONCAT(B.ANOFIM,B.MESFIM) <= CONCAT(YEAR(T.DATA_REF),MONTH(T.DATA_REF)) OR B.ANOFIM IS NULL)
--)

UPDATE T SET T.BOLSISTA = 'S'
FROM BI_FINANCEIRO T 
WHERE T.BOLSA > 0

--APAGANDO SALDOS VENCIDOS *ROTINA REMOVIDA EM 02/06/2020 MEDIANTE VALIDAÇÃO DO FINANCEIRO (NELSON ALBUQUERQUE)
--DELETE FROM BI_FINANCEIRO
--	WHERE VENCIDA = 'S'
--	AND PAGO = 'N'
--	AND SALDO < 0


--INSERIR PERIODO LETIVO DA COBRANÇA
UPDATE BI
	SET BI.PERIODO_LETIVO = CONCAT(LD.ANO_REF,'/',LD.PERIODO_REF)
	FROM BI_FINANCEIRO BI
	JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = BI.COBRANCA
	JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB



--INSERIR AGING EM COBRANÇAS VENCIDAS

UPDATE BI
	SET BI.AGING = CASE
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) <= 30 THEN '01. Até 30 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN '02. de 31 a 60 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN '03. de 61 a 90 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 91 AND 180 THEN '04. de 91 a 180 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) BETWEEN 181 AND 365 THEN '05. de 181 a 365 dias'  
			WHEN DATEDIFF(DD, BI.DATA_VENCIMENTO, GETDATE()) > 365 THEN '06. Acima de 365 dias'  
			ELSE NULL END  
	FROM BI_FINANCEIRO BI
	WHERE BI.VENCIDA = 'S'

--DEFININDO TIPO_FINAN
UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_50','PROUNI50') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO = 0.5000
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO)

UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
SELECT TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_100','PROUNI100') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO = 1.0000
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO)


UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA = 'PROIES100'
AND TB.GRUPO_BOLSA = 'PROIES' 
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM  LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				WHERE 1=1 
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND CONCAT(LD.ANO_REF,'/',LD.PERIODO_REF) = BI.PERIODO_LETIVO
				AND LD.ALUNO = BI.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo')
				AND LC.TIPO_PAGAMENTO = 'Especial' AND LC.TIPO_CRED = 'PROIES')
				


UPDATE BI SET BI.TIPO_FINAN = 'FIES'
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND TB.GRUPO_BOLSA = 'FIES' 
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND (BI.TIPO_FINAN IS NULL OR TIPO_FINAN = '')

UPDATE BI SET BI.TIPO_FINAN = 'FIES' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO)
					


UPDATE BI SET BI.TIPO_FINAN = 'FIES+PROUNI'
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND TB.GRUPO_BOLSA = 'FIES' 
AND (B.ANOINI IS NULL OR B.ANOINI <= YEAR(BI.DATA_REF))
AND (B.MESINI IS NULL OR B.MESINI >= MONTH(BI.DATA_REF))
AND (B.ANOFIM IS NULL OR B.ANOFIM >= YEAR(BI.DATA_REF))
AND (B.MESFIM IS NULL OR B.MESFIM >= MONTH(BI.DATA_REF))
)
AND BI.TIPO_FINAN <> 'FIES'
AND TIPO_FINAN IS NOT NULL AND TIPO_FINAN <> ''

UPDATE BI SET BI.TIPO_FINAN = 'FIES+PROUNI' 
FROM BI_FINANCEIRO BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0
					AND CONCAT(PPP.ANO,'/',PPP.PERIODO) = BI.PERIODO_LETIVO
AND BI.TIPO_FINAN LIKE '%PROUNI%')

UPDATE BI_FINANCEIRO SET TIPO_FINAN = 'PAGANTES'
WHERE (TIPO_FINAN IS NULL OR TIPO_FINAN = '')

--UPDATE BI_FINANCEIRO SET TIPO_FINAN = 'BOLSISTA'
--WHERE TIPO_FINAN = 'PAGANTES' AND BOLSISTA = 'S'

--SANEAMENTO DE NOMES DE CURSOS
UPDATE BI_FINANCEIRO  SET NOME_CURSO = 'Direito' WHERE NOME_CURSO = 'Bacharel em Direito'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Biomedicina' WHERE NOME_CURSO = 'Biomedicina - ITA'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Ciências Contábeis' WHERE NOME_CURSO = 'Ciências Contábeis (Noturno) CESUFS'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Ciências Econômicas' WHERE NOME_CURSO = 'Ciências Econômicas (Noturno- CESUFS)'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Administração' WHERE NOME_CURSO LIKE '%Administração%' AND TIPO_CURSO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP')
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Comunicação Social - Jornalismo' WHERE NOME_CURSO = 'Comunicação Social com Habilitação em Jornalismo'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Comunicação Social - Publicidade e Propaganda' WHERE NOME_CURSO = 'Comunicação Social com Habilitação em Publicidade e Propaganda'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Tecnológico em Segurança no Trabalho' WHERE NOME_CURSO = 'Segurança do Trabalho'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Tecnológico em Radiologia' WHERE NOME_CURSO = 'Tecnólogo em Radiologia'
UPDATE BI_FINANCEIRO SET NOME_CURSO = 'Psicologia' WHERE NOME_CURSO = 'Psicologia - Formação de Psicólogo'

--STATUS_FTC
UPDATE BI SET BI.STATUS_FTC = X.STATUS_FTC
FROM BI_FINANCEIRO BI
JOIN BI_REMATRICULA X ON X.ALUNO = BI.ALUNO AND CONCAT(X.ANO,'/',X.SEMESTRE) = BI.PERIODO_LETIVO
WHERE BI.ALUNO = X.ALUNO


--CALCULANDO A SERIE_CALCULDADA
UPDATE T
	SET T.SERIE_CALCULADA = (SELECT COUNT(DISTINCT CONCAT(HM.ANO,HM.SEMESTRE))+1 
							FROM LYCEUM..LY_HISTMATRICULA HM 
							WHERE T.ALUNO = HM.ALUNO 
							AND CONCAT(HM.ANO,'/',HM.SEMESTRE) < T.PERIODO_LETIVO
							AND HM.SITUACAO_HIST NOT IN ('Cancelado','Dispensado'))
	FROM BI_FINANCEIRO T

--CALCULANDO A SERIE_INTEGRALIZADA
--UPDATE T
--	SET T.SERIE_INTEGRALIZADA = LYCEUMINTEGRACAO.dbo.FN_FTC_CALCULA_SERIE_CH(T.ALUNO,SUBSTRING(T.PERIODO_LETIVO,0,5),SUBSTRING(T.PERIODO_LETIVO,6,1))

--	FROM BI_FINANCEIRO T