USE FTC_DATAMART
GO

--EXEC BI_GESTAO_PESSOAS 2018,2
--DROP TABLE BI_GESTAO_PESSOAS
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_GESTAO_PESSOAS'))
   exec('CREATE PROCEDURE [dbo].[BI_GESTAO_PESSOAS] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_GESTAO_PESSOAS_JOB
(            
  @p_ano VARCHAR(4)      
, @p_mes VARCHAR(2)      

)            
AS            
-- [INÍCIO]                    
BEGIN  

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_GESTAO_PESSOAS'))   
BEGIN
	DELETE FROM BI_GESTAO_PESSOAS WHERE MES_COMPETENCIA = @p_mes AND ANO_COMPETENCIA = @p_ano 
END

ELSE
	CREATE TABLE BI_GESTAO_PESSOAS --DROP TABLE BI_GESTAO_PESSOAS
	(
		CODEMPRESA NUMERIC(5)
		,EMPRESA VARCHAR(255)
		,FILIAL VARCHAR(60)
		,CODSECAO VARCHAR(35)
		,SECAO VARCHAR(60)
		,MES_COMPETENCIA NUMERIC(5)
		,ANO_COMPETENCIA NUMERIC(5)
		,PERIODO_FOLHA NUMERIC(5)
		,MATRICULA VARCHAR(20)
		,FUNCIONARIO VARCHAR(120)
		,SEXO VARCHAR(1)
		,TIPO_RECEBIMENTO VARCHAR(10)
		,TIPO_FUNCIONARIO VARCHAR(50)
		,PCD VARCHAR(3)
		,SITUACAO_ATUAL VARCHAR(50)
		,SITUACAO_HISTORICA VARCHAR(50)
		,MOTIVO_DEMISSAO VARCHAR(50)
		,DATA_SITUACAO_HISTORICA VARCHAR(10)
		,DATA_INICIO_FERIAS VARCHAR(10)
		,DATA_FIM_FERIAS VARCHAR(10)
		,TIPO_AFASTAMENTO VARCHAR(50)
		,MOTIVO_AFASTAMENTO VARCHAR(50)
		,INICIO_AFASTAMENTO VARCHAR(10)
		,FIM_AFASTAMENTO VARCHAR(10)
		,CPF VARCHAR(11)
		,DATA_NASCIMENTO VARCHAR(10)
		,DATA_ADMISSAO VARCHAR(10)
		,DATA_DEMISSAO VARCHAR(10)
		,FUNCAO VARCHAR(100)
		,GRAU_INSTRUCAO VARCHAR(255)
		,NIVEL_SALARIAL VARCHAR(10)
		,CODHORARIO VARCHAR(10)
		,HORARIO_TRABALHO VARCHAR(100)
		,SUBGRUPO VARCHAR(30)
		,CODCUSTO VARCHAR(25)
		,CCUSTO VARCHAR(60)
		,CCUSTO_PERCENT NUMERIC(15,2)
		,CODEVENTO VARCHAR(4)
		,EVENTO VARCHAR(80)
		,TIPO_EVENTO VARCHAR(8)
		,EVENTO_REF NUMERIC(15,2)
		,VALOR_EVENTO NUMERIC
		,SALARIO_CADASTRO NUMERIC
		,SALARIO_HISTORICO NUMERIC(15,2)
		,LIQUIDO_FOLHA_EVENTO_MES NUMERIC(15,2)
		,LIQUIDO_TOTAL_MES NUMERIC

	)


-- [FIM]
END

/*
1.       Apenas no primeiro acesso, com a finalidade de acessar os dados históricos, Janeiro/2005 até Dezembro/2018;

 
	insert into BI_GESTAO_PESSOAS
      select * from openquery(DBRM,'select * from rm.ftc_folha_mensal');


2.       A partir de Janeiro/2019 realizar os passos abaixo:

     execute ('begin rm.p_ftc_folha_mensal(''6'',''2020''); end; ') at [DBRM];
	 
	 DELETE FROM BI_GESTAO_PESSOAS WHERE ANO_COMPETENCIA = 2020 AND MES_COMPETENCIA = 6
	 
	 INSERT INTO BI_GESTAO_PESSOAS
     select * from openquery(DBRM,'select * from rm.ftc_folha_mensal where ano_competencia = 2020 and mes_competencia = 6');

	 SELECT * FROM BI_GESTAO_PESSOAS WHERE ANO_COMPETENCIA = 2020 AND MES_COMPETENCIA = 6 AND FILIAL = 'IMES' AND CPF = '02151070557'
	 	
	 
	
	

	      
*/
