USE FTC_DATAMART
GO

--EXEC BI_HIST_JOB

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_HIST_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_HIST_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_HIST_JOB --DROP PROCEDURE BI_HIST_JOB

AS            

BEGIN    
	
	DELETE FROM BI_ACOMP_MATR_HIST WHERE DATA_HIST <= GETDATE() AND DATA_HIST > GETDATE()-1	
	INSERT INTO BI_ACOMP_MATR_HIST
	SELECT GETDATE() AS DATA_HIST, *
	FROM BI_ACOMP_MATR

	DELETE FROM BI_ACOMP_MATR_POS_HIST WHERE DATA_HIST <= GETDATE() AND DATA_HIST > GETDATE()-1	
	INSERT INTO BI_ACOMP_MATR_POS_HIST
	SELECT GETDATE() AS DATA_HIST, *
	FROM BI_ACOMP_MATR_POS

	DELETE FROM BI_REMATRICULA_HIST WHERE DATA_HIST <= GETDATE() AND DATA_HIST > GETDATE()-1	
	INSERT INTO BI_REMATRICULA_HIST
	SELECT GETDATE() AS DATA_HIST, *
	FROM BI_REMATRICULA

END