USE LYCEUM
GO

IF (NOT EXISTS (SELECT * 
                 FROM LYCEUMINTEGRACAO.INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = 'BI_INADIMPLENCIA'))
	BEGIN

	--DROP TABLE LYCEUMINTEGRACAO..BI_INADIMPLENCIA

	CREATE TABLE LYCEUMINTEGRACAO..BI_INADIMPLENCIA
	(
		COD_UNIDADE T_CODIGO,
		NOME_UNIDADE T_ALFALARGE,
		SITUACAO_ALUNO T_CODIGO,
		ALUNO T_CODIGO,
		RESP T_CODIGO,
		TIPO_CURSO T_CODIGO,
		COD_CURSO T_CODIGO,
		NOME_CURSO T_ALFALARGE,
		COBRANCA T_NUMERO,
		TIPO_COBRANCA VARCHAR(20),
		DATA_DE_VENCIMENTO T_DATA,
		FAIXA_VENCIMENTO_VENCIDAS VARCHAR(30),
		DIAS_ATRASO T_NUMERO,
		ANO_REF T_ANO,
		MES_REF T_MES,
		VALOR_ABERTO DECIMAL(10,2),

	)


	END

ELSE

	BEGIN 

		DELETE FROM LYCEUMINTEGRACAO..BI_INADIMPLENCIA

END

	INSERT INTO LYCEUMINTEGRACAO..BI_INADIMPLENCIA
	SELECT 	DISTINCT
		a.UNIDADE_FISICA AS COD_UNIDADE,  
		ue.NOME_COMP AS NOME_UNIDADE,
		a.SIT_ALUNO AS SITUACAO_ALUNO,  
        car.ALUNO,
		cob2.RESP,  
		cur.TIPO AS TIPO_CURSO, 
        cob.CURSO AS COD_CURSO,  
        cur.NOME AS NOME_CURSO,  
		car.COBRANCA,  
		CASE cob.NUM_COBRANCA  
			WHEN 1 THEN 'MENSALIDADE'  
            WHEN 2 THEN 'SERVICO'  
            WHEN 3 THEN 'ACORDO'  
            WHEN 4 THEN 'OUTROS'  
            WHEN 5 THEN 'CHEQUE DEVOLVIDO'  
			ELSE NULL END AS TIPO_COBRANCA,  
		cob.DATA_DE_VENCIMENTO,  
		CASE
			WHEN DATEDIFF(DD, cob.DATA_DE_VENCIMENTO, GETDATE()) <= 30 THEN '01. Até 30 dias'  
			WHEN DATEDIFF(DD, cob.DATA_DE_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN '02. de 31 a 60 dias'  
			WHEN DATEDIFF(DD, cob.DATA_DE_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN '03. de 61 a 90 dias'  
			WHEN DATEDIFF(DD, cob.DATA_DE_VENCIMENTO, GETDATE()) BETWEEN 91 AND 180 THEN '04. de 91 a 180 dias'  
			WHEN DATEDIFF(DD, cob.DATA_DE_VENCIMENTO, GETDATE()) BETWEEN 181 AND 365 THEN '05. de 181 a 365 dias'  
			WHEN DATEDIFF(DD, cob.DATA_DE_VENCIMENTO, GETDATE()) > 365 THEN '06. Acima de 365 dias'  
			ELSE NULL END AS FAIXA_VENCIMENTO_VENCIDAS,  
		DATEDIFF(DD, cob.DATA_DE_VENCIMENTO, GETDATE()) AS DIAS_ATRASO, 
		cob2.ANO AS ANO_REF,
		cob2.MES AS MES_REF, 
		cob2.VALOR AS VALOR_ABERTO  
 FROM AY_RESUMO_ATO car JOIN  
   LY_ALUNO A ON A.ALUNO = car.ALUNO JOIN
   LY_COBRANCA cob ON car.COBRANCA = cob.COBRANCA JOIN  
   VW_COBRANCA cob2 ON cob2.COBRANCA = cob.COBRANCA JOIN
   LY_UNIDADE_FISICA ue ON a.UNIDADE_FISICA = ue.UNIDADE_FIS JOIN  
   LY_CURSO cur ON cob.CURSO = cur.CURSO
   WHERE	cob2.VALOR > 0 
			AND cob2.DATA_DE_VENCIMENTO < GETDATE() 
			AND cob.ESTORNO = 'N' 
			AND cob.DT_ESTORNO IS NULL 
			AND cob.DATA_DE_FATURAMENTO IS NOT NULL
GO          

--select SUM(VALOR_ABERTO), FAIXA_VENCIMENTO_VENCIDAS 
--FROM LYCEUMINTEGRACAO..BI_INADIMPLENCIA 
--WHERE SITUACAO_ALUNO = 'Ativo'
--group by FAIXA_VENCIMENTO_VENCIDAS