USE FTC_DATAMART
GO


--DELETE FROM BI_METAS WHERE ANO = 2020 AND SEMESTRE = 1


INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Administração','N','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Ciências Contábeis','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Direito','M','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Direito','N','80','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Enfermagem','M','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Enfermagem','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Farmácia','M','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Farmácia','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Fisioterapia','M','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Fisioterapia','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Gestão de Recursos Humanos','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Gestão Financeira','N','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Jornalismo','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Logística','N','25','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Nutrição','M','31','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Nutrição','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Pedagogia','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Psicologia','M','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Psicologia','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FCS','FTC CAMPUS - COMERCIO','Publicidade e Propaganda','N','0','CALOURO','2020/1')



INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Radiologia','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Radiologia','M','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Administração','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Administração','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Ciências Contábeis','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Direito','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Direito','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Enfermagem','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Enfermagem','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Farmácia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Farmácia','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Fisioterapia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Fisioterapia','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Nutrição','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Nutrição','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Odontologia','I','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Psicologia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Psicologia','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Gestão de Recursos Humanos','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Gestão Financeira','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-LAPA','FTC CAMPUS - LAPA','Logística','N','0','CALOURO','2020/1')





INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Administração','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Arquitetura e Urbanismo','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Biomedicina','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Ciências Contábeis','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Direito','N','150','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Educação Física','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Enfermagem','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Enfermagem','N','38','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Engenharia Civil','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Farmácia','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Fisioterapia','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Fisioterapia','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Gastronomia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Gastronomia','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Gestão de Recursos Humanos','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Gestão de Recursos Humanos','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Medicina Veterinária','M','54','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Nutrição','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Odontologia','I','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Odontologia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Psicologia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Psicologia','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-FSA','FTC DE FEIRA DE SANTANA','Sistemas de Informação','N','30','CALOURO','2020/1')




INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Administração','N','80','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Biomedicina','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Biomedicina','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Direito','M','100','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Direito','N','180','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Enfermagem','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Enfermagem','N','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Engenharia Ambiental e Sanitária','N','20','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Engenharia Civil','N','90','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Tecnóloga em Estética e Cosmética ','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Tecnóloga em Estética e Cosmética ','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Farmácia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Farmácia','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Fisioterapia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Fisioterapia','N','55','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Medicina Veterinária','I','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Medicina Veterinária','M','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Medicina Veterinária','N','45','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Nutrição','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Nutrição','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Odontologia','I','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Odontologia','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Psicologia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Psicologia','N','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-ITA','FTC DE ITABUNA','Sistemas de Informação','N','45','CALOURO','2020/1')




INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Administração','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Biomedicina','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Direito','N','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Educação Física','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Enfermagem','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Engenharia Civil','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Engenharia Elétrica','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Farmácia','N','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Fisioterapia','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Gestao Pública','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Nutrição','N','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Odontologia','I','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Odontologia','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-JEQ','FTC DE JEQUIÉ','Psicologia','N','50','CALOURO','2020/1')





INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Administração','M','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Administração','N','80','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Administração FGV','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Administração FGV','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Arquitetura e Urbanismo','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Arquitetura e Urbanismo','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Biomedicina','M','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Biomedicina','N','85','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Ciências Aeronáuticas','M','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Cinema e Vídeo','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Cinema e Vídeo','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Direito','M','105','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Direito','N','125','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Educação Física','M','70','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Educação Física','N','105','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Enfermagem','M','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Enfermagem','N','80','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Engenharia Ambiental e Sanitária','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Engenharia Civil','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Engenharia Elétrica Automação','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Engenharia Mecatrônica','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Farmácia','M','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Farmácia','N','95','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Fisioterapia','M','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Fisioterapia','N','70','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Jornalismo','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Jornalismo','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Logística','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Logística','N','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Medicina Veterinária','M','70','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Nutrição','M','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Nutrição','N','75','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Odontologia','I','130','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Psicologia','M','95','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Psicologia','N','135','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Publicidade e Propaganda','M','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Publicidade e Propaganda','N','75','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Radiologia','M','67','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Radiologia','N','80','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-SSA','FTC CAMPUS - PARALELA','Sistemas de Informação','N','50','CALOURO','2020/1')



INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-MED','FTC CAMPUS - MEDICINA','Medicina','I','150','CALOURO','2020/1')



INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Administração','N','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Análise e Desenvolvimento de Sistemas','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Arquitetura e Urbanismo','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Arquitetura e Urbanismo','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Biomedicina','M','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Biomedicina','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Direito','M','100','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Direito','N','100','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Educação Física','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Educação Física','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Enfermagem','M','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Enfermagem','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Engenharia Ambiental e Sanitária','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Engenharia Civil','M','55','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Engenharia Civil','N','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Engenharia Elétrica','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Engenharia Mecatrônica','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Farmácia','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Farmácia','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Fisioterapia','M','45','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Fisioterapia','N','45','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Gastronomia','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Gastronomia','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Gestão de Recursos Humanos','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Gestão de Recursos Humanos','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Medicina Veterinária','M','65','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Nutrição','M','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Nutrição','N','35','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Odontologia','I','90','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Psicologia','M','45','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Psicologia','N','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Publicidade e Propaganda','N','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','FTC-VIC','FTC DE VITÓRIA DA CONQUISTA','Sistemas de Informação','N','30','CALOURO','2020/1')


INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Biomedicina','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Biomedicina','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Enfermagem','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Enfermagem','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Farmácia','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Farmácia','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Fisioterapia','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Fisioterapia','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Nutrição','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Nutrição','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-JUA','FTC DE JUAZEIRO','Odontologia','I','50','CALOURO','2020/1')



INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Administração FGV','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Administração FGV','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Arquitetura e Urbanismo','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Arquitetura e Urbanismo','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Direito','M','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Direito','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Engenharia Civil','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Engenharia Civil','N','60','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Engenharia Elétrica','M','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Engenharia Elétrica','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Engenharia de Produção','N','40','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Psicologia','M','30','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-PET','FTC DE PETROLINA','Psicologia','N','40','CALOURO','2020/1')


INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-SP','FTC DE SÃO PAULO','Administração','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-SP','FTC DE SÃO PAULO','Direito','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-SP','FTC DE SÃO PAULO','Engenharia Civil','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-SP','FTC DE SÃO PAULO','Engenharia de Controle e Automação','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-SP','FTC DE SÃO PAULO','Engenharia Elétrica','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-SP','FTC DE SÃO PAULO','Engenharia Eletrônica','N','0','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','OTE-SP','FTC DE SÃO PAULO','Engenharia Mecânica','N','0','CALOURO','2020/1')


INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','UNECE-EUN','UNESULBAHIA FACULDADES INTEGRADAS - EUNÁPOLIS','Administração','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','UNECE-EUN','UNESULBAHIA FACULDADES INTEGRADAS - EUNÁPOLIS','Ciências Contábeis','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','UNECE-EUN','UNESULBAHIA FACULDADES INTEGRADAS - EUNÁPOLIS','Direito','M','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','UNECE-EUN','UNESULBAHIA FACULDADES INTEGRADAS - EUNÁPOLIS','Direito','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','UNECE-EUN','UNESULBAHIA FACULDADES INTEGRADAS - EUNÁPOLIS','Enfermagem','N','50','CALOURO','2020/1')
INSERT INTO BI_METAS VALUES ('2020','1','GRADUACAO','UNECE-EUN','UNESULBAHIA FACULDADES INTEGRADAS - EUNÁPOLIS','Fisioterapia','N','50','CALOURO','2020/1')



UPDATE BI_METAS SET TIPO_CURSO = 'TECNOLOGO'
WHERE NOME_CURSO IN ('Análise e Desenvolvimento de Sistemas','Design de Interiores','Estética e Cosmética',
					'Gastronomia','Gestão de Recursos Humanos','Gestão Financeira','Gestao Pública','Radiologia')



UPDATE BI_METAS SET NOME_UNIDADE = 'FTC CAMPUS - COMERCIO' WHERE NOME_UNIDADE = 'FACULDADE DE TECNOLOGIA E CIENCIAS - COMÉRCIO'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC CAMPUS - LAPA' WHERE NOME_UNIDADE = 'FACULDADE DE TECNOLOGIA E CIENCIAS - COMÉRCIO' AND NOME_CURSO IN ('Odontologia','')
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC CAMPUS - MEDICINA' WHERE NOME_CURSO = 'Medicina'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC CAMPUS - PARALELA' WHERE NOME_UNIDADE = 'FACULDADE DE TECNOLOGIA E CIÊNCIAS - SALVADOR'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC DE FEIRA DE SANTANA' WHERE NOME_UNIDADE = 'FACULDADE DE TECNOLOGIA E CIÊNCIAS - FEIRA DE SANTANA'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC DE ITABUNA' WHERE NOME_UNIDADE = 'FACULDADE DE TECNOLOGIA E CIÊNCIAS - ITABUNA'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC DE JEQUIÉ' WHERE NOME_UNIDADE = 'FACULDADE DE TECNOLOGIA E CIÊNCIAS - JEQUIÉ'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC DE JUAZEIRO' WHERE NOME_UNIDADE = 'ORGANIZACAO TECNOLOGICA DE ENSINO - JUAZEIRO'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC DE PETROLINA' WHERE NOME_UNIDADE = 'ORGANIZACAO TECNOLOGICA DE ENSINO - PETROLINA'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC DE SÃO PAULO' WHERE NOME_UNIDADE = 'ORGANIZACAO TECNOLOGICA DE ENSINO - SAO PAULO'
UPDATE BI_METAS SET NOME_UNIDADE = 'FTC DE VITÓRIA DA CONQUISTA' WHERE NOME_UNIDADE = 'FACULDADE DE TECNOLOGIA E CIÊNCIAS - VITÓRIA DA CONQUISTA'
