USE FTC_DATAMART
GO
--EXEC BI_METAS_JOB 2020,1


IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_METAS_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_METAS_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_METAS_JOB
(            
  @p_ano VARCHAR(4)
, @p_semestre VARCHAR(2) 

)            
AS            
-- [INÍCIO]                    
BEGIN    
	
IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_METAS'))   
BEGIN
	DELETE FROM BI_METAS WHERE ANO = '2020' AND SEMESTRE = '1' AND TIPO_ALUNO = 'VETERANO'
END    

ELSE
BEGIN
	CREATE TABLE BI_METAS (

		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		TIPO_CURSO VARCHAR(30),
		COD_UNIDADE VARCHAR(20),
		NOME_UNIDADE VARCHAR(100),
		NOME_CURSO VARCHAR(100),
		TURNO VARCHAR(1),
		METAS INT,
		TIPO_ALUNO VARCHAR(20),
		PERIODO_LETIVO VARCHAR(10),
		CURSO VARCHAR(20)
	) 

	
END

	INSERT INTO BI_METAS
	SELECT	DISTINCT
			'2020' ANO,
			'1' SEMESTRE,
			TIPO_CURSO,
			UNIDADE_FISICA_ALUNO AS COD_UNIDADE,
			NOME_UNIDADE_ENSINO_ALUNO AS NOME_UNIDADE,
			NOME_CURSO,
			TURNO,
			CEILING(COUNT(ALUNO)*0.88) AS METAS,
			TIPO_ALUNO,
			CONCAT(ANO,'/',SEMESTRE) AS PERIODO_LETIVO,
			CURSO
	FROM BI_REMATRICULA
	WHERE TIPO_ALUNO = 'VETERANO'
	--AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO')
	AND ANO = @p_ano
	AND SEMESTRE = @p_semestre
	GROUP BY ANO, SEMESTRE, TIPO_CURSO, UNIDADE_FISICA_ALUNO, NOME_UNIDADE_ENSINO_ALUNO, NOME_CURSO, TURNO,TIPO_ALUNO,CURSO
	ORDER BY 4,6


	--UPDATE BI_METAS SET NOME_CURSO = 'Jornalismo' WHERE NOME_CURSO = 'Comunicação Social - Jornalismo'
	--UPDATE BI_METAS SET NOME_CURSO = 'Publicidade e Propaganda' WHERE NOME_CURSO = 'Comunicação Social - Publicidade e Propaganda'
	--UPDATE BI_METAS SET NOME_CURSO = 'Cinema e Vídeo' WHERE NOME_CURSO = 'Comunicação Social - Cinema e Vídeo'
	--UPDATE BI_METAS SET NOME_CURSO = 'Pedagogia' WHERE NOME_CURSO = 'Licenciatura em Pedagogia'
	--UPDATE BI_METAS SET NOME_CURSO = 'Gestão de Recursos Humanos' WHERE NOME_CURSO = 'Tecnológico em Gestão de Recursos Humanos'
	--UPDATE BI_METAS SET NOME_CURSO = 'Ciências Aeronáuticas' WHERE NOME_CURSO = 'Ciências Aeronáuticas - Piloto Comercial'
	--UPDATE BI_METAS SET NOME_CURSO = 'Radiologia' WHERE NOME_CURSO = 'Tecnológico em Radiologia'
	--UPDATE BI_METAS SET NOME_CURSO = 'Logística' WHERE NOME_CURSO = 'Tecnológico em Logística'
	--UPDATE BI_METAS SET NOME_CURSO = 'Engenharia Elétrica Automação' WHERE NOME_CURSO = 'Engenharia Elétrica - Automação'
	--UPDATE BI_METAS SET NOME_CURSO = 'Gestão Financeira' WHERE NOME_CURSO = 'Tecnológico em Gestão Financeira'
	--UPDATE BI_METAS SET NOME_CURSO = 'Estética e Cosmética' WHERE NOME_CURSO = 'Tecnóloga em Estética e Cosmética'
	--UPDATE BI_METAS SET NOME_CURSO = 'Engenharia Ambiental e Sanitária' WHERE NOME_CURSO = 'Engenharia Ambiental'
	--UPDATE BI_METAS SET NOME_UNIDADE = 'FTC CAMPUS - MEDICINA', COD_UNIDADE = 'FTC-MED' WHERE NOME_CURSO = 'Medicina'
	



-- [FIM]
END