USE FTC_DATAMART
GO

--EXEC BI_RITMO_MATRICULA_JOB 2020,1
--DROP TABLE BI_RITMO_MATRICULA
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_RITMO_MATRICULA_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_RITMO_MATRICULA_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_RITMO_MATRICULA_JOB
(				
  @p_ano VARCHAR(4)      
, @p_semestre VARCHAR(2)      

)            
AS            
-- [INÍCIO]                    
BEGIN  

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_RITMO_MATRICULA'))   
BEGIN
	DELETE FROM BI_RITMO_MATRICULA WHERE ANO = @p_ano AND SEMESTRE = @p_semestre
END

ELSE 

CREATE TABLE BI_RITMO_MATRICULA (
ANO VARCHAR(4),
SEMESTRE VARCHAR(2),
PERIODO_LETIVO VARCHAR(7),
UNIDADE_ENSINO_ALUNO VARCHAR(20),
NOME_CURSO VARCHAR(100),
TIPO_ALUNO VARCHAR(50),
TIPO_FINAN VARCHAR(50),
TIPO_INGRESSO VARCHAR(50),
SIT_MATRICULA_ANTERIOR VARCHAR(50),
DIA_RITMO VARCHAR(2),
MES_RITMO VARCHAR(2),
ANO_RITMO VARCHAR(4),
DATA_MATRICULA VARCHAR(10),
DIA_CAMPANHA INT,
MATRICULADOS INT
)


INSERT INTO BI_RITMO_MATRICULA
SELECT	ANO,
		SEMESTRE,
		CONCAT(ANO,'/',SEMESTRE) AS PERIODO_LETIVO, 
		UNIDADE_ENSINO_ALUNO, 
		NOME_CURSO,
		TIPO_ALUNO,
		TIPO_FINAN,
		TIPO_INGRESSO,
		SIT_MATRICULA_ANTERIOR,
		DAY(CONVERT(DATETIME,DATA_MATRICULA,103)) DIA_RITMO, 
		MONTH(CONVERT(DATETIME,DATA_MATRICULA,103)) MES_RITMO, 
		YEAR(CONVERT(DATETIME,DATA_MATRICULA,103)) ANO_RITMO, 
		CONVERT(VARCHAR(10),DATA_MATRICULA,103) DATA_MATRICULA,
		0 AS DIA_CAMPANHA,
		COUNT(ALUNO) MATRICULADOS
FROM BI_REMATRICULA
WHERE 1=1
AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO','CONCLUIDO','INCONCLUIDO')
AND PAGO = 1
AND ANO = @p_ano
AND SEMESTRE = @p_semestre
GROUP BY ANO,SEMESTRE,CONCAT(ANO,'/',SEMESTRE), UNIDADE_ENSINO_ALUNO, NOME_CURSO,TIPO_ALUNO,TIPO_FINAN,TIPO_INGRESSO,SIT_MATRICULA_ANTERIOR,DAY(CONVERT(DATETIME,DATA_MATRICULA,103)),MONTH(CONVERT(DATETIME,DATA_MATRICULA,103)),YEAR(CONVERT(DATETIME,DATA_MATRICULA,103)), CONVERT(VARCHAR(10),DATA_MATRICULA,103)
ORDER BY CONCAT(ANO,'/',SEMESTRE), UNIDADE_ENSINO_ALUNO, NOME_CURSO, YEAR(CONVERT(DATETIME,DATA_MATRICULA,103)),MONTH(CONVERT(DATETIME,DATA_MATRICULA,103)),DAY(CONVERT(DATETIME,DATA_MATRICULA,103))


UPDATE T SET T.DIA_CAMPANHA = DATEDIFF(DAY,CONVERT(DATETIME,X.DATA_PERIODO,103),CONVERT(DATETIME,T.DATA_MATRICULA,103))+1 
FROM BI_RITMO_MATRICULA T
JOIN (SELECT DISTINCT ANO, SEMESTRE, DATA_PERIODO FROM BI_REMATRICULA) X ON X.ANO = T.ANO AND X.SEMESTRE = T.SEMESTRE
AND T.ANO = @p_ano
AND T.SEMESTRE = @p_semestre

END