USE FTC_DATAMART
GO

CREATE TABLE BI_REMATRICULA_HIST
(
	[DATA_HIST] DATETIME,
	[ANO] VARCHAR(4),
	[SEMESTRE] VARCHAR(2),
	[STATUS_FTC] VARCHAR(50),
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(20),
	[NOME_UNIDADE_ENSINO_ALUNO] VARCHAR(100),
	[UNIDADE_FISICA_ALUNO] VARCHAR(30),
	[TIPO_CURSO] VARCHAR(50),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR(100),
	[CURRICULO] VARCHAR(20),
	[TURNO] VARCHAR(20),
	[SERIE] SMALLINT,
	[SERIE_CALCULADA] SMALLINT,
	[TIPO_ALUNO] VARCHAR(50),
	[TIPO_INGRESSO] VARCHAR(50),
	[ANO_INGRESSO] VARCHAR(4),
	[SEM_INGRESSO] VARCHAR(2),
	[ALUNO] VARCHAR(20),
	[CPF] VARCHAR(20),
	[NOME_ALUNO] VARCHAR(100),
	[E_MAIL] VARCHAR(100),
	[DDD] VARCHAR(10),
	[FONE] VARCHAR(30),
	[CELULAR] VARCHAR(30),
	[CEP] VARCHAR(10),
	[MUNICIPIO] VARCHAR(20),
	[SIT_MATRICULA] VARCHAR(50),
	[PAGO] SMALLINT,
	[NAO_PAGO] SMALLINT,
	[TIPO_FINAN] VARCHAR(50),
	[FINAN] VARCHAR(10),
	[DATA_PERIODO] VARCHAR(10),
	[INDICE_REPROVACAO] DECIMAL(10,2),
	[QTD_INADIMP] INT,
	[PERC_FALTAS] DECIMAL(10,2),
	[DATA_MATRICULA] VARCHAR(10),
	[ANTECIP_FINAN] VARCHAR(1),
	[DT_ANTECIP] VARCHAR(10),
	[TIPO_ANTECIP] VARCHAR(20),
	[VALOR_ATENCIP] NUMERIC(20,2),
	[PERFIL_EVASAO] VARCHAR(30),
	[ULTIMA_MATRICULA] VARCHAR(6),
	[SOLICITOU_PLANO] VARCHAR(1),
	[SOLICITOU_HIST] VARCHAR(1),
	[TIPO_TRANSF] VARCHAR(50),
	[VALOR_MENSALIDADE] DECIMAL(10,2),
	[VALOR_SEMESTRALIDADE] DECIMAL(10,2),
	[DT_ENCERRAMENTO] VARCHAR(10),
	[BOLSISTA] VARCHAR(1),
	[MEDIA_PERC_BOLSA] DECIMAL(10,2)
)


ALTER TABLE BI_REMATRICULA_HIST
	--ADD	[TIPO_FINAN_ANTERIOR] VARCHAR(50),
	--[DIA_CAMPANHA] INT 
	ADD	[DATA_ULTIMO_LOGIN_BB] VARCHAR(10),
	[SEMANA_ULTIMO_LOGIN_BB] INT