USE FTC_DATAMART
GO

--EXEC BI_REMATRICULA_JOB 2020,1
--DROP TABLE BI_REMATRICULA
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_REMATRICULA_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_REMATRICULA_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_REMATRICULA_JOB
(            
  @p_ano VARCHAR(4)      
, @p_semestre VARCHAR(2)      

)            
AS            
-- [INÍCIO]                    
BEGIN  

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_REMATRICULA'))   
BEGIN
	DELETE FROM BI_REMATRICULA WHERE ANO = @p_ano AND SEMESTRE = @p_semestre
END

ELSE


CREATE TABLE BI_REMATRICULA --DROP TABLE BI_REMATRICULA
(
	[ANO] VARCHAR(4),
	[SEMESTRE] VARCHAR(2),
	[STATUS_FTC] VARCHAR(50),
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(20),
	[NOME_UNIDADE_ENSINO_ALUNO] VARCHAR(100),
	[UNIDADE_FISICA_ALUNO] VARCHAR(30),
	[TIPO_CURSO] VARCHAR(50),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR(100),
	[CURRICULO] VARCHAR(20),
	[TURNO] VARCHAR(20),
	[SERIE] SMALLINT,
	[SERIE_CALCULADA] SMALLINT,
	[TIPO_ALUNO] VARCHAR(50),
	[TIPO_INGRESSO] VARCHAR(50),
	[ANO_INGRESSO] VARCHAR(4),
	[SEM_INGRESSO] VARCHAR(2),
	[ALUNO] VARCHAR(20),
	[CPF] VARCHAR(20),
	[NOME_ALUNO] VARCHAR(100),
	[E_MAIL] VARCHAR(100),
	[DDD] VARCHAR(10),
	[FONE] VARCHAR(30),
	[CELULAR] VARCHAR(30),
	[CEP] VARCHAR(10),
	[MUNICIPIO] VARCHAR(20),
	[SIT_MATRICULA] VARCHAR(50),
	[PAGO] SMALLINT,
	[NAO_PAGO] SMALLINT,
	[TIPO_FINAN] VARCHAR(50),
	[FINAN] VARCHAR(10),
	[DATA_PERIODO] VARCHAR(10),
	[INDICE_REPROVACAO] DECIMAL(10,2),
	[QTD_INADIMP] INT,
	[PERC_FALTAS] DECIMAL(10,2),
	[DATA_MATRICULA] VARCHAR(10),
	[ANTECIP_FINAN] VARCHAR(1),
	[DT_ANTECIP] VARCHAR(10),
	[TIPO_ANTECIP] VARCHAR(20),
	[VALOR_ATENCIP] NUMERIC(20,2),
	[PERFIL_EVASAO] VARCHAR(30),
	[ULTIMA_MATRICULA] VARCHAR(6),
	[SOLICITOU_PLANO] VARCHAR(1),
	[SOLICITOU_HIST] VARCHAR(1),
	[TIPO_TRANSF] VARCHAR(50),
	[VALOR_MENSALIDADE] DECIMAL(10,2),
	[VALOR_SEMESTRALIDADE] DECIMAL(10,2),
	[DT_ENCERRAMENTO] VARCHAR(10),
	[BOLSISTA] VARCHAR(1),
	[MEDIA_PERC_BOLSA] DECIMAL(10,2),
	[SIT_MATRICULA_ANTERIOR] VARCHAR(50),
	[PROFISSAO] VARCHAR(100),
	[CARGO] VARCHAR(100),
	[ESPECIALIDADE] VARCHAR(100),
	[EMPRESA] VARCHAR(100),
	[AREA] VARCHAR(100),
	[DEPARTAMENTO] VARCHAR(100),
	[BAIRRO_COMERCIAL] VARCHAR(50),
	[PAIS_COMERCIAL] VARCHAR(50),
	[COD_MUNICIPIO_COMERCIAL] VARCHAR(20),
	[MUNICIPIO_COMERCIAL] VARCHAR(100),
	[NECESSIDADE_ESPECIAL] VARCHAR(50),
	[COR_RACA] VARCHAR(50),
	[RENDA] DECIMAL(10,2),
	[CONTRIBUI_RENDA_FAMILIAR] VARCHAR(1),
	[RELIGIAO] VARCHAR(50),
	[FORMACAO_ANTERIOR] VARCHAR(200),
	[TIPO_FORMACAO_ANTERIOR] VARCHAR(50),
	[ORIGEM_FORMACAO_ANTERIOR] VARCHAR(50),
	[ANO_CONCL_FORMACAO_ANTERIOR] VARCHAR(4),
	[PAIS_FORMACAO_ANTERIOR] VARCHAR(50),
	[COD_MUNICIPIO_FORMACAO_ANTERIOR] VARCHAR(20),
	[MUNICIPIO_FORMACAO_ANTERIOR] VARCHAR(100),
	[UF_FORMACAO_ANTERIOR] VARCHAR(10),
	[SEXO] VARCHAR(1),
	[DATA_NASCIMENTO] VARCHAR(10),
	[ESTADO_CIVIL] VARCHAR(50),
	[NACIONALIDADE] VARCHAR(50),
	[PAIS_NASCIMENTO] VARCHAR(50),
	[COD_MUNICIPIO_RESIDENCIAL] VARCHAR(20),
	[MUNICIPIO_RESIDENCIAL] VARCHAR(100),
	[UF_RESIDENCIAL] VARCHAR(10),
	[PAIS_RESIDENCIAL] VARCHAR(50),
	[END_CORRETO] VARCHAR(1),
	[BAIRRO] VARCHAR (100),
	[DATA_INGRESSO] VARCHAR(10),
	[DATA_PAGAMENTO] VARCHAR(10),
	[TIPO_PAGAMENTO] VARCHAR(50),
	[TEM_NOTA] VARCHAR(1),
	[TIPO_FINAN_ANTERIOR] VARCHAR(50),
	[DIA_CAMPANHA] INT,
	[CONCURSO] VARCHAR(20),
	[DESC_CONCURSO] VARCHAR(100),
	[ORIGEM_MATRICULA] VARCHAR(50),
	[CONTRATO_ACEITO] VARCHAR(1),
	[BOLSAS] VARCHAR(100),
	[DATA_MATRICULA_ORC] VARCHAR(10),
	[CANDIDATO] VARCHAR(50),
	[TIPO_CREDITO] VARCHAR(50),
	[DATA_VENCIMENTO] VARCHAR(10),
	[DATA_VENCIMENTO_ORI] VARCHAR(10),
	[DATA_ULTIMO_LOGIN_BB] VARCHAR(10),
	[SEMANA_ULTIMO_LOGIN_BB] INT
	
)       



--1.0 CRIACAO DA TABELA TEMPORARIA DE ATIVOS

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.TEMP_REMATRICULA'))   
BEGIN
	DROP TABLE TEMP_REMATRICULA 
END

CREATE TABLE TEMP_REMATRICULA 
(
	[ANO] VARCHAR(4),
	[SEMESTRE] VARCHAR(2),
	[STATUS_FTC] VARCHAR(50),
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(20),
	[NOME_UNIDADE_ENSINO_ALUNO] VARCHAR(100),
	[UNIDADE_FISICA_ALUNO] VARCHAR(30),
	[TIPO_CURSO] VARCHAR(50),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR(100),
	[CURRICULO] VARCHAR(20),
	[TURNO] VARCHAR(20),
	[SERIE] SMALLINT,
	[SERIE_CALCULADA] SMALLINT,
	[TIPO_ALUNO] VARCHAR(50),
	[TIPO_INGRESSO] VARCHAR(50),
	[ANO_INGRESSO] VARCHAR(4),
	[SEM_INGRESSO] VARCHAR(2),
	[ALUNO] VARCHAR(20),
	[CPF] VARCHAR(20),
	[NOME_ALUNO] VARCHAR(100),
	[E_MAIL] VARCHAR(100),
	[DDD] VARCHAR(10),
	[FONE] VARCHAR(30),
	[CELULAR] VARCHAR(30),
	[CEP] VARCHAR(10),
	[MUNICIPIO] VARCHAR(20),
	[SIT_MATRICULA] VARCHAR(50),
	[PAGO] SMALLINT,
	[NAO_PAGO] SMALLINT,
	[TIPO_FINAN] VARCHAR(50),
	[FINAN] VARCHAR(10),
	[DATA_PERIODO] VARCHAR(10),
	[INDICE_REPROVACAO] DECIMAL(10,2),
	[QTD_INADIMP] INT,
	[PERC_FALTAS] DECIMAL(10,2),
	[DATA_MATRICULA] VARCHAR(10),
	[ANTECIP_FINAN] VARCHAR(1),
	[DT_ANTECIP] VARCHAR(10),
	[TIPO_ANTECIP] VARCHAR(20),
	[VALOR_ATENCIP] NUMERIC(10,2),
	[PERFIL_EVASAO] VARCHAR(30),
	[ULTIMA_MATRICULA] VARCHAR(6),
	[SOLICITOU_PLANO] VARCHAR(1),
	[SOLICITOU_HIST] VARCHAR(1),
	[TIPO_TRANSF] VARCHAR(50),
	[VALOR_MENSALIDADE] DECIMAL(10,2),
	[VALOR_SEMESTRALIDADE] DECIMAL(10,2),
	[DT_ENCERRAMENTO] VARCHAR(10),
	[BOLSISTA] VARCHAR(1),
	[MEDIA_PERC_BOLSA] DECIMAL(10,2),
	[SIT_MATRICULA_ANTERIOR] VARCHAR(50),
	[PROFISSAO] VARCHAR(100),
	[CARGO] VARCHAR(100),
	[ESPECIALIDADE] VARCHAR(100),
	[EMPRESA] VARCHAR(100),
	[AREA] VARCHAR(100),
	[DEPARTAMENTO] VARCHAR(100),
	[BAIRRO_COMERCIAL] VARCHAR(50),
	[PAIS_COMERCIAL] VARCHAR(50),
	[COD_MUNICIPIO_COMERCIAL] VARCHAR(20),
	[MUNICIPIO_COMERCIAL] VARCHAR(100),
	[NECESSIDADE_ESPECIAL] VARCHAR(50),
	[COR_RACA] VARCHAR(50),
	[RENDA] DECIMAL(10,2),
	[CONTRIBUI_RENDA_FAMILIAR] VARCHAR(1),
	[RELIGIAO] VARCHAR(50),
	[FORMACAO_ANTERIOR] VARCHAR(200),
	[TIPO_FORMACAO_ANTERIOR] VARCHAR(50),
	[ORIGEM_FORMACAO_ANTERIOR] VARCHAR(50),
	[ANO_CONCL_FORMACAO_ANTERIOR] VARCHAR(4),
	[PAIS_FORMACAO_ANTERIOR] VARCHAR(50),
	[COD_MUNICIPIO_FORMACAO_ANTERIOR] VARCHAR(20),
	[MUNICIPIO_FORMACAO_ANTERIOR] VARCHAR(100),
	[UF_FORMACAO_ANTERIOR] VARCHAR(10),
	[SEXO] VARCHAR(1),
	[DATA_NASCIMENTO] VARCHAR(10),
	[ESTADO_CIVIL] VARCHAR(50),
	[NACIONALIDADE] VARCHAR(50),
	[PAIS_NASCIMENTO] VARCHAR(50),
	[COD_MUNICIPIO_RESIDENCIAL] VARCHAR(20),
	[MUNICIPIO_RESIDENCIAL] VARCHAR(100),
	[UF_RESIDENCIAL] VARCHAR(10),
	[PAIS_RESIDENCIAL] VARCHAR(50),
	[END_CORRETO] VARCHAR(1),
	[BAIRRO] VARCHAR (100),
	[DATA_INGRESSO] VARCHAR(10),
	[DATA_PAGAMENTO] VARCHAR(10),
	[TIPO_PAGAMENTO] VARCHAR(50),
	[TEM_NOTA] VARCHAR(1),
	[TIPO_FINAN_ANTERIOR] VARCHAR(50),
	[DIA_CAMPANHA] INT,
	[CONCURSO] VARCHAR(20),
	[DESC_CONCURSO] VARCHAR(100),
	[ORIGEM_MATRICULA] VARCHAR(50),
	[CONTRATO_ACEITO] VARCHAR(1),
	[BOLSAS] VARCHAR(100),
	[DATA_MATRICULA_ORC] VARCHAR(10),
	[CANDIDATO] VARCHAR(50),
	[TIPO_CREDITO] VARCHAR(50),
	[DATA_VENCIMENTO] VARCHAR(10),
	[DATA_VENCIMENTO_ORI] VARCHAR(10),
	[DATA_ULTIMO_LOGIN_BB] VARCHAR(10),
	[SEMANA_ULTIMO_LOGIN_BB] INT
)       

--2.0 PRIMEIRA CARGA COM ALUNOS QUE ESTUDARAM NO PERIODO ANTERIOR AO SELECIONADO
INSERT INTO TEMP_REMATRICULA
SELECT DISTINCT
	@p_ano AS ANO,
	@p_semestre AS SEMESTRE,
	NULL AS STATUS_FTC,
	C.FACULDADE AS UNIDADE_ENSINO_ALUNO,
	UE.NOME_COMP AS NOME_UNIDADE_ENSINO_ALUNO,
	A.UNIDADE_FISICA AS UNIDADE_FISICA_ALUNO,
	C.TIPO AS TIPO_CURSO,
	C.CURSO AS CURSO,
	C.NOME AS NOME_CURSO,
	A.CURRICULO AS CURRICULO,
	A.TURNO AS TURNO,
	A.SERIE AS SERIE,
	0 AS SERIE_CALCULADA,
	'VETERANO' AS TIPO_ALUNO,
	A.TIPO_INGRESSO AS TIPO_INGRESSO,
	A.ANO_INGRESSO AS ANO_INGRESSO,
	A.SEM_INGRESSO AS SEM_INGRESSO,
	A.ALUNO AS ALUNO,
	P.CPF AS CPF,
	A.NOME_COMPL AS NOME_ALUNO,
	P.E_MAIL AS E_MAIL,
	ISNULL(P.DDD_FONE_CELULAR,P.DDD_FONE) AS DDD,
	ISNULL(P.FONE,'') AS FONE,
	ISNULL(P.CELULAR,'') AS CELULAR,
	ISNULL(P.CEP,'00000-000'),
	P.END_MUNICIPIO AS MUNICIPIO,
	'Sem-Matrícula' AS SIT_MATRICULA,
	0 AS PAGO,
	0 AS NAO_PAGO,
	NULL AS TIPO_FINAN,
	NULL AS FINAN,
	NULL AS DATA_PERIODO,
	0.00 AS INDICE_REPROVACAO,
	0 AS QTD_INADIMP,
	0.00 AS PERC_FALTAS,
	(SELECT TOP 1 CONVERT(VARCHAR(10),MIN(DT_MATRICULA),103) FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre AND SITUACAO_HIST NOT IN ('Dispensado','Inconcluido','Cancelado')) AS DATA_MATRICULA,
	'N' AS ANTECIP_FINAN,
	NULL AS DT_ANTECIP,
	NULL AS TIPO_ANTECIP,
	0.00 AS VALOR_ANTECIP,
	NULL AS PERFIL_EVASAO,
	NULL AS ULTIMA_MATRICULA,
	'N' AS SOLICITOU_PLANO,
	'N' AS SOLICITOU_HIST,
	NULL AS TIPO_TRANSF,
	0.00 AS VALOR_MENSALIDADE,
	0.00 AS VALOR_SEMESTRALIDADE,
	NULL AS DT_ENCERRAMENTO,
	'N' AS BOLSISTA,
	0.00 AS MEDIA_PERC_BOLSA,
	'Sem-Matrícula' AS SIT_MATRICULA_ANTERIOR,
	P.PROFISSAO,
	P.CARGO,
	P.ESPECIALIZACAO AS ESPECIALIDADE,
	P.NOME_EMPRESA AS EMPRESA,
	P.AREA_PROF AS AREA,
	P.DEPTO_COM AS DEPARTAMENTO,
	P.ENDCOM_BAIRRO AS BAIRRO_COMERCIAL,
	P.ENDCOM_PAIS PAIS_COMERCIAL,
	P.ENDCOM_MUNICIPIO AS COD_MUNICIPIO_COMERCIAL,
	'' AS MUNICIPIO_COMERCIAL,
	P.NECESSIDADE_ESPECIAL,
	P.COR_RACA,
	P.RENDA_MENSAL AS RENDA,
	P.CONTRIBUI_RENDA AS CONTRIBUI_RENDA_FAMILIAR,
	P.CREDO AS RELIGIAO,
	O.NOME_COMP AS FORMACAO_ANTERIOR,
	O.TIPO_INST AS TIPO_FORMACAO_ANTERIOR,
	O.TIPO_ORIGEM AS ORIGEM_FORMACAO_ANTERIOR,
	A.ANOCONCL_2G AS ANO_CONCL_FORMACAO_ANTERIOR,
	O.PAIS AS PAIS_FORMACAO_ANTERIOR,
	O.MUNICIPIO AS COD_MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS UF_FORMACAO_ANTERIOR,
	P.SEXO,
	CONVERT(VARCHAR(10),P.DT_NASC,103) AS DATA_NASCIMENTO,
	P.EST_CIVIL AS ESTADO_CIVIL,
	P.NACIONALIDADE,
	P.PAIS_NASC AS PAIS_NASCIMENTO,
	P.END_MUNICIPIO AS COD_MUNICIPIO_RESIDENCIAL,
	'' AS MUNICIPIO_RESIDENCIAL,
	'' AS UF_RESIDENCIAL,
	P.END_PAIS AS PAIS_RESIDENCIAL,
	P.END_CORRETO,
	P.BAIRRO,
	CONVERT(VARCHAR(10),A.DT_INGRESSO,103) AS DATA_INGRESSO,
	NULL AS DATA_PAGAMENTO,
	NULL AS TIPO_PAGAMENTO,
	'N' AS TEM_NOTA,
	'' AS TIPO_FINAN_ANTERIOR,
	0 AS DIA_CAMPANHA,
	CO.CONCURSO,
	CO.DESCRICAO AS DESC_CONCURSO,
	'' AS ORIGEM_MATRICULA,
	'N' AS CONTRATO_ACEITO,
	'' AS BOLSAS,
	'' AS DATA_MATRICULA_ORC,
	A.CANDIDATO,
	'' AS TIPO_CREDITO,
	'' AS DATA_VENCIMENTO,
	'' AS DATA_VENCIMENTO_ORI,
	'' AS DATA_ULTIMO_LOGIN_BB,
	0 AS SEMANA_ULTIMO_LOGIN_BB
FROM LYCEUM..LY_HISTMATRICULA HM
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN LYCEUM..LY_OUTRAS_FACULDADES O ON O.OUTRA_FACULDADE = A.OUTRA_FACULDADE
JOIN LYCEUM..LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO','GRADUACAO-EAD','GRADUACAO-SP')
JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE  AND C.FACULDADE <> '02'
LEFT JOIN LYCEUM..LY_CONCURSO CO ON CO.CONCURSO = A.CONCURSO
WHERE 1=1 AND HM.SITUACAO_HIST NOT IN ('Dispensado','Inconcluido','Cancelado')
AND (@p_ano IS NOT NULL AND HM.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END) 
AND (@p_semestre IS NOT NULL AND HM.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END)

UNION ALL

SELECT DISTINCT
	@p_ano AS ANO,
	@p_semestre AS SEMESTRE,
	NULL AS STATUS_FTC,
	C.FACULDADE AS UNIDADE_ENSINO_ALUNO,
	UE.NOME_COMP AS NOME_UNIDADE_ENSINO_ALUNO,
	A.UNIDADE_FISICA AS UNIDADE_FISICA_ALUNO,
	C.TIPO AS TIPO_CURSO,
	C.CURSO AS CURSO,
	C.NOME AS NOME_CURSO,
	A.CURRICULO AS CURRICULO,
	A.TURNO AS TURNO,
	A.SERIE AS SERIE,
	0 AS SERIE_CALCULADA,
	'VETERANO' AS TIPO_ALUNO,
	A.TIPO_INGRESSO AS TIPO_INGRESSO,
	A.ANO_INGRESSO AS ANO_INGRESSO,
	A.SEM_INGRESSO AS SEM_INGRESSO,
	A.ALUNO AS ALUNO,
	P.CPF AS CPF,
	A.NOME_COMPL AS NOME_ALUNO,
	P.E_MAIL AS E_MAIL,
	ISNULL(P.DDD_FONE_CELULAR,P.DDD_FONE) AS DDD,
	ISNULL(P.FONE,'') AS FONE,
	ISNULL(P.CELULAR,'') AS CELULAR,
	ISNULL(P.CEP,'00000-000'),
	P.END_MUNICIPIO AS MUNICIPIO,
	'Sem-Matrícula' AS SIT_MATRICULA,
	0 AS PAGO,
	0 AS NAO_PAGO,
	NULL AS TIPO_FINAN,
	NULL AS FINAN,
	NULL AS DATA_PERIODO,
	0.00 AS INDICE_REPROVACAO,
	0 AS QTD_INADIMP,
	0.00 AS PERC_FALTAS,
	(SELECT TOP 1 CONVERT(VARCHAR(10),MIN(DT_MATRICULA),103) FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre AND SITUACAO_HIST NOT IN ('Dispensado','Inconcluido','Cancelado')) AS DATA_MATRICULA,
	'N' AS ANTECIP_FINAN,
	NULL AS DT_ANTECIP,
	NULL AS TIPO_ANTECIP,
	0.00 AS VALOR_ANTECIP,
	NULL AS PERFIL_EVASAO,
	NULL AS ULTIMA_MATRICULA,
	'N' AS SOLICITOU_PLANO,
	'N' AS SOLICITOU_HIST,
	NULL AS TIPO_TRANSF,
	0.00 AS VALOR_MENSALIDADE,
	0.00 AS VALOR_SEMESTRALIDADE,
	NULL AS DT_ENCERRAMENTO,
	'N' AS BOLSISTA,
	0.00 AS MEDIA_PERC_BOLSA,
	'Sem-Matrícula' AS SIT_MATRICULA_ANTERIOR,
	P.PROFISSAO,
	P.CARGO,
	P.ESPECIALIZACAO AS ESPECIALIDADE,
	P.NOME_EMPRESA AS EMPRESA,
	P.AREA_PROF AS AREA,
	P.DEPTO_COM AS DEPARTAMENTO,
	P.ENDCOM_BAIRRO AS BAIRRO_COMERCIAL,
	P.ENDCOM_PAIS PAIS_COMERCIAL,
	P.ENDCOM_MUNICIPIO AS COD_MUNICIPIO_COMERCIAL,
	'' AS MUNICIPIO_COMERCIAL,
	P.NECESSIDADE_ESPECIAL,
	P.COR_RACA,
	P.RENDA_MENSAL AS RENDA,
	P.CONTRIBUI_RENDA AS CONTRIBUI_RENDA_FAMILIAR,
	P.CREDO AS RELIGIAO,
	O.NOME_COMP AS FORMACAO_ANTERIOR,
	O.TIPO_INST AS TIPO_FORMACAO_ANTERIOR,
	O.TIPO_ORIGEM AS ORIGEM_FORMACAO_ANTERIOR,
	A.ANOCONCL_2G AS ANO_CONCL_FORMACAO_ANTERIOR,
	O.PAIS AS PAIS_FORMACAO_ANTERIOR,
	O.MUNICIPIO AS COD_MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS UF_FORMACAO_ANTERIOR,
	P.SEXO,
	CONVERT(VARCHAR(10),P.DT_NASC,103) AS DATA_NASCIMENTO,
	P.EST_CIVIL AS ESTADO_CIVIL,
	P.NACIONALIDADE,
	P.PAIS_NASC AS PAIS_NASCIMENTO,
	P.END_MUNICIPIO AS COD_MUNICIPIO_RESIDENCIAL,
	'' AS MUNICIPIO_RESIDENCIAL,
	'' AS UF_RESIDENCIAL,
	P.END_PAIS AS PAIS_RESIDENCIAL,
	P.END_CORRETO,
	P.BAIRRO,
	CONVERT(VARCHAR(10),A.DT_INGRESSO,103) AS DATA_INGRESSO,
	NULL AS DATA_PAGAMENTO,
	NULL AS TIPO_PAGAMENTO,
	'N' AS TEM_NOTA,
	'' AS TIPO_FINAN_ANTERIOR,
	0 AS DIA_CAMPANHA,
	CO.CONCURSO,
	CO.DESCRICAO AS DESC_CONCURSO,
	'' AS ORIGEM_MATRICULA,
	'N' AS CONTRATO_ACEITO,
	'' AS BOLSAS,
	'' AS DATA_MATRICULA_ORC,
	A.CANDIDATO,
	'' AS TIPO_CREDITO,
	'' AS DATA_VENCIMENTO,
	'' AS DATA_VENCIMENTO_ORI,
	'' AS DATA_ULTIMO_LOGIN_BB,
	0 AS SEMANA_ULTIMO_LOGIN_BB
FROM LYCEUM..LY_HISTMATRICULA HM
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN LYCEUM..LY_OUTRAS_FACULDADES O ON O.OUTRA_FACULDADE = A.OUTRA_FACULDADE
JOIN LYCEUM..LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO','GRADUACAO-EAD','GRADUACAO-SP')
JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE  AND C.FACULDADE <> '02'
LEFT JOIN LYCEUM..LY_CONCURSO CO ON CO.CONCURSO = A.CONCURSO
WHERE 1=1 AND HM.SITUACAO_HIST NOT IN ('Dispensado','Inconcluido','Cancelado')
AND (@p_ano IS NOT NULL AND HM.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END) 
AND (@p_semestre IS NOT NULL AND HM.SEMESTRE = CASE @p_semestre WHEN '1' THEN '4' WHEN '2' THEN '3' ELSE @p_semestre END)

--2.2 APAGANDO ALUNOS DE REINGRESSO QUE ENTRARÃO COMO CALOUROS
DELETE FROM TEMP_REMATRICULA WHERE ANO_INGRESSO = @p_ano AND SEM_INGRESSO = @p_semestre

--3.0 INSERINDO ALUNOS CALOUROS NO PERIODO ATUAL
INSERT INTO TEMP_REMATRICULA
SELECT DISTINCT
	A.ANO_INGRESSO AS ANO,
	A.SEM_INGRESSO AS SEMESTRE,
	NULL AS STATUS_FTC,
	C.FACULDADE AS UNIDADE_ENSINO_ALUNO,
	UE.NOME_COMP AS NOME_UNIDADE_ENSINO_ALUNO,
	A.UNIDADE_FISICA AS UNIDADE_FISICA_ALUNO,
	C.TIPO AS TIPO_CURSO,
	C.CURSO AS CURSO,
	C.NOME AS NOME_CURSO,
	A.CURRICULO AS CURRICULO,
	A.TURNO AS TURNO,
	A.SERIE AS SERIE,
	0 AS SERIE_CALCULADA,
	'CALOURO' AS TIPO_ALUNO,
	A.TIPO_INGRESSO AS TIPO_INGRESSO,
	A.ANO_INGRESSO AS ANO_INGRESSO,
	A.SEM_INGRESSO AS SEM_INGRESSO,
	A.ALUNO AS ALUNO,
	P.CPF AS CPF,
	A.NOME_COMPL AS NOME_ALUNO,
	P.E_MAIL AS E_MAIL,
	ISNULL(P.DDD_FONE_CELULAR,P.DDD_FONE) AS DDD,
	ISNULL(P.FONE,'') AS FONE,
	ISNULL(P.CELULAR,'') AS CELULAR,
	ISNULL(P.CEP,'00000-000'),
	P.END_MUNICIPIO AS MUNICIPIO,
	'Sem-Matrícula' AS SIT_MATRICULA,
	0 AS PAGO,
	0 AS NAO_PAGO,
	NULL AS TIPO_FINAN,
	NULL AS FINAN,
	NULL AS DATA_PERIODO,
	0.00 AS INDICE_REPROVACAO,
	0 AS QTD_INADIMP,
	0.00 AS PERC_FALTAS,
	NULL AS DATA_MATRICULA,
	'N' AS ANTECIP_FINAN,
	NULL AS DT_ANTECIP,
	NULL AS TIPO_ANTECIP,
	0.00 AS VALOR_ANTECIP,
	NULL AS PERFIL_EVASAO,
	NULL AS ULTIMA_MATRICULA,
	'N' AS SOLICITOU_PLANO,
	'N' AS SOLICITOU_DISC,
	NULL AS TIPO_TRANSF,
	0.00 AS VALOR_MENSALIDADE,
	0.00 AS VALOR_SEMESTRALIDADE,
	NULL AS DT_ENCERRAMENTO,
	'N' AS BOLSISTA,
	0.00 AS MEDIA_PERC_BOLSA,
	'Sem-Matrícula' AS SIT_MATRICULA_ANTERIOR,
	P.PROFISSAO,
	P.CARGO,
	P.ESPECIALIZACAO AS ESPECIALIDADE,
	P.NOME_EMPRESA AS EMPRESA,
	P.AREA_PROF AS AREA,
	P.DEPTO_COM AS DEPARTAMENTO,
	P.ENDCOM_BAIRRO AS BAIRRO_COMERCIAL,
	P.ENDCOM_PAIS PAIS_COMERCIAL,
	P.ENDCOM_MUNICIPIO AS COD_MUNICIPIO_COMERCIAL,
	'' AS MUNICIPIO_COMERCIAL,
	P.NECESSIDADE_ESPECIAL,
	P.COR_RACA,
	P.RENDA_MENSAL AS RENDA,
	P.CONTRIBUI_RENDA AS CONTRIBUI_RENDA_FAMILIAR,
	P.CREDO AS RELIGIAO,
	O.NOME_COMP AS FORMACAO_ANTERIOR,
	O.TIPO_INST AS TIPO_FORMACAO_ANTERIOR,
	O.TIPO_ORIGEM AS ORIGEM_FORMACAO_ANTERIOR,
	A.ANOCONCL_2G AS ANO_CONCL_FORMACAO_ANTERIOR,
	O.PAIS AS PAIS_FORMACAO_ANTERIOR,
	O.MUNICIPIO AS COD_MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS UF_FORMACAO_ANTERIOR,
	P.SEXO,
	CONVERT(VARCHAR(10),P.DT_NASC,103) AS DATA_NASCIMENTO,
	P.EST_CIVIL AS ESTADO_CIVIL,
	P.NACIONALIDADE,
	P.PAIS_NASC AS PAIS_NASCIMENTO,
	P.END_MUNICIPIO AS COD_MUNICIPIO_RESIDENCIAL,
	'' AS MUNICIPIO_RESIDENCIAL,
	'' AS UF_RESIDENCIAL,
	P.END_PAIS AS PAIS_RESIDENCIAL,
	P.END_CORRETO,
	P.BAIRRO,
	CONVERT(VARCHAR(10),A.DT_INGRESSO,103) AS DATA_INGRESSO,
	NULL AS DATA_PAGAMENTO,
	NULL AS TIPO_PAGAMENTO,
	'N' AS TEM_NOTA,
	'' AS TIPO_FINAN_ANTERIOR,
	0 AS DIA_CAMPANHA,
	CO.CONCURSO,
	CO.DESCRICAO AS DESC_CONCURSO,
	'' AS ORIGEM_MATRICULA,
	'N' AS CONTRATO_ACEITO,
	'' AS BOLSAS,
	'' AS DATA_MATRICULA_ORC,
	A.CANDIDATO,
	'' AS TIPO_CREDITO,
	'' AS DATA_VENCIMENTO,
	'' AS DATA_VENCIMENTO_ORI,
	'' AS DATA_ULTIMO_LOGIN_BB,
	0 AS SEMANA_ULTIMO_LOGIN_BB
FROM LYCEUM..LY_ALUNO A
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN LYCEUM..LY_OUTRAS_FACULDADES O ON O.OUTRA_FACULDADE = A.OUTRA_FACULDADE
JOIN LYCEUM..LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO','GRADUACAO-EAD','GRADUACAO-SP')
JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE  AND C.FACULDADE <> '02'
LEFT JOIN LYCEUM..LY_CONCURSO CO ON CO.CONCURSO = A.CONCURSO
WHERE 1=1 
AND (@p_ano IS NOT NULL AND A.ANO_INGRESSO = @p_ano) 
AND (@p_semestre IS NOT NULL AND A.SEM_INGRESSO = @p_semestre)
AND NOT EXISTS (SELECT TOP 1 1 FROM TEMP_REMATRICULA BI2 WHERE BI2.ALUNO = A.ALUNO)

--3.0.1 LOGO APOS ESSA INSERÇÃO, TODOS OS CALOUROS DO TIPO_INGRESSO REINGRESSO SERÃO MODIFICADOS PARA TIPO_ALUNO REINGRESSO

UPDATE TEMP_REMATRICULA SET TIPO_ALUNO = 'REINGRESSO' 
WHERE TIPO_INGRESSO = 'Reingresso'
AND (@p_ano IS NOT NULL AND ANO_INGRESSO = @p_ano) 
AND (@p_semestre IS NOT NULL AND SEM_INGRESSO = @p_semestre)



--3.1 INSERINDO ALUNOS VETERANOS QUE ESTUDARAM NO PERIODO PORÉM NÃO TIVERAM REGISTRO NO PERIODO ANTERIOR (REINGRESSO)
INSERT INTO TEMP_REMATRICULA
SELECT DISTINCT
	@p_ano AS ANO,
	@p_semestre AS SEMESTRE,
	NULL AS STATUS_FTC,
	C.FACULDADE AS UNIDADE_ENSINO_ALUNO,
	UE.NOME_COMP AS NOME_UNIDADE_ENSINO_ALUNO,
	A.UNIDADE_FISICA AS UNIDADE_FISICA_ALUNO,
	C.TIPO AS TIPO_CURSO,
	C.CURSO AS CURSO,
	C.NOME AS NOME_CURSO,
	A.CURRICULO AS CURRICULO,
	A.TURNO AS TURNO,
	A.SERIE AS SERIE,
	0 AS SERIE_CALCULADA,
	'REINGRESSO' AS TIPO_ALUNO,
	'Reingresso' AS TIPO_INGRESSO,
	A.ANO_INGRESSO AS ANO_INGRESSO,
	A.SEM_INGRESSO AS SEM_INGRESSO,
	A.ALUNO AS ALUNO,
	P.CPF AS CPF,
	A.NOME_COMPL AS NOME_ALUNO,
	P.E_MAIL AS E_MAIL,
	ISNULL(P.DDD_FONE_CELULAR,P.DDD_FONE) AS DDD,
	ISNULL(P.FONE,'') AS FONE,
	ISNULL(P.CELULAR,'') AS CELULAR,
	ISNULL(P.CEP,'00000-000'),
	P.END_MUNICIPIO AS MUNICIPIO,
	'Sem-Matrícula' AS SIT_MATRICULA,
	0 AS PAGO,
	0 AS NAO_PAGO,
	NULL AS TIPO_FINAN,
	NULL AS FINAN,
	NULL AS DATA_PERIODO,
	0.00 AS INDICE_REPROVACAO,
	0 AS QTD_INADIMP,
	0.00 AS PERC_FALTAS,
	(SELECT TOP 1 CONVERT(VARCHAR(10),MIN(DT_MATRICULA),103) FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre AND SITUACAO_HIST NOT IN ('Dispensado','Inconcluido','Cancelado')) AS DATA_MATRICULA,
	'N' AS ANTECIP_FINAN,
	NULL AS DT_ANTECIP,
	NULL AS TIPO_ANTECIP,
	0.00 AS VALOR_ANTECIP,
	NULL AS PERFIL_EVASAO,
	NULL AS ULTIMA_MATRICULA,
	'N' AS SOLICITOU_PLANO,
	'N' AS SOLICITOU_DISC,
	NULL AS TIPO_TRANSF,
	0.00 AS VALOR_MENSALIDADE,
	0.00 AS VALOR_SEMESTRALIDADE,
	NULL AS DT_ENCERRAMENTO,
	'N' AS BOLSISTA,
	0.00 AS MEDIA_PERC_BOLSA,
	'Sem-Matrícula' AS SIT_MATRICULA_ANTERIOR,
	P.PROFISSAO,
	P.CARGO,
	P.ESPECIALIZACAO AS ESPECIALIDADE,
	P.NOME_EMPRESA AS EMPRESA,
	P.AREA_PROF AS AREA,
	P.DEPTO_COM AS DEPARTAMENTO,
	P.ENDCOM_BAIRRO AS BAIRRO_COMERCIAL,
	P.ENDCOM_PAIS PAIS_COMERCIAL,
	P.ENDCOM_MUNICIPIO AS COD_MUNICIPIO_COMERCIAL,
	'' AS MUNICIPIO_COMERCIAL,
	P.NECESSIDADE_ESPECIAL,
	P.COR_RACA,
	P.RENDA_MENSAL AS RENDA,
	P.CONTRIBUI_RENDA AS CONTRIBUI_RENDA_FAMILIAR,
	P.CREDO AS RELIGIAO,
	O.NOME_COMP AS FORMACAO_ANTERIOR,
	O.TIPO_INST AS TIPO_FORMACAO_ANTERIOR,
	O.TIPO_ORIGEM AS ORIGEM_FORMACAO_ANTERIOR,
	A.ANOCONCL_2G AS ANO_CONCL_FORMACAO_ANTERIOR,
	O.PAIS AS PAIS_FORMACAO_ANTERIOR,
	O.MUNICIPIO AS COD_MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS UF_FORMACAO_ANTERIOR,
	P.SEXO,
	CONVERT(VARCHAR(10),P.DT_NASC,103) AS DATA_NASCIMENTO,
	P.EST_CIVIL AS ESTADO_CIVIL,
	P.NACIONALIDADE,
	P.PAIS_NASC AS PAIS_NASCIMENTO,
	P.END_MUNICIPIO AS COD_MUNICIPIO_RESIDENCIAL,
	'' AS MUNICIPIO_RESIDENCIAL,
	'' AS UF_RESIDENCIAL,
	P.END_PAIS AS PAIS_RESIDENCIAL,
	P.END_CORRETO,
	P.BAIRRO,
	CONVERT(VARCHAR(10),A.DT_INGRESSO,103) AS DATA_INGRESSO,
	NULL AS DATA_PAGAMENTO,
	NULL AS TIPO_PAGAMENTO,
	'N' AS TEM_NOTA,
	'' AS TIPO_FINAN_ANTERIOR,
	0 AS DIA_CAMPANHA,
	CO.CONCURSO,
	CO.DESCRICAO AS DESC_CONCURSO,
	'' AS ORIGEM_MATRICULA,
	'N' AS CONTRATO_ACEITO,
	'' AS BOLSAS,
	'' AS DATA_MATRICULA_ORC,
	A.CANDIDATO,
	'' AS TIPO_CREDITO,
	'' AS DATA_VENCIMENTO,
	'' AS DATA_VENCIMENTO_ORI,
	'' AS DATA_ULTIMO_LOGIN_BB,
	0 AS SEMANA_ULTIMO_LOGIN_BB
FROM LYCEUM..LY_HISTMATRICULA HM
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN LYCEUM..LY_OUTRAS_FACULDADES O ON O.OUTRA_FACULDADE = A.OUTRA_FACULDADE
JOIN LYCEUM..LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO','GRADUACAO-EAD','GRADUACAO-SP')
JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE AND C.FACULDADE <> '02'
LEFT JOIN LYCEUM..LY_CONCURSO CO ON CO.CONCURSO = A.CONCURSO
WHERE 1=1
AND (@p_ano = HM.ANO)
AND (@p_semestre = HM.SEMESTRE)
AND NOT EXISTS (SELECT TOP 1 1 FROM TEMP_REMATRICULA T WHERE T.ALUNO = HM.ALUNO AND T.ANO = HM.ANO AND HM.SEMESTRE = T.SEMESTRE)
AND HM.SITUACAO_HIST NOT IN ('Cancelado','Dispensado')
AND NOT EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI WHERE BI.ALUNO = HM.ALUNO AND BI.STATUS_FTC IN ('TRANCADO','INCONCLUIDO','CONCLUIDO','MATRICULADO PAGO','PRE-MATRICULADO PAGO')
									AND BI.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
									AND BI.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE @p_semestre END)


--3.2 INSERIR ALUNOS VETERANOS QUE NÃO ESTUDARAM NO PERIODO ANTERIOR, PORÉM TÊM MATRÍCULA NO PERIODO ATUAL.
INSERT INTO TEMP_REMATRICULA
SELECT DISTINCT
	@p_ano AS ANO,
	@p_semestre AS SEMESTRE,
	NULL AS STATUS_FTC,
	C.FACULDADE AS UNIDADE_ENSINO_ALUNO,
	UE.NOME_COMP AS NOME_UNIDADE_ENSINO_ALUNO,
	A.UNIDADE_FISICA AS UNIDADE_FISICA_ALUNO,
	C.TIPO AS TIPO_CURSO,
	C.CURSO AS CURSO,
	C.NOME AS NOME_CURSO,
	A.CURRICULO AS CURRICULO,
	A.TURNO AS TURNO,
	A.SERIE AS SERIE,
	0 AS SERIE_CALCULADA,
	'REINGRESSO' AS TIPO_ALUNO,
	'Reingresso' AS TIPO_INGRESSO,
	A.ANO_INGRESSO AS ANO_INGRESSO,
	A.SEM_INGRESSO AS SEM_INGRESSO,
	A.ALUNO AS ALUNO,
	P.CPF AS CPF,
	A.NOME_COMPL AS NOME_ALUNO,
	P.E_MAIL AS E_MAIL,
	ISNULL(P.DDD_FONE_CELULAR,P.DDD_FONE) AS DDD,
	ISNULL(P.FONE,'') AS FONE,
	ISNULL(P.CELULAR,'') AS CELULAR,
	ISNULL(P.CEP,'00000-000'),
	P.END_MUNICIPIO AS MUNICIPIO,
	'Sem-Matrícula' AS SIT_MATRICULA,
	0 AS PAGO,
	0 AS NAO_PAGO,
	NULL AS TIPO_FINAN,
	NULL AS FINAN,
	NULL AS DATA_PERIODO,
	0.00 AS INDICE_REPROVACAO,
	0 AS QTD_INADIMP,
	0.00 AS PERC_FALTAS,
	(SELECT TOP 1 CONVERT(VARCHAR(10),MIN(DT_INSERCAO),103) FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre) AS DATA_MATRICULA,
	'N' AS ANTECIP_FINAN,
	NULL AS DT_ANTECIP,
	NULL AS TIPO_ANTECIP,
	0.00 AS VALOR_ANTECIP,
	NULL AS PERFIL_EVASAO,
	NULL AS ULTIMA_MATRICULA,
	'N' AS SOLICITOU_PLANO,
	'N' AS SOLICITOU_DISC,
	NULL AS TIPO_TRANSF,
	0.00 AS VALOR_MENSALIDADE,
	0.00 AS VALOR_SEMESTRALIDADE,
	NULL AS DT_ENCERRAMENTO,
	'N' AS BOLSISTA,
	0.00 AS MEDIA_PERC_BOLSA,
	'Sem-Matrícula' AS SIT_MATRICULA_ANTERIOR,
	P.PROFISSAO,
	P.CARGO,
	P.ESPECIALIZACAO AS ESPECIALIDADE,
	P.NOME_EMPRESA AS EMPRESA,
	P.AREA_PROF AS AREA,
	P.DEPTO_COM AS DEPARTAMENTO,
	P.ENDCOM_BAIRRO AS BAIRRO_COMERCIAL,
	P.ENDCOM_PAIS PAIS_COMERCIAL,
	P.ENDCOM_MUNICIPIO AS COD_MUNICIPIO_COMERCIAL,
	'' AS MUNICIPIO_COMERCIAL,
	P.NECESSIDADE_ESPECIAL,
	P.COR_RACA,
	P.RENDA_MENSAL AS RENDA,
	P.CONTRIBUI_RENDA AS CONTRIBUI_RENDA_FAMILIAR,
	P.CREDO AS RELIGIAO,
	O.NOME_COMP AS FORMACAO_ANTERIOR,
	O.TIPO_INST AS TIPO_FORMACAO_ANTERIOR,
	O.TIPO_ORIGEM AS ORIGEM_FORMACAO_ANTERIOR,
	A.ANOCONCL_2G AS ANO_CONCL_FORMACAO_ANTERIOR,
	O.PAIS AS PAIS_FORMACAO_ANTERIOR,
	O.MUNICIPIO AS COD_MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS MUNICIPIO_FORMACAO_ANTERIOR,
	'' AS UF_FORMACAO_ANTERIOR,
	P.SEXO,
	CONVERT(VARCHAR(10),P.DT_NASC,103) AS DATA_NASCIMENTO,
	P.EST_CIVIL AS ESTADO_CIVIL,
	P.NACIONALIDADE,
	P.PAIS_NASC AS PAIS_NASCIMENTO,
	P.END_MUNICIPIO AS COD_MUNICIPIO_RESIDENCIAL,
	'' AS MUNICIPIO_RESIDENCIAL,
	'' AS UF_RESIDENCIAL,
	P.END_PAIS AS PAIS_RESIDENCIAL,
	P.END_CORRETO,
	P.BAIRRO,
	CONVERT(VARCHAR(10),A.DT_INGRESSO,103) AS DATA_INGRESSO,
	NULL AS DATA_PAGAMENTO,
	NULL AS TIPO_PAGAMENTO,
	'N' AS TEM_NOTA,
	'' AS TIPO_FINAN_ANTERIOR,
	0 AS DIA_CAMPANHA,
	CO.CONCURSO,
	CO.DESCRICAO AS DESC_CONCURSO,
	'' AS ORIGEM_MATRICULA,
	'N' AS CONTRATO_ACEITO,
	'' AS BOLSAS,
	'' AS DATA_MATRICULA_ORC,
	A.CANDIDATO,
	'' AS TIPO_CREDITO,
	'' AS DATA_VENCIMENTO,
	'' AS DATA_VENCIMENTO_ORI,
	'' AS DATA_ULTIMO_LOGIN_BB,
	0 AS SEMANA_ULTIMO_LOGIN_BB
FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA HM
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN LYCEUM..LY_OUTRAS_FACULDADES O ON O.OUTRA_FACULDADE = A.OUTRA_FACULDADE
JOIN LYCEUM..LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO','GRADUACAO-EAD','GRADUACAO-SP')
JOIN LYCEUM..LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE AND C.FACULDADE <> '02'
LEFT JOIN LYCEUM..LY_CONCURSO CO ON CO.CONCURSO = A.CONCURSO
WHERE 1=1
AND HM.ANO = @p_ano AND HM.SEMESTRE = @p_semestre
AND HM.SIT_MATRICULA NOT IN ('Cancelado','Dispensado')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI WHERE CONCAT(@p_ano,@p_semestre) > CONCAT(BI.ANO,BI.SEMESTRE))
AND NOT EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI WHERE BI.ALUNO = HM.ALUNO AND BI.STATUS_FTC IN ('TRANCADO','INCONCLUIDO','CONCLUIDO','MATRICULADO PAGO','PRE-MATRICULADO PAGO')
									AND BI.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
									AND BI.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE @p_semestre END)
AND NOT EXISTS (SELECT TOP 1 1 FROM TEMP_REMATRICULA BI2 WHERE BI2.ALUNO = HM.ALUNO)

-- UPDATE NOME MUNICIPIO / UF / BAIRRO

UPDATE T SET T.MUNICIPIO_COMERCIAL = HD.NOME
FROM TEMP_REMATRICULA  T
JOIN LYCEUM..HD_MUNICIPIO HD ON HD.MUNICIPIO = T.COD_MUNICIPIO_COMERCIAL

UPDATE T SET T.MUNICIPIO_RESIDENCIAL = HD.NOME
FROM TEMP_REMATRICULA  T
JOIN LYCEUM..HD_MUNICIPIO HD ON HD.MUNICIPIO = T.COD_MUNICIPIO_RESIDENCIAL

UPDATE T SET T.UF_RESIDENCIAL = HD.UF
FROM TEMP_REMATRICULA  T
JOIN LYCEUM..HD_MUNICIPIO HD ON HD.MUNICIPIO = T.COD_MUNICIPIO_RESIDENCIAL

UPDATE T SET T.MUNICIPIO_FORMACAO_ANTERIOR = HD.NOME
FROM TEMP_REMATRICULA  T
JOIN LYCEUM..HD_MUNICIPIO HD ON HD.MUNICIPIO = T.COD_MUNICIPIO_FORMACAO_ANTERIOR

UPDATE T SET T.UF_FORMACAO_ANTERIOR = HD.UF
FROM TEMP_REMATRICULA  T
JOIN LYCEUM..HD_MUNICIPIO HD ON HD.MUNICIPIO = T.COD_MUNICIPIO_FORMACAO_ANTERIOR

UPDATE T SET T.BAIRRO = B.BAIRRO
FROM TEMP_REMATRICULA T
JOIN BASE_CEP B ON B.CEP = T.CEP

--UPDATE DATA PERIODO

UPDATE TEMP_REMATRICULA
	SET DATA_PERIODO = CONCAT('01/',CASE SEMESTRE WHEN 1 THEN '01/' WHEN 3 THEN '05/' WHEN 4 THEN '10/' ELSE '07/' END,ANO)

--UPDATE MAX ULTIMA_MATRICULA
UPDATE T
	SET T.ULTIMA_MATRICULA = (SELECT MAX(CONCAT(BI.ANO,'/',BI.SEMESTRE)) FROM BI_REMATRICULA BI WHERE BI.ALUNO = T.ALUNO AND BI.STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO','CONCLUIDO') )
FROM TEMP_REMATRICULA T

-- UPDATE DATA DE MATRICULA PARA O ORÇAMENTO

	UPDATE T SET T.DATA_MATRICULA_ORC = CONVERT(VARCHAR(10),T.DATA_MATRICULA,103)
	FROM TEMP_REMATRICULA T

	--UPDATE T SET T.DATA_MATRICULA_ORC = CASE WHEN @p_semestre = '1'	
	--									THEN CONVERT(VARCHAR(10),'20/04/'+@p_ano,103) 
	--									ELSE CONVERT(VARCHAR(10),'30/09/'+@p_ano,103) END
	--FROM TEMP_REMATRICULA T
	--WHERE CONVERT(VARCHAR(10),T.DATA_MATRICULA,103) > CASE WHEN @p_semestre = '1' THEN CONVERT(VARCHAR(10),'20/04/'+@p_ano,103) ELSE CONVERT(VARCHAR(10),'30/09/'+@p_ano,103) END

	
	--UPDATE T SET T.DATA_MATRICULA_ORC = CASE WHEN @p_semestre = '1' 
	--									THEN CONVERT(VARCHAR(10),'01/01/'+@p_ano,103) 
	--									ELSE CONVERT(VARCHAR(10),'01/06/'+@p_ano,103) END
	--FROM TEMP_REMATRICULA T
	--WHERE CONVERT(VARCHAR(10),T.DATA_MATRICULA,103) < CASE WHEN @p_semestre = '1' THEN CONVERT(VARCHAR(10),'01/01/'+@p_ano,103) ELSE CONVERT(VARCHAR(10),'01/06/'+@p_ano,103) END

--UPDATE SIT_MATRICULA_ANTERIOR
UPDATE T
	SET T.SIT_MATRICULA_ANTERIOR = ISNULL((SELECT TOP 1 SIT_MATRICULA 
									FROM BI_REMATRICULA BI 
									WHERE BI.ALUNO = T.ALUNO 
									AND BI.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
									AND BI.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE @p_semestre END),'Sem-Matrícula')
FROM TEMP_REMATRICULA T


--UPDATE TIPO_FINAN_ANTERIOR
UPDATE T
	SET T.TIPO_FINAN_ANTERIOR = ISNULL((SELECT TOP 1 TIPO_FINAN 
									FROM BI_REMATRICULA BI 
									WHERE BI.ALUNO = T.ALUNO 
									AND BI.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
									AND BI.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE @p_semestre END),'ERRO')
FROM TEMP_REMATRICULA T

--UPDATE LISTA DE BOLSAS
	UPDATE T
		SET T.BOLSAS = STUFF((SELECT DISTINCT ',' + B.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..LY_BOLSA B
                        WHERE 1=1
						AND (B.ANOFIM >= @p_ano OR B.ANOFIM IS NULL) AND (B.MESFIM >= CASE @p_semestre WHEN 1 THEN 6 ELSE 12 END OR B.MESFIM IS NULL OR (B.MESINI = B.MESFIM AND B.ANOINI = B.ANOFIM))
						AND B.DATA_CANCEL IS NULL
                        AND B.ALUNO = T.ALUNO
                        FOR XML PATH('') 
                        ), 1, 1, '' )
	FROM TEMP_REMATRICULA T



--4.0 VERIFICANDO MATRICULA ATUAL E DATA DE MATRÍCULA


--IF CONCAT(@p_ano,@p_semestre) < CONCAT(YEAR(GETDATE()),CASE WHEN MONTH(GETDATE()) < 7 THEN 1 ELSE 2 END) 
IF CONCAT(@p_ano,@p_semestre) < '20201'
	BEGIN
		UPDATE T SET T.SIT_MATRICULA = CASE HM.SITUACAO_HIST WHEN 'Aprovado' THEN 'MATRICULADO' WHEN 'Rep Nota' THEN 'MATRICULADO' WHEN 'Rep Freq' THEN 'MATRICULADO' ELSE HM.SITUACAO_HIST END
		FROM TEMP_REMATRICULA T
		JOIN LYCEUM..LY_HISTMATRICULA HM ON HM.ALUNO = T.ALUNO
		WHERE 1=1
		AND HM.ANO = @p_ano
		AND HM.SEMESTRE = @p_semestre
		AND HM.SITUACAO_HIST NOT IN ('Dispensado','Cancelado','Inconcluido')
		AND T.SIT_MATRICULA = 'Sem-Matrícula'

		UPDATE T SET T.SIT_MATRICULA = CASE VW.SIT_MATRICULA WHEN 'Pre-Matriculado' THEN 'PRE-MATRICULADO' WHEN 'Aprovado' THEN 'MATRICULADO' WHEN 'Rep Nota' THEN 'MATRICULADO' WHEN 'Rep Freq' THEN 'MATRICULADO' ELSE VW.SIT_MATRICULA END
		FROM TEMP_REMATRICULA T
		JOIN LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = T.ALUNO
		WHERE 1=1
		AND VW.ANO = @p_ano
		AND VW.SEMESTRE = @p_semestre
		AND VW.SIT_MATRICULA NOT IN ('Cancelado','Dispensado')
		AND T.SIT_MATRICULA = 'Sem-Matrícula'

		UPDATE T SET T.DATA_MATRICULA = (SELECT CONVERT(VARCHAR(10),MIN(VW.DT_INSERCAO),103)
		FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW 
		WHERE VW.ALUNO = T.ALUNO
		AND VW.ANO = @p_ano
		AND VW.SEMESTRE = @p_semestre
		AND VW.SIT_MATRICULA NOT IN ('Cancelado','Dispensado'))
		FROM TEMP_REMATRICULA T
		WHERE T.DATA_MATRICULA IS NULL
	

		UPDATE T SET T.DATA_MATRICULA = (SELECT CONVERT(VARCHAR(10),MIN(VW.DT_MATRICULA),103)
		FROM LYCEUM..LY_HISTMATRICULA VW 
		WHERE VW.ALUNO = T.ALUNO
		AND VW.ANO = @p_ano
		AND VW.SEMESTRE = @p_semestre
		AND VW.SITUACAO_HIST NOT IN ('Cancelado','Dispensado'))
		FROM TEMP_REMATRICULA T
		WHERE T.DATA_MATRICULA IS NULL


		UPDATE T SET T.DATA_MATRICULA = T.DATA_PERIODO
		FROM TEMP_REMATRICULA T
		WHERE T.DATA_MATRICULA IS NULL

	END
ELSE
	BEGIN
		UPDATE T SET T.SIT_MATRICULA = CASE VW.SIT_MATRICULA WHEN 'Pre-Matriculado' THEN 'PRE-MATRICULADO' WHEN 'Aprovado' THEN 'MATRICULADO' WHEN 'Rep Nota' THEN 'MATRICULADO' WHEN 'Rep Freq' THEN 'MATRICULADO' ELSE VW.SIT_MATRICULA END
		FROM TEMP_REMATRICULA T
		JOIN LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = T.ALUNO
		WHERE 1=1
		AND VW.ANO = @p_ano
		AND VW.SEMESTRE = @p_semestre
		AND VW.SIT_MATRICULA NOT IN ('Cancelado','Dispensado')
		AND T.SIT_MATRICULA = 'Sem-Matrícula'

		UPDATE T SET T.DATA_MATRICULA = (SELECT CONVERT(VARCHAR(10),MIN(VW.DT_INSERCAO),103)
		FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW 
		WHERE VW.ALUNO = T.ALUNO
		AND VW.ANO = @p_ano
		AND VW.SEMESTRE = @p_semestre
		AND VW.SIT_MATRICULA NOT IN ('Cancelado','Dispensado'))
		FROM TEMP_REMATRICULA T
		WHERE T.DATA_MATRICULA IS NULL
	

		UPDATE T SET T.DATA_MATRICULA = (SELECT CONVERT(VARCHAR(10),MIN(VW.DT_MATRICULA),103)
		FROM LYCEUM..LY_HISTMATRICULA VW 
		WHERE VW.ALUNO = T.ALUNO
		AND VW.ANO = @p_ano
		AND VW.SEMESTRE = @p_semestre
		AND VW.SITUACAO_HIST NOT IN ('Cancelado','Dispensado'))
		FROM TEMP_REMATRICULA T
		WHERE T.DATA_MATRICULA IS NULL

		UPDATE T SET T.DATA_MATRICULA = T.DATA_PERIODO
		FROM TEMP_REMATRICULA T
		WHERE T.DATA_MATRICULA IS NULL

		UPDATE T SET T.ORIGEM_MATRICULA = (SELECT TOP 1 CASE WHEN PM2.OBS IS NULL OR RTRIM(LTRIM(PM2.OBS)) = '' THEN 'Secretaria' ELSE 'Aluno Online' END 
											FROM LYCEUM..LY_PRE_MATRICULA PM2 WHERE PM2.ALUNO = T.ALUNO)
		FROM TEMP_REMATRICULA T

	END

--UPDATE DIA_CAMPANHA

		UPDATE T SET T.DIA_CAMPANHA = DATEDIFF(DAY,CONVERT(DATETIME,T.DATA_PERIODO,103),CONVERT(DATETIME,T.DATA_MATRICULA,103))+1 
		FROM TEMP_REMATRICULA T

--CONTRATO ACEITO
		
		UPDATE T SET T.CONTRATO_ACEITO = 'S'
		FROM TEMP_REMATRICULA T
		WHERE EXISTS (SELECT TOP 1 1
						FROM LYCEUM..LY_CONTRATO_ALUNO CA WHERE CA.ALUNO = T.ALUNO AND CA.ANO = T.ANO AND CA.PERIODO = T.SEMESTRE
						AND CA.CONTRATO_ACEITO = 'S'
						AND NOT EXISTS (SELECT TOP 1 1 
										FROM LYCEUM..LY_CONTRATO_REMOVIDO CR
										WHERE CR.CHAVE = CA.ID_CONTRATO_ALUNO)
						)


--3.0.2 ALUNOS CONCLUINTES

CREATE TABLE TEMP_CONCLUINTES
(
	CURSO VARCHAR(20),
	TURNO VARCHAR(1),
	CURRICULO VARCHAR(30),
	TIPO_CURSO VARCHAR(50),
	QTD_SEMESTRES INT,
	CALCULA_CONCL VARCHAR(1)

)

INSERT INTO TEMP_CONCLUINTES
SELECT DISTINCT CURSO, TURNO, CURRICULO, TIPO_CURSO, 0 AS QTD_SEMESTRES, 'N' AS CALCULA_CONCL
FROM TEMP_REMATRICULA

UPDATE C SET C.QTD_SEMESTRES = (SELECT MAX(SERIE_IDEAL) 
								FROM LYCEUM..LY_GRADE G 
								WHERE G.CURSO = C.CURSO 
								AND G.CURRICULO = C.CURRICULO
								AND G.TURNO = C.TURNO
								)
FROM TEMP_CONCLUINTES C

UPDATE TEMP_CONCLUINTES SET CALCULA_CONCL = 'S'
WHERE QTD_SEMESTRES > (CASE WHEN TIPO_CURSO = 'GRADUACAO' THEN 5 WHEN TIPO_CURSO = 'TECNOLOGO' THEN 3 ELSE 8 END)


UPDATE T SET T.TIPO_ALUNO = T.TIPO_ALUNO+'-CONCLUINTE'
FROM TEMP_REMATRICULA T
JOIN TEMP_CONCLUINTES C ON C.CURRICULO = T.CURRICULO AND C.CURSO = T.CURSO AND C.TURNO = T.TURNO
WHERE LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(T.ALUNO,'S') <= 1
AND C.CALCULA_CONCL = 'S'
AND EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_GRADE G
			JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA=G.DISCIPLINA   
             OR G.FORMULA_EQUIV LIKE '%'+D.DISCIPLINA+'%'
			WHERE D.NOME LIKE '%Ativi%Comple%'
			AND G.CURSO = T.CURSO AND G.TURNO = T.TURNO AND G.CURRICULO = T.CURRICULO)
AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_HISTMATRICULA HM
			JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
			WHERE D.NOME LIKE '%Ativi%Comple%' AND HM.SITUACAO_HIST IN ('Aprovado','Dispensado')
			AND HM.ALUNO = T.ALUNO)

DROP TABLE TEMP_CONCLUINTES

	

--4.1 REMOVER ALUNOS CALOUROS QUE NAO TIVERAM MATRICULA E NAO CANCELARAM/EVADIRAM/CONCLUIRAM (REINGRESSO)
--DELETE FROM TEMP_REMATRICULA
--WHERE ANO_INGRESSO =  @p_ano 
--AND SEM_INGRESSO = @p_semestre
--AND SIT_MATRICULA = 'Sem-Matrícula'


--5.0 CLASSIFICANDO ALUNOS (IN)CONCLUINTES, CANCELADOS E EVADIDOS, CHECANDO TAMBEM SE HOUVE ENCERRAMENTO NO PERIODO ANTERIOR

--SÓ VERIFICA SE ESTÁ CONCLUÍDO DE ACORDO COM A FUNÇÃO DE DISCIPLINAS PENDENTES SE FOR NO PERÍODO ATUAL
--IF CONCAT(@p_ano,@p_semestre) = CONCAT(YEAR(GETDATE()),CASE WHEN MONTH(GETDATE()) < 7 THEN 1 ELSE 2 END)
IF CONCAT(@p_ano,@p_semestre) = '20201'     
BEGIN
--INCONCLUIDOS
UPDATE T SET STATUS_FTC = 'INCONCLUIDO'
FROM TEMP_REMATRICULA T
WHERE LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(T.ALUNO,'N') = 1
AND EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_GRADE G
			JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA=G.DISCIPLINA   
             OR G.FORMULA_EQUIV LIKE '%'+D.DISCIPLINA+'%'
			WHERE D.NOME LIKE '%Ativi%Comple%'
			AND G.CURSO = T.CURSO AND G.TURNO = T.TURNO AND G.CURRICULO = T.CURRICULO)
AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_HISTMATRICULA HM
			JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
			WHERE D.NOME LIKE '%Ativi%Comple%' AND HM.SITUACAO_HIST IN ('Aprovado','Dispensado')
			AND HM.ALUNO = T.ALUNO)
AND T.ANO = @p_ano AND T.SEMESTRE = @p_semestre

--CONCLUIDOS
UPDATE T SET STATUS_FTC = 'CONCLUIDO'
FROM TEMP_REMATRICULA T
WHERE LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(T.ALUNO,'N') = 0
AND T.ANO = @p_ano
AND T.SEMESTRE = @p_semestre
AND EXISTS (SELECT TOP 1 1 
			FROM LYCEUM..LY_HISTMATRICULA 
			WHERE ALUNO = T.ALUNO 
			AND ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
			AND SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END)
AND NOT EXISTS (SELECT TOP 1 1
				FROM LYCEUM..LY_H_CURSOS_CONCL
				WHERE ALUNO = T.ALUNO
				AND CONCAT(ANO_ENCERRAMENTO,SEM_ENCERRAMENTO) <= CONCAT(T.ANO,T.SEMESTRE)
				AND MOTIVO <> 'CONCLUSAO'
				AND DT_REABERTURA IS NULL)
AND EXISTS (SELECT TOP 1 1 
			FROM LYCEUM..LY_GRADE G
			WHERE G.CURSO = T.CURSO
			AND G.CURRICULO = T.CURRICULO
			AND G.TURNO = T.TURNO
			)


--ATUALIZA O STATUS DO PERIODO ANTERIOR DESSES ALUNOS POIS ELES JÁ CONCLUIRAM TODAS AS DISCIPLINAS
UPDATE T SET STATUS_FTC = 'INCONCLUIDO'
FROM BI_REMATRICULA T
JOIN TEMP_REMATRICULA T1 ON T1.ALUNO = T.ALUNO
WHERE T1.STATUS_FTC = 'INCONCLUIDO'
AND T.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
AND T.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END

UPDATE T SET STATUS_FTC = 'CONCLUIDO'
FROM BI_REMATRICULA T
JOIN TEMP_REMATRICULA T1 ON T1.ALUNO = T.ALUNO
WHERE T1.STATUS_FTC = 'CONCLUIDO'
AND T.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
AND T.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END


--DEPOIS REMOVE DA TEMP REMATRICULA TODO O REGISTRO DO PERIODO ATUAL
DELETE FROM TEMP_REMATRICULA WHERE STATUS_FTC = 'INCONCLUIDO'
DELETE FROM TEMP_REMATRICULA WHERE STATUS_FTC = 'CONCLUIDO'

END


--CONCLUIDOS NORMAIS
UPDATE T SET STATUS_FTC = 'CONCLUIDO', DT_ENCERRAMENTO = CONVERT(VARCHAR(10),H.DT_ENCERRAMENTO,103)
FROM TEMP_REMATRICULA T 
JOIN LYCEUM..LY_H_CURSOS_CONCL H ON H.ALUNO = T.ALUNO
WHERE H.MOTIVO = 'Conclusao' AND CONCAT(H.ANO_ENCERRAMENTO,H.SEM_ENCERRAMENTO) <= CONCAT(@p_ano,@p_semestre)
AND H.DT_REABERTURA IS NULL

--JUBILAMENTO
UPDATE T SET STATUS_FTC = 'JUBILADO', DT_ENCERRAMENTO = CONVERT(VARCHAR(10),H.DT_ENCERRAMENTO,103)
FROM TEMP_REMATRICULA T 
JOIN LYCEUM..LY_H_CURSOS_CONCL H ON H.ALUNO = T.ALUNO
WHERE H.MOTIVO = 'Jubilamento' AND H.ANO_ENCERRAMENTO = @p_ano AND H.SEM_ENCERRAMENTO = @p_semestre
AND H.DT_REABERTURA IS NULL

--TRANSFERENCIA
UPDATE T SET STATUS_FTC = 'TRANSFERIDO', T.DT_ENCERRAMENTO = CONVERT(VARCHAR(10),H.DT_ENCERRAMENTO,103)
FROM TEMP_REMATRICULA T 
JOIN LYCEUM..LY_H_CURSOS_CONCL H ON H.ALUNO = T.ALUNO
WHERE H.MOTIVO IN ('TRANSFERENCIA') 
AND (
		(H.ANO_ENCERRAMENTO = @p_ano 
		AND H.SEM_ENCERRAMENTO = @p_semestre) 
	OR 
		(H.ANO_ENCERRAMENTO = CASE @p_semestre WHEN '1' THEN @p_ano WHEN '2' THEN @p_ano+1 WHEN '11' THEN @p_ano WHEN '22' THEN @p_ano+1 ELSE @p_ano END 
		AND H.SEM_ENCERRAMENTO = CASE @p_semestre WHEN '1' THEN '2' WHEN '11' THEN '2' ELSE '1' END)
	)
AND H.DT_REABERTURA IS NULL 
AND SIT_MATRICULA <> 'MATRICULADO'


--EVASAO
UPDATE T SET STATUS_FTC = 'EVADIDO', T.DT_ENCERRAMENTO = CONVERT(VARCHAR(10),H.DT_ENCERRAMENTO,103)
FROM TEMP_REMATRICULA T 
JOIN LYCEUM..LY_H_CURSOS_CONCL H ON H.ALUNO = T.ALUNO
WHERE H.MOTIVO IN ('Abandono','Evasao') AND H.ANO_ENCERRAMENTO = @p_ano AND H.SEM_ENCERRAMENTO = @p_semestre
AND H.DT_REABERTURA IS NULL --AND SIT_MATRICULA <> 'MATRICULADO'

--CANCELAMENTO
UPDATE T SET STATUS_FTC = 'CANCELADO', T.DT_ENCERRAMENTO = CONVERT(VARCHAR(10),H.DT_ENCERRAMENTO,103)
FROM TEMP_REMATRICULA T 
JOIN LYCEUM..LY_H_CURSOS_CONCL H ON H.ALUNO = T.ALUNO
WHERE H.MOTIVO IN ('Cancelamento') AND (H.ANO_ENCERRAMENTO = @p_ano AND H.SEM_ENCERRAMENTO = @p_semestre)
AND H.DT_REABERTURA IS NULL --AND SIT_MATRICULA <> 'MATRICULADO'


--TRANCAMENTO
UPDATE T SET STATUS_FTC = 'TRANCADO', T.DT_ENCERRAMENTO = T.DATA_MATRICULA
FROM TEMP_REMATRICULA T
WHERE 1=1
AND T.SIT_MATRICULA = 'Trancado'

UPDATE T SET STATUS_FTC = 'TRANCADO', T.DT_ENCERRAMENTO = CONVERT(VARCHAR(10),A.DT_TRANC,103)
FROM TEMP_REMATRICULA T
JOIN LYCEUM..LY_TRANCAMENTO A ON A.ALUNO = T.ALUNO AND A.ANO_TRANC = @p_ano AND A.SEM_TRANC = @p_semestre
WHERE 1=1
AND SIT_MATRICULA <> 'MATRICULADO'


--6.0 VERIFICANDO PAGAMENTOS
UPDATE T SET T.PAGO = 1
FROM TEMP_REMATRICULA T
WHERE EXISTS (SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = T.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo')
UNION

--BOLSA 100% NO SEMESTRE
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
					
UNION
--BOLSA 100% ABERTA		
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL
UNION
--BOLSA 100% FECHADA NO SEMESTRE		
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM = @p_ano) 
					AND (B.MESFIM = CASE WHEN @p_semestre = 1 THEN 6 ELSE 12 END)
		
UNION
--BOLSA CREDEDUC
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE (B.TIPO_BOLSA = 'CREDEDUC' OR B.TIPO_BOLSA LIKE '%QUERO%' OR B.TIPO_BOLSA LIKE '%EDUCA%')
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
UNION
--BOLSA FIES TEMP *SOLICITADO POR ANDRÉ BRITTO / ANA PAULA GOMES em 25/03/2019*
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)


UNION
--ALUNO CONTRATO FIES
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = T.ALUNO
UNION
--COBRANÇA DE MENSALIDADE SEM SALDO A PAGAR
	SELECT TOP 1 'S' FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS','SM','MS_EB')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = T.ALUNO
					AND VW.ANO = @p_ano
					AND VW.ESTORNO = 'N'
					AND (IL.DESCRICAO LIKE '%Acerto%' OR IL.DESCRICAO LIKE '%Restitu%')
					AND VW.VALOR <= 0 --SE O ALUNO DEVE MENOS ATÉ 50 REAIS NÃO É CONSIDERADO INADIMPLENTE
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11','3') THEN 1 WHEN @p_semestre IN ('2','22','4') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11','3') THEN 6 WHEN @p_semestre IN ('2','22','4') THEN 12 ELSE 12 END
UNION
-- BOLSA PROUNI 
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B
					JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
					WHERE TB.GRUPO_BOLSA =  'PROUNI'
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
	
UNION
-- RESPONSAVEL PROUNI
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = T.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre
UNION
-- RESPONSAVEL FIES 100%
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = T.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre
	)


UPDATE TEMP_REMATRICULA SET NAO_PAGO = 1 WHERE PAGO = 0

--6.0.1 TIPO DE PAGAMENTO
--PAGAMENTO EFETIVO
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'PAGAMENTO' AS TIPO FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = T.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo'))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT  CONVERT(VARCHAR(10),MIN(IC.DATA),103) FROM  LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = T.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo'))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'PAGAMENTO'

--BOLSA 100% NO SEMESTRE
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'BOLSA100' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT CONVERT(VARCHAR(10),MIN(B.DATA_BOLSA),103) FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'BOLSA100NOPERIODO'


--BOLSA 100% ABERTA						
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'BOLSA100ABERTA' AS TIPO FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT CONVERT(VARCHAR(10),MIN(B.DATA_BOLSA),103) FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'BOLSA100ABERTA'
		
--BOLSA CREDEDUC
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'BOLSACREDEDUC' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA = 'CREDEDUC' 
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT CONVERT(VARCHAR(10),MIN(B.DATA_BOLSA),103) AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA = 'CREDEDUC' 
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'BOLSACREDEDUC'


--ALUNO CONTRATO FIES
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'CONTRATOFIES' AS TIPO FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = T.ALUNO)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT CONVERT(VARCHAR(10),MIN(B.DATA_BOLSA),103) FROM LYCEUM..LY_BOLSA B
					JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
					WHERE TB.GRUPO_BOLSA = 'FIES'
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'CONTRATOFIES'

--COBRANÇA DE MENSALIDADE SEM SALDO A PAGAR
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'ACERTORESTITUICAO' FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS','SM')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = T.ALUNO
					AND VW.ANO = @p_ano
					AND VW.ESTORNO = 'N'
					AND (IL.DESCRICAO LIKE '%Acerto%' OR IL.DESCRICAO LIKE '%Restitu%')
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11','3') THEN 1 WHEN @p_semestre IN ('2','22','4') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11') THEN 6 WHEN @p_semestre IN ('2','22') THEN 12 ELSE 12 END 		
					AND VW.VALOR <= 0
					)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT CONVERT(VARCHAR(10),MIN(IL.DATA),103) FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS','SM')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = T.ALUNO
					AND VW.ANO = @p_ano
					AND VW.ESTORNO = 'N'
					AND (IL.DESCRICAO LIKE '%Acerto%' OR IL.DESCRICAO LIKE '%Restitu%')
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11','3') THEN 1 WHEN @p_semestre IN ('2','22','4') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11') THEN 6 WHEN @p_semestre IN ('2','22') THEN 12 ELSE 12 END 		
					AND VW.VALOR <= 50)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'ACERTORESTITUICAO'


--BOLSA FIES TEMP *SOLICITADO POR ANDRÉ BRITTO / ANA PAULA GOMES em 25/03/2019*
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'BOLSAFIESTEMP' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT CONVERT(VARCHAR(10),MIN(B.DATA_BOLSA),103) FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL))
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'BOLSAFIESTEMP'

--BOLSA PROUNI
UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'BOLSAPROUNI' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = T.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL

UPDATE T SET T.DATA_PAGAMENTO = (SELECT CONVERT(VARCHAR(10),MIN(PPP.DT_ULT_ALT),103) FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = T.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO = 'BOLSAPROUNI'

UPDATE TEMP_REMATRICULA SET TIPO_PAGAMENTO = ''

--6.1 DEFININDO FINAN

UPDATE T SET FINAN = 'PAGO'
FROM TEMP_REMATRICULA T
WHERE T.PAGO = 1

UPDATE T SET FINAN = 'NÃO-PAGO'
FROM TEMP_REMATRICULA T
WHERE T.PAGO = 0

--6.1.1 DEFININDO BOLSISTAS
UPDATE T SET T.BOLSISTA = 'S'
FROM TEMP_REMATRICULA T 
WHERE EXISTS (SELECT TOP 1 1  FROM LYCEUM..LY_BOLSA B 
				WHERE B.ALUNO = T.ALUNO 
				AND B.DATA_CANCEL IS NULL 
				AND (CONCAT(B.ANOFIM,B.MESFIM) <= (CASE @p_semestre WHEN 1 THEN CONCAT(@p_ano,'6') WHEN 3 THEN CONCAT(@p_ano,'7') ELSE CONCAT(@p_ano,'12') END) OR B.ANOFIM IS NULL)
)

--6.2 ATENCIPACAO FINANCEIRA
UPDATE T SET T.ANTECIP_FINAN = 'S', T.TIPO_ANTECIP = X.TIPO_PAGAMENTO, T.DT_ANTECIP = CONVERT(VARCHAR(10),X.DATA,103), T.VALOR_ATENCIP = X.VALOR
FROM TEMP_REMATRICULA T
JOIN (SELECT DISTINCT A.ALUNO,LD.ANO_REF, LD.PERIODO_REF, LC.TIPO_PAGAMENTO, LC.DATA, (SELECT SUM(VALOR)*-1 FROM LYCEUM..LY_ITEM_CRED IC 
			JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
			WHERE C.ALUNO = A.ALUNO 
			AND CONVERT(VARCHAR(10),IC.DATA,103) = CONVERT(VARCHAR(10),LP.DATA,103)
			AND IC.TIPO_ENCARGO IS NULL
			AND IC.TIPODESCONTO IS NULL
			AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC2 WHERE IC2.LANC_CRED = IC.LANC_CRED AND IC2.ITEM_ESTORNADO IS NOT NULL)
			) AS VALOR
		FROM LYCEUM..LY_ITEM_CRED LP
		JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = LP .LANC_CRED
		JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
		JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
		JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
		JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
		WHERE C.NUM_COBRANCA = 1 AND C.ESTORNO = 'N' AND C.DT_ESTORNO IS NULL
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_CRED IC WHERE IC.LANC_CRED = LP.LANC_CRED AND IC.ITEM_ESTORNADO IS NOT NULL)) X ON X.ALUNO = T.ALUNO AND X.ANO_REF = T.ANO AND T.SEMESTRE = X.PERIODO_REF
WHERE X.DATA < T.DATA_PERIODO AND T.TIPO_ALUNO  IN ('VETERANO','VETERANO-CONCLUINTE')


--TIPO_PAGAMENTO,TIPO_CREDITO, DATA_VENCIMENTO, DATA_VENCIMENTO_ORI

UPDATE T SET T.TIPO_PAGAMENTO = (
				SELECT TOP 1 LC.TIPO_PAGAMENTO
				FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA 
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IC.COBRANCA AND VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL AND IC.ITEM_ESTORNADO IS NULL
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = ''

UPDATE T SET T.TIPO_PAGAMENTO = (
				SELECT TOP 1 'ACERTO/ACORDO'
				FROM LYCEUM..LY_ITEM_LANC IL  
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('Acerto','Acordo')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND (IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END OR IL.PARCELA IS NULL)

), T.TIPO_CREDITO = (
				SELECT TOP 1 'ACERTO/ACORDO'
				FROM LYCEUM..LY_ITEM_LANC IL  
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('Acerto','Acordo')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND (IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END OR IL.PARCELA IS NULL)

)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = ''
AND PAGO = 1


UPDATE T SET T.TIPO_CREDITO = (
				SELECT TOP 1 LC.TIPO_CRED
				FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA 
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = IC.COBRANCA AND VW.COBRANCA = IL.COBRANCA
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL AND IC.ITEM_ESTORNADO IS NULL
				AND VW.VALOR <=0
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_REMATRICULA T
WHERE T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = ''
AND PAGO = 1

UPDATE T SET T.DATA_VENCIMENTO = (
				SELECT CONVERT(VARCHAR(10),MIN(VW.DATA_DE_VENCIMENTO),103)
				FROM LYCEUM..VW_COBRANCA VW 
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_REMATRICULA T


UPDATE T SET T.DATA_VENCIMENTO_ORI = (
				SELECT CONVERT(VARCHAR(10),MIN(C.DATA_DE_VENCIMENTO_ORIG),103)
				FROM LYCEUM..VW_COBRANCA VW 
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL 
				AND VW.ALUNO = T.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre
				AND IL.PARCELA = CASE WHEN @p_semestre = 1 THEN 1 ELSE 6 END

)
FROM TEMP_REMATRICULA T


UPDATE T SET T.TIPO_CREDITO = 'PROUNI', T.TIPO_PAGAMENTO = 'BOLSA'
FROM TEMP_REMATRICULA T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN IN ('PROUNI INTEGRAL','PROUNI PARCIAL')
AND T.PAGO = 1

UPDATE T SET T.TIPO_CREDITO = 'PROIES', T.TIPO_PAGAMENTO = 'BOLSA'
FROM TEMP_REMATRICULA T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN IN ('PROIES')
AND T.PAGO = 1

UPDATE T SET T.TIPO_CREDITO = 'FIES', T.TIPO_PAGAMENTO = 'BOLSA'
FROM TEMP_REMATRICULA T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN = 'FIES'
AND T.PAGO = 1

UPDATE T SET T.TIPO_CREDITO = 'CAMPANHA', T.TIPO_PAGAMENTO = 'DESCONTO'
FROM TEMP_REMATRICULA T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.TIPO_FINAN = 'PAGANTES'
AND T.PAGO = 1



UPDATE T SET T.TIPO_CREDITO = 'NÃO-PAGO', T.TIPO_PAGAMENTO = 'NÃO-PAGO'
FROM TEMP_REMATRICULA T
WHERE (T.TIPO_CREDITO IS NULL OR T.TIPO_CREDITO = '') AND (T.TIPO_PAGAMENTO IS NULL OR T.TIPO_PAGAMENTO = '')
AND T.PAGO = 0



--7.0 DEFININDO STATUS FTC DO PUBLICO RESTANTE

		--ALTERAÇÃO DE REGRA PARA MEDICINA DEVIDO A MATRÍCULA FINANCEIRA
		UPDATE BI SET BI.STATUS_FTC = 'PRE-MATRICULADO PAGO'
		FROM TEMP_REMATRICULA BI
		WHERE BI.SIT_MATRICULA = 'Sem-Matrícula' AND BI.PAGO = 1 AND BI.CURSO = '722'
		AND EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_LANC_DEBITO LD 
		WHERE LD.ALUNO = BI.ALUNO AND LD.ANO_REF = @p_ano 
		AND LD.PERIODO_REF = @p_semestre AND LD.CODIGO_LANC IN ('SM','MS')
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno'))
		AND STATUS_FTC IS NULL
		
		UPDATE BI SET BI.STATUS_FTC = 'PRE-MATRICULADO NÃO-PAGO'
		FROM TEMP_REMATRICULA BI
		WHERE BI.SIT_MATRICULA = 'Sem-Matrícula' AND BI.PAGO = 0 AND BI.CURSO = '722'
		AND EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_LANC_DEBITO LD 
		WHERE LD.ALUNO = BI.ALUNO AND LD.ANO_REF = @p_ano 
		AND LD.PERIODO_REF = @p_semestre AND LD.CODIGO_LANC IN ('SM','MS')
		AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno'))
		AND STATUS_FTC IS NULL
		
		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'PRE-MATRICULADO PAGO'
		WHERE SIT_MATRICULA = 'Pre-Matriculado' AND PAGO = 1 AND STATUS_FTC IS NULL

		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'PRE-MATRICULADO NÃO-PAGO'
		WHERE SIT_MATRICULA = 'Pre-Matriculado' AND PAGO = 0 AND STATUS_FTC IS NULL

		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'PRE-MATRICULADO PAGO'
		WHERE SIT_MATRICULA = 'Pre-Matricula' AND PAGO = 1 AND STATUS_FTC IS NULL

		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'PRE-MATRICULADO NÃO-PAGO'
		WHERE SIT_MATRICULA = 'Pre-Matricula' AND PAGO = 0 AND STATUS_FTC IS NULL

		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'MATRICULADO PAGO'
		WHERE SIT_MATRICULA IN ('Matriculado','Dispensado') AND PAGO = 1 AND STATUS_FTC IS NULL

		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'MATRICULADO NÃO-PAGO'
		WHERE SIT_MATRICULA IN ('Matriculado','Dispensado') AND PAGO = 0 AND STATUS_FTC IS NULL

		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'NÃO-MATRICULADO'
		WHERE SIT_MATRICULA = 'Sem-Matrícula' AND PAGO = 1 AND STATUS_FTC IS NULL

		UPDATE TEMP_REMATRICULA SET STATUS_FTC = 'NÃO-MATRICULADO'
		WHERE SIT_MATRICULA = 'Sem-Matrícula' AND PAGO = 0 AND STATUS_FTC IS NULL


--7.1 APÓS A CLASSIFICAÇÂO, REMOVER CASOS DUPLICADOS DE NÃO-REMATRICULADOS E PRÉ-MATRICULADOS (AJUSTE VERIFICAÇÃO DE PRÉ-MATRICULA NO PERIODO ANTERIOR)
DELETE B1 FROM TEMP_REMATRICULA B1
WHERE B1.STATUS_FTC = 'NÃO-REMATRICULADO'
AND EXISTS (SELECT TOP 1 1 FROM TEMP_REMATRICULA B2 WHERE B2.ALUNO = B1.ALUNO AND B2.ANO = B1.ANO AND B2.SEMESTRE = B1.SEMESTRE AND B2.STATUS_FTC = 'PRE-MATRICULADO PAGO')

DELETE B1 FROM TEMP_REMATRICULA B1
WHERE B1.STATUS_FTC = 'NÃO-REMATRICULADO'
AND EXISTS (SELECT TOP 1 1 FROM TEMP_REMATRICULA B2 WHERE B2.ALUNO = B1.ALUNO AND B2.ANO = B1.ANO AND B2.SEMESTRE = B1.SEMESTRE AND B2.STATUS_FTC = 'PRE-MATRICULADO NÃO-PAGO')

--7.3 REMOVER CONCLUIDOS/CANCELADOS/EVADIDOS DUPLICADOS QUE NÃO SE MATRICULARAM NO PERIODO ATUAL
DELETE B1 FROM TEMP_REMATRICULA B1
WHERE 1=1
AND EXISTS (SELECT TOP 1 1 
			FROM BI_REMATRICULA B 
			WHERE B.ALUNO = B1.ALUNO 
			AND B.STATUS_FTC = 'CONCLUIDO'
			AND B1.STATUS_FTC = B.STATUS_FTC
			AND CONCAT(B.ANO,B.SEMESTRE) <= CONCAT(@p_ano,@p_semestre))
AND B1.STATUS_FTC NOT IN ('PRE-MATRICULADO PAGO','MATRICULADO PAGO')


--8.0 DEFININDO TIPO_FINAN

UPDATE BI SET BI.TIPO_FINAN = 'FIES'
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND TB.GRUPO_BOLSA = 'FIES' 
AND B.DATA_CANCEL IS NULL 
AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
)

IF CONCAT(@p_ano,@p_semestre) >= '20201' 
BEGIN
UPDATE BI SET BI.TIPO_FINAN = 'FIES' 
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
END



IF CONCAT(@p_ano,@p_semestre) >= '20201' 
BEGIN
UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO = 0.5000
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
END


UPDATE BI SET BI.TIPO_FINAN = 'PROUNI PARCIAL' 
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_50','PROUNI50') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND B.DATA_CANCEL IS NULL
AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
)



UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
FROM TEMP_REMATRICULA BI WHERE EXISTS (
SELECT TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND B.TIPO_BOLSA IN ('PROUNI_100','PROUNI100') 
AND TB.GRUPO_BOLSA = 'PROUNI'
AND B.DATA_CANCEL IS NULL 
AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
)


IF CONCAT(@p_ano,@p_semestre) >= '20201' 
BEGIN
UPDATE BI SET BI.TIPO_FINAN = 'PROUNI INTEGRAL' 
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO = 1.0000
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
END

UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
FROM TEMP_REMATRICULA BI 
WHERE EXISTS (
				select TOP 1 1 
				FROM LYCEUM..LY_BOLSA B
				JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
				WHERE B.ALUNO = BI.ALUNO
				AND B.TIPO_BOLSA = 'PROIES100'
				AND TB.GRUPO_BOLSA = 'PROIES' 
				AND B.DATA_CANCEL IS NULL 
				AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
				AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
)


IF CONCAT(@p_ano,@p_semestre) >= '20201' 
BEGIN
UPDATE BI SET BI.TIPO_FINAN = 'PROIES' 
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM  LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN LYCEUM..LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = BI.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo')
				AND LC.TIPO_PAGAMENTO = 'Especial' AND LC.TIPO_CRED = 'PROIES')
END


UPDATE BI SET BI.TIPO_FINAN = 'FIES+PROUNI'
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_BOLSA B
JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
WHERE B.ALUNO = BI.ALUNO
AND TB.GRUPO_BOLSA = 'FIES' 
AND B.DATA_CANCEL IS NULL 
AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
)
AND TIPO_FINAN LIKE 'PRO%'

IF CONCAT(@p_ano,@p_semestre) >= '20201' 
BEGIN
UPDATE BI SET BI.TIPO_FINAN = 'FIES+PROUNI' 
FROM TEMP_REMATRICULA BI WHERE EXISTS (
select TOP 1 1 
FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = BI.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre)
AND BI.TIPO_FINAN LIKE '%PROUNI%'
END

UPDATE TEMP_REMATRICULA SET TIPO_FINAN = 'PAGANTES'
WHERE TIPO_FINAN IS NULL

UPDATE T SET TIPO_FINAN = 'BOLSISTA'
FROM TEMP_REMATRICULA T
WHERE T.TIPO_FINAN = 'PAGANTES'
AND EXISTS (

--BOLSA 100% NO SEMESTRE
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					--AND B.TIPO_BOLSA IN ('IMES','BF PCD','PARES','BAFFFTC','BINCRH')
					AND (B.MESINI IN (1,7) AND B.MESFIM IN (6,12))
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
					
UNION
--BOLSA 100% ABERTA		
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL
UNION
--BOLSA 100% FECHADA NO SEMESTRE		
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOINI = @p_ano)
					AND (B.MESINI = CASE WHEN @p_semestre = 1 THEN 1 ELSE 7 END)
					AND (B.ANOFIM = @p_ano) 
					AND (B.MESFIM = CASE WHEN @p_semestre = 1 THEN 6 ELSE 12 END)
		)

--8.0.1 DIVIDINDO FIES
--UPDATE T SET T.TIPO_FINAN = 'FIES INTEGRAL'
--FROM TEMP_REMATRICULA T
--WHERE EXISTS (SELECT TOP 1 1 
--FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
--					WHERE PPP.RESP = 'FIES' --RESP FIES
--					AND PPP.ALUNO = T.ALUNO
--					AND PPP.PERCENT_DIVIDA_ALUNO = 1
--					AND PPP.ANO = @p_ano
--					AND PPP.PERIODO = @p_semestre)

--UPDATE T SET T.TIPO_FINAN = 'FIES PARCIAL'
--FROM TEMP_REMATRICULA T
--WHERE T.TIPO_FINAN = 'FIES'

--8.1 DEFININDO TIPO_FINAN PARA FIES NO PERIODO ATUAL (SE TINHA FIES NO PERIODO PASSADO, CONSIDERAR TAMBEM NO ATUAL)
IF CONCAT(@p_ano,@p_semestre) = '20201' 
BEGIN
	UPDATE BI SET BI.TIPO_FINAN = BI2.TIPO_FINAN
	FROM TEMP_REMATRICULA BI
	JOIN BI_REMATRICULA BI2 ON BI2.ALUNO = BI.ALUNO 
	WHERE BI2.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
		AND BI2.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END
		AND BI2.TIPO_FINAN IN ('FIES','FIES+PROUNI')
		AND BI.TIPO_FINAN = 'PAGANTES'
		AND BI.PAGO = 0
		AND BI.SIT_MATRICULA  <> 'Matriculado'

	UPDATE BI SET BI.TIPO_FINAN = BI2.TIPO_FINAN
	FROM TEMP_REMATRICULA BI
	JOIN BI_REMATRICULA BI2 ON BI2.ALUNO = BI.ALUNO 
	WHERE BI2.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
		AND BI2.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END
		AND BI2.TIPO_FINAN = 'PROIES'
			
		
END

--8.1.1 DIVIDIR FIES EM INTEGRAL/PARCIAL PARA OS FIES "NAO EFETIVADOS"
--UPDATE T SET T.TIPO_FINAN = 'FIES PARCIAL'
--FROM TEMP_REMATRICULA T


--INDICE DE REPROVACAO
UPDATE BI SET BI.INDICE_REPROVACAO = (SELECT CONVERT(DECIMAL(10,2),COUNT(*))
FROM LYCEUM..LY_HISTMATRICULA HM 
WHERE HM.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
		AND HM.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END
		AND HM.ALUNO = BI.ALUNO AND HM.SITUACAO_HIST IN ('Rep Nota','Rep Freq')) / (SELECT CONVERT(DECIMAL(10,2),COUNT(*))
FROM LYCEUM..LY_HISTMATRICULA HM
WHERE HM.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
		AND HM.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END
		AND HM.ALUNO = BI.ALUNO AND HM.SITUACAO_HIST NOT IN ('Dispensado','Cancelado', 'Inconcluido'))
FROM TEMP_REMATRICULA BI
JOIN LYCEUM..LY_HISTMATRICULA HM2 ON HM2.ALUNO = BI.ALUNO AND HM2.SITUACAO_HIST NOT IN ('Dispensado','Cancelado', 'Inconcluido')
		AND HM2.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END
		AND HM2.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END
WHERE BI.TIPO_ALUNO = 'VETERANO'

--TEM NOTA

IF CONCAT(@p_ano,@p_semestre) < '20201'

	BEGIN

	UPDATE BI SET TEM_NOTA = 'S'
	FROM TEMP_REMATRICULA BI
	WHERE EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_NOTA_HISTMATR N
					WHERE N.ANO = @p_ano AND N.SEMESTRE = @p_semestre
					AND N.ALUNO = BI.ALUNO)
	END
ELSE
	BEGIN
	UPDATE BI SET TEM_NOTA = 'S'
	FROM TEMP_REMATRICULA BI
	WHERE EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_NOTA N
					WHERE N.ANO = @p_ano AND N.SEMESTRE = @p_semestre
					AND N.ALUNO = BI.ALUNO)
	END


--9.0 SANEAMENTO DE NOMES DE CURSOS
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Direito' WHERE NOME_CURSO = 'Bacharel em Direito'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Biomedicina' WHERE NOME_CURSO = 'Biomedicina - ITA'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Ciências Contábeis' WHERE NOME_CURSO = 'Ciências Contábeis (Noturno) CESUFS'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Ciências Econômicas' WHERE NOME_CURSO = 'Ciências Econômicas (Noturno- CESUFS)'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Design de Produto' WHERE NOME_CURSO = 'DESIGN DE PRODUTO'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Administração' WHERE NOME_CURSO LIKE '%Administração%'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Comunicação Social - Jornalismo' WHERE NOME_CURSO = 'Comunicação Social com Habilitação em Jornalismo'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Comunicação Social - Publicidade e Propaganda' WHERE NOME_CURSO = 'Comunicação Social com Habilitação em Publicidade e Propaganda'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Comunicação Social - Publicidade e Propaganda' WHERE NOME_CURSO = 'Publicidade e Propaganda'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Tecnológico em Segurança no Trabalho' WHERE NOME_CURSO = 'Segurança do Trabalho'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Tecnológico em Radiologia' WHERE NOME_CURSO = 'Tecnólogo em Radiologia'
UPDATE TEMP_REMATRICULA SET NOME_CURSO = 'Psicologia' WHERE NOME_CURSO = 'Psicologia - Formação de Psicólogo'


--11.0 CALCULANDO A SERIE_CALCULDADA
UPDATE T
	SET T.SERIE_CALCULADA = (SELECT COUNT(DISTINCT CONCAT(HM.ANO,HM.SEMESTRE))+1 
							FROM LYCEUM..LY_HISTMATRICULA HM 
							WHERE T.ALUNO = HM.ALUNO 
							AND CONCAT(HM.ANO,HM.SEMESTRE) < CONCAT(@p_ano,@p_semestre)
							AND HM.SITUACAO_HIST NOT IN ('Cancelado','Dispensado'))
	FROM TEMP_REMATRICULA T
	

--11.1 TODO CALOURO DEVE SER TRATADO COM SERIE_CALCULADA = 1
UPDATE T
	SET T.SERIE_CALCULADA = 1
	FROM TEMP_REMATRICULA T
	WHERE T.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE','REINGRESSO','REINGRESSO-CONCLUINTE')
	


--12.0 TRATAMENTO PARA SERIE CALCULADA MAIOR QUE O MAXIMO DE SEMESTRES
UPDATE T
	SET T.SERIE_CALCULADA = (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)
	FROM TEMP_REMATRICULA T
	JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = T.ALUNO
	WHERE T.SERIE_CALCULADA > (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)
	AND T.TIPO_ALUNO IN ('VETERANO','VETERANO-CONCLUINTE')

IF @p_ano = 2020 AND @p_semestre = 1
	BEGIN
	
	UPDATE T SET TIPO_ALUNO = 'VETERANO', T.TIPO_INGRESSO = A.TIPO_INGRESSO, T.SERIE_CALCULADA = T.SERIE
	FROM TEMP_REMATRICULA T
	JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = T.ALUNO
	WHERE T.UNIDADE_FISICA_ALUNO = 'UNECE-EUN'
	AND CONCAT(T.ANO_INGRESSO,T.SEM_INGRESSO) < '20201'
	AND T.ANO = 2020 AND T.SEMESTRE = 1

	END



--13.0 SANEAMENTO CURSOS DE POS COMO GRADUACAO
DELETE FROM TEMP_REMATRICULA WHERE NOME_CURSO LIKE 'Especialização%'
DELETE FROM TEMP_REMATRICULA WHERE NOME_CURSO LIKE 'Mestr%'

--14.0 REMOVER ALUNOS "VERMELHOS" QUE JÁ SÃO "VERMELHOS NO PERÍODO ANTERIOR
DELETE BI 
FROM TEMP_REMATRICULA BI WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 WHERE BI2.ALUNO = BI.ALUNO 
			AND BI2.ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END
			AND BI2.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE @p_semestre END
			AND BI2.STATUS_FTC IN ('EVADIDO','CONCLUIDO','CANCELADO','TRANSFERIDO','NÃO REMATRICULADO', 'PRE-MATRICULADO NÃO-PAGO'))
AND BI.STATUS_FTC NOT IN ('PRE-MATRICULADO PAGO','MATRICULADO PAGO','TRANCADO','CONCLUIDO')

--15.0 CONTAR QUANTIDADE DE COBRANCAS DE MENSALIDADE ATRASADAS.
UPDATE BI SET QTD_INADIMP = (SELECT count(distinct CONCAT(C.ANO,C.MES)) FROM LYCEUM..LY_COBRANCA C
JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
WHERE C.DATA_DE_VENCIMENTO < GETDATE() AND VW.VALOR > 50
--AND C.NUM_COBRANCA IN (1,5)
AND IL.CODIGO_LANC IN ('MS','MS_EB','SM')
AND C.ESTORNO = 'N'
AND C.DT_ESTORNO IS NULL
AND C.ALUNO = BI.ALUNO
AND CONCAT(LD.ANO_REF,LD.PERIODO_REF) < CONCAT(BI.ANO,BI.SEMESTRE)
AND C.RESP NOT IN ('FIES','03738654000105'))
FROM TEMP_REMATRICULA BI


--16.0 CONTAR QUANTIDADE DE FALTAS QUE O ALUNO TEVE NO SEMESTRE
--SERÁ REALIZADO UMA MEDIA PERCENTUAL DE FALTA DE ACORDO COM A CH DAS DISCIPLINAS
--IF CONCAT(@p_ano,@p_semestre) < CONCAT(YEAR(GETDATE()),CASE WHEN MONTH(GETDATE()) < 7 THEN 1 ELSE 2 END) 
	--BEGIN
	UPDATE BI2 SET BI2.PERC_FALTAS = (SELECT 1-AVG(HM.PERC_PRESENCA) 
	FROM LYCEUM..LY_HISTMATRICULA HM 
	WHERE HM.ANO = CASE @p_semestre WHEN '1' THEN HM.ANO-1 WHEN '2' THEN HM.ANO WHEN '11' THEN HM.ANO-1 WHEN '22' THEN HM.ANO ELSE HM.ANO END 
		AND HM.SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE HM.SEMESTRE END
		AND BI2.ALUNO = HM.ALUNO AND HM.SITUACAO_HIST NOT IN ('Cancelado','Dispensado','Trancado')
		)
	FROM TEMP_REMATRICULA BI2 
	
	UPDATE TEMP_REMATRICULA SET PERC_FALTAS = 0.00 WHERE TIPO_ALUNO = 'CALOURO'
		
	--END
--ELSE
--	BEGIN

--	CREATE TABLE TEMP_FALTAS (
--		ALUNO VARCHAR(20),
--		DISCIPLINA VARCHAR(20),
--		TURMA VARCHAR(30),
--		ANO VARCHAR(4),
--		SEMESTRE VARCHAR(2),
--		TOTAL_AULAS INT,
--		TOTAL_FALTAS INT
--	)

--	INSERT INTO TEMP_FALTAS
--	SELECT VW.ALUNO, VW.DISCIPLINA, VW.TURMA, VW.ANO, VW.SEMESTRE,0,0
--	FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW
--	JOIN TEMP_REMATRICULA BI ON BI.ALUNO = VW.ALUNO AND BI.ANO = VW.ANO AND BI.SEMESTRE = VW.SEMESTRE

--	UPDATE T SET T.TOTAL_AULAS = (SELECT COUNT(*) FROM LYCEUM..LY_AGENDA A WHERE A.DISCIPLINA = T.DISCIPLINA AND A.TURMA = T.TURMA AND A.ANO = T.ANO AND A.SEMESTRE = T.SEMESTRE)
--	FROM TEMP_FALTAS T

--	UPDATE T SET T.TOTAL_FALTAS = (SELECT CONVERT(INT,FALTAS) FROM LYCEUM..LY_FALTA A WHERE A.DISCIPLINA = T.DISCIPLINA AND A.TURMA = T.TURMA AND A.ANO = T.ANO AND A.PERIODO = T.SEMESTRE AND A.ALUNO = T.ALUNO)
--	FROM TEMP_FALTAS T

--	UPDATE T SET T.TOTAL_FALTAS = 0 FROM TEMP_FALTAS T WHERE T.TOTAL_FALTAS IS NULL
		
--	UPDATE BI SET BI.PERC_FALTAS = (SELECT AVG(T.TOTAL_FALTAS)/AVG(T.TOTAL_AULAS) FROM TEMP_FALTAS T WHERE T.ALUNO = BI.ALUNO AND T.ANO = BI.ANO AND T.SEMESTRE = BI.SEMESTRE AND T.TOTAL_AULAS > 0)
--	FROM TEMP_REMATRICULA BI

--	DROP TABLE TEMP_FALTAS

--	END

	UPDATE TEMP_REMATRICULA SET PERC_FALTAS = 0.00 WHERE PERC_FALTAS IS NULL
	
--17.0 MANTER SOMENTE STATUS OFICIAIS // REGRA EXCLUÍDA EM 06dez2019
--UPDATE T SET T.STATUS_FTC = 'EVADIDO'
--FROM TEMP_REMATRICULA T
--WHERE T.STATUS_FTC IN ('NÃO REMATRICULADO NÃO-PAGO','NÃO REMATRICULADO PAGO','PRE-MATRICULADO NÃO-PAGO')

--18.0 CLASIFICAÇÂO PERFIL DE EVASÃO
UPDATE T SET T.PERFIL_EVASAO = 'APROVEITAMENTO'
FROM TEMP_REMATRICULA T
WHERE T.INDICE_REPROVACAO >= 0.25

UPDATE T SET T.PERFIL_EVASAO = 'FREQUÊNCIA'
FROM TEMP_REMATRICULA T
WHERE T.PERC_FALTAS >= 0.25

UPDATE T SET T.PERFIL_EVASAO = 'INADIMPLÊNCIA'
FROM TEMP_REMATRICULA T
WHERE T.QTD_INADIMP > 0

UPDATE T SET T.PERFIL_EVASAO = 'REGULAR'
FROM TEMP_REMATRICULA T
WHERE T.PERFIL_EVASAO IS NULL

--19.0 VERIFICAR SE HOUVE SOLICITACAO DE PLANO/HISTORICO

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.TEMP_SERVICO'))   
BEGIN
	DROP TABLE TEMP_SERVICO 
END


CREATE TABLE TEMP_SERVICO (
	SOLICITACAO INT,
	ALUNO VARCHAR(20),
	DATA_ABERTURA VARCHAR(10),
	SERVICO VARCHAR(20)
)

INSERT INTO TEMP_SERVICO
SELECT DISTINCT  
 SS.SOLICITACAO
,SS.ALUNO
,CONVERT(VARCHAR(10),SS.DATA,103) AS DATA_ABERTURA
,ISS.SERVICO
FROM  LYCEUM..LY_SOLICITACAO_SERV SS
JOIN LYCEUM..LY_ITENS_SOLICIT_SERV ISS ON ISS.SOLICITACAO = SS.SOLICITACAO
JOIN LYCEUM..LY_TABELA_SERVICOS TS ON TS.SERVICO = ISS.SERVICO
JOIN TEMP_REMATRICULA BI ON BI.ALUNO = SS.ALUNO
WHERE TS.SERVICO IN ('AOL_HISESC1','AOL_HISESC2','AOL_PLADISC1','AOL_PLADISC')
AND DATEDIFF(DAY,SS.DATA,BI.DATA_PERIODO) BETWEEN 1 AND CASE MONTH(BI.DATA_PERIODO) WHEN 1 THEN 184 ELSE 181 END

UPDATE BI SET SOLICITOU_PLANO = 'S'
FROM TEMP_REMATRICULA BI
JOIN TEMP_SERVICO T ON T.ALUNO = BI.ALUNO
WHERE T.SERVICO IN ('AOL_PLADISC1','AOL_PLADISC1')


UPDATE BI SET SOLICITOU_HIST = 'S'
FROM TEMP_REMATRICULA BI
JOIN TEMP_SERVICO T ON T.ALUNO = BI.ALUNO
WHERE T.SERVICO IN ('AOL_HISESC1','AOL_HISESC2')

DROP TABLE TEMP_SERVICO

--20.0 VALOR DA MENSALIDADE E DA SEMESTRALIDADE

UPDATE BI SET BI.VALOR_MENSALIDADE = VM.VALOR_MENSALIDADE, VALOR_SEMESTRALIDADE = VM.VALOR_MENSALIDADE*6
FROM TEMP_REMATRICULA BI
JOIN BI_VALOR_MENSALIDADE VM ON VM.ANO = BI.ANO 
								AND VM.SEMESTRE = BI.SEMESTRE 
								AND VM.CURSO = BI.CURSO 
								AND VM.CURRICULO = BI.CURRICULO 
								AND VM.TURNO = BI.TURNO 
								AND VM.SERIE = BI.SERIE
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre


--21.0 MEDIA PERCENTUAL de BOLSA // REGRA EXCLUÍDA EM 06dez2019

--CREATE TABLE TEMP_PERC_BOLSA (
--	ANO VARCHAR(4),
--	SEMESTRE VARCHAR(2),
--	ALUNO VARCHAR(20),
--	VALOR_SEMESTRALIDADE DECIMAL(10,2),
--	MEDIA_PERC_BOLSA DECIMAL(10,2)
--	)

--INSERT INTO TEMP_PERC_BOLSA
--SELECT ANO, SEMESTRE, ALUNO, VALOR_SEMESTRALIDADE, 0.00 AS MEDIA_PERC_BOLSA
--FROM TEMP_REMATRICULA



--UPDATE B SET B.VALOR_SEMESTRALIDADE = (SELECT SUM(IL.VALOR) 
--					FROM LYCEUM..LY_ITEM_LANC IL
--					WHERE IL.LANC_DEB IN (SELECT LD.lanc_deb 
--					FROM LYCEUM..LY_LANC_DEBITO LD
--					WHERE LD.ALUNO = B.ALUNO
--					AND LD.ANO_REF = CASE B.SEMESTRE WHEN '1' THEN B.ANO-1 WHEN '2' THEN B.ANO WHEN '11' THEN B.ANO-1 WHEN '22' THEN B.ANO ELSE B.ANO END 
--					AND LD.PERIODO_REF = CASE B.SEMESTRE WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE B.SEMESTRE END
--					AND ITEM_ESTORNADO IS NULL AND NUM_BOLSA IS NULL
--					AND LD.CODIGO_LANC = 'MS'))
--FROM TEMP_PERC_BOLSA B



--UPDATE B SET B.MEDIA_PERC_BOLSA = (SELECT SUM(IL.VALOR) 
--					FROM LYCEUM..LY_ITEM_LANC IL
--					WHERE IL.LANC_DEB IN (SELECT LD.lanc_deb 
--					FROM LYCEUM..LY_LANC_DEBITO LD
--					WHERE LD.ALUNO = B.ALUNO
--					AND LD.ANO_REF = CASE B.SEMESTRE WHEN '1' THEN B.ANO-1 WHEN '2' THEN B.ANO WHEN '11' THEN B.ANO-1 WHEN '22' THEN B.ANO ELSE B.ANO END 
--					AND LD.PERIODO_REF = CASE B.SEMESTRE WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE B.SEMESTRE END
--					AND ITEM_ESTORNADO IS NULL
--					AND LD.CODIGO_LANC = 'MS'))/B.VALOR_SEMESTRALIDADE
--FROM TEMP_PERC_BOLSA B
--WHERE B.VALOR_SEMESTRALIDADE > 0



--UPDATE BI SET BI.MEDIA_PERC_BOLSA = B.MEDIA_PERC_BOLSA, BI.VALOR_SEMESTRALIDADE = B.VALOR_SEMESTRALIDADE
--FROM TEMP_REMATRICULA BI
--JOIN TEMP_PERC_BOLSA B ON B.ALUNO = BI.ALUNO AND B.ANO = BI.ANO AND B.SEMESTRE = BI.SEMESTRE

--DROP TABLE TEMP_PERC_BOLSA

--22 ULTIMO ACESSO AO BLACKBOARD

	UPDATE BI SET BI.DATA_ULTIMO_LOGIN_BB = ISNULL((SELECT CONVERT(VARCHAR(10),MAX(X.ULTIMO_LOGIN),23)
		FROM BI_BB_ACESSO_ALUNO X
		WHERE X.ALUNO = BI.ALUNO AND X.ANO = BI.ANO AND X.SEMESTRE = BI.SEMESTRE
		GROUP BY ANO, SEMESTRE, ALUNO),CONVERT(VARCHAR(10),BI.DATA_PERIODO,23))  
	FROM TEMP_REMATRICULA BI
	

	UPDATE BI SET BI.SEMANA_ULTIMO_LOGIN_BB = ISNULL(DATEDIFF(week,DATA_ULTIMO_LOGIN_BB,GETDATE()),0)
	FROM TEMP_REMATRICULA BI
	

--RESULTADO FINAL
		INSERT INTO BI_REMATRICULA
		SELECT DISTINCT
			ANO,
			SEMESTRE, 
			STATUS_FTC,
			UNIDADE_ENSINO_ALUNO,
			NOME_UNIDADE_ENSINO_ALUNO,
			UNIDADE_FISICA_ALUNO,
			TIPO_CURSO,
			CURSO,
			NOME_CURSO,
			CURRICULO,
			TURNO,
			SERIE,
			SERIE_CALCULADA,
			TIPO_ALUNO,
			TIPO_INGRESSO,
			ANO_INGRESSO,
			SEM_INGRESSO,
			ALUNO,
			CPF,
			NOME_ALUNO,
			E_MAIL,
			DDD,
			FONE,
			CELULAR,
			CEP,
			MUNICIPIO,
			SIT_MATRICULA,
			PAGO,
			NAO_PAGO,
			TIPO_FINAN,
			FINAN,
			DATA_PERIODO,
			INDICE_REPROVACAO,
			QTD_INADIMP,
			PERC_FALTAS,
			DATA_MATRICULA,
			ANTECIP_FINAN,
			DT_ANTECIP,
			TIPO_ANTECIP,
			VALOR_ATENCIP,
			PERFIL_EVASAO,
			ULTIMA_MATRICULA,
			SOLICITOU_PLANO,
			SOLICITOU_HIST,
			TIPO_TRANSF,
			VALOR_MENSALIDADE,
			VALOR_SEMESTRALIDADE,
			DT_ENCERRAMENTO,
			BOLSISTA,
			MEDIA_PERC_BOLSA,
			SIT_MATRICULA_ANTERIOR,
			PROFISSAO,
			CARGO,
			ESPECIALIDADE,
			EMPRESA,
			AREA,
			DEPARTAMENTO,
			BAIRRO_COMERCIAL,
			PAIS_COMERCIAL,
			COD_MUNICIPIO_COMERCIAL,
			MUNICIPIO_COMERCIAL,
			NECESSIDADE_ESPECIAL,
			COR_RACA,
			RENDA,
			CONTRIBUI_RENDA_FAMILIAR,
			RELIGIAO,
			FORMACAO_ANTERIOR,
			TIPO_FORMACAO_ANTERIOR,
			ORIGEM_FORMACAO_ANTERIOR,
			ANO_CONCL_FORMACAO_ANTERIOR,
			PAIS_FORMACAO_ANTERIOR,
			COD_MUNICIPIO_FORMACAO_ANTERIOR,
			MUNICIPIO_FORMACAO_ANTERIOR,
			UF_FORMACAO_ANTERIOR,
			SEXO,
			DATA_NASCIMENTO,
			ESTADO_CIVIL,
			NACIONALIDADE,
			PAIS_NASCIMENTO,
			COD_MUNICIPIO_RESIDENCIAL,
			MUNICIPIO_RESIDENCIAL,
			UF_RESIDENCIAL,
			PAIS_RESIDENCIAL,
			END_CORRETO,
			BAIRRO,
			DATA_INGRESSO,
			DATA_PAGAMENTO,
			TIPO_PAGAMENTO,
			TEM_NOTA,
			TIPO_FINAN_ANTERIOR,
			DIA_CAMPANHA,
			CONCURSO,
			DESC_CONCURSO,
			ORIGEM_MATRICULA,
			CONTRATO_ACEITO,
			BOLSAS,
			DATA_MATRICULA_ORC,
			CANDIDATO,
			TIPO_CREDITO,
			DATA_VENCIMENTO,
			DATA_VENCIMENTO_ORI,
			DATA_ULTIMO_LOGIN_BB,
			SEMANA_ULTIMO_LOGIN_BB
		FROM TEMP_REMATRICULA

DROP TABLE TEMP_REMATRICULA

--VERIFICAÇÃO DE CANCELAMENTO RETROATIVO
UPDATE T SET STATUS_FTC = 'EVADIDO'
FROM BI_REMATRICULA T 
JOIN LYCEUM..LY_H_CURSOS_CONCL H ON H.ALUNO = T.ALUNO AND H.ANO_ENCERRAMENTO = T.ANO AND H.SEM_ENCERRAMENTO = T.SEMESTRE
WHERE H.MOTIVO IN ('Abandono','Evasao') AND H.ANO_ENCERRAMENTO = @p_ano AND H.SEM_ENCERRAMENTO = @p_semestre
AND H.DT_REABERTURA IS NULL 

--DELETE FINAL DOS DUPLICADOS
DELETE BI FROM BI_REMATRICULA BI
WHERE BI.DATA_MATRICULA IS NULL
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.ALUNO = BI.ALUNO AND BI2.DATA_MATRICULA IS NOT NULL 
			AND BI2.ANO = BI.ANO AND BI2.SEMESTRE = BI.SEMESTRE)

--UPDATE MAX ULTIMA_MATRICULA
UPDATE T
	SET T.ULTIMA_MATRICULA = (SELECT MAX(CONCAT(BI.ANO,'/',BI.SEMESTRE)) FROM BI_REMATRICULA BI WHERE BI.ALUNO = T.ALUNO AND BI.STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO','CONCLUIDO') )
FROM BI_REMATRICULA T
WHERE T.ANO = @p_ano AND T.SEMESTRE = @p_semestre

--CLASSIFICAÇÃO DE TRANSFERENCIAS
UPDATE BI SET TIPO_TRANSF = 'ENTRADA CURSO'
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('TRANSFERIDO','CANCELADO') AND BI.CPF <> '' AND BI.CPF IS NOT NULL
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO = BI2.UNIDADE_ENSINO_ALUNO)

UPDATE BI SET TIPO_TRANSF = 'SAIDA CURSO'
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND BI.STATUS_FTC IN ('TRANSFERIDO','CANCELADO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')  AND BI.CPF <> '' AND BI.CPF IS NOT NULL
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO = BI2.UNIDADE_ENSINO_ALUNO)


UPDATE BI SET TIPO_TRANSF = 'ENTRADA UNIDADE'
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('TRANSFERIDO','CANCELADO') AND BI.CPF <> '' AND BI.CPF IS NOT NULL
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO <> BI2.UNIDADE_ENSINO_ALUNO)

UPDATE BI SET TIPO_TRANSF = 'SAIDA UNIDADE'
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND BI.STATUS_FTC IN ('TRANSFERIDO','CANCELADO')
AND STATUS_FTC NOT IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO') AND BI.CPF <> '' AND BI.CPF IS NOT NULL
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO <> BI2.UNIDADE_ENSINO_ALUNO)

--SANEAMENTO CALOUROS 2018.1 de JUAZEIRO
IF @p_ano = 2018 AND @p_semestre = 1
	BEGIN
	UPDATE T SET TIPO_ALUNO = 'CALOURO', SERIE_CALCULADA = 1
	FROM BI_REMATRICULA T
	WHERE T.UNIDADE_FISICA_ALUNO = 'OTE-JUA'
	AND T.ANO = 2018 AND T.SEMESTRE = 1

	DELETE T1 
	FROM BI_REMATRICULA T1 
	WHERE T1.UNIDADE_FISICA_ALUNO = 'OTE-JUA'
	AND T1.ANO = 2017 AND T1.SEMESTRE = 2
	AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA T WHERE T.ALUNO = T1.ALUNO AND T.ANO = 2018 AND T.SEMESTRE = 1)
END


--SANEAMENTO CALOUROS 2019.1 de PETROLINA DIREITO
IF @p_ano = 2019 AND @p_semestre = 1
	BEGIN
	UPDATE T SET TIPO_ALUNO = 'CALOURO', SERIE_CALCULADA = 1
	FROM BI_REMATRICULA T
	WHERE T.UNIDADE_FISICA_ALUNO = 'OTE-PET' AND T.CURSO = '4018'
	AND T.ANO = 2019 AND T.SEMESTRE = 1

	DELETE T1 
	FROM BI_REMATRICULA T1 
	WHERE T1.UNIDADE_FISICA_ALUNO = 'OTE-PET' AND T1.CURSO = '4018'
	AND T1.ANO = 2018 AND T1.SEMESTRE = 2
	AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA T WHERE T.ALUNO = T1.ALUNO AND T.ANO = 2019 AND T.SEMESTRE = 1)
END

--[FIM]
END
GO