USE FTC_DATAMART
GO

--EXEC BI_VALOR_MENSALIDADE_JOB

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_VALOR_MENSALIDADE_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_VALOR_MENSALIDADE_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 


ALTER PROCEDURE dbo.BI_VALOR_MENSALIDADE_JOB

AS            
-- [INÍCIO]                    
BEGIN  


IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.BI_VALOR_MENSALIDADE'))   
BEGIN
	DROP TABLE BI_VALOR_MENSALIDADE
END

ELSE

	CREATE TABLE BI_VALOR_MENSALIDADE
	(
		CURSO VARCHAR(20),
		TURNO VARCHAR(1),
		CURRICULO VARCHAR(20),
		SERIE SMALLINT,
		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		VALOR_MENSALIDADE DECIMAL(10,2)
	)


INSERT INTO BI_VALOR_MENSALIDADE
SELECT	DISTINCT 
		S.CURSO,
		S.TURNO,
		S.CURRICULO,
		S.SERIE,
		VSP.ANO,
		VSP.PERIODO AS SEMESTRE,
		CONVERT(DECIMAL(10,2),VSP.CUSTO_UNITARIO*SUM(D.CREDITOS)/6) AS VALOR_MENSALIDADE
FROM BI_REMATRICULA BI
JOIN LYCEUM..LY_CURSO C ON C.CURSO = BI.CURSO
JOIN LYCEUM..LY_GRADE G ON G.CURSO = BI.CURSO AND G.TURNO = BI.TURNO AND G.CURRICULO = BI.CURRICULO AND G.SERIE_IDEAL = BI.SERIE
JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA = G.DISCIPLINA
JOIN LYCEUM..LY_SERIE S ON S.CURSO = BI.CURSO AND S.TURNO = BI.TURNO AND S.CURRICULO = BI.CURRICULO AND S.SERIE = BI.SERIE
JOIN LYCEUM..LY_VALOR_SERV_PERIODO VSP ON VSP.SERVICO = S.SERVICO_CRED AND VSP.ANO = BI.ANO AND VSP.PERIODO = BI.SEMESTRE
WHERE 1=1
GROUP BY 
		BI.ALUNO,
		S.CURSO,
		S.TURNO,
		S.CURRICULO,
		S.SERIE,
		VSP.ANO,
		VSP.PERIODO,
		VSP.CUSTO_UNITARIO
END