--SELECT * FROM AY_RESUMO_ATO WHERE COBRANCA = '838291'
--SELECT * FROM AY_RESUMO_ATO WHERE COBRANCA = '2475918'

--SELECT dbo.fnGetDtContabil('Ly_Item_Lanc','2475916','1','','','') 

--SELECT * FROM LY_ITEM_LANC
--Relat_Faturamento_FTC
USE LYCEUM
GO

SELECT	DISTINCT 
		C.RESP
		, C.ALUNO
		, C.COBRANCA
		, A.UNIDADE_FISICA
		, CC.TIPO
		, ISNULL(IL.CENTRO_DE_CUSTO,'') AS CENTRO_DE_CUSTO
		, A.CURSO
		, CC.NOME
		, UF.NOME_COMP
		, RF.TITULAR
		, RF.CPF_TITULAR
		, A.NOME_COMPL
		, CASE C.NUM_COBRANCA    
             WHEN 1 THEN 'MENSALIDADE'    
             WHEN 2 THEN 'SERVICO'    
             WHEN 3 THEN 'ACORDO'    
             WHEN 4 THEN 'OUTROS'    
             WHEN 5 THEN 'CHEQUE DEVOLVIDO'    
             ELSE NULL END AS TIPO_COBRANCA 
		, IL.CODIGO_LANC
		, 'N' AS 'COBRANCA ESTORNADA'
		, C.DATA_DE_GERACAO
		, C.DATA_DE_VENCIMENTO_ORIG
		, C.ANO AS ANO_REF
		, C.MES AS MES_REF
		, C.DATA_DE_FATURAMENTO
		, (SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = C.COBRANCA AND IL.NUM_BOLSA IS NULL)																AS [VALOR_TITULO]
		, (SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = C.COBRANCA)																						AS [VALOR_FATURADO]
		, (SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC1 WHERE IC1.COBRANCA = C.COBRANCA AND IC1.TIPO_ENCARGO = 'MULTA')														AS [MULTA]
		, (SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC4 WHERE IC4.COBRANCA = C.COBRANCA AND IC4.TIPO_ENCARGO = 'PERDEBOLSA')												AS [PERDEBOLSA]
		, (SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC2 WHERE IC2.COBRANCA = C.COBRANCA AND IC2.TIPO_ENCARGO = 'JUROS')														AS [JUROS]
		, (SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = C.COBRANCA AND IC3.TIPODESCONTO IN ('Acréscimo','Concedido','DescBanco','PagtoAntecipado'))	AS [DESCONTO]
		, (SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = C.COBRANCA AND IC3.TIPODESCONTO IS NULL AND IC3.TIPO_ENCARGO IS NULL)*-1						AS [VALOR_PAGO]
		, CONCAT(LD.ANO_REF,'/',LD.PERIODO_REF) AS PERIODO_DIVIDA
		, A.SIT_ALUNO
		, ISNULL(HCC.MOTIVO,'') AS MOTIVO_SITUACAO
		, ISNULL(HCC.DT_INSERCAO,'') AS DATA_INSERCAO_SITUACAO
FROM LY_COBRANCA C
JOIN LY_RESP_FINAN RF ON RF.RESP = C.RESP
JOIN LY_ITEM_LANC IL ON IL.COBRANCA = C.COBRANCA
JOIN LY_ALUNO A ON A.ALUNO = C.ALUNO
JOIN LY_CURSO CC ON CC.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
JOIN VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
LEFT JOIN LY_H_CURSOS_CONCL HCC ON HCC.ALUNO = A.ALUNO
WHERE C.DATA_DE_FATURAMENTO IS NOT NULL AND C.ESTORNO = 'N' AND DT_ESTORNO IS NULL AND CONCAT(LD.ANO_REF,'/',LD.PERIODO_REF) >= '2016/0' AND VW.VALOR > 0
ORDER BY ALUNO,ANO_REF,MES_REF