select A.ALUNO, A.NOME_COMPL, A.CURSO, C.NOME, A.CURRICULO, A.TURNO, A.UNIDADE_FISICA  
from LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
where SIT_ALUNO = 'Cancelado' and ANO_INGRESSO = 2017 and SEM_INGRESSO = 2 and UNIDADE_FISICA = 'FCS'