--2016.1
SELECT ALUNO, '2016.1' PERIODO_ULTIMO_VINCULO FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE SIT_ALUNO = 'Ativo'
AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2016 AND SEMESTRE = 1)
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2016 AND SEMESTRE = 2)
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2017)
AND NOT EXISTS (SELECT TOP 1 1 FROM VW_TRANC_ALUNO WHERE ALUNO = A.ALUNO)
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_H_CURSOS_CONCL WHERE ALUNO = A.ALUNO)
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')

UNION

--2016.2
SELECT ALUNO, '2016.2' PERIODO_ULTIMO_VINCULO FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE SIT_ALUNO = 'Ativo'
AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2016 AND SEMESTRE = 2)
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2017)
AND NOT EXISTS (SELECT TOP 1 1 FROM VW_TRANC_ALUNO WHERE ALUNO = A.ALUNO)
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_H_CURSOS_CONCL WHERE ALUNO = A.ALUNO)
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
