USE LYCEUM
GO

SELECT COUNT(A.ALUNO) QTD_MATRICULAS,P.PESSOA,P.CPF, P.NOME_COMPL,  C.CURSO, C.NOME  
INTO  #TEMP
FROM LY_PESSOA P
JOIN LY_ALUNO A ON A.PESSOA = P.PESSOA
JOIN LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
WHERE 1=1
AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2017)
GROUP BY P.CPF, P.NOME_COMPL, C.CURSO, C.NOME,P.PESSOA
HAVING COUNT(A.ALUNO) > 1
GO

SELECT A.ALUNO, A.NOME_COMPL, A.UNIDADE_FISICA, C.CURSO, C.NOME, A.SIT_ALUNO, A.ANO_INGRESSO, A.SEM_INGRESSO
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
JOIN #TEMP T ON T.PESSOA = A.PESSOA
WHERE A.ANO_INGRESSO > '2010'
ORDER BY A.UNIDADE_FISICA

--select * from LY_HISTMATRICULA WHERE ALUNO = '171041050'

--171041050	Antonio Lucas dos Santos Henn	112	Bacharel em Direito	Evadido	2017	1
--181041804	Antonio Lucas dos Santos Henn	112	Bacharel em Direito	Ativo	2018	1