select DISTINCT INEP_CURSO, C.CURSO, NOME, FACULDADE, UE.NOME_COMP from LY_CURSO C
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_ALUNO A ON A.CURSO = C.CURSO
WHERE ATIVO = 'S'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND (INEP_CURSO IS NULL OR INEP_CURSO = '')
AND FACULDADE <> '02'
    AND EXISTS(
                SELECT  1 FROM  LY_HISTMATRICULA H 
                WHERE 1=1
                AND H.ALUNO=A.ALUNO
                AND H.ANO='2017'
                --AND H.SEMESTRE='2'
            )