

select CC.CURSO AS COD_CURSO_LYCEUM, CENTRO_DE_CUSTO, C.NOME AS NOME_CURSO, C.ATIVO 
FROM LYCEUM..LY_CENTRO_DE_CUSTO CC
RIGHT JOIN LYCEUM..LY_CURSO C ON C.CURSO = CC.CURSO


select * FROM LYCEUM..LY_CURSO WHERE CURSO = '4019'