select DISTINCT 
		vw.VALOR AS SALDO_COBRANCA
		,x.VALOR AS SALDO_INCONSISTENTE
		,c.* from LY_COBRANCA C
    ,
JOIN VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
JOIN	(SELECT IL.COBRANCA, SUM(IL.VALOR) VALOR FROM LY_LANC_DEBITO LD 
		JOIN LY_ITEM_LANC IL ON IL.LANC_DEB = LD.LANC_DEB
		WHERE CONCAT(LD.ANO_REF,LD.PERIODO_REF) < '20180'
		OR LD.DESCRICAO LIKE 'Mig Ref%'
		GROUP BY IL.COBRANCA) X ON X.COBRANCA = C.COBRANCA
WHERE 1=1
AND C.ANO = 2018
AND C.MES  < 7 
--AND C.DATA_DE_FATURAMENTO >= '2018-01-01' 
--AND C.ESTORNO = 'N' 
--AND C.DATA_DE_GERACAO >= '2018-01-01'
--AND C.COBRANCA = '3554636'
UNION
SELECT DISTINCT -- rodar apenas quando for solicitado MIG REF
		VW.VALOR AS SALDO_COBRANCA
		,X.VALOR AS SALDO_INCONSISTENTE
		,CUR.TIPO
		,C.* FROM LY_COBRANCA C
JOIN VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
JOIN LY_CURSO CUR ON CUR.CURSO = C.CURSO
JOIN	(SELECT IL.COBRANCA, SUM(IL.VALOR) VALOR FROM LY_LANC_DEBITO LD 
		JOIN LY_ITEM_LANC IL ON IL.LANC_DEB = LD.LANC_DEB
		WHERE --CONCAT(LD.ANO_REF,LD.PERIODO_REF) < '20180'
		LD.DESCRICAO LIKE 'MIG REF%'
		--OR IL.PARCELA <> 5
		GROUP BY IL.COBRANCA) X ON X.COBRANCA = C.COBRANCA
WHERE 1=1
AND C.ANO = 2018 
AND C.MES = 3
--AND C.DATA_DE_FATURAMENTO >= '2018-01-01' 
--AND C.ESTORNO = 'N' 
--AND C.DATA_DE_GERACAO >= '2018-01-01'
AND C.COBRANCA = '3554636'


select * from LY_COBRANCA WHERE COBRANCA = '3554636'
select * from LY_ITEM_LANC WHERE COBRANCA = '3554636'

select * from LY_LANC_DEBITO WHERE LANC_DEB = '2417161'
select * from LY_ITEM_LANC WHERE LANC_DEB = '2417161'

select *
--COUNT(COB.COBRANCA) COBRANCA,
--CUR.TIPO
--COUNT(CUR.TIPO) CURSO--, CUR.CURSO
from ly_cobranca cob
join ly_curso cur
on cur.curso = cob.curso
where cob.data_de_geracao <'2018-01-01' 
and cob.data_de_faturamento > '2018-01-01'
and cob.estorno = 'N' --AND CUR.TIPO ='ENS BASICO'
GROUP BY CUR.TIPO