USE LYCEUM
GO

/*
SELECT VW.* FROM LY_COBRANCA C
JOIN VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
WHERE C.ESTORNO = 'S' AND DT_ESTORNO IS NOT NULL AND VW.VALOR > 0 AND VW.data_de_faturamento is not null
ORDER BY VW.ALUNO,ANO,MES

SELECT * FROM VW_COBRANCA WHERE COBRANCA = '4982177'
SELECT * FROM LY_ITEM_LANC WHERE COBRANCA = '4982177'

*/

UPDATE C SET C.ESTORNO = 'N', C.DT_ESTORNO = NULL
FROM LY_COBRANCA C
JOIN VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
WHERE C.ESTORNO = 'S' AND DT_ESTORNO IS NOT NULL AND VW.VALOR > 0 AND VW.data_de_faturamento is not null
GO

