SELECT DISTINCT NAME, compatibility_level FROM sys.databases WHERE compatibility_level = 130
ORDER BY 1

SELECT @@VERSION

USE [master]
GO
ALTER DATABASE API SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE EAD SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE EADBOX SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE HADES SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE HADES_AUDIT SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE LYCEUM SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE LYCEUMA SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE LYCEUMINTEGRACAO SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE LYCEUMMART SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE LYCEUMTEMP SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE MIGRACAO SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE MONITOR SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE ReportServer SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE ReportServerTempDB SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE SISRELATORIO SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE VIRTUALCLASS SET COMPATIBILITY_LEVEL = 130
GO
