SELECT DISTINCT A.ALUNO FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = A.ALUNO
WHERE C.TIPO = 'GRADUACAO' AND VW.ANO = 2017 AND VW.SEMESTRE = 1
AND EXISTS (SELECT 1 FROM LY_BOLSA B WHERE B.ALUNO = A.ALUNO AND (B.TIPO_BOLSA LIKE '%FIES%' OR B.TIPO_BOLSA LIKE 'PROUNI') AND  B.DATA_CANCEL IS NULL AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL))  
AND A.SIT_ALUNO = 'Ativo'
AND VW.SIT_MATRICULA = 'Pre-matriculado'

UNION

SELECT DISTINCT A.ALUNO FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = A.ALUNO
WHERE C.TIPO = 'GRADUACAO' AND VW.ANO = 2017 AND VW.SEMESTRE = 1
AND EXISTS (SELECT TOP 1 1 
					FROM LY_ITEM_LANC IL
					JOIN LY_LANC_DEBITO LD
						ON IL.LANC_DEB = LD.LANC_DEB 
					JOIN VW_COBRANCA C
						ON IL.COBRANCA = C.COBRANCA
					JOIN LY_COBRANCA CC ON CC.COBRANCA = C.COBRANCA
				WHERE LD.ALUNO = A.ALUNO
				AND LD.CODIGO_LANC = 'MS'
				AND LD.ANO_REF = VW.ANO
				AND LD.PERIODO_REF = VW.SEMESTRE
				AND C.VALOR = 0
				AND LD.LANC_DEB = VW.LANC_DEB
				AND CC.ESTORNO = 'N'
				GROUP BY IL.COBRANCA
				HAVING MAX(IL.PARCELA) = 1)
AND A.SIT_ALUNO = 'Ativo'
AND VW.SIT_MATRICULA = 'Pre-matriculado'
ORDER BY 1