SELECT DISTINCT ALUNO, UNIDADE_ENSINO_ALUNO, NOME_UNIDADE_ENSINO_ALUNO, UNIDADE_FISICA_ALUNO FROM BI_REMATRICULA BI
JOIN LYCEUM..LY_UNIDADES_ASSOCIADAS UA ON UA.UNIDADE_FIS = BI.UNIDADE_FISICA_ALUNO  AND UA.UNIDADE_ENS <> BI.UNIDADE_ENSINO_ALUNO
WHERE ANO = 2020 AND SEMESTRE = 1
ORDER BY 4

SELECT * FROM BI_REMATRICULA BI 
WHERE BI.ANO = 2020 AND BI.SEMESTRE = 1
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.NOME_ALUNO = BI.NOME_ALUNO
			AND BI2.CPF <> BI.CPF
			AND BI2.ANO = 2020 AND BI2.SEMESTRE =1)
ORDER BY BI.NOME_ALUNO

SELECT * FROM LYCEUM..LY_UNIDADE_ENSINO