USE FTC_DATAMART
GO

CREATE TABLE TEMP
(
	UNIDADE_FISICA_ALUNO VARCHAR(50),
	NOME_CURSO VARCHAR(100),
	TURNO VARCHAR(1),
	SAIDA INT,
	ENTRADA INT
)

DELETE FROM TEMP

INSERT INTO TEMP
SELECT DISTINCT BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO, BI.TURNO, 0 AS SAIDA, 0 AS ENTRADA
FROM BI_REMATRICULA BI
WHERE ANO = 2020 AND SEMESTRE = 1 
AND TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
AND TIPO_TRANSF IS NOT NULL
AND BI.UNIDADE_FISICA_ALUNO IN ('FTC-LAPA','FCS')



UPDATE T SET T.SAIDA = (SELECT ISNULL(COUNT(BI.ALUNO),0)
FROM BI_REMATRICULA BI
WHERE ANO = 2020 AND SEMESTRE = 1 
AND TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
AND TIPO_TRANSF IN ('SAIDA UNIDADE','SAIDA CURSO')
AND BI.UNIDADE_FISICA_ALUNO IN ('FTC-LAPA','FCS')
AND BI.UNIDADE_FISICA_ALUNO = T.UNIDADE_FISICA_ALUNO
AND BI.NOME_CURSO = T.NOME_CURSO
AND BI.TURNO = T.TURNO
GROUP BY BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO, BI.TURNO)
FROM TEMP T


UPDATE T SET T.ENTRADA = (SELECT ISNULL(COUNT(BI.ALUNO),0)
FROM BI_REMATRICULA BI
WHERE ANO = 2020 AND SEMESTRE = 1 
AND TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
AND TIPO_TRANSF IN ('ENTRADA UNIDADE','ENTRADA CURSO')
AND BI.UNIDADE_FISICA_ALUNO IN ('FTC-LAPA','FCS')
AND BI.UNIDADE_FISICA_ALUNO = T.UNIDADE_FISICA_ALUNO
AND BI.NOME_CURSO = T.NOME_CURSO
AND BI.TURNO = T.TURNO
GROUP BY BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO, BI.TURNO)
FROM TEMP T

UPDATE TEMP SET ENTRADA = 0 WHERE ENTRADA IS NULL

UPDATE TEMP SET SAIDA = 0 WHERE SAIDA IS NULL