USE LYCEUM
GO

SELECT	UE.UNIDADE_ENS
		,UE.NOME_COMP
		,C.TIPO
		,C.CURSO
		,C.NOME
		,A.TURNO
		,A.CURRICULO
		,A.ALUNO
		,A.NOME_COMPL
		,A.SIT_ALUNO
		,VW.SIT_MATRICULA
		,ISNULL(VW.TURMA,'') AS TURMA
		,VW.DISCIPLINA
		,D.NOME
		,ISNULL(LD.VALOR,0) AS VALOR_DISCIPLINA
		,D.CREDITOS AS CH_DISCIPLINA
FROM LY_ALUNO A
JOIN LY_CURSO C ON A.CURSO = C.CURSO
JOIN VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = A.ALUNO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = VW.DISCIPLINA
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
LEFT JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = VW.LANC_DEB
WHERE 1=1
AND VW.ANO = '2018' AND VW.SEMESTRE IN ('0','1')
AND C.TIPO IN ('GRADUACAO','TECNOLOGO','ENS BASICO')
AND C.FACULDADE IN ('50','51','52','53','03','04','05','06','07','21','22','29')
ORDER BY 1,4,8