USE LYCEUM
GO

--EXEC FTC_Relat_StatusMatriculaPos '03',NULL,'2738',NULL,NULL,NULL,NULL,NULL,1

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_StatusMatriculaPos'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_StatusMatriculaPos] AS BEGIN SET NOCOUNT OFF; END')
GO 

 
ALTER PROCEDURE dbo.FTC_Relat_StatusMatriculaPos       
(            
 @p_unidade VARCHAR(20)
 )
 AS
 -- [INÍCIO]                    
BEGIN            
        
SET NOCOUNT ON   

select A.UNIDADE_FISICA, UF.NOME_COMP, A.CURSO, C.NOME,A.SIT_ALUNO, A.ALUNO, A.NOME_COMPL, ISNULL(CONCAT(P.DDD_FONE_CELULAR,P.CELULAR),'') AS CELULAR, P.E_MAIL
--COUNT(A.ALUNO), A.UNIDADE_FISICA 
FROM LY_ALUNO A
JOIN LY_UNIDADE_FISISCA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
--JOIN LY_FL_ALUNO FA ON FA.ALUNO = A.ALUNO
WHERE 1=1
--AND FA.FL_FIELD_01 = 'VIRTUAL'
AND ((UF.UNIDADE_FIS = @p_faculdade AND @p_faculdade IS NOT NULL) OR @p_faculdade IS NULL)
AND C.TIPO = 'POS-GRADUACAO'
AND A.SIT_ALUNO = 'Ativo'
AND EXISTS (SELECT TOP 1 1 FROM LY_COBRANCA WHERE ALUNO = A.ALUNO AND DATA_DE_VENCIMENTO >= GETDATE() AND DATA_DE_FATURAMENTO IS NOT NULL AND ESTORNO = 'N' AND DT_ESTORNO IS NULL)
--AND NOT EXISTS (SELECT TOP 1 1 FROM VW_matricula_pre_matricula WHERE ALUNO = A.ALUNO)
--AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO)
--GROUP BY A.UNIDADE_FISICA

ORDER BY A.UNIDADE_FISICA, A.CURSO, A.ALUNO

SET NOCOUNT OFF

END

-- [FIM]  