SELECT	UF.UNIDADE_FIS
		, UF.NOME_COMP AS NOME_UNIDADE
		, CU.CURSO
		, CU.NOME AS NOME_CURSO
		, A.ALUNO
		, A.NOME_COMPL AS NOME_ALUNO
		, C.COBRANCA
		, C.DATA_DE_VENCIMENTO
		, SUM(IL.VALOR) AS VALOR_BOLETO
		, C.DATA_DE_GERACAO
		, B.IMPRESSO_WEB
FROM LY_BOLETO B
JOIN LY_COBRANCA C ON C.RESP = B.RESP
JOIN LY_ITEM_LANC IL ON IL.BOLETO = B.BOLETO AND IL.ALUNO = C.ALUNO AND IL.RESP = C.RESP
JOIN LY_ALUNO A ON A.ALUNO = IL.ALUNO
JOIN LY_CURSO CU ON CU.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
GROUP BY UF.UNIDADE_FIS	, UF.NOME_COMP, CU.CURSO, CU.NOME, A.ALUNO, A.NOME_COMPL, C.COBRANCA, C.DATA_DE_VENCIMENTO, C.DATA_DE_GERACAO, B.IMPRESSO_WEB