SELECT	A.ALUNO, 
		A.NOME_COMPL, 
		A.UNIDADE_FISICA, 
		A.CURSO, 
		C.NOME, 
		A.TURNO, 
		A.CURRICULO,
		P.DDD_FONE+'-'+P.FONE AS TELEFONE, 
		P.DDD_FONE_CELULAR+'-'+P.CELULAR AS CELULAR, 
		A.SIT_ALUNO,
		A.TIPO_INGRESSO
  FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE 1=1 
AND A.SIT_ALUNO = 'Cancelado'
AND A.ANO_INGRESSO = '2017'
AND A.SEM_INGRESSO = '1'
ORDER BY 3,4,2