SELECT --TOP 100 
		A.NOME_COMPL																		AS NOME_ALUNO
		,ISNULL(P.CPF,'-- NÃO TEM --')														AS CPF_ALUNO
		,C.COBRANCA																			AS ID_PARCELA
		,MIG.CODIGO_MENSALIDADE_VIRTUAL																					AS ID_PARCELA_ANTIGA
		,A.ALUNO																			AS RA_ALUNO 
		,FL.FL_FIELD_02																	    AS RA_ANTIGO 
		--,A.CURSO																			AS CURSO
		--,CUR.NOME																			AS NOME_CURSO	
		--,A.UNIDADE_FISICA																	AS UNIDADE_FISICA 
		,C.DATA_DE_VENCIMENTO																AS VENCIMENTO
		,COB.VALOR_TOTAL																	AS VALOR_PARCELA
		--,C.ANO																				AS ANO_PARCELA
		--,C.MES																				AS MES_PARCELA
		, (CASE C.NUM_COBRANCA
				WHEN 1 THEN 'MENSALIDADE'
				WHEN 2 THEN 'SERVIÇOS'
				WHEN 3 THEN 'PARCELA DE ACORDO'
				WHEN 4 THEN 'DIVERSOS - DÍVIDAS AVULSAS'
				WHEN 5 THEN 'DIVIDA DE CHEQUE'
			ELSE 'DIVERSOS'
		END)																				AS DESCRICAO_PARCELA
		,'COBRANCA'																			AS BOL_CHQ
		,(ISNULL(P.DDD_FONE,'') + '-' + ISNULL(P.FONE,''))									AS TELEFONE_FIXO
		,(ISNULL(P.DDD_FONE_CELULAR,'') + '-' + ISNULL(P.CELULAR,''))						AS TELEFONE_CELULAR
		,(ISNULL(P.DDD_FONE_COMERCIAL,'') + '-' + ISNULL(P.FONE_COM,''))					AS TELEFONE_COM
		,P.E_MAIL																			AS EMAIL
		,P.ENDERECO																			AS ENDERECO
		,P.END_NUM																			AS NUMERO
		,P.END_COMPL																		AS COMPLEMENTO
		,P.BAIRRO																			AS BAIRRO
		,P.CEP																				AS CEP
		,ISNULL(MUN.NOME,'')																AS CIDADE
		,ISNULL(MUN.UF,'')																	AS UF
FROM LY_ALUNO A
JOIN LY_PESSOA P
	ON A.PESSOA = P.PESSOA
JOIN Ly_CURSO CUR
	ON A.CURSO = CUR.CURSO
JOIN LY_COBRANCA C
	ON A.ALUNO = C.ALUNO
-- Consulto o valor da item lanc
JOIN (SELECT COBRANCA, SUM(VALOR) AS VALOR_TOTAL FROM LY_ITEM_LANC GROUP BY COBRANCA) COB
	ON C.COBRANCA = COB.COBRANCA
-- COnsulto a cidade e uf do endereço do aluno
LEFT JOIN (SELECT CODIGO, NOME, UF_SIGLA AS UF FROM MUNICIPIO) MUN
	ON P.END_MUNICIPIO =  MUN.CODIGO
LEFT JOIN LY_FL_ALUNO FL
    ON FL.ALUNO = A.ALUNO
JOIN ftc_vw_consulta_migracao MIG
    ON MIG.ALUNO = A.ALUNO
WHERE 1=1
AND MIG.ANO = 2016
AND C.NUM_COBRANCA = 1
--AND EXISTS (SELECT TOP 1 1 FROM VW_COBRANCA		-- A condição é ter saldo na cobrança
--				WHERE COBRANCA = C.COBRANCA
--				AND VALOR > 0)
--AND FL.ALUNO = '161030335'
--AND C.DATA_DE_VENCIMENTO < '2015-12-31'
--## INCLUIR ABAIXO AS CONDIÇÕES PARA INDICAR AS COBRANCAS QUE IRÃO PARA A LPONTES
-- AND EXISTS .....
-- teste atualizacao--

ORDER BY C.ANO, C.MES, C.DATA_DE_VENCIMENTO
