

DECLARE @p_ano VARCHAR(4) = '2020'
DECLARE @p_semestre VARCHAR(2) = '1'
--DECLARE @p_cpf VARCHAR(11) = ''

SELECT BI.CPF, BI.ALUNO, 'ENTRADA CURSO' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
INTO #TEMP
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
--AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('TRANSFERIDO','CANCELADO') AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO = BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO)
AND BI.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')


UNION

SELECT BI.CPF, BI.ALUNO, 'SAIDA CURSO' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND BI.STATUS_FTC IN ('TRANSFERIDO','CANCELADO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF  AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO = BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO
			AND BI2.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE'))
--AND BI.CPF = @p_cpf OR @p_cpf = ''

UNION

SELECT BI.CPF, BI.ALUNO, 'ENTRADA UNIDADE' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
--AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('TRANSFERIDO','CANCELADO') AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO <> BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO)
AND BI.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
--AND BI.CPF = @p_cpf OR @p_cpf = ''

UNION

SELECT BI.CPF, BI.ALUNO, 'SAIDA UNIDADE' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND BI.STATUS_FTC IN ('TRANSFERIDO','CANCELADO')
AND STATUS_FTC NOT IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO <> BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO
			AND BI2.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE'))
--AND BI.CPF = @p_cpf OR @p_cpf = ''
ORDER BY CPF

SELECT DISTINCT ALUNO FROM #TEMP ORDER BY CPF

SELECT * FROM #TEMP WHERE CPF = '02841902501' ORDER BY 3
SELECT ALUNO,* FROM BI_REMATRICULA WHERE CPF = '02841902501' ORDER BY 1, ANO, SEMESTRE

LYCEUM..LY_ALUNO
