SELECT ANO_REF, PERIODO_REF, B.ALUNO, ISNULL(SUM(LD.VALOR),0.00) DIVIDA_CALCULADA
FROM LYCEUM..LY_LANC_DEBITO LD
JOIN #TEMPALUNO B ON B.ALUNO = LD.ALUNO
WHERE LD.ALUNO = B.ALUNO
AND LD.CODIGO_LANC IN ('MS','SM')
AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno')
AND CONCAT(LD.ANO_REF,LD.PERIODO_REF) >= '20172'
GROUP BY LD.ANO_REF, LD.PERIODO_REF, B.ALUNO
ORDER BY B.ALUNO, LD.ANO_REF, LD.PERIODO_REF