USE LYCEUM
GO


--QUANTIDADE DE ALUNOS POR DISCIPLINA
--HISTORICO
SELECT	HM.ANO,
		HM.SEMESTRE,
		A.UNIDADE_FISICA,
		C.CURSO,
		C.NOME AS NOME_CURSO,
		D.DISCIPLINA,
		D.NOME AS NOME_DISCIPLINA,
		COUNT(A.ALUNO) AS QTD_ALUNOS
FROM	LY_HISTMATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
WHERE 1=1
AND HM.SITUACAO_HIST IN ('Aprovado','Rep Nota','Rep Freq')
AND CONCAT(HM.ANO,HM.SEMESTRE) >= '20141'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND C.FACULDADE IN ('03','04','05')
GROUP BY Hm.ANO, HM.SEMESTRE, A.UNIDADE_FISICA, C.CURSO, C.NOME, D.DISCIPLINA, D.NOME

--MATRICULA
SELECT	HM.ANO,
		HM.SEMESTRE,
		A.UNIDADE_FISICA,
		C.CURSO,
		C.NOME AS NOME_CURSO,
		D.DISCIPLINA,
		D.NOME AS NOME_DISCIPLINA,
		COUNT(A.ALUNO) AS QTD_ALUNOS
FROM	LY_HISTMATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
WHERE 1=1
AND HM.SITUACAO_HIST IN ('Aprovado','Rep Nota','Rep Freq')
AND CONCAT(HM.ANO,HM.SEMESTRE) >= '20141'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND C.FACULDADE IN ('03','04','05')
GROUP BY Hm.ANO, HM.SEMESTRE, A.UNIDADE_FISICA, C.CURSO, C.NOME, D.DISCIPLINA, D.NOME





--MEDIA DISCIPLINAS POR ALUNO POR PERIODO, UNIDADE, CURSO E SERIE
--MEDIA CARGA HORARIA POR ALUNO POR PERIODO, UNIDADE, CURSO E SERIE
--HISTORICO
SELECT	HM.ANO,
		HM.SEMESTRE,
		A.UNIDADE_FISICA,
		C.CURSO,
		C.NOME AS NOME_CURSO,
		HM.SERIE,
		A.ALUNO,
		COUNT(HM.DISCIPLINA) AS QTD_DISCIPLINA
INTO #TEMP_DISCIPLINAS
FROM	LY_HISTMATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
WHERE 1=1
AND HM.SITUACAO_HIST IN ('Aprovado','Rep Nota','Rep Freq')
AND CONCAT(HM.ANO,HM.SEMESTRE) >= '20141'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
--AND C.FACULDADE IN ('03','04','05')
GROUP BY HM.ANO, HM.SEMESTRE, A.UNIDADE_FISICA, C.CURSO, C.NOME, HM.SERIE, A.ALUNO

--MATRICULA

INSERT INTO #TEMP_DISCIPLINAS
SELECT	HM.ANO,
		HM.SEMESTRE,
		A.UNIDADE_FISICA,
		C.CURSO,
		C.NOME AS NOME_CURSO,
		A.SERIE,
		A.ALUNO,
		COUNT(HM.DISCIPLINA) AS QTD_DISCIPLINA
FROM	LY_MATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
WHERE 1=1
AND HM.SIT_MATRICULA IN ('Aprovado','Rep Nota','Rep Freq','Matriculado')
AND CONCAT(HM.ANO,HM.SEMESTRE) >= '20141'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
--AND C.FACULDADE IN ('03','04','05')
GROUP BY HM.ANO, HM.SEMESTRE, A.UNIDADE_FISICA, C.CURSO, C.NOME, A.SERIE, A.ALUNO

	DELETE FROM #TEMP_DISCIPLINAS WHERE SERIE = 0 OR SERIE IS NULL

	UPDATE T
	SET T.SERIE = (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)
	FROM #TEMP_DISCIPLINAS T
	JOIN LY_ALUNO A ON A.ALUNO = T.ALUNO
	WHERE T.SERIE > (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)

SELECT	ANO,
		SEMESTRE,
		UNIDADE_FISICA,
		CURSO,
		NOME_CURSO,
		SERIE,
		AVG(QTD_DISCIPLINA) AS MEDIA_DISCIPLINA
FROM #TEMP_DISCIPLINAS
GROUP BY ANO, SEMESTRE, UNIDADE_FISICA,	CURSO, NOME_CURSO, SERIE
ORDER BY 1,2,3,4,6


--select * FROM LY_HISTMATRICULA  HM
--JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
--WHERE HM.ANO = 2016 AND HM.SEMESTRE = 2 AND HM.SERIE = 1 AND HM.SITUACAO_HIST IN ('Aprovado','Rep Nota','Rep Freq')
--AND A.CURSO = '2060'
--ORDER BY 1

--MEDIA CARGA HORARIA POR ALUNO POR PERIODO, UNIDADE, CURSO E SERIE
--HISTORICO
SELECT	HM.ANO,
		HM.SEMESTRE,
		A.UNIDADE_FISICA,
		C.CURSO,
		C.NOME AS NOME_CURSO,
		A.SERIE,
		A.ALUNO,
		SUM(HM.CREDITOS) AS TOTAL_CH
INTO #TEMP_CH
FROM LY_HISTMATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
WHERE 1=1
AND HM.SITUACAO_HIST IN ('Aprovado','Rep Nota','Rep Freq')
AND CONCAT(HM.ANO,HM.SEMESTRE) >= '20141'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
--AND C.FACULDADE IN ('03','04','05')
GROUP BY HM.ANO, HM.SEMESTRE, A.UNIDADE_FISICA, C.CURSO, C.NOME, A.SERIE, A.ALUNO

--MATRICULA
INSERT INTO #TEMP_CH
SELECT	HM.ANO,
		HM.SEMESTRE,
		A.UNIDADE_FISICA,
		C.CURSO,
		C.NOME AS NOME_CURSO,
		A.SERIE,
		A.ALUNO,
		SUM(D.CREDITOS) AS TOTAL_CH
FROM LY_MATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
WHERE 1=1
AND HM.SIT_MATRICULA IN ('Aprovado','Rep Nota','Rep Freq','Matriculado')
AND CONCAT(HM.ANO,HM.SEMESTRE) >= '20141'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
--AND C.FACULDADE IN ('03','04','05')
GROUP BY HM.ANO, HM.SEMESTRE, A.UNIDADE_FISICA, C.CURSO, C.NOME, A.SERIE, A.ALUNO

	DELETE FROM #TEMP_CH WHERE SERIE = 0 OR SERIE IS NULL
	
	UPDATE T
	SET T.SERIE = (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)
	FROM #TEMP_CH T
	JOIN LY_ALUNO A ON A.ALUNO = T.ALUNO
	WHERE T.SERIE > (SELECT MAX(G.SERIE_IDEAL) FROM LYCEUM..LY_GRADE G WHERE G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO)


SELECT	ANO,
		SEMESTRE,
		UNIDADE_FISICA,
		CURSO,
		NOME_CURSO,
		SERIE,
		ROUND(AVG(TOTAL_CH),0) AS MEDIA_DISCIPLINA
FROM #TEMP_CH
GROUP BY ANO, SEMESTRE, UNIDADE_FISICA,	CURSO, NOME_CURSO, SERIE
ORDER BY 1,2,3,4,6


select * FROM LY_HISTMATRICULA  HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
WHERE HM.ANO = 2016 AND HM.SEMESTRE = 2 AND HM.SERIE = 1 AND HM.SITUACAO_HIST IN ('Aprovado','Rep Nota','Rep Freq')
AND A.CURSO = '2060'
ORDER BY 1