USE LYCEUM
GO

SELECT	UE.UNIDADE_ENS
		,UE.NOME_COMP
		,C.CURSO
		,C.NOME AS NOME_CURSO
		,A.ALUNO
		,A.NOME_COMPL AS NOME_ALUNO
		,A.SIT_ALUNO
		,CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) AS PERIODO_INGRESSO
		,CONCAT('('+ISNULL(P.DDD_FONE_CELULAR,'')+')',ISNULL(P.CELULAR,'')) AS CELULAR
		,CONCAT('('+ISNULL(P.DDD_FONE,'')+')',ISNULL(P.FONE,'')) AS TELEFONE
		,P.E_MAIL
FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_CONCURSO CO ON CO.CONCURSO = A.CONCURSO
WHERE 1=1
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2016' AND SEMESTRE = '2')
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2017' AND SEMESTRE = '1')
AND NOT EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2017' AND SEMESTRE = '2')
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_H_CURSOS_CONCL WHERE ALUNO = A.ALUNO AND MOTIVO = 'Conclusao')
--AND (SELECT SUM(CREDITOS) FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND SITUACAO_HIST IN ('Aprovado','Dispensado')) 
--< (SELECT SUM(D.CREDITOS) FROM LY_GRADE G JOIN LY_DISCIPLINA D ON D.DISCIPLINA = G.DISCIPLINA WHERE G.CURSO = A.CURSO AND G.CURRICULO = A.CURRICULO AND G.TURNO = A.TURNO )


UNION

SELECT	UE.UNIDADE_ENS
		,UE.NOME_COMP
		,C.CURSO
		,C.NOME AS NOME_CURSO
		,A.ALUNO
		,A.NOME_COMPL AS NOME_ALUNO
		,A.SIT_ALUNO
		,CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) AS PERIODO_INGRESSO
		,CONCAT('('+ISNULL(P.DDD_FONE_CELULAR,'')+')',ISNULL(P.CELULAR,'')) AS CELULAR
		,CONCAT('('+ISNULL(P.DDD_FONE,'')+')',ISNULL(P.FONE,'')) AS TELEFONE
		,P.E_MAIL
FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_CONCURSO CO ON CO.CONCURSO = A.CONCURSO
WHERE 1=1
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2017' AND SEMESTRE = '1')
--AND NOT EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2017' AND SEMESTRE = '1')
AND NOT EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2017' AND SEMESTRE = '2')
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_H_CURSOS_CONCL WHERE ALUNO = A.ALUNO AND MOTIVO = 'Conclusao')
--AND (SELECT SUM(CREDITOS) FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND SITUACAO_HIST IN ('Aprovado','Dispensado')) 
--< (SELECT SUM(D.CREDITOS) FROM LY_GRADE G JOIN LY_DISCIPLINA D ON D.DISCIPLINA = G.DISCIPLINA WHERE G.CURSO = A.CURSO AND G.CURRICULO = A.CURRICULO AND G.TURNO = A.TURNO )



select distinct vw.aluno, vw.sit_matricula, vw.disciplina, vw.ano, vw.semestre from VW_MATRICULA_E_PRE_MATRICULA vw
join LY_ALUNO a on a.ALUNO = vw.aluno
join ly_curso c on c.curso = a.curso
 WHERE ANO = 2017 and semestre = 1 and c.tipo in ('GRADUACAO','TECNOLOGO')
union
select distinct vw.aluno, vw.sit_matricula, vw.disciplina, vw.ano, vw.semestre from VW_MATRICULA_E_PRE_MATRICULA vw
join LY_ALUNO a on a.ALUNO = vw.aluno
join ly_curso c on c.curso = a.curso
 WHERE ANO = 2016 and semestre = 2 and c.tipo in ('GRADUACAO','TECNOLOGO')


select * from VW_MATRICULA_E_PRE_MATRICULA WHERE ANO = 2016 and semestre = 2
--SELECT DISTINCT MOTIVO FROM LY_H_CURSOS_CONCL 