--SELECT TIPO_TRANSF,* FROM BI_REMATRICULA WHERE CPF = '86160918583'
--SELECT * FROM LYCEUM..LY_PESSOA WHERE CPF = '86160918583'
--SELECT * FROM LYCEUM..LY_PESSOA WHERE PESSOA = '4727'
--SELECT * FROM LYCEUM..LY_ALUNO WHERE PESSOA = '4727'
--SELECT * FROM LYCEUM..LY_ALUNO WHERE NOME_COMPL = 'Renata de Jesus Santos'
--SELECT * FROM LYCEUM..LY_CURSO WHERE CURSO  =  '733'
--SELECT * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '072030071'

DECLARE @p_ano VARCHAR(4) = '2020'
DECLARE @p_semestre VARCHAR(2) = '1'
DECLARE @p_cpf VARCHAR(11) = '99474298572'

SELECT BI.CPF, BI.ALUNO, 'ENTRADA CURSO' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
--AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('TRANSFERIDO','CANCELADO') AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO = BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO)
AND BI.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
AND BI.CPF = @p_cpf

SELECT BI.CPF, BI.ALUNO, 'SAIDA CURSO' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND BI.STATUS_FTC IN ('TRANSFERIDO','CANCELADO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF  AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO = BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO
			AND BI2.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE'))
AND BI.CPF = @p_cpf

SELECT BI.CPF, BI.ALUNO, 'ENTRADA UNIDADE' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
--AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC IN ('TRANSFERIDO','CANCELADO') AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO <> BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO)
AND BI.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
AND BI.CPF = @p_cpf

SELECT BI.CPF, BI.ALUNO, 'SAIDA UNIDADE' AS TIPO_TRANSF, BI.TIPO_INGRESSO, BI.STATUS_FTC, BI.UNIDADE_FISICA_ALUNO, BI.NOME_CURSO
FROM BI_REMATRICULA BI
WHERE BI.ANO = @p_ano AND BI.SEMESTRE = @p_semestre
AND BI.STATUS_FTC IN ('TRANSFERIDO','CANCELADO')
AND STATUS_FTC NOT IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.CPF <> '' AND BI2.CPF IS NOT NULL AND BI2.CPF <> '00000000000'
			AND BI2.ANO = @p_ano AND BI2.SEMESTRE = @p_semestre AND BI.UNIDADE_ENSINO_ALUNO <> BI2.UNIDADE_ENSINO_ALUNO AND BI2.ALUNO <> BI.ALUNO
			AND BI2.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE'))
AND BI.CPF = @p_cpf
ORDER BY CPF