--LYCEUM

SELECT TOP 1
   I.sistema_origem      as SISTEMA_ORIGEM  
 , c.valor        as SALDO_LYCEUM  
 , c.COBRANCA       AS COBRANCA
 , c.ano         AS ANO
 , c.mes         AS MES
 , c.data_de_faturamento     AS DATA_FATURAMENTO
 , c.ALUNO        AS ALUNO
 , c.RESP        AS RESP
 , c.DATA_DE_VENCIMENTO     AS DATA_VENCIMENTO
 , I.ALUNO  
 , I.RESP  
 , I.CPF_RESP  
 , I.PERIODO_LETIVO  
 , I.ANO  
 , I.MES  
 , I.DESCRICAO  
 , I.CURSO  
 , I.TURNO  
 , I.CURRICULO  
 , I.UNIDADE_FISICA  
 , I.LANC_DEB  
 , I.CODIGO_LANC  
 , I.VALOR_DESC_DEBITO  
 , I.DESCRICAO_DESC_DEBITO  
 , I.VALOR_DESC_DEBITO2  
 , I.DESCRICAO_DESC_DEBITO2  
 , I.DESCRICAO_LANC_DEBITO  
 , I.COBRANCA  
 , CASE I.NUM_COBRANCA
				WHEN 1 THEN 'MENSALIDADE'
				WHEN 2 THEN 'SERVIÇOS'
				WHEN 3 THEN 'PARCELA DE ACORDO'
				WHEN 4 THEN 'DIVERSOS - DÍVIDAS AVULSAS'
				WHEN 5 THEN 'DIVIDA DE CHEQUE'
			ELSE 'DIVERSOS' 
	END							AS NUM_COBRANCA
 , AY.EVENTO_NUM AS EVENTO_NUM_COBRANCA
 , ISNULL(AY.EVENTO_DESCR,'') AS EVENTO_DESCR_COBRANCA
 , ISNULL(AY.DATACONTAB,'') AS DATACONTAB_COBRANCA
 , I.DATA_VENCIMENTO  
 , I.DATA_GERACAO  
 , I.DATA_FATURAMENTO  
 , I.VALOR_BRUTO  
 , I.TIPO_BOLSA1  
 , I.PERCENTUAL_BOLSA1  
 , I.VALOR_BOLSA1  
 , I.ORDEM_BOLSA1  
 , I.TIPO_BOLSA2  
 , I.PERCENTUAL_BOLSA2  
 , I.VALOR_BOLSA2  
 , I.ORDEM_BOLSA2  
 , I.TIPO_BOLSA3  
 , I.PERCENTUAL_BOLSA3  
 , I.VALOR_BOLSA3  
 , I.ORDEM_BOLSA3  
 , I.TIPO_BOLSA4  
 , I.PERCENTUAL_BOLSA4  
 , I.VALOR_BOLSA4  
 , I.ORDEM_BOLSA4  
 , I.PARCELA  
 , I.PERCENTUAL_MULTA  
 , I.PERCENTUAL_JUROS  
 , I.DATA_VENCIMENTO_ANTECIPACAO1  
 , I.PERCENTUAL_ANTECIPACAO1  
 , I.VALOR_ANTECIPACAO1  
 , I.DATA_VENCIMENTO_ANTECIPACAO2  
 , I.PERCENTUAL_ANTECIPACAO2  
 , I.VALOR_ANTECIPACAO2  
 , I.DATA_VENCIMENTO_ANTECIPACAO3  
 , I.PERCENTUAL_ANTECIPACAO3  
 , I.VALOR_ANTECIPACAO3  
 , I.BOLETO  
 , I.NOSSO_NUMERO  
 , I.INSTRUCAO  
 , I.BANCO  
 , I.AGENCIA  
 , I.CONTA_CORRENTE  
 , I.CONVENIO  
 , I.CARTEIRA  
 , I.DOCUMENTO  
 , I.LANC_CRED
 , AY2.EVENTO_NUM AS EVENTO_NUM_LANC_CRED
 , ISNULL(AY2.EVENTO_DESCR,'') AS EVENTO_DESCR_LANC_CRED
 , AY2.DATACONTAB	 AS DATACONTAB_LANC_CRED  
 , I.DATA_PAGAMENTO  
 , I.TIPO_PAGAMENTO  
 , I.DETALHAMENTO_CREDITO  
 , I.OBSERVACAO  
 , I.USUARIO  
 , I.DESCRICAO_LANC_CREDITO  
 , I.VALOR_MULTA  
 , I.VALOR_JUROS_TOTAL  
 , I.VALOR_PAGO  
 , I.VALOR_DESCONTO  
 , I.VALOR_ACORDADO  
 , I.DATA_ACORDO  
 , I.VALOR_FINAL  
 , I.ESTORNO  
 , I.DATA_ESTORNO  
 , I.MENSAGEM_OBS  
 , I.RPS  
 , I.NFE  
 , I.DATA_ENVIO_RPS  
 , I.EH_SALDO  
 , I.CONTRATO_QTDEPARCELAS  
 , I.CONTRATO_ANOINICIO  
 , I.CONTRATO_MESINICIO  
 , I.CONTRATO_MESINICIO_AGERAR  
 , I.CONTRATO_QTDEPARCELAS_AGERAR  
 , I.CONTA_FINANCEIRA  
 , I.CENTRO_CUSTO  
 , I.FLAG_RESP_PLANO_PAGAMENTO  
 , I.CODIGO_ALUNO_VIRTUAL  
 , I.CODIGO_MENSALIDADE_VIRTUAL  
 , I.CODIGO_CONTRATO_VIRTUAL  
 , I.AGE_IN_CODIGO  
 , I.CODIGO_MENSALIDADE_ACORDO  
 , I.MIGRAR  
 , I.VALOR_ITEM_ADICIONAL  
 , I.DESCRICAO_ITEM_ADICIONAL  
 , I.VALOR_ACERTO  
 , I.TIPO_ACERTO  
 , I.ADIANTAMENTO  
FROM lyceum..vw_cobranca c  
join migracao..tbl_financeiro I  
       on c.cobranca = I.cobranca  
       and c.aluno = I.aluno
left join (SELECT COBRANCA, evento_num, evento_descr, DATACONTAB from AY_RESUMO_ATO WHERE TIPODOC = 'CB' AND ANO_REF = 2016) AY  ON AY.COBRANCA  = I.COBRANCA
left join (SELECT LANC_CRED, EVENTO_NUM, EVENTO_DESCR, DATACONTAB from AY_RESUMO_ATO WHERE TIPODOC = 'PG' AND ANO_REF = 2016) AY2  ON AY2.LANC_CRED  = I.LANC_CRED
WHERE I.migrar = 'S' 
AND I.ANO = 2016 
ORDER BY I.ALUNO, I.ANO, I.MES


--MIGRADO

SELECT TOP 1
   I.sistema_origem      as SISTEMA_ORIGEM  
 , i.COBRANCA       AS COBRANCA
 , i.ano         AS ANO
 , i.mes         AS MES
 , i.data_faturamento     AS DATA_FATURAMENTO
 , i.ALUNO        AS ALUNO
 , i.RESP        AS RESP
 , i.DATA_VENCIMENTO     AS DATA_VENCIMENTO
 , I.ALUNO  
 , I.RESP  
 , I.CPF_RESP  
 , I.PERIODO_LETIVO  
 , I.ANO  
 , I.MES  
 , I.DESCRICAO  
 , I.CURSO  
 , I.TURNO  
 , I.CURRICULO  
 , I.UNIDADE_FISICA  
 , I.LANC_DEB  
 , I.CODIGO_LANC  
 , I.VALOR_DESC_DEBITO  
 , I.DESCRICAO_DESC_DEBITO  
 , I.VALOR_DESC_DEBITO2  
 , I.DESCRICAO_DESC_DEBITO2  
 , I.DESCRICAO_LANC_DEBITO  
 , I.COBRANCA  
 , CASE I.NUM_COBRANCA
				WHEN 1 THEN 'MENSALIDADE'
				WHEN 2 THEN 'SERVIÇOS'
				WHEN 3 THEN 'PARCELA DE ACORDO'
				WHEN 4 THEN 'DIVERSOS - DÍVIDAS AVULSAS'
				WHEN 5 THEN 'DIVIDA DE CHEQUE'
			ELSE 'DIVERSOS' 
	END							AS NUM_COBRANCA
 , AY.EVENTO_NUM AS EVENTO_NUM_COBRANCA
 , ISNULL(AY.EVENTO_DESCR,'') AS EVENTO_DESCR_COBRANCA
 , ISNULL(AY.DATACONTAB,'') AS DATACONTAB_COBRANCA
 , I.DATA_VENCIMENTO  
 , I.DATA_GERACAO  
 , I.DATA_FATURAMENTO  
 , I.VALOR_BRUTO  
 , I.TIPO_BOLSA1  
 , I.PERCENTUAL_BOLSA1  
 , I.VALOR_BOLSA1  
 , I.ORDEM_BOLSA1  
 , I.TIPO_BOLSA2  
 , I.PERCENTUAL_BOLSA2  
 , I.VALOR_BOLSA2  
 , I.ORDEM_BOLSA2  
 , I.TIPO_BOLSA3  
 , I.PERCENTUAL_BOLSA3  
 , I.VALOR_BOLSA3  
 , I.ORDEM_BOLSA3  
 , I.TIPO_BOLSA4  
 , I.PERCENTUAL_BOLSA4  
 , I.VALOR_BOLSA4  
 , I.ORDEM_BOLSA4  
 , I.PARCELA  
 , I.PERCENTUAL_MULTA  
 , I.PERCENTUAL_JUROS  
 , I.DATA_VENCIMENTO_ANTECIPACAO1  
 , I.PERCENTUAL_ANTECIPACAO1  
 , I.VALOR_ANTECIPACAO1  
 , I.DATA_VENCIMENTO_ANTECIPACAO2  
 , I.PERCENTUAL_ANTECIPACAO2  
 , I.VALOR_ANTECIPACAO2  
 , I.DATA_VENCIMENTO_ANTECIPACAO3  
 , I.PERCENTUAL_ANTECIPACAO3  
 , I.VALOR_ANTECIPACAO3  
 , I.BOLETO  
 , I.NOSSO_NUMERO  
 , I.INSTRUCAO  
 , I.BANCO  
 , I.AGENCIA  
 , I.CONTA_CORRENTE  
 , I.CONVENIO  
 , I.CARTEIRA  
 , I.DOCUMENTO  
 , I.LANC_CRED
 , AY2.EVENTO_NUM AS EVENTO_NUM_LANC_CRED
 , ISNULL(AY2.EVENTO_DESCR,'') AS EVENTO_DESCR_LANC_CRED   
 , AY2.DATACONTAB AS DATACONTAB_LANC_CRED   
 , I.DATA_PAGAMENTO  
 , I.TIPO_PAGAMENTO  
 , I.DETALHAMENTO_CREDITO  
 , I.OBSERVACAO  
 , I.USUARIO  
 , I.DESCRICAO_LANC_CREDITO  
 , I.VALOR_MULTA  
 , I.VALOR_JUROS_TOTAL  
 , I.VALOR_PAGO  
 , I.VALOR_DESCONTO  
 , I.VALOR_ACORDADO  
 , I.DATA_ACORDO  
 , I.VALOR_FINAL  
 , I.ESTORNO  
 , I.DATA_ESTORNO  
 , I.MENSAGEM_OBS  
 , I.RPS  
 , I.NFE  
 , I.DATA_ENVIO_RPS  
 , I.EH_SALDO  
 , I.CONTRATO_QTDEPARCELAS  
 , I.CONTRATO_ANOINICIO  
 , I.CONTRATO_MESINICIO  
 , I.CONTRATO_MESINICIO_AGERAR  
 , I.CONTRATO_QTDEPARCELAS_AGERAR  
 , I.CONTA_FINANCEIRA  
 , I.CENTRO_CUSTO  
 , I.FLAG_RESP_PLANO_PAGAMENTO  
 , I.CODIGO_ALUNO_VIRTUAL  
 , I.CODIGO_MENSALIDADE_VIRTUAL  
 , I.CODIGO_CONTRATO_VIRTUAL  
 , I.AGE_IN_CODIGO  
 , I.CODIGO_MENSALIDADE_ACORDO  
 , I.MIGRAR  
 , I.VALOR_ITEM_ADICIONAL  
 , I.DESCRICAO_ITEM_ADICIONAL  
 , I.VALOR_ACERTO  
 , I.TIPO_ACERTO  
 , I.ADIANTAMENTO  
FROM  migracao..tbl_financeiro I  
left join (SELECT COBRANCA, evento_num, evento_descr, DATACONTAB from AY_RESUMO_ATO WHERE TIPODOC = 'CB' AND ANO_REF = 2016) AY  ON AY.COBRANCA  = I.COBRANCA
left join (SELECT LANC_CRED, EVENTO_NUM, EVENTO_DESCR, DATACONTAB from AY_RESUMO_ATO WHERE TIPODOC = 'PG' AND ANO_REF = 2016) AY2  ON AY2.LANC_CRED  = I.LANC_CRED
WHERE I.migrar = 'S' 
AND I.ANO = 2016 
ORDER BY I.ALUNO, I.ANO, I.MES