SELECT	DISTINCT
		A.SERIE
		, A.ALUNO
		, P.PESSOA
		, P.CPF
		, P.NOME_COMPL
		, [DBO].[FN_FTC_MATRICULA_SERIADA_SELEC_TURMAS](A.ALUNO,2021,1) AS 'DESBLOQUEADO E COM DIVIDA PRE-MATRICULA'
		, IIF((LYCEUMINTEGRACAO.DBO.FN_FTC_ALUNO_PAGO ( A.ALUNO, ( select TOP 1 LANC_DEB from LYCEUM..LY_PRE_MATRICULA where  ANO = 2021 AND SEMESTRE = 1 AND aluno = A.ALUNO ) ) = 1), 'S', 'N') AS 'BOLSA, FIES, PROUNI OU STATUS PAGO'
		, IIF((SELECT TOP 1 1 FROM LYCEUMINTEGRACAO..FTC_SELECAO_TURMAS WHERE ALUNO = A.ALUNO AND ANO = 2021 AND SEMESTRE = 1) = 1, 'S', 'N') AS 'REALIZOU SELECAO TURMAS 2021'
		, IIF((SELECT TOP 1 1 FROM LYCEUMINTEGRACAO..FTC_SELECAO_TURMAS WHERE ALUNO = A.ALUNO AND ANO = 2021 AND SEMESTRE = 1) = 1, ISNULL((SELECT TOP 1 REPLACE(RTRIM(LTRIM(RIGHT(TURMA, 3))), '_', '') FROM LYCEUMINTEGRACAO..FTC_SELECAO_TURMAS WHERE ALUNO = A.ALUNO AND ANO = 2021 AND SEMESTRE = 1 AND RIGHT(TURMA, 3) LIKE '%T%'), 'VERIFICAR'), '-') AS 'GRUPO ESCOLHIDO'
		, IIF((SELECT TOP 1 1 FROM LYCEUMINTEGRACAO..FTC_SELECAO_TURMAS WHERE ALUNO = A.ALUNO AND ANO = 2021 AND SEMESTRE = 1) = 1, ISNULL((SELECT TOP 1 FORMAT([DATA], 'dd/MM/yyyy HH:mm') FROM LYCEUMINTEGRACAO..FTC_SELECAO_TURMAS WHERE ALUNO = A.ALUNO AND ANO = 2021 AND SEMESTRE = 1), 'VERIFICAR'), '-') AS 'DATA SELEÇÃO'
		, IIF((SELECT TOP 1 1 FROM LYCEUM..LY_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2021 AND SEMESTRE = 1 AND SIT_MATRICULA = 'Matriculado') = 1, 'S', 'N') AS 'EXISTE MATRICULA LYCEUM 2021'
FROM	LYCEUM..LY_ALUNO AS A
		INNER JOIN LYCEUM..LY_PESSOA P
			ON P.PESSOA = A.PESSOA
WHERE	1 = 1     --AND P.PESSOA = 183961
		--and a.aluno = '202041423'
        ------------------------------------------------- MEDICINA        
        AND A.CURSO = '722'        
        ------------------------------------------------- ATIVOS        
        AND A.SIT_ALUNO = 'Ativo'        
ORDER BY A.SERIE, P.NOME_COMPL