USE FTC_DATAMART
GO

--EXEC BI_RITMO_MATRICULA_JOB 2020,1
--DROP TABLE BI_RITMO_MATRICULA
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.BI_RITMO_MATRICULA_JOB'))
   exec('CREATE PROCEDURE [dbo].[BI_RITMO_MATRICULA_JOB] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.BI_DMP_JOB
(				
  @p_ano VARCHAR(4)      
, @p_semestre VARCHAR(2)      

)            
AS            
-- [INÍCIO]                    
BEGIN  


SELECT	CONCAT(ANO,'/',SEMESTRE) AS PERIODO_LETIVO, 
		UNIDADE_ENSINO_ALUNO, 
		NOME_CURSO,
		TIPO_ALUNO,
		TIPO_FINAN,
		DAY(CONVERT(DATETIME,DATA_MATRICULA,103)) DIA, 
		MONTH(CONVERT(DATETIME,DATA_MATRICULA,103)) MES, 
		YEAR(CONVERT(DATETIME,DATA_MATRICULA,103)) ANO, 
		COUNT(ALUNO) MATRICULADOS
FROM BI_REMATRICULA
WHERE 1=1--ANO IN (2019,2020) AND SEMESTRE = 1
--AND TIPO_FINAN IN ('FIES','PAGANTES')
--AND TIPO_CURSO IN ('GRADUACAO','TECNOLOGO')
--AND TIPO_INGRESSO NOT IN ('TransferenciaInterna','Ouvinte')
--AND SIT_MATRICULA IN ('MATRICULADO','PRE-MATRIC')
--AND TIPO_ALUNO IN ('CALOURO','REINGRESSO','CALOURO-CONCLUINTE','REINGRESSO-CONCLUINTE')
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NAO-PAGO','CONCLUIDO')
AND PAGO = 1
GROUP BY CONCAT(ANO,'/',SEMESTRE), UNIDADE_ENSINO_ALUNO, NOME_CURSO,TIPO_ALUNO,TIPO_FINAN,DAY(CONVERT(DATETIME,DATA_MATRICULA,103)),MONTH(CONVERT(DATETIME,DATA_MATRICULA,103)),YEAR(CONVERT(DATETIME,DATA_MATRICULA,103)) 
ORDER BY CONCAT(ANO,'/',SEMESTRE), UNIDADE_ENSINO_ALUNO, NOME_CURSO, YEAR(CONVERT(DATETIME,DATA_MATRICULA,103)),MONTH(CONVERT(DATETIME,DATA_MATRICULA,103)),DAY(CONVERT(DATETIME,DATA_MATRICULA,103))


END