USE LYCEUM

GO

--Consulta Valor Líquido de uma cobrança

SELECT SUM(VALOR) FROM LY_ITEM_LANC 
Where Cobranca = 4987593
AND (CODIGO_LANC <> 'Acerto' 
OR (CODIGO_LANC = 'Acerto' 
 AND VALOR > 0 
 AND ACORDO IS NULL 
 AND COBRANCA_ORIG IS NULL 
 AND DEVOLUCAO IS NULL 
 AND ITEMCOBRANCA_ORIG IS NULL))

 