SELECT DISTINCT A.UNIDADE_FISICA, VW.nome_comp, A.CURSO, C.NOME, A.ALUNO, A.NOME_COMPL,HCC.MOTIVO, CONCAT(HCC.ANO_ENCERRAMENTO,HCC.SEM_ENCERRAMENTO) AS PERIODO_ENCERRAMENTO, X.PERIODO_LETIVO AS PERIODO_HISTORICO
FROM LY_H_CURSOS_CONCL HCC
JOIN LY_ALUNO A ON A.ALUNO = HCC.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN VW_UNIDADES VW ON VW.faculdade = A.UNIDADE_FISICA AND VW.fisica = 'S'
JOIN (SELECT HM.ALUNO, MAX(CONCAT(HM.ANO,HM.SEMESTRE)) AS PERIODO_LETIVO FROM LY_HISTMATRICULA HM GROUP BY HM.ALUNO) X  ON HCC.ALUNO = X.ALUNO
WHERE X.PERIODO_LETIVO > CONCAT(HCC.ANO_ENCERRAMENTO,HCC.SEM_ENCERRAMENTO)
AND HCC.DT_REABERTURA IS NULL
AND X.PERIODO_LETIVO >= '20172' AND LEN(X.PERIODO_LETIVO) = 5

--GROUP BY X.PERIODO_LETIVO ORDER BY  2
