USE FTC_DATAMART
GO

DROP TABLE #TEMP

SELECT ALUNO, 'N' CONTRATO_ACEITO, '01/01/1900' AS DATA_ACEITE, 'N' AS ENTURMADO INTO #TEMP FROM BI_REMATRICULA
WHERE ANO = 2020
AND SEMESTRE = 1

UPDATE T SET T.CONTRATO_ACEITO = ISNULL(CA.CONTRATO_ACEITO,'X'), T.DATA_ACEITE = ISNULL(CONVERT(VARCHAR(10),CA.DATA_ACEITE,103),'01/01/1900')
FROM #TEMP T
LEFT JOIN LYCEUM..LY_CONTRATO_ALUNO CA ON CA.ALUNO = T.ALUNO AND CA.ANO = 2020 AND  CA.PERIODO = 1

UPDATE T SET T.ENTURMADO = 'S'
FROM #TEMP T
WHERE EXISTS (SELECT TOP 1 1
			FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW WHERE VW.ALUNO = T.ALUNO AND VW.ANO = 2020 AND VW.SEMESTRE = 1 
			AND VW.TURMA IS NOT NULL AND VW.TURMA <> '')

SELECT * FROM #TEMP