DECLARE 
	@p_ano VARCHAR(4),
	@p_semestre VARCHAR(2)

SET	@p_ano = '2018'
SET	@p_semestre = '1'


    SELECT    
  T.ANO
  ,T.SEMESTRE
  ,ISNULL (D.NUM_FUNC,'')        AS NUM_FUNC  
  ,ISNULL (D.NOME_COMPL,'')    AS NOME_COMPL 
  ,ISNULL (D.CPF,'') AS CPF
  ,ISNULL (T.CURSO,'') AS CURSO
  ,ISNULL (C.NOME,'') AS NOME_CURSO
  ,ISNULL (T.TURNO,'') AS TURNO
  ,ISNULL (T.CURRICULO,'') AS CURRICULO
  ,T.SERIE 
  ,T.SIT_TURMA
  ,ISNULL (T.TURMA,'')     AS TURMA  
  ,ISNULL (T.DISCIPLINA,'')    AS DISCIPLINA  
  ,DI.NOME_COMPL AS  NOME_DISCIPLINA
  ,ISNULL (T.ANO,'')      AS ANO  
  ,ISNULL (T.SEMESTRE,'')     AS SEMESTRE  
  ,ISNULL (T.FACULDADE,'')    AS FACULDADE  
  ,DI.AULAS_SEMANAIS      AS CH_SEMANAL
  ,AD.DIA_SEMANA
  ,CONVERT(VARCHAR(05),HORAINI_AULA,108) AS HORARIO_AULA 
  ,ISNULL((SELECT COUNT(*) 
			FROM VW_MATRICULA_E_PRE_MATRICULA M 
			WHERE M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE AND M.SIT_MATRICULA NOT IN ('Cancelado','Trancado')
			)+(
			SELECT COUNT(*) 
			FROM LY_HISTMATRICULA M 
			WHERE M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE AND M.SITUACAO_HIST NOT IN ('Cancelado','Trancado')
			),0) AS QTD_ALUNOS
  --,ISNULL(TD.OBSERVACAO,'') AS OBS_DOCENTE_TURMA
  FROM LY_TURMA T
   INNER JOIN LY_DOCENTE D  ON D.NUM_FUNC  = T.NUM_FUNC
   --INNER JOIN LY_TURMA_DOCENTE TD ON TD.NUM_FUNC = D.NUM_FUNC AND TD.DISCIPLINA = T.DISCIPLINA AND TD.TURMA = T.TURMA AND TD.ANO = T.ANO AND TD.PERIODO = T.SEMESTRE  
   INNER JOIN LY_DISCIPLINA DI ON DI.DISCIPLINA = T.DISCIPLINA 
   LEFT JOIN LY_CURSO C ON C.CURSO = T.CURSO
   LEFT JOIN LY_AULA_DOCENTE AD ON AD.TURMA = T.TURMA AND AD.TURNO = T.TURNO AND AD.DISCIPLINA = T.DISCIPLINA AND AD.ANO = T.ANO AND AD.SEMESTRE = T.SEMESTRE
   LEFT JOIN LY_HOR_OPER HO ON HO.AULA = AD.AULA AND HO.DIA_SEMANA = AD.DIA_SEMANA AND HO.TURNO = AD.TURNO AND HO.FACULDADE = AD.FACULDADE
  WHERE 1=1
AND (@P_ANO IS NOT NULL AND ISNULL(T.ANO,@P_ANO) = @P_ANO)
AND (@P_SEMESTRE IS NOT NULL AND ISNULL(T.SEMESTRE,@P_SEMESTRE) = @P_SEMESTRE)
--AND (@P_FACULDADE IS NOT NULL AND C.FACULDADE = @P_FACULDADE)
--AND (@P_TIPO_CURSO IS NOT NULL AND C.TIPO = @P_TIPO_CURSO)  
--AND ((@P_CURSO IS NOT NULL AND C.CURSO = @P_CURSO) OR @P_CURSO IS NULL)
--AND ((@P_TURNO IS NOT NULL AND T.TURNO = @P_TURNO) OR @P_TURNO IS NULL)
--AND ((@P_DOCENTE IS NOT NULL AND AD.NUM_FUNC = @P_DOCENTE) OR @P_DOCENTE IS NULL)  
 
ORDER BY 1,2,4,3   