USE LYCEUM
GO

SELECT C.FACULDADE, UF.NOME_COMP AS NOME_UNIDADE, A.CURSO, C.NOME AS NOME_CURSO, A.ALUNO, A.NOME_COMPL AS NOME_ALUNO , HM.ANO, HM.SEMESTRE, D.DISCIPLINA, D.NOME AS NOME_DISCIPLINA, HM.NOTA_FINAL, HM.SITUACAO_HIST, ISNULL(HM.OBSERVACAO,'') AS OBSERVACAO
FROM LY_HISTMATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
WHERE 1=1
AND A.SIT_ALUNO = 'Ativo' AND EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2017' AND SEMESTRE = '2')
AND C.FACULDADE = '29'
ORDER BY C.FACULDADE, C.CURSO, HM.ANO, HM.SEMESTRE, A.ALUNO