SELECT A.UNIDADE_FISICA,P.NOME_COMPL, ISNULL(P.DDD_FONE_CELULAR,'') AS DDD_CELULAR,ISNULL(P.CELULAR,'') AS CELULAR,ISNULL(P.E_MAIL,'') AS EMAIL FROM LY_PESSOA P, LY_ALUNO A
WHERE P.PESSOA = A.PESSOA AND A.SIT_ALUNO = 'Ativo'
AND A.UNIDADE_FISICA IN ('FCS')