USE [master]
GO

CREATE LOGIN [fsalmeida] WITH PASSWORD=N'ftc!2020' MUST_CHANGE, DEFAULT_DATABASE=[UNIFTC_ONE], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
ALTER LOGIN [fsalmeida] with DEFAULT_DATABASE = [TOPDESK_PROD]
GO

USE [TOPDESK_PROD]
GO
CREATE USER [fsalmeida] FOR LOGIN [fsalmeida]
GO

GRANT SELECT ON Change TO [fsalmeida]
GRANT SELECT ON wijzigingstatus TO [fsalmeida]