USE FTC_DATAMART
GO

		DECLARE  @p_ano VARCHAR(4), @p_semestre VARCHAR(2)
		DECLARE cursor1 CURSOR FOR
		SELECT DISTINCT ANO, SEMESTRE  FROM BI_REMATRICULA
		ORDER BY ANO, SEMESTRE

		OPEN cursor1

		FETCH NEXT FROM cursor1 INTO @p_ano, @p_semestre

		WHILE @@FETCH_STATUS = 0
		BEGIN
			
		EXEC BI_REMATRICULA_JOB @p_ano, @p_semestre

		FETCH NEXT FROM cursor1 INTO @p_ano, @p_semestre
		END
		CLOSE cursor1
		DEALLOCATE cursor1

		EXEC BI_ACOMP_MATR_POS_JOB

		EXEC BI_ACOMP_MATR_JOB 2019,0

		EXEC BI_ACOMP_MATR_JOB 2019,1
