--SELECT 
--	C.UNID_FISICA
--	,CUR.CURSO
--	,CUR.NOME
--	,C.ANO ANO_REF
--	,C.MES MES_REF
--	,IL.COBRANCA
--	,C.DATA_DE_GERACAO	
--	,C.DATA_DE_FATURAMENTO
--	,C.DATA_DE_VENCIMENTO
--	,CONVERT(NUMERIC(10,2),IL.VALOR)*-1 VALOR
--FROM LY_ITEM_LANC IL
SELECT C.UNID_FISICA,C.ANO, C.MES,CONCAT('R$',CONVERT(NUMERIC(10,2),SUM(IL.VALOR))*-1) VALOR FROM LY_ITEM_LANC IL
JOIN LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = C.UNID_FISICA
JOIN LY_CURSO CUR ON CUR.CURSO = C.CURSO
WHERE 1=1
AND IL.DT_ENVIO_CONTAB IS NULL
AND IL.ITEM_ESTORNADO IS NULL
AND IL.NUM_BOLSA IS NOT NULL
AND C.ESTORNO = 'N'
AND C.ANO = 2018 AND C.MES < 4
AND NOT EXISTS (SELECT TOP 1 1 FROM AY_RESUMO_ATO WHERE COBRANCA = IL.COBRANCA AND NUM_BOLSA = IL.NUM_BOLSA AND LANC_DEB = IL.LANC_DEB )
AND C.DATA_DE_VENCIMENTO <= '2018-03-31'
GROUP BY C.ANO, C.MES,C.UNID_FISICA
ORDER BY 1,2,4,5