DISABLE TRIGGER CRO_Ly_Histmatricula_Update ON LY_HISTMATRICULA
GO

UPDATE HM SET HM.DISCIPLINA = UPPER(HM.DISCIPLINA)
FROM LY_HISTMATRICULA HM WHERE HM.ALUNO = '171030451'
--147988 OU SPR406 OU 149648 OU SPR470

ENABLE TRIGGER CRO_Ly_Histmatricula_Update ON LY_HISTMATRICULA
GO
