USE LYCEUM
GO

/*
DISABLE TRIGGER CRO_Ly_Pessoa_Update ON LY_PESSOA
GO

UPDATE LY_PESSOA SET SENHA_TAC = dbo.Crypt('FTC2018')

ENABLE TRIGGER CRO_Ly_Pessoa_Update ON LY_PESSOA
GO

*/

DISABLE TRIGGER CRO_Ly_Docente_Update ON LY_DOCENTE
GO

UPDATE LY_DOCENTE SET SENHA_DOL = dbo.Crypt('FTC2018')

ENABLE TRIGGER CRO_Ly_Docente_Update ON LY_DOCENTE
GO
