SELECT 
CONCAT(LTRIM(RTRIM(D.NOME)),'-',LTRIM(RTRIM(DO.NOME_COMPL)),'-',LTRIM(RTRIM(T.TURMA))) AS NOME_SALA_EADBOX,
P.CPF AS document_id,
P.NOME_COMPL AS name,
P.E_MAIL As email,
'' as tags,
'' as biography,
'' as cover_color,
CONCAT(P.DDD_FONE_CELULAR,P.CELULAR) as mobile_phone,
CONCAT(P.DDD_FONE,P.FONE) as home_phone,
'' as profession,
P.ENDERECO as street,
P.END_NUM as number,
isnull(P.END_COMPL,'') as complement,
P.BAIRRO as neighborhood,
P.CEP as zip,
H.UF as state,
P.CPF as password,
'' as teams,
a.aluno as matricula
FROM LYCEUM..LY_TURMA T 
INNER JOIN LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW ON VW.DISCIPLINA = T.DISCIPLINA AND VW.TURMA = T.TURMA AND VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE
INNER JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = VW.ALUNO
INNER JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
INNER JOIN LYCEUM..HD_MUNICIPIO H ON H.MUNICIPIO = P.END_MUNICIPIO
INNER JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA=T.DISCIPLINA
INNER JOIN LYCEUM..LY_CURSO C ON C.CURSO =T.CURSO
INNER JOIN LYCEUM..LY_DOCENTE DO ON DO.NUM_FUNC = T.NUM_FUNC
WHERE 1 =1
AND T.ANO =2018
AND T.SEMESTRE =1
AND T.NIVEL ='TEORICA'
AND T.DISCIPLINA IN ('EPR521','DIR502','SPR407')
AND T.FACULDADE IN ('FCS','FTC-FSA')
AND T.CURSO IN ('2212','3205','90','975','899','789','2555','2054','376','3178','2255','2262','446','980','2431','2553')

UNION

SELECT 
CONCAT(LTRIM(RTRIM(D.NOME)),'-',LTRIM(RTRIM(DO.NOME_COMPL)),'-',LTRIM(RTRIM(T.TURMA))) AS NOME_SALA_EADBOX,
P.CPF AS document_id,
P.NOME_COMPL AS name,
P.E_MAIL As email,
'' as tags,
'' as biography,
'' as cover_color,
CONCAT(P.DDD_FONE_CELULAR,P.CELULAR) as mobile_phone,
CONCAT(P.DDD_FONE,P.FONE) as home_phone,
'' as profession,
P.ENDERECO as street,
P.END_NUM as number,
isnull(P.END_COMPL,'') as complement,
P.BAIRRO as neighborhood,
P.CEP as zip,
H.UF as state,
P.CPF as password,
'' as teams,
a.aluno as matricula
FROM LYCEUM..LY_TURMA T 
INNER JOIN LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW ON VW.DISCIPLINA = T.DISCIPLINA AND VW.TURMA = T.TURMA AND VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE
INNER JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = VW.ALUNO
INNER JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
INNER JOIN LYCEUM..HD_MUNICIPIO H ON H.MUNICIPIO = P.END_MUNICIPIO
INNER JOIN LYCEUM..LY_DISCIPLINA D ON D.DISCIPLINA=T.DISCIPLINA
INNER JOIN LYCEUM..LY_DOCENTE DO ON DO.NUM_FUNC = T.NUM_FUNC
WHERE 1 =1
AND T.ANO =2018
AND T.SEMESTRE =1
AND T.NIVEL ='TEORICA'
AND T.DISCIPLINA IN ('SPR407')
AND T.FACULDADE IN ('FCS','FTC-FSA')

order by 1