SELECT DISTINCT G.CURSO, G.CURRICULO, G.SERIE_IDEAL ,D.DISCIPLINA, D.NOME
  FROM LY_GRADE G
JOIN LY_ALUNO A ON A.CURSO = G.CURSO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = G.DISCIPLINA
JOIN VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = A.ALUNO
JOIN LY_TURMA T ON T.DISCIPLINA = VW.DISCIPLINA
WHERE 1=1
AND A.CURSO = '722'
AND A.SIT_ALUNO = 'Ativo'
AND VW.ANO = '2017'
AND VW.SEMESTRE = '1'
ORDER BY 2,3