--Caique Iure Teles Ferreira
--Valor total das dividas no Lyceum diverge com o virtual
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Caique Iure Teles Ferreira%'
SELECT SUM(valor_bruto) FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152' AND DATA_ESTORNO IS NULL AND VALOR_FINAL >= 0
SELECT * FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152' AND DATA_ESTORNO IS NULL AND VALOR_FINAL = 0
SELECT * FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152' AND DATA_ESTORNO IS NULL

SELECT * FROM LY_COBRANCA WHERE ALUNO = '121070691' AND ANO = 2015 AND MES BETWEEN 7 AND 12
SELECT * FROM LY_LANC_DEBITO WHERE ALUNO = '121070691' AND ANO_REF = '2015' AND PERIODO_REF = '2'
SELECT * from VIRTUALCLASS..TBL_FINANCEIRO where CODIGO_ALUNO_VIRTUAL=805408 and PERIODO_LETIVO='20152'and DATA_ESTORNO IS NULL

SELECT VALOR,* FROM LY_LANC_DEBITO WHERE ALUNO = '121070691' AND ANO_REF = '2015' AND PERIODO_REF = '2' ORDER BY 1
SELECT SUM(VALOR_BRUTO) from VIRTUALCLASS..TBL_FINANCEIRO where CODIGO_ALUNO_VIRTUAL=805408 and PERIODO_LETIVO='20152'


--Rodrigo Calasans de Santana Almeida(FORMADOS) 
--Possui 2 ingressos em 2013.2 no virtual, também tem evasão no Virtual
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Rodrigo%Calasans%Santana%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '111070010'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '092070413'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Rodrigo%Calasans%Santana%'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '131701'
SELECT * FROM VIRTUALCLASS..TBL_ENADE WHERE ALUNO = '131701'


