USE LYCEUM
GO

SELECT  DISTINCT
		UE.UNIDADE_ENS
		, UE.NOME_COMP
		, C.TIPO
		, C.CURSO
		, C.NOME
		, P.CPF AS CPF_ALUNO
		, A.ALUNO
		, A.NOME_COMPL AS NOME_ALUNO
		, PPP.PLANOPAG
		, PPP.RESP AS CPF_RESP
		, PPP.NUM_PARCELAS
		, LD.VALOR AS VALOR_DIVIDA_TOTAL
		, LD.VALOR/PPP.NUM_PARCELAS AS VALOR_MENSALIDADE
FROM VW_MATRICULA_E_PRE_MATRICULA VW
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = VW.LANC_DEB
JOIN LY_PLANO_PGTO_PERIODO PPP ON PPP.ALUNO = A.ALUNO AND PPP.ANO = VW.ANO AND PPP.PERIODO = VW.SEMESTRE
WHERE VW.ANO = 2019 AND VW.SEMESTRE = 1
AND (EXISTS (SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = 2019
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = 1
				AND LD.ALUNO = VW.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB'))
OR EXISTS 	(SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = VW.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOINI >= (SELECT YEAR(DT_INICIO) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = 2019 AND PERIODO = 1))
					AND (B.MESINI = CASE WHEN '1' IN ('1','11') THEN 1 WHEN '2' IN ('2','22') THEN 7 ELSE 1 END))
OR EXISTS (SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = VW.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL))
ORDER BY 1,4