/*
SELECT DISTINCT T.DISCIPLINA,T.NUM_FUNC, T.TURMA, T.ANO, T.SEMESTRE 
FROM LY_TURMA T, LY_CURSO C, LY_COORDENACAO CO, LY_MATRICULA M  
WHERE T.ANO = M.ANO  
AND T.SEMESTRE = M.SEMESTRE  
AND T.DISCIPLINA = M.DISCIPLINA  
AND T.TURMA = M.TURMA  
AND T.NUM_FUNC <> 1 
AND T.CURSO = C.CURSO
AND C.CURSO = CO.CURSO 
AND C.TIPO = 'GRADUACAO' 
AND CO.NUM_FUNC = '1638'

SELECT * FROM LY_DOCENTE WHERE NOME_COMPL LIKE '%paschoal%molin%'

*/
/*
SELECT DISTINCT CUR.FACULDADE+'-'+UE.NOME_COMP AS DISCIPLINA,C.NUM_FUNC, T.CURSO+'-'+CUR.NOME AS TURMA, T.ANO, T.SEMESTRE 
FROM LY_COORDENACAO C 
JOIN LY_DOCENTE D ON D.NUM_FUNC = C.NUM_FUNC  
JOIN LY_TURMA T ON T.CURSO = C.CURSO 
JOIN LY_CURSO CUR ON CUR.CURSO = T.CURSO  
JOIN LY_MATRICULA M ON M.TURMA = T.TURMA AND M.DISCIPLINA = T.DISCIPLINA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = CUR.FACULDADE
WHERE D.ATIVO = 'S'  
AND D.DT_DEMISSÃO IS NULL 
AND CUR.TIPO IN ('GRADUACAO','TECNOLOGO')  
AND T.NUM_FUNC = '974'
*/

SELECT DISTINCT CUR.FACULDADE+'-'+UE.NOME_COMP AS DISCIPLINA,C.NUM_FUNC, A.CURSO+'-'+CUR.NOME AS TURMA, T.ANO, T.SEMESTRE 
FROM LY_COORDENACAO C 
JOIN LY_CURSO CUR ON CUR.CURSO = C.CURSO
JOIN LY_UNIDADE_ENSINO  UE ON UE.UNIDADE_ENS = CUR.FACULDADE
JOIN LY_ALUNO A ON A.CURSO = CUR.CURSO
JOIN LY_MATRICULA M ON M.ALUNO = A.ALUNO
LEFT JOIN LY_TURMA T ON T.DISCIPLINA = M.DISCIPLINA AND T.TURMA = M.TURMA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE
WHERE CUR.TIPO IN ('GRADUACAO','TECNOLOGO') AND M.ALUNO = '011040391'

SELECT CURSO, * FROM LY_ALUNO WHERE ALUNO = '142070055'

SELECT A.ALUNO, T.CURSO, A.CURSO FROM LY_MATRICULA M
JOIN LY_TURMA T ON T.DISCIPLINA = M.DISCIPLINA AND T.TURMA = M.TURMA AND T.ANO = M.ANO AND T.SEMESTRE = M.SEMESTRE
JOIN LY_ALUNO A ON A.ALUNO = M.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE T.CURSO <> A.CURSO
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')

SELECT * FROM LY_MATRICULA lm WHERE lm.ALUNO = '142070055'

SELECT * FROM LY_TURMA 
WHERE TURMA = '04_EME9AN'
AND DISCIPLINA = '146627'
AND ANO = '2017'
AND SEMESTRE = '1'

SELECT * FROM LY_COORDENACAO lc WHERE lc.NUM_FUNC = '1864'


SELECT DISTINCT C.NUM_FUNC 
FROM LY_COORDENACAO C 
JOIN LY_DOCENTE D ON D.NUM_FUNC = C.NUM_FUNC  
JOIN LY_TURMA T ON T.CURSO = C.CURSO 
JOIN LY_CURSO CUR ON CUR.CURSO = T.CURSO
JOIN LY_MATRICULA M ON M.ANO = T.ANO AND m.SEMESTRE = T.SEMESTRE AND M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA
WHERE D.ATIVO = 'S'  
AND D.DT_DEMISSÃO IS NULL 
AND CUR.TIPO IN ('GRADUACAO','TECNOLOGO')  
AND T.NUM_FUNC = '974'

SELECT DISTINCT T.* 
FROM LY_COORDENACAO C 
JOIN LY_DOCENTE D ON D.NUM_FUNC = C.NUM_FUNC  
JOIN LY_TURMA T ON T.CURSO = C.CURSO 
JOIN LY_CURSO CUR ON CUR.CURSO = T.CURSO
JOIN LY_MATRICULA M ON M.ANO = T.ANO AND m.SEMESTRE = T.SEMESTRE AND M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA
WHERE D.ATIVO = 'S'  
AND D.DT_DEMISSÃO IS NULL 
AND CUR.TIPO IN ('GRADUACAO','TECNOLOGO')  
AND T.NUM_FUNC = '974'

SELECT * FROM LY_COORDENACAO lc WHERE lc.CURSO IN ('2093','27','294')


SELECT DISTINCT CO.NUM_FUNC 
FROM LY_ALUNO A, LY_MATRICULA M, LY_CURSO C, LY_COORDENACAO CO, LY_DOCENTE D  
WHERE A.ALUNO = M.ALUNO 
AND D.NUM_FUNC = CO.NUM_FUNC
AND C.CURSO = A.CURSO 
AND CO.NUM_FUNC <> 1 
AND CO.CURSO = C.CURSO 
AND D.DT_DEMISSAO IS NULL
AND D.ATIVO = 'S'
AND C.TIPO IN ('GRADUACAO','TECNOLOGO') 
AND M.ALUNO = '%%CHAVE1'


SELECT * FROM LY_COORDENACAO C
WHERE NOT EXISTS (SELECT * FROM LY_TURMA T WHERE T.NUM_FUNC = C.NUM_FUNC)

--502
SELECT * FROM LY_COORDENACAO lc WHERE lc.NUM_FUNC = '1638'
SELECT * FROM LY_COORDENACAO lc WHERE lc.CURSO = '502'
SELECT * FROM LY_DOCENTE ld WHERE ld.NUM_FUNC = '1687'
SELECT * FROM LY_DOCENTE ld WHERE ld.NOME_COMPL LIKE '%luciene%lessa%'

SELECT * FROM LY_TURMA WHERE NUM_FUNC = '1638'


SELECT * FROM LY_TURMA WHERE CURSO = '502' AND ANO = 2017 AND SEMESTRE = 1
SELECT * FROM LY_TURMA WHERE TURMA LIKE '04_BMD%' AND ANO = 2017 AND SEMESTRE = 1



SELECT * FROM ly_curso WHERE nome LIKE '%farmacia%'
SELECT * FROM ly_curso WHERE CURSO = '3242'

SELECT * FROM LY_CURSO WHERE CURSO IN (SELECT CURSO FROM LY_COORDENACAO lc WHERE lc.NUM_FUNC = '1687')


SELECT * FROM ly_aluno WHERE NOME_COMPL LIKE '%sheila%macedo%'