--DESCRIÇÃO DA COBRANCA
SELECT * FROM LY_COBRANCA WHERE COBRANCA = '54531'
--RESUMO DE SALDO DA COBRANCA, COM MAIS "DADOS CHAVE"
SELECT * FROM VW_COBRANCA WHERE COBRANCA = '54531'
--LANÇAMENTOS DE DÍVIDA (PODE CONTER BOLSAS, ESTORNOS DE DÍVIDA E LANÇAMENTOS DAS PARCELAS)
SELECT * FROM LY_ITEM_LANC WHERE COBRANCA = '54531'
SELECT sum(VALOR) FROM LY_ITEM_LANC WHERE COBRANCA = '54531'
--DESCRIÇÃO DA DÍVIDA
select * FROM LY_LANC_DEBITO WHERE LANC_DEB = '4635596'
--PLANO DE PAGAMENTO DO ALUNO, ONDE CONSTA A FORMA COMO A DÍVIDA SERÁ PAGA (QUANTIDADE DE PARCELAS, PERCENTUAL DA DÍVIDA QUE O RESPONSÁVEL FINANCEIRO IRÁ PAGAR)
select * FROM LY_PLANO_PGTO_PERIODO WHERE ALUNO = '162060070' AND ANO = '2016' AND PERIODO = '2'
--LANÇAMENTOS DE PAGAMENTOS, ENCARGOS (JUROS, MULTA, PERDEBOLSA)
select * FROM LY_ITEM_CRED WHERE COBRANCA = '54531'
--DESCRICAO DO PAGAMENTO (FORMA DE PAGAMENTO, DADOS DE CHEQUE, CARTAO, ETC)
select * FROM LY_LANC_CREDITO WHERE LANC_CRED = '40401'