USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_SomatorioDividasPeriodoLetivo'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_SomatorioDividasPeriodoLetivo] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.FTC_Relat_SomatorioDividasPeriodoLetivo
(      
	 @p_ano VARCHAR(4)
	,@p_semestre VARCHAR(2)
	,@p_unidade VARCHAR(30)  
	,@p_curso VARCHAR(30)  
)      
AS      

--EXEC FTC_Relat_SomatorioDividasPeriodoLetivo 2018,0,'50',NULL
-- [INÍCIO]              
BEGIN      
  
SET NOCOUNT ON  
  
 SELECT DISTINCT
 SUM(LD.VALOR) AS VALOR
,LD.ALUNO
,ISNULL(P.CPF,'') AS CPF_ALUNO
,PPP.RESP AS CPF_RESP
,C.CURSO
,C.NOME AS NOME_CURSO
,LD.ANO_REF
,LD.PERIODO_REF 
,C.FACULDADE
,UE.NOME_COMP
FROM  LY_LANC_DEBITO LD
INNER JOIN LY_ALUNO A ON A.ALUNO=LD.ALUNO
INNER JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
INNER JOIN LY_CURSO C ON C.CURSO =A.CURSO
INNER JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
INNER JOIN (SELECT DISTINCT ANO, SEMESTRE, ALUNO, LANC_DEB FROM VW_MATRICULA_E_PRE_MATRICULA ) X ON X.ALUNO = A.ALUNO AND X.LANC_DEB = LD.LANC_DEB AND X.ANO = LD.ANO_REF AND X.SEMESTRE = LD.PERIODO_REF
INNER JOIN LY_PLANO_PGTO_PERIODO PPP ON PPP.ALUNO = LD.ALUNO AND PPP.ANO = LD.ANO_REF AND PPP.PERIODO = LD.PERIODO_REF
WHERE 1=1
AND LD.CODIGO_LANC IN ('MS','MS_EB')
AND A.SIT_ALUNO <> 'Cancelado'
AND LD.ANO_REF = @p_ano AND LD.PERIODO_REF = @p_semestre
AND ((@p_curso IS NOT NULL AND C.CURSO = @p_curso) OR @p_curso IS NULL)
AND ((@p_unidade IS NOT NULL AND C.FACULDADE = @p_unidade) OR @p_unidade IS NULL)

GROUP BY LD.ALUNO,LD.ANO_REF,LD.PERIODO_REF,C.CURSO,C.NOME,C.FACULDADE,P.CPF,UE.NOME_COMP,PPP.RESP
ORDER  BY 9,5

SET NOCOUNT OFF
END
GO

delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_Relat_SomatorioDividasPeriodoLetivo'
and IDENTIFICACAO_CODIGO = '0001'
go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_Relat_SomatorioDividasPeriodoLetivo' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2018-08-15' DATA_CRIACAO
, 'Relatório de Somatório de Dívidas de Mensalidade de Alunos' OBJETIVO
, 'Ana Paula' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
go 


--SELECT SUM(VALOR) FROM LY_LANC_DEBITO WHERE ALUNO='011040916' AND ANO_REF='2016' AND PERIODO_REF='2'
--4233,60
--6309,36