SELECT DISTINCT
 A.ALUNO
,A.NOME_COMPL AS NOME_ALUNO
,P.CPF
,P.E_MAIL
,P.FONE
,A.CURRICULO
,A.CURSO
,A.TURNO
,A.SERIE
,A.UNIDADE_FISICA
,CONVERT(VARCHAR(10),A.DT_INGRESSO,103) AS DT_INGRESSO
,A.ANO_INGRESSO
,A.SEM_INGRESSO
,C.NOME AS NOME_CURSO
,((SELECT format(SUM(H.HORAS_AULA), '#') *100
FROM LY_HISTMATRICULA H 
WHERE 1=1
AND H.ALUNO=A.ALUNO
AND H.SITUACAO_HIST in ('Aprovado','Dispensado')
GROUP BY H.ALUNO) / (SELECT  format(CUR.AULAS_PREVISTAS, '#') AS CH_CURSO
FROM  LY_CURRICULO CUR
WHERE 1=1
AND CUR.CURRICULO =A.CURRICULO
AND CUR.CURSO=A.CURSO
AND CUR.TURNO=A.TURNO
AND CUR.AULAS_PREVISTAS>0) )AS PERCENTUAL_CURSADO
FROM  LY_ALUNO A
INNER JOIN LY_GRADE G ON G.CURRICULO = A.CURRICULO AND G.TURNO = A.TURNO AND G.CURSO = A.CURSO
INNER JOIN LY_CURSO C ON C.CURSO = A.CURSO
INNER JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
WHERE 1=1
AND A.SIT_ALUNO='Ativo'
AND A.UNIDADE_FISICA=CASE WHEN @UNIDADE IS NULL THEN A.UNIDADE_FISICA ELSE @UNIDADE END
AND A.CURSO=CASE WHEN @CURSO IS NULL THEN A.CURSO ELSE @CURSO END
AND EXISTS(
            SELECT  1 FROM LY_HISTMATRICULA HIST 
            WHERE HIST.ALUNO=A.ALUNO  
            AND HIST.ANO = CASE WHEN @ANO IS NULL THEN HIST.ANO ELSE @ANO END   --YEAR(GETDATE())-1 
            AND HIST.SEMESTRE = @SEMESTRE --IN ('1','2')
          )
GROUP BY A.ALUNO,A.NOME_COMPL,A.SERIE,A.CURSO,A.UNIDADE_FISICA,C.NOME,A.DT_INGRESSO,A.ANO_INGRESSO,A.CURRICULO,A.SEM_INGRESSO,A.TURNO,A.UNIDADE_FISICA,P.CPF,P.FONE,P.E_MAIL,A.TURNO
HAVING
((SELECT format(SUM(H.HORAS_AULA), '#') * 100
FROM LY_HISTMATRICULA H 
WHERE 1=1
AND H.ALUNO=A.ALUNO
AND H.SITUACAO_HIST in ('Aprovado','Dispensado')
GROUP BY H.ALUNO) / 
(SELECT  format(CUR.AULAS_PREVISTAS, '#') AS CH_CURSO
FROM  LY_CURRICULO CUR
WHERE 1=1
AND CUR.CURRICULO =A.CURRICULO
AND CUR.CURSO=A.CURSO
AND CUR.TURNO=A.TURNO
AND CUR.AULAS_PREVISTAS>0) ) BETWEEN 75 AND 100