IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_SP_csvPagamentoTitulos'))
   exec('CREATE PROCEDURE [dbo].[FTC_SP_csvPagamentoTitulos] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.FTC_SP_csvPagamentoTitulos
(      
  @P_ANO VARCHAR(20)
, @P_SEMESTRE VARCHAR(20)
, @P_FACULDADE VARCHAR(20)
, @P_TIPO_CURSO VARCHAR(20)  
, @P_CURSO  VARCHAR(20)  
, @P_TURNO  VARCHAR(20)  
, @P_CURRICULO VARCHAR(20)  
)      
AS      
-- [INÍCIO]              
BEGIN      
  
SET NOCOUNT ON  
  SELECT	DISTINCT
		VW.LANC_CRED						AS [PAGAMENTO],
		VW.COBRANCA							AS [COBRANCA],
		C.ESTORNO							AS [COBRANCA_ESTORNADA],
		VW.TIPO_PAGAMENTO					AS [TIPO_PAGAMENTO],
		VW.TIPO_CREDITO						AS [TIPO_CREDITO],
		C.UNID_FISICA						AS [UNIDADE_FISICA],
		CU.CURSO							AS [CURSO],
		CU.NOME								AS [NOME_CURSO],
		A.TURNO								AS [TURNO],
		A.CURRICULO							AS [CURRICULO],
		VW.ALUNO							AS [ALUNO], 
		VW.NOME_COMPLETO					AS [NOME_ALUNO],
		VW.RESP								AS [RESPONSAVEL_FINANCEIRO],
		VW.NOME_RESP						AS [NOME_RESPONSAVEL],
		CONVERT(VARCHAR(10),C.DATA_DE_VENCIMENTO,105)		AS [DATA_VENCIMENTO],
		CONVERT(VARCHAR(10),VW.DATA_CREDITO,105)			AS [DATA_PAGAMENTO],
		CONVERT(VARCHAR(10),LC.DATA,105)					AS [DATA_RECEBIMENTO],
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA AND IL.NUM_BOLSA IS NULL)																AS [VALOR_TITULO],
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA)																						AS [VALOR_FATURADO],
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC1 WHERE IC1.COBRANCA = VW.COBRANCA AND IC1.TIPO_ENCARGO = 'MULTA')														AS [MULTA],
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC4 WHERE IC4.COBRANCA = VW.COBRANCA AND IC4.TIPO_ENCARGO = 'PERDEBOLSA')												AS [PERDEBOLSA],
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC2 WHERE IC2.COBRANCA = VW.COBRANCA AND IC2.TIPO_ENCARGO = 'JUROS')														AS [JUROS],
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = VW.COBRANCA AND IC3.TIPODESCONTO IN ('Acréscimo','Concedido','DescBanco','PagtoAntecipado'))	AS [DESCONTO],
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = VW.COBRANCA AND IC3.TIPODESCONTO IS NULL AND IC3.TIPO_ENCARGO IS NULL)*-1						AS [VALOR_PAGO],
		CASE WHEN EXISTS (SELECT 1 FROM LY_MATRICULA M WHERE M.ANO = @P_ANO  AND M.SEMESTRE = @P_SEMESTRE AND M.ALUNO = A.ALUNO AND M.SIT_MATRICULA NOT IN ('Cancelado')) THEN 'Matriculado'
			 WHEN EXISTS (SELECT 1 FROM LY_MATRICULA M WHERE M.ANO = @P_ANO  AND M.SEMESTRE = @P_SEMESTRE AND M.ALUNO = A.ALUNO AND M.SIT_MATRICULA IN ('Cancelado')) THEN 'Cancelado'
			 WHEN EXISTS (SELECT 1 FROM LY_PRE_MATRICULA M WHERE M.ANO = @P_ANO  AND M.SEMESTRE = @P_SEMESTRE AND M.ALUNO = A.ALUNO) THEN 'Pré-Matriculado' ELSE 'Ingressado' END												AS [SIT_MATRICULA]
FROM VW_FLUXO_CAIXA_REL VW
JOIN LY_ITEM_CRED IC ON IC.LANC_CRED = VW.LANC_CRED
JOIN LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
JOIN LY_LANC_CREDITO LC ON LC.LANC_CRED = VW.LANC_CRED
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
JOIN LY_CURSO CU ON CU.CURSO = A.CURSO
WHERE 1 = 1
AND ((@P_ANO IS NOT NULL AND C.ANO = @P_ANO) OR @P_ANO IS NULL)
AND ((@P_SEMESTRE IS NOT NULL AND C.MES BETWEEN	(CASE WHEN @P_SEMESTRE = '1' THEN '1' ELSE '7' END) AND (CASE WHEN @P_SEMESTRE = '1' THEN '6' ELSE '12' END)) OR @P_SEMESTRE IS NULL)   
AND ((@P_FACULDADE IS NOT NULL AND CU.FACULDADE = @P_FACULDADE) OR @P_FACULDADE IS NULL) 
AND ((@P_TIPO_CURSO IS NOT NULL AND CU.TIPO = @P_TIPO_CURSO) OR @P_TIPO_CURSO IS NULL)  
AND ((@P_CURSO IS NOT NULL AND CU.CURSO = @P_CURSO) OR @P_CURSO IS NULL)
AND ((@P_TURNO IS NOT NULL AND A.TURNO = @P_TURNO) OR @P_TURNO IS NULL)  
AND ((@P_CURRICULO IS NOT NULL AND A.CURRICULO = @P_CURRICULO) OR @P_CURRICULO IS NULL)   
ORDER BY UNIDADE_FISICA,PAGAMENTO,COBRANCA 
  
--exec FTC_SP_csvPagamentoTitulos '2016','2', '04', 'GRADUACAO', '722', 'I', NULL  
SET NOCOUNT OFF  
  
END              
GO
-- [FIM]      



--##
--## PARAMETRIZAÇÃO/CADASTRO DA LISTA NO LYCEUM
--##

DECLARE @V_CONSULTA_DINAMICA INT
DECLARE @V_NOME_CONSULTA_DINAMICA varchar(100)

-- Colocar nome da lista (que será apresentada no combo)
set @V_NOME_CONSULTA_DINAMICA ='Custom - Pagamento de Títulos'

-- Consulta ID da Lista
SELECT @V_CONSULTA_DINAMICA = ID FROM LY_CONSULTA_DINAMICA WHERE TITULO = @V_NOME_CONSULTA_DINAMICA

-- armazena padrões de acesso
SELECT PADACES
INTO #TEMP_CONSULTA_DINAMICA
FROM LY_CONSULTA_DINAMICA_PADACES WHERE ID = @V_CONSULTA_DINAMICA


DELETE LY_CONSULTA_DINAMICA_PADACES WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA

BEGIN

IF NOT EXISTS(SELECT 1 FROM LY_CONSULTA_DINAMICA C WHERE C.TITULO = @V_NOME_CONSULTA_DINAMICA)
INSERT INTO LY_CONSULTA_DINAMICA(TITULO, TIPO, STORED_PROCEDURE)
VALUES(@V_NOME_CONSULTA_DINAMICA,'CSV','sp:FTC_SP_csvPagamentoTitulos(@P_ANO@,@P_SEMESTRE@,@P_FACULDADE@,@P_TIPO_CURSO@,@P_CURSO@,@P_TURNO@,@P_CURRICULO@)')

SET @V_CONSULTA_DINAMICA = @@IDENTITY

-- Insere padrões de acesso
INSERT INTO LY_CONSULTA_DINAMICA_PADACES (ID_CONSULTA_DINAMICA, PADACES)
SELECT @V_CONSULTA_DINAMICA, PADACES FROM #TEMP_CONSULTA_DINAMICA

-- Insere parametros

	--@p_ano			T_ANO,
	--@p_semestre		T_Semestre2,
	--@p_unidade_ensino	T_codigo,
	--@p_tipo_curso		T_codigo,
	--@p_curso			T_codigo,
	--@p_turno			T_codigo,
	--@p_curriculo		T_codigo,	
	--@p_sit_matricula	T_codigo,
	--@p_tem_turma		varchar(1)

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 1, 'P_ANO', 5, 'Ano', 'S', 'SELECT DISTINCT ANO AS CODIGO, (''ANO: '' + convert(varchar,ANO)) AS DESCRICAO FROM LY_PERIODO_LETIVO ORDER BY ANO DESC', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 2, 'P_SEMESTRE', 5, 'Semestre', 'S', 'SELECT DISTINCT PERIODO AS CODIGO, (''PERÍODO: '' + convert(varchar,PERIODO)) AS DESCRICAO FROM LY_PERIODO_LETIVO WHERE ANO = ISNULL(@p_ano@,ANO) ORDER BY PERIODO', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 3, 'P_FACULDADE', 5, 'Unidade Ensino', 'S', 'Select unidade_ens as codigo, nome_comp as descricao from ly_unidade_ensino order by unidade_ens', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 4, 'P_TIPO_CURSO', 5, 'Tipo de Curso', 'S', 'Select tipo as codigo, descricao from ly_tipo_curso order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 5, 'P_CURSO', 5, 'Curso', 'N', 'Select Curso as codigo, nome as descricao from ly_curso where tipo = isnull(@p_tipo_curso@,tipo) and faculdade = isnull(@p_faculdade@,faculdade) order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 6, 'P_TURNO', 5, 'Turno', 'N', 'Select turno as codigo, descricao from ly_turno order by turno', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 7, 'P_CURRICULO', 5, 'Curriculo', 'N', 'Select Curriculo as CODIGO, (''Currículo: '' + convert(varchar,Curriculo)) AS DESCRICAO FROM LY_curriculo WHERE curso = ISNULL(@p_curso@,curso) AND turno = ISNULL(@p_turno@,turno) and dt_extincao is null ORDER BY curriculo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

--SELECT * FROM LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA
--SELECT * FROM LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA

drop table  #TEMP_CONSULTA_DINAMICA

END
GO

delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_SP_csvPagamentoTitulos'
and IDENTIFICACAO_CODIGO = '0001'
go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_SP_csvPagamentoTitulos' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2016-11-09' DATA_CRIACAO
, 'ListaNG - Pagamento de Títulos' OBJETIVO
, 'Simone Oliveira, André Britto' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
go 