USE LYCEUM
GO
  
--CREATE VIEW FTC_VW_MOVIMENTO_CAIXA      
--AS      
SELECT CC.ID_ABERTURA,A.ALUNO, A.NOME_COMPL, C.RESP, R.TITULAR, C.COBRANCA,      
       LC.LANC_CRED, IC.VALOR, LC.TIPO_PAGAMENTO, LC.TIPO_CRED, LC.BOLETO, LC.DT_CREDITO,    
       CC.USUARIO_LYC, CC.USUARIO_WIN, CC.DATA_ABERTURA, CC.VALOR_ABERTURA, CC.DATA_FECHAMENTO,    
       LC.BANCO, LC.AGENCIA, LC.CONTA_BANCO, LC.SERIE, LC.NUMERO, CC.HORA_ABERTURA, CC.HORA_FECHAMENTO,   
       A.UNIDADE_FISICA, U.NOME_COMP, CUR.FACULDADE     
FROM LY_ALUNO A        
  JOIN LY_COBRANCA  C ON C.ALUNO  = A.ALUNO        
  JOIN LY_RESP_FINAN R ON C.RESP = R.RESP      
  JOIN LY_ITEM_CRED  IC ON IC.COBRANCA = C.COBRANCA        
  JOIN LY_LANC_CREDITO  LC ON LC.LANC_CRED = IC.LANC_CRED        
  JOIN LY_CONTROLE_CAIXA CC ON CC.ID_ABERTURA = LC.ID_ABERTURA    
  LEFT JOIN LY_UNIDADE_FISICA U ON U.UNIDADE_FIS = A.UNIDADE_FISICA  
  JOIN LY_CURSO CUR ON CUR.CURSO = A.CURSO  
WHERE IC.TIPODESCONTO IS NULL        
  AND IC.TIPO_ENCARGO IS NULL        
  --AND LC.TIPO_PAGAMENTO <> 'BANCO'      
  AND LC.ID_ABERTURA IS NOT NULL    
  AND 0 > (SELECT SUM(VALOR) FROM LY_ITEM_CRED WHERE LANC_CRED = IC.LANC_CRED)
  AND CC.USUARIO_LYC = '91185149520'  AND CC.DATA_ABERTURA = '2016-05-03'