USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_csvControleDocenteAulasSemanais '))
   exec('CREATE PROCEDURE [dbo].[FTC_csvControleDocenteAulasSemanais] AS BEGIN SET NOCOUNT OFF; END')
GO 

--EXEC FTC_csvControleDocenteAulasSemanais '2019','1','','','','',''

ALTER PROCEDURE dbo.FTC_csvControleDocenteAulasSemanais    
 @P_ANO    T_ANO  
,@P_SEMESTRE  T_SEMESTRE2  
,@P_FACULDADE  T_CODIGO
,@P_TIPO_CURSO VARCHAR(30)
,@P_CURSO T_CODIGO   
,@P_TURNO T_CODIGO
,@P_DOCENTE   T_CODIGO  
AS      
BEGIN     
  
 	/*
 	* 
 	* 
 	* 
 	* ALTERADO POR MIGUEL EM 10/11/2016 PARA ATENDER SOLICITAÇÃO DE SIMONE OLIVEIRA - CONTROLADORIA
 	* ACRESCENTADO NOVOS CAMPOS NA LISTA NG DETALHADA.
 	* 
 	* 
 	* 
 	* */
 	  
  SELECT    
  T.ANO
  ,T.SEMESTRE
  ,ISNULL (D.NUM_FUNC,'')        AS NUM_FUNC  
  ,ISNULL (D.NOME_COMPL,'')    AS NOME_COMPL 
  ,ISNULL (D.CPF,'') AS CPF
  ,ISNULL (T.CURSO,'') AS CURSO
  ,ISNULL (C.NOME,'') AS NOME_CURSO
  ,ISNULL (T.TURNO,'') AS TURNO
  ,ISNULL (T.CURRICULO,'') AS CURRICULO
  ,T.SERIE 
  ,T.SIT_TURMA
  ,ISNULL (T.TURMA,'')     AS TURMA  
  ,ISNULL (T.DISCIPLINA,'')    AS DISCIPLINA  
  ,DI.NOME_COMPL AS  NOME_DISCIPLINA
  ,ISNULL (T.ANO,'')      AS ANO  
  ,ISNULL (T.SEMESTRE,'')     AS SEMESTRE  
  ,ISNULL (T.FACULDADE,'')    AS FACULDADE  
  ,DI.AULAS_SEMANAIS      AS CH_SEMANAL
  ,AD.DIA_SEMANA
  ,CONVERT(VARCHAR(05),HORAINI_AULA,108) AS HORARIO_AULA 
  ,ISNULL((SELECT COUNT(*) 
			FROM VW_MATRICULA_E_PRE_MATRICULA M 
			WHERE M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE AND M.SIT_MATRICULA NOT IN ('Cancelado','Trancado')
			UNION
			SELECT COUNT(*) 
			FROM LY_HISTMATRICULA M 
			WHERE M.DISCIPLINA = T.DISCIPLINA AND M.TURMA = T.TURMA AND M.ANO = T.ANO AND M.SEMESTRE = T.SEMESTRE AND M.SITUACAO_HIST NOT IN ('Cancelado','Trancado')
			),0) AS QTD_ALUNOS
  ,ISNULL(TD.OBSERVACAO,'') AS OBS_DOCENTE_TURMA
  FROM LY_TURMA T
   INNER JOIN LY_DOCENTE D  ON D.NUM_FUNC  = T.NUM_FUNC
   INNER JOIN LY_TURMA_DOCENTE TD ON TD.NUM_FUNC = D.NUM_FUNC AND TD.DISCIPLINA = T.DISCIPLINA AND TD.TURMA = T.TURMA AND TD.ANO = T.ANO AND TD.PERIODO = T.SEMESTRE  
   INNER JOIN LY_DISCIPLINA DI ON DI.DISCIPLINA = T.DISCIPLINA 
   LEFT JOIN LY_CURSO C ON C.CURSO = T.CURSO
   LEFT JOIN LY_AULA_DOCENTE AD ON AD.TURMA = T.TURMA AND AD.TURNO = T.TURNO AND AD.DISCIPLINA = T.DISCIPLINA AND AD.ANO = T.ANO AND AD.SEMESTRE = T.SEMESTRE
   LEFT JOIN LY_HOR_OPER HO ON HO.AULA = AD.AULA AND HO.DIA_SEMANA = AD.DIA_SEMANA AND HO.TURNO = AD.TURNO AND HO.FACULDADE = AD.FACULDADE
  WHERE 1=1
AND (@P_ANO IS NOT NULL AND ISNULL(T.ANO,@P_ANO) = @P_ANO)
AND (@P_SEMESTRE IS NOT NULL AND ISNULL(T.SEMESTRE,@P_SEMESTRE) = @P_SEMESTRE)
AND (@P_FACULDADE IS NOT NULL AND C.FACULDADE = @P_FACULDADE)
AND (@P_TIPO_CURSO IS NOT NULL AND C.TIPO = @P_TIPO_CURSO)  
AND ((@P_CURSO IS NOT NULL AND C.CURSO = @P_CURSO) OR @P_CURSO IS NULL)
AND ((@P_TURNO IS NOT NULL AND T.TURNO = @P_TURNO) OR @P_TURNO IS NULL)
AND ((@P_DOCENTE IS NOT NULL AND AD.NUM_FUNC = @P_DOCENTE) OR @P_DOCENTE IS NULL)  
 
ORDER BY 1,2,4,3   
  
SET NOCOUNT OFF  
  

 END              
GO
-- [FIM]      

--##
--## PARAMETRIZAÇÃO/CADASTRO DA LISTA NO LYCEUM
--##

DECLARE @V_CONSULTA_DINAMICA INT
DECLARE @V_NOME_CONSULTA_DINAMICA varchar(100)

-- Colocar nome da lista (que será apresentada no combo)
set @V_NOME_CONSULTA_DINAMICA ='Custom - Controle Docente - Aulas Semanais'

-- Consulta ID da Lista
SELECT @V_CONSULTA_DINAMICA = ID FROM LY_CONSULTA_DINAMICA WHERE TITULO = @V_NOME_CONSULTA_DINAMICA

-- armazena padrões de acesso
SELECT PADACES
INTO #TEMP_CONSULTA_DINAMICA
FROM LY_CONSULTA_DINAMICA_PADACES WHERE ID = @V_CONSULTA_DINAMICA


DELETE LY_CONSULTA_DINAMICA_PADACES WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA

BEGIN

IF NOT EXISTS(SELECT 1 FROM LY_CONSULTA_DINAMICA C WHERE C.TITULO = @V_NOME_CONSULTA_DINAMICA)
INSERT INTO LY_CONSULTA_DINAMICA(TITULO, TIPO, STORED_PROCEDURE)
VALUES(@V_NOME_CONSULTA_DINAMICA,'CSV','sp:FTC_csvControleDocenteAulasSemanais(@P_ANO@,@P_SEMESTRE@,@P_FACULDADE@,@P_TIPO_CURSO@,@P_CURSO@,@P_TURNO@,@P_DOCENTE@)')

SET @V_CONSULTA_DINAMICA = @@IDENTITY

-- Insere padrões de acesso
INSERT INTO LY_CONSULTA_DINAMICA_PADACES (ID_CONSULTA_DINAMICA, PADACES)
SELECT @V_CONSULTA_DINAMICA, PADACES FROM #TEMP_CONSULTA_DINAMICA

-- Insere parametros

	--@p_ano				T_ANO,
	--@p_semestre			T_Semestre2,
	--@p_unidade_ensino	T_codigo,
	--@p_tipo_curso		T_codigo,
	--@p_curso			T_codigo,
	--@p_turno			T_codigo,
	--@p_curriculo		T_codigo,	
	--@p_sit_matricula	T_codigo,
	--@p_tem_turma		varchar(1)

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 1, 'P_ANO', 5, 'Ano', 'S', 'SELECT DISTINCT ANO AS CODIGO, (''ANO: '' + convert(varchar,ANO)) AS DESCRICAO FROM LY_PERIODO_LETIVO ORDER BY ANO DESC', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 2, 'P_SEMESTRE', 5, 'Período', 'S', 'SELECT DISTINCT PERIODO AS CODIGO, (''PERÍODO: '' + convert(varchar,PERIODO)) AS DESCRICAO FROM LY_PERIODO_LETIVO WHERE ANO = ISNULL(@p_ano@,ANO) ORDER BY PERIODO', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 3, 'P_FACULDADE', 5, 'Unidade Ensino', 'S', 'Select unidade_ens as codigo, nome_comp as descricao from ly_unidade_ensino order by unidade_ens', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 4, 'P_TIPO_CURSO', 5, 'Tipo de Curso', 'S', 'Select tipo as codigo, descricao from ly_tipo_curso order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 5, 'P_CURSO', 5, 'Curso', 'N', 'Select Curso as codigo, nome as descricao from ly_curso where tipo = isnull(@p_tipo_curso@,tipo) and faculdade = (@p_faculdade@,faculdade) order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 6, 'P_TURNO', 5, 'Turno', 'N', 'Select turno as codigo, descricao from ly_turno order by turno', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 7, 'P_DOCENTE', 5, 'Código Docente', 'N', 'SELECT  NUM_FUNC AS CODIGO , NOME_COMPL AS DESCRICAO FROM LY_DOCENTE_UNIDADE  where NUM_FUNC = isnull(@p_docente@,NUM_FUNC) and FACULDADE = isnull (@p_unidade_ensino@,FACULDADE) order by NUM_FUNC', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR


--SELECT * FROM LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA
--SELECT * FROM LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA

drop table  #TEMP_CONSULTA_DINAMICA

END
GO

delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_csvControleDocenteAulasSemanais'
and IDENTIFICACAO_CODIGO = '0001'
go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_csvControleDocenteAulasSemanais' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2016-11-08' DATA_CRIACAO
, 'ListaNG - Situação Alunos Macro' OBJETIVO
, 'Simone Oliveira, André Britto' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO 