USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_RecebimentosFinan'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_RecebimentosFinan] AS BEGIN SET NOCOUNT OFF; END')
GO

--EXEC FTC_Relat_RecebimentosFinan 'FTC-SSA',NULL,'S','MS',NULL,NULL,NULL,NULL,'2018-01-01','2018-03-31'

    
ALTER PROCEDURE dbo.FTC_Relat_RecebimentosFinan 
(      
 @p_unidade VARCHAR(20),    
 @p_curso VARCHAR(20),        
 @p_estorno VARCHAR(1),    
 @p_codigo_lanc VARCHAR(MAX),    
 @p_databaixa_ini DATETIME,    
 @p_databaixa_fim DATETIME,    
 @p_dataref_ini DATETIME,    
 @p_dataref_fim DATETIME, 
 @p_datavenc_ini DATETIME,
 @p_datavenc_fim DATETIME
-- @P_TIPO_EMISSAO T_CODIGO    
)      
AS  

BEGIN    
-- [INÍCIO]    
 -- Verifica se todos os códigos de lançamento foram informados,    
 -- caso sim considera como se o parâmetro não estivesse sendo passado, para    
 -- evitar que items com o código de lançamento vazio sejam ignorados    
 DECLARE @v_todos_cod_lanc VARCHAR(1)    
    
 IF NOT EXISTS ( SELECT 1    
     FROM LY_COD_LANC    
     WHERE NOT EXISTS ( SELECT 1 FROM dbo.fnMultiValue('I', @p_codigo_lanc, ',') WHERE LY_COD_LANC.CODIGO_LANC = ValorIni ) )    
 BEGIN    
   SET @v_todos_cod_lanc = 'S'    
 END    
 ELSE    
 BEGIN    
   SET @v_todos_cod_lanc = 'N'    
 END 
 
SELECT	
		A.UNIDADE_FISICA AS COD_UNIDADE,
		UF.NOME_COMP AS NOME_UNIDADE,
		CUR.TIPO,
		LC.LANC_CRED,
		C.COBRANCA,
		C.ESTORNO AS COBRANCA_ESTORNADA,
		C.DT_ESTORNO AS DATA_ESTORNO,
		ISNULL(LC.TIPO_PAGAMENTO,'') AS TIPO_PAGAMENTO,
		ISNULL(LC.TIPO_CRED,'') AS TIPO_CREDITO,
		CUR.TIPO AS TIPO_CURSO,
		C.CURSO AS COD_CURSO,
		CUR.NOME AS NOME_CURSO,
		C.ALUNO, 
		A.NOME_COMPL AS NOME_ALUNO,
		C.RESP AS RESPONSAVEL,
		CASE WHEN RF.CPF_TITULAR IS NULL    
			THEN dbo.fn_FormataNumeroCNPJ(rf.CGC_TITULAR)    
			ELSE dbo.fn_FormataNumeroCPF(rf.CPF_TITULAR) 
		END AS DOCUMENTO_TITULAR, 
		CONVERT(DATETIME, '01-' + STR(C.mes)  + '-' + STR(CASE WHEN C.ANO < 1901 THEN 1900 ELSE C.ANO END), 105) AS DATAREF,
		CONVERT(DATETIME,C.DATA_DE_VENCIMENTO,105) AS DATA_VENCIMENTO,
		CONVERT(DATETIME,LC.DT_CREDITO,105) AS DATA_PAGAMENTO,
		CONVERT(DATETIME,LC.DATA,105) AS DATA_RECEBIMENTO,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = C.COBRANCA AND IL.ITEM_ESTORNADO IS NULL AND IL.NUM_BOLSA IS NULL) AS VALOR_BRUTO,
		(SELECT ISNULL(SUM(VALOR),0)*-1 FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = C.COBRANCA AND IL.ITEM_ESTORNADO IS NULL AND IL.NUM_BOLSA IS NOT NULL) AS BOLSA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC1 WHERE IC1.COBRANCA = C.COBRANCA AND IC1.TIPO_ENCARGO = 'MULTA') AS MULTA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC4 WHERE IC4.COBRANCA = C.COBRANCA AND IC4.TIPO_ENCARGO = 'PERDEBOLSA') AS PERDEBOLSA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC2 WHERE IC2.COBRANCA = C.COBRANCA AND IC2.TIPO_ENCARGO = 'JUROS') AS JUROS,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = C.COBRANCA AND IC3.TIPODESCONTO IN ('Acréscimo','Concedido','DescBanco','PagtoAntecipado')) AS DESCONTO,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = C.COBRANCA AND IC3.TIPODESCONTO IS NULL AND IC3.TIPO_ENCARGO IS NULL)*-1 AS VALOR_PAGO
FROM LY_COBRANCA C
JOIN LY_ALUNO A ON A.ALUNO = C.ALUNO
JOIN LY_RESP_FINAN RF ON RF.RESP = C.RESP
JOIN LY_CURSO CUR ON CUR.CURSO = C.CURSO
JOIN LY_ITEM_CRED IC ON IC.COBRANCA = C.COBRANCA
JOIN LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = C.UNID_FISICA
JOIN VW_LANCAMENTOS_PAGAMENTOS LP ON LP.COBRANCA = C.COBRANCA
WHERE  C.ESTORNO = 'N' AND C.DT_ESTORNO IS NULL
AND ( @p_unidade IS NULL OR (@p_unidade IS NOT NULL AND A.UNIDADE_FISICA = @p_unidade) )    
AND ( @p_curso IS NULL OR (@p_curso IS NOT NULL AND A.CURSO = @p_curso) )    
AND ( @p_databaixa_ini IS NULL OR (@p_databaixa_ini IS NOT NULL AND LC.DATA >= @p_databaixa_ini) )    
AND ( @p_databaixa_fim IS NULL OR (@p_databaixa_fim IS NOT NULL AND LC.DATA <= @p_databaixa_fim) ) 
AND (C.ANO BETWEEN YEAR(@p_dataref_ini) AND YEAR(@p_dataref_fim))
AND (C.MES BETWEEN MONTH(@p_dataref_ini) AND MONTH(@p_dataref_fim))
AND ( @p_datavenc_ini IS NULL OR (@p_datavenc_ini IS NOT NULL AND C.DATA_DE_VENCIMENTO  >= @p_datavenc_ini) )    
AND ( @p_datavenc_fim IS NULL OR (@p_datavenc_fim IS NOT NULL AND C.DATA_DE_VENCIMENTO <= @p_datavenc_fim) )    
 AND ( @p_codigo_lanc IS NULL OR @v_todos_cod_lanc = 'S' OR EXISTS ( SELECT 1  
                                                                       FROM VW_LANCAMENTOS_PAGAMENTOS ra2  
                                                                       WHERE ra2.COBRANCA = c.COBRANCA  
                                                                         AND EXISTS ( SELECT 1 FROM dbo.fnMultiValue('I', @p_codigo_lanc, ',') WHERE ValorIni = ra2.CODIGO_LANC ) ) )  
	
	    
 END                
-- [FIM]    
    
RETURN 
GO


delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_Relat_RecebimentosFinan'
and IDENTIFICACAO_CODIGO = '0001'
go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_Relat_RecebimentosFinan' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2018-04-20' DATA_CRIACAO
, 'Relatório - Contas em Aberto - Financeiro' OBJETIVO
, 'Ana Paula' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO  
