  
ALTER PROCEDURE FTC_Relat_Avaliacao_Coordenador_2018_NG  
 @p_avaliacaoq VARCHAR(30)    
 ,@p_aplicacao VARCHAR(30)    
 ,@p_unidade VARCHAR(15)    
 ,@p_curso VARCHAR(20)    
 ,@p_docente VARCHAR(15)     
 ,@p_turma VARCHAR (30)    
 ,@p_disciplina VARCHAR(20)   
AS  
BEGIN  
/*  
Autor: Miguel Barreto  
Atualizado em: 13/07/2017  
*/  
-- Teste:  
--EXEC FTC_Relat_Avaliacao_Coordenador_2018_NG 'Avaliação Docente II', 'AVALDOCENTE2_20181', '03', NULL, NULL,NULL,NULL  
  
  
  
-- PARAMETROS PARA TESTE DA PROCEDURE  
/*DECLARE  
  @p_avaliacaoq VARCHAR(30)    
  ,@p_aplicacao VARCHAR(30)    
  ,@p_unidade VARCHAR(15)    
  ,@p_curso VARCHAR(20)    
  ,@p_docente VARCHAR(15)     
  ,@p_turma VARCHAR (30)    
  ,@p_disciplina VARCHAR(20)   
  
 SET @p_avaliacaoq = 'Avaliação DocenteIV'  
 SET @p_aplicacao = 'AVALDOCENTE4_20181'  
 SET @p_turma = NULL  
 SET @p_disciplina = NULL  
 SET @p_curso = NULL  
 SET @p_unidade = '29'  
 SET @p_docente = NULL  
 */  
  
  
  
 CREATE TABLE #TEMP_SUM_MEDIACURSOGERAL  
 (  
 TIPO_QUESTIONARIO VARCHAR(20),  
 APLICACAO VARCHAR(20),  
 QUESTAO NUMERIC(10),  
 FACULDADE VARCHAR(20),  
 CURSO VARCHAR(20),  
 SOMA INT,  
 QUANTIDADE INT  
  
 )  
  
IF @p_avaliacaoq = 'Avaliação Docente II' OR @p_avaliacaoq = 'Avaliação DocenteIV'  
BEGIN  
   
-- TABELA #TEMP_SUM_MEDIACURSOGERAL  
  
  INSERT INTO #TEMP_SUM_MEDIACURSOGERAL  
  SELECT   
   R.TIPO_QUESTIONARIO  
   ,R.APLICACAO  
   ,R.QUESTAO  
   ,C.FACULDADE  
   ,C.CURSO  
   ,SUM(CONVERT(INT,CR.CONCEITO)) AS SOMA  
   ,COUNT(CR.CONCEITO) AS QUANTIDADE  
   --INTO #TEMP_SUM_MEDIACURSOGERAL --DROP TABLE #TEMP_SUM_MEDIACURSOGERAL  
  FROM LY_APLIC_QUESTIONARIO AS AQ  
  INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO  
   AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO  
   AND R.APLICACAO = AQ.APLICACAO  
  INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO  
   AND CR.QUESTIONARIO = R.QUESTIONARIO  
   AND CR.TIPO_OBJETO = R.TIPO_OBJETO  
   AND CR.APLICACAO = R.APLICACAO  
   AND CR.QUESTAO = R.QUESTAO  
   AND CR.RESPOSTA = R.RESPOSTA  
   AND CR.CHAVE_RESP = R.CHAVE_RESP  
  INNER JOIN LY_COORDENACAO CO ON CO.NUM_FUNC = R.CODIGO  
  INNER JOIN LY_CURSO C ON C.CURSO = CO.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
  WHERE 1 = 1   
   AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)  
   AND C.CURSO = ISNULL(@p_curso, C.CURSO)  
   AND CO.NUM_FUNC = ISNULL(@p_docente, CO.NUM_FUNC)  
   AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq  
   AND R.APLICACAO = @p_aplicacao  
  GROUP BY  
   R.TIPO_QUESTIONARIO  
   ,R.APLICACAO  
   ,R.QUESTAO  
   ,C.FACULDADE  
   ,C.CURSO  
  
END  
  
IF @p_avaliacaoq = 'Avaliação DocenteIII'  
 BEGIN  
    
  INSERT INTO #TEMP_SUM_MEDIACURSOGERAL  
  SELECT   
   R.TIPO_QUESTIONARIO  
   ,R.APLICACAO  
   ,R.QUESTAO  
   ,C.FACULDADE  
   ,C.CURSO  
   ,SUM(CONVERT(INT,CR.CONCEITO)) AS SOMA  
   ,COUNT(CR.CONCEITO) AS QUANTIDADE  
  FROM LY_APLIC_QUESTIONARIO AS AQ  
  INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO  
   AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO  
   AND R.APLICACAO = AQ.APLICACAO  
  INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO  
   AND CR.QUESTIONARIO = R.QUESTIONARIO  
   AND CR.APLICACAO = R.APLICACAO  
   AND CR.QUESTAO = R.QUESTAO  
   AND CR.RESPOSTA = R.RESPOSTA  
   AND CR.CHAVE_RESP = R.CHAVE_RESP  
  INNER JOIN LY_DOCENTE D ON D.NUM_FUNC = R.CODIGO  
  INNER JOIN LY_TURMA T ON T.NUM_FUNC = D.NUM_FUNC  
  INNER JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
  WHERE 1 = 1   
   --AND T.ANO = '2017' AND T.SEMESTRE = '2'  
   AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)  
   AND C.CURSO = ISNULL(@p_curso, C.CURSO)  
   AND D.NUM_FUNC = ISNULL(@p_docente, D.NUM_FUNC)  
   AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq  
   AND R.APLICACAO = @p_aplicacao  
  GROUP BY  
   R.TIPO_QUESTIONARIO  
   ,R.APLICACAO  
   ,R.QUESTAO  
   ,C.FACULDADE  
   ,C.CURSO  
  
 END  
  
  
 CREATE TABLE #TEMP_RELATORIO_ALUNO1  
 (  
  TIPO_QUESTIONARIO VARCHAR(20),  
  APLICACAO VARCHAR(20),  
  QUESTIONARIO VARCHAR(20),  
  QUESTAO NUMERIC(10),  
  ORDEM INT,  
  PERGUNTA VARCHAR(500),  
  PROFESSOR VARCHAR(100),  
  CODIGO_CURSO VARCHAR(20),  
  CURSO VARCHAR(300),  
  CODIGO_UNIDADE_FISICA VARCHAR(20),  
  UNIDADE_FISICA VARCHAR(100),  
  --QTDTURMA INT,  
  --MEDIACURSOGERAL NUMERIC(10,2),  
  --MEDIAPROFESSOR DECIMAL(10,2),  
  MTO_SATISF INT,  
  SATISF INT,  
  PARC_SATISF INT,  
  INSATISF INT,  
  NAOSEI INT,  
  NUMERO INT  
 )  
  
IF @p_avaliacaoq = 'Avaliação Docente II' OR @p_avaliacaoq = 'Avaliação DocenteIV'  
BEGIN  
  
 INSERT INTO #TEMP_RELATORIO_ALUNO1  
 SELECT  
 AQ.TIPO_QUESTIONARIO AS TIPO_QUESTIONARIO  
 ,AQ.APLICACAO AS APLICACAO  
 ,AQ.QUESTIONARIO AS QUESTIONARIO  
 ,R.QUESTAO AS QUESTAO  
 ,CAST(NULL AS INT) AS ORDEM  
 ,CAST(NULL AS VARCHAR(500)) AS PERGUNTA  
 ,D.NOME_COMPL AS PROFESSOR  
 ,C.CURSO AS CODIGO_CURSO  
 ,C.NOME AS CURSO  
 ,C.FACULDADE AS CODIGO_UNIDADE_FISICA  
 ,UE.NOME_COMP AS UNIDADE_FISICA  
 --,CAST(NULL AS INT) AS QTDTURMA  
 --,CAST(NULL AS NUMERIC(10,2)) AS MEDIACURSOGERAL  
 --,CAST(SUM(CR.CONCEITO) AS DECIMAL(10,2)) AS MEDIAPROFESSOR  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 1 THEN 1  
   ELSE 0 
  END  
 ) AS MTO_SATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 2 THEN 1 
   ELSE 0 
  END  
 ) AS SATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 3 THEN 1 
   ELSE 0 
  END  
 ) AS PARC_SATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 4 THEN 1 
   ELSE 0
  END  
 ) AS INSATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 5 THEN 1 
   ELSE 0
  END  
 ) AS NAOSEI  
 ,COUNT(DISTINCT R.AVA_CODIGO) AS NUMERO  
FROM LY_APLIC_QUESTIONARIO AS AQ  
INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO  
 AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO  
 AND R.APLICACAO = AQ.APLICACAO  
INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO  
 AND CR.QUESTIONARIO = R.QUESTIONARIO  
 AND CR.APLICACAO = R.APLICACAO  
 AND CR.QUESTAO = R.QUESTAO  
 AND CR.RESPOSTA = R.RESPOSTA  
 AND CR.CHAVE_RESP = R.CHAVE_RESP  
INNER JOIN LY_DOCENTE AS D ON D.NUM_FUNC = R.CODIGO  
INNER JOIN LY_COORDENACAO CO ON CO.NUM_FUNC = D.NUM_FUNC  
INNER JOIN LY_CURSO C ON C.CURSO = CO.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
INNER JOIN LY_UNIDADE_ENSINO AS UE ON UE.UNIDADE_ENS = C.FACULDADE  
WHERE 1 = 1   
 AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)  
 AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq  
 AND R.APLICACAO = @p_aplicacao  
 AND C.CURSO = ISNULL(@p_curso, C.CURSO)  
 AND CO.NUM_FUNC = ISNULL(@p_docente, CO.NUM_FUNC)  
GROUP BY  
 AQ.TIPO_QUESTIONARIO  
 ,AQ.APLICACAO  
 ,AQ.QUESTIONARIO  
 ,R.QUESTAO  
 ,D.NOME_COMPL  
 ,C.CURSO  
 ,C.NOME  
 ,C.FACULDADE  
 ,UE.NOME_COMP  
  
END  
  
  
IF @p_avaliacaoq = 'Avaliação DocenteIII'  
BEGIN  
  
 INSERT INTO #TEMP_RELATORIO_ALUNO1  
 SELECT  
 AQ.TIPO_QUESTIONARIO AS TIPO_QUESTIONARIO  
 ,AQ.APLICACAO AS APLICACAO  
 ,AQ.QUESTIONARIO AS QUESTIONARIO  
 ,R.QUESTAO AS QUESTAO  
 ,CAST(NULL AS INT) AS ORDEM  
 ,CAST(NULL AS VARCHAR(500)) AS PERGUNTA  
 ,D.NOME_COMPL AS PROFESSOR  
 ,C.CURSO AS CODIGO_CURSO  
 ,C.NOME AS CURSO  
 ,C.FACULDADE AS CODIGO_UNIDADE_FISICA  
 ,UE.NOME_COMP AS UNIDADE_FISICA  
 --,CAST(NULL AS INT) AS QTDTURMA  
 --,CAST(NULL AS NUMERIC(10,2)) AS MEDIACURSOGERAL  
 --,CAST(SUM(CR.CONCEITO) AS DECIMAL(10,2)) AS MEDIAPROFESSOR  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 1 THEN 1  
   ELSE 0  
  END  
 ) AS MTO_SATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 2 THEN 1  
   ELSE 0  
  END  
 ) AS SATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 3 THEN 1 
   ELSE 0 
  END  
 ) AS PARC_SATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 4 THEN 1  
   ELSE 0
  END  
 ) AS INSATISF  
 ,SUM(  
  CASE CR.CONCEITO  
   WHEN 5 THEN 1  
   ELSE 0  
  END  
 ) AS NAOSEI  
 ,COUNT(DISTINCT R.AVA_CODIGO) AS NUMERO  
FROM LY_APLIC_QUESTIONARIO AS AQ  
INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO  
 AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO  
 AND R.APLICACAO = AQ.APLICACAO  
INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO  
 AND CR.QUESTIONARIO = R.QUESTIONARIO  
 AND CR.APLICACAO = R.APLICACAO  
 AND CR.QUESTAO = R.QUESTAO  
 AND CR.RESPOSTA = R.RESPOSTA  
 AND CR.CHAVE_RESP = R.CHAVE_RESP  
INNER JOIN LY_DOCENTE AS D ON D.NUM_FUNC = R.CODIGO  
INNER JOIN LY_TURMA T ON T.NUM_FUNC = D.NUM_FUNC  
INNER JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
INNER JOIN LY_UNIDADE_ENSINO AS UE ON UE.UNIDADE_ENS = C.FACULDADE  
WHERE 1 = 1   
 AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)  
 AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq  
 AND R.APLICACAO = @p_aplicacao  
 AND C.CURSO = ISNULL(@p_curso, C.CURSO)  
 AND D.NUM_FUNC = ISNULL(@p_docente, D.NUM_FUNC)  
GROUP BY  
 AQ.TIPO_QUESTIONARIO  
 ,AQ.APLICACAO  
 ,AQ.QUESTIONARIO  
 ,R.QUESTAO  
 ,D.NOME_COMPL  
 ,C.CURSO  
 ,C.NOME  
 ,C.FACULDADE  
 ,UE.NOME_COMP  
  
END  
  
-- UPDATE ORDEM E PERGUNTA  
UPDATE #TEMP_RELATORIO_ALUNO1 SET  
 ORDEM = Q.ORDEM  
 ,PERGUNTA = Q.QUESTAO_OBJETIVA  
FROM LY_QUESTAO AS Q  
INNER JOIN #TEMP_RELATORIO_ALUNO1 AS TRA ON TRA.QUESTIONARIO = Q.QUESTIONARIO  
 AND TRA.TIPO_QUESTIONARIO = Q.TIPO_QUESTIONARIO  
 AND TRA.QUESTAO = Q.QUESTAO  
  
  
-- TABELA #TEMP_RELATORIO_ALUNO2  
  
SELECT  
 TIPO_QUESTIONARIO  
 ,APLICACAO  
 ,QUESTIONARIO  
 ,QUESTAO  
 ,ORDEM  
 ,PERGUNTA  
 ,PROFESSOR  
 ,CODIGO_CURSO  
 ,CURSO  
 ,CODIGO_UNIDADE_FISICA  
 ,UNIDADE_FISICA  
 --,QTDTURMA  
 --,MEDIACURSOGERAL  
 --,MEDIAPROFESSOR  
 ,MTO_SATISF  
 ,SATISF  
 ,PARC_SATISF  
 ,INSATISF  
 ,NAOSEI  
 --,NUMERO  
 ,SUM(MTO_SATISF + SATISF + PARC_SATISF + INSATISF + NAOSEI) AS NUMERO --SUBSTITUIR O NUMERO (DE PARTICIPANTES)  
 INTO #TEMP_RELATORIO_ALUNO2 --DROP TABLE #TEMP_RELATORIO_ALUNO2  
FROM #TEMP_RELATORIO_ALUNO1  
GROUP BY  
 TIPO_QUESTIONARIO  
 ,APLICACAO  
 ,QUESTIONARIO  
 ,QUESTAO  
 ,ORDEM  
 ,PERGUNTA  
 ,PROFESSOR  
 ,CODIGO_CURSO  
 ,CURSO  
 ,CODIGO_UNIDADE_FISICA  
 ,UNIDADE_FISICA  
 --,QTDTURMA  
 --,MEDIACURSOGERAL  
 --,MEDIAPROFESSOR  
 ,MTO_SATISF  
 ,SATISF  
 ,PARC_SATISF  
 ,INSATISF  
 ,NAOSEI  
 ,NUMERO  
  
  
-- UPDATE PERCENTUAIS DE RESPOSTA  
--UPDATE #TEMP_RELATORIO_ALUNO2 SET  
-- MEDIAPROFESSOR = (MEDIAPROFESSOR / NUMERO)  
--UPDATE #TEMP_RELATORIO_ALUNO2 SET  
-- MTO_SATISF = (MTO_SATISF / NUMERO) * 100  
--UPDATE #TEMP_RELATORIO_ALUNO2 SET  
-- SATISF = (SATISF / NUMERO) * 100  
--UPDATE #TEMP_RELATORIO_ALUNO2 SET  
-- PARC_SATISF = (PARC_SATISF / NUMERO) * 100  
--UPDATE #TEMP_RELATORIO_ALUNO2 SET  
-- INSATISF = (INSATISF / NUMERO) * 100  
--UPDATE #TEMP_RELATORIO_ALUNO2 SET  
-- NAOSEI = (NAOSEI / NUMERO) * 100  
  
   
 IF ISNULL(@p_curso,'') <> ''  
 BEGIN  
 DECLARE @V_NUMERO INT     
 SET @V_NUMERO = dbo.fn_AvalDocQtdPartic(@p_avaliacaoq, @p_aplicacao, @p_unidade, @p_curso)    
   
 UPDATE #TEMP_RELATORIO_ALUNO2 SET    
 NUMERO = @V_NUMERO  
 END  
 IF ISNULL(@p_curso,'') = '' AND @p_avaliacaoq <> 'Avaliação Docente II' AND @p_avaliacaoq <> 'Avaliação DocenteIII'  
 BEGIN  
  DECLARE  @p_avaliacaoq1 VARCHAR(30), @p_aplicacao1 VARCHAR(30), @p_unidade1 VARCHAR(15), @p_curso1 VARCHAR(20)  
  DECLARE cursor1 CURSOR FOR  
  SELECT DISTINCT TIPO_QUESTIONARIO, APLICACAO, CODIGO_UNIDADE_FISICA, CODIGO_CURSO  FROM #TEMP_RELATORIO_ALUNO2  
  
  OPEN cursor1  
  
  FETCH NEXT FROM cursor1 INTO @p_avaliacaoq1, @p_aplicacao1, @p_unidade1, @p_curso1  
  
  WHILE @@FETCH_STATUS = 0  
  BEGIN  
  
   UPDATE #TEMP_RELATORIO_ALUNO2 SET NUMERO = (SELECT dbo.fn_AvalDocQtdPartic(@p_avaliacaoq1, @p_aplicacao1, @p_unidade1, @p_curso1))  
   WHERE TIPO_QUESTIONARIO = @p_avaliacaoq1 AND APLICACAO = @p_aplicacao1 AND CODIGO_UNIDADE_FISICA = @p_unidade1 AND CODIGO_CURSO = @p_curso1  
  
  FETCH NEXT FROM cursor1 INTO @p_avaliacaoq1, @p_aplicacao1, @p_unidade1, @p_curso1  
  END  
  CLOSE cursor1  
  DEALLOCATE cursor1  
    
 END  
  
--DELETE FROM #TEMP_RELATORIO_ALUNO2 WHERE NUMERO = 0  
  
  
  
-- VERFICACAO DO PERCENTUAL:  
/*  
SELECT  
 TIPO_QUESTIONARIO  
 ,APLICACAO  
 ,QUESTIONARIO  
 ,QUESTAO  
 ,ORDEM  
 ,PERGUNTA  
 ,PROFESSOR  
 ,CODIGO_CURSO  
 ,CURSO  
 ,CODIGO_UNIDADE_FISICA  
 ,UNIDADE_FISICA  
 ,TURMA  
 ,CODIGO_DISCIPLINA  
 ,DISCIPLINA  
 ,ANO  
 ,SEMESTRE  
 ,QTDTURMA  
 ,MEDIACURSOGERAL  
 ,MEDIAPROFESSOR  
 ,MTO_SATISF  
 ,SATISF  
 ,PARC_SATISF  
 ,INSATISF  
 ,NUMERO  
 ,(MTO_SATISF + SATISF + PARC_SATISF + INSATISF) AS SOMA  
FROM #TEMP_RELATORIO_ALUNO2  
ORDER BY  
 SOMA  
*/  
  
  
SELECT  
 *  
FROM #TEMP_RELATORIO_ALUNO2  
WHERE 1=1  
ORDER BY  
 PROFESSOR  
 ,APLICACAO  
 ,CURSO  
 ,ORDEM  
  
-- APAGA TABELAS  
  
 DROP TABLE #TEMP_SUM_MEDIACURSOGERAL;  
  
 DROP TABLE #TEMP_RELATORIO_ALUNO1;  
  
 DROP TABLE #TEMP_RELATORIO_ALUNO2;  
  
END  
  