USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_ContasEmAbertoFinan'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_ContasEmAbertoFinan] AS BEGIN SET NOCOUNT OFF; END')
GO 

--EXEC FTC_Relat_ContasEmAbertoFinan NULL,NULL,NULL,NULL,'2018-10-31',NULL,NULL,NULL,NULL,NULL,NULL,'2'


 ALTER PROCEDURE dbo.FTC_Relat_ContasEmAbertoFinan
(        
  @p_unidade VARCHAR(MAX)  
, @p_tipo VARCHAR(20)    
, @p_curso  VARCHAR(20)
, @p_codigo_lanc VARCHAR(MAX)
, @p_database DATETIME
, @p_dataref_ini DATETIME
, @p_dataref_fim DATETIME  
, @p_datavenc_ini DATETIME
, @p_datavenc_fim DATETIME 
, @p_aluno VARCHAR(11)
, @p_resp VARCHAR(11)
, @p_tipo_relatorio VARCHAR(1)

)        
AS    
BEGIN        

	 DECLARE @v_todos_cod_lanc VARCHAR(1)  
	 DECLARE @v_todos_unidade_ens VARCHAR(1)  
  
 IF NOT EXISTS ( SELECT 1  
     FROM LY_COD_LANC  
     WHERE NOT EXISTS ( SELECT 1 FROM dbo.fnMultiValue('I', @p_codigo_lanc, ',') WHERE LY_COD_LANC.CODIGO_LANC = ValorIni ) )  
 BEGIN  
   SET @v_todos_cod_lanc = 'S'  
 END  
 ELSE  
 BEGIN  
   SET @v_todos_cod_lanc = 'N'  
 END  


  IF NOT EXISTS ( SELECT 1  
     FROM LY_UNIDADE_ENSINO  
     WHERE NOT EXISTS ( SELECT 1 FROM dbo.fnMultiValue('I', @p_unidade, ',') WHERE LY_UNIDADE_ENSINO.UNIDADE_ENS = ValorIni ) )  
 BEGIN  
   SET @v_todos_unidade_ens = 'S'  
 END  
 ELSE  
 BEGIN  
   SET @v_todos_unidade_ens = 'N'  
 END  


CREATE TABLE #TEMP_RELATORIO (
	COD_UNIDADE VARCHAR(30)
	,NOME_UNIDADE VARCHAR(150)
	,TIPO_CURSO VARCHAR(75)
	,COD_CENTROCUSTO VARCHAR(30)
	,DESCR_CENTROCUSTO VARCHAR(100)
	,COD_CURSO VARCHAR(20)
	,NOME_CURSO VARCHAR(200)
	,ALUNO VARCHAR(20)
	,NOME_COMPL VARCHAR(200)
	,COBRANCA NUMERIC
	,TIPO_COBRANCA VARCHAR(30)
	,CODIGO_LANCAMENTO VARCHAR(50)
	,DT_GERACAO_COB DATETIME
	,RESP VARCHAR(20)
	,TITULAR VARCHAR(200)
	,CPF_TITULAR VARCHAR(20)
	,CPF_ALUNO VARCHAR(20)
	,VALOR_TOTAL_COBRANCA NUMERIC(20,2)
	,VALOR_FATURADO NUMERIC(20,2)
	,VALOR_ESTORNOS NUMERIC(20,2)
	,VALOR_BOLSAS NUMERIC(20,2)
	,SALDO NUMERIC(20,2)
	,DATA_DE_VENCIMENTO DATETIME
	,DATA_DE_VENCIMENTO_ORIG DATETIME
	,DATAREF DATETIME
	,PERIODO_LETIVO VARCHAR(20)
	,DATA_CANCEL_MATR DATETIME
	,VALOR_DIVIDA_PERIODO DECIMAL(20,2)
	,VENCIDO30 DECIMAL(20,2)
	,VENCIDO60 DECIMAL(20,2)
	,VENCIDO90 DECIMAL(20,2)
	,VENCIDO120 DECIMAL(20,2)
	,VENCIDO180 DECIMAL(20,2)
	,VENCIDO365 DECIMAL(20,2)
	,VENCIDO366 DECIMAL(20,2)
	,TOTALVENCIDO DECIMAL(20,2)
	,AVENCER30 DECIMAL(20,2)
	,AVENCER60 DECIMAL(20,2)
	,AVENCER90 DECIMAL(20,2)
	,AVENCER120 DECIMAL(20,2)
	,AVENCER180 DECIMAL(20,2)
	,AVENCER365 DECIMAL(20,2)
	,AVENCER366 DECIMAL(20,2)
	,TOTALAVENCER DECIMAL(20,2)
	)


	INSERT INTO #TEMP_RELATORIO
	SELECT	
			 A.UNIDADE_FISICA AS COD_UNIDADE
			,UE.NOME_COMP AS NOME_UNIDADE
			,C.TIPO AS TIPO_CURSO
			,(SELECT TOP 1 ISNULL(CCUSTO.CENTRO_DE_CUSTO,'')  FROM  LY_CENTRO_DE_CUSTO CCUSTO WHERE CCUSTO.CURSO=CO.CURSO) COD_CENTROCUSTO  
			--,ISNULL(RA.CENTRO_DE_CUSTO,'') AS COD_CENTROCUSTO
			,ISNULL(TI.DESCR,'') AS DESCR_CENTROCUSTO
			,C.CURSO AS COD_CURSO
			,C.NOME AS NOME_CURSO
			,A.ALUNO
			,A.NOME_COMPL
			,CO.COBRANCA
			,CASE co.NUM_COBRANCA  
			 WHEN 1 THEN 'MENSALIDADE'  
             WHEN 2 THEN 'SERVICO'  
             WHEN 3 THEN 'ACORDO'  
             WHEN 4 THEN 'OUTROS'  
             WHEN 5 THEN 'CHEQUE DEVOLVIDO'  
             ELSE '' END AS TIPO_COBRANCA
			 ,STUFF((SELECT DISTINCT ',' + IL.CODIGO_LANC AS [text()]
                        FROM LY_ITEM_LANC IL
                        WHERE
                        IL.COBRANCA = CO.COBRANCA
                        FOR XML PATH('') 
                        ), 1, 1, '' ) AS CODIGO_LANCAMENTO
			,CO.DATA_DE_GERACAO AS DT_GERACAO_COB
			,CO.RESP
			,RF.TITULAR
			,RF.CPF_TITULAR
			,P.CPF AS CPF_ALUNO
			,(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = CO.COBRANCA AND IL.NUM_BOLSA IS NULL AND IL.ITEM_ESTORNADO IS NULL AND IL.DATA <= ISNULL(@p_database,GETDATE())) AS VALOR_TOTAL_COBRANCA
			,(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = CO.COBRANCA AND IL.DATA <= ISNULL(@p_database,GETDATE()))													AS [VALOR_FATURADO]
			,(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = CO.COBRANCA AND IL.ITEM_ESTORNADO IS NOT NULL AND IL.DATA <= ISNULL(@p_database,GETDATE()))						AS [VALOR_ESTORNOS]
			,(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = CO.COBRANCA AND IL.NUM_BOLSA IS NOT NULL AND IL.ITEM_ESTORNADO IS NULL AND IL.DATA <= ISNULL(@p_database,GETDATE()))	AS [VALOR_BOLSAS]
			,(SELECT ISNULL(SUM(RA2.VALOR),0) FROM FTC_VW_LANCAMENTOS_PAGAMENTOS RA2 WHERE RA2.COBRANCA = CO.COBRANCA AND RA2.DATA <= ISNULL(@p_database,GETDATE())) AS SALDO
			,CO.DATA_DE_VENCIMENTO
			,CO.DATA_DE_VENCIMENTO_ORIG
			,CONVERT(DATETIME, '01/' + STR(co.mes)  + '/' + STR(CASE WHEN CO.ANO < 1901 THEN 1900 ELSE CO.ANO END), 103) AS DATAREF
			,(SELECT TOP 1 CONCAT(LD.ANO_REF,LD.PERIODO_REF) FROM LY_LANC_DEBITO LD JOIN LY_ITEM_LANC IL ON IL.LANC_DEB = LD.LANC_DEB WHERE IL.COBRANCA = CO.COBRANCA) AS PERIODO_LETIVO
			,(SELECT TOP 1 ISNULL(CONVERT(DATETIME,DT_ENCERRAMENTO,103),'') FROM LY_H_CURSOS_CONCL WHERE ALUNO = CO.ALUNO AND MOTIVO = 'Cancelamento' AND DT_REABERTURA IS NULL) AS DATA_CANCEL_MATR
			,(SELECT SUM(LD.VALOR) FROM LY_LANC_DEBITO LD JOIN LY_ITEM_LANC IL ON IL.LANC_DEB = LD.LANC_DEB AND LD.ALUNO = CO.ALUNO WHERE IL.COBRANCA = CO.COBRANCA ) AS VALOR_DIVIDA_PERIODO
			,CONVERT(DECIMAL(20,2),0.00) AS VENCIDO30, CONVERT(DECIMAL(20,2),0.00) AS VENCIDO60, CONVERT(DECIMAL(20,2),0.00) AS VENCIDO90, CONVERT(DECIMAL(20,2),0.00) AS VENCIDO120, CONVERT(DECIMAL(20,2),0.00) AS VENCIDO180, CONVERT(DECIMAL(20,2),0.00) AS VENCIDO365, CONVERT(DECIMAL(20,2),0.00) AS VENCIDO366, CONVERT(DECIMAL(20,2),0.00) AS TOTALVENCIDO
			,CONVERT(DECIMAL(20,2),0.00) AS AVENCER30, CONVERT(DECIMAL(20,2),0.00) AS AVENCER60, CONVERT(DECIMAL(20,2),0.00) AS AVENCER90, CONVERT(DECIMAL(20,2),0.00) AS AVENCER120, CONVERT(DECIMAL(20,2),0.00) AS AVENCER180, CONVERT(DECIMAL(20,2),0.00) AS AVENCER365, CONVERT(DECIMAL(20,2),0.00) AS AVENCER366, CONVERT(DECIMAL(20,2),0.00) AS TOTALAVENCER
	FROM LY_COBRANCA CO
	JOIN LY_ALUNO A ON A.ALUNO = CO.ALUNO
	JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
	JOIN LY_RESP_FINAN RF ON RF.RESP = CO.RESP
	JOIN LY_CURSO C ON C.CURSO = A.CURSO
	LEFT JOIN LY_CENTRO_DE_CUSTO CC ON CC.CURSO = CO.CURSO
	LEFT JOIN HD_TABELAITEM TI ON TI.ITEM = CC.CENTRO_DE_CUSTO AND TABELA = 'CentroCusto'
	JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
	WHERE 1=1--RA.EVENTO_NUM IN (1,4,28,30,31,32)
	AND (SELECT ISNULL(SUM(RA2.VALOR),0) FROM FTC_VW_LANCAMENTOS_PAGAMENTOS RA2 WHERE RA2.COBRANCA = CO.COBRANCA AND RA2.DATA <= ISNULL(@p_database,GETDATE())) <> 0
	--AND ( @p_unidade IS NULL OR (@p_unidade IS NOT NULL AND C.FACULDADE = @p_unidade) )    
	--AND ( @p_codigo_lanc IS NULL OR (@p_codigo_lanc IS NOT NULL AND RA.CODIGO_LANC = @p_codigo_lanc) )   
	AND ( @p_unidade IS NULL OR @v_todos_unidade_ens = 'S' OR EXISTS (SELECT 1
																		FROM LY_CURSO C
																		WHERE C.FACULDADE = UE.UNIDADE_ENS
																		AND EXISTS (SELECT 1 FROM dbo.fnMultiValue('I', @p_unidade, ',') WHERE ValorIni = C.FACULDADE ) ) )   
	AND ( @p_tipo IS NULL OR (@p_tipo IS NOT NULL AND c.TIPO = @p_tipo) )    
	AND ( @p_curso IS NULL OR (@p_curso IS NOT NULL AND c.CURSO = @p_curso) )    
	AND ( @p_dataref_ini IS NULL OR (@p_dataref_ini IS NOT NULL AND CONVERT(DATETIME, '01/' + STR(co.mes)  + '/' + STR(CO.ANO), 103)  >= @p_dataref_ini) )    
	AND ( @p_dataref_fim IS NULL OR (@p_dataref_fim IS NOT NULL AND CONVERT(DATETIME, '01/' + STR(co.mes) + '/' + STR(CO.ANO), 103)  <= @p_dataref_fim) )    
	AND ( @p_datavenc_ini IS NULL OR (@p_datavenc_ini IS NOT NULL AND CO.DATA_DE_VENCIMENTO  >= @p_datavenc_ini) )    
	AND ( @p_datavenc_fim IS NULL OR (@p_datavenc_fim IS NOT NULL AND CO.DATA_DE_VENCIMENTO  <= @p_datavenc_fim) )    
	--AND ( @p_database IS NULL OR (@p_database IS NOT NULL AND RA.DATACONTAB  <= ISNULL(@p_database,GETDATE())) )  
	AND ( @p_aluno IS NULL OR (@p_aluno IS NOT NULL AND co.ALUNO = @p_aluno) )    
	AND ( @p_resp IS NULL OR (@p_resp IS NOT NULL AND co.RESP = @p_resp) )    
    AND ( @p_codigo_lanc IS NULL OR @v_todos_cod_lanc = 'S' OR EXISTS ( SELECT 1  
                                                                       FROM LY_ITEM_LANC ra2  
                                                                       WHERE ra2.COBRANCA = co.COBRANCA  
                                                                         AND EXISTS ( SELECT 1 FROM dbo.fnMultiValue('I', @p_codigo_lanc, ',') WHERE ValorIni = ra2.CODIGO_LANC ) ) )  
	

	INSERT INTO #TEMP_RELATORIO
	SELECT  TOP 1 '' AS COD_UNIDADE, '' AS NOME_UNIDADE, '' AS TIPO_CURSO,'' AS COD_CENTROCUSTO,'' AS DESCR_CENTROCUSTO,'' AS COD_CURSO,'' AS NOME_CURSO, '' AS ALUNO
			,'' AS NOME_COMPL,0 AS COBRANCA, '' AS TIPO_COBRANCA, '' AS CODIGO_LANCAMENTO,'' AS DT_GERACAO_COB, '' AS RESP ,'' AS TITULAR, '' AS CPF_TITULAR, '' AS CPF_ALUNO
			, 0.00 AS VALOR_TOTAL_COBRANCA, 0.00 AS VALOR_FATURADO, 0.00 AS VALOR_ESTORNOS,0.00 AS VALOR_BOLSAS ,0.00 AS SALDO, '' AS DATA_DE_VENCIMENTO, '' AS DATA_DE_VENCIMENTO_ORIG, '' AS DATAREF
			,'' AS PERIODO_LETIVO,'' AS DATA_CANCEL_MATR, 0.00 AS VALOR_DIVIDA_PERIODO
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN -30 AND -1)		AS VENCIDO30
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN -60 AND -31)	AS VENCIDO60
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN -90 AND -61)	AS VENCIDO90
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN -120 AND -91)	AS VENCIDO120
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN -180 AND -121)	AS VENCIDO180
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN -365 AND -181)	AS VENCIDO365
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) < -365)					AS VENCIDO366
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) < 0)					AS TOTALVENCIDO
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN 0 AND 30)		AS AVENCER30
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN 31 AND 60)		AS AVENCER60
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN 61 AND 90)		AS AVENCER90
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN 91 AND 120)		AS AVENCER120
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN 121 AND 180)	AS AVENCER180
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) BETWEEN 181 AND 365)	AS AVENCER365
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) > 365)					AS AVENCER366
			,(SELECT ISNULL(SUM(SALDO),0) FROM #TEMP_RELATORIO WHERE DATEDIFF(DAY,ISNULL(@p_database,GETDATE()),DATA_DE_VENCIMENTO) >= 0)					AS TOTALAVENCER

IF @p_tipo_relatorio = '0'
BEGIN
	
	SELECT	DISTINCT
			COD_UNIDADE
			,TIPO_CURSO
			,TIPO_COBRANCA
			,CODIGO_LANCAMENTO
			,SUM(SALDO) AS SALDO
	FROM #TEMP_RELATORIO
	GROUP BY  COD_UNIDADE, TIPO_CURSO,TIPO_COBRANCA,CODIGO_LANCAMENTO
	HAVING SUM(SALDO) <> 0
	ORDER BY 1,2,3,4

	DROP TABLE #TEMP_RELATORIO


END

IF @p_tipo_relatorio = '1'
BEGIN

	SELECT	COD_UNIDADE,
			NOME_UNIDADE,
			TIPO_CURSO,
			COD_CENTROCUSTO,
			DESCR_CENTROCUSTO,
			COD_CURSO,
			NOME_CURSO,
			ALUNO,
			NOME_COMPL,
			COBRANCA,
			TIPO_COBRANCA,
			CODIGO_LANCAMENTO,
			RESP,
			TITULAR,
			CPF_TITULAR,
			CPF_ALUNO,
			VALOR_TOTAL_COBRANCA,
			VALOR_FATURADO,
			VALOR_BOLSAS,
			VALOR_ESTORNOS,
			SALDO,
			DT_GERACAO_COB,
			DATA_DE_VENCIMENTO,
			DATA_DE_VENCIMENTO_ORIG,
			DATAREF,
			PERIODO_LETIVO,
			DATA_CANCEL_MATR,
			VALOR_DIVIDA_PERIODO
	FROM #TEMP_RELATORIO
	WHERE COD_UNIDADE <> ('')
	ORDER BY 1,4,6,8
END
	
IF @p_tipo_relatorio = '2'
	BEGIN
		
		SELECT	VENCIDO30
				,VENCIDO60
				,VENCIDO90
				,VENCIDO120
				,VENCIDO180
				,VENCIDO365
				,VENCIDO366
				,TOTALVENCIDO
				,AVENCER30
				,AVENCER60
				,AVENCER90
				,AVENCER120
				,AVENCER180
				,AVENCER365
				,AVENCER366
				,TOTALAVENCER
		FROM #TEMP_RELATORIO
		WHERE COD_UNIDADE = ''
	
	END


END
GO

delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_Relat_ContasEmAbertoFinan'
and IDENTIFICACAO_CODIGO = '0003'
go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_Relat_ContasEmAbertoFinan' NOME
, '0003' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2018-11-28' DATA_CRIACAO
, 'Relatório - Contas em Aberto - Financeiro - Erro numeric' OBJETIVO
, 'Ana Paula' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO  