USE LYCEUM
GO
  
--CREATE VIEW FTC_VW_CONTATOS_ALUNOS_ATIVOS_RESP      
--AS 

SELECT	DISTINCT
		A.ALUNO AS MATRICULA,
		A.NOME_COMPL AS NOME,
		C.NOME AS CURSO,
		A.SERIE,
		A.TURNO,
		A.UNIDADE_FISICA,
		LRF.RESP AS CPF_RESPONSAVEL,
		LRF.TITULAR AS RESPONSÁVEL,
		ISNULL((P.DDD_FONE + '-' + p.FONE),'') AS TELEFONE,
		ISNULL((P.DDD_FONE_CELULAR + '-' + P.CELULAR),'') AS CELULAR,
		(SELECT P.E_MAIL FROM LY_PESSOA P WHERE P.CPF = LRF.CPF_TITULAR) AS EMAIL
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_COBRANCA lc ON LC.ALUNO = A.ALUNO
JOIN LY_RESP_FINAN lrf ON LRF.RESP = LC.RESP
WHERE 1=1
AND A.SIT_ALUNO = 'ATIVO' AND A.UNIDADE_FISICA = 'DOM-SSA'
ORDER BY 3,4

--SELECT * FROM LY_COBRANCA lc