    
ALTER VIEW FTC_VW_APONTAMENTO_DOCENTE_HORAS_ATIVIDADES      
AS   
  
SELECT DO.NUM_FUNC AS COD_DOCENTE  
  , DO.NOME_COMPL AS NOME  
  , PL.ANO  
  , PL.PERIODO AS SEMESTRE  
  , PL.DESCRICAO AS PERIODO  
  , UE.UNIDADE_ENS AS COD_UNIDADE  
  , UE.NOME_COMP AS UNIDADE  
  , ISNULL(C.CURSO,'') AS COD_CURSO  
  , ISNULL(C.NOME,'') AS CURSO  
  , DTA.CODATIV_DOCEN AS COD_ATIVIDADE  
  , DTA.DESCRICAO  
  , ISNULL(DAH.QTDE,0) AS QTDE  
  , DAH.TIPO_QTDE  
  , DAH.DIA_SEMANA  
  , CONVERT(VARCHAR(11),DAH.DATA_ULT_ALT,103)  AS DT_VINCULO   
  , CAST(ISNULL(DAH.TURNO,'')+' - '+CASE WHEN DAH.DIA_SEMANA = 2 THEN 'Segunda-Feira'  
           WHEN DAH.DIA_SEMANA = 3 THEN 'Terça-Feira'  
           WHEN DAH.DIA_SEMANA = 4 THEN 'Quarta-Feira'   
           WHEN DAH.DIA_SEMANA = 5 THEN 'Quinta-Feira'  
           WHEN DAH.DIA_SEMANA = 6 THEN 'Sexta-Feira'  
           WHEN DAH.DIA_SEMANA = 7 THEN 'Sábado'  
           WHEN DAH.DIA_SEMANA = 1 THEN 'Domingo' END+' - '+CONVERT(VARCHAR(5),DAH.HORA_INICIO,114) AS VARCHAR(30)) AS HORARIO  
FROM LY_DOCENTE DO  
JOIN LY_DOCENTE_ATIVIDADES_HORARIOS DAH ON DAH.NUM_FUNC = DO.NUM_FUNC  
JOIN LY_DOCENTE_TIPOS_ATIVIDADES DTA ON DTA.CODATIV_DOCEN = DAH.CODATIV_DOCEN  
JOIN HD_TABELAITEM TI ON TI.ITEM = DTA.GRUPO AND TI.TABELA = 'GrupoAtivDocente'  
JOIN LY_PERIODO_LETIVO PL ON PL.ANO = DAH.ANO AND PL.PERIODO = DAH.PERIODO  
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = DAH.UNIDADE  
LEFT JOIN LY_CURSO C ON C.CURSO = DAH.CURSO  
GO  