  
ALTER PROCEDURE dbo.FTC_Relat_AvalInstAcompanhamento  
(    
 @p_unidade VARCHAR(20),  
 @p_curso VARCHAR(20),
 @p_aplicacao VARCHAR(50),
 @p_tiporelatorio VARCHAR(1)  
)                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                
AS    
    
-- [INÍCIO]    
BEGIN    
 IF ISNULL(@p_unidade,'') = '' AND ISNULL(@p_curso,'') = ''  
 BEGIN  
	 IF @p_aplicacao in ('AVAL_INST3_2017', 'AVL_INST3_2018')  
	   BEGIN  
	   SELECT DISTINCT PQ.APLICACAO,
	   UF.UNIDADE_FIS AS COD_UNIDADE,  
	   UF.NOME_COMP AS NOME_UNIDADE,  
	   COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
	   COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_COORDENACAO CO ON PQ.CODIGO = CO.NUM_FUNC
	   JOIN LY_CURSO C ON C.CURSO = CO.CURSO  
	   JOIN LY_UNIDADE_FISICA UF ON UF.FL_FIELD_01 = CONVERT(NUMERIC,C.FACULDADE)
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
	   WHERE 1=1  
		 AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
		 AND PQ.APLICACAO = @p_aplicacao
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP  
	   ORDER BY 2,4  
	   END 

 	 IF @p_aplicacao in ('AVL_INST2_2017', 'AVAL_INST2_2018')  
	   BEGIN  
	   SELECT DISTINCT PQ.APLICACAO,
	   UF.UNIDADE_FIS AS COD_UNIDADE,  
	   UF.NOME_COMP AS NOME_UNIDADE,  
	  COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
	   COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_TURMA T ON PQ.CODIGO = T.NUM_FUNC
	   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
	   JOIN LY_CURSO C ON C.CURSO = T.CURSO  
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
	   WHERE 1=1  
		 AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
		 AND PQ.APLICACAO = @p_aplicacao
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP  
	   ORDER BY 2,4  
	   END  

	IF @p_aplicacao in ('AVALDOCENTE1_20182','AVALDOCENTE1_20172','AVALDOCM2_20172','AVALDOCM1_20172','AVAL_INST1_2017', 'AVAL_INST1_2018','AVALDOCENTE1_20181','AVALDOCM2_20181','AVALDOCM1_20181','AVALDOCM1_20182','AVALDOCM2_20182')  
	  BEGIN  
	   SELECT DISTINCT PQ.APLICACAO,
	   UF.UNIDADE_FIS AS COD_UNIDADE,  
	   UF.NOME_COMP AS NOME_UNIDADE,  
	   COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
	   COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_ALUNO A ON A.ALUNO = PQ.CODIGO  
	   JOIN LY_CURSO C ON C.CURSO = A.CURSO  
	   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA  
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
	   WHERE 1=1  
		 AND PQ.APLICACAO = @p_aplicacao
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP  
	   ORDER BY 2,4  
	   END  
     
	  IF @p_aplicacao IN ('AVALDOCENTE4_20172','AVALDOCENTE4_20181','AVALDOCENTE4_20182')  
	   BEGIN  
	   SELECT DISTINCT PQ.APLICACAO,   
	   UF.UNIDADE_FIS AS COD_UNIDADE,  
	   UF.NOME_COMP AS NOME_UNIDADE,  
	   COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
	   COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
	   JOIN LY_ALUNO A ON A.ALUNO = PQ.CODIGO  
	   JOIN LY_CURSO C ON C.CURSO = A.CURSO  
	   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA  
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
	   WHERE 1=1  
		 AND PQ.APLICACAO = @p_aplicacao
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP  
	   ORDER BY 2,4  
	  END  
     
	  IF @p_aplicacao IN ('AVALDOCENTE2_20172','AVALDOCENTE2_20181','AVALDOCENTE2_20182', 'AVALDOCENTE2_20182B', 'AVALDOCENTE5_20182', 'AVALDOCENTE5_20182B')
	   BEGIN  
	   SELECT DISTINCT PQ.APLICACAO,   
		 UF.UNIDADE_FIS AS COD_UNIDADE,  
		 UF.NOME_COMP AS NOME_UNIDADE,  
		 COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
		 COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
	   JOIN LY_TURMA T ON PQ.CODIGO = T.NUM_FUNC
	   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
	   JOIN LY_CURSO C ON C.CURSO = T.CURSO  
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
	   WHERE 1=1   
            AND C.TIPO IN ('GRADUACAO','TECNOLOGO')   
            AND T.ANO = (SELECT TOP 1 PL.ANO FROM LY_PERIODO_LETIVO AS PL WHERE CURRENT_TIMESTAMP BETWEEN PL.DT_INICIO AND DT_FIM AND PERIODO IN (1,2))
            AND T.SEMESTRE = (SELECT TOP 1 PL.PERIODO FROM LY_PERIODO_LETIVO AS PL WHERE CURRENT_TIMESTAMP BETWEEN PL.DT_INICIO AND DT_FIM AND PERIODO IN (1,2))
            AND PQ.APLICACAO = @p_aplicacao
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP
	   ORDER BY 2,4  
	   END  
    
	  IF @p_aplicacao IN ('AVALDOCENTE03_20172','AVALDOCENTE3_20181B','AVALDOCENTE3_20182') 
	   BEGIN  
	   SELECT DISTINCT PQ.APLICACAO,   
		 UF.UNIDADE_FIS AS COD_UNIDADE,  
		 UF.NOME_COMP AS NOME_UNIDADE,  
		 COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
		 COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
	   JOIN LY_COORDENACAO CO ON PQ.CODIGO = CO.NUM_FUNC  
	   JOIN LY_TURMA T ON T.CURSO = CO.CURSO  
	   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
	   JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.CURSO = CO.CURSO  
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
	   WHERE 1=1   
		 AND C.TIPO IN ('GRADUACAO','TECNOLOGO')   
		-- AND T.ANO = '2017'   
		 --AND T.SEMESTRE = '2'  
		 AND PQ.APLICACAO = @p_aplicacao
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP  
	   ORDER BY 2,4  
	   END  
	END  
   
 IF @p_tiporelatorio = '0' AND @p_unidade <> ''  
  BEGIN  
   IF @p_aplicacao in ('AVAL_INST3_2017', 'AVL_INST3_2018')  
   BEGIN  
   SELECT DISTINCT PQ.APLICACAO,   
     UF.UNIDADE_FIS AS COD_UNIDADE,  
     UF.NOME_COMP AS NOME_UNIDADE,  
     C.CURSO AS COD_CURSO,   
     C.NOME AS NOME_CURSO,   
     COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
     COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_COORDENACAO CO ON PQ.CODIGO = CO.NUM_FUNC
	   JOIN LY_CURSO C ON C.CURSO = CO.CURSO  
	   JOIN LY_UNIDADE_FISICA UF ON UF.FL_FIELD_01 = CONVERT(NUMERIC,C.FACULDADE)
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1   
     AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
     AND PQ.APLICACAO = @p_aplicacao
     AND (C.CURSO = ISNULL(@p_curso,C.CURSO) OR @p_curso = '')  
     AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP,C.CURSO,C.NOME  
   ORDER BY 2,4  
	END  
  
     IF @p_aplicacao in ('AVL_INST2_2017', 'AVAL_INST2_2018')  
	BEGIN  
      
	   SELECT DISTINCT PQ.APLICACAO,   
		 UF.UNIDADE_FIS AS COD_UNIDADE,  
		 UF.NOME_COMP AS NOME_UNIDADE,  
		 C.CURSO AS COD_CURSO,   
		 C.NOME AS NOME_CURSO,   
		 COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
		 COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_TURMA T ON PQ.CODIGO = T.NUM_FUNC
	   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
	   JOIN LY_CURSO C ON C.CURSO = T.CURSO  
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL   
	   WHERE 1=1   
		 AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
		 AND PQ.APLICACAO = @p_aplicacao
		 AND (C.CURSO = ISNULL(@p_curso,C.CURSO) OR @p_curso = '')  
		 AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP,C.CURSO,C.NOME  
	   ORDER BY 2,4  
     
	 END 
   IF @p_aplicacao in ('AVALDOCENTE1_20182','AVALDOCENTE1_20172','AVALDOCM2_20172','AVALDOCM1_20172','AVAL_INST1_2017', 'AVAL_INST1_2018','AVALDOCENTE1_20181','AVALDOCM2_20181','AVALDOCM1_20181','AVALDOCM1_20182','AVALDOCM2_20182')  
   BEGIN  
      
   SELECT DISTINCT PQ.APLICACAO,    
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
   COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
   FROM LY_PARTICIPACAO_QUEST PQ  
   JOIN LY_ALUNO A ON A.ALUNO = PQ.CODIGO  
   JOIN LY_CURSO C ON C.CURSO = A.CURSO  
   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA  
   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1  
     AND PQ.APLICACAO = @p_aplicacao
     AND (A.CURSO = ISNULL(@p_curso,A.CURSO) OR @p_curso = '')  
     AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP,C.CURSO,C.NOME  
   ORDER BY 2,4  
     
   END  
   IF @p_aplicacao IN ('AVALDOCENTE4_20172','AVALDOCENTE4_20181','AVALDOCENTE4_20182')  
   BEGIN  
      
   SELECT DISTINCT PQ.APLICACAO,   
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
   COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
   FROM LY_PARTICIPACAO_QUEST PQ  
   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
   JOIN LY_ALUNO A ON A.ALUNO = PQ.CODIGO  
   JOIN LY_CURSO C ON C.CURSO = A.CURSO  
   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA  
   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1  
     AND PQ.APLICACAO = @p_aplicacao
     AND (A.CURSO = ISNULL(@p_curso,A.CURSO) OR @p_curso = '')  
     AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP,C.CURSO,C.NOME  
   ORDER BY 2,4  
     
   END  
     
   IF @p_aplicacao IN ('AVALDOCENTE2_20172','AVALDOCENTE2_20181','AVALDOCENTE2_20182', 'AVALDOCENTE2_20182B', 'AVALDOCENTE5_20182', 'AVALDOCENTE5_20182B')
   BEGIN  
      
	   SELECT DISTINCT PQ.APLICACAO,   
		 UF.UNIDADE_FIS AS COD_UNIDADE,  
		 UF.NOME_COMP AS NOME_UNIDADE,  
		 C.CURSO AS COD_CURSO,   
		 C.NOME AS NOME_CURSO,   
		 COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
		 COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
	   FROM LY_PARTICIPACAO_QUEST PQ  
	   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
	   JOIN LY_TURMA T ON PQ.CODIGO = T.NUM_FUNC  
	   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
	   JOIN LY_CURSO C ON C.CURSO = T.CURSO  
	   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
	   WHERE 1=1   
            AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
            AND T.ANO = (SELECT TOP 1 PL.ANO FROM LY_PERIODO_LETIVO AS PL WHERE CURRENT_TIMESTAMP BETWEEN PL.DT_INICIO AND DT_FIM AND PERIODO IN (1,2))
            AND T.SEMESTRE = (SELECT TOP 1 PL.PERIODO FROM LY_PERIODO_LETIVO AS PL WHERE CURRENT_TIMESTAMP BETWEEN PL.DT_INICIO AND DT_FIM AND PERIODO IN (1,2))  
            AND PQ.APLICACAO = @p_aplicacao
            AND (C.CURSO = ISNULL(@p_curso,C.CURSO) OR @p_curso = '')  
            AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
	   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP,C.CURSO,C.NOME  
	   ORDER BY 2,4  
     
   END  
     
   IF @p_aplicacao IN ('AVALDOCENTE03_20172','AVALDOCENTE3_20181B','AVALDOCENTE3_20182') 
   BEGIN  
      
   SELECT DISTINCT PQ.APLICACAO,   
     UF.UNIDADE_FIS AS COD_UNIDADE,  
     UF.NOME_COMP AS NOME_UNIDADE,  
     C.CURSO AS COD_CURSO,   
     C.NOME AS NOME_CURSO,   
     COUNT(DISTINCT PQ.CODIGO) AS QTD_APLICADOS,   
     COUNT(DISTINCT PQ2.CODIGO) AS QTD_RESPONDIDOS  
   FROM LY_PARTICIPACAO_QUEST PQ  
   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
   JOIN LY_COORDENACAO CO ON PQ.CODIGO = CO.NUM_FUNC  
   JOIN LY_TURMA T ON T.CURSO = CO.CURSO  
   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
   JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.CURSO = CO.CURSO  
   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1   
     AND C.TIPO IN ('GRADUACAO','TECNOLOGO')  
    -- AND T.ANO = '2017'   
     --AND T.SEMESTRE = '2'  
     AND PQ.APLICACAO = @p_aplicacao
     AND (C.CURSO = ISNULL(@p_curso,C.CURSO) OR @p_curso = '')  
     AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   GROUP BY PQ.APLICACAO,UF.UNIDADE_FIS,UF.NOME_COMP,C.CURSO,C.NOME  
   ORDER BY 2,4  
     
   END  
     
  END  
   
 IF @p_tiporelatorio = '1' AND @p_unidade <> ''  
  BEGIN 
     
  IF @p_aplicacao in ('AVAL_INST3_2017', 'AVL_INST3_2018')  
   BEGIN  
     
   SELECT DISTINCT PQ.APLICACAO,   
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   CO.NUM_FUNC AS CODIGO,  
   D.NOME_COMPL AS NOME,   
   ISNULL((SELECT TOP 1 'S' FROM LY_PARTICIPACAO_QUEST WHERE CODIGO = PQ2.CODIGO),'N') AS PARTICIPOU,  
   ISNULL(CONVERT(VARCHAR(10),PQ2.DATA_PART,103),'') AS DATA_PARTICIPACAO  
	FROM LY_PARTICIPACAO_QUEST PQ  
	JOIN LY_COORDENACAO CO ON PQ.CODIGO = CO.NUM_FUNC
	JOIN LY_DOCENTE D ON PQ.CODIGO = D.NUM_FUNC
	JOIN LY_CURSO C ON C.CURSO = CO.CURSO  
	JOIN LY_UNIDADE_FISICA UF ON UF.FL_FIELD_01 = CONVERT(NUMERIC,C.FACULDADE)
	LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1   
   AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
   AND PQ.APLICACAO = @p_aplicacao
   AND (C.CURSO = ISNULL(@p_curso,C.CURSO) OR @p_curso = '')  
   AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '') 
   AND UF.UNIDADE_FIS NOT IN ('FTC-IGT') -- Removida a unidade FTC Iguatemi pois não deve constar no relatório de acompanhamento, já que é a mesma unidade física da FCS - Comercio | HelpDesk: 56003 @author Lucas Trindade @date 2018-11-09
   ORDER BY 2,4  
     
   END 
   IF @p_aplicacao in ('AVL_INST2_2017', 'AVAL_INST2_2018')  
   BEGIN  
     
   SELECT DISTINCT PQ.APLICACAO,   
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   D.NUM_FUNC AS CODIGO,  
   D.NOME_COMPL AS NOME,   
   ISNULL((SELECT TOP 1 'S' FROM LY_PARTICIPACAO_QUEST WHERE CODIGO = PQ2.CODIGO),'N') AS PARTICIPOU,  
   ISNULL(CONVERT(VARCHAR(10),PQ2.DATA_PART,103),'') AS DATA_PARTICIPACAO  
	FROM LY_PARTICIPACAO_QUEST PQ  
	JOIN LY_TURMA T ON PQ.CODIGO = T.NUM_FUNC
	JOIN LY_DOCENTE D ON D.NUM_FUNC = PQ.CODIGO
	JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
	JOIN LY_CURSO C ON C.CURSO = T.CURSO  
	LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1 
	AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
    AND PQ.APLICACAO = @p_aplicacao
    AND (T.CURSO = ISNULL(@p_curso,T.CURSO) OR @p_curso = '')  
    AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   ORDER BY 2,4  
   END  
  
   
   IF @p_aplicacao in ('AVALDOCENTE1_20182','AVALDOCENTE1_20172','AVALDOCM2_20172','AVALDOCM1_20172','AVAL_INST1_2017', 'AVAL_INST1_2018','AVALDOCENTE1_20181','AVALDOCM2_20181','AVALDOCM1_20181','AVALDOCM1_20182','AVALDOCM2_20182')  
   BEGIN  
     
   SELECT DISTINCT PQ.APLICACAO,      
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   A.ALUNO AS CODIGO,  
   A.NOME_COMPL AS NOME,   
   ISNULL((SELECT TOP 1 'S' FROM LY_PARTICIPACAO_QUEST WHERE CODIGO = PQ2.CODIGO),'N') AS PARTICIPOU,  
   ISNULL(CONVERT(VARCHAR(10),PQ2.DATA_PART,103),'') AS DATA_PARTICIPACAO  
   FROM LY_PARTICIPACAO_QUEST PQ  
   JOIN LY_ALUNO A ON A.ALUNO = PQ.CODIGO  
   JOIN LY_CURSO C ON C.CURSO = A.CURSO  
   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA  
   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1  
     AND PQ.APLICACAO = @p_aplicacao
     AND (A.CURSO = ISNULL(@p_curso,A.CURSO) OR @p_curso = '')  
     AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   ORDER BY 2,4  
     
   END  
     
  IF @p_aplicacao IN ('AVALDOCENTE4_20172','AVALDOCENTE4_20181','AVALDOCENTE4_20182')  
   BEGIN  
     
   SELECT DISTINCT PQ.APLICACAO,   
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   A.ALUNO AS CODIGO,  
   A.NOME_COMPL AS NOME,   
   ISNULL((SELECT TOP 1 'S' FROM LY_PARTICIPACAO_QUEST WHERE CODIGO = PQ2.CODIGO),'N') AS PARTICIPOU,  
   ISNULL(CONVERT(VARCHAR(10),PQ2.DATA_PART,103),'') AS DATA_PARTICIPACAO  
   FROM LY_PARTICIPACAO_QUEST PQ  
   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
   JOIN LY_ALUNO A ON A.ALUNO = PQ.CODIGO  
   JOIN LY_CURSO C ON C.CURSO = A.CURSO  
   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA  
   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1  
     AND PQ.APLICACAO = @p_aplicacao  
     AND (A.CURSO = ISNULL(@p_curso,A.CURSO) OR @p_curso = '')  
     AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   ORDER BY 2,4  
     
   END  
     
  IF @p_aplicacao IN ('AVALDOCENTE2_20172','AVALDOCENTE2_20181','AVALDOCENTE2_20182', 'AVALDOCENTE2_20182B', 'AVALDOCENTE5_20182', 'AVALDOCENTE5_20182B')
   BEGIN  

   SELECT DISTINCT PQ.APLICACAO,   
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   D.NUM_FUNC AS CODIGO,  
   CONCAT(D.NOME_COMPL, '(', T.TURMA, ' - ', T.DISCIPLINA, ') ') AS NOME,   
   ISNULL((SELECT TOP 1 'S' FROM LY_PARTICIPACAO_QUEST WHERE CODIGO = PQ2.CODIGO),'N') AS PARTICIPOU,  
   ISNULL(CONVERT(VARCHAR(10),PQ2.DATA_PART,103),'') AS DATA_PARTICIPACAO  
   FROM LY_PARTICIPACAO_QUEST PQ  
   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
   JOIN LY_TURMA T ON PQ.CODIGO = T.NUM_FUNC  
   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
   JOIN LY_CURSO C ON C.CURSO = T.CURSO  
   JOIN LY_DOCENTE D ON D.NUM_FUNC = T.NUM_FUNC  
   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE    1=1 
            AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
            AND T.ANO = (SELECT TOP 1 PL.ANO FROM LY_PERIODO_LETIVO AS PL WHERE CURRENT_TIMESTAMP BETWEEN PL.DT_INICIO AND DT_FIM AND PERIODO IN (1,2))
            AND T.SEMESTRE = (SELECT TOP 1 PL.PERIODO FROM LY_PERIODO_LETIVO AS PL WHERE CURRENT_TIMESTAMP BETWEEN PL.DT_INICIO AND DT_FIM AND PERIODO IN (1,2))
            AND PQ.APLICACAO = @p_aplicacao  
            AND (T.CURSO = ISNULL(@p_curso,T.CURSO) OR @p_curso = '')  
            AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   ORDER BY 2,4  
     
   END  
     
  IF @p_aplicacao IN ('AVALDOCENTE03_20172','AVALDOCENTE3_20181B','AVALDOCENTE3_20182') 
   BEGIN  
     
   SELECT DISTINCT PQ.APLICACAO,   
   UF.UNIDADE_FIS AS COD_UNIDADE,  
   UF.NOME_COMP AS NOME_UNIDADE,  
   C.CURSO AS COD_CURSO,   
   C.NOME AS NOME_CURSO,   
   CO.NUM_FUNC AS CODIGO,  
   D.NOME_COMPL AS NOME,   
   ISNULL((SELECT TOP 1 'S' FROM LY_PARTICIPACAO_QUEST WHERE CODIGO = PQ2.CODIGO),'N') AS PARTICIPOU,  
   ISNULL(CONVERT(VARCHAR(10),PQ2.DATA_PART,103),'') AS DATA_PARTICIPACAO  
   FROM LY_PARTICIPACAO_QUEST PQ  
   JOIN LY_QUESTAO_APLICADA QA ON QA.APLICACAO = PQ.APLICACAO AND QA.TIPO_QUESTIONARIO = PQ.TIPO_QUESTIONARIO AND QA.PAR_TIPO_OBJETO = PQ.TIPO_OBJETO AND QA.PAR_CODIGO = PQ.CODIGO  
   JOIN LY_COORDENACAO CO ON PQ.CODIGO = CO.NUM_FUNC  
   JOIN LY_DOCENTE D ON D.NUM_FUNC = CO.NUM_FUNC  
   JOIN LY_TURMA T ON T.CURSO = CO.CURSO  
   JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE  
   JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.CURSO = CO.CURSO  
   LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL  
   WHERE 1=1   
   AND C.TIPO IN ('GRADUACAO','TECNOLOGO')   
   --AND T.ANO = '2017'   
   --AND T.SEMESTRE = '2'  
   AND PQ.APLICACAO = @p_aplicacao
   AND (T.CURSO = ISNULL(@p_curso,T.CURSO) OR @p_curso = '')  
   AND (C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE) OR @p_unidade = '')  
   ORDER BY 2,4  
     
   END  
  END  
END 
-- [FIM]

DELETE FROM LY_CUSTOM_CLIENTE WHERE NOME = 'FTC_Relat_AvalInstAcompanhamento' AND IDENTIFICACAO_CODIGO = '0003'

INSERT INTO LY_CUSTOM_CLIENTE (NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE) 

SELECT 
  'FTC_Relat_AvalInstAcompanhamento' NOME , 
  '0003' IDENTIFICAO_CODIGO , 
  'Lucas Trindade' AUTOR,  
  '2018-11-06' DATA_CRIACAO, 
  'Relatorio Acompanhamento Avaliacao Docente' OBJETIVO, 
  'Dayse Christyanne' SOLICITADO_POR,
  'S' ATIVO, 
  'RELATORIO' TIPOCOMPONENTE, 
  'CLIENTE' TIPO, 
  'FTC' CLIENTE

GO  

INSERT INTO LY_CUSTOM_CLIENTE (NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE) 
SELECT 
  'FTC_Relat_AvalInstAcompanhamento' NOME , 
  '0004' IDENTIFICAO_CODIGO , 
  'Lucas Trindade' AUTOR,  
  '2018-11-09' DATA_CRIACAO, 
  'Relatorio Acompanhamento Avaliacao Docente' OBJETIVO, 
  'Dayse Christyanne' SOLICITADO_POR,
  'S' ATIVO, 
  'RELATORIO' TIPOCOMPONENTE, 
  'CLIENTE' TIPO, 
  'FTC' CLIENTE

GO  