USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_SP_csvSituacaoAlunos '))
   exec('CREATE PROCEDURE [dbo].[FTC_SP_csvSituacaoAlunos] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE dbo.FTC_SP_csvSituacaoAlunos     
(      
  @P_ANO VARCHAR(4)
, @P_SEMESTRE VARCHAR(1)
, @P_FACULDADE VARCHAR(20)
, @P_TIPO_CURSO VARCHAR(20)  
, @P_CURSO  VARCHAR(20)  
, @P_TURNO  VARCHAR(20)  
, @P_CURRICULO VARCHAR(20)  
)      
AS      
-- [INÍCIO]              
BEGIN      
  
SET NOCOUNT ON  
  
  SELECT   
              PM.ANO																	AS [ANO], 
			  PM.SEMESTRE																AS [SEMESTRE], 
			  C.CURSO																	AS [CURSO],  
			  C.NOME																	AS [NOME_CURSO], 
			  A.CURRICULO																AS [CURRICULO], 
			  A.TURNO																	AS [TURNO],
			  A.SERIE																	AS [SERIE_ALUNO], 
			  C.FACULDADE																AS [UNIDADE_ENSINO_ALUNO], 
              UE.NOME_COMP																AS [NOME_UNIDADE_ENSINO_ALUNO], 
			  PM.SIT_MATRICULA															AS [SIT_MATRICULA],
			  A.ANO_INGRESSO															AS [ANO_INGRESSO],
			  A.SEM_INGRESSO															AS [SEM_INGRESSO],
			  A.TIPO_INGRESSO															AS [TIPO_INGRESSO], 
			  A.ALUNO																	AS [ALUNO], 
			  PES.NOME_COMPL															AS [NOME_ALUNO],
              PES.CPF																	AS [CPF],
			  PES.RG_NUM																AS [RG], 
			  A.ANOCONCL_2G																AS [ANO_CONCLUSAO_2G], 
			  PES.E_MAIL																AS [E_MAIL],
			  PES.ENDERECO																AS [ENDERECO],
              PES.END_NUM																AS [NUMERO],
              PES.END_COMPL																AS [COMPLEMENTO],
              PES.CEP																	AS [CEP],
              HM.NOME																	AS [CIDADE],
              HM.UF																		AS [ESTADO],	
              PES.FONE																	AS [FONE], 
			  PES.CELULAR																AS [CELULAR], 
			  ISNULL(T.CURSO,'')														AS [CURSO_TURMA],
			  (SELECT NOME FROM LY_CURSO C1 WHERE C1.CURSO = T.CURSO)					AS NOME_CURSO_TURMA, 
              PM.DISCIPLINA																AS [DISCIPLINA], 
			  D.NOME																	AS [NOME_DISCIPLINA], 
			  ISNULL(PM.TURMA,'')														AS [TURMA],
			  ROUND(ISNULL(LVSP.CUSTO_UNITARIO*D.CREDITOS,0),2)							AS [VALOR_DISCIPLINA],
			  ISNULL(T.UNIDADE_RESPONSAVEL,'')											AS [UNIDADE_ENSINO_TURMA], 
			  ISNULL(T.NUM_FUNC,0)														AS [COD_DOCENTE_TURMA],
			  ISNULL(DOC.NOME_COMPL,'')													AS [NOME_DOCENTE_TURMA],
			  PM.CONFIRMADA																AS [CONFIRMADA],
              A.SIT_ALUNO																AS [SIT_ALUNO],
              ISNULL((SELECT TOP 1 'S' 
					FROM LY_ITEM_LANC IL
					JOIN LY_LANC_DEBITO LD
						ON IL.LANC_DEB = LD.LANC_DEB 
					JOIN VW_COBRANCA C
						ON IL.COBRANCA = C.COBRANCA
				WHERE LD.ALUNO = PM.ALUNO
				AND LD.ANO_REF = PM.ANO
				AND LD.PERIODO_REF = PM.SEMESTRE
				AND C.VALOR = 0
				AND LD.LANC_DEB = PM.LANC_DEB
				GROUP BY IL.COBRANCA
				HAVING MAX(IL.PARCELA) = 1
				),'N')																	AS [PAGO],
				ISNULL(CA.CONTRATO_ACEITO,'X')											AS [CONTRATO_ACEITO]
FROM (SELECT ANO, SEMESTRE, DISCIPLINA, TURMA, ALUNO, SIT_MATRICULA, LANC_DEB, DT_ULTALT , SERIE_CALCULO, COBRANCA_SEP, SIT_DETALHE, GRUPO_ELETIVA , DT_INSERCAO, 'S' AS CONFIRMADA
FROM VW_MATRICULA_E_PRE_MATRICULA
UNION
SELECT ANO, SEMESTRE, DISCIPLINA, TURMA, ALUNO, SITUACAO_HIST AS SIT_MATRICULA, LANC_DEB, DT_ULTALT, SERIE AS SERIE_CALCULO, COBRANCA_SEP, SIT_DETALHE, GRUPO_ELETIVA, DT_MATRICULA AS DT_INSERCAO, 'S' CONFIRMADA
FROM LY_HISTMATRICULA
) PM	
JOIN LY_ALUNO A							-- PARA JOIN COM CURSO
	ON PM.ALUNO = A.ALUNO
JOIN LY_PESSOA PES
    ON PES.PESSOA = A.PESSOA
JOIN LY_CURSO C							-- PARA SABER NOME DO CURSO E JOIN COM UNIDADE ENSINO
	ON A.CURSO = C.CURSO
JOIN LY_DISCIPLINA D
	ON PM.DISCIPLINA = D.DISCIPLINA
JOIN LY_UNIDADE_ENSINO UE				-- PARA SABER NOME UNIDADE ENSINO
	ON C.FACULDADE = UE.UNIDADE_ENS
LEFT JOIN LY_TURMA T 
	ON T.TURMA = PM.TURMA AND T.DISCIPLINA = PM.DISCIPLINA AND T.ANO = PM.ANO AND T.SEMESTRE = PM.SEMESTRE
JOIN HD_MUNICIPIO HM
	ON HM.MUNICIPIO = PES.END_MUNICIPIO
LEFT JOIN LY_DOCENTE DOC 
	ON DOC.NUM_FUNC = T.NUM_FUNC
JOIN LY_SERIE LS 
	ON LS.CURSO = A.CURSO AND LS.TURNO = A.TURNO AND LS.CURRICULO = A.CURRICULO AND LS.SERIE = PM.SERIE_CALCULO
LEFT JOIN LY_VALOR_SERV_PERIODO LVSP 
	ON LVSP.SERVICO = LS.SERVICO_CRED AND LVSP.ANO = PM.ANO AND LVSP.PERIODO = PM.SEMESTRE
LEFT JOIN LY_CONTRATO_ALUNO CA 
	ON CA.ALUNO = PM.ALUNO AND CA.ANO = PM.ANO AND CA.PERIODO = PM.SEMESTRE
WHERE 1=1--C.ATIVO  = 'S' AND A.SIT_ALUNO = 'Ativo'
--AND (CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) >= '20162' OR A.UNIDADE_FISICA IN ('DOM-SSA','DOM-JEQ','DOM-VIC','DOM-PET'))
AND (@P_ANO IS NOT NULL AND PM.ANO = @P_ANO)
AND (@P_SEMESTRE IS NOT NULL AND PM.SEMESTRE = @P_SEMESTRE)
AND (@P_FACULDADE IS NOT NULL AND C.FACULDADE = @P_FACULDADE) 
AND (@P_TIPO_CURSO IS NOT NULL AND C.TIPO = @P_TIPO_CURSO)  
AND ((@P_CURSO IS NOT NULL AND C.CURSO = @P_CURSO) OR @P_CURSO IS NULL)
AND ((@P_TURNO IS NOT NULL AND A.TURNO = @P_TURNO) OR @P_TURNO IS NULL)  
AND ((@P_CURRICULO IS NOT NULL AND A.CURRICULO = @P_CURRICULO) OR @P_CURRICULO IS NULL)   
 
  
ORDER BY C.FACULDADE, UE.NOME_COMP, C.CURSO, C.NOME
  
  
SET NOCOUNT OFF  
  
END              
GO
-- [FIM]      



--##
--## PARAMETRIZAÇÃO/CADASTRO DA LISTA NO LYCEUM
--##

DECLARE @V_CONSULTA_DINAMICA INT
DECLARE @V_NOME_CONSULTA_DINAMICA varchar(100)

-- Colocar nome da lista (que será apresentada no combo)
set @V_NOME_CONSULTA_DINAMICA ='Custom - Situação Alunos - Mátricula / Pré-Matrícula'

-- Consulta ID da Lista
SELECT @V_CONSULTA_DINAMICA = ID FROM LY_CONSULTA_DINAMICA WHERE TITULO = @V_NOME_CONSULTA_DINAMICA

-- armazena padrões de acesso
SELECT PADACES
INTO #TEMP_CONSULTA_DINAMICA
FROM LY_CONSULTA_DINAMICA_PADACES WHERE ID = @V_CONSULTA_DINAMICA


DELETE LY_CONSULTA_DINAMICA_PADACES WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA
DELETE LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA

BEGIN

IF NOT EXISTS(SELECT 1 FROM LY_CONSULTA_DINAMICA C WHERE C.TITULO = @V_NOME_CONSULTA_DINAMICA)
INSERT INTO LY_CONSULTA_DINAMICA(TITULO, TIPO, STORED_PROCEDURE)
VALUES(@V_NOME_CONSULTA_DINAMICA,'CSV','sp:FTC_SP_csvSituacaoAlunos(@P_ANO@,@P_SEMESTRE@,@P_FACULDADE@,@P_TIPO_CURSO@,@P_CURSO@,@P_TURNO@,@P_CURRICULO@)')

SET @V_CONSULTA_DINAMICA = @@IDENTITY

-- Insere padrões de acesso
INSERT INTO LY_CONSULTA_DINAMICA_PADACES (ID_CONSULTA_DINAMICA, PADACES)
SELECT @V_CONSULTA_DINAMICA, PADACES FROM #TEMP_CONSULTA_DINAMICA

-- Insere parametros

	--@p_ano				T_ANO,
	--@p_semestre			T_Semestre2,
	--@p_unidade_ensino	T_codigo,
	--@p_tipo_curso		T_codigo,
	--@p_curso			T_codigo,
	--@p_turno			T_codigo,
	--@p_curriculo		T_codigo,	
	--@p_sit_matricula	T_codigo,
	--@p_tem_turma		varchar(1)

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 1, 'P_ANO', 5, 'Ano', 'S', 'SELECT DISTINCT ANO AS CODIGO, (''ANO: '' + convert(varchar,ANO)) AS DESCRICAO FROM LY_PERIODO_LETIVO ORDER BY ANO DESC', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 2, 'P_SEMESTRE', 5, 'Período', 'S', 'SELECT DISTINCT PERIODO AS CODIGO, (''PERÍODO: '' + convert(varchar,PERIODO)) AS DESCRICAO FROM LY_PERIODO_LETIVO WHERE ANO = ISNULL(@p_ano@,ANO) ORDER BY PERIODO', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 3, 'P_FACULDADE', 5, 'Unidade Ensino', 'S', 'Select unidade_ens as codigo, nome_comp as descricao from ly_unidade_ensino order by unidade_ens', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 4, 'P_TIPO_CURSO', 5, 'Tipo de Curso', 'S', 'Select tipo as codigo, descricao from ly_tipo_curso order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 5, 'P_CURSO', 5, 'Curso', 'N', 'Select Curso as codigo, nome as descricao from ly_curso where tipo = isnull(@p_tipo_curso@,tipo) and faculdade = (@p_faculdade@,faculdade) order by tipo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 6, 'P_TURNO', 5, 'Turno', 'N', 'Select turno as codigo, descricao from ly_turno order by turno', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

INSERT INTO LY_CONSULTA_DINAMICA_PARAMETROS(ID_CONSULTA_DINAMICA,ORDEM,PARAMETRO,TIPO,DESCRICAO,OBRIGATORIO,SQL_TEXTO,COL_VALOR,COL_DESCR)
SELECT @V_CONSULTA_DINAMICA, 7, 'P_CURRICULO', 5, 'Curriculo', 'N', 'Select Curriculo as CODIGO, (''Currículo: '' + convert(varchar,Curriculo)) AS DESCRICAO FROM LY_curriculo WHERE curso = ISNULL(@p_curso@,curso) AND turno = ISNULL(@p_turno@,turno) and dt_extincao is null ORDER BY curriculo', 'CODIGO' COL_VALOR, 'DESCRICAO' COL_DESCR

--SELECT * FROM LY_CONSULTA_DINAMICA WHERE ID = @V_CONSULTA_DINAMICA
--SELECT * FROM LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID_CONSULTA_DINAMICA = @V_CONSULTA_DINAMICA

drop table  #TEMP_CONSULTA_DINAMICA

END
GO

delete from LY_CUSTOM_CLIENTE
where NOME = 'FTC_SP_csvSituacaoAlunos'
and IDENTIFICACAO_CODIGO = '0001'
go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_SP_csvSituacaoAlunos' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2016-11-08' DATA_CRIACAO
, 'ListaNG - Situação Alunos Macro' OBJETIVO
, 'Simone Oliveira, André Britto' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO 