USE LYCEUM
GO

--EXEC FTC_Relat_StatusMatricula 2018,2,NULL,NULL,NULL,NULL,NULL,NULL,1

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_StatusMatricula'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_StatusMatricula] AS BEGIN SET NOCOUNT OFF; END')
GO 
      
ALTER PROCEDURE dbo.FTC_Relat_StatusMatricula       
(            
  @p_ano VARCHAR(4)      
, @p_semestre VARCHAR(2)      
, @p_unidade VARCHAR(20)      
, @p_tipo VARCHAR(20)        
, @p_curso  VARCHAR(20)        
, @p_turno  VARCHAR(20)
, @p_ano_ingresso numeric(4)
, @p_sem_ingresso numeric(2)        
, @p_tipo_relatorio VARCHAR(1)
)            
AS            
-- [INÍCIO]                    
BEGIN            
        
SET NOCOUNT ON   

CREATE TABLE #TEMP_ALUNOS 
(
	[UNIDADE_ENSINO_ALUNO]	VARCHAR(20),
	[NOME_UNIDADE_ENSINO_ALUNO] VARCHAR(100),
	[CURSO] VARCHAR(20),
	[NOME_CURSO] VARCHAR(100),
	[SERIE] NUMERIC(10),
	[TURNO] VARCHAR(20),
	[CONCURSO] VARCHAR(20),
	[DESC_CONCURSO] VARCHAR(100),
	[TIPO_ALUNO] VARCHAR(50),
	[TIPO_INGRESSO] VARCHAR(50),
	[PAGO] NUMERIC(10),
	[NAO_PAGO] NUMERIC(10),
	[BOLSISTA] VARCHAR(1),
	[DATA_PAGAMENTO] DATETIME,
	[SIT_MATRICULA] VARCHAR(20),
	[DATA_MATRICULA] DATETIME,
	[ORIGEM_MATRICULA] VARCHAR(50),
	[DATA_INGRESSO] DATETIME,
	[ALUNO] VARCHAR(20),
	[CPF] VARCHAR(20),
	[NOME_ALUNO] VARCHAR(100),
	[CURRICULO] VARCHAR(20),
	[DATA_NASC] DATETIME,
	[RG] VARCHAR(20),
	[E_MAIL] VARCHAR(100),
	[ENDERECO] VARCHAR(50),
	[NUMERO] VARCHAR(20),
	[COMPLEMENTO] VARCHAR(50),
	[CEP] VARCHAR(9),
	[BAIRRO] VARCHAR(50),
	[CIDADE] VARCHAR(100),
	[ESTADO] VARCHAR(2),
	[FONE] VARCHAR(30),
	[CELULAR] VARCHAR(30),
	[CONTRATO_ACEITO] VARCHAR(1)

)



--ALIMENTANDO TEMPORARIA COM TODOS OS ALUNOS DO FILTRO
	INSERT INTO #TEMP_ALUNOS
	SELECT  DISTINCT      
		 C.FACULDADE						AS [UNIDADE_ENSINO_ALUNO],       
		 A.UNIDADE_FISICA					AS [NOME_UNIDADE_ENSINO_ALUNO],      
		 C.CURSO							AS [CURSO],        
		 C.NOME								AS [NOME_CURSO],
		 A.SERIE							AS [SERIE],
		 A.TURNO							AS [TURNO],
		 A.CONCURSO							AS [CONCURSO],
		 ISNULL(CON.DESCRICAO,'')			AS [DESC_CONCURSO],
	 CASE	WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO'
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO' 
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'CALOURO'
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'CALOURO' END AS TIPO_ALUNO,     
	 CASE	WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO'
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO' 
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN A.TIPO_INGRESSO
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN A.TIPO_INGRESSO END AS TIPO_INGRESSO,    
		 1								AS [PAGO],
		 0								AS [NAO_PAGO],
		 ISNULL((SELECT TOP 1 'S' FROM LY_BOLSA WHERE ALUNO = A.ALUNO AND DATA_CANCEL IS NULL AND (ANOFIM >= YEAR(GETDATE()) OR ANOFIM IS NULL) AND (MESFIM >= MONTH(GETDATE()) OR MESFIM IS NULL)),'N') AS [BOLSISTA],
		 (SELECT MIN(IC.DATA)
				FROM LY_ITEM_CRED IC
				JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA 
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				JOIN VW_COBRANCA VW ON VW.COBRANCA = IC.COBRANCA AND VW.COBRANCA = IL.COBRANCA
				WHERE IL.CODIGO_LANC IN ('MS','MS_EB')
				AND IL.ITEM_ESTORNADO IS NULL AND IC.ITEM_ESTORNADO IS NULL
				AND VW.VALOR <=1
				AND VW.ALUNO = A.ALUNO	
				AND LD.ANO_REF = @p_ano
				AND LD.PERIODO_REF = @p_semestre			
				)					AS [DATA_PAGAMENTO],
		 ISNULL((SELECT TOP 1 'Matriculado' FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre AND SIT_MATRICULA IN ('Matriculado','Aprovado','Rep Nota','Rep Falta','Trancado')),'Pre-Matric') AS [SIT_MATRICULA],
		 (SELECT MIN(DT_INSERCAO) FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre) AS [DATA_MATRICULA],
		 CASE WHEN PM2.OBS IS NULL OR RTRIM(LTRIM(PM2.OBS)) = '' THEN 'Secretaria' ELSE 'Aluno Online' END AS [ORIGEM_MATRICULA],
		 A.DT_INGRESSO AS [DATA_INGRESSO],
		 PM.ALUNO,
		 P.CPF,
		 A.NOME_COMPL AS NOME_ALUNO,
		 A.CURRICULO,
		 P.DT_NASC			AS [DATA_NASC],
		 P.RG_NUM              AS [RG],     
		 P.E_MAIL                AS [E_MAIL],    
		 P.ENDERECO                AS [ENDERECO],    
		 P.END_NUM                AS [NUMERO],    
		 P.END_COMPL            AS [COMPLEMENTO],    
		 P.CEP					AS [CEP],    
		 P.BAIRRO			AS [BAIRRO],  
		 HM.NOME                 AS [CIDADE],    
		 HM.UF                  AS [ESTADO],     
		 P.FONE                 AS [FONE],     
		 P.CELULAR                AS [CELULAR],
		 ISNULL((SELECT TOP 1 CONTRATO_ACEITO FROM LY_CONTRATO_ALUNO WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND PERIODO = @p_semestre),'N') AS [CONTRATO_ACEITO] 
		 --INTO #TEMP_ALUNOS
	FROM LY_ALUNO A 
	JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA            
	JOIN VW_MATRICULA_E_PRE_MATRICULA PM ON PM.ALUNO = A.ALUNO
	LEFT JOIN LY_PRE_MATRICULA PM2 ON PM2.ALUNO = PM.ALUNO AND PM2.ANO = PM.ANO AND PM2.SEMESTRE = PM.SEMESTRE AND PM2.DISCIPLINA = PM.DISCIPLINA AND PM2.TURMA = PM.TURMA
	JOIN LY_CURSO C ON A.CURSO = C.CURSO
	JOIN LY_UNIDADE_ENSINO UE ON C.FACULDADE = UE.UNIDADE_ENS
	JOIN HD_MUNICIPIO HM ON HM.MUNICIPIO = P.END_MUNICIPIO 
	LEFT JOIN LY_CONCURSO CON ON CON.CONCURSO = A.CONCURSO
	WHERE 1=1 
	AND A.SIT_ALUNO <> 'Cancelado' 
	AND PM.SIT_MATRICULA <> 'Cancelado'
	AND (EXISTS (SELECT TOP 1 1 FROM LY_ITEM_CRED IC
				JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB	/*PAGAMENTO REAL NUMA COBRANÇA DE MENSALIDADE*/
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = PM.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB'))
		OR EXISTS (SELECT TOP 1 1 FROM LY_BOLSA B
					WHERE B.ALUNO = PM.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1			/*BOLSA 100%  NO PERIODO LETIVO*/
					AND (B.ANOINI >= YEAR(GETDATE()) 
					AND (B.MESINI = CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END))
					
					)
		
		OR EXISTS (SELECT TOP 1 1 FROM LY_BOLSA B 
					WHERE B.ALUNO = A.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1		/*BOLSA 100% SEM FIM*/
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL)
		
		OR EXISTS (SELECT TOP 1 1 FROM LY_BOLSA B 
					WHERE B.TIPO_BOLSA = 'CREDEDUC' 
					AND B.ALUNO = PM.ALUNO
					AND B.DATA_CANCEL IS NULL			/*BOLSA ESPECIFICA CREDEDUC - NÃO CANCELADA E EM VIGÊNCIA*/
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL)
					
				)

		OR EXISTS (SELECT TOP 1 1 FROM LY_CONTRATO_FIES CF
					JOIN LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO			/*CONTRAFO FIES NO PERÍODO*/
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = A.ALUNO)					
					
		OR EXISTS (SELECT TOP 1 1 FROM VW_COBRANCA VW
					JOIN LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = A.ALUNO
					AND VW.ANO = @p_ano
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11') THEN 6 WHEN @p_semestre IN ('2','22') THEN 12 ELSE 12 END 		
					AND VW.VALOR <= 0 		
		)
		)
	AND ((@p_ano IS NOT NULL AND PM.ANO = @p_ano) OR @p_ano IS NULL)        
	AND ((@p_semestre IS NOT NULL AND PM.SEMESTRE = @p_semestre)  OR @p_semestre IS NULL)       
	AND ((@p_unidade IS NOT NULL AND C.FACULDADE = @p_unidade) OR @p_unidade IS NULL)       
	AND ((@p_tipo IS NOT NULL AND C.TIPO = @p_tipo) OR @p_tipo IS NULL)        
	AND ((@p_curso IS NOT NULL AND A.CURSO = @p_curso) OR @p_curso IS NULL)      
	AND ((@p_turno IS NOT NULL AND A.TURNO = @p_turno) OR @p_turno IS NULL)  
	AND ((@p_ano_ingresso IS NOT NULL AND A.ANO_INGRESSO = @p_ano_ingresso) OR @p_ano_ingresso IS NULL)      
	AND ((@p_sem_ingresso IS NOT NULL AND A.SEM_INGRESSO = @p_sem_ingresso) OR @p_sem_ingresso IS NULL)  

UNION ALL

    SELECT   DISTINCT     
     C.FACULDADE						AS [UNIDADE_ENSINO_ALUNO],       
     A.UNIDADE_FISICA					AS [NOME_UNIDADE_ENSINO_ALUNO],      
     C.CURSO							AS [CURSO],        
     C.NOME								AS [NOME_CURSO],       
	 A.SERIE							AS [SERIE],
     A.TURNO							AS [TURNO],
	 A.CONCURSO							AS [CONCURSO],
	ISNULL(CON.DESCRICAO,'')			AS [DESC_CONCURSO],
	 CASE	WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO'
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO' 
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'CALOURO'
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'CALOURO' END AS TIPO_ALUNO,     
	 CASE	WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO'
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) < '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN 'VETERANO' 
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20191' AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN A.TIPO_INGRESSO
			WHEN CONCAT(A.ANO_INGRESSO,A.SEM_INGRESSO) = '20190' AND C.TIPO NOT IN ('GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','LINGUAS', 'PRONATEC','TECNICO') THEN A.TIPO_INGRESSO END AS TIPO_INGRESSO, 
	 0								AS [PAGO],
	 1								AS [NAO_PAGO],
	 ISNULL((SELECT TOP 1 'S' FROM LY_BOLSA WHERE ALUNO = A.ALUNO AND DATA_CANCEL IS NULL AND (ANOFIM >= YEAR(GETDATE()) OR ANOFIM IS NULL) AND (MESFIM >= MONTH(GETDATE()) OR MESFIM IS NULL)),'N') AS [BOLSISTA],
	 NULL							AS [DATA_PAGAMENTO],
	 ISNULL((SELECT TOP 1 'Matriculado' FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre AND SIT_MATRICULA IN ('Matriculado','Aprovado','Rep Nota','Rep Falta','Trancado')),'Pre-Matric') AS [SIT_MATRICULA],
	 (SELECT MIN(DT_INSERCAO) FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND SEMESTRE = @p_semestre) AS [DATA_MATRICULA],
	 CASE WHEN PM2.OBS IS NULL OR RTRIM(LTRIM(PM2.OBS)) = '' THEN 'Secretaria' ELSE 'Aluno Online' END AS [ORIGEM_MATRICULA],
	 A.DT_INGRESSO AS [DATA_INGRESSO],
	 PM.ALUNO,
	 P.CPF,
	 A.NOME_COMPL AS NOME_ALUNO,
	 A.CURRICULO,
	 P.DT_NASC			AS [DATA_NASC],
     P.RG_NUM                AS [RG],     
     P.E_MAIL                AS [E_MAIL],    
     P.ENDERECO                AS [ENDERECO],    
     P.END_NUM                AS [NUMERO],    
     P.END_COMPL            AS [COMPLEMENTO],    
     P.CEP					AS [CEP],    
     P.BAIRRO			AS [BAIRRO],  
     HM.NOME                 AS [CIDADE],    
     HM.UF                  AS [ESTADO],     
     P.FONE                 AS [FONE],     
     P.CELULAR                AS [CELULAR],
	 ISNULL((SELECT TOP 1 CONTRATO_ACEITO FROM LY_CONTRATO_ALUNO WHERE ALUNO = A.ALUNO AND ANO = @p_ano AND PERIODO = @p_semestre),'N') AS [CONTRATO_ACEITO] 
FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA             
JOIN VW_MATRICULA_E_PRE_MATRICULA PM ON PM.ALUNO = A.ALUNO 
LEFT JOIN LY_PRE_MATRICULA PM2 ON PM2.ALUNO = PM.ALUNO AND PM2.ANO = PM.ANO AND PM2.SEMESTRE = PM.SEMESTRE AND PM2.DISCIPLINA = PM.DISCIPLINA AND PM2.TURMA = PM.TURMA     
JOIN LY_CURSO C ON A.CURSO = C.CURSO
JOIN LY_UNIDADE_ENSINO UE ON C.FACULDADE = UE.UNIDADE_ENS
JOIN HD_MUNICIPIO HM ON HM.MUNICIPIO = P.END_MUNICIPIO 
LEFT JOIN LY_CONCURSO CON ON CON.CONCURSO = A.CONCURSO
WHERE 1=1 
AND A.SIT_ALUNO <> 'Cancelado'  
AND PM.SIT_MATRICULA <> 'Cancelado'
AND (NOT EXISTS (SELECT TOP 1 1 FROM LY_ITEM_CRED IC
				JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = PM.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB'))
		AND NOT EXISTS (SELECT TOP 1 1 FROM LY_BOLSA B
					WHERE B.ALUNO = PM.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOINI >= YEAR(GETDATE()) 
					AND (B.MESINI = CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END))
					)

		AND NOT EXISTS (SELECT TOP 1 1 FROM LY_BOLSA B 
					WHERE B.TIPO_BOLSA = 'CREDEDUC' 
					AND B.ALUNO = PM.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL)
					
				)

		AND NOT EXISTS (SELECT TOP 1 1 FROM LY_BOLSA B 
					WHERE B.ALUNO = A.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL)

		AND NOT EXISTS (SELECT TOP 1 1 FROM LY_CONTRATO_FIES CF
					JOIN LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = A.ALUNO)	
					
		AND NOT EXISTS (SELECT TOP 1 1 FROM VW_COBRANCA VW
					JOIN LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = A.ALUNO
					AND VW.ANO = @p_ano
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11') THEN 6 WHEN @p_semestre IN ('2','22') THEN 12 ELSE 12 END 		
					AND VW.VALOR <= 0 		
		) )
AND ((@p_ano IS NOT NULL AND PM.ANO = @p_ano) OR @p_ano IS NULL)        
AND ((@p_semestre IS NOT NULL AND PM.SEMESTRE = @p_semestre)  OR @p_semestre IS NULL)        
AND ((@p_unidade IS NOT NULL AND C.FACULDADE = @p_unidade) OR @p_unidade IS NULL)       
AND ((@p_tipo IS NOT NULL AND C.TIPO = @p_tipo) OR @p_tipo IS NULL)        
AND ((@p_curso IS NOT NULL AND A.CURSO = @p_curso) OR @p_curso IS NULL)      
AND ((@p_turno IS NOT NULL AND A.TURNO = @p_turno) OR @p_turno IS NULL)   
AND ((@p_ano_ingresso IS NOT NULL AND A.ANO_INGRESSO = @p_ano_ingresso) OR @p_ano_ingresso IS NULL)      
AND ((@p_sem_ingresso IS NOT NULL AND A.SEM_INGRESSO = @p_sem_ingresso) OR @p_sem_ingresso IS NULL)  
ORDER BY C.FACULDADE, C.CURSO 

--ATUALIZANDO OS ALUNOS QUE POSSUEM SECRETARIA E ALUNO ONLINE

	DELETE T1 FROM #TEMP_ALUNOS T1 
	WHERE T1.ORIGEM_MATRICULA = 'Secretaria'
	AND EXISTS ( SELECT TOP 1 1 
				 FROM #TEMP_ALUNOS T2 
				 WHERE T2.ALUNO = T1.ALUNO 
				 AND T2.ORIGEM_MATRICULA = 'Aluno Online'
				)

--REMOVENDO OS ALUNOS QUE NÃO TEM MATRÍCULA NO PERIODO

	DELETE T1 FROM #TEMP_ALUNOS T1
	WHERE NOT EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ANO = @p_ano AND SEMESTRE = @p_semestre AND ALUNO = T1.ALUNO)

--ATUALIZANDO ORIGEM_MATRICULA PARA ALUNOS MATRICULADOS

	UPDATE T1 SET T1.ORIGEM_MATRICULA = 'Efetivado'
	FROM #TEMP_ALUNOS T1 WHERE SIT_MATRICULA IN ('Matriculado','Aprovado','Rep Falta','Rep Nota','Trancado')


--TRAZENDO RESULTADO SINTETICO
IF @p_tipo_relatorio = '0'
	BEGIN
			SELECT        
			 UNIDADE_ENSINO_ALUNO,
			 NOME_UNIDADE_ENSINO_ALUNO,
			 CURSO,
			 NOME_CURSO,
			 TURNO,
			 TIPO_ALUNO,
			 TIPO_INGRESSO,	
			 SUM(PAGO) AS PAGO,
			 SUM(NAO_PAGO) AS NAO_PAGO,				
			 COUNT(ALUNO)			AS [QTD_ALUNOS]
		FROM #TEMP_ALUNOS
		WHERE 1=1  
		GROUP BY UNIDADE_ENSINO_ALUNO,NOME_UNIDADE_ENSINO_ALUNO, CURSO, NOME_CURSO, TIPO_INGRESSO, TIPO_ALUNO, TURNO
		ORDER BY UNIDADE_ENSINO_ALUNO, CURSO, TIPO_ALUNO, TIPO_INGRESSO, TURNO
	END

IF @p_tipo_relatorio = '1' 
	BEGIN
									
		SELECT * FROM #TEMP_ALUNOS 
		ORDER BY 1,3

	END       
        
		DROP TABLE #TEMP_ALUNOS

SET NOCOUNT OFF        
        
END                  
GO   
-- [FIM]          
    
    
DELETE FROM LY_CUSTOM_CLIENTE    
where NOME = 'FTC_Relat_StatusMatricula'    
and IDENTIFICACAO_CODIGO = '0010' 
GO

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_Relat_StatusMatricula' NOME
, '0010' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2018-12-03' DATA_CRIACAO
, 'Relatório - Status Matrícula - Correção Pagamentos' OBJETIVO
, 'Paulo' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO 