SELECT	UF.UNIDADE_FIS AS COD_UNIDADE,
		UF.NOME_COMP,
		C.CURSO AS COD_CURSO, 
		C.NOME, 
		COUNT(PQ.CODIGO) AS QTD_ALUNOS_APLICADOS, 
		COUNT(PQ2.CODIGO) AS QTD_ALUNOS_RESPONDIDOS
		--CONVERT(VARCHAR(50),CAST(PQ2.CODIGO AS DECIMAL)/CAST(PQ.CODIGO AS DECIMAL)*100)+'%' AS PERCENTUAL_RESPONDIDO 
FROM LY_PARTICIPACAO_QUEST PQ
JOIN LY_ALUNO A ON A.ALUNO = PQ.CODIGO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
LEFT JOIN LY_PARTICIPACAO_QUEST PQ2 ON PQ2.CODIGO = PQ.CODIGO AND PQ2.APLICACAO = PQ.APLICACAO AND PQ2.DATA_PART IS NOT NULL
WHERE	PQ.APLICACAO = 'AVALDOCENTE1_20171'
		--AND A.CURSO = '2060'
		--AND A.UNIDADE_FISICA = 'FCS'
GROUP BY UF.UNIDADE_FIS,UF.NOME_COMP,C.CURSO,C.NOME
ORDER BY 1,3