USE LYCEUM
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_AlunoAtivoSemPreMatricula'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_AlunoAtivoSemPreMatricula] AS BEGIN SET NOCOUNT OFF; END')
GO

--EXEC FTC_Relat_AlunoAtivoSemPreMatricula NULL,NULL

ALTER PROCEDURE FTC_Relat_AlunoAtivoSemPreMatricula
(        
	@p_unidade VARCHAR(20)
	,@p_tipo VARCHAR(20)      
 
)        
AS 
-- [INÍCIO]                
BEGIN        
    
SET NOCOUNT ON  

SELECT	C.FACULDADE AS COD_UNIDADE
		,UE.NOME_COMP AS NOME_UNIDADE
		,C.TIPO AS TIPO_CURSO
		,C.CURSO AS COD_CURSO
		,C.NOME AS NOME_CURSO
		,A.ALUNO AS COD_ALUNO
		,A.NOME_COMPL AS NOME_ALUNO
		,A.ANO_INGRESSO
		,A.SEM_INGRESSO
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
WHERE 1=1 AND A.SIT_ALUNO = 'Ativo'
AND NOT EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO)
AND ((@p_unidade IS NOT NULL AND C.FACULDADE = @p_unidade) OR @p_unidade IS NULL)  
AND ((@p_tipo IS NOT NULL AND C.TIPO = @p_tipo) OR @p_tipo IS NULL) 
ORDER BY 1,3      

SET NOCOUNT OFF

END  