USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_Avaliacao_Coordenador'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_Avaliacao_Coordenador] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE FTC_Relat_Avaliacao_Coordenador
	@p_avaliacaoq VARCHAR(30)  
	,@p_aplicacao VARCHAR(30)  
	,@p_unidade VARCHAR(15)  
	,@p_curso VARCHAR(20)  
	,@p_docente VARCHAR(15)   
	,@p_turma VARCHAR (30)  
	,@p_disciplina VARCHAR(20) 
AS
BEGIN
/*
Autor: Miguel Barreto
Atualizado em: 13/07/2017
*/
-- Teste:
--EXEC FTC_Relat_Avaliacao_Coordenador 'Avaliação DocenteIII', 'AVALDOCENTE03_20171', '04', NULL, NULL,NULL,NULL

/*
-- PARAMETROS PARA TESTE DA PROCEDURE
DECLARE
	@p_avaliacaoq VARCHAR(30)
	,@p_avaliacaoq VARCHAR(30)
	,@p_curso VARCHAR(20)
	,@p_docente NUMERIC(15)

	SET @p_curso = '010064'
	SET @p_docente = NULL
	SET @p_turma = NULL
	SET @p_disciplina = NULL
	SET @DT_INICIO  = '2016-05-09'

*/

	CREATE TABLE #TEMP_SUM_MEDIACURSOGERAL
	(
	TIPO_QUESTIONARIO VARCHAR(20),
	APLICACAO VARCHAR(20),
	QUESTAO NUMERIC(10),
	FACULDADE VARCHAR(20),
	CURSO VARCHAR(20),
	SOMA DECIMAL(10,2),
	QUANTIDADE INT

	)

IF @p_avaliacaoq = 'Avaliação Docente II' OR @p_avaliacaoq = 'Avaliação DocenteIV'
BEGIN
	
-- TABELA #TEMP_SUM_MEDIACURSOGERAL

		INSERT INTO #TEMP_SUM_MEDIACURSOGERAL
		SELECT 
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO
			,SUM(CONVERT(DECIMAL(10,2),CR.CONCEITO)) AS SOMA
			,COUNT(CR.CONCEITO) AS QUANTIDADE
			--INTO #TEMP_SUM_MEDIACURSOGERAL --DROP TABLE #TEMP_SUM_MEDIACURSOGERAL
		FROM LY_APLIC_QUESTIONARIO AS AQ
		INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
			AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
			AND R.APLICACAO = AQ.APLICACAO
		INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
			AND CR.QUESTIONARIO = R.QUESTIONARIO
			AND CR.APLICACAO = R.APLICACAO
			AND CR.QUESTAO = R.QUESTAO
			AND CR.RESPOSTA = R.RESPOSTA
			AND CR.CHAVE_RESP = R.CHAVE_RESP
		INNER JOIN LY_COORDENACAO CO ON CO.NUM_FUNC = R.CODIGO
		INNER JOIN LY_CURSO C ON C.CURSO = CO.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
		WHERE 1 = 1 
			AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)
			AND C.CURSO = ISNULL(@p_curso, C.CURSO)
			AND CO.NUM_FUNC = ISNULL(@p_docente, CO.NUM_FUNC)
			AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
			AND R.APLICACAO = @p_aplicacao
		GROUP BY
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO

END

IF @p_avaliacaoq = 'Avaliação DocenteIII'
	BEGIN
		IF @p_aplicacao = 'AVALDOCENTE03_20171'
		BEGIN
			INSERT INTO #TEMP_SUM_MEDIACURSOGERAL
		SELECT 
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO
			,SUM(CONVERT(DECIMAL(10,2),CR.CONCEITO)) AS SOMA
			,COUNT(CR.CONCEITO) AS QUANTIDADE
		FROM LY_APLIC_QUESTIONARIO AS AQ
		INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
			AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
			AND R.APLICACAO = AQ.APLICACAO
		INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
			AND CR.QUESTIONARIO = R.QUESTIONARIO
			AND CR.APLICACAO = R.APLICACAO
			AND CR.QUESTAO = R.QUESTAO
			AND CR.RESPOSTA = R.RESPOSTA
			AND CR.CHAVE_RESP = R.CHAVE_RESP
		INNER JOIN LY_DOCENTE D ON D.NUM_FUNC = R.AVA_CODIGO4
		INNER JOIN LY_TURMA T ON T.NUM_FUNC = D.NUM_FUNC AND T.ANO = R.CODIGO AND T.SEMESTRE = R.AVA_CODIGO1 AND T.TURMA = R.AVA_CODIGO3 AND T.DISCIPLINA = R.AVA_CODIGO2
		INNER JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
		WHERE 1 = 1 
			--AND T.ANO = '2017' AND T.SEMESTRE = '2'
			AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)
			AND C.CURSO = ISNULL(@p_curso, C.CURSO)
			AND D.NUM_FUNC = ISNULL(@p_docente, D.NUM_FUNC)
			AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
			AND R.APLICACAO = @p_aplicacao
		GROUP BY
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO
		END

		ELSE

		INSERT INTO #TEMP_SUM_MEDIACURSOGERAL
		SELECT 
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO
			,SUM(CONVERT(DECIMAL(10,2),CR.CONCEITO)) AS SOMA
			,COUNT(CR.CONCEITO) AS QUANTIDADE
		FROM LY_APLIC_QUESTIONARIO AS AQ
		INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
			AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
			AND R.APLICACAO = AQ.APLICACAO
		INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
			AND CR.QUESTIONARIO = R.QUESTIONARIO
			AND CR.APLICACAO = R.APLICACAO
			AND CR.QUESTAO = R.QUESTAO
			AND CR.RESPOSTA = R.RESPOSTA
			AND CR.CHAVE_RESP = R.CHAVE_RESP
		INNER JOIN LY_DOCENTE D ON D.NUM_FUNC = R.CODIGO
		INNER JOIN LY_TURMA T ON T.NUM_FUNC = D.NUM_FUNC
		INNER JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
		WHERE 1 = 1 
			--AND T.ANO = '2017' AND T.SEMESTRE = '2'
			AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)
			AND C.CURSO = ISNULL(@p_curso, C.CURSO)
			AND D.NUM_FUNC = ISNULL(@p_docente, D.NUM_FUNC)
			AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
			AND R.APLICACAO = @p_aplicacao
		GROUP BY
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO

	END


	CREATE TABLE #TEMP_RELATORIO_ALUNO1
	(
		TIPO_QUESTIONARIO VARCHAR(20),
		APLICACAO VARCHAR(20),
		QUESTIONARIO VARCHAR(20),
		QUESTAO NUMERIC(10),
		ORDEM INT,
		PERGUNTA VARCHAR(500),
		PROFESSOR VARCHAR(100),
		CODIGO_CURSO VARCHAR(20),
		CURSO VARCHAR(300),
		CODIGO_UNIDADE_FISICA VARCHAR(20),
		UNIDADE_FISICA VARCHAR(100),
		QTDTURMA INT,
		MEDIACURSOGERAL NUMERIC(10,2),
		MEDIAPROFESSOR DECIMAL(10,2),
		SEMPRE NUMERIC(10,2),
		EVENTUALMENTE NUMERIC(10,2),
		RARAMENTE NUMERIC(10,2),
		NUNCA NUMERIC(10,2),
		NUMERO INT,
	)

IF @p_avaliacaoq = 'Avaliação Docente II' OR @p_avaliacaoq = 'Avaliação DocenteIV'
BEGIN

	INSERT INTO #TEMP_RELATORIO_ALUNO1
	SELECT
	AQ.TIPO_QUESTIONARIO AS TIPO_QUESTIONARIO
	,AQ.APLICACAO AS APLICACAO
	,AQ.QUESTIONARIO AS QUESTIONARIO
	,R.QUESTAO AS QUESTAO
	,CAST(NULL AS INT) AS ORDEM
	,CAST(NULL AS VARCHAR(500)) AS PERGUNTA
	,D.NOME_COMPL AS PROFESSOR
	,C.CURSO AS CODIGO_CURSO
	,C.NOME AS CURSO
	,C.FACULDADE AS CODIGO_UNIDADE_FISICA
	,UE.NOME_COMP AS UNIDADE_FISICA
	,CAST(NULL AS INT) AS QTDTURMA
	,CAST(NULL AS NUMERIC(10,2)) AS MEDIACURSOGERAL
	,CAST(SUM(CR.CONCEITO) AS DECIMAL(10,2)) AS MEDIAPROFESSOR
	,SUM(
		CASE CR.CONCEITO
			WHEN 1 THEN 1.00
			ELSE 0.00
		END
	) AS SEMPRE
	,SUM(
		CASE CR.CONCEITO
			WHEN 2 THEN 1.00
			ELSE 0.00
		END
	) AS EVENTUALMENTE
	,SUM(
		CASE CR.CONCEITO
			WHEN 3 THEN 1.00
			ELSE 0.00
		END
	) AS RARAMENTE
	,SUM(
		CASE CR.CONCEITO
			WHEN 4 THEN 1.00
			ELSE 0.00
		END
	) AS NUNCA
	,COUNT(DISTINCT R.AVA_CODIGO) AS NUMERO
FROM LY_APLIC_QUESTIONARIO AS AQ
INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
	AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
	AND R.APLICACAO = AQ.APLICACAO
INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
	AND CR.QUESTIONARIO = R.QUESTIONARIO
	AND CR.APLICACAO = R.APLICACAO
	AND CR.QUESTAO = R.QUESTAO
	AND CR.RESPOSTA = R.RESPOSTA
	AND CR.CHAVE_RESP = R.CHAVE_RESP
INNER JOIN LY_COORDENACAO CO ON CO.NUM_FUNC = R.CODIGO
INNER JOIN LY_DOCENTE AS D ON D.NUM_FUNC = CO.NUM_FUNC
INNER JOIN LY_CURSO C ON C.CURSO = CO.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
INNER JOIN LY_UNIDADE_ENSINO AS UE ON UE.UNIDADE_ENS = C.FACULDADE
WHERE 1 = 1 
	AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)
	AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
	AND R.APLICACAO = @p_aplicacao
	AND C.CURSO = ISNULL(@p_curso, C.CURSO)
	AND CO.NUM_FUNC = ISNULL(@p_docente, CO.NUM_FUNC)
GROUP BY
	AQ.TIPO_QUESTIONARIO
	,AQ.APLICACAO
	,AQ.QUESTIONARIO
	,R.QUESTAO
	,D.NOME_COMPL
	,C.CURSO
	,C.NOME
	,C.FACULDADE
	,UE.NOME_COMP

END


IF @p_avaliacaoq = 'Avaliação DocenteIII'
BEGIN
	IF @p_aplicacao = 'AVALDOCENTE03_20171'

	BEGIN
		INSERT INTO #TEMP_RELATORIO_ALUNO1
		SELECT
		AQ.TIPO_QUESTIONARIO AS TIPO_QUESTIONARIO
		,AQ.APLICACAO AS APLICACAO
		,AQ.QUESTIONARIO AS QUESTIONARIO
		,R.QUESTAO AS QUESTAO
		,CAST(NULL AS INT) AS ORDEM
		,CAST(NULL AS VARCHAR(500)) AS PERGUNTA
		,D.NOME_COMPL AS PROFESSOR
		,C.CURSO AS CODIGO_CURSO
		,C.NOME AS CURSO
		,C.FACULDADE AS CODIGO_UNIDADE_FISICA
		,UE.NOME_COMP AS UNIDADE_FISICA
		,CAST(NULL AS INT) AS QTDTURMA
		,CAST(NULL AS NUMERIC(10,2)) AS MEDIACURSOGERAL
		,CAST(SUM(CR.CONCEITO) AS DECIMAL(10,2)) AS MEDIAPROFESSOR
		,SUM(
			CASE CR.CONCEITO
				WHEN 1 THEN 1.00
				ELSE 0.00
			END
		) AS SEMPRE
		,SUM(
			CASE CR.CONCEITO
				WHEN 2 THEN 1.00
				ELSE 0.00
			END
		) AS EVENTUALMENTE
		,SUM(
			CASE CR.CONCEITO
				WHEN 3 THEN 1.00
				ELSE 0.00
			END
		) AS RARAMENTE
		,SUM(
			CASE CR.CONCEITO
				WHEN 4 THEN 1.00
				ELSE 0.00
			END
		) AS NUNCA
		,COUNT(DISTINCT R.AVA_CODIGO) AS NUMERO
	FROM LY_APLIC_QUESTIONARIO AS AQ
	INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
		AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
		AND R.APLICACAO = AQ.APLICACAO
	INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
		AND CR.QUESTIONARIO = R.QUESTIONARIO
		AND CR.APLICACAO = R.APLICACAO
		AND CR.QUESTAO = R.QUESTAO
		AND CR.RESPOSTA = R.RESPOSTA
		AND CR.CHAVE_RESP = R.CHAVE_RESP
	INNER JOIN LY_DOCENTE D ON D.NUM_FUNC = R.AVA_CODIGO4
	INNER JOIN LY_TURMA T ON T.NUM_FUNC = D.NUM_FUNC AND T.ANO = R.CODIGO AND T.SEMESTRE = R.AVA_CODIGO1 AND T.TURMA = R.AVA_CODIGO3 AND T.DISCIPLINA = R.AVA_CODIGO2
	INNER JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
	INNER JOIN LY_UNIDADE_ENSINO AS UE ON UE.UNIDADE_ENS = C.FACULDADE
	WHERE 1 = 1 
		AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)
		AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
		AND R.APLICACAO = @p_aplicacao
		AND C.CURSO = ISNULL(@p_curso, C.CURSO)
		AND D.NUM_FUNC = ISNULL(@p_docente, D.NUM_FUNC)
	GROUP BY
		AQ.TIPO_QUESTIONARIO
		,AQ.APLICACAO
		,AQ.QUESTIONARIO
		,R.QUESTAO
		,D.NOME_COMPL
		,C.CURSO
		,C.NOME
		,C.FACULDADE
		,UE.NOME_COMP
	END

	ELSE

	INSERT INTO #TEMP_RELATORIO_ALUNO1
	SELECT
	AQ.TIPO_QUESTIONARIO AS TIPO_QUESTIONARIO
	,AQ.APLICACAO AS APLICACAO
	,AQ.QUESTIONARIO AS QUESTIONARIO
	,R.QUESTAO AS QUESTAO
	,CAST(NULL AS INT) AS ORDEM
	,CAST(NULL AS VARCHAR(500)) AS PERGUNTA
	,D.NOME_COMPL AS PROFESSOR
	,C.CURSO AS CODIGO_CURSO
	,C.NOME AS CURSO
	,C.FACULDADE AS CODIGO_UNIDADE_FISICA
	,UE.NOME_COMP AS UNIDADE_FISICA
	,CAST(NULL AS INT) AS QTDTURMA
	,CAST(NULL AS NUMERIC(10,2)) AS MEDIACURSOGERAL
	,CAST(SUM(CR.CONCEITO) AS DECIMAL(10,2)) AS MEDIAPROFESSOR
	,SUM(
		CASE CR.CONCEITO
			WHEN 1 THEN 1.00
			ELSE 0.00
		END
	) AS SEMPRE
	,SUM(
		CASE CR.CONCEITO
			WHEN 2 THEN 1.00
			ELSE 0.00
		END
	) AS EVENTUALMENTE
	,SUM(
		CASE CR.CONCEITO
			WHEN 3 THEN 1.00
			ELSE 0.00
		END
	) AS RARAMENTE
	,SUM(
		CASE CR.CONCEITO
			WHEN 4 THEN 1.00
			ELSE 0.00
		END
	) AS NUNCA
	,COUNT(DISTINCT R.AVA_CODIGO) AS NUMERO
FROM LY_APLIC_QUESTIONARIO AS AQ
INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
	AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
	AND R.APLICACAO = AQ.APLICACAO
INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
	AND CR.QUESTIONARIO = R.QUESTIONARIO
	AND CR.APLICACAO = R.APLICACAO
	AND CR.QUESTAO = R.QUESTAO
	AND CR.RESPOSTA = R.RESPOSTA
	AND CR.CHAVE_RESP = R.CHAVE_RESP
INNER JOIN LY_DOCENTE AS D ON D.NUM_FUNC = R.CODIGO
INNER JOIN LY_TURMA T ON T.NUM_FUNC = D.NUM_FUNC
INNER JOIN LY_CURSO C ON C.CURSO = T.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
INNER JOIN LY_UNIDADE_ENSINO AS UE ON UE.UNIDADE_ENS = C.FACULDADE
WHERE 1 = 1 
	AND C.FACULDADE = ISNULL(@p_unidade,C.FACULDADE)
	AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
	AND R.APLICACAO = @p_aplicacao
	AND C.CURSO = ISNULL(@p_curso, C.CURSO)
	AND D.NUM_FUNC = ISNULL(@p_docente, D.NUM_FUNC)
GROUP BY
	AQ.TIPO_QUESTIONARIO
	,AQ.APLICACAO
	,AQ.QUESTIONARIO
	,R.QUESTAO
	,D.NOME_COMPL
	,C.CURSO
	,C.NOME
	,C.FACULDADE
	,UE.NOME_COMP

END

-- UPDATE ORDEM E PERGUNTA
UPDATE #TEMP_RELATORIO_ALUNO1 SET
	ORDEM = Q.ORDEM
	,PERGUNTA = Q.QUESTAO_OBJETIVA
FROM LY_QUESTAO AS Q
INNER JOIN #TEMP_RELATORIO_ALUNO1 AS TRA ON TRA.QUESTIONARIO = Q.QUESTIONARIO
	AND TRA.TIPO_QUESTIONARIO = Q.TIPO_QUESTIONARIO
	AND TRA.QUESTAO = Q.QUESTAO


-- TABELA #TEMP_RELATORIO_ALUNO2

SELECT
	TIPO_QUESTIONARIO
	,APLICACAO
	,QUESTIONARIO
	,QUESTAO
	,ORDEM
	,PERGUNTA
	,PROFESSOR
	,CODIGO_CURSO
	,CURSO
	,CODIGO_UNIDADE_FISICA
	,UNIDADE_FISICA
	,QTDTURMA
	,MEDIACURSOGERAL
	,MEDIAPROFESSOR
	,SEMPRE
	,EVENTUALMENTE
	,RARAMENTE
	,NUNCA
	--,NUMERO
	,SUM(SEMPRE + EVENTUALMENTE + RARAMENTE + NUNCA) AS NUMERO --SUBSTITUIR O NUMERO (DE PARTICIPANTES)
	INTO #TEMP_RELATORIO_ALUNO2 --DROP TABLE #TEMP_RELATORIO_ALUNO2
FROM #TEMP_RELATORIO_ALUNO1
GROUP BY
	TIPO_QUESTIONARIO
	,APLICACAO
	,QUESTIONARIO
	,QUESTAO
	,ORDEM
	,PERGUNTA
	,PROFESSOR
	,CODIGO_CURSO
	,CURSO
	,CODIGO_UNIDADE_FISICA
	,UNIDADE_FISICA
	,QTDTURMA
	,MEDIACURSOGERAL
	,MEDIAPROFESSOR
	,SEMPRE
	,EVENTUALMENTE
	,RARAMENTE
	,NUNCA
	,NUMERO


-- UPDATE PERCENTUAIS DE RESPOSTA
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	MEDIAPROFESSOR = (MEDIAPROFESSOR / NUMERO)
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	SEMPRE = (SEMPRE / NUMERO) * 100
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	EVENTUALMENTE = (EVENTUALMENTE / NUMERO) * 100
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	RARAMENTE = (RARAMENTE / NUMERO) * 100
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	NUNCA = (NUNCA / NUMERO) * 100

 --DECLARE @V_NUMERO INT   
 --SET @V_NUMERO = dbo.fn_AvalDocQtdPartic(@p_avaliacaoq, @p_aplicacao, @p_unidade, @p_curso)  
 
 --UPDATE #TEMP_RELATORIO_ALUNO2 SET  
 --NUMERO = @V_NUMERO
 


-- VERFICACAO DO PERCENTUAL:
/*
SELECT
	TIPO_QUESTIONARIO
	,APLICACAO
	,QUESTIONARIO
	,QUESTAO
	,ORDEM
	,PERGUNTA
	,PROFESSOR
	,CODIGO_CURSO
	,CURSO
	,CODIGO_UNIDADE_FISICA
	,UNIDADE_FISICA
	,TURMA
	,CODIGO_DISCIPLINA
	,DISCIPLINA
	,ANO
	,SEMESTRE
	,QTDTURMA
	,MEDIACURSOGERAL
	,MEDIAPROFESSOR
	,SEMPRE
	,EVENTUALMENTE
	,RARAMENTE
	,NUNCA
	,NUMERO
	,(SEMPRE + EVENTUALMENTE + RARAMENTE + NUNCA) AS SOMA
FROM #TEMP_RELATORIO_ALUNO2
ORDER BY
	SOMA
*/

-- UPDATE MEDIACURSOGERAL
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	MEDIACURSOGERAL = CAST(TMPSUM.SOMA / TMPSUM.QUANTIDADE AS NUMERIC(10))
FROM #TEMP_SUM_MEDIACURSOGERAL AS TMPSUM
WHERE 1 = 1
	AND #TEMP_RELATORIO_ALUNO2.TIPO_QUESTIONARIO = TMPSUM.TIPO_QUESTIONARIO  
	AND #TEMP_RELATORIO_ALUNO2.APLICACAO = TMPSUM.APLICACAO  
	AND #TEMP_RELATORIO_ALUNO2.ORDEM = TMPSUM.QUESTAO  
	AND #TEMP_RELATORIO_ALUNO2.CODIGO_CURSO = TMPSUM.CURSO  
	AND #TEMP_RELATORIO_ALUNO2.CODIGO_UNIDADE_FISICA = TMPSUM.FACULDADE  

SELECT
	*
FROM #TEMP_RELATORIO_ALUNO2
WHERE 1=1
ORDER BY
	PROFESSOR
	,APLICACAO
	,CURSO
	,ORDEM

-- APAGA TABELAS

	DROP TABLE #TEMP_SUM_MEDIACURSOGERAL;

	DROP TABLE #TEMP_RELATORIO_ALUNO1;

	DROP TABLE #TEMP_RELATORIO_ALUNO2;

END

