USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_ValidaHistorico'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_ValidaHistorico] AS BEGIN SET NOCOUNT OFF; END')
GO

--EXEC FTC_Relat_ValidaHistorico NULL,NULL, '07','GRADUACAO', NULL, NULL,NULL

ALTER PROCEDURE FTC_Relat_ValidaHistorico
(        
  @p_ano VARCHAR(4)  
, @p_semestre VARCHAR(1)  
, @p_unidade VARCHAR(20)  
, @p_tipo VARCHAR(20)    
, @p_curso  VARCHAR(20)    
, @p_turno  VARCHAR(20)    
, @p_curriculo VARCHAR(20)    
)        
AS 
-- [INÍCIO]                
BEGIN        
    
SET NOCOUNT ON   

SELECT C.FACULDADE, UF.NOME_COMP AS NOME_UNIDADE, A.CURSO, C.NOME AS NOME_CURSO, A.ALUNO, A.NOME_COMPL AS NOME_ALUNO , HM.ANO, HM.SEMESTRE, D.DISCIPLINA, D.NOME AS NOME_DISCIPLINA, HM.NOTA_FINAL, HM.SITUACAO_HIST, ISNULL(HM.OBSERVACAO,'') AS OBSERVACAO
FROM LY_HISTMATRICULA HM
JOIN LY_ALUNO A ON A.ALUNO = HM.ALUNO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = HM.DISCIPLINA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
WHERE 1=1
AND A.SIT_ALUNO = 'Ativo' AND EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = '2017' AND SEMESTRE = '2')
AND ((@p_ano IS NOT NULL AND HM.ANO = @p_ano)  OR @p_ano is null)
AND ((@p_semestre IS NOT NULL AND HM.SEMESTRE = @p_semestre)  or @p_semestre is null)
AND (@p_unidade IS NOT NULL AND C.FACULDADE = @p_unidade)   
AND (@p_tipo IS NOT NULL AND C.TIPO = @p_tipo)    
AND ((@p_curso IS NOT NULL AND C.CURSO = @p_curso) OR @p_curso IS NULL)  
AND ((@p_turno IS NOT NULL AND A.TURNO = @p_turno) OR @p_turno IS NULL)    
AND ((@p_curriculo IS NOT NULL AND A.CURRICULO = @p_curriculo) OR @p_curriculo IS NULL)
ORDER BY C.FACULDADE, C.CURSO, HM.ANO, HM.SEMESTRE, A.ALUNO

SET NOCOUNT OFF   

-- [FIM]
END

go

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
'FTC_Relat_ValidaHistorico' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel Barreto' AUTOR
, '2017-12-15' DATA_CRIACAO
, 'Validação do lançamento de Notas nos Historico' OBJETIVO
, 'Josane Oliveira' SOLICITADO_POR
, 'S' ATIVO
, 'Procedure' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO 
