USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_Avaliacao_Mestrado_Curso'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_Avaliacao_Mestrado_Curso] AS BEGIN SET NOCOUNT OFF; END')
GO 

ALTER PROCEDURE FTC_Relat_Avaliacao_Mestrado_Curso
	@p_avaliacaoq VARCHAR(30)  
	,@p_aplicacao VARCHAR(30)  
	,@p_unidade VARCHAR(15)  
	,@p_curso VARCHAR(20)  
	,@p_docente VARCHAR(15)   
	,@p_turma VARCHAR (30)  
	,@p_disciplina VARCHAR(20) 
AS
BEGIN
/*
Autor: Miguel Barreto
Atualizado em: 13/07/2017
*/
-- Teste:
--EXEC FTC_Relat_Avaliacao_Mestrado_Curso 'Av Docente M I', 'AVALDOCM1_20181', '04', NULL,  NULL, NULL, NULL


-- PARAMETROS PARA TESTE DA PROCEDURE
/*
DROP TABLE #TEMP_SUM_MEDIACURSOGERAL

DECLARE
	@p_avaliacaoq VARCHAR(30),
	@p_aplicacao VARCHAR(30)
	

	SET @p_avaliacaoq = '010064'
	SET @p_aplicacao = NULL
	*/



-- TABELA #TEMP_SUM_MEDIACURSOGERAL
		SELECT 
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO
			,SUM(CONVERT(DECIMAL(10,2),CR.CONCEITO)) AS SOMA
			,COUNT(CR.CONCEITO) AS QUANTIDADE
			INTO #TEMP_SUM_MEDIACURSOGERAL --DROP TABLE #TEMP_SUM_MEDIACURSOGERAL
		FROM LY_APLIC_QUESTIONARIO AS AQ
		INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
			AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
			AND R.APLICACAO = AQ.APLICACAO
		INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
			AND CR.QUESTIONARIO = R.QUESTIONARIO
			AND CR.APLICACAO = R.APLICACAO
			AND CR.QUESTAO = R.QUESTAO
			AND CR.RESPOSTA = R.RESPOSTA
			AND CR.CHAVE_RESP = R.CHAVE_RESP
		INNER JOIN LY_CURSO C ON C.CURSO = R.CODIGO
		WHERE 1 = 1 
			AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
			AND R.APLICACAO = @p_aplicacao
		GROUP BY
			R.TIPO_QUESTIONARIO
			,R.APLICACAO
			,R.QUESTAO
			,C.FACULDADE
			,C.CURSO


-- TABELA #TEMP_RELATORIO_ALUNO1

SELECT
	AQ.TIPO_QUESTIONARIO AS TIPO_QUESTIONARIO
	,AQ.APLICACAO AS APLICACAO
	,AQ.QUESTIONARIO AS QUESTIONARIO
	,R.QUESTAO AS QUESTAO
	,CAST(NULL AS INT) AS ORDEM
	,CAST(NULL AS VARCHAR(500)) AS PERGUNTA
	,C.CURSO AS CODIGO_CURSO
	,C.NOME AS CURSO
	,C.FACULDADE AS CODIGO_UNIDADE_FISICA
	,UE.NOME_COMP AS UNIDADE_FISICA
	,CAST(NULL AS INT) AS QTDTURMA
	,CAST(NULL AS NUMERIC(10,2)) AS MEDIACURSOGERAL
	,CAST(SUM(CR.CONCEITO) AS DECIMAL(10,2)) AS MEDIAPROFESSOR
	,SUM(
		CASE CR.CONCEITO
			WHEN 1 THEN 1.00
			ELSE 0.00
		END
	) AS SEMPRE
	,SUM(
		CASE CR.CONCEITO
			WHEN 2 THEN 1.00
			ELSE 0.00
		END
	) AS EVENTUALMENTE
	,SUM(
		CASE CR.CONCEITO
			WHEN 3 THEN 1.00
			ELSE 0.00
		END
	) AS RARAMENTE
	,SUM(
		CASE CR.CONCEITO
			WHEN 4 THEN 1.00
			ELSE 0.00
		END
	) AS NUNCA
	,COUNT(DISTINCT R.AVA_CODIGO) AS NUMERO
	INTO #TEMP_RELATORIO_ALUNO1 --DROP TABLE #TEMP_RELATORIO_ALUNO1
FROM LY_APLIC_QUESTIONARIO AS AQ
INNER JOIN LY_RESPOSTA AS R ON R.QUESTIONARIO = AQ.QUESTIONARIO
	AND R.TIPO_QUESTIONARIO = AQ.TIPO_QUESTIONARIO
	AND R.APLICACAO = AQ.APLICACAO
INNER JOIN LY_CONCEITO_RESPOSTA AS CR ON CR.TIPO_QUESTIONARIO = R.TIPO_QUESTIONARIO
	AND CR.QUESTIONARIO = R.QUESTIONARIO
	AND CR.APLICACAO = R.APLICACAO
	AND CR.QUESTAO = R.QUESTAO
	AND CR.RESPOSTA = R.RESPOSTA
	AND CR.CHAVE_RESP = R.CHAVE_RESP
INNER JOIN LY_CURSO C ON C.CURSO = R.CODIGO
INNER JOIN LY_UNIDADE_ENSINO AS UE ON UE.UNIDADE_ENS = C.FACULDADE
WHERE 1 = 1 
	AND AQ.TIPO_QUESTIONARIO = @p_avaliacaoq
	AND R.APLICACAO = @p_aplicacao
GROUP BY
	AQ.TIPO_QUESTIONARIO
	,AQ.APLICACAO
	,AQ.QUESTIONARIO
	,R.QUESTAO
	,C.CURSO
	,C.NOME
	,C.FACULDADE
	,UE.NOME_COMP


-- UPDATE ORDEM E PERGUNTA
UPDATE #TEMP_RELATORIO_ALUNO1 SET
	ORDEM = Q.ORDEM
	,PERGUNTA = Q.QUESTAO_OBJETIVA
FROM LY_QUESTAO AS Q
INNER JOIN #TEMP_RELATORIO_ALUNO1 AS TRA ON TRA.QUESTIONARIO = Q.QUESTIONARIO
	AND TRA.TIPO_QUESTIONARIO = Q.TIPO_QUESTIONARIO
	AND TRA.QUESTAO = Q.QUESTAO


-- TABELA #TEMP_RELATORIO_ALUNO2

SELECT
	TIPO_QUESTIONARIO
	,APLICACAO
	,QUESTIONARIO
	,QUESTAO
	,ORDEM
	,PERGUNTA
	,CODIGO_CURSO
	,CURSO
	,CODIGO_UNIDADE_FISICA
	,UNIDADE_FISICA
	,QTDTURMA
	,MEDIACURSOGERAL
	,MEDIAPROFESSOR
	,SEMPRE
	,EVENTUALMENTE
	,RARAMENTE
	,NUNCA
	--,NUMERO
	,SUM(SEMPRE + EVENTUALMENTE + RARAMENTE + NUNCA) AS NUMERO --SUBSTITUIR O NUMERO (DE PARTICIPANTES)
	INTO #TEMP_RELATORIO_ALUNO2 --DROP TABLE #TEMP_RELATORIO_ALUNO2
FROM #TEMP_RELATORIO_ALUNO1
GROUP BY
	TIPO_QUESTIONARIO
	,APLICACAO
	,QUESTIONARIO
	,QUESTAO
	,ORDEM
	,PERGUNTA
	,CODIGO_CURSO
	,CURSO
	,CODIGO_UNIDADE_FISICA
	,UNIDADE_FISICA
	,QTDTURMA
	,MEDIACURSOGERAL
	,MEDIAPROFESSOR
	,SEMPRE
	,EVENTUALMENTE
	,RARAMENTE
	,NUNCA
	,NUMERO


-- UPDATE PERCENTUAIS DE RESPOSTA
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	MEDIAPROFESSOR = (MEDIAPROFESSOR / NUMERO)
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	SEMPRE = (SEMPRE / NUMERO) * 100
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	EVENTUALMENTE = (EVENTUALMENTE / NUMERO) * 100
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	RARAMENTE = (RARAMENTE / NUMERO) * 100
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	NUNCA = (NUNCA / NUMERO) * 100


-- VERFICACAO DO PERCENTUAL:
/*
SELECT
	TIPO_QUESTIONARIO
	,APLICACAO
	,QUESTIONARIO
	,QUESTAO
	,ORDEM
	,PERGUNTA
	,PROFESSOR
	,CODIGO_CURSO
	,CURSO
	,CODIGO_UNIDADE_FISICA
	,UNIDADE_FISICA
	,TURMA
	,CODIGO_DISCIPLINA
	,DISCIPLINA
	,ANO
	,SEMESTRE
	,QTDTURMA
	,MEDIACURSOGERAL
	,MEDIAPROFESSOR
	,SEMPRE
	,EVENTUALMENTE
	,RARAMENTE
	,NUNCA
	,NUMERO
	,(SEMPRE + EVENTUALMENTE + RARAMENTE + NUNCA) AS SOMA
FROM #TEMP_RELATORIO_ALUNO2
ORDER BY
	SOMA
*/

-- UPDATE MEDIACURSOGERAL
UPDATE #TEMP_RELATORIO_ALUNO2 SET
	MEDIACURSOGERAL = CAST(TMPSUM.SOMA / TMPSUM.QUANTIDADE AS VARCHAR(10))
FROM #TEMP_SUM_MEDIACURSOGERAL AS TMPSUM
WHERE 1 = 1
	AND #TEMP_RELATORIO_ALUNO2.TIPO_QUESTIONARIO = TMPSUM.TIPO_QUESTIONARIO  
	AND #TEMP_RELATORIO_ALUNO2.APLICACAO = TMPSUM.APLICACAO  
	AND #TEMP_RELATORIO_ALUNO2.ORDEM = TMPSUM.QUESTAO  
	AND #TEMP_RELATORIO_ALUNO2.CODIGO_CURSO = TMPSUM.CURSO  
	AND #TEMP_RELATORIO_ALUNO2.CODIGO_UNIDADE_FISICA = TMPSUM.FACULDADE  

SELECT
	*
FROM #TEMP_RELATORIO_ALUNO2
WHERE 1=1
ORDER BY
	APLICACAO
	,CURSO
	,ORDEM

-- APAGA TABELAS

	DROP TABLE #TEMP_SUM_MEDIACURSOGERAL;

	DROP TABLE #TEMP_RELATORIO_ALUNO1;

	DROP TABLE #TEMP_RELATORIO_ALUNO2;

END

