USE LYCEUM
GO

DROP TABLE #VETERANO
GO
--MONTA TABELA TEMP PARA GUARDAR ALUNOS COM HISTORICO E MATRICULA
-- HISTORICO
SELECT	DISTINCT
		A.ALUNO
		INTO #VETERANO
FROM LY_ALUNO A
-- VETERANO (MATRICULADO NO SEMESTRE ANTERIOR)
INNER JOIN LY_HISTMATRICULA HM ON HM.ALUNO = A.ALUNO
WHERE A.SIT_ALUNO = 'ATIVO'
AND HM.ANO = '2016'
AND HM.SEMESTRE = '1'
AND HM.SITUACAO_HIST IN ('APROVADO', 'REP NOTA', 'REP FREQ', 'TRANCADO')
AND NOT EXISTS (SELECT 1 FROM LY_TRANCAMENTO T WHERE T.ALUNO = HM.ALUNO AND T.ANO_TRANC = HM.ANO AND T.SEM_TRANC = HM.SEMESTRE)

UNION

-- MATRICULA
SELECT	DISTINCT
		A.ALUNO
FROM LY_ALUNO A
-- VETERANO (MATRICULADO NO SEMESTRE ANTERIOR)
INNER JOIN LY_MATRICULA M ON M.ALUNO = A.ALUNO
WHERE A.SIT_ALUNO = 'ATIVO'
AND M.ANO = '2016'
AND M.SEMESTRE = '1'
AND M.SIT_MATRICULA IN ('MATRICULADO', 'APROVADO', 'REP NOTA', 'REP FREQ', 'TRANCADO')
AND NOT EXISTS (SELECT 1 FROM LY_TRANCAMENTO T WHERE T.ALUNO = M.ALUNO AND T.ANO_TRANC = M.ANO AND T.SEM_TRANC = M.SEMESTRE)
GO

--LIMPA REGISTROS EXISTENTES
DELETE FROM LY_CONJ_ALUNO WHERE CONJ_ALUNO = 'GERA_PRE_MATRICULA'
GO
DELETE FROM LY_DEF_CONJ_ALUNO WHERE CONJ_ALUNO = 'GERA_PRE_MATRICULA'
GO

INSERT INTO LY_DEF_CONJ_ALUNO
SELECT 'GERA_PRE_MATRICULA', 'Gerar matrícula (com histórico/matricula no sem. anterior e sem trancamento no sem. anterior)'
GO

INSERT INTO LY_CONJ_ALUNO
SELECT 'GERA_PRE_MATRICULA', VET.ALUNO
FROM #VETERANO VET
GO

