DECLARE @pAluno VARCHAR(11)

SET @pAluno = '062290456'

SELECT * FROM ly_aluno WHERE ALUNO = @pAluno

SELECT * FROM LY_MATRICULA WHERE ALUNO = @pAluno

SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = @pAluno

SELECT * FROM LY_TRANCAMENTO WHERE ALUNO = @pAluno