USE LYCEUM
GO

SELECT  A.UNIDADE_FISICA, UF.NOME_COMP AS NOME_UNIDADE, C.CURSO, CUR.TURNO, C.NOME AS NOME_CURSO, CUR.CURRICULO, CUR.OBS, COUNT(DISTINCT A.ALUNO) QTD_ALUNOS FROM LY_CURRICULO CUR
JOIN LY_ALUNO A ON A.CURSO = CUR.CURSO AND A.CURRICULO = CUR.CURRICULO AND A.TURNO = CUR.TURNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
WHERE 1=1
AND EXISTS (SELECT 1 FROM LY_MATRICULA WHERE ALUNO = A.ALUNO AND CONCAT(ANO,SEMESTRE) IN ('20172','20182'))
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND A.SIT_ALUNO = 'Ativo'
GROUP BY A.UNIDADE_FISICA, UF.NOME_COMP, C.CURSO,CUR.TURNO, C.NOME, CUR.CURRICULO, CUR.OBS
ORDER BY 1,3,6
