USE LYCEUM
GO

SELECT DISTINCT A.ALUNO, A.NOME_COMPL, A.UNIDADE_FISICA, CUR.TIPO, CUR.CURSO, CUR.NOME AS NOME_CURSO, C.COBRANCA, IL.BOLETO, C.DATA_DE_VENCIMENTO, SUM(IL.VALOR) AS VALOR FROM LY_ALUNO A
JOIN LY_COBRANCA C ON C.ALUNO = A.ALUNO
JOIN LY_CURSO CUR ON CUR.CURSO = A.CURSO
JOIN LY_ITEM_LANC IL ON IL.COBRANCA = C.COBRANCA
WHERE IL.BOLETO IS NOT NULL AND C.DATA_DE_VENCIMENTO >= '2018-01-01'
GROUP BY A.ALUNO, A.NOME_COMPL,A.UNIDADE_FISICA, CUR.TIPO, CUR.CURSO, CUR.NOME, C.COBRANCA, IL.BOLETO, C.DATA_DE_VENCIMENTO
ORDER BY 3,5