SELECT DISTINCT C.* FROM VW_COBRANCA C 
JOIN LY_ITEM_CRED IC ON IC.COBRANCA = C.COBRANCA
WHERE IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
AND C.VALOR > 0 AND IC.USUARIO <> 'Migracao'
order by 2,3,5