select IC.LANC_CRED AS PAGAMENTO, IC.COBRANCA, VALOR, U.USUARIO, U.NOME,ic.data from LY_ITEM_CRED IC
JOIN LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
JOIN LY_CURSO C ON C.CURSO = IC.CURSO
JOIN HD_USUARIO U ON U.USUARIO = IC.USUARIO
WHERE C.FACULDADE = '07'
AND IC.ITEM_ESTORNADO IS NOT NULL
AND LC.TIPO_PAGAMENTO = 'Cheque'
AND IC.DATA >= '2017-07-12' 
AND IC.DATA < '2017-07-14'
order by ic.data