SELECT A.ALUNO FROM LY_ALUNO A
WHERE EXISTS (
	SELECT 1 FROM LY_PARTICIPACAO_QUEST 
	WHERE A.ALUNO = CODIGO 
	AND APLICACAO = 'AVALDOCENTE1_20171'
	AND DATA_PART IS NOT NULL
)

SELECT DISTINCT A.ALUNO  
FROM LY_ALUNO A JOIN LY_CURSO C ON C.CURSO = a.CURSO 
WHERE A.SIT_ALUNO = 'Ativo' AND C.TIPO IN ('GRADUACAO','TECNOLOGO') 
AND EXISTS (SELECT 1 FROM LY_MATRICULA VW WHERE VW.ALUNO = A.ALUNO)
AND NOT EXISTS (SELECT 1 FROM LY_CONJ_ALUNO WHERE ALUNO = A.ALUNO AND CONJ_ALUNO = 'ALUAVALDOC1_20171')