SELECT	BI.UNIDADE_FISICA_ALUNO
		, BI.NOME_CURSO
		, BI.ALUNO
		, BI.CPF
		, BI.NOME_ALUNO
		, BI.INDICE_REPROVACAO*100 AS INDICE_REPROVACAO
		, BI.PERC_FALTAS*100 AS PERC_FALTAS
		, BI.QTD_INADIMP
		, VM.VALOR_MENSALIDADE * 6 AS VALOR_SEMESTRALIDADE
		, BI.ULTIMA_MATRICULA
		, BI.SIT_MATRICULA
		, BI.SOLICITOU_PLANO
		, BI.SOLICITOU_HIST
		, BI.E_MAIL
		, BI.DDD
		, BI.FONE
		, BI.CELULAR
FROM BI_REMATRICULA BI
JOIN BI_VALOR_MENSALIDADE VM ON VM.ANO = BI.ANO AND VM.SEMESTRE = BI.SEMESTRE AND VM.CURSO = BI.CURSO AND VM.CURRICULO = BI.CURRICULO AND VM.TURNO = BI.TURNO AND VM.SERIE = BI.SERIE
 WHERE BI.STATUS_FTC NOT IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') 
AND BI.ANO = 2018 AND BI.SEMESTRE = 2 AND BI.TIPO_ALUNO = 'VETERANO' AND BI.TIPO_TRANSF IS NULL
ORDER BY 1,2