--PADACES

INSERT INTO [HD_PADACES] ([PADACES],[NOME],[PAGINA_INICIAL])VALUES('SuperFinan','Perfil de Supervisor Financeiro',NULL)

--PADTRANS

INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Cons Devolucao','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Devolucao','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Estorno Resumo Financeiro','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Proc Estorna Cobrança','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Remove Boleto Resumo Financeiro',NULL,NULL,NULL)
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Remove Cobrança Resumo Financeiro',NULL,NULL,NULL)
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Remove Devolucao Cobranca','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Remove Dívida Resumo Financeiro',NULL,NULL,NULL)
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Lyceum','Remove Pagamento',NULL,NULL,NULL)
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Secretaria','TFIN009D','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Secretaria','TFIN011D','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Secretaria','TFIN012D','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('SuperFinan','Secretaria','TFIN063D','S','S','S')