/*
CRIADO POR:		IGOR CAMPOS/ YURI GUIMARAES
CRIADO EM:		02/07/2020 16:04
ATUALIZADO POR:	
ATUALIZADO EM:	
USO:			
EXEMPLO:		
RETORNO:		

INSERCAO DOS ALUNOS NA PRE MATRICULA DE MEDICINA, AQUI TAMBEM INSERE AS DISCIPLINAS...

*/

USE LYCEUM
go

DECLARE
	@INSERIR_DISCIPLINA VARCHAR(1) = 'S'
	,@INSERIR_ANTECIPACAO VARCHAR(1) = 'S'	
	,@IMPORTAR_MEDICINA VARCHAR(1) = 'S'
	,@CURSOR VARCHAR(1) = 'S'

-- Lista Disciplinas do curso de medicina
IF OBJECT_ID('TEMPDB.DBO.##V_DISC_MEDICINA', 'U') IS NOT NULL DROP TABLE ##V_DISC_MEDICINA
SELECT DISTINCT
	G.CURSO
	,G.TURNO
	,G.CURRICULO
	,('MFM_' + G.CURSO + '_' + G.CURRICULO + '_' + CAST(G.SERIE_IDEAL AS VARCHAR(2))) DISCIPLINA
	,G.SERIE_IDEAL SERIE
	,CAST(SUM(D.CREDITOS) AS INTEGER) CREDITOS
	,(
		SELECT
			MAX(SERIE_IDEAL)
		FROM LYCEUM..LY_GRADE
		WHERE 1 = 1
			AND CURSO = G.CURSO
			AND TURNO = G.TURNO
			AND CURRICULO = G.CURRICULO
	) SERIE_MAX
	INTO ##V_DISC_MEDICINA
FROM LYCEUM..LY_GRADE G
INNER JOIN LYCEUM..LY_DISCIPLINA D ON 1 = 1
	AND D.DISCIPLINA = G.DISCIPLINA
WHERE 1 = 1
	AND G.CURSO = '722'
	AND EXISTS (
		SELECT TOP 1
			1
		FROM LYCEUM..LY_ALUNO A
		INNER JOIN LYCEUM..LY_CURSO C ON 1 = 1
			AND C.CURSO = A.CURSO
		WHERE 1 = 1
			AND A.CURSO = G.CURSO
			AND A.TURNO = G.TURNO
			AND A.CURRICULO = G.CURRICULO
			AND C.TIPO IN ('GRADUACAO', 'TECNOLOGO')
			AND A.SIT_ALUNO = 'ATIVO'			
			AND EXISTS (
				SELECT TOP 1
					1
				FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA
				WHERE 1 = 1
					AND ALUNO = A.ALUNO
			)
	)
GROUP BY G.CURSO,G.TURNO,G.CURRICULO,G.SERIE_IDEAL

-- VERIFICAR REGISTROS:
-- SELECT DISTINCT CREDITOS FROM ##V_DISC_MEDICINA ORDER BY CREDITOS
-- ORDER BY CURSO, TURNO, CURRICULO, SERIE 


-- DISCIPLINAS A SEREM INSERIDAS:
IF OBJECT_ID('TEMPDB.DBO.##V_DISC_ANTECIPACAO', 'U') IS NOT NULL DROP TABLE ##V_DISC_ANTECIPACAO
SELECT DISTINCT
	CURSO
	,TURNO
	,CURRICULO
	,SERIE
	,DISCIPLINA
	,CREDITOS
	,SERIE_MAX
	INTO ##V_DISC_ANTECIPACAO
FROM (
	SELECT * FROM ##V_DISC_MEDICINA
) TB
WHERE 1 = 1

-- VERIFICAR REGISTROS:
--SELECT * FROM ##V_DISC_ANTECIPACAO_OUTROS ORDER BY CURSO


-- EXIBE QUANTIDADE DE DISCIPLINAS PARA INSERIR
SELECT
	COUNT(1) DISCIPLINAS_PARA_INSERIR
FROM ##V_DISC_ANTECIPACAO V
WHERE 1 = 1
	AND NOT EXISTS (
		SELECT TOP 1
			1
		FROM LYCEUM..LY_DISCIPLINA
		WHERE 1 = 1
			AND DISCIPLINA = V.DISCIPLINA
	)

-- INSERIR AS DISCIPLINAS:
IF (@INSERIR_DISCIPLINA = 'S')
BEGIN

	INSERT INTO LYCEUM..LY_DISCIPLINA (DISCIPLINA, FACULDADE, DEPTO, NOME, NOME_COMPL, CREDITOS, TEM_NOTA, TEM_FREQ, VERIFICA_HORARIO, ATIVA, ESTAGIO, PRAZO_REVISAO, TIPO, TRUNCA_MEDIA, FL_FIELD_01)
	SELECT DISTINCT
		V.DISCIPLINA
		,'04' FACULDADE
		,'GERAL' DEPTO
		,'Matricula Financeira Medicina' NOME
		,('Matricula Financeira Medicina. Curso: ' + CURSO + ', Curriculo: ' + CURRICULO) NOME_COMPL
		,V.CREDITOS
		,'N' TEM_NOTA
		,'N' TEM_FREQ
		,'N' VERIFICA_HORARIO
		,'S' ATIVA
		,'N' ESTAGIO
		,0 PRAZO_REVISAO
		,'TEORICA' TIPO
		,'N' TRUNCA_MEDIA
		,GETDATE() FL_FIELD_01 -- DATA QUE FOI INSERIDA A DISCIPLINA
	FROM ##V_DISC_ANTECIPACAO V
	WHERE 1 = 1
		AND NOT EXISTS (
			SELECT TOP 1
				1
			FROM LYCEUM..LY_DISCIPLINA
			WHERE 1 = 1
				AND DISCIPLINA = V.DISCIPLINA
		)
END

-- VERIFICAR AS DISCIPLINAS QUE FORAM ADICIONADAS (UMA HORA ATRAS)
--SELECT * FROM LYCEUM..LY_DISCIPLINA WHERE FL_FIELD_01 > DATEADD(HH, -1, GETDATE())


DECLARE
	@ANO_MAT_ANTECIPACAO VARCHAR(4) = '2021'
	,@SEM_MAT_ANTECIPACAO VARCHAR(2) = '1'
	,@SERIE_INCREMENTO INTEGER = 1
	,@ALUNO_CONSULTA VARCHAR(20) = NULL--'171060062'


IF OBJECT_ID('TEMPDB.DBO.##V_ALUNO_INSERIR_MEDICINA', 'U') IS NOT NULL DROP TABLE ##V_ALUNO_INSERIR_MEDICINA
SELECT DISTINCT
	A.ALUNO
	,A.SERIE SERIE_ALUNO
	,V.CURSO
	,V.TURNO
	,V.CURRICULO
	,CASE
		WHEN V.SERIE + @SERIE_INCREMENTO >= SERIE_MAX THEN SERIE_MAX
		WHEN V.SERIE + @SERIE_INCREMENTO <= SERIE_MAX THEN V.SERIE + @SERIE_INCREMENTO
		WHEN V.SERIE >= SERIE_MAX THEN SERIE_MAX
		ELSE V.SERIE
	END SERIE
	--,V.SERIE
	,CASE
		WHEN V.CURSO = '722' AND V.SERIE IN (9, 10) THEN 11
		ELSE V.SERIE
	END SERIE_CALCULO
	,V.DISCIPLINA
	,CASE
		WHEN V.SERIE IN (9, 10) THEN (SELECT CREDITOS FROM ##V_DISC_ANTECIPACAO WHERE DISCIPLINA = 'MFM_' + V.CURSO + '_' + V.CURRICULO + '_11')
		ELSE V.CREDITOS
	END CREDITOS
	,V.SERIE_MAX
	,@ANO_MAT_ANTECIPACAO ANO
	,@SEM_MAT_ANTECIPACAO SEM
	,A.ANO_INGRESSO
	,A.SEM_INGRESSO
INTO ##V_ALUNO_INSERIR_MEDICINA
FROM LYCEUM..LY_ALUNO A
INNER JOIN ##V_DISC_ANTECIPACAO V ON 1 = 1
	AND V.CURSO = A.CURSO
	AND V.TURNO = A.TURNO
	AND V.CURRICULO = A.CURRICULO
	AND V.SERIE = A.SERIE + @SERIE_INCREMENTO
WHERE 1 = 1
	AND A.ALUNO = ISNULL(@ALUNO_CONSULTA, A.ALUNO)
	AND A.CURSO = '722' -- CURSO DE MEDICINA
   AND EXISTS (
		SELECT TOP 1
			1
		FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA
		WHERE 1 = 1
			AND ALUNO = A.ALUNO
	)
	AND NOT EXISTS (
		SELECT TOP 1
			1
		FROM LYCEUM..LY_PRE_MATRICULA
		WHERE 1 = 1
			AND ALUNO = A.ALUNO
			AND DISCIPLINA = V.DISCIPLINA
			AND ANO = @ANO_MAT_ANTECIPACAO
			AND SEMESTRE = @SEM_MAT_ANTECIPACAO
	)
	AND NOT EXISTS (
		SELECT TOP 1
			1
		FROM LYCEUM..LY_MATRICULA
		WHERE 1 = 1
			AND ALUNO = A.ALUNO
			AND DISCIPLINA = V.DISCIPLINA
			AND ANO = @ANO_MAT_ANTECIPACAO
			AND SEMESTRE = @SEM_MAT_ANTECIPACAO
	)
	AND NOT EXISTS (
		SELECT TOP 1
			1
		FROM LYCEUM..LY_HISTMATRICULA M
		WHERE 1 = 1
			AND ALUNO = A.ALUNO
			AND DISCIPLINA = V.DISCIPLINA
			AND SITUACAO_HIST IN ('APROVADO', 'DISPENSADO')
	)

-- VERIFICAR REGISTROS:
--SELECT * FROM ##V_ALUNO_INSERIR_MEDICINA ORDER BY ALUNO, CURSO, TURNO, CURRICULO, SERIE, DISCIPLINA



IF (@IMPORTAR_MEDICINA = 'N')
BEGIN 
	TRUNCATE TABLE TEMPDB.DBO.##V_ALUNO_INSERIR_MEDICINA
END

INSERT INTO LYCEUMTEMP.dbo.FTC_ANTECIPACAO_FINANCEIRA (ALUNO, SERIE_ALUNO, CURSO, TURNO, CURRICULO, SERIE, SERIE_CALCULO, DISCIPLINA, CREDITOS, SERIE_MAX, ANO, SEM)
SELECT ALUNO, SERIE_ALUNO, CURSO, TURNO, CURRICULO, SERIE, SERIE_CALCULO, DISCIPLINA, CREDITOS, SERIE_MAX, ANO, SEM 
FROM LYCEUMINTEGRACAO..FTC_ANTECIPACAO_FINANCEIRA A
WHERE NOT EXISTS ( SELECT TOP 1 1 FROM LYCEUMTEMP.dbo.FTC_ANTECIPACAO_FINANCEIRA F WHERE 
	F.ALUNO = A.ALUNO AND F.SERIE_ALUNO = A.SERIE_ALUNO AND  F.CURSO = A.CURSO AND F.TURNO = A.TURNO AND F.CURRICULO = A.CURRICULO AND F.SERIE = A.SERIE AND F.SERIE_CALCULO = A.SERIE_CALCULO AND F.DISCIPLINA = A.DISCIPLINA AND F.CREDITOS = A.CREDITOS AND F.SERIE_MAX = A.SERIE_MAX AND F.ANO = A.ANO AND F.SEM = A.SEM
)

IF (@INSERIR_ANTECIPACAO = 'S')
BEGIN
	
	TRUNCATE TABLE LYCEUMINTEGRACAO.dbo.FTC_ANTECIPACAO_FINANCEIRA
	INSERT INTO LYCEUMINTEGRACAO..FTC_ANTECIPACAO_FINANCEIRA (ALUNO, SERIE_ALUNO, CURSO, TURNO, CURRICULO, SERIE, SERIE_CALCULO, DISCIPLINA, CREDITOS, SERIE_MAX, ANO, SEM)
	SELECT
		ALUNO
		,SERIE_ALUNO
		,CURSO
		,TURNO
		,CURRICULO
		,SERIE
		,SERIE_CALCULO
		,DISCIPLINA
		,CREDITOS
		,SERIE_MAX
		,ANO
		,SEM
	FROM (
		SELECT DISTINCT
			*
		FROM ##V_ALUNO_INSERIR_MEDICINA
	) T
	WHERE 1 = 1
		--AND T.ANO_INGRESSO = '2020'
		--AND T.SEM_INGRESSO = '1'
		AND NOT EXISTS (
			SELECT TOP 1
				1
			FROM LYCEUMINTEGRACAO..FTC_ANTECIPACAO_FINANCEIRA
			WHERE 1 = 1
				AND ALUNO = T.ALUNO
				AND SERIE_ALUNO = T.SERIE_ALUNO
				AND CURSO = T.CURSO
				AND TURNO = T.TURNO
				AND CURRICULO = T.CURRICULO
				AND SERIE = T.SERIE
				AND SERIE_CALCULO = T.SERIE_CALCULO
				AND DISCIPLINA = T.DISCIPLINA
				AND CREDITOS = T.CREDITOS
				AND SERIE_MAX = T.SERIE_MAX
				AND ANO = T.ANO
				AND SEM = T.SEM
		)
END
-- VERIFICAR REGISTROS:
-- SELECT * FROM LYCEUMINTEGRACAO..FTC_ANTECIPACAO_FINANCEIRA ORDER BY ALUNO, CURSO, TURNO, CURRICULO, SERIE, DISCIPLINA


IF (@CURSOR = 'S')
BEGIN

	DECLARE
		@ID INTEGER
		,@ALUNO VARCHAR(60)
		,@SERIE INTEGER
		,@DISCIPLINA VARCHAR(20)
		,@CREDITOS INTEGER
		,@SESSAO VARCHAR(20) = (SELECT @@SPID)
		,@DT_INSERT DATETIME = GETDATE()
		,@ANO VARCHAR(4)
		,@SEM VARCHAR(2)

	-- ID DA SESSAO PARA REVISAR NA TABELA DO LYCEUM
	--SELECT @SESSAO ID_SESSAO

	-- CURSOR PARA PERCORRER OS NOMES DOS OBJETOS 
	DECLARE CURSOR_OBJECTS CURSOR FOR

	-- #################### CRIA A LISTA DE ALUNOS QUE SER INSERIDA #################### --

		SELECT 
			ID
			,ALUNO
			--,SERIE_ALUNO
			--,CURSO
			--,TURNO
			--,CURRICULO
			,SERIE_CALCULO
			,DISCIPLINA
			,CREDITOS
			--,SERIE_MAX
			,ANO
			,SEM
		FROM LYCEUMINTEGRACAO..FTC_ANTECIPACAO_FINANCEIRA
		WHERE 1 = 1
			AND IMPORTADO IS NULL
		ORDER BY
			ALUNO DESC
		
	-- ABRINDO CURSOR PARA LEITURA
	OPEN CURSOR_OBJECTS

	-- LENDO A PRXIMA LINHA
	FETCH NEXT FROM CURSOR_OBJECTS INTO @ID, @ALUNO, @SERIE, @DISCIPLINA, @CREDITOS, @ANO, @SEM

	-- PERCORRENDO LINHAS DO CURSOR (ENQUANTO HOUVEREM)
	WHILE @@FETCH_STATUS = 0
	BEGIN

		--TRUNCATE TABLE LYCEUM..LY_PROCESSA_MATRICULA_GRUPO
		--DELETE FROM LYCEUM..LY_PROCESSA_MATRICULA_GRUPO WHERE SESSAO_ID = 715

		INSERT INTO LYCEUM..LY_PROCESSA_MATRICULA_GRUPO
			(
				SESSAO_ID, DISCIPLINA, TURMA, ANO, SEMESTRE, SUBTURMA1, SUBTURMA2, SIT_MATRICULA, SIT_DETALHE, OBS, MATRICULANOVA, SERIE_IDEAL
				, SERIE_CALCULO, COBRANCA_SEP, DT_INSERCAO, DT_MATRICULA, ALOCADO, CONTEXTO, VERMAXREPROVACAO, VERVAGA, VERGRADE, VERHORARIO
				, VERPREREQ, VERLIMITESCREDITOS, VERDISCIPADAP, VERPLANOESTUDO, VERCARGAHORARIA, ACEITE_ONLINE, VERGRUPO, CONFIRMADA, DISPENSADA
			)
			SELECT
				@SESSAO SESSAO_ID
				,@DISCIPLINA
				,NULL TURMA
				,@ANO ANO
				,@SEM SEMESTRE
				,NULL SUBTURMA
				,NULL SUBTURMA2
				,'PR-MATRICULADO' SIT_MATRICULA
				,'CURRICULAR' SIT_DETALHE
				,('Matrcula Financeira Medicina ' + CAST(@ANO AS VARCHAR(4)) + '.' + CAST(@SEM AS VARCHAR(2)) + '. Crditos: ' + CAST(@CREDITOS AS VARCHAR(6))) OBS
				,'S' MATRICULANOVA
				,@SERIE SERIE_IDEAL
				,@SERIE SERIE_CALCULO
				,'N' COBRANCA_SEP
				,@DT_INSERT DT_INSERCAO
				,@DT_INSERT DT_MATRICULA
				,'S' ALOCADO
				,'MATRICULA PELA INTERNET' CONTEXTO
				,'N' VERMAXREPROVACAO
				,'N' VERVAGA
				,'N' VERGRADE
				,'N' VERHORARIO
				,'N' VERPREREQ
				,'N' VERLIMITESCREDITOS
				,'N' VERDISCIPADAP
				,'N' VERPLANOESTUDO
				,'N' VERCARGAHORARIA
				,'S' ACEITE_ONLINE
				,'N' VERGRUPO
				,'N' CONFIRMADA
				,'N' DISPENSADA
			WHERE 1 = 1

			EXEC LYCEUM..PROCESSA_MATRICULA_GRUPO @SESSAO, @ALUNO, @ANO, @SEM, 'MATRICULA PELA INTERNET', 'S', 'N', 'N', 'N', NULL;

			UPDATE LYCEUMINTEGRACAO..FTC_ANTECIPACAO_FINANCEIRA SET IMPORTADO = 'S' WHERE ID = @ID

		-- LENDO A PRXIMA LINHA
		FETCH NEXT FROM CURSOR_OBJECTS INTO @ID, @ALUNO, @SERIE, @DISCIPLINA, @CREDITOS, @ANO, @SEM
	END

	-- FECHANDO CURSOR PARA LEITURA
	CLOSE CURSOR_OBJECTS

	-- DESALOCANDO O CURSOR
	DEALLOCATE CURSOR_OBJECTS

END

--SELECT * FROM LYCEUMINTEGRACAO..FTC_ANTECIPACAO_FINANCEIRA WHERE IMPORTADO = 'S'
----select * from LY_PRE_MATRICULA WHERE DT_INSERCAO >= '2020-07-02'

---- select * from LY_PRE_MATRICULA WHERE ANO = 2020 AND SEMESTRE = 2 AND DISCIPLINA LIKE 'MFM_722%'


