USE LYCEUM
GO

--PADACES
INSERT INTO [HD_PADACES] ([PADACES],[NOME],[PAGINA_INICIAL])VALUES('AvaliaInstituc','Perfil para Avaliação Institucional',NULL)

--SETOR
INSERT INTO [HD_SETOR] ([SETOR],[NOME],[SETORPAI],[TIPO_SETOR],[DTINI],[DTFIM],[NUMEROLOG],[COMPLEMENTO],[FONE],[FAX],[ATIVO],[MUNICIPIO],[BAIRRO],[LOGRADOURO],[TRECHO_LOGR],[CNPJ],[PAIS],[CEP],[STAMP_ATUALIZACAO],[OBSERVACAO])VALUES('GER. ACAD. AVAL','GERÊNCIA ACADÊMICA E AVALIAÇÃO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'S',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

--USUARIOS
INSERT INTO [HD_USUARIO] ([USUARIO],[SIS],[NOME],[GRUPOUSU],[SENHA],[PRIVILEGIADO],[EMAIL],[MATRICULA],[SETOR],[HABILITADO],[MOTIVO_DESABILITADO],[DATA_ALTERACAO_SENHA],[ALTERAR_SENHA],[SENHAS_ANTERIORES],[SENHA_TEMP],[ULTIMO_LOGIN],[TENTATIVAS_INCORRETAS],[WINUSUARIO],[PESSOA],[PADRAO])VALUES('01371394547',NULL,'Dayse Ackerman',NULL,'…ËX§í#|¿Y¦ú?‚Ê]©EŠß,€ÅPžã','N',NULL,NULL,'GER. ACAD. AVAL','S',NULL,'Sep 14 2016 10:03:08:000AM','N',NULL,NULL,NULL,NULL,'GLOBAL\dcasouza',NULL,'GERAL')
INSERT INTO [HD_USUARIO] ([USUARIO],[SIS],[NOME],[GRUPOUSU],[SENHA],[PRIVILEGIADO],[EMAIL],[MATRICULA],[SETOR],[HABILITADO],[MOTIVO_DESABILITADO],[DATA_ALTERACAO_SENHA],[ALTERAR_SENHA],[SENHAS_ANTERIORES],[SENHA_TEMP],[ULTIMO_LOGIN],[TENTATIVAS_INCORRETAS],[WINUSUARIO],[PESSOA],[PADRAO])VALUES('48203610587',NULL,'Liane Soares',NULL,'…ËX§í#|¿Y¦ú?‚Ê]©EŠß,€ÅPžã','N',NULL,NULL,'GER. ACAD. AVAL','S',NULL,'Sep 14 2016 10:04:28:000AM','N',NULL,NULL,NULL,NULL,'GLOBAL\lsoares',NULL,'GERAL')

--TRANSACOES
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Aplic Questionario','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Aplic Questionario Geral','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Aspecto','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Filtro Aplic Quest','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Filtro Publico Alvo','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Questionário','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Relatorios','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Tipo de Objeto','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Tipo de Questão','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('AvaliaInstituc','Lyceum','Tipo de Questionario','S','S','S')

--PADUSUARIO

INSERT INTO [HD_PADUSUARIO] ([PADACES],[USUARIO])VALUES('AvaliaInstituc','01371394547')
INSERT INTO [HD_PADUSUARIO] ([PADACES],[USUARIO])VALUES('AvaliaInstituc','48203610587')