--PADRAO DE ACESSO
INSERT INTO [HD_PADACES] ([PADACES],[NOME],[PAGINA_INICIAL])VALUES('VB_ProcSele','Perfil para Processo Seletivo',NULL)

--TRANSAÇÕES
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Areas de Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Avaliacao Continua Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Avaliacao por Etapas - ProcSel','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Avaliacao Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Boletos Vestibular Cancelados','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Candidatos','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Concursos','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Convocacao Manual','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Cursos','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Dados de Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Dados Pessoais','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Exames de Lingua','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Imprime Formul RespVest','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Ingresso ( Vestibular )','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Lista de Espera','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Notas de Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc Calculo Notas Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc Classificacao','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc Convocacao','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc de Classificação de alunos','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc Desclassificacao','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc Efetiva Inscricao','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc Ensala Alunos do Simulado','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc Entrada de Notas','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Proc ImportaBoletoVest','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Provas de Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','PSeletivo OnLine Candidato','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Responsavel Financeiro Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Respostas do Candidato','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Resultado Final Vestibular','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Transferência de Candidatos','S','S','S')
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Lyceum','Turnos',NULL,NULL,NULL)
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Secretaria','TAOP033D',NULL,NULL,NULL)
INSERT INTO [HD_PADTRANS] ([PADACES],[SIS],[TRANS],[PODEALT],[PODECAD],[PODEREM])VALUES('VB_ProcSele','Secretaria','TPSE001D',NULL,NULL,NULL)

--RELATORIOS
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Academico','AcaRevalidaVest')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Academico','AcaSemRegVest')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesCandidatosporVaga')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesClassifAlfa')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesClassifCurso')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesClassifOpcao')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesConfigConcurso')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesConfigSalas')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesConvConcurso')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesConvCurso')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesConvocados')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesEstatPreMatr')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesEtiqCarteira')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesEtiqCarteira2C')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesEtiqIdentidade')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesEtiqMalaDireta')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesFolhaRedacao')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesGeralAlfa')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscrAlfa')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscrCanhoto')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscrCursoSexo')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscritos')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscrLingua')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscrSala')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscrSalaEsp')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesInscrSalaFreq')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesListaEspera')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesNotasBrutas')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesNotasIndiv')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesNotasPadroniz')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesNotasPontos')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesSalasNumCandidatos')
INSERT INTO [HD_PADREL] ([PADACES],[SIS],[GRUPORELAT],[RELATORIO])VALUES('VB_ProcSele','Lyceum','Vestibular','VesSemOpcao')

--PROCESSOS
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','CalculaNotaVest')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','Classifica')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','Convoca')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','Desclassifica')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','EfetivaInscricao')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','Ensala')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','EntradaNota')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','ImportaBoletoVest')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','IngressoVestibular')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','Normaliza')
INSERT INTO [HD_PADPROC] ([PADACES],[SIS],[PROCESSO])VALUES('VB_ProcSele','Lyceum','Pontuacao')