USE LYCEUM
GO

--##  Apagando os registros existentes nos CONJUNTOS  ##--
DELETE FROM LY_CONJ_ALUNO 
WHERE CONJ_ALUNO IN ('ALUNOS_FIES','ALUNOS_PROUNI')
GO

--## Inserindo os conjunto de FIES ##--

INSERT INTO LY_CONJ_ALUNO
SELECT	'ALUNOS_FIES' CONJ_ALUNO,
		A.ALUNO
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE 1=1
AND EXISTS (SELECT TOP 1 1 FROM LY_BOLSA WHERE ALUNO = A.ALUNO AND TIPO_BOLSA LIKE '%FIES%')
AND EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND SIT_MATRICULA <> 'Cancelado' AND ANO = 2018 AND SEMESTRE = 1)
GO


--## Inserindo os conjunto de PROUNI ##--

INSERT INTO LY_CONJ_ALUNO
SELECT	'ALUNOS_PROUNI' CONJ_ALUNO,
		A.ALUNO
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE 1=1
AND EXISTS (SELECT TOP 1 1 FROM LY_BOLSA WHERE ALUNO = A.ALUNO AND (TIPO_BOLSA LIKE '%PROUNI%' OR TIPO_BOLSA LIKE '%PROIES%'))
AND EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND SIT_MATRICULA <> 'Cancelado' AND ANO = 2018 AND SEMESTRE = 1)

GO