USE LYCEUM
GO

--##  Apagando os registros existentes nos CONJUNTOS  ##--
DELETE FROM LY_CONJ_ALUNO 
WHERE CONJ_ALUNO IN ('GRADUACAO_FCS','GRADUACAO_FTCFSA','GRADUACAO_FTCITA','GRADUACAO_FTCJEQ','GRADUACAO_FTCSSA','GRADUACAO_FTCVIC','GRADUACAO_FTCPET','GRADUACAO_FTCSP','GRADUACAO_FTCJUA','MESTRADO','POS_GRADUACAO')
GO

--## Inserindo os conjunto de graduação ##--

INSERT INTO LY_CONJ_ALUNO
SELECT	CASE 
			WHEN A.UNIDADE_FISICA = 'FCS' THEN 'GRADUACAO_FCS'
			WHEN A.UNIDADE_FISICA = 'FTC-FSA' THEN 'GRADUACAO_FTCFSA'
			WHEN A.UNIDADE_FISICA = 'FTC-ITA' THEN 'GRADUACAO_FTCITA'
			WHEN A.UNIDADE_FISICA = 'FTC-JEQ' THEN 'GRADUACAO_FTCJEQ'
			WHEN A.UNIDADE_FISICA = 'FTC-SSA' THEN 'GRADUACAO_FTCSSA'
			WHEN A.UNIDADE_FISICA = 'FTC-VIC' THEN 'GRADUACAO_FTCVIC'
			WHEN A.UNIDADE_FISICA = 'OTE-PET' THEN 'GRADUACAO_FTCPET'
			WHEN A.UNIDADE_FISICA = 'OTE-SP' THEN 'GRADUACAO_FTCSP'
			WHEN A.UNIDADE_FISICA = 'OTE-JUA' THEN 'GRADUACAO_FTCJUA'
		END AS CONJ_ALUNO
		, A.ALUNO
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE 1=1
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
AND A.UNIDADE_FISICA IN ('FCS','FTC-FSA','FTC-ITA','FTC-JEQ','FTC-SSA','FTC-VIC','OTE-PET','OTE-SP','OTE-JUA')
AND EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND SIT_MATRICULA <> 'Cancelado' AND ANO = 2018 AND SEMESTRE = 1)
GO

--SELECT * FROM LY_CONJ_ALUNO WHERE CONJ_ALUNO IN ('GRADUACAO_FCS','GRADUACAO_FTCFSA','GRADUACAO_FTCITA','GRADUACAO_FTCJEQ','GRADUACAO_FTCSSA','GRADUACAO_FTCVIC','GRADUACAO_FTCPET','GRADUACAO_FTCSP','GRADUACAO_FTCJUA','MESTRADO','POS_GRADUACAO')

INSERT INTO LY_CONJ_ALUNO
SELECT	CASE 
			WHEN C.TIPO = 'MESTRADO' THEN 'MESTRADO'
			WHEN  C.TIPO = 'POS-GRADUACAO' THEN 'POS_GRADUACAO'
		END AS CONJ_ALUNO
		, A.ALUNO
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE 1=1
AND C.TIPO IN ('POS-GRADUACAO','MESTRADO')
AND EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND SIT_MATRICULA <> 'Cancelado')
GO