USE LYCEUMA
GO

--SELECT dbo.fnGetDtContabil('Ly_Item_Lanc','4393072','1','','','')  

select DISTINCT TOP 100000 RA.ATO_ID,
				IL.ALUNO, 
				IL.COBRANCA, 
				RA.ANO_REF, 
				RA.MES_REF,
				RA.ITEMCOBRANCA,
				RA.EVENTO_NUM,
				RA.EVENTO_DESCR,
				RA.VALOR_SINAL,  
				RA.DATACONTAB AS DATACONTAB_ANTIGA, 
				IL.DATA AS DATACONTAB_NOVA
				--dbo.fnGetDtContabil('Ly_Item_Lanc',RA.COBRANCA,RA.ITEMCOBRANCA,'','','') AS DATACONTAB_CERTA
INTO #TEMP1 --DROP TABLE #TEMP1
FROM LY_ITEM_LANC IL 
JOIN AY_RESUMO_ATO RA ON RA.COBRANCA = IL.COBRANCA AND IL.ITEMCOBRANCA = RA.ITEMCOBRANCA AND RA.ALUNO = IL.ALUNO
WHERE RA.DATACONTAB <> IL.DATA--dbo.fnGetDtContabil('Ly_Item_Lanc',RA.COBRANCA,RA.ITEMCOBRANCA,'','','')
--AND RA.COBRANCA = '4137483' AND RA.ITEMCOBRANCA = '11'
ORDER BY IL.ALUNO, RA.ANO_REF, RA.MES_REF

DELETE FROM #TEMP1 WHERE MONTH(DATACONTAB_ANTIGA) = MONTH(DATACONTAB_NOVA)

--SELECT dbo.fnGetDtContabil('Ly_Item_Lanc','4102044','12','','','')  


UPDATE #TEMP1 SET DATACONTAB_NOVA = dbo.fnGetDtContabil('Ly_Item_Lanc',COBRANCA,ITEMCOBRANCA,'','','')
WHERE DATACONTAB_ANTIGA <> dbo.fnGetDtContabil('Ly_Item_Lanc',COBRANCA,ITEMCOBRANCA,'','','')
GO


SELECT * FROM #TEMP1 
WHERE YEAR(DATACONTAB_NOVA) >= 2016 
ORDER BY ALUNO, ANO_REF, MES_REF,ITEMCOBRANCA

--select * from LY_COBRANCA WHERE COBRANCA = '4139303'
--select * from AY_RESUMO_ATO WHERE COBRANCA = '4393072' AND ITEMCOBRANCA = '1'


--SELECT dbo.fnGetDtContabil('Ly_Item_Lanc','4393072','1','','','')  