SELECT DISTINCT P.CPF, P.NOME_COMPL,C.NOME AS NOME_CURSO, P.ALUNO AS MATRICULA_LYCEUM, P.COD_ALUNO_VIRTUAL, P.CURSO,P.TURNO,P.CURRICULO 
  FROM TBL_PESSOA_ALUNO_DOCENTE_RESP P
  JOIN TBL_CURSO_MATRIZ C ON C.CURSO = P.CURSO
WHERE P.SISTEMA_ORIGEM = 'VIRTUAL' AND P.TIPO_AGENTE = 'ALUNO'
AND P.UNIDADE_ENSINO = '06' AND EXISTS (SELECT 1 FROM TBL_FINANCEIRO F WHERE F.ALUNO = P.ALUNO) 
AND EXISTS (SELECT 1 FROM TBL_HISTORICO H WHERE H.ALUNO = P.ALUNO )
AND P.MIGRAR = 'S'