USE LYCEUM
GO

select UF.UNIDADE_FIS,UF.NOME_COMP,U.USUARIO, U.NOME, ISNULL(SETOR,'') AS SETOR, U.WINUSUARIO AS LOGIN, PU.PADACES AS PERFIL_ACESSO FROM HD_USUARIO U
JOIN HD_PADUSUARIO PU ON PU.USUARIO = U.USUARIO
JOIN LY_USUARIO_UNIDADE UU ON UU.USUARIO = U.USUARIO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = UU.FACULDADE
 WHERE PADACES = 'SecadUnidade'
 ORDER BY 1

