SELECT luu.USUARIO,hu.NOME, luu.FACULDADE, lf.NOME_COMP 
  FROM LY_USUARIO_UNIDADE luu
JOIN HD_USUARIO hu ON hu.USUARIO = luu.USUARIO
join LY_FACULDADE lf ON lf.FACULDADE = luu.FACULDADE
WHERE luu.USUARIO NOT IN ('75933748587','01528328582')
AND hu.SETOR <> 'TI'
AND hu.HABILITADO = 'S'
ORDER BY 1