USE LYCEUM
GO

DROP TABLE #TEMP_TURMAS

CREATE TABLE #TEMP_TURMAS (
	QTD_ALUNO INT,
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	CURSO VARCHAR(20),
	TURNO VARCHAR(2),
	CURRICULO VARCHAR(50),
	SERIE VARCHAR(2),
	DISCIPLINA VARCHAR(20),
	TURMA VARCHAR(50),
	NIVEL VARCHAR(50)
)

--TURMA
INSERT INTO #TEMP_TURMAS
SELECT COUNT(VW.ALUNO) AS QTD_ALUNO,T.ANO,T.SEMESTRE, T.CURSO AS CURSO, T.TURNO, T.CURRICULO, T.SERIE, T.DISCIPLINA, T.TURMA, T.NIVEL FROM LY_TURMA T
JOIN VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE AND VW.DISCIPLINA = T.DISCIPLINA AND VW.TURMA = T.TURMA
WHERE T.ANO = 2019
AND T.SEMESTRE = 1
AND T.SIT_TURMA = 'Aberta'
AND VW.SIT_MATRICULA IN ('Matriculado','Rep Nota','Rep Freq','Aprovado')
AND T.CURSO IS NOT NULL AND T.CURRICULO IS NOT NULL AND T.SERIE IS NOT NULL
GROUP BY T.ANO,T.SEMESTRE, T.CURSO, T.TURNO, T.CURRICULO, T.SERIE,T.DISCIPLINA, T.TURMA, T.NIVEL

INSERT INTO #TEMP_TURMAS
SELECT COUNT(VW.ALUNO) AS QTD_ALUNO,T.ANO,T.SEMESTRE, T.CURSO AS CURSO, T.TURNO, T.CURRICULO, T.SERIE, T.DISCIPLINA, T.TURMA, T.NIVEL FROM LY_TURMA T
JOIN LY_HISTMATRICULA VW ON VW.ANO = T.ANO AND VW.SEMESTRE = T.SEMESTRE AND VW.DISCIPLINA = T.DISCIPLINA AND VW.TURMA = T.TURMA
WHERE T.ANO = 2018
AND T.SEMESTRE = 2
--AND T.SIT_TURMA = 'Aberta'
AND VW.SITUACAO_HIST IN ('Rep Nota','Rep Freq','Aprovado')
AND T.CURSO IS NOT NULL AND T.CURRICULO IS NOT NULL AND T.SERIE IS NOT NULL
GROUP BY T.ANO,T.SEMESTRE, T.CURSO, T.TURNO, T.CURRICULO, T.SERIE,T.DISCIPLINA, T.TURMA, T.NIVEL

--UPDATE #TEMP_TURMAS SET SERIE = '' WHERE SERIE IS NULL


SELECT AVG(QTD_ALUNO) ALUNO_P_DOCENTE, ANO, SEMESTRE, UE.UNIDADE_ENS AS COD_UNIDADE,UE.NOME_COMP AS NOME_UNIDADE, T.CURSO AS COD_CURSO, C.NOME AS NOME_CURSO, TURNO
FROM #TEMP_TURMAS T
JOIN LY_CURSO C ON C.CURSO = T.CURSO COLLATE Latin1_General_CI_AI
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
GROUP BY ANO, SEMESTRE, T.CURSO, TURNO,UE.UNIDADE_ENS, UE.NOME_COMP, C.NOME
ORDER BY ANO,SEMESTRE, T.CURSO, TURNO

SELECT AVG(QTD_ALUNO) ALUNO_P_DOCENTE, ANO, SEMESTRE, CURSO, TURNO
FROM #TEMP_TURMAS T
--JOIN LY_CURSO C ON C.CURSO = T.CURSO COLLATE Latin1_General_CI_AI
--JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
GROUP BY ANO, SEMESTRE, T.CURSO, TURNO
ORDER BY ANO,SEMESTRE, T.CURSO, TURNO


SELECT	ANO
		,SEMESTRE
		,UE.UNIDADE_ENS AS COD_UNIDADE
		,UE.NOME_COMP AS NOME_UNIDADE
		,C.CURSO AS COD_CURSO
		,C.NOME AS NOME_CURSO
		,T.TURNO
		, COUNT(*) AS QTD_TURMAS
FROM #TEMP_TURMAS T
JOIN LY_CURSO C ON C.CURSO = T.CURSO COLLATE Latin1_General_CI_AI
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
GROUP BY ANO, SEMESTRE, UE.UNIDADE_ENS, UE.NOME_COMP,C.CURSO,C.NOME,T.TURNO
ORDER BY ANO,SEMESTRE, UE.UNIDADE_ENS, C.CURSO