USE MIGRACAO
GO

SELECT * FROM TBL_FINANCEIRO tf
WHERE 1 = 1
AND tf.VALOR_BRUTO <> tf.VALOR_BOLSA1
AND tf.VALOR_PAGO > 0 
AND tf.VALOR_BOLSA1 > 0
AND EXISTS (SELECT 1 FROM TBL_FINANCEIRO tf2 WHERE tf2.ALUNO = tf.ALUNO AND tf2.ANO = tf.ano AND tf2.mes = tf.mes 
			AND tf2.PERIODO_LETIVO = tf.PERIODO_LETIVO AND tf.RESP = tf2.RESP AND tf2.valor_pago = 0 
			AND tf2.valor_bolsa1 > 0 AND tf2.VALOR_BRUTO = tf2.VALOR_BOLSA1)
AND tf.SISTEMA_ORIGEM = 'VIRTUAL'
AND tf.MIGRAR = 'S'
--AND tf.ANO IN (2016,2017,2018)


SELECT VALOR_BRUTO,VALOR_DESCONTO,VALOR_PAGO, VALOR_BOLSA1,* FROM TBL_FINANCEIRO 
WHERE 1 = 1
AND ALUNO = '141041040'
AND ANO = '2014'
AND MES = '2'

