USE FTC_DATAMART
GO

DECLARE @p_ano VARCHAR(4)
DECLARE @p_semestre VARCHAR(2)

SET @p_ano = '2017'
SET @p_semestre = '1'

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.PERCENT_EVASAO'))   
BEGIN
	DELETE FROM PERCENT_EVASAO WHERE ANO = @p_ano AND SEMESTRE = @p_semestre
END

ELSE 

CREATE TABLE PERCENT_EVASAO --DROP TABLE PERCENT_EVASAO
(
ANO VARCHAR(4),
SEMESTRE VARCHAR(2),
COD_UNIDADE VARCHAR(50),
NOME_UNIDADE VARCHAR(200),
COD_CURSO VARCHAR(50),
NOME_CURSO VARCHAR(200),
TURNO VARCHAR(1),
TOTAL_EVADIDOS INT,
TOTAL_BASE INT
)

INSERT INTO PERCENT_EVASAO
SELECT DISTINCT ANO,
				SEMESTRE,
				UNIDADE_FISICA_ALUNO AS COD_UNIDADE, 
				NOME_UNIDADE_ENSINO_ALUNO AS NOME_UNIDADE,
				CURSO AS COD_CURSO,
				NOME_CURSO,
				TURNO,
				0 AS TOTAL_EVADIDOS, 
				0 AS TOTAL_BASE
FROM BI_REMATRICULA 
WHERE ANO = @p_ano AND SEMESTRE = @p_semestre

UPDATE P SET TOTAL_EVADIDOS = (SELECT COUNT(ALUNO) 
								FROM BI_REMATRICULA 
								WHERE ANO = @p_ano
								AND SEMESTRE = @p_semestre
								AND UNIDADE_FISICA_ALUNO = P.COD_UNIDADE 
								AND CURSO = P.COD_CURSO
								AND TURNO = P.TURNO
								AND TIPO_ALUNO IN ('VETERANO','VETERANO-CONCLUINTE')
								AND STATUS_FTC NOT IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO','CONCLUIDO')
								AND (TIPO_TRANSF NOT IN ('SAIDA CURSO','SAIDA UNIDADE') OR TIPO_TRANSF IS NULL))
FROM PERCENT_EVASAO P


UPDATE P SET TOTAL_BASE = (SELECT COUNT(ALUNO) 
								FROM BI_REMATRICULA 
								WHERE ANO = @p_ano
								AND SEMESTRE = @p_semestre
								AND UNIDADE_FISICA_ALUNO = P.COD_UNIDADE 
								AND CURSO = P.COD_CURSO
								AND TURNO = P.TURNO
								AND TIPO_ALUNO IN ('VETERANO','VETERANO-CONCLUINTE')
								AND (TIPO_TRANSF NOT IN ('SAIDA CURSO','SAIDA UNIDADE') OR TIPO_TRANSF IS NULL))
FROM PERCENT_EVASAO P


--UPDATE P SET P.PERCENT_EVASAO = CONVERT(DECIMAL(10,4),TOTAL_EVADIDOS)/(CONVERT(DECIMAL(10,4),TOTAL_BASE))
--FROM PERCENT_EVASAO P
--WHERE TOTAL_BASE > 0 AND P.ANO =  @p_ano AND P.SEMESTRE = @p_semestre

DELETE FROM PERCENT_EVASAO WHERE NOME_UNIDADE IS NULL

--UPDATE PERCENT_EVASAO SET PERCENT_EVASAO = 0.0000 WHERE TOTAL_EVADIDOS = 0 AND TOTAL_BASE = 0

SELECT * FROM PERCENT_EVASAO ORDER BY 1,2,3,5