  
CREATE PROCEDURE PR_AUTOMATIZA_REMOCAO_CONTRATO  
(  
  @p_aluno VARCHAR(20)  
, @p_id_contrato INT  
)  
AS  
BEGIN  
  
 IF @p_id_contrato > 0  
 BEGIN  
  IF NOT EXISTS(SELECT TOP 1 1 FROM LY_CONTRATO_REMOVIDO WHERE CHAVE = @p_id_contrato AND ALUNO = @p_aluno)  
  BEGIN  
   INSERT INTO LY_CONTRATO_REMOVIDO(ALUNO, ANO, PERIODO, CHAVE, CONTRATO_ACEITO, DATA_ACEITE, OFERTA_DE_CURSO)  
   SELECT ALUNO, ANO, PERIODO, @p_id_contrato AS CHAVE, CONTRATO_ACEITO, DATA_ACEITE, OFERTA_DE_CURSO   
   FROM LY_CONTRATO_ALUNO   
   WHERE ID_CONTRATO_ALUNO = @p_id_contrato  
  
   INSERT INTO LY_CONTR_ALU_IMG_REMOV(ALUNO, ANO, PERIODO, CHAVE, IMAGEM, CODIGO_HASH)  
   SELECT C.ALUNO, C.ANO, C.PERIODO, C.ID_CONTRATO_ALUNO, IMAGEM, CODIGO_HASH  
   FROM LY_CONTRATO_ALUNO_IMG CI  
   JOIN LY_CONTRATO_ALUNO C  
    ON (C.ID_CONTRATO_ALUNO = CI.ID_CONTRATO_ALUNO)  
   WHERE C.ID_CONTRATO_ALUNO = @p_id_contrato  
  END  
  
  IF EXISTS(SELECT TOP 1 1 FROM LY_CONTRATO_REMOVIDO WHERE CHAVE = @p_id_contrato)  
  BEGIN  
   DELETE LY_CONTRATO_ALUNO_IMG WHERE ID_CONTRATO_ALUNO = @p_id_contrato  
   DELETE LY_CONTRATO_ALUNO WHERE ID_CONTRATO_ALUNO = @p_id_contrato  
  END  
 END  
  
END  