USE LYCEUMINTEGRACAO
GO
ALTER PROCEDURE FTC_VALIDA_ACESSO_ALUNO(@CPF VARCHAR(20), @SENHA VARCHAR(MAX), @AMBIENTE VARCHAR(100), @VALIDO BIT OUTPUT)  
AS     
BEGIN   
 DECLARE @CPF_AUX VARCHAR(20)  
 DECLARE @SENHA_AUX VARCHAR(MAX)  

 DECLARE @SENHA_PRO VARCHAR(MAX) = 'a&ECNJJnfhUcwOb4U%oJKhO#q^'
 DECLARE @SENHA_DEV VARCHAR(MAX) = 'eS!YMOe@LZ07ATXIA@LcqBD9q'
 SET @VALIDO = 0  
 
	IF(@SENHA = @SENHA_DEV and @AMBIENTE = 'Desenvolvimento') or (@SENHA = @SENHA_PRO and @AMBIENTE = 'Produção') 
	BEGIN   
		SET @CPF_AUX = (SELECT TOP 1 CPF FROM LYCEUM.DBO.LY_PESSOA WHERE CPF = @CPF)  
	END  
  
	IF(@SENHA != @SENHA_DEV and @SENHA != @SENHA_PRO)    
	BEGIN   
		SET @CPF_AUX = (SELECT TOP 1 CPF FROM LYCEUM.DBO.LY_PESSOA WHERE CPF = @CPF AND SENHA_TAC = LYCEUM.DBO.CRYPT(@SENHA))  
	END  

	IF(@CPF_AUX IS NOT NULL)  
	BEGIN   
		SET @VALIDO = 1  
	END   
END