select TIPO,* FROM LY_DISCIPLINA WHERE DISCIPLINA IN ('143015','143016','143017','143018','143019','143020','143023','143024','143025','143026','150170','150177')
select * FROM LY_TURMA WHERE ANO = 2019 AND SEMESTRE = 1 AND CURSO = '722'

select * FROM LY_ALUNO WHERE ALUNO = '160500278'
select * FROM LY_PRE_MATRICULA WHERE ALUNO = '160500278'
select * FROM LY_PREMATGRADE WHERE ALUNO = '160500278'
DELETE FROM LY_PREMATGRADE WHERE ALUNO = '160500278' AND ANO = 2016
select * FROM LY_ALUNO WHERE ALUNO = '160500155'
select * FROM LY_ALUNO WHERE CURSO = '50EFII' AND CURRICULO = '2016' AND TURNO = 'M' AND SERIE = '9'
select * FROM LY_HISTMATRICULA WHERE ALUNO = '160500161'
select * FROM LY_HISTMATRICULA WHERE ALUNO = '160500155'
select * FROM LY_HISTMATRICULA WHERE SITUACAO_HIST = 'Dispensado'
SELECT * FROM LY_CURRICULO_SEQ
select * FROM LY_ALUNO_CURSO_PROXIMO WHERE ALUNO = '160500278'
select * FROM LY_ALUNO_CURSO_SUBSEQUENTE WHERE ALUNO = '160500278'

select * FROM LY_H_CURR_ALUNO WHERE ALUNO = '160500155'
select * FROM LY_PRE_MATRICULA WHERE ALUNO = '160500155'


INSERT INTO LY_HISTMATRICULA
select A.ALUNO,'1','2017','0',G.DISCIPLINA,NULL,NULL,'Dispensado',1,D.HORAS_AULA,D.CREDITOS,NULL,D.HORAS_AULA,'DI-Curricular',NULL,NULL,D.HORAS_AULA,NULL,'Presencial',G.SERIE_IDEAL,NULL,NULL,NULL,'Curricular',NULL,NULL,'N',GETDATE(),A.DT_INGRESSO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
FROM LY_GRADE G
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = G.DISCIPLINA
JOIN LY_ALUNO A ON A.CURRICULO = G.CURRICULO AND A.CURSO = G.CURSO AND A.TURNO = G.TURNO
WHERE A.ALUNO = '160500278'
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND DISCIPLINA = G.DISCIPLINA AND SITUACAO_HIST IN ('Dispensado','Aprovado'))

select * FROM LY_GRADE_SERIE WHERE CURSO = '50EFI' AND CURRICULO = '2016' ORDER BY SERIE
select * FROM LY_GRADE WHERE CURSO = '50EFI' AND CURRICULO = '2016' AND TURNO = 'M' ORDER BY SERIE_IDEAL
select * FROM LY_HISTMATRICULA WHERE ALUNO = '160500278'

Select a.curso, a.turno, a.curriculo from ly_curriculo c, ly_curriculo_seq s, ly_aluno_curso_subsequente a 
where c.curso = s.curso and c.turno = s.turno and c.curriculo = s.curriculo and s.curso_seq = a.curso 
and s.turno_seq = a.turno AND s.curriculo_seq = a.curriculo and a.ALUNO = '160500278' and c.curso = '50EFII' and c.turno = 'M' and c.curriculo = '2016'

select * FROM LY_SERIE WHERE CURSO = '50EFII' AND TURNO = 'M' AND CURRICULO = '2018'
select * FROM LY_SERIE WHERE CURSO = '50EM' AND TURNO = 'M' AND CURRICULO = '2018'

select * FROM LY_GRADE WHERE CURSO = '50EFII' AND CURRICULO = '2018' AND TURNO = 'M' ORDER BY SERIE_IDEAL
select * FROM LY_GRADE WHERE CURSO = '50EM' AND CURRICULO = '2018' AND TURNO = 'M' ORDER BY SERIE_IDEAL

select ly_serie.serie from ly_serie 
                 where ly_serie.curso = '50EM' 
                   and ly_serie.turno =  'M'
                   and ly_serie.curriculo = '2018'
                   and ly_serie.serie > '9'
                   order by ly_serie.serie 

select * FROM LY_DISCIPLINA WHERE DISCIPLINA LIKE '50EM1%'

select * FROM LY_MATGRADE WHERE ALUNO = '160500278'
DELETE FROM LY_IMAGEM WHERE ANO = 2018 AND SEMESTRE = 0 AND TURMA = '50EM1AM'