SELECT DISTINCT M.ANO
				, M.SEMESTRE
				, A.UNIDADE_FISICA
				, A.CURSO
				, C.NOME AS NOME_CURSO
				, A.ALUNO
				, A.NOME_COMPL
				, M.DISCIPLINA
				, D.NOME
				, M.SIT_MATRICULA
				, T.SIT_TURMA
FROM LY_ALUNO A
JOIN VW_MATRICULA_E_PRE_MATRICULA M ON M.ALUNO = A.ALUNO
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = M.DISCIPLINA
JOIN LY_TURMA T ON T.DISCIPLINA = M.DISCIPLINA AND T.TURMA = M.TURMA AND T.ANO = M.ANO AND T.SEMESTRE = M.SEMESTRE
JOIN LY_CURSO C ON C.CURSO = A.CURSO
WHERE 1=1
AND D.CATEGORIA_ENTURMACAO = 'DIGITAL'
AND M.ANO = 2017 AND M.SEMESTRE = 1
AND NOT EXISTS (SELECT 1 FROM LY_NOTA N WHERE N.ALUNO = M.ALUNO AND N.DISCIPLINA = M.DISCIPLINA AND N.TURMA = M.TURMA AND N.ANO = M.ANO AND N.SEMESTRE = M.SEMESTRE AND N.PROVA = 'VA')
ORDER BY 3,5,7