USE LYCEUM
GO

UPDATE LY_CONSULTA_DINAMICA
SET STORED_PROCEDURE = 'sp:FTC_csvControleDocenteAulasSemanais(@p_ano@,@p_semestre@,@p_unidade_fisica@,@p_docente@)'
WHERE ID = 31
GO

UPDATE LY_CONSULTA_DINAMICA_PARAMETROS
SET SQL_TEXTO  = 'SELECT DISTINCT SEMESTRE AS CODIGO, ANO AS DESCRICAO FROM LY_TURMA WHERE ANO = ISNULL(@p_ano@,ANO) ORDER BY SEMESTRE',ORDEM = 2
WHERE PARAMETRO = 'p_semestre' ANd ID = 186
GO

UPDATE LY_CONSULTA_DINAMICA_PARAMETROS
SET SQL_TEXTO  = 'SELECT  NUM_FUNC AS CODIGO , NOME_COMPL AS DESCRICAO FROM LY_DOCENTE  where NUM_FUNC = isnull(@p_docente@,NUM_FUNC) order by NUM_FUNC'
WHERE PARAMETRO = 'p_docente' ANd ID = 187
GO

UPDATE LY_CONSULTA_DINAMICA_PARAMETROS
SET SQL_TEXTO  = 'SELECT UNIDADE_FIS AS CODIGO, NOME_COMP AS DESCRICAO FROM LY_UNIDADE_FISICA order by UNIDADE_FIS', PARAMETRO = 'p_unidade_fisica', ORDEM = 4
WHERE PARAMETRO = 'p_unidade_ensino' ANd ID = 188
GO

DELETE FROM LY_CONSULTA_DINAMICA_PARAMETROS WHERE ID = 189 AND PARAMETRO = 'p_tipo'
GO