--SINTETICO

SELECT   COUNT(A.ALUNO)QTD_ALUNO,A.CURRICULO,A.CURSO,A.TURNO,C.NOME AS NOME_CURSO,A.UNIDADE_FISICA,G.DISCIPLINA,D.NOME,D.CREDITOS
FROM LY_ALUNO A 
INNER JOIN LY_GRADE G ON G.CURSO=A.CURSO AND G.CURRICULO=A.CURRICULO AND G.TURNO=A.TURNO
INNER JOIN LY_DISCIPLINA D ON D.DISCIPLINA= G.DISCIPLINA
INNER JOIN LY_CURSO C ON C.CURSO=A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
WHERE 1=1
AND NOT EXISTS(SELECT TOP 1 1 FROM  LY_HISTMATRICULA H
				JOIN LY_ALUNO A ON A.ALUNO = H.ALUNO 
               WHERE H.ALUNO = A.ALUNO 
               AND (H.DISCIPLINA=G.DISCIPLINA OR (G.FORMULA_EQUIV LIKE '%'+H.DISCIPLINA+'%' AND G.CURSO = A.CURSO AND G.CURRICULO = A.CURRICULO AND G.TURNO = A.TURNO))
               AND  H.SITUACAO_HIST IN ('Aprovado','Dispensado')
               )
AND  EXISTS (SELECT  TOP 1 1  FROM LY_HISTMATRICULA HM 
             WHERE HM.ALUNO = A.ALUNO AND HM.ANO=2018 AND HM.SEMESTRE=2)
GROUP BY A.CURRICULO,A.CURSO,A.TURNO,C.NOME,A.UNIDADE_FISICA,G.DISCIPLINA,D.NOME,D.CREDITOS
ORDER BY 7

--ANALITICO

SELECT   A.ALUNO,A.NOME_COMPL,A.CURRICULO,A.CURSO,A.TURNO,C.NOME AS NOME_CURSO,A.UNIDADE_FISICA,G.DISCIPLINA,D.NOME,D.CREDITOS
FROM LY_ALUNO A 
INNER JOIN LY_GRADE G ON G.CURSO=A.CURSO AND G.CURRICULO=A.CURRICULO AND G.TURNO=A.TURNO
INNER JOIN LY_DISCIPLINA D ON D.DISCIPLINA= G.DISCIPLINA 
INNER JOIN LY_CURSO C ON C.CURSO=A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
WHERE 1=1
AND NOT EXISTS(SELECT TOP 1 1 FROM  LY_HISTMATRICULA H
				JOIN LY_ALUNO A ON A.ALUNO = H.ALUNO 
               WHERE H.ALUNO = A.ALUNO 
               AND (H.DISCIPLINA=G.DISCIPLINA OR (G.FORMULA_EQUIV LIKE '%'+H.DISCIPLINA+'%' AND G.CURSO = A.CURSO AND G.CURRICULO = A.CURRICULO AND G.TURNO = A.TURNO))
               AND  H.SITUACAO_HIST IN ('Aprovado','Dispensado')
               )
AND  EXISTS (SELECT TOP 1 1  FROM LY_HISTMATRICULA HM 
             WHERE HM.ALUNO = A.ALUNO AND HM.ANO=2018 AND HM.SEMESTRE=2)

ORDER BY 8,7