USE LYCEUM
GO

DECLARE @P_ANO INT = 2021;
DECLARE @P_SEMESTRE INT = 1;

--IF OBJECT_ID('TEMPDB.DBO.#TEMP', 'U') IS NOT NULL DROP TABLE #TEMP;

WITH PLANO_PAGAMENTO (ALUNO, RESP, VENCIMENTO_ATUAL, VENCIMENTO_ANTERIOR)
AS
(
	SELECT	PPP1.ALUNO AS ALUNO
			,PPP1.RESP AS RESP
			,PPP1.DIA_VENCIMENTO AS VENCIMENTO_ATUAL
			,PPP2.DIA_VENCIMENTO AS VENCIMENTO_ANTERIOR
	FROM LY_PLANO_PGTO_PERIODO PPP1
	JOIN LY_PLANO_PGTO_PERIODO PPP2 ON PPP2.ALUNO = PPP1.ALUNO AND PPP1.RESP = PPP2.RESP AND PPP2.ANO = CASE WHEN @P_SEMESTRE = 1 THEN @P_ANO-1 ELSE @P_ANO END AND PPP2.PERIODO = CASE WHEN @P_SEMESTRE = 1 THEN 2 ELSE @P_SEMESTRE END
	WHERE PPP1.ANO = @P_ANO AND PPP1.PERIODO = @P_SEMESTRE
	AND PPP1.RESP NOT IN ('FIES','03738654000105','00360305000104')
)


SELECT DISTINCT @P_ANO AS ANO, @P_SEMESTRE AS SEMESTRE, UE.NOME_ABREV, UE.NOME_COMP, C.TIPO, C.NOME, PP.RESP, A.ALUNO, A.NOME_COMPL, PP.VENCIMENTO_ANTERIOR, PP.VENCIMENTO_ATUAL
--INTO #TEMP
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN PLANO_PAGAMENTO PP ON PP.ALUNO = A.ALUNO
WHERE 1=1
AND EXISTS (SELECT TOP 1 1 FROM #TEMP WHERE ALUNO = A.ALUNO AND RESP = PP.RESP) 
--AND PP.VENCIMENTO_ANTERIOR <> PP.VENCIMENTO_ATUAL
AND EXISTS (SELECT TOP 1 1 FROM LY_MATRICULA M WHERE M.ALUNO = A.ALUNO AND M.ANO = @P_ANO AND M.SEMESTRE = @P_SEMESTRE AND M.SIT_MATRICULA IN ('Matriculado','Aprovado','Rep Nota','Rep Freq')) 
ORDER BY 1,4


UPDATE P SET P.DIA_VENCIMENTO = CASE	WHEN ISNULL(T.VENCIMENTO_ANTERIOR,0) < 10 THEN 10
										WHEN ISNULL(T.VENCIMENTO_ANTERIOR,0) BETWEEN 11 AND 14 THEN 15
										WHEN ISNULL(T.VENCIMENTO_ANTERIOR,0) BETWEEN 16 AND 19 THEN 20
										WHEN ISNULL(T.VENCIMENTO_ANTERIOR,0) > 20 THEN 30
										ELSE ISNULL(T.VENCIMENTO_ANTERIOR,0)
								END
FROM LY_PLANO_PGTO_PERIODO P
JOIN #TEMP T ON T.ALUNO = P.ALUNO AND P.ANO = T.ANO AND P.PERIODO = T.SEMESTRE AND P.RESP = T.RESP
WHERE T.VENCIMENTO_ANTERIOR >= VENCIMENTO_ATUAL

UPDATE P SET P.DIA_VENCIMENTO = CASE	WHEN ISNULL(T.VENCIMENTO_ATUAL,0) < 10 THEN 10
										WHEN ISNULL(T.VENCIMENTO_ATUAL,0) BETWEEN 11 AND 14 THEN 15
										WHEN ISNULL(T.VENCIMENTO_ATUAL,0) BETWEEN 16 AND 19 THEN 20
										WHEN ISNULL(T.VENCIMENTO_ATUAL,0) > 20 THEN 30
										ELSE ISNULL(T.VENCIMENTO_ATUAL,0)
								END
FROM LY_PLANO_PGTO_PERIODO P
JOIN #TEMP T ON T.ALUNO = P.ALUNO AND P.ANO = T.ANO AND P.PERIODO = T.SEMESTRE AND P.RESP = T.RESP
WHERE 1=1


