USE LYCEUM
GO

DECLARE @P_ALUNO VARCHAR(20) = '202041087'
DECLARE @P_ANO INT = 2021
DECLARE @P_SEMESTRE INT = 1
DECLARE @P_DIVIDA INT
  
DECLARE            
  @P_SITFINANOK T_SIMNAO,            
  @P_MSG_ERRO VARCHAR(4000),
  @P_DATA_LIMITE VARCHAR(10)

--SETA DATA LIMITE PARA VERIFICAÇÃO FINANCEIRA          
   SET @P_DATA_LIMITE = CASE       
       WHEN @P_SEMESTRE = 1 THEN CAST(@p_ano AS VARCHAR(4))+'-03-31'       
       WHEN @P_SEMESTRE = 2 THEN CAST(@p_ano AS VARCHAR(4))+'-07-01'      
       WHEN @P_SEMESTRE = 3 THEN CAST(@p_ano AS VARCHAR(4))+'-04-01' --TRIMESTRAL ESPECIAL EAD 1º SEMESTRE      
       --WHEN @P_SEMESTRE = 11 THEN CAST(@p_ano AS VARCHAR(4))+'-01-01' --TRIMESTRAL      
       --WHEN @P_SEMESTRE = 12 THEN CAST(@p_ano AS VARCHAR(4))+'-03-01' --TRIMESTRAL      
       --WHEN @P_SEMESTRE = 23 THEN CAST(@p_ano AS VARCHAR(4))+'-07-01' --TRIMESTRAL      
       --WHEN @P_SEMESTRE = 24 THEN CAST(@p_ano AS VARCHAR(4))+'-10-01' --TRIMESTRAL      
      END   
EXEC SITUACAOFINANOK            
        @P_ALUNO,             
        'N',            
        2021,            
        1,            
        @P_SITFINANOK OUTPUT,            
        @P_MSG_ERRO OUTPUT,            
        NULL,            
        NULL,            
        NULL,            
        @P_DATA_LIMITE     --data limite
		
SELECT @P_SITFINANOK,@P_MSG_ERRO

--TEM PRE_MATRÍCULA?
SELECT * FROM LY_PRE_MATRICULA WHERE ALUNO = @P_ALUNO AND ANO = @P_ANO AND SEMESTRE = @P_SEMESTRE
--ESCOLHEU CH NO MATRÍCULA FINANCEIRA?
SELECT * FROM LYCEUMINTEGRACAO..REMATRICULA WHERE ALUNO = @P_ALUNO
--TEM DÉBITO?
SELECT * FROM LY_LANC_DEBITO WHERE ALUNO = @P_ALUNO AND ANO_REF = @P_ANO AND PERIODO_REF = @P_SEMESTRE
SELECT @P_DIVIDA = LANC_DEB FROM LY_LANC_DEBITO WHERE ALUNO = @P_ALUNO AND ANO_REF = @P_ANO AND PERIODO_REF = @P_SEMESTRE
--TEM PLANO DE PAGAMENTO?
SELECT * FROM LY_PLANO_PGTO_PERIODO WHERE ALUNO = @P_ALUNO AND ANO = @P_ANO AND PERIODO = @P_SEMESTRE
--TEM COBRANÇA GERADA?
SELECT * FROM VW_COBRANCA WHERE ALUNO = @P_ALUNO AND ANO  = @P_ANO AND MES = @P_SEMESTRE
--QUAIS SAO AS BOLSAS?
SELECT * FROM LY_BOLSA WHERE ALUNO = @P_ALUNO AND (ANOFIM >= @P_ANO OR ANOFIM IS NULL) AND DATA_CANCEL IS NULL
--TEM CONTRATO?
SELECT * FROM LY_CONTRATO_ALUNO WHERE ALUNO = @P_ALUNO AND ANO = @P_ANO AND PERIODO = @P_SEMESTRE
--PAGO?
SELECT LYCEUMINTEGRACAO.DBO.FN_FTC_ALUNO_PAGO(@P_ALUNO,@P_DIVIDA) AS PAGO
  

--SELECT * FROM VW_COBRANCA WHERE COBRANCA = '30837071'
--SELECT * FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '201210118'
--SELECT LYCEUMINTEGRACAO.DBO.FN_FTC_ALUNO_PAGO('211100040',28986353)
--SELECT * FROM LY_TIPO_BOLSA WHERE TIPO_BOLSA = 'BOLSA DOM SSA'
--SELECT * FROM LY_RESP_FINAN WHERE RESP IN ('00360305000104','03738654000105')