--RELATORIO COM TODOS OS REQUIREMENTO PENDENDTE

DECLARE
  @servico VARCHAR(20),
  @setor   VARCHAR(20),
  @data    VARCHAR(10)

SET @servico=''
SET @setor=''
SET @data=''

SELECT DISTINCT 
 SS.SOLICITACAO
,SS.ALUNO
,AL.NOME_COMPL AS NOME_ALUNO
,AL.UNIDADE_FISICA
--,al.UNIDADE_ENSINO
,CONVERT(VARCHAR(10),SS.DATA,103) AS DATA_ABERTURA 
,ISS.SERVICO +' - '+TS.DESCRICAO AS SERVICO
,FA.PASSO
,A.COMENTARIO
,CONVERT(VARCHAR(10),A.DATA,103) AS DATA_ATENDIMENTO
,A.STATUS
,A.SETOR
,U.NOME AS USUARIO
,A.PROXIMO_SETOR
,A.SETOR
,FA.TIPO_ANDAMENTO
FROM  LY_SOLICITACAO_SERV SS
INNER JOIN LY_ANDAMENTO A ON A.SOLICITACAO = SS.SOLICITACAO 
INNER JOIN LY_ALUNO AL ON AL.ALUNO=SS.ALUNO
INNER JOIN LY_ITENS_SOLICIT_SERV ISS ON ISS.SOLICITACAO =SS.SOLICITACAO
INNER JOIN LY_TABELA_SERVICOS TS ON TS.SERVICO=ISS.SERVICO
INNER JOIN LY_FLUXO_DE_ANDAMENTO FA ON FA.SERVICO=ISS.SERVICO
INNER JOIN HD_USUARIO U ON U.USUARIO=A.USUARIO
WHERE 1=1
--AND ISS.SERVICO='GRD_REAB_TRANC'
--AND FA.PASSO=5
AND NOT  EXISTS(SELECT 1 FROM  LY_ANDAMENTO AA WHERE AA.SOLICITACAO=SS.SOLICITACAO)


select distinct  SS.SOLICITACAO,ss.ALUNO,al.UNIDADE_FISICA,convert(varchar(10),ss.DATA,103) as DATA_ABERTURA,iss.SERVICO,ts.DESCRICAO,ss.OBS,fa.SETOR,fa.PASSO,fa.PRAZO
,fa.TIPO_ANDAMENTO
,la.STATUS
--,(SELECT TOP 1 AA.STATUS FROM  LY_ANDAMENTO AA WHERE AA.SOLICITACAO=SS.SOLICITACAO AND  AA.STATUS IN ('Executado','Atendido'))
FROM  LY_SOLICITACAO_SERV SS
INNER JOIN LY_ITENS_SOLICIT_SERV ISS ON ISS.SOLICITACAO =SS.SOLICITACAO
INNER JOIN LY_FLUXO_DE_ANDAMENTO FA ON FA.SERVICO=ISS.SERVICO
INNER JOIN LY_TABELA_SERVICOS TS ON TS.SERVICO=ISS.SERVICO
INNER JOIN LY_ALUNO AL ON AL.ALUNO=SS.ALUNO
LEFT JOIN dbo.LY_ANDAMENTO la ON SS.SOLICITACAO = LA.SOLICITACAO AND LA.PASSO=FA.PASSO
where 1=1
--and ss.DATA >'2017-01-01'
--AND FA.PASSO=5
AND  not EXISTS(SELECT 1 FROM  LY_ANDAMENTO AA WHERE AA.SOLICITACAO=SS.SOLICITACAO /*AND  AA.STATUS IN ('Executado','Atendido')*/)

union
--Requerimentos já executados
SELECT DISTINCT SS.SOLICITACAO,ss.ALUNO,al.UNIDADE_FISICA,convert(varchar(10),ss.DATA,103) as DATA_ABERTURA,iss.SERVICO,ts.DESCRICAO,ss.OBS,fa.SETOR,fa.PASSO,fa.PRAZO,fa.TIPO_ANDAMENTO
,la.STATUS
--,(SELECT TOP 1 AA.STATUS FROM  LY_ANDAMENTO AA WHERE AA.SOLICITACAO=SS.SOLICITACAO) as STATUS
FROM  LY_SOLICITACAO_SERV SS
INNER JOIN LY_ITENS_SOLICIT_SERV ISS ON ISS.SOLICITACAO =SS.SOLICITACAO
INNER JOIN LY_FLUXO_DE_ANDAMENTO FA ON FA.SERVICO=ISS.SERVICO
INNER JOIN LY_TABELA_SERVICOS TS ON TS.SERVICO=ISS.SERVICO
INNER JOIN LY_ALUNO AL ON AL.ALUNO=SS.ALUNO
LEFT JOIN dbo.LY_ANDAMENTO la ON SS.SOLICITACAO = LA.SOLICITACAO AND LA.PASSO=FA.PASSO
where 1=1
--and ss.DATA >'2017-01-01'
--AND FA.PASSO=5
AND   EXISTS(SELECT 1 FROM  LY_ANDAMENTO AA WHERE AA.SOLICITACAO=SS.SOLICITACAO)
--AND SS.SOLICITACAO='26106'


SELECT * FROM  LY_ANDAMENTO AA WHERE  aa.SOLICITACAO='26106'



SELECT  ISS.ALUNO,A.UNIDADE_FISICA,AN.SERVICO,TS.DESCRICAO,AN.SOLICITACAO,AN.PASSO,AN.STATUS,AN.SETOR, CONVERT(VARCHAR (10),AN.DATA,103) AS DATA_EXECUCAO FROM LY_ANDAMENTO AN 
INNER JOIN LY_SOLICITACAO_SERV ISS ON ISS.SOLICITACAO =AN.SOLICITACAO
INNER JOIN LY_ALUNO A ON A.ALUNO=ISS.ALUNO
INNER JOIN LY_TABELA_SERVICOS TS ON TS.SERVICO=AN.SERVICO
WHERE 1=1
--and AN.STATUS in ('Atendido','executado')
order by AN.SOLICITACAO


SELECT  distinct status FROM  LY_ANDAMENTO


SELECT * FROM  LY_ANDAMENTO






