select P.CPF, DBO.DECRYPT(SENHA_TAC),* from LY_PESSOA P
JOIN LY_ALUNO A ON A.PESSOA = P.PESSOA
WHERE A.ALUNO = '211100040'

select * from LY_NOTA_HISTMATR

select * from LY_CONTRATO_REMOVIDO WHERE ALUNO = '211100040'
