SELECT	DISTINCT TOP 500
		LC.LANC_CRED
		VW.COBRANCA,
		C.ESTORNO AS COBRANCA_ESTORNADA,
		C.DT_ESTORNO AS DATA_ESTORNO,
		ISNULL(LC.TIPO_PAGAMENTO,'') AS TIPO_PAGAMENTO,
		ISNULL(LC.TIPO_CRED,'') AS TIPO_CREDITO,
		C.UNID_FISICA AS COD_UNIDADE,
		CUR.TIPO AS TIPO_CURSO,
		C.CURSO AS COD_CURSO,
		CUR.NOME,
		VW.ALUNO, 
		VW.RESP AS RESPONSAVEL,
		CONVERT(VARCHAR(10),C.DATA_DE_VENCIMENTO,105) AS DATA_VENCIMENTO,
		CONVERT(VARCHAR(10),LC.DT_CREDITO,105) AS DATA_PAGAMENTO,
		CONVERT(VARCHAR(10),LC.DATA,105) AS DATA_RECEBIMENTO,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA AND IL.ITEM_ESTORNADO IS NULL AND IL.NUM_BOLSA IS NULL) AS VALOR_BRUTO,
		(SELECT ISNULL(SUM(VALOR),0)*-1 FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = VW.COBRANCA AND IL.ITEM_ESTORNADO IS NULL AND IL.NUM_BOLSA IS NOT NULL) AS BOLSA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC1 WHERE IC1.COBRANCA = VW.COBRANCA AND IC1.TIPO_ENCARGO = 'MULTA') AS MULTA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC4 WHERE IC4.COBRANCA = VW.COBRANCA AND IC4.TIPO_ENCARGO = 'PERDEBOLSA') AS PERDEBOLSA,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC2 WHERE IC2.COBRANCA = VW.COBRANCA AND IC2.TIPO_ENCARGO = 'JUROS') AS JUROS,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = VW.COBRANCA AND IC3.TIPODESCONTO IN ('Acréscimo','Concedido','DescBanco','PagtoAntecipado')) AS DESCONTO,
		(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_CRED IC3 WHERE IC3.COBRANCA = VW.COBRANCA AND IC3.TIPODESCONTO IS NULL AND IC3.TIPO_ENCARGO IS NULL)*-1 AS VALOR_PAGO
FROM AY_VW_FATURAMENTO VW
JOIN LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
JOIN LY_CURSO CUR ON CUR.CURSO = C.CURSO
LEFT JOIN LY_ITEM_CRED IC ON IC.LANC_CRED = C.COBRANCA
LEFT JOIN LY_LANC_CREDITO LC ON LC.LANC_CRED = IC.LANC_CRED
WHERE  1=1
--VW.COBRANCA = '26911'


SELECT * FROM LY_ITEM_CRED WHERE LANC_CRED = '20511'
SELECT * FROM LY_LANC_CREDITO WHERE LANC_CRED = '40835'

SELECT * FROM vw_fluxo_caixa_rel WHERE LANC_CRED = '69162'

SELECT DISTINCT IL.CODIGO_LANC FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = 21363
SELECT DISTINCT TIPODESCONTO FROM LY_ITEM_CRED IL WHERE IL.COBRANCA = 21363
SELECT * FROM LY_ITEM_CRED IL WHERE IL.COBRANCA = 26911
