 SELECT DISTINCT c.ANO_INI
				,c.SEM_INI
				, c1.tipo
				,C1.CURSO
				, C1.NOME
				, c.CURRICULO
				, c.TURNO
				, c1.FACULDADE
				, ue.NOME_COMP
				, c.DT_HOMOLOG
				, c.AULAS_PREVISTAS
				, c.CREDITOS AS CREDITOS_CURRICULO
				, SUM(D.CREDITOS) AS CREDITOS_DISCIPLINAS
				, SUM(D.HORAS_AULA+HORAS_LAB+HORAS_ATIV+HORAS_ESTAGIO) AS CH_TOTAL_DISCIPLINAS
   FROM LY_CURRICULO c
 JOIN LY_CURSO c1 ON c1.CURSO = c.CURSO
 JOIN LY_UNIDADE_ENSINO ue ON ue.UNIDADE_ENS = c1.FACULDADE
 JOIN LY_GRADE G ON G.CURSO = c.CURSO AND G.CURRICULO = c.CURRICULO AND G.TURNO = c.TURNO
 JOIN LY_DISCIPLINA D ON D.DISCIPLINA = G.DISCIPLINA
 WHERE 1=1
 --AND c.DT_HOMOLOG = (SELECT MAX(DT_HOMOLOG) FROM LY_CURRICULO WHERE CURSO = c.CURSO)
 AND DT_EXTINCAO IS NULL
 AND c1.ativo = 'S'
 AND c1.FACULDADE <> '02'
 GROUP BY c.ANO_INI
				,c.SEM_INI
				, c1.tipo
				,C1.CURSO
				, C1.NOME
				, c.CURRICULO
				, c.TURNO
				, c1.FACULDADE
				, ue.NOME_COMP
				, c.DT_HOMOLOG
				, c.AULAS_PREVISTAS
				, c.CREDITOS
 ORDER BY FACULDADE, TIPO, CURSO