SELECT	DISTINCT
              PM.ANO, 
			  PM.SEMESTRE, 
			  C.CURSO,  
			  C.NOME AS NOME_CURSO, 
			  A.CURRICULO, 
			  A.TURNO, 
			  C.FACULDADE, 
              UE.NOME_COMP as NOME_FACULDADE, 
			  'Pré-Matriculado' AS SIT_MATRICULA, 
			  A.ALUNO, 
			  P.NOME_COMPL,
              P.CPF,
			  P.RG_NUM, 
			  a.anoconcl_2g as ANO_CONCLUSAO_2G, 
			  P.E_MAIL,
			  P.ENDERECO,
              P.END_NUM AS NUMERO,
              P.END_COMPL AS COMPLEMENTO,
              P.CEP,
              hm.NOME AS CIDADE,
              hm.UF AS ESTADO,	
              P.FONE, 
			  P.CELULAR, 
			  B.TIPO_BOLSA, 
			  TB.DESCRICAO AS NOME_BOLSA, 
              B.PERC_VALOR, 
			  B.VALOR, 
			  B.ANOINI, 
			  B.MESINI, 
			  B.ANOFIM, 
			  B.MESFIM, 
              B.DATA_BOLSA, 
			  B.DATA_CANCEL AS DATA_CANCELAMENTO_BOLSA,
			  VW.COBRANCA,
			  CASE WHEN VW.VALOR <=0 THEN 'S' ELSE 'N' END AS PAGO,  
              PM.DISCIPLINA, 
			  D.NOME AS NOME_DISCIPLINA, 
			  PM.TURMA, 
			  PM.CONFIRMADA, 
              a.sit_aluno
FROM VW_COBRANCA VW
JOIN LY_ALUNO A ON VW.ALUNO = VW.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_PRE_MATRICULA PM ON PM.ALUNO = VW.ALUNO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA AND IL.LANC_DEB = PM.LANC_DEB
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = PM.DISCIPLINA
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN LY_BOLSA B ON B.ALUNO = VW.ALUNO
LEFT JOIN LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
JOIN HD_MUNICIPIO HM ON HM.MUNICIPIO = P.END_MUNICIPIO
WHERE C.TIPO = 'GRADUACAO'

UNION ALL

SELECT	DISTINCT
              PM.ANO, 
			  PM.SEMESTRE, 
			  C.CURSO,  
			  C.NOME AS NOME_CURSO, 
			  A.CURRICULO, 
			  A.TURNO, 
			  C.FACULDADE, 
              UE.NOME_COMP as NOME_FACULDADE, 
			  PM.SIT_MATRICULA, 
			  A.ALUNO, 
			  P.NOME_COMPL,
              P.CPF,
			  P.RG_NUM, 
			  a.anoconcl_2g as ANO_CONCLUSAO_2G, 
			  P.E_MAIL,
			  P.ENDERECO,
              P.END_NUM AS NUMERO,
              P.END_COMPL AS COMPLEMENTO,
              P.CEP,
              hm.NOME AS CIDADE,
              hm.UF AS ESTADO,	
              P.FONE, 
			  P.CELULAR, 
			  B.TIPO_BOLSA, 
			  TB.DESCRICAO AS NOME_BOLSA, 
              B.PERC_VALOR, 
			  B.VALOR, 
			  B.ANOINI, 
			  B.MESINI, 
			  B.ANOFIM, 
			  B.MESFIM, 
              B.DATA_BOLSA, 
			  B.DATA_CANCEL AS DATA_CANCELAMENTO_BOLSA,
			  VW.COBRANCA,
			  CASE WHEN VW.VALOR <=0 THEN 'S' ELSE 'N' END AS PAGO,  
              PM.DISCIPLINA, 
			  D.NOME AS NOME_DISCIPLINA, 
			  PM.TURMA, 
			  'S' AS CONFIRMADA, 
              a.sit_aluno
FROM VW_COBRANCA VW
JOIN LY_ALUNO A ON VW.ALUNO = VW.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_MATRICULA PM ON PM.ALUNO = VW.ALUNO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA AND IL.LANC_DEB = PM.LANC_DEB
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = PM.DISCIPLINA
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
LEFT JOIN LY_BOLSA B ON B.ALUNO = VW.ALUNO
LEFT JOIN LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
JOIN HD_MUNICIPIO HM ON HM.MUNICIPIO = P.END_MUNICIPIO
WHERE C.TIPO = 'GRADUACAO'