DROP TABLE #SERVICO

SELECT S.CURSO, S.TURNO, S.CURRICULO, S.SERIE, S.SERVICO_CRED
INTO #SERVICO
FROM LY_SERIE S
JOIN LY_CURRICULO C ON C.CURSO = S.CURSO AND C.TURNO = S.TURNO AND C.CURRICULO = S.CURRICULO
JOIN LY_CURSO CUR ON CUR.CURSO = C.CURSO
WHERE NOT EXISTS (SELECT 1 FROM LY_VALOR_SERV_PERIODO VSP WHERE VSP.SERVICO = S.SERVICO )
AND S.DT_EXTINCAO IS NULL
AND C.DT_EXTINCAO IS NULL
AND CUR.ATIVO = 'S'

DROP TABLE #DISCIPLINAS

SELECT DISTINCT DISCIPLINA 
INTO #DISCIPLINAS
FROM LY_PRE_MATRICULA PM
WHERE PM.ALUNO LIKE '162%'
UNION
SELECT DISTINCT DISCIPLINA 
FROM LY_MATRICULA M
WHERE M.ALUNO LIKE '162%'


DROP TABLE #DISCIPLINA_SERVICO

SELECT DISTINCT S.SERVICO_CRED, G.DISCIPLINA 
INTO #DISCIPLINA_SERVICO
FROM #SERVICO S
JOIN LY_GRADE G ON G.CURSO = S.CURSO AND G.TURNO = S.TURNO AND G.CURRICULO = S.CURRICULO AND G.SERIE_IDEAL = S.SERIE
WHERE  G.DISCIPLINA IN (SELECT DISCIPLINA FROM #DISCIPLINAS)
AND S.SERVICO_CRED IS NOT NULL
ORDER BY 1

SELECT * FROM #SERVICO S
WHERE NOT EXISTS (SELECT 1 FROM LY_VALOR_SERV_PERIODO VSP WHERE VSP.SERVICO = S.SERVICO_CRED)
AND EXISTS (SELECT 1 FROM LY_ALUNO A WHERE A.CURSO = S.CURSO AND A.TURNO = S.TURNO AND A.CURRICULO = S.CURRICULO)
AND S.SERVICO_CRED IS NOT NULL
--AND S.SERIE = '1'
ORDER BY 1,2,3,4,5
