SELECT	T.UNIDADE_RESPONSAVEL AS UNIDADE_ENSINO,
		UE.NOME_COMP AS NOME_UNIDADE_ENS,
		T.FACULDADE AS UNIDADE_FISICA,
		UF.NOME_COMP AS NOME_UNIDADE_FIS,
		T.ANO,
		T.SEMESTRE,
		T.SIT_TURMA,
		T.TURMA,
		T.DISCIPLINA,
		isnull(T.NIVEL,'') AS NIVEL_TURMA,
		isnull(D.TIPO,'') AS TIPO_DISCIPLINA,
		D.NOME AS NOME_DISCIPLINA,
		T.CURSO,
		C.NOME AS NOME_CURSO,
		C.FACULDADE AS UNIDADE_CURSO,
		ISNULL(TC.CURSO,'') AS RESERVA_CURSO,
		ISNULL((SELECT C1.NOME FROM LY_CURSO C1 WHERE C1.CURSO = TC.CURSO),'') AS NOME_RESERVA_CURSO,
		ISNULL(TC.VAGAS,0) AS VAGAS,
		ISNULL(T.TEM_HORARIO,'N') AS TEM_HORARIO
FROM LY_TURMA T
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = T.DISCIPLINA
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = T.UNIDADE_RESPONSAVEL
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = T.FACULDADE
JOIN LY_CURSO C ON C.CURSO = T.CURSO
LEFT JOIN LY_TURMA_CURSO TC ON TC.DISCIPLINA = T.DISCIPLINA AND TC.TURMA = T.TURMA AND TC.ANO = T.ANO AND TC.SEMESTRE = T.SEMESTRE 
WHERE T.ANO = 2017 AND T.SEMESTRE = 1
AND NOT EXISTS (SELECT 1 FROM LY_AGENDA AG WHERE AG.ANO = T.ANO AND AG.SEMESTRE = T.SEMESTRE AND AG.DISCIPLINA = T.DISCIPLINA AND AG.TURMA = T.TURMA) 
--AND NOT EXISTS (SELECT 1 FROM LY_FREQ FQ WHERE FQ.ANO = T.ANO AND FQ.PERIODO = T.SEMESTRE AND FQ.DISCIPLINA = T.DISCIPLINA AND FQ.TURMA = T.TURMA) 
--AND NOT EXISTS (SELECT 1 FROM LY_HOR_AULA HA WHERE HA.ANO = T.ANO AND HA.SEMESTRE = T.SEMESTRE AND HA.DISCIPLINA = T.DISCIPLINA AND HA.TURMA = T.TURMA) 
ORDER BY 1,3,9,8

--SELECT	TC.ANO,
--		TC.SEMESTRE,
--		TC.TURMA,
--		TC.DISCIPLINA,
--		D.NOME AS NOME_DISCIPLINA,
--		TC.CURSO,
--		C.NOME AS NOME_CURSO,
--		TC.VAGAS 
--FROM LY_TURMA_CURSO TC
--JOIN LY_CURSO C ON C.CURSO = TC.CURSO
--JOIN LY_DISCIPLINA D ON D.DISCIPLINA = TC.DISCIPLINA
--WHERE (TC.ANO = 2017 AND TC.SEMESTRE = 1)
--ORDER BY 4,6


