SELECT DISTINCT A.ALUNO, A.NOME_COMPL, P.CPF, C.CURSO, C.NOME,A.TURNO,CONCAT(P.DDD_FONE+'-',P.FONE) AS TELEFONE, CONCAT(P.DDD_FONE_CELULAR+'-',P.CELULAR) AS CELULAR, P.E_MAIL  
FROM LY_ALUNO A
JOIN VW_MATRICULA_E_PRE_MATRICULA VW ON VW.ALUNO = A.ALUNO
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
WHERE C.FACULDADE = '04' AND C.TIPO = 'GRADUACAO'
AND A.ANO_INGRESSO = '2017' AND A.SEM_INGRESSO = '1'
AND VW.SIT_MATRICULA = 'Pre-matriculado'
ORDER BY 4,2