USE LYCEUM
GO

--EXEC FTC_Relat_AlunosAtivosPos ''

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.FTC_Relat_AlunosAtivosPos'))
   exec('CREATE PROCEDURE [dbo].[FTC_Relat_AlunosAtivosPos] AS BEGIN SET NOCOUNT OFF; END')
GO 


ALTER PROCEDURE dbo.FTC_Relat_AlunosAtivosPos       
(            
 @p_unidade VARCHAR(20)
 )
 AS
 -- [INÍCIO]                    
BEGIN            

SET NOCOUNT ON   

select A.UNIDADE_FISICA, UF.NOME_COMP, A.CURSO, C.NOME,A.SIT_ALUNO, A.ALUNO, A.NOME_COMPL, ISNULL(CONCAT(P.DDD_FONE_CELULAR,P.CELULAR),'') AS CELULAR, P.E_MAIL, 1 AS PAGO, 0 AS NAO_PAGO
FROM LY_ALUNO A
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
WHERE 1=1
--AND FA.FL_FIELD_01 = 'VIRTUAL'
AND ((C.FACULDADE = @p_unidade AND ISNULL(@p_unidade,'') <> '') OR ISNULL(@p_unidade,'') = '')
AND C.TIPO = 'POS-GRADUACAO'
AND A.SIT_ALUNO = 'Ativo'
AND EXISTS (SELECT TOP 1 1 FROM LY_COBRANCA WHERE ALUNO = A.ALUNO AND DATA_DE_VENCIMENTO >= GETDATE() AND DATA_DE_FATURAMENTO IS NOT NULL AND ESTORNO = 'N' AND DT_ESTORNO IS NULL)
AND (EXISTS (SELECT TOP 1 1 FROM LY_ITEM_CRED IC
				JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.ALUNO = A.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','ACORDO'))
					
		OR EXISTS (SELECT TOP 1 1 FROM VW_COBRANCA VW
					JOIN LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					JOIN LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
					WHERE VW.ALUNO = A.ALUNO AND VW.VALOR <= 0
					AND IL.PARCELA = 1
					AND IL.CODIGO_LANC IN ('MS','MS_EB','ACORDO')
					AND C.DT_ESTORNO IS NULL))

UNION

select A.UNIDADE_FISICA, UF.NOME_COMP, A.CURSO, C.NOME,A.SIT_ALUNO, A.ALUNO, A.NOME_COMPL, ISNULL(CONCAT(P.DDD_FONE_CELULAR,P.CELULAR),'') AS CELULAR, P.E_MAIL, 0 AS PAGO, 1 AS NAO_PAGO
--COUNT(A.ALUNO), A.UNIDADE_FISICA 
FROM LY_ALUNO A
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
WHERE 1=1
AND ((C.FACULDADE = @p_unidade AND ISNULL(@p_unidade,'') <> '') OR ISNULL(@p_unidade,'') = '')
AND C.TIPO = 'POS-GRADUACAO'
AND A.SIT_ALUNO = 'Ativo'
AND EXISTS (SELECT TOP 1 1 FROM LY_COBRANCA WHERE ALUNO = A.ALUNO AND DATA_DE_VENCIMENTO >= GETDATE() AND DATA_DE_FATURAMENTO IS NOT NULL AND ESTORNO = 'N' AND DT_ESTORNO IS NULL)
AND (NOT EXISTS (SELECT TOP 1 1 FROM LY_ITEM_CRED IC
				JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.ALUNO = A.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','ACORDO'))
		AND NOT EXISTS (SELECT TOP 1 1 FROM VW_COBRANCA VW
					JOIN LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					JOIN LY_COBRANCA C ON C.COBRANCA = VW.COBRANCA
					WHERE VW.ALUNO = A.ALUNO AND VW.VALOR <= 0
					AND IL.PARCELA = 1
					AND IL.CODIGO_LANC IN ('MS','MS_EB','ACORDO')
					AND C.DT_ESTORNO IS NULL))

ORDER BY A.UNIDADE_FISICA, A.CURSO, A.ALUNO

SET NOCOUNT OFF

END

-- [FIM]  

  
DELETE FROM LY_CUSTOM_CLIENTE    
where NOME = 'FTC_Relat_AlunosAtivosPos'    
and IDENTIFICACAO_CODIGO = '0001' 
GO

INSERT INTO LY_CUSTOM_CLIENTE
(NOME, IDENTIFICACAO_CODIGO, AUTOR, DATA_CRIACAO, OBJETIVO, SOLICITADO_POR, ATIVO, TIPOCOMPONENTE, TIPO, CLIENTE)
SELECT
  'FTC_Relat_AlunosAtivosPos' NOME
, '0001' IDENTIFICAO_CODIGO
, 'Miguel' AUTOR
, '2018-03-05' DATA_CRIACAO
, 'Relatório - Alunos Ativos da Pós com contas em aberto' OBJETIVO
, 'Reinaldo Borba' SOLICITADO_POR
, 'S' ATIVO
, 'PROCEDURE' TIPOCOMPONENTE
, 'CLIENTE' TIPO
, 'FTC' CLIENTE
GO 