USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.Relat_P_AvaliacaoM'))
   exec('CREATE PROCEDURE [dbo].[Relat_P_AvaliacaoM] AS BEGIN SET NOCOUNT OFF; END')
GO
  
ALTER PROCEDURE [dbo].[Relat_P_AvaliacaoM]   

AS    
BEGIN    
    
SELECT	TIPO_QUESTIONARIO AS CODIGO
		,TIPO_QUESTIONARIO+' - '+DESCRICAO AS DESCR 
FROM LY_TIPO_QUESTIONARIO
WHERE TIPO_QUESTIONARIO IN ('Av Docente M I','Av Docente M II')

ORDER BY 1    
    
END; 

