--Relat_Faturamento_NC_FiesProuni  '03','FTC-FSA',NULL,NULL,NULL,NULL,NULL,'S','2017-01-01','2017-01-31',NULL,NUll,NULL,NULL

USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.Relat_Faturamento_NC_FiesProuni'))
   exec('CREATE PROCEDURE [dbo].[Relat_Faturamento_NC_FiesProuni] AS BEGIN SET NOCOUNT OFF; END')
GO

ALTER PROCEDURE dbo.Relat_Faturamento_NC_FiesProuni    
(      
 @p_unidade VARCHAR(20),    
 @p_unid_fisica VARCHAR(20),
 @p_tipo VARCHAR(20),    
 @p_curso VARCHAR(20)   

)      
      
AS      

-- [INÍCIO]                
BEGIN  

SELECT	A.ALUNO
		,A.NOME_COMPL AS NOME_ALUNO
		,CU.TIPO AS TIPO_CURSO
		,CU.CURSO AS COD_CURSO
		,CU.NOME AS NOME_CURSO
		,CU.FACULDADE AS COD_UNIDADE
		,UE.NOME_COMP AS NOME_UNIDADE
		,M.NOME_COMP AS MANTENEDORA
		,CASE c.NUM_COBRANCA    
             WHEN 1 THEN 'MENSALIDADE'    
             WHEN 2 THEN 'SERVICO'    
             WHEN 3 THEN 'ACORDO'    
             WHEN 4 THEN 'OUTROS'    
             WHEN 5 THEN 'CHEQUE DEVOLVIDO'    
             ELSE NULL END AS TIPO_COBRANCA
		,C.COBRANCA  
		,(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = C.COBRANCA AND IL.NUM_BOLSA IS NULL AND IL.ITEM_ESTORNADO IS NULL) AS [VALOR_BRUTO]
		,(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = C.COBRANCA AND IL.ITEM_ESTORNADO IS NOT NULL)						AS [VALOR_ESTORNOS]
		,(SELECT ISNULL(SUM(VALOR),0) FROM LY_ITEM_LANC IL WHERE IL.COBRANCA = C.COBRANCA AND IL.NUM_BOLSA IS NOT NULL AND IL.ITEM_ESTORNADO IS NULL)	AS [VALOR_BOLSAS]
		,C.ANO
		,C.MES
FROM LY_ALUNO A
JOIN LY_BOLSA B ON B.ALUNO = A.ALUNO
JOIN LY_CURSO CU ON CU.CURSO = A.CURSO
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = CU.FACULDADE
JOIN LY_INSTITUICAO I ON I.NOME_ABREV = A.UNIDADE_FISICA
JOIN LY_MANTENEDORA M ON M.MANTENEDORA = I.MANTENEDORA
JOIN LY_COBRANCA C ON C.ALUNO = A.ALUNO
JOIN LY_ITEM_LANC IL ON IL.COBRANCA = C.COBRANCA
WHERE B.TIPO_BOLSA IN ('FIES_TEMP','FIES','FIESGERAL','FIES100','FIESFNDE','FIESTA','PROUNI R','PROUNI_100','PROUNI_50','PROUNI100','PROUNI50')
AND NOT EXISTS (SELECT TOP 1 1 FROM AY_RESUMO_ATO WHERE COBRANCA = C.COBRANCA AND ALUNO = A.ALUNO)
AND C.ESTORNO = 'N'
AND CU.FACULDADE = '03'
AND CONCAT(C.ANO,C.MES) >= '20160'

END                
-- [FIM]