USE LYCEUM
GO

DECLARE
    @p_unidade          T_CODIGO,  
    @p_unidade_fisica   T_CODIGO,  
    @p_tipo             T_CODIGO,  
    @p_curso            T_CODIGO,  
    @p_datareceb_ini    DATETIME,  
    @p_datareceb_fim    DATETIME,  
    @p_aluno            T_CODIGO  
      
SET @p_unidade   = NULL  
SET @p_unidade_fisica   = NULL  
SET @p_tipo             = NULL 
SET @p_curso            = NULL  
SET @p_datareceb_ini    = '2017-01-01'  
SET @p_datareceb_fim     = '2017-12-31'
SET @p_aluno            = '152040173'
    
     
      SELECT  DISTINCT  
        C.FACULDADE UNID_RESP, FR.NOME_COMP NOME_UNID_RESP, FR.CGC,  
        FR.ENDERECO, FR.END_NUM, FR.END_COMPL, FR.BAIRRO, MU.NOME MUNICIPIO, MU.UF_SIGLA,   
        A.UNIDADE_FISICA UNID_FISICA, FF.NOME_COMP NOME_UNID_FISICA,  
        C.CURSO, C.NOME NOME_CURSO, A.ALUNO, A.NOME_COMPL, P.SEXO ALU_SEXO, PR.COBRANCA,   
        CAST(PR.ANOREF AS VARCHAR) + '/' + CAST(PR.MESREF AS VARCHAR) AS PARCELA,   
        PR.DATA_DE_VENCIMENTO AS DATA_VENCTO, RL.DT_RECEBIMENTO AS DATA_PAGAMENTO,  
		RL.VALOR AS VALOR_PAGO,
        --dbo.fn_VW_Receita_Liquida(pr.COBRANCA, RL.DT_RECEBIMENTO, RL.DT_RECEBIMENTO) AS VALOR_PAGO,
		PR.anoref,
		PR.mesref,
		RL.LANC_CRED 
    FROM VW_Cobranca_Mensalidade pr   
     INNER JOIN LY_CURSO c ON pr.CURSO = c.CURSO  
        INNER JOIN VW_RECEITA_LIQUIDA RL ON PR.COBRANCA = RL.COBRANCA AND PR.ANOREF = RL.ANOREF AND PR.MESREF = RL.MESREF AND PR.ALUNO = RL.ALUNO  
        INNER JOIN LY_ALUNO A ON PR.ALUNO = A.ALUNO  
        INNER JOIN LY_PESSOA P ON A.PESSOA = P.PESSOA  
        INNER JOIN LY_FACULDADE FR ON C.FACULDADE = FR.FACULDADE  
        INNER JOIN MUNICIPIO MU ON FR.MUNICIPIO = MU.CODIGO  
        INNER JOIN LY_FACULDADE FF ON A.UNIDADE_FISICA = FF.FACULDADE  
    WHERE 1=1  
        --dbo.fn_VW_Receita_Liquida(pr.COBRANCA, RL.DT_RECEBIMENTO, RL.DT_RECEBIMENTO) > 0 
		AND pr.NUM_COBRANCA IN (1,2) --MOSTRAR SOMENTE PAGAMENTOS DE COBRANÇAS DE MENSALIDADE E ACORDOS
		AND RL.VALOR > 0     
        AND C.FACULDADE = ISNULL(@p_unidade, C.FACULDADE)  
        AND A.UNIDADE_FISICA = ISNULL(@p_unidade_fisica, A.UNIDADE_FISICA)  
        AND C.TIPO = ISNULL(@p_tipo, C.TIPO)  
        AND C.CURSO = ISNULL(@p_curso, C.CURSO)  
        AND RL.DT_RECEBIMENTO >= ISNULL(@p_datareceb_ini, RL.DT_RECEBIMENTO)  
        AND RL.DT_RECEBIMENTO <= ISNULL(@p_datareceb_fim, RL.DT_RECEBIMENTO)  
        AND A.ALUNO = ISNULL(@p_aluno, A.ALUNO)  
        AND PR.RESP <> 'FIES'  -- MFR: NÃO MOSTRAR PAGAMENTOS DO RESPONSÁVEL FIES  
		AND NOT EXISTS (SELECT 1 FROM VW_LANC_CREDITO_REMOVIDO WHERE LANC_CRED = RL.LANC_CRED ) --NÃO MOSTRAR PAGAMENTOS ESTORNADOS
    ORDER BY   
       pr.AnoRef, pr.MesRef

