USE BLACKBOARD
GO

IF EXISTS (SELECT * FROM sys.tables WHERE type = 'U' AND OBJECT_ID = OBJECT_ID('dbo.SA_BB_ACESSO'))   
BEGIN
	DROP TABLE SA_BB_ACESSO
END    

CREATE TABLE SA_BB_ACESSO (
	 COURSE_ID VARCHAR(100),
     COURSE_NAME VARCHAR(333),
	 PERIODO_LETIVO VARCHAR(333),
     USER_ID VARCHAR(50),
     NOME_USUARIO VARCHAR(333),
     ROLE VARCHAR(50),
	 ROLE_NAME VARCHAR(64),
	 ROW_STATUS SMALLINT,
	 LAST_ACCESS_DATE DATETIME,
	 LAST_LOGIN_DATE DATETIME
)
