GO
USE DW_DATAMART

GO
CREATE TABLE DIM_LY_DISCIPLINA (
  DISCIPLINA VARCHAR(20)  NOT NULL  ,
  NOME_UNIDADE_ABREV VARCHAR(20)    ,
  DEPTO VARCHAR(20)    ,
  NOME VARCHAR(200)    ,
  NOME_COMPL VARCHAR(200)  NOT NULL  ,
  CREDITOS INT    ,
  TEM_NOTA VARCHAR(1)   DEFAULT ('S') ,
  TIPO_NOTA VARCHAR(15)  NOT NULL  ,
  TEM_FREQ VARCHAR(1)   DEFAULT ('S') ,
  PRIORIZA_FREQ VARCHAR(1)  NOT NULL DEFAULT ('S') ,
  VERIFICA_HORARIO VARCHAR(1)   DEFAULT ('S') ,
  ATIVA VARCHAR(1)   DEFAULT ('S') ,
  FORMULA_MF1 VARCHAR(500)  NOT NULL  ,
  FORMULA_MF2 VARCHAR(500)  NOT NULL  ,
  FORMULA_MF3 VARCHAR(500)  NOT NULL  ,
  FORMULA_CA1 VARCHAR(500)  NOT NULL  ,
  FORMULA_CA2 VARCHAR(500)  NOT NULL  ,
  FORMULA_CA3 VARCHAR(500)  NOT NULL  ,
  CONCEITO_MIN_1 VARCHAR(15)  NOT NULL  ,
  CONCEITO_MIN_2 VARCHAR(15)  NOT NULL  ,
  CONCEITO_MIN_3 VARCHAR(15)  NOT NULL  ,
  CONCEITO_MIN_EX VARCHAR(15)  NOT NULL  ,
  CONCEITO_MIN_EX_2 VARCHAR(15)  NOT NULL  ,
  PERC_PRESMIN NUMERIC(7, 4)  NOT NULL  ,
  SERVICO VARCHAR(20)  NOT NULL  ,
  ESTAGIO VARCHAR(1)   DEFAULT ('N') ,
  HORAS_AULA INT  NOT NULL DEFAULT (0) ,
  HORAS_LAB INT  NOT NULL DEFAULT (0) ,
  HORAS_ATIV INT  NOT NULL DEFAULT (0) ,
  HORAS_ESTAGIO INT  NOT NULL DEFAULT (0) ,
  PRAZO_REVISAO VARCHAR(3)   DEFAULT (0) ,
  FORMULA_PREREQ VARCHAR(2000)  NOT NULL  ,
  FORMULA_EQUIV VARCHAR(2000)  NOT NULL  ,
  TIPO VARCHAR(20)  NOT NULL  ,
  GRUPO_NOTA VARCHAR(20)  NOT NULL  ,
  GRUPO_MEDIA VARCHAR(20)  NOT NULL  ,
  N_CASAS_DEC VARCHAR(1)  NOT NULL  ,
  NOTA_MAX VARCHAR(15)  NOT NULL  ,
  N_CASAS_DEC_MEDIA NUMERIC(1)  NOT NULL  ,
  NOTA_MAX_MEDIA VARCHAR(15)  NOT NULL  ,
  AULAS_SEMANAIS DECIMAL(7, 4)  NOT NULL  ,
  AULAS_SEM_AULA DECIMAL(7, 4)  NOT NULL  ,
  AULAS_SEM_LAB DECIMAL(7, 4)  NOT NULL  ,
  AULAS_SEM_ATIV DECIMAL(7, 4)  NOT NULL  ,
  TRUNCA_MEDIA VARCHAR(1)   DEFAULT ('N') ,
  FALTA_DIARIA VARCHAR(1)  NOT NULL  ,
  PRAZO_DIVULGACAO VARCHAR(3)  NOT NULL  ,
  PIM VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  COPIA_NOTA_SUBTURMA VARCHAR(1)  NOT NULL DEFAULT ('S') ,
  NOME_FANTASIA VARCHAR(200)  NOT NULL  ,
  AVAL_COMPETENCIA VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  STAMP_ATUALIZACAO DATETIME  NOT NULL  ,
  TEM_AVAL_DESCRITIVA VARCHAR(1)  NOT NULL  ,
  COMPONENTE VARCHAR(40)  NOT NULL  ,
  AREA_CONHECIMENTO VARCHAR(40)  NOT NULL  ,
  PERMITE_MANTER_HORARIO VARCHAR(1)  NOT NULL  ,
  MULTIPLA VARCHAR(1)  NOT NULL  ,
  CAMPO_01 VARCHAR(20)  NOT NULL  ,
  CATEGORIA_ENTURMACAO VARCHAR(40)  NOT NULL  ,
  OBS_FORMULA_MF1 VARCHAR(500)  NOT NULL  ,
  OBS_FORMULA_MF2 VARCHAR(500)  NOT NULL  ,
  OBS_FORMULA_MF3 VARCHAR(500)  NOT NULL  ,
  FL_FIELD_01 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_02 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_03 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_04 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_05 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_06 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_07 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_08 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_09 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_10 VARCHAR(2000)  NOT NULL  ,
  TIPO_ESTAGIO VARCHAR(20)  NOT NULL    ,
PRIMARY KEY(DISCIPLINA));
GO

CREATE TABLE DIM_LY_CURSO (
  CURSO VARCHAR(20)  NOT NULL  ,
  NUM_FUNC VARCHAR(15)  NOT NULL  ,
  NOME_UNIDADE_ABREV VARCHAR(20)    ,
  MNEMONICO VARCHAR(6)    ,
  NOME VARCHAR(2000)  NOT NULL  ,
  HABILITACAO VARCHAR(255)  NOT NULL  ,
  TITULO VARCHAR(50)    ,
  DECRETO VARCHAR(2000)  NOT NULL  ,
  ATIVO VARCHAR(1)   DEFAULT ('S') ,
  FORMATURA VARCHAR(1)   DEFAULT ('S') ,
  KIT VARCHAR(20)  NOT NULL  ,
  TIPO VARCHAR(20)  NOT NULL  ,
  DT_DOU DATETIME  NOT NULL  ,
  COBRAN_DISC VARCHAR(1)   DEFAULT ('S') ,
  VAGAS INT  NOT NULL  ,
  VALOR_CRED_ASSOC_DISC VARCHAR(1)   DEFAULT ('S') ,
  DEPTO VARCHAR(20)  NOT NULL  ,
  USA_SERIE_IDEAL VARCHAR(1)  NOT NULL  ,
  MODALIDADE VARCHAR(20)  NOT NULL  ,
  INEP_DTINICIO DATETIME  NOT NULL  ,
  INEP_AREA_DE_CONHECIMENTO VARCHAR(50)  NOT NULL  ,
  INEP_CURSO VARCHAR(50)  NOT NULL  ,
  INEP_GRAU VARCHAR(50)  NOT NULL  ,
  INEP_NIVEL VARCHAR(50)  NOT NULL  ,
  INEP_PRESENCIAL VARCHAR(1)  NOT NULL  ,
  INEP_TIPOCURSOEXTENSAO VARCHAR(50)  NOT NULL  ,
  INEP_TIPOCURSOPOS VARCHAR(50)  NOT NULL  ,
  INEP_TURNO VARCHAR(50)  NOT NULL  ,
  INEP_EXT_ALUNOSCONCLUINTES INT  NOT NULL  ,
  INEP_EXT_ALUNOSEXECUTIVOS INT  NOT NULL  ,
  INEP_EXT_ALUNOSGRADUACAO INT  NOT NULL  ,
  INEP_EXT_ALUNOSMATRICULADOS INT  NOT NULL  ,
  INEP_EXT_ALUNOSOUTRASIES INT  NOT NULL  ,
  INEP_EXT_ALUNOSPOSGRADUACAO INT  NOT NULL  ,
  INEP_EXT_ALUNOSPROFEDBASICA INT  NOT NULL  ,
  INEP_EXT_ALUNOSPROFLIBERAIS INT  NOT NULL  ,
  INEP_EXT_CARGA_HORARIA NUMERIC(18)  NOT NULL  ,
  INEP_EXT_DOCENTESIES INT  NOT NULL  ,
  INEP_EXT_DOCENTESOUTRASIES INT  NOT NULL  ,
  INEP_EXT_PESSOASCOMUNIDADE INT  NOT NULL  ,
  INEP_EXT_PESSOASOUTRASIES INT  NOT NULL  ,
  INEP_EXT_SERVIDORESIES INT  NOT NULL  ,
  INEP_TIPODOC_CRIACAO VARCHAR(50)  NOT NULL  ,
  INEP_NUMDESPACHO_CRIACAO VARCHAR(50)  NOT NULL  ,
  INEP_DTDESPACHO_CRIACAO DATETIME  NOT NULL  ,
  INEP_TIPODOC_REC VARCHAR(50)  NOT NULL  ,
  INEP_NUMDOC_REC VARCHAR(50)  NOT NULL  ,
  INEP_DTPUBL_REC DATETIME  NOT NULL  ,
  INEP_VALIDADE_REC VARCHAR(50)  NOT NULL  ,
  INEP_NUMDESPACHO_REC VARCHAR(50)  NOT NULL  ,
  INEP_DTDESPACHO_REC DATETIME  NOT NULL  ,
  INEP_DIPLOMA_REC VARCHAR(1)  NOT NULL  ,
  INEP_DTFINAL_REC DATETIME  NOT NULL  ,
  INEP_TIPODOC_RENOV VARCHAR(50)  NOT NULL  ,
  INEP_NUMDOC_RENOV VARCHAR(50)  NOT NULL  ,
  INEP_DTPUBL_RENOV DATETIME  NOT NULL  ,
  INEP_VALIDADE_RENOV VARCHAR(50)  NOT NULL  ,
  INEP_NUMDESPACHO_RENOV VARCHAR(50)  NOT NULL  ,
  INEP_DTDESPACHO_RENOV DATETIME  NOT NULL  ,
  INEP_Q01 VARCHAR(100)  NOT NULL  ,
  INEP_Q02 VARCHAR(100)  NOT NULL  ,
  INEP_Q03 VARCHAR(100)  NOT NULL  ,
  INEP_OCDE VARCHAR(50)  NOT NULL  ,
  INEP_DIPLOMAS VARCHAR(2000)  NOT NULL  ,
  INEP_TURNOOFERTA VARCHAR(50)  NOT NULL  ,
  INEP_REGIME VARCHAR(50)  NOT NULL  ,
  GRUPO_CURSO VARCHAR(20)  NOT NULL  ,
  CURSO_ASSOCIADO VARCHAR(20)  NOT NULL  ,
  FACULDADE_ASSOCIADA VARCHAR(20)  NOT NULL  ,
  NOME_SECRETARIA VARCHAR(100)  NOT NULL  ,
  RG_NUM_SECRETARIA VARCHAR(15)  NOT NULL  ,
  PORTARIA_SECRETARIA VARCHAR(255)  NOT NULL  ,
  NOME_DIRETOR VARCHAR(100)  NOT NULL  ,
  RG_NUM_DIRETOR VARCHAR(15)  NOT NULL  ,
  PORTARIA_DIRETOR VARCHAR(255)  NOT NULL  ,
  STAMP_ATUALIZACAO DATETIME  NOT NULL  ,
  TEM_RECLASSIFICACAO VARCHAR(1)  NOT NULL  ,
  DURACAO_AULA INT  NOT NULL  ,
  FL_FIELD_01 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_02 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_03 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_04 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_05 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_06 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_07 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_08 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_09 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_10 VARCHAR(2000)  NOT NULL  ,
  EVENTO VARCHAR(1)  NOT NULL DEFAULT ('N')   ,
PRIMARY KEY(CURSO));
GO

CREATE TABLE DIM_LY_DOCENTE (
  ID_DOCENTE INT  NOT NULL   IDENTITY ,
  NOME_DOCENTE VARCHAR(150)    ,
  CPF VARCHAR(20)    ,
  DEPTO VARCHAR(100)    ,
  ATIVO VARCHAR(20)    ,
  NOME_COMPL VARCHAR(200)    ,
  ENDERECO VARCHAR(200)    ,
  END_NUM VARCHAR(100)    ,
  END_COMPL VARCHAR(100)    ,
  BAIRRO VARCHAR(100)    ,
  MUNICIPIO VARCHAR(100)    ,
  CEP VARCHAR(20)    ,
  FONE VARCHAR(20)    ,
  RG_TIPO VARCHAR(20)    ,
  RG_NUM VARCHAR(20)    ,
  RG_DTEXP VARCHAR(20)    ,
  RG_UF VARCHAR(2)    ,
  RG_EMISSOR VARCHAR(20)    ,
  ENDCOM VARCHAR(200)    ,
  ENDCOM_NUM VARCHAR(50)    ,
  ENDCOM_COMPL VARCHAR(200)    ,
  ENDCOM_BAIRRO VARCHAR(100)    ,
  ENDCOM_PAIS VARCHAR(100)    ,
  ENDCOM_MUNICIPIO VARCHAR(100)    ,
  ENDCOM_CEP VARCHAR(20)    ,
  FONE_COM VARCHAR(20)    ,
  PERC_DEDIC_MENS VARCHAR(100)    ,
  E_MAIL VARCHAR(100)    ,
  MAILBOX VARCHAR(100)    ,
  OBS VARCHAR(100)    ,
  CPROF_NUM VARCHAR(100)    ,
  CPROF_SERIE VARCHAR(100)    ,
  CPROF_DATAEXP DATETIME    ,
  CPROF_UF VARCHAR(2)    ,
  HAB_TAC VARCHAR(20)    ,
  CELULAR VARCHAR(20)    ,
  FAX_RES VARCHAR(20)    ,
  FAX_COM VARCHAR(20)    ,
  NOME_EMPRESA VARCHAR(200)    ,
  E_MAIL_COM VARCHAR(100)    ,
  BANCO VARCHAR(100)    ,
  SEXO VARCHAR(20)    ,
  EST_CIVIL VARCHAR(20)    ,
  DT_ADMISSAO DATETIME    ,
  DT_NASC DATETIME    ,
  DT_ULT_TITULO DATETIME    ,
  FECHAR_TURMA_INTERNET VARCHAR(100)    ,
  CONTRATO_TRABALHO VARCHAR(100)    ,
  REGIME_TRABALHO VARCHAR(100)    ,
  FL_FIELD_01 VARCHAR(2000)    ,
  FL_FIELD_02 VARCHAR(2000)    ,
  FL_FIELD_03 VARCHAR(2000)    ,
  FL_FIELD_04 VARCHAR(2000)    ,
  FL_FIELD_05 VARCHAR(2000)    ,
  FL_FIELD_06 VARCHAR(2000)    ,
  FL_FIELD_07 VARCHAR(2000)    ,
  FL_FIELD_08 VARCHAR(2000)    ,
  FL_FIELD_09 VARCHAR(2000)    ,
  FL_FIELD_10 VARCHAR(2000)    ,
  NOME_SOCIAL VARCHAR(200)      ,
PRIMARY KEY(ID_DOCENTE));
GO

CREATE TABLE DIM_TEMPO (
  ID_TEMPO DATETIME  NOT NULL  ,
  FERIADO BIT  NOT NULL  ,
  DIA VARCHAR(2)    ,
  MES VARCHAR(2)    ,
  ANO VARCHAR(4)    ,
  SEMANA VARCHAR(2)    ,
  TRIMESTRE VARCHAR(2)    ,
  SEMESTRE VARCHAR(2)      ,
PRIMARY KEY(ID_TEMPO));
GO

CREATE TABLE DIM_LY_UNIDADE (
  ID_UNIDADE INT  NOT NULL  ,
  UNIDADE_ENS VARCHAR(20)    ,
  NOME_UNIDADE VARCHAR(100)    ,
  NOME_UNIDADE_ABREV VARCHAR    ,
  CENTRO_DE_CUSTO VARCHAR(20)  NOT NULL  ,
  DESCR_CENTRO_CUSTO VARCHAR(200)  NOT NULL    ,
PRIMARY KEY(ID_UNIDADE));
GO

CREATE TABLE DIM_DY_CONCURSO (
  ID_DY_CONCURSO INT  NOT NULL  ,
  NOME VARCHAR(200)    ,
  DT_VEST DATETIME    ,
  SEMESTRE VARCHAR(2)    ,
  ANO VARCHAR(4)    ,
  STATUS_CONCURSO VARCHAR(30)    ,
  CONSURSO_LYCEUM VARCHAR(30)    ,
  TIPO_CONCURSO_METE VARCHAR(30)    ,
  ORDENACAO_ENSALAMENTO VARCHAR(100)    ,
  CODIGO_SERVICO_PAGAMENTO VARCHAR(100)    ,
  TIPO_CONCURSO VARCHAR(30)    ,
  LINK VARCHAR(100)    ,
  UNIDADE VARCHAR(200)    ,
  CURSO VARCHAR(100)      ,
PRIMARY KEY(ID_DY_CONCURSO));
GO

CREATE TABLE DIM_DY_CANDIDATO (
  ID_DY_CANDIDATO INT  NOT NULL  ,
  CANDIDATO VARCHAR(30)    ,
  CPF VARCHAR(20)    ,
  NOME VARCHAR(200)    ,
  EMAIL VARCHAR(100)    ,
  CELULAR VARCHAR(20)    ,
  DADOS_VALIDADOS INT  NOT NULL  ,
  ENDERECO VARCHAR(250)    ,
  END_NUM VARCHAR(100)    ,
  END_COMPL VARCHAR(200)    ,
  BAIRRO VARCHAR(100)    ,
  MUNICIPIO VARCHAR(100)    ,
  CEP VARCHAR(20)    ,
  NECESSIDADE_ESPECIAL VARCHAR(30)    ,
  LINGUA VARCHAR(30)    ,
  SEXO VARCHAR(20)    ,
  TRAINEE VARCHAR(20)    ,
  INFORMACOES_SOBRE_BOLSAS VARCHAR(20)      ,
PRIMARY KEY(ID_DY_CANDIDATO));
GO

CREATE TABLE DIM_DY_OFERTAS (
  ID_DY_OFERTAS INT  NOT NULL  ,
  TURNO VARCHAR(20)    ,
  CURSO VARCHAR(200)    ,
  ANO VARCHAR(4)    ,
  PERIODO VARCHAR(7)    ,
  STATUS_CONCURSO VARCHAR(30)    ,
  CONSULTOR VARCHAR(100)    ,
  UNIDADE VARCHAR(200)    ,
  QTD_VAGAS FLOAT      ,
PRIMARY KEY(ID_DY_OFERTAS));
GO

CREATE TABLE DIM_LY_CONCURSO (
  CONCURSO VARCHAR(20)  NOT NULL  ,
  DESCRICAO VARCHAR(100)  NOT NULL  ,
  STATUS VARCHAR(15)    ,
  NUM_MAX_OPCOES VARCHAR(3)    ,
  ANO VARCHAR(4)    ,
  SEMESTRE VARCHAR(2)    ,
  TIPO_CLASSIFICACAO VARCHAR(30)  NOT NULL  ,
  CHAMADA_ATUAL VARCHAR(3)  NOT NULL  ,
  TEM_BOLETO VARCHAR(1)   DEFAULT ('N') ,
  BOLETO_BANCO VARCHAR(3)  NOT NULL  ,
  BOLETO_AGENCIA VARCHAR(7)  NOT NULL  ,
  BOLETO_CONTA_BANCO VARCHAR(15)  NOT NULL  ,
  BOLETO_INSTRUCOES VARCHAR(2000)  NOT NULL  ,
  BOLETO_DIA_VENCIMENTO DATETIME  NOT NULL  ,
  BOLETO_CARTEIRA INT  NOT NULL  ,
  BOLETO_ESPECIE_DOC INT  NOT NULL  ,
  BOLETO_ACEITE INT  NOT NULL  ,
  BOLETO_VALOR INT  NOT NULL  ,
  BOLETO_ESPECIE VARCHAR(2)  NOT NULL  ,
  INSCR_ABERTA VARCHAR(1)   DEFAULT ('N') ,
  PUBLIC_RESULT VARCHAR(1)   DEFAULT ('N') ,
  PUBLIC_PROVA VARCHAR(1)   DEFAULT ('N') ,
  DT_INICIO DATETIME  NOT NULL  ,
  DT_FIM DATETIME  NOT NULL  ,
  PUBLIC_SALA DATETIME   DEFAULT ('N') ,
  ENTREGA_DOCS VARCHAR(1)  NOT NULL  ,
  INSTRUCOES_CONCURSO VARCHAR(2000)  NOT NULL  ,
  N_DIAS_VENC_BOL INT  NOT NULL  ,
  IGNORA_ORDEM_CHAMADA VARCHAR(1)   DEFAULT ('N') ,
  NUM_DIG_COD VARCHAR(3)   DEFAULT (10) ,
  BOLETO_CONVENIO VARCHAR(20)  NOT NULL  ,
  RESTRINGE_LOCAL_PROVA VARCHAR(1)   DEFAULT ('N') ,
  DT_VEST DATETIME  NOT NULL  ,
  EXIGIR_RESP_FINAN VARCHAR(1)   DEFAULT ('N') ,
  INGR_MENS VARCHAR(2000)  NOT NULL  ,
  INGR_DTINI DATETIME  NOT NULL  ,
  INGR_DTFIM DATETIME  NOT NULL  ,
  INGR_BOL_DT_VENC DATETIME  NOT NULL  ,
  DISPONIVEL_WEB VARCHAR(1)   DEFAULT ('S') ,
  SIMULADO VARCHAR(1)   DEFAULT ('N') ,
  UTILIZA_ENEM_VESTIB VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  TEM_PRE_INSCRICAO VARCHAR(1)   DEFAULT ('S') ,
  AGENDADO VARCHAR(1)   DEFAULT ('N') ,
  N_DIAS_VENC_BOL_MATR VARCHAR(3)  NOT NULL  ,
  MATRICULA_AVULSA VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  PLANOPAG VARCHAR(20)  NOT NULL  ,
  GRUPO_ENCARGO VARCHAR(20)  NOT NULL  ,
  GRUPO_DESCONTO VARCHAR(20)  NOT NULL  ,
  TEM_VAGA_REMANESC VARCHAR(1)   DEFAULT ('N') ,
  GERA_COD_LOCALINSC VARCHAR(1)   DEFAULT ('N') ,
  MIN_TOTPONTOS DECIMAL(6, 2)  NOT NULL  ,
  LASTNUMCAND NUMERIC(10)   DEFAULT (0) ,
  COLABORADOR_META VARCHAR(20)  NOT NULL  ,
  TIPO_CONCURSO VARCHAR(40)  NOT NULL  ,
  EXIGE_DOCINGRESSO VARCHAR(1)   DEFAULT ('N') ,
  IMPRIMIR_REQUERIMENTO VARCHAR(1)  NOT NULL DEFAULT ('S') ,
  MODELO_BOLETO VARCHAR(3)  NOT NULL  ,
  IDADE_MINIMA VARCHAR(3)  NOT NULL  ,
  MSN_ENTREVISTA VARCHAR(2000)  NOT NULL  ,
  INGR_ENTURMA_PRE_MATR VARCHAR(1)   DEFAULT ('S') ,
  EXIGE_LOCAL_PROVA VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  INGR_ESCOLHE_PLANO VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  INGR_MAX_RESP_FINAN VARCHAR(3)  NOT NULL  ,
  AGENDAMENTO_MESMO_DIA VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  UNIDADE_RESPONSAVEL VARCHAR(20)  NOT NULL  ,
  FACULDADE VARCHAR(20)  NOT NULL  ,
  SUBPERIODO VARCHAR(2)  NOT NULL  ,
  INGR_EXIGE_RESP_LEGAL VARCHAR(1)   DEFAULT ('N') ,
  TIPO_QUESTIONARIO VARCHAR(20)  NOT NULL  ,
  QUESTIONARIO VARCHAR(20)  NOT NULL  ,
  APLICACAO VARCHAR(20)  NOT NULL  ,
  INGR_VER_FINAN VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  TIPO_INGRESSO VARCHAR(20)  NOT NULL  ,
  AGENDAMENTO_PROVA VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  CONV_MANUAL_OUTRO_CURSO VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  PERMITE_TREINEIRO VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  EXIGE_NecEsp VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  PERMITE_RESP_ESTRANG VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  INSTRUCOES_VIA_EMAIL VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_01 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_02 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_03 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_04 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_05 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_06 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_07 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_08 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_09 VARCHAR(2000)  NOT NULL  ,
  FL_FIELD_10 VARCHAR(2000)  NOT NULL  ,
  MENSAGEM_CANDIDATO VARCHAR(2000)  NOT NULL  ,
  ENSINO_BASICO VARCHAR(1)  NOT NULL DEFAULT ('N')   ,
PRIMARY KEY(CONCURSO));
GO

CREATE TABLE DIM_LY_ALUNO (
  ID_ALUNO INT  NOT NULL  ,
  ALUNO VARCHAR(20)    ,
  CURRICULO VARCHAR(20)    ,
  NOME_ALUNO VARCHAR(100)    ,
  NOME_SOCIAL VARCHAR(100)    ,
  EST_CIVIL VARCHAR(1)    ,
  SEXO VARCHAR(20)    ,
  COR_RACA VARCHAR(30)    ,
  DATA_NASCIMENTO DATETIME    ,
  ENDERECO VARCHAR(50)    ,
  NUMERO VARCHAR(20)    ,
  COMPLEMENTO VARCHAR(50)    ,
  CEP VARCHAR(9)    ,
  BAIRRO VARCHAR(50)    ,
  CIDADE VARCHAR(100)    ,
  ESTADO VARCHAR(2)    ,
  DDD_FONE VARCHAR(3)    ,
  FONE VARCHAR(30)    ,
  DDD_CELULAR VARCHAR(3)    ,
  E_MAIL VARCHAR(100)    ,
  RG VARCHAR(20)    ,
  CPF VARCHAR(20)    ,
  RG_NUM VARCHAR(20)    ,
  RG_TIPO VARCHAR(30)    ,
  RG_EMISSOR VARCHAR(100)    ,
  RG_UF VARCHAR(2)    ,
  RG_DTEXP DATETIME    ,
  TIP_ALUNO VARCHAR(30)      ,
PRIMARY KEY(ID_ALUNO));
GO

CREATE TABLE FAT_LY_ALUNO_CH_SEMESTRIALIZADO (
  ID_LY_ALUNO_CH_SEMESTRE_GERAL INT  NOT NULL   IDENTITY ,
  ID_ALUNO INT  NOT NULL  ,
  ANO_INGRESSO INT    ,
  SEM_INGRESSO INT    ,
  TURNO VARCHAR(2)    ,
  CURRICULO VARCHAR(30)    ,
  SERIE FLOAT    ,
  SIT_ALUNO VARCHAR(30)    ,
  TIP_INGRESSO VARCHAR(30)    ,
  QTD_DISC_CURSADAS_GRADE FLOAT    ,
  QTD_DISC_CURSADAS_FORA_GRADE FLOAT    ,
  QTD_GRADE_TOTAL FLOAT    ,
  QTD_GRADE_SERIE_1 FLOAT    ,
  QTD_HIST_SERIE_1 FLOAT    ,
  QTD_CH_GRADE_SERIE_1 FLOAT    ,
  QTD_CH_HIST_SERIE_1 FLOAT    ,
  QTD_GRADE_SERIE_2 FLOAT    ,
  QTD_HIST_SERIE_2 FLOAT    ,
  QTD_CH_GRADE_SERIE_2 FLOAT    ,
  QTD_CH_HIST_SERIE_2 FLOAT    ,
  QTD_GRADE_SERIE_3 FLOAT    ,
  QTD_HIST_SERIE_3 FLOAT    ,
  QTD_CH_GRADE_SERIE_3 FLOAT    ,
  QTD_CH_HIST_SERIE_3 FLOAT    ,
  QTD_GRADE_SERIE_4 FLOAT    ,
  QTD_HIST_SERIE_4 FLOAT    ,
  QTD_CH_GRADE_SERIE_4 FLOAT    ,
  QTD_CH_HIST_SERIE_4 FLOAT    ,
  QTD_GRADE_SERIE_5 FLOAT    ,
  QTD_HIST_SERIE_5 FLOAT    ,
  QTD_CH_GRADE_SERIE_5 FLOAT    ,
  QTD_CH_HIST_SERIE_5 FLOAT    ,
  QTD_GRADE_SERIE_6 FLOAT    ,
  QTD_HIST_SERIE_6 FLOAT    ,
  QTD_CH_GRADE_SERIE_6 FLOAT    ,
  QTD_CH_HIST_SERIE_6 FLOAT    ,
  QTD_GRADE_SERIE_7 FLOAT    ,
  QTD_HIST_SERIE_7 FLOAT    ,
  QTD_CH_GRADE_SERIE_7 FLOAT    ,
  QTD_CH_HIST_SERIE_7 FLOAT    ,
  QTD_GRADE_SERIE_8 FLOAT    ,
  QTD_HIST_SERIE_8 FLOAT    ,
  QTD_CH_GRADE_SERIE_8 FLOAT    ,
  QTD_CH_HIST_SERIE_8 FLOAT    ,
  QTD_GRADE_SERIE_9 FLOAT    ,
  QTD_HIST_SERIE_9 FLOAT    ,
  QTD_CH_GRADE_SERIE_9 FLOAT    ,
  QTD_CH_HIST_SERIE_9 FLOAT    ,
  QTD_GRADE_SERIE_10 FLOAT    ,
  QTD_HIST_SERIE_10 FLOAT    ,
  QTD_CH_GRADE_SERIE_10 FLOAT    ,
  QTD_CH_HIST_SERIE_10 FLOAT    ,
  QTD_GRADE_SERIE_11 FLOAT    ,
  QTD_HIST_SERIE_11 FLOAT    ,
  QTD_CH_GRADE_SERIE_11 FLOAT    ,
  QTD_CH_HIST_SERIE_11 FLOAT    ,
  QTD_GRADE_SERIE_12 FLOAT    ,
  QTD_HIST_SERIE_12 FLOAT    ,
  QTD_CH_GRADE_SERIE_12 FLOAT    ,
  QTD_CH_HIST_SERIE_12 FLOAT      ,
PRIMARY KEY(ID_LY_ALUNO_CH_SEMESTRE_GERAL, ID_ALUNO),
  FOREIGN KEY(ID_ALUNO)
    REFERENCES DIM_LY_ALUNO(ID_ALUNO));
GO

CREATE INDEX FK_Mod_Mult_77 ON FAT_LY_ALUNO_CH_SEMESTRIALIZADO (ID_ALUNO);
GO

CREATE TABLE DIM_TURMA (
  ID_TURMA INTEGER  NOT NULL  ,
  DISCIPLINA VARCHAR(20)  NOT NULL  ,
  TURMA VARCHAR(20)    ,
  ANO VARCHAR(4)    ,
  SEMESTRE VARCHAR(2)    ,
  NOME_UNIDADE_ABREV VARCHAR(20)    ,
  DEPENDENCIA VARCHAR(20)    ,
  NUM_FUNC VARCHAR(15)    ,
  TURNO VARCHAR(20)    ,
  CURSO VARCHAR(20)    ,
  CURRICULO VARCHAR(20)    ,
  SERIE VARCHAR(3)    ,
  AULAS_PREVISTAS DATETIME    ,
  MIN_AULAS DATETIME    ,
  NUM_ALUNOS INT    ,
  DT_ULTALT DATETIME    ,
  FORMULA_MF1 VARCHAR(500)    ,
  FORMULA_MF2 VARCHAR(500)    ,
  FORMULA_MF3 VARCHAR(500)    ,
  FORMULA_CA1 VARCHAR(500)    ,
  FORMULA_CA2 VARCHAR(500)    ,
  FORMULA_CA3 VARCHAR(500)    ,
  CONCEITO_MIN_1 VARCHAR(15)    ,
  CONCEITO_MIN_2 VARCHAR(15)    ,
  CONCEITO_MIN_3 VARCHAR(15)    ,
  CONCEITO_MIN_EX VARCHAR(15)    ,
  CONCEITO_MIN_EX_2 VARCHAR(15)    ,
  DT_INICIO DATETIME    ,
  DT_FIM DATETIME    ,
  SIT_TURMA VARCHAR(15)   NOT NULL DEFAULT ('Aberta') ,
  NIVEL VARCHAR(20)    ,
  AULAS_DADAS DATETIME    ,
  UNIDADE_RESPONSAVEL VARCHAR(1)   DEFAULT ('') ,
  ESPECIAL VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  UTILIZA_INDICE VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  TEM_HORARIO VARCHAR(1)    ,
  ULT_NUM_CHAMADA INT    ,
  NIVEL_PRESENCA VARCHAR(15)  NOT NULL DEFAULT ('Presencial') ,
  EXIBE_SOMENTE_LISTA_SEL VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  LANCAMENTO_HISTORICO VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  TURMA_INTEGRACAO VARCHAR(50)   DEFAULT ('N') ,
  INTERF_ENS_DIST VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  IDIOMA VARCHAR(40)    ,
  CLASSIFICACAO VARCHAR(40)    ,
  DT_LIMITE_ENTURMA DATETIME    ,
  STAMP_ATUALIZACAO DATETIME    ,
  DT_CONFIRMA_DOL DATETIME    ,
  EM_ELABORACAO VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  DISCIPLINA_MULTIPLA VARCHAR(20)    ,
  DT_CRIACAO DATETIME    ,
  DURACAO_AULA INT    ,
  PERMITE_CHOQUE_HORARIO VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  CENTRO_DE_CUSTO VARCHAR(50)    ,
  OBS_FORMULA_MF1 VARCHAR(500)    ,
  OBS_FORMULA_MF2 VARCHAR(500)    ,
  OBS_FORMULA_MF3 VARCHAR(500)    ,
  UTILIZA_PROC_SELETIVO VARCHAR(1)  NOT NULL DEFAULT ('N') ,
  FL_FIELD_01 VARCHAR(2000)    ,
  FL_FIELD_02 VARCHAR(2000)    ,
  FL_FIELD_03 VARCHAR(2000)    ,
  FL_FIELD_04 VARCHAR(2000)    ,
  FL_FIELD_05 VARCHAR(2000)    ,
  FL_FIELD_06 VARCHAR(2000)    ,
  FL_FIELD_07 VARCHAR(2000)    ,
  FL_FIELD_08 VARCHAR(2000)    ,
  FL_FIELD_09 VARCHAR(2000)    ,
  FL_FIELD_10 VARCHAR(2000)    ,
  FL_FIELD_11 VARCHAR(2000)    ,
  FL_FIELD_12 VARCHAR(2000)    ,
  FL_FIELD_13 VARCHAR(2000)    ,
  FL_FIELD_14 VARCHAR(2000)    ,
  FL_FIELD_15 VARCHAR(2000)    ,
  FL_FIELD_16 VARCHAR(2000)    ,
  FL_FIELD_17 VARCHAR(2000)    ,
  FL_FIELD_18 VARCHAR(2000)    ,
  FL_FIELD_19 VARCHAR(2000)    ,
  FL_FIELD_20 VARCHAR(2000)    ,
  VAGAS_CALOUROS INT    ,
  VAGAS_VETERANOS INT      ,
PRIMARY KEY(ID_TURMA, DISCIPLINA),
  FOREIGN KEY(DISCIPLINA)
    REFERENCES DIM_LY_DISCIPLINA(DISCIPLINA));
GO

CREATE INDEX FK_Mod_Mult_55 ON DIM_TURMA (DISCIPLINA);
GO

CREATE TABLE FAT_DY_CLASSIFICACAO (
  ID_DY_CLASSIFICACOES INT  NOT NULL   IDENTITY ,
  ID_DY_CANDIDATO INT  NOT NULL  ,
  DATA_CLASSIFICACAO DATETIME    ,
  PONTUACAO_FINAL DECIMAL(10,2)      ,
PRIMARY KEY(ID_DY_CLASSIFICACOES, ID_DY_CANDIDATO),
  FOREIGN KEY(ID_DY_CANDIDATO)
    REFERENCES DIM_DY_CANDIDATO(ID_DY_CANDIDATO),
  FOREIGN KEY(DATA_CLASSIFICACAO)
    REFERENCES DIM_TEMPO(ID_TEMPO));
GO

CREATE INDEX FK_Mod_Mult_121 ON FAT_DY_CLASSIFICACAO (ID_DY_CANDIDATO);
GO
CREATE INDEX FK_Mod_Mult_130 ON FAT_DY_CLASSIFICACAO (DATA_CLASSIFICACAO);
GO

CREATE TABLE FAT_LY_ALUNO_CH_DISCIPLINA (
  ID_LY_ALUNO_CH_GERAL INTEGER  NOT NULL   IDENTITY ,
  ID_ALUNO INT  NOT NULL  ,
  DISCIPLINA VARCHAR(20)  NOT NULL  ,
  CURSO VARCHAR(20)    ,
  TURNO VARCHAR(1)    ,
  CURRICULO VARCHAR(30)    ,
  ALUNO_SERIE INT    ,
  TIPO_INGRESSO VARCHAR(30)    ,
  ANO_INGRESSO INT    ,
  SEM_INGRESSO INT    ,
  DISC_SERIE VARCHAR(1)    ,
  DISC_COD INT    ,
  DISC_NOME VARCHAR(200)    ,
  CH FLOAT    ,
  QTD_DISC_GRADE FLOAT    ,
  QTD_DISC_HIT_GRADE FLOAT      ,
PRIMARY KEY(ID_LY_ALUNO_CH_GERAL, ID_ALUNO, DISCIPLINA),
  FOREIGN KEY(ID_ALUNO)
    REFERENCES DIM_LY_ALUNO(ID_ALUNO),
  FOREIGN KEY(DISCIPLINA)
    REFERENCES DIM_LY_DISCIPLINA(DISCIPLINA));
GO

CREATE INDEX FK_Mod_Mult_78 ON FAT_LY_ALUNO_CH_DISCIPLINA (ID_ALUNO);
GO
CREATE INDEX FK_Mod_Mult_85 ON FAT_LY_ALUNO_CH_DISCIPLINA (DISCIPLINA);
GO

CREATE TABLE FAT_DY_AVALIACOES (
  ID_DY_AVALIACOES INT  NOT NULL   IDENTITY ,
  ID_DY_CANDIDATO INT  NOT NULL  ,
  DATA_AVALIACAO DATETIME    ,
  NOME_FATOR VARCHAR(100)    ,
  NOME_LOCAL_AVALIACAO VARCHAR(100)    ,
  NOME_GRUPO_AVALIACAO VARCHAR(100)    ,
  ENDERECO_LOCAL_AVALIACAO VARCHAR(200)    ,
  LINGUA_ESTRAGEIRA VARCHAR(50)    ,
  TIP_FATOR VARCHAR(30)    ,
  VAL_PADRAO_FATOR DECIMAL(10,2)    ,
  VAL_AVALIACAO DECIMAL(10,2)    ,
  VAL_CONSIDERADO DECIMAL(10,2)    ,
  VAL_LIMITE_FATOR DECIMAL(10,2)    ,
  VAL_TEXTO_PADRAO_FATOR VARCHAR(100)    ,
  VAL_PONTO_QUESTOES DECIMAL(10,2)    ,
  VAL_PONTO_QUESTOES_INICIAL DECIMAL(10,2)    ,
  VAL_PONTO_QUSTOES_FINAL DECIMAL(10,2)      ,
PRIMARY KEY(ID_DY_AVALIACOES, ID_DY_CANDIDATO),
  FOREIGN KEY(ID_DY_CANDIDATO)
    REFERENCES DIM_DY_CANDIDATO(ID_DY_CANDIDATO),
  FOREIGN KEY(DATA_AVALIACAO)
    REFERENCES DIM_TEMPO(ID_TEMPO));
GO

CREATE INDEX FK_Mod_Mult_120 ON FAT_DY_AVALIACOES (ID_DY_CANDIDATO);
GO
CREATE INDEX FK_Mod_Mult_83 ON FAT_DY_AVALIACOES (DATA_AVALIACAO);
GO

CREATE TABLE FAT_DOCENTE_CH (
  ID_DOCENTE_CH INT  NOT NULL   IDENTITY ,
  ID_DOCENTE INT  NOT NULL  ,
  ID_UNIDADE INT  NOT NULL  ,
  ANO VARCHAR(4)    ,
  SEMESTRE VARCHAR(2)    ,
  CH_SEMESTRE FLOAT    ,
  TURMA VARCHAR(1)    ,
  DISCIPLINA VARCHAR(100)      ,
PRIMARY KEY(ID_DOCENTE_CH, ID_DOCENTE, ID_UNIDADE),
  FOREIGN KEY(ID_DOCENTE)
    REFERENCES DIM_LY_DOCENTE(ID_DOCENTE),
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES DIM_LY_UNIDADE(ID_UNIDADE));
GO

CREATE INDEX FK_Mod_Mult_108 ON FAT_DOCENTE_CH (ID_DOCENTE);
GO
CREATE INDEX FK_Mod_Mult_109 ON FAT_DOCENTE_CH (ID_UNIDADE);
GO

CREATE TABLE FAT_DY_CHAMADA (
  ID_DY_CHAMADAS INT  NOT NULL   IDENTITY ,
  ID_DY_CANDIDATO INT  NOT NULL  ,
  DATA_CHAMADA DATETIME    ,
  NOME_CHAMADA VARCHAR(100)    ,
  FASE_CHAMADA VARCHAR(30)      ,
PRIMARY KEY(ID_DY_CHAMADAS, ID_DY_CANDIDATO),
  FOREIGN KEY(ID_DY_CANDIDATO)
    REFERENCES DIM_DY_CANDIDATO(ID_DY_CANDIDATO),
  FOREIGN KEY(DATA_CHAMADA)
    REFERENCES DIM_TEMPO(ID_TEMPO));
GO

CREATE INDEX FK_Mod_Mult_119 ON FAT_DY_CHAMADA (ID_DY_CANDIDATO);
GO
CREATE INDEX FK_Mod_Mult_131 ON FAT_DY_CHAMADA (DATA_CHAMADA);
GO

CREATE TABLE FAT_INSCRICAO (
  ID_INSCRICAO INT  NOT NULL   IDENTITY ,
  ID_DY_CONCURSO INT  NOT NULL  ,
  ID_DY_OFERTAS INT  NOT NULL  ,
  ID_DY_CANDIDATO INT  NOT NULL  ,
  DATA_INSCRICAO DATETIME    ,
  NUMERO_INSCRICAO VARCHAR(30)    ,
  ORIGEM_INSCRICAO VARCHAR(100)    ,
  CURRICULO VARCHAR(20)    ,
  CURSO VARCHAR(20)    ,
  CURSO_NOME VARCHAR(100)    ,
  CATEGORIA VARCHAR(100)    ,
  CONTEUDO_CAMPANHA VARCHAR(100)    ,
  MIDIA_CAMPANHA VARCHAR(200)    ,
  NOME_CAMPANHA VARCHAR(200)    ,
  SIT_MATRICULA VARCHAR(50)      ,
PRIMARY KEY(ID_INSCRICAO, ID_DY_CONCURSO, ID_DY_OFERTAS, ID_DY_CANDIDATO),
  FOREIGN KEY(ID_DY_CONCURSO)
    REFERENCES DIM_DY_CONCURSO(ID_DY_CONCURSO),
  FOREIGN KEY(ID_DY_CANDIDATO)
    REFERENCES DIM_DY_CANDIDATO(ID_DY_CANDIDATO),
  FOREIGN KEY(DATA_INSCRICAO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(ID_DY_OFERTAS)
    REFERENCES DIM_DY_OFERTAS(ID_DY_OFERTAS));
GO

CREATE INDEX FK_Mod_Mult_99 ON FAT_INSCRICAO (ID_DY_CONCURSO);
GO
CREATE INDEX FK_Mod_Mult_102 ON FAT_INSCRICAO (ID_DY_CANDIDATO);
GO
CREATE INDEX FK_Mod_Mult_106 ON FAT_INSCRICAO (DATA_INSCRICAO);
GO
CREATE INDEX FK_Mod_Mult_112 ON FAT_INSCRICAO (ID_DY_OFERTAS);
GO

CREATE TABLE FAT_LY_HISTORICO_ALUNO (
  ID_HISTORICO_ALUNO INT  NOT NULL   IDENTITY ,
  ID_ALUNO INT  NOT NULL  ,
  ID_UNIDADE INT  NOT NULL  ,
  DISCIPLINA VARCHAR(20)  NOT NULL  ,
  CURSO VARCHAR(20)  NOT NULL  ,
  ID_TURMA INTEGER  NOT NULL  ,
  DATA_PERIODO DATETIME    ,
  DT_ENCERRAMENTO DATETIME    ,
  DT_ANTECIP DATETIME    ,
  TURNO VARCHAR(20)    ,
  SERIE INT    ,
  ULTIMA_MATRICULA VARCHAR(6)    ,
  CURRICULO VARCHAR(30)    ,
  NOME_EXIBICAO_GRADE INTEGER    ,
  FORMULA_PREREQ_GRADE INTEGER    ,
  FORMULA_EQUIV_GRADE INTEGER    ,
  SERIE_PREREQ_GRADE VARCHAR(3)    ,
  SERIE_IDEAL_GRADE VARCHAR(3)    ,
  TIP_INGRESSO VARCHAR(50)    ,
  TIP_ALUNO VARCHAR(50)    ,
  TIP_ANTECIP VARCHAR(20)    ,
  TIP_ESPECIAL_GRADE INTEGER    ,
  TIP_TRANSF VARCHAR(50)    ,
  TIP_OBRIGATORIA_GRADE INTEGER    ,
  SIT_MATRICULA VARCHAR(50)    ,
  SIT_PERFIL_EVASAO VARCHAR(30)    ,
  SIT_PAGAMENTO INT    ,
  SIT_ANTECIP_FINAN VARCHAR(1)    ,
  SIT_SOLICITOU_PLANO VARCHAR(1)    ,
  SIT_SOLICITOU_HIST VARCHAR(1)    ,
  SIT_BOLSISTA VARCHAR(1)    ,
  SIT_TESE_DISSERTACAO_GRADE INTEGER    ,
  SIT_RETEM_SERIE INTEGER    ,
  VAL_INDICE_REPROVACAO DECIMAL(10,2)    ,
  VAL_ATENCIP DECIMAL(10,2)    ,
  VAL_MEDIA_PERC_BOLSA DECIMAL(10,2)    ,
  VAL_SEMESTRE FLOAT    ,
  QTD_MAX_REPROV INTEGER    ,
  QTD_MAX_MATR_APROV INTEGER    ,
  QTD_AULAS_SEMANAIS_GRADE FLOAT    ,
  QTD_INADIMP INT    ,
  QTD_AULAS_SEM_AULA_GRADE FLOAT    ,
  QTD_AULAS_SEM_LAB_GRAVE FLOAT    ,
  QTD_AULAS_SEM_ATIV_GRADE FLOAT      ,
PRIMARY KEY(ID_HISTORICO_ALUNO, ID_ALUNO, ID_UNIDADE, DISCIPLINA, CURSO, ID_TURMA),
  FOREIGN KEY(ID_ALUNO)
    REFERENCES DIM_LY_ALUNO(ID_ALUNO),
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES DIM_LY_UNIDADE(ID_UNIDADE),
  FOREIGN KEY(DATA_PERIODO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DT_ENCERRAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DT_ANTECIP)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DISCIPLINA)
    REFERENCES DIM_LY_DISCIPLINA(DISCIPLINA),
  FOREIGN KEY(CURSO)
    REFERENCES DIM_LY_CURSO(CURSO),
  FOREIGN KEY(ID_TURMA, DISCIPLINA)
    REFERENCES DIM_TURMA(ID_TURMA, DISCIPLINA));
GO

CREATE INDEX FK_Mod_Mult_84 ON FAT_LY_HISTORICO_ALUNO (ID_ALUNO);
GO
CREATE INDEX FK_Mod_Mult_110 ON FAT_LY_HISTORICO_ALUNO (ID_UNIDADE);
GO
CREATE INDEX FK_Mod_Mult_134 ON FAT_LY_HISTORICO_ALUNO (DATA_PERIODO);
GO
CREATE INDEX FK_Mod_Mult_135 ON FAT_LY_HISTORICO_ALUNO (DT_ENCERRAMENTO);
GO
CREATE INDEX FK_Mod_Mult_136 ON FAT_LY_HISTORICO_ALUNO (DT_ANTECIP);
GO
CREATE INDEX FK_Mod_Mult_85 ON FAT_LY_HISTORICO_ALUNO (DISCIPLINA);
GO
CREATE INDEX FK_Mod_Mult_54 ON FAT_LY_HISTORICO_ALUNO (CURSO);
GO
CREATE INDEX FK_Mod_Mult_57 ON FAT_LY_HISTORICO_ALUNO (ID_TURMA, DISCIPLINA);
GO

CREATE TABLE FAT_LY_REMATRICULA (
  ID_REMATRICULA INT  NOT NULL  ,
  ID_ALUNO INT  NOT NULL  ,
  ID_TEMPO DATETIME  NOT NULL  ,
  ID_UNIDADE INT  NOT NULL  ,
  CURSO VARCHAR(20)  NOT NULL  ,
  ID_DY_OFERTAS INT  NOT NULL  ,
  ID_DY_CONCURSO INT  NOT NULL  ,
  ID_INSCRICAO INT  NOT NULL  ,
  DATA_PERIODO DATETIME  NOT NULL  ,
  DT_ENCERRAMENTO DATETIME  NOT NULL  ,
  DT_ANTECIP DATETIME  NOT NULL  ,
  DATA_PAGAMENTO DATETIME    ,
  CANDIDATO INT    ,
  ANO DATETIME    ,
  ANO_INGRESSO DATETIME    ,
  SEMESTRE INTEGER    ,
  SEM_INGRESSO DATETIME    ,
  ULTIMA_MATRICULA VARCHAR(6)  NOT NULL  ,
  CURRICULO VARCHAR(30)    ,
  SERIE INT    ,
  QTD_INADIMP INTEGER  NOT NULL  ,
  TIP_INGRESSO VARCHAR(50)  NOT NULL  ,
  SIT_MATRICULA VARCHAR(50)  NOT NULL  ,
  SIT_PAGAMENTO VARCHAR(5)  NOT NULL  ,
  SIT_ANTECIP_FINAN VARCHAR(1)  NOT NULL  ,
  SIT_PERFIL_EVASAO VARCHAR(30)  NOT NULL  ,
  SIT_SOLICITOU_PLANO VARCHAR(1)  NOT NULL  ,
  SIT_SOLICITOU_HISTORICO VARCHAR(1)  NOT NULL  ,
  TIP_FINANCEIRO VARCHAR(50)  NOT NULL  ,
  TIP_ANTECIP VARCHAR(20)  NOT NULL  ,
  TIP_TRANSF VARCHAR(50)  NOT NULL  ,
  TIP_BOLSISTA VARCHAR(1)  NOT NULL  ,
  VAL_PERC_FALTAS DECIMAL(10, 2)  NOT NULL  ,
  VAL_ATENCIP DECIMAL(10, 2)  NOT NULL  ,
  VAL_INDICE_REPROVACAO DECIMAL(10, 2)  NOT NULL  ,
  VAL_MEDIA_PERC_BOLSA DECIMAL(10, 2)  NOT NULL  ,
  VAL_SEMESTRE FLOAT      ,
PRIMARY KEY(ID_REMATRICULA, ID_ALUNO, ID_TEMPO, ID_UNIDADE, CURSO),
  FOREIGN KEY(ID_ALUNO)
    REFERENCES DIM_LY_ALUNO(ID_ALUNO),
  FOREIGN KEY(ID_TEMPO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES DIM_LY_UNIDADE(ID_UNIDADE),
  FOREIGN KEY(DATA_PERIODO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DT_ENCERRAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DT_ANTECIP)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_PAGAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(ID_INSCRICAO, ID_DY_CONCURSO, ID_DY_OFERTAS, CANDIDATO)
    REFERENCES FAT_INSCRICAO(ID_INSCRICAO, ID_DY_CONCURSO, ID_DY_OFERTAS, ID_DY_CANDIDATO),
  FOREIGN KEY(CURSO)
    REFERENCES DIM_LY_CURSO(CURSO));
GO

CREATE INDEX FK_Mod_Mult_24 ON FAT_LY_REMATRICULA (ID_ALUNO);
GO
CREATE INDEX FK_Mod_Mult_54 ON FAT_LY_REMATRICULA (ID_TEMPO);
GO
CREATE INDEX FK_Mod_Mult_47 ON FAT_LY_REMATRICULA (ID_UNIDADE);
GO
CREATE INDEX FK_Mod_Mult_106 ON FAT_LY_REMATRICULA (DATA_PERIODO);
GO
CREATE INDEX FK_Mod_Mult_107 ON FAT_LY_REMATRICULA (DT_ENCERRAMENTO);
GO
CREATE INDEX FK_Mod_Mult_108 ON FAT_LY_REMATRICULA (DT_ANTECIP);
GO
CREATE INDEX FK_Mod_Mult_80 ON FAT_LY_REMATRICULA (DATA_PAGAMENTO);
GO
CREATE INDEX FK_Mod_Mult_81 ON FAT_LY_REMATRICULA (ID_INSCRICAO, ID_DY_CONCURSO, ID_DY_OFERTAS, CANDIDATO);
GO
CREATE INDEX FK_Mod_Mult_51 ON FAT_LY_REMATRICULA (CURSO);
GO

CREATE TABLE FAT_LY_MATRICULA (
  ID_MATRICULA INT  NOT NULL  ,
  ID_ALUNO INT  NOT NULL  ,
  ID_UNIDADE INT  NOT NULL  ,
  CONCURSO VARCHAR(20)  NOT NULL  ,
  CURSO VARCHAR(20)  NOT NULL  ,
  ID_DY_OFERTAS INT  NOT NULL  ,
  ID_DY_CONCURSO INT  NOT NULL  ,
  ID_INSCRICAO INT  NOT NULL  ,
  DATA_PAGAMENTO DATETIME  NOT NULL  ,
  DATA_MATRICULA DATETIME  NOT NULL  ,
  DATA_CANCELAMENTO DATETIME  NOT NULL  ,
  DATA_INGRESSO DATETIME  NOT NULL  ,
  DT_INSERCAO DATETIME    ,
  DT_ENCERRAMENTO DATETIME    ,
  CANDIDATO INT    ,
  ANO VARCHAR(4)    ,
  SEMESTRE VARCHAR(2)    ,
  TURNO VARCHAR(20)  NOT NULL  ,
  SERIE INT    ,
  ORIGEM_MATRICULA VARCHAR(50)  NOT NULL  ,
  MOTIVO_ENCERRAMENTO VARCHAR(30)    ,
  CAUSA_ENCERRAMENTO VARCHAR(20)    ,
  TIP_INGRESSO VARCHAR(50)  NOT NULL  ,
  SIT_PAGAMENTO NUMERIC(10)  NOT NULL  ,
  SIT_BOLSISTA VARCHAR(1)  NOT NULL  ,
  SIT_MATRICULA VARCHAR(50)  NOT NULL  ,
  SIT_ALUNO VARCHAR(30)    ,
  SIT_TURMA_PREFERENCIAL VARCHAR(20)      ,
PRIMARY KEY(ID_MATRICULA, ID_ALUNO, ID_UNIDADE, CONCURSO, CURSO),
  FOREIGN KEY(ID_ALUNO)
    REFERENCES DIM_LY_ALUNO(ID_ALUNO),
  FOREIGN KEY(DATA_PAGAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_MATRICULA)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_INGRESSO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_CANCELAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES DIM_LY_UNIDADE(ID_UNIDADE),
  FOREIGN KEY(DT_INSERCAO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DT_ENCERRAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(ID_INSCRICAO, ID_DY_CONCURSO, ID_DY_OFERTAS, CANDIDATO)
    REFERENCES FAT_INSCRICAO(ID_INSCRICAO, ID_DY_CONCURSO, ID_DY_OFERTAS, ID_DY_CANDIDATO),
  FOREIGN KEY(CONCURSO)
    REFERENCES DIM_LY_CONCURSO(CONCURSO),
  FOREIGN KEY(CURSO)
    REFERENCES DIM_LY_CURSO(CURSO));
GO

CREATE INDEX FK_Mod_Mult_27 ON FAT_LY_MATRICULA (ID_ALUNO);
GO
CREATE INDEX FK_Mod_Mult_53 ON FAT_LY_MATRICULA (DATA_PAGAMENTO);
GO
CREATE INDEX FK_Mod_Mult_56 ON FAT_LY_MATRICULA (DATA_MATRICULA);
GO
CREATE INDEX FK_Mod_Mult_57 ON FAT_LY_MATRICULA (DATA_INGRESSO);
GO
CREATE INDEX FK_Mod_Mult_58 ON FAT_LY_MATRICULA (DATA_CANCELAMENTO);
GO
CREATE INDEX FK_Mod_Mult_48 ON FAT_LY_MATRICULA (ID_UNIDADE);
GO
CREATE INDEX FK_Mod_Mult_105 ON FAT_LY_MATRICULA (DT_INSERCAO);
GO
CREATE INDEX FK_Mod_Mult_109 ON FAT_LY_MATRICULA (DT_ENCERRAMENTO);
GO
CREATE INDEX FK_Mod_Mult_82 ON FAT_LY_MATRICULA (ID_INSCRICAO, ID_DY_CONCURSO, ID_DY_OFERTAS, CANDIDATO);
GO
CREATE INDEX FK_Mod_Mult_86 ON FAT_LY_MATRICULA (CONCURSO);
GO
CREATE INDEX FK_Mod_Mult_52 ON FAT_LY_MATRICULA (CURSO);
GO

CREATE TABLE FAT_LY_FINANCEIRO (
  ID_FINANCEIRO INT  NOT NULL  ,
  ID_ALUNO INT  NOT NULL  ,
  ID_TEMPO DATETIME  NOT NULL  ,
  ID_UNIDADE INT  NOT NULL  ,
  CURSO VARCHAR(20)  NOT NULL  ,
  DATA_REF DATETIME  NOT NULL  ,
  DATA_ESTORNO DATETIME  NOT NULL  ,
  DATA_FATURAMENTO DATETIME  NOT NULL  ,
  DATA_VENCIMENTO DATETIME  NOT NULL  ,
  DATA_PAGAMENTO DATETIME  NOT NULL  ,
  DATA_RECEBIMENTO DATETIME  NOT NULL  ,
  RESPONSAVEL VARCHAR(20)  NOT NULL  ,
  PERIODO VARCHAR(7)  NOT NULL  ,
  AGING VARCHAR(30)  NOT NULL  ,
  TIP_COBRANCA VARCHAR(50)  NOT NULL  ,
  TIP_PAGAMENTO VARCHAR(30)  NOT NULL  ,
  TIP_CREDITO VARCHAR(20)  NOT NULL  ,
  TIP_BOLSA VARCHAR(100)  NOT NULL  ,
  TIP_FINAN VARCHAR(30)  NOT NULL  ,
  VAL_COBRANCA NUMERIC(18)  NOT NULL  ,
  VAL_BRUTO DECIMAL(10, 2)  NOT NULL  ,
  VAL_LIQUIDO DECIMAL(10, 2)  NOT NULL  ,
  VAL_BOLSA DECIMAL(10, 2)  NOT NULL  ,
  VAL_MULTA DECIMAL(10, 2)  NOT NULL  ,
  VAL_PERDEBOLSA DECIMAL(10, 2)  NOT NULL  ,
  VAL_JUROS DECIMAL(10, 2)  NOT NULL  ,
  VAL_DESCONTOS DECIMAL(10, 2)  NOT NULL  ,
  VAL_ESTORNO DECIMAL(10, 2)  NOT NULL  ,
  VAL_PAGO DECIMAL(10, 2)  NOT NULL  ,
  VAL_SALDO DECIMAL(10, 2)  NOT NULL  ,
  VAL_MENSALIDADE DECIMAL(10,2)    ,
  SIT_COBRANCA_ESTORNADA VARCHAR(1)  NOT NULL  ,
  SIT_PAGO VARCHAR(1)  NOT NULL  ,
  SIT_VENCIDA VARCHAR(1)  NOT NULL    ,
PRIMARY KEY(ID_FINANCEIRO, ID_ALUNO, ID_TEMPO, ID_UNIDADE, CURSO),
  FOREIGN KEY(ID_ALUNO)
    REFERENCES DIM_LY_ALUNO(ID_ALUNO),
  FOREIGN KEY(ID_TEMPO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_REF)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(ID_TEMPO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_ESTORNO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_FATURAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_VENCIMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_PAGAMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(DATA_RECEBIMENTO)
    REFERENCES DIM_TEMPO(ID_TEMPO),
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES DIM_LY_UNIDADE(ID_UNIDADE),
  FOREIGN KEY(CURSO)
    REFERENCES DIM_LY_CURSO(CURSO));
GO

CREATE INDEX FK_Mod_Mult_25 ON FAT_LY_FINANCEIRO (ID_ALUNO);
GO
CREATE INDEX FK_Mod_Mult_62 ON FAT_LY_FINANCEIRO (ID_TEMPO);
GO
CREATE INDEX FK_Mod_Mult_43 ON FAT_LY_FINANCEIRO (DATA_REF);
GO
CREATE INDEX FK_Mod_Mult_49 ON FAT_LY_FINANCEIRO (ID_TEMPO);
GO
CREATE INDEX FK_Mod_Mult_100 ON FAT_LY_FINANCEIRO (DATA_ESTORNO);
GO
CREATE INDEX FK_Mod_Mult_101 ON FAT_LY_FINANCEIRO (DATA_FATURAMENTO);
GO
CREATE INDEX FK_Mod_Mult_102 ON FAT_LY_FINANCEIRO (DATA_VENCIMENTO);
GO
CREATE INDEX FK_Mod_Mult_103 ON FAT_LY_FINANCEIRO (DATA_PAGAMENTO);
GO
CREATE INDEX FK_Mod_Mult_104 ON FAT_LY_FINANCEIRO (DATA_RECEBIMENTO);
GO
CREATE INDEX FK_Mod_Mult_79 ON FAT_LY_FINANCEIRO (ID_UNIDADE);
GO
CREATE INDEX FK_Mod_Mult_53 ON FAT_LY_FINANCEIRO (CURSO);
GO



