USE LYCEUM
GO

DECLARE @p_ano VARCHAR(4) = '2020'
DECLARE @p_semestre VARCHAR(2) = '2'

IF OBJECT_ID('TEMPDB.DBO.##TBL_ACEITOMETRO') IS NOT NULL
BEGIN
	DROP TABLE ##TBL_ACEITOMETRO
END


CREATE TABLE ##TBL_ACEITOMETRO (
	UNIDADE_ENSINO VARCHAR(30),
	NOME_UNIDADE_ENSINO VARCHAR(MAX),
	UNIDADE_FISICA VARCHAR(30),
	NOME_UNIDADE_FISICA VARCHAR(MAX),
	TIPO_CURSO VARCHAR(50),
	CURSO VARCHAR(30),
	NOME_CURSO VARCHAR(MAX),
	TURNO VARCHAR(1),
	CURRICULO VARCHAR(30),
	SERIE INT,
	ALUNO VARCHAR(20),
	NOME_ALUNO VARCHAR(MAX),
	CH_DISCIPLINA_NORMAL VARCHAR(50),
	CH_DISCIPLINA_ESCOLHIDA VARCHAR(50),
	DISCIPLINA_ESCOLHIDA VARCHAR(50),
	ACEITOU_CONTRATO VARCHAR(1),
	VALOR_SEMESTRALIDADE_NORMAL DECIMAL(10,2),
	VALOR_SEMESTRALIDADE_ESCOLHIDO DECIMAL(10,2),
	BOLSAS VARCHAR(MAX),
	PERC_BOLSA DECIMAL(10,2),
	VALOR_PAGO DECIMAL(10,2),
	MATRICULA_COMPLETA VARCHAR(1)

)

INSERT INTO ##TBL_ACEITOMETRO
SELECT	DISTINCT 
		UE.UNIDADE_ENS, 
		UE.NOME_COMP, 
		UF.UNIDADE_FIS, 
		UF.NOME_COMP, 
		C.TIPO, 
		C.CURSO, 
		C.NOME, 
		A.TURNO, 
		A.CURRICULO, 
		A.SERIE,
		A.ALUNO, 
		A.NOME_COMPL,
		0.00,
		VW1.CREDITOS,
		VW1.TIPO_DESCRICAO,
		ISNULL(CA.CONTRATO_ACEITO,'N'),
		0.00,
		VW1.CUSTO_ESTIMADO,
		'' AS BOLSAS,
		0.00 AS PERC_BOLSA,
		ISNULL((SELECT SUM(IC.VALOR)*-1
				FROM LY_ITEM_CRED IC
				JOIN LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
				JOIN (SELECT DISTINCT IL.ALUNO,IL.LANC_DEB, IL.COBRANCA 
						FROM LY_ITEM_LANC IL 
						) X ON X.COBRANCA = IC.COBRANCA
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = X.LANC_DEB
				WHERE LD.CODIGO_LANC IN ('MS','SM') AND X.ALUNO = A.ALUNO
				AND IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
				AND LD.ANO_REF = @p_ano AND LD.PERIODO_REF = @p_semestre
				)
				,0.00),
		'N'
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
JOIN LYCEUMINTEGRACAO..FTC_DISCIPLINA_MATRICULA_FINANCEIRA VW1 ON VW1.CURSO = A.CURSO AND VW1.TURNO = A.TURNO AND VW1.CURRICULO = A.CURRICULO AND VW1.SERIE = A.SERIE
JOIN LY_PRE_MATRICULA PM ON PM.DISCIPLINA = VW1.DISCIPLINA_LYCEUM AND PM.ALUNO = A.ALUNO
LEFT JOIN LY_CONTRATO_ALUNO CA ON CA.ALUNO = PM.ALUNO AND CA.ANO = PM.ANO AND CA.PERIODO = PM.SEMESTRE
WHERE 1=1
AND PM.ANO = @p_ano AND PM.SEMESTRE = @p_semestre
ORDER BY A.ALUNO


UPDATE T SET T.CH_DISCIPLINA_NORMAL = VW.CREDITOS, T.VALOR_SEMESTRALIDADE_NORMAL = VW.CUSTO_ESTIMADO 
FROM ##TBL_ACEITOMETRO T
JOIN LYCEUMINTEGRACAO..FTC_DISCIPLINA_MATRICULA_FINANCEIRA VW ON VW.CURSO = T.CURSO AND VW.TURNO = T.TURNO AND VW.CURRICULO = T.CURRICULO AND VW.SERIE = T.SERIE
WHERE VW.TIPO_DESCRICAO = 'CARGA HORÁRIA NORMAL'

--UPDATE LISTA DE BOLSAS
	UPDATE T
		SET T.BOLSAS = STUFF((SELECT DISTINCT ',' + B.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..LY_BOLSA B
                        WHERE 1=1
						AND (B.ANOFIM >= @p_ano OR B.ANOFIM IS NULL) AND (B.MESFIM >= CASE @p_semestre WHEN 1 THEN 6 ELSE 12 END OR B.MESFIM IS NULL OR (B.MESINI = B.MESFIM AND B.ANOINI = B.ANOFIM))
						AND B.DATA_CANCEL IS NULL
                        AND B.ALUNO = T.ALUNO
                        FOR XML PATH('') 
                        ), 1, 1, '' )
	FROM ##TBL_ACEITOMETRO T

	IF OBJECT_ID('TEMPDB.DBO.##TEMP_BOLSA') IS NOT NULL
	BEGIN
		DROP TABLE ##TEMP_BOLSA
	END

	CREATE TABLE ##TEMP_BOLSA
	(
		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		TIPO_BOLSA VARCHAR(50),
		PERC_VALOR VARCHAR(20),
		VALOR DECIMAL(10,2),
		ALUNO VARCHAR(20),
		QTD_PARCELAS INT,
		NUM_BOLSA INT,
		ANOINI INT,
		ANOFIM INT,
		MESINI INT,
		MESFIM INT

	)

	INSERT INTO ##TEMP_BOLSA
	SELECT	@p_ano AS ANO,
			@p_semestre AS SEMESTRE,
			B.TIPO_BOLSA,
			B.PERC_VALOR,
			CONVERT(DECIMAL(10,2),B.VALOR) AS VALOR,
			B.ALUNO,
			(ISNULL(B.MESFIM,CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END) - B.MESINI)+1 AS QTD_PARCELAS,
			NUM_BOLSA,
			B.ANOINI,
			B.ANOFIM,
			B.MESINI,
			B.MESFIM
	FROM LY_BOLSA B
	JOIN ##TBL_ACEITOMETRO D ON D.ALUNO = B.ALUNO
	WHERE 1=1
	AND B.DATA_CANCEL IS NULL
	--AND B.ANOINI <= @p_ano
	--AND B.MESINI <= CASE WHEN @p_semestre = '1' THEN 1 ELSE 7 END
	AND B.ANOFIM >= ISNULL(@p_ano,B.ANOFIM) 
	AND B.MESFIM BETWEEN CASE WHEN @p_semestre = '1' THEN 1 ELSE 7 END AND CASE WHEN @p_semestre = '1' THEN 6 ELSE 12 END


		DELETE FROM ##TEMP_BOLSA WHERE VALOR = 0.00

		IF OBJECT_ID('TEMPDB.DBO.##TEMP_DMP') IS NOT NULL
			BEGIN
				DROP TABLE ##TEMP_DMP
			END


		CREATE TABLE ##TEMP_DMP (
			ALUNO VARCHAR(20),
			VALOR_SEMESTRALIDADE_BRUTO DECIMAL(10,2),
			VALOR_SEMESTRALIDADE_LIQUIDO DECIMAL(10,2),
			PERC_BOLSA DECIMAL(10,2)
		)

		INSERT INTO ##TEMP_DMP
		SELECT DISTINCT ALUNO, VALOR_SEMESTRALIDADE_ESCOLHIDO, 0.00, 0.00
		FROM ##TBL_ACEITOMETRO

		DECLARE @p_aluno VARCHAR(20)
		DECLARE cursor1 CURSOR FOR
		SELECT DISTINCT ALUNO
		FROM ##TEMP_DMP
		ORDER BY ALUNO
					
		OPEN cursor1

		FETCH NEXT FROM cursor1 INTO @p_aluno

		WHILE @@FETCH_STATUS = 0
		BEGIN

			UPDATE B SET B.VALOR_SEMESTRALIDADE_LIQUIDO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_SEMESTRALIDADE_BRUTO - (BO.VALOR*BO.QTD_PARCELAS) ELSE B.VALOR_SEMESTRALIDADE_BRUTO*(1-(BO.VALOR*BO.QTD_PARCELAS/6)) END
			FROM ##TEMP_DMP B
			JOIN ##TEMP_BOLSA BO ON BO.ALUNO = B.ALUNO
			WHERE  B.ALUNO = @p_aluno
			
			
		FETCH NEXT FROM cursor1 INTO @p_aluno
		
		END
		CLOSE cursor1
		DEALLOCATE cursor1

		UPDATE B SET B.PERC_BOLSA = 1-(B.VALOR_SEMESTRALIDADE_LIQUIDO/VALOR_SEMESTRALIDADE_BRUTO)
		FROM ##TEMP_DMP B
		WHERE B.VALOR_SEMESTRALIDADE_BRUTO > 0


		UPDATE T SET T.PERC_BOLSA = B.PERC_BOLSA
		FROM ##TBL_ACEITOMETRO  T
		JOIN ##TEMP_DMP B ON B.ALUNO = T.ALUNO

		UPDATE T SET T.PERC_BOLSA = 0.00
		FROM ##TBL_ACEITOMETRO T
		WHERE T.BOLSAS IS NULL AND PERC_BOLSA = 1.00


		UPDATE T SET MATRICULA_COMPLETA = 'S'
		FROM ##TBL_ACEITOMETRO T
		WHERE T.ACEITOU_CONTRATO = 'S' AND VALOR_PAGO > 0.00

		SELECT * FROM ##TBL_ACEITOMETRO