USE LYCEUM
GO

DECLARE @p_ano VARCHAR(4) = '2021'
DECLARE @p_semestre VARCHAR(2) = '1'

IF OBJECT_ID('TEMPDB.DBO.##TBL_ACEITOMETRO') IS NOT NULL
BEGIN
	DELETE FROM ##TBL_ACEITOMETRO WHERE ANO = @p_ano and SEMESTRE = @p_semestre
END

ELSE 

BEGIN 

	CREATE TABLE ##TBL_ACEITOMETRO ( --DROP TABLE ##TBL_ACEITOMETRO
		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		UNIDADE_ENSINO VARCHAR(30),
		NOME_UNIDADE_ENSINO VARCHAR(MAX),
		SIGLA_UNIDADE_FISICA VARCHAR(30),
		TIPO_CURSO VARCHAR(50),
		CURSO VARCHAR(30),
		NOME_CURSO VARCHAR(MAX),
		TURNO VARCHAR(1),
		SERIE INT,
		CURRICULO VARCHAR(30),
		SIT_ALUNO VARCHAR(30),
		ALUNO VARCHAR(20),
		NOME_ALUNO VARCHAR(MAX),
		VALOR_SEMESTRALIDADE_ESCOLHIDO DECIMAL(10,2),
		BOLSAS VARCHAR(MAX),
		PERC_BOLSA DECIMAL(10,2),
		BENEFICIARIO VARCHAR(1),
		BENEFICIARIO_PENDENTE VARCHAR(1),
		PERIODO_INGRESSO VARCHAR(6), 
		DIAS_S_0_DO_INICIO INT,
		DIAS_S_1_DO_INICIO INT,
		DIAS_S_2_DO_INICIO INT,
		DIAS_S_3_DO_INICIO INT,
		DIAS_S_4_DO_INICIO INT,
		DIAS_REMATR_S_0_DO_FIM INT,
		DIAS_REMATR_S_1_DO_FIM INT,
		DIAS_REMATR_S_2_DO_FIM INT,
		DIAS_REMATR_S_3_DO_FIM INT,
		DIAS_REMATR_S_4_DO_FIM INT,
		DIAS_REMATR_S_0_DAS_AULAS INT,
		DIAS_REMATR_S_1_DAS_AULAS INT,
		DIAS_REMATR_S_2_DAS_AULAS INT,
		DIAS_REMATR_S_3_DAS_AULAS INT,
		DIAS_REMATR_S_4_DAS_AULAS INT,
		DIAS_REMATR_S_0_DO_LIMITE INT,
		DIAS_REMATR_S_1_DO_LIMITE INT,
		DIAS_REMATR_S_2_DO_LIMITE INT,
		DIAS_REMATR_S_3_DO_LIMITE INT,
		DIAS_REMATR_S_4_DO_LIMITE INT,
		STATUS_REMATR_S_0 VARCHAR(30),
		STATUS_REMATR_S_1 VARCHAR(30),
		STATUS_REMATR_S_2 VARCHAR(30),
		STATUS_REMATR_S_3 VARCHAR(30),
		STATUS_REMATR_S_4 VARCHAR(30),
		PERC_PROUNI DECIMAL(10,2),
		PERC_FIES DECIMAL(10,2),
		PENDENCIA_FINANCEIRA VARCHAR(1),
		VALOR_PENDENCIA DECIMAL(10,2),
		COMECOU_REMATRICULA VARCHAR(1),
		EFETIVOU_PAGAMENTO VARCHAR(1),
		VALOR_PAGO DECIMAL(10,2),
		TIPO_PAGAMENTO VARCHAR(30),
		TIPO_CRED VARCHAR(30),
		SELECIONOU_DISCIPLINAS VARCHAR(1),
		ACEITOU_CONTRATO VARCHAR(1),
		EFETIVOU_MATRICULA VARCHAR(1)

	)

END

INSERT INTO ##TBL_ACEITOMETRO
SELECT	DISTINCT
		@p_ano AS ANO,
		@p_semestre AS SEMESTRE,
		UE.UNIDADE_ENS AS UNIDADE_ENSINO, 
		UE.NOME_COMP AS NOME_UNIDADE_ENSINO, 
		UF.UNIDADE_FIS AS SIGLA_UNIDADE_FISICA,  
		C.TIPO AS TIPO_CURSO, 
		C.CURSO AS CURSO, 
		C.NOME AS NOME_CURSO, 
		A.TURNO AS TURNO,  
		A.SERIE AS SERIE,
		A.CURRICULO,
		A.SIT_ALUNO,
		A.ALUNO AS ALUNO, 
		A.NOME_COMPL AS NOME_ALUNO,
		0.00 AS VALOR_SEMESTRALIDADE_ESCOLHIDO,
		'' AS BOLSAS,
		0.00 AS PERC_BOLSA,
		'N' AS BENEFICIARIO,
		'N' AS BENEFICIARIO_PENDENTE,
		CONCAT(A.ANO_INGRESSO, A.SEM_INGRESSO) AS PERIODO_INGRESSO, 
		0 AS DIAS_S_0_DO_INICIO,
		0 AS DIAS_S_1_DO_INICIO,
		0 AS DIAS_S_2_DO_INICIO,
		0 AS DIAS_S_3_DO_INICIO,
		0 AS DIAS_S_4_DO_INICIO,
		0 AS DIAS_REMATR_S_0_DO_FIM,
		0 AS DIAS_REMATR_S_1_DO_FIM,
		0 AS DIAS_REMATR_S_2_DO_FIM,
		0 AS DIAS_REMATR_S_3_DO_FIM,
		0 AS DIAS_REMATR_S_4_DO_FIM,
		0 AS DIAS_REMATR_S_0_DAS_AULAS,
		0 AS DIAS_REMATR_S_1_DAS_AULAS,
		0 AS DIAS_REMATR_S_2_DAS_AULAS,
		0 AS DIAS_REMATR_S_3_DAS_AULAS,
		0 AS DIAS_REMATR_S_4_DAS_AULAS,
		0 AS DIAS_REMATR_S_0_DO_LIMITE,
		0 AS DIAS_REMATR_S_1_DO_LIMITE,
		0 AS DIAS_REMATR_S_2_DO_LIMITE,
		0 AS DIAS_REMATR_S_3_DO_LIMITE,
		0 AS DIAS_REMATR_S_4_DO_LIMITE,
		'' AS STATUS_REMATR_S_0,
		'' AS STATUS_REMATR_S_1,
		'' AS STATUS_REMATR_S_2,
		'' AS STATUS_REMATR_S_3,
		'' AS STATUS_REMATR_S_4,
		0.00 AS PERC_PROUNI,
		0.00 AS PERC_FIES,
		'N' AS PENDENCIA_FINANCEIRA,
		ISNULL((SELECT SUM(VW.VALOR)
				FROM VW_COBRANCA VW
				JOIN (SELECT DISTINCT IL.ALUNO,IL.LANC_DEB, IL.COBRANCA 
						FROM LY_ITEM_LANC IL 
						) X ON X.COBRANCA = VW.COBRANCA								/*VALOR PENDENCIA FINANCEIRA EM PERIODOS ANTERIORES AO ATUAL*/
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = X.LANC_DEB
				JOIN LY_PLANO_PGTO_PERIODO PPP ON PPP.ALUNO = VW.ALUNO AND PPP.RESP = VW.RESP AND PPP.ANO = LD.ANO_REF AND PPP.PERIODO = LD.PERIODO_REF AND PPP.RESP NOT IN ('00360305000104','03738654000105','00378257000181','FIES')	
				WHERE VW.VALOR > 0.00 AND LD.CODIGO_LANC IN ('MS','SM','Acordo','CD')
				AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno')
				AND VW.ALUNO = A.ALUNO
				AND VW.DATA_DE_VENCIMENTO < GETDATE()
				AND CONCAT(LD.ANO_REF,LD.PERIODO_REF) < CONCAT(@p_ano,@p_semestre)),0.00) AS VALOR_PENDENCIA,
		ISNULL((SELECT TOP 1 'S' FROM LYCEUMINTEGRACAO..REMATRICULA R WHERE R.ALUNO = A.ALUNO AND R.ANO = @p_ano AND R.SEMESTRE = @p_semestre),'N') AS COMECOU_REMATRICULA,
		'N' AS EFETIVOU_PAGAMENTO,
		ISNULL((SELECT SUM(IC.VALOR)*-1
		FROM LY_ITEM_CRED IC
		JOIN LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
		JOIN (SELECT DISTINCT IL.ALUNO,IL.LANC_DEB, IL.COBRANCA			/*VALOR MENSALIDADE PAGO NO SEMESTRE ATUAL*/
				FROM LY_ITEM_LANC IL 
				) X ON X.COBRANCA = IC.COBRANCA
		JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = X.LANC_DEB
		JOIN LY_PLANO_PGTO_PERIODO PPP ON PPP.ALUNO = C.ALUNO AND PPP.RESP = C.RESP AND PPP.ANO = LD.ANO_REF AND PPP.PERIODO = LD.PERIODO_REF AND PPP.RESP NOT IN ('00360305000104','03738654000105','00378257000181','FIES')	
		WHERE LD.CODIGO_LANC IN ('MS','SM') AND X.ALUNO = A.ALUNO
		AND IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
		AND LD.ANO_REF = @p_ano AND LD.PERIODO_REF = @p_semestre
		AND C.ESTORNO = 'N' AND C.DT_ESTORNO IS NULL
		),0.00) AS VALOR_PAGO,
		'' AS TIPO_PAGAMENTO,
		'' AS TIPO_CRED,
		'N' AS SELECIONOU_DISCIPLINAS,
		ISNULL(CA.CONTRATO_ACEITO,'N') AS ACEITOU_CONTRATO,
		'N' AS EFETIVOU_MATRICULA
FROM LY_ALUNO A
JOIN LY_CURSO C ON C.CURSO = A.CURSO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = A.UNIDADE_FISICA
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
--JOIN LYCEUMINTEGRACAO..FTC_DISCIPLINA_MATRICULA_FINANCEIRA VW1 ON VW1.CURSO = A.CURSO AND VW1.TURNO = A.TURNO AND VW1.CURRICULO = A.CURRICULO AND VW1.SERIE = A.SERIE AND VW1.TIPO = 'NR'
LEFT JOIN LY_CONTRATO_ALUNO CA ON CA.ALUNO = A.ALUNO AND CA.ANO = @p_ano AND CA.PERIODO = @p_semestre
WHERE 1=1 AND UE.UNIDADE_ENS <> 10 AND C.CURSO <> '507'
--AND PM.ANO = @p_ano AND PM.SEMESTRE = @p_semestre
AND EXISTS (	
					SELECT TOP 1 1 FROM LY_HISTMATRICULA HM 
					WHERE HM.ALUNO = A.ALUNO 
					AND HM.ANO = CASE WHEN @p_semestre = 1 THEN @p_ano-1 ELSE @p_ano END 
					AND (HM.SEMESTRE = CASE WHEN @p_semestre = 1 THEN 2 ELSE 1 END	OR HM.SEMESTRE = CASE WHEN @p_semestre = 1 THEN 4 ELSE 3 END)
					AND SITUACAO_HIST NOT IN ('Dispensado','Cancelado')	 AND HM.LANC_DEB IS NOT NULL					/* ESTUDOU NO SEMESTRE PASSADO */
					UNION 
					SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA VW 
					WHERE VW.ALUNO = A.ALUNO  AND VW.LANC_DEB IS NOT NULL
					AND VW.ANO = CASE WHEN @p_semestre = 1 THEN @p_ano-1 ELSE @p_ano END  
					AND (VW.SEMESTRE = CASE WHEN @p_semestre = 1 THEN 2 ELSE 1 END	OR VW.SEMESTRE = CASE WHEN @p_semestre = 1 THEN 4 ELSE 3 END)
					AND vw.SIT_MATRICULA NOT IN ('Dispensado','Cancelado')
					UNION
					SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA VW1
					WHERE VW1.ALUNO = A.ALUNO
					AND VW1.ANO = @p_ano
					AND VW1.SEMESTRE = @p_semestre
					AND VW1.SIT_MATRICULA NOT IN ('Dispensado','Cancelado')
			) 
AND NOT EXISTS	(	
					SELECT TOP 1 1 FROM LY_H_CURSOS_CONCL H
					WHERE H.ALUNO = A.ALUNO					/*NAO POSSUI ENCERRAMENTO DE QUALQUER ESPECIE*/
					AND H.DT_REABERTURA IS NULL
				)

ORDER BY A.ALUNO



--UPDATE DIAS ADMISSÃO
IF CONCAT(@p_ano,@p_semestre) = '20211'
BEGIN
UPDATE T SET T.DIAS_REMATR_S_0_DAS_AULAS = DATEDIFF(DAY,PL.DT_INICIO_AULA,X.DT_MATRICULA), T.STATUS_REMATR_S_0 = CASE WHEN T.PERIODO_INGRESSO = CONCAT(X.ANO,X.SEMESTRE) THEN 'ADMISSÃO' 
																										WHEN T.PERIODO_INGRESSO < CONCAT(X.ANO,X.SEMESTRE) THEN 'READMISSÃO'
																										ELSE 'NÃO RETORNADO' END
FROM ##TBL_ACEITOMETRO T
JOIN LY_PERIODO_LETIVO PL ON PL.ANO = T.ANO AND PL.PERIODO = T.SEMESTRE
JOIN (	SELECT MIN(VW.DT_INSERCAO) DT_MATRICULA, VW.ALUNO, VW.ANO, VW.SEMESTRE 
		FROM VW_MATRICULA_E_PRE_MATRICULA VW 
		WHERE VW.SIT_MATRICULA NOT IN ('Cancelado','Dispensado') 
		GROUP BY VW.ALUNO,VW.ANO, VW.SEMESTRE 
		) X ON X.ALUNO = T.ALUNO 
				AND X.ANO = T.ANO 
				AND X.SEMESTRE = T.SEMESTRE
END
ELSE 
BEGIN
	UPDATE T SET T.DIAS_REMATR_S_0_DAS_AULAS = DATEDIFF(DAY,PL.DT_INICIO_AULA,X.DT_MATRICULA), T.STATUS_REMATR_S_0 = CASE WHEN T.PERIODO_INGRESSO = CONCAT(X.ANO,X.SEMESTRE) THEN 'ADMISSÃO' 
																										WHEN T.PERIODO_INGRESSO < CONCAT(X.ANO,X.SEMESTRE) THEN 'READMISSÃO'
																										ELSE 'NÃO RETORNADO' END
	FROM ##TBL_ACEITOMETRO T
	JOIN LY_PERIODO_LETIVO PL ON PL.ANO = T.ANO AND PL.PERIODO = T.SEMESTRE
	JOIN (	SELECT MIN(VW.DT_MATRICULA) DT_MATRICULA, VW.ALUNO, VW.ANO, VW.SEMESTRE 
			FROM LY_HISTMATRICULA VW 
			WHERE VW.SITUACAO_HIST NOT IN ('Cancelado','Dispensado') 
			GROUP BY VW.ALUNO,VW.ANO, VW.SEMESTRE 
			) X ON X.ALUNO = T.ALUNO 
					AND X.ANO = T.ANO 
					AND X.SEMESTRE = T.SEMESTRE
END 
UPDATE T SET T.DIAS_REMATR_S_1_DAS_AULAS = DATEDIFF(DAY,PL.DT_INICIO_AULA,X.DT_MATRICULA), T.STATUS_REMATR_S_1 = CASE WHEN T.PERIODO_INGRESSO = CONCAT(X.ANO,X.SEMESTRE) THEN 'ADMISSÃO' 
																										WHEN T.PERIODO_INGRESSO < CONCAT(X.ANO,X.SEMESTRE) THEN 'READMISSÃO'
																										ELSE 'INEXISTENTE' END
FROM ##TBL_ACEITOMETRO T
JOIN LY_PERIODO_LETIVO PL ON	PL.ANO = CASE WHEN T.SEMESTRE = 1 THEN T.ANO-1 ELSE T.ANO END 
								AND PL.PERIODO = CASE WHEN T.SEMESTRE = 1 THEN 2 ELSE 1 END
JOIN (	SELECT MIN(VW.DT_MATRICULA) DT_MATRICULA, VW.ALUNO, VW.ANO, VW.SEMESTRE 
		FROM LY_HISTMATRICULA VW 
		WHERE VW.SITUACAO_HIST NOT IN ('Cancelado','Dispensado')  AND VW.LANC_DEB IS NOT NULL
		GROUP BY VW.ALUNO,VW.ANO, VW.SEMESTRE
		) X ON X.ALUNO = T.ALUNO 
				AND X.ANO = CASE WHEN T.SEMESTRE = 1 THEN T.ANO-1 ELSE T.ANO END 
				AND X.SEMESTRE = CASE WHEN T.SEMESTRE = 1 THEN 2 ELSE 1 END

UPDATE T SET T.DIAS_REMATR_S_2_DAS_AULAS = DATEDIFF(DAY,PL.DT_INICIO_AULA,X.DT_MATRICULA), T.STATUS_REMATR_S_2 = CASE WHEN T.PERIODO_INGRESSO = CONCAT(X.ANO,X.SEMESTRE) THEN 'ADMISSÃO' 
																										WHEN T.PERIODO_INGRESSO < CONCAT(X.ANO,X.SEMESTRE) THEN 'READMISSÃO'
																										ELSE 'INEXISTENTE' END
FROM ##TBL_ACEITOMETRO T
JOIN LY_PERIODO_LETIVO PL ON	PL.ANO = T.ANO-1 
								AND PL.PERIODO = T.SEMESTRE
JOIN (	SELECT MIN(VW.DT_MATRICULA) DT_MATRICULA, VW.ALUNO, VW.ANO, VW.SEMESTRE 
		FROM LY_HISTMATRICULA VW 
		WHERE VW.SITUACAO_HIST NOT IN ('Cancelado','Dispensado')  AND VW.LANC_DEB IS NOT NULL
		GROUP BY VW.ALUNO,VW.ANO, VW.SEMESTRE 
		) X ON X.ALUNO = T.ALUNO 
				AND X.ANO = T.ANO-1 
				AND X.SEMESTRE = T.SEMESTRE

UPDATE T SET T.DIAS_REMATR_S_3_DAS_AULAS = DATEDIFF(DAY,PL.DT_INICIO_AULA,X.DT_MATRICULA), T.STATUS_REMATR_S_3 = CASE WHEN T.PERIODO_INGRESSO = CONCAT(X.ANO,X.SEMESTRE) THEN 'ADMISSÃO' 
																										WHEN T.PERIODO_INGRESSO < CONCAT(X.ANO,X.SEMESTRE) THEN 'READMISSÃO'
																										ELSE 'INEXISTENTE' END
FROM ##TBL_ACEITOMETRO T
JOIN LY_PERIODO_LETIVO PL ON	PL.ANO = CASE WHEN T.SEMESTRE = 1 THEN T.ANO-2 ELSE T.ANO-1 END
								AND PL.PERIODO = CASE WHEN T.SEMESTRE = 1 THEN 2 ELSE 1 END
JOIN (	SELECT MIN(VW.DT_MATRICULA) DT_MATRICULA, VW.ALUNO, VW.ANO, VW.SEMESTRE 
		FROM LY_HISTMATRICULA VW 
		WHERE VW.SITUACAO_HIST NOT IN ('Cancelado','Dispensado')  AND VW.LANC_DEB IS NOT NULL
		GROUP BY VW.ALUNO,VW.ANO, VW.SEMESTRE 
		) X ON X.ALUNO = T.ALUNO 
				AND X.ANO = CASE WHEN T.SEMESTRE = 1 THEN T.ANO-2 ELSE T.ANO-1 END 
				AND X.SEMESTRE = CASE WHEN T.SEMESTRE = 1 THEN 2 ELSE 1 END

UPDATE T SET T.DIAS_REMATR_S_4_DAS_AULAS = DATEDIFF(DAY,PL.DT_INICIO_AULA,X.DT_MATRICULA), T.STATUS_REMATR_S_4 = CASE WHEN T.PERIODO_INGRESSO = CONCAT(X.ANO,X.SEMESTRE) THEN 'ADMISSÃO' 
																										WHEN T.PERIODO_INGRESSO < CONCAT(X.ANO,X.SEMESTRE) THEN 'READMISSÃO'
																										ELSE 'INEXISTENTE' END
FROM ##TBL_ACEITOMETRO T
JOIN LY_PERIODO_LETIVO PL ON	PL.ANO = T.ANO-1 
								AND PL.PERIODO = T.SEMESTRE
JOIN (	SELECT MIN(VW.DT_MATRICULA) DT_MATRICULA, VW.ALUNO, VW.ANO, VW.SEMESTRE 
		FROM LY_HISTMATRICULA VW 
		WHERE VW.SITUACAO_HIST NOT IN ('Cancelado','Dispensado')  AND VW.LANC_DEB IS NOT NULL
		GROUP BY VW.ALUNO,VW.ANO, VW.SEMESTRE 
		) X ON X.ALUNO = T.ALUNO 
				AND X.ANO = T.ANO-2 
				AND X.SEMESTRE = T.SEMESTRE

--UPDATE NÃO RETORNADO

DECLARE @p_periodos4 VARCHAR(6),
@p_periodos3 VARCHAR(6),
@p_periodos2 VARCHAR(6),
@p_periodos1 VARCHAR(6)

SET @p_periodos4 = CONCAT(@p_ano-2,@p_semestre)
SET @p_periodos3 = CASE WHEN @p_semestre = 1 THEN CONCAT(@p_ano-2,2) ELSE CONCAT(@p_ano-1,1) END
SET @p_periodos2 = CONCAT(@p_ano-1,@p_semestre)
SET @p_periodos1 = CASE WHEN @p_semestre = 1 THEN CONCAT(@p_ano-1,2) ELSE CONCAT(@p_ano,1) END


UPDATE T SET T.STATUS_REMATR_S_1 = 'NÃO RETORNADO'
FROM ##TBL_ACEITOMETRO T
WHERE T.STATUS_REMATR_S_1 = 'INEXISTENTE'
AND T.PERIODO_INGRESSO < @p_periodos1

UPDATE T SET T.STATUS_REMATR_S_2 = 'NÃO RETORNADO'
FROM ##TBL_ACEITOMETRO T
WHERE T.STATUS_REMATR_S_2 = 'INEXISTENTE'
AND T.PERIODO_INGRESSO < @p_periodos2

UPDATE T SET T.STATUS_REMATR_S_3 = 'NÃO RETORNADO'
FROM ##TBL_ACEITOMETRO T
WHERE T.STATUS_REMATR_S_3= 'INEXISTENTE'
AND T.PERIODO_INGRESSO < @p_periodos3

UPDATE T SET T.STATUS_REMATR_S_4 = 'NÃO RETORNADO'
FROM ##TBL_ACEITOMETRO T
WHERE T.STATUS_REMATR_S_4 = 'INEXISTENTE'
AND T.PERIODO_INGRESSO < @p_periodos4


--UPDATE BOLSA GOVERNAMENTAL
UPDATE T SET T.BENEFICIARIO = 'S'
FROM ##TBL_ACEITOMETRO T
WHERE EXISTS (
--BOLSA FIES TEMP
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP','FIES')
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)

UNION
--ALUNO CONTRATO FIES
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = T.ALUNO

UNION
-- BOLSA PROUNI 
	SELECT TOP 1 'S'
				FROM LYCEUM..LY_BOLSA B
				JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
				WHERE B.ALUNO = T.ALUNO
				AND B.TIPO_BOLSA = 'PROIES100'
				AND TB.GRUPO_BOLSA = 'PROIES' 
				AND B.DATA_CANCEL IS NULL 
				AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
				AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)	

UNION
-- RESPONSAVEL PROUNI
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = T.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre
UNION
-- RESPONSAVEL FIES 100%
	SELECT TOP 1 'S' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = T.ALUNO
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre
	)


--UPDATE REALIZOU PAGAMENTO
UPDATE T SET T.EFETIVOU_PAGAMENTO = 'S'
FROM ##TBL_ACEITOMETRO T
WHERE T.VALOR_PAGO > 0.00
 
UPDATE T SET T.EFETIVOU_PAGAMENTO = 'S'
FROM ##TBL_ACEITOMETRO T
WHERE 1=1
--AND ACEITOU_CONTRATO = 'S'
AND BENEFICIARIO = 'S'
AND  EXISTS (
			SELECT TOP 1 1 
			FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
			WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
			AND PPP.ALUNO = T.ALUNO
			AND PPP.PERCENT_DIVIDA_ALUNO = 1.0000
			AND PPP.ANO = T.ANO
			AND PPP.PERIODO = T.SEMESTRE

			UNION

			SELECT TOP 1 1 
			FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
			WHERE PPP.RESP = 'FIES' --RESP FIES
			AND PPP.ALUNO = T.ALUNO
			AND PPP.PERCENT_DIVIDA_ALUNO = 1.0000
			AND PPP.ANO = T.ANO
			AND PPP.PERIODO = T.SEMESTRE
			)

--UPDATE PERC_PROUNI PERC_FIES
UPDATE T SET T.PERC_FIES = ISNULL(PPP.PERCENT_DIVIDA_ALUNO,0.00)
FROM ##TBL_ACEITOMETRO T
JOIN LY_PLANO_PGTO_PERIODO PPP ON PPP.ALUNO = T.ALUNO AND PPP.RESP = 'FIES' AND PPP.ANO = T.ANO AND PPP.PERIODO = T.SEMESTRE

--UPDATE PERC_PROUNI PERC_PROUNI
UPDATE T SET T.PERC_PROUNI = ISNULL(PPP.PERCENT_DIVIDA_ALUNO,0.00)
FROM ##TBL_ACEITOMETRO T
JOIN LY_PLANO_PGTO_PERIODO PPP ON PPP.ALUNO = T.ALUNO AND PPP.RESP = '03738654000105' AND PPP.ANO = T.ANO AND PPP.PERIODO = T.SEMESTRE


--UPDATE BENEFICIARIO_PENDENTE
UPDATE T SET T.BENEFICIARIO_PENDENTE = 'S'
FROM ##TBL_ACEITOMETRO T
WHERE T.BENEFICIARIO = 'S'
AND T.EFETIVOU_PAGAMENTO = 'N'

--UPDATE TIPO_CRED
UPDATE T SET T.TIPO_CRED = (	SELECT TOP 1 LC.TIPO_CRED 
									FROM LY_LANC_CREDITO  LC
									JOIN LY_ITEM_CRED IC ON IC.LANC_CRED = LC.LANC_CRED
									JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
									JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
									WHERE LD.ANO_REF = T.ANO AND LD.PERIODO_REF = T.SEMESTRE AND LD.ALUNO = T.ALUNO
									AND LD.CODIGO_LANC IN ('MS','SM','Acordo')
									AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno') -- DIVIDA NAO ESTORNADA
								)
FROM ##TBL_ACEITOMETRO T


UPDATE T SET T.TIPO_PAGAMENTO = (	SELECT TOP 1 LC.TIPO_PAGAMENTO 
									FROM LY_LANC_CREDITO  LC
									JOIN LY_ITEM_CRED IC ON IC.LANC_CRED = LC.LANC_CRED
									JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
									JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
									WHERE LD.ANO_REF = T.ANO AND LD.PERIODO_REF = T.SEMESTRE AND LD.ALUNO = T.ALUNO
									AND LD.CODIGO_LANC IN ('MS','SM','Acordo')
									AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_DESCONTO_DEBITO LDD WHERE LDD.LANC_DEB = LD.LANC_DEB AND LDD.MOTIVO_DESCONTO = 'Estorno') -- DIVIDA NAO ESTORNADA
									
								)
FROM ##TBL_ACEITOMETRO T



--UPDATE ESCOLHEU DISCIPLINAS

IF CONCAT(@p_ano,@p_semestre) = '20211'
BEGIN
	UPDATE T SET T.SELECIONOU_DISCIPLINAS = 'S'
	FROM ##TBL_ACEITOMETRO T
	WHERE 1=1
	AND EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE T.ALUNO = ALUNO AND T.ANO = @p_ano AND T.SEMESTRE = @p_semestre AND SIT_MATRICULA NOT IN ('Cancelado','Dispensado') )
END
ELSE
BEGIN
	UPDATE T SET T.SELECIONOU_DISCIPLINAS = 'S'
	FROM ##TBL_ACEITOMETRO T
	WHERE 1=1
	AND EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_HISTMATRICULA WHERE T.ALUNO = ALUNO AND T.ANO = @p_ano AND T.SEMESTRE = @p_semestre AND SITUACAO_HIST NOT IN ('Cancelado','Dispensado'))
	
END

--UPDATE PENDENCIA FINANCEIRA

UPDATE T SET T.VALOR_PENDENCIA = 0.00
FROM ##TBL_ACEITOMETRO T
WHERE T.VALOR_PENDENCIA < 48.01

UPDATE T SET T.PENDENCIA_FINANCEIRA = 'S'
FROM ##TBL_ACEITOMETRO T
WHERE T.VALOR_PENDENCIA > 0.00

--VALOR SEMESTRALIDADE ESCOLHIDO
UPDATE T SET T.VALOR_SEMESTRALIDADE_ESCOLHIDO = VW.CUSTO_ESTIMADO 
FROM ##TBL_ACEITOMETRO T
JOIN LYCEUMINTEGRACAO..FTC_DISCIPLINA_MATRICULA_FINANCEIRA VW ON VW.CURSO = T.CURSO AND VW.TURNO = T.TURNO AND VW.CURRICULO = T.CURRICULO AND VW.SERIE = T.SERIE AND VW.ANO = T.ANO AND VW.PERIODO = T.SEMESTRE
WHERE VW.TIPO = 'NR'
AND VW.ANO = @p_ano AND VW.PERIODO = @p_semestre

--UPDATE LISTA DE BOLSAS
	UPDATE T
		SET T.BOLSAS = STUFF((SELECT DISTINCT ' + ' + B.TIPO_BOLSA AS [text()]
                        FROM LYCEUM..LY_BOLSA B
                        WHERE 1=1
						AND B.ANOFIM >= ISNULL(T.ANO,B.ANOFIM) 
						AND B.MESFIM BETWEEN CASE WHEN T.SEMESTRE = '1' THEN 1 ELSE 7 END AND CASE WHEN T.SEMESTRE = '1' THEN 6 ELSE 12 END
						AND B.DATA_CANCEL IS NULL
                        AND B.ALUNO = T.ALUNO
                        FOR XML PATH('') 
                        ), 1, 2, '' )
	FROM ##TBL_ACEITOMETRO T

	UPDATE T SET T.BOLSAS = ''
	FROM ##TBL_ACEITOMETRO T
	WHERE T.BOLSAS IS NULL

	IF OBJECT_ID('TEMPDB.DBO.##TEMP_BOLSA') IS NOT NULL
	BEGIN
		DROP TABLE ##TEMP_BOLSA
	END

	CREATE TABLE ##TEMP_BOLSA
	(
		ANO VARCHAR(4),
		SEMESTRE VARCHAR(2),
		TIPO_BOLSA VARCHAR(50),
		PERC_VALOR VARCHAR(20),
		VALOR DECIMAL(10,2),
		ALUNO VARCHAR(20),
		QTD_PARCELAS INT,
		NUM_BOLSA INT,
		ANOINI INT,
		ANOFIM INT,
		MESINI INT,
		MESFIM INT

	)

	INSERT INTO ##TEMP_BOLSA
	SELECT	D.ANO AS ANO,
			D.SEMESTRE AS SEMESTRE,
			B.TIPO_BOLSA,
			B.PERC_VALOR,
			CONVERT(DECIMAL(10,2),B.VALOR) AS VALOR,
			B.ALUNO,
			(ISNULL(B.MESFIM,CASE WHEN D.SEMESTRE = '1' THEN 6 ELSE 12 END) - B.MESINI)+1 AS QTD_PARCELAS,
			NUM_BOLSA,
			B.ANOINI,
			B.ANOFIM,
			B.MESINI,
			B.MESFIM
	FROM LY_BOLSA B
	JOIN ##TBL_ACEITOMETRO D ON D.ALUNO = B.ALUNO AND D.SELECIONOU_DISCIPLINAS = 'S'
	WHERE 1=1
	AND B.DATA_CANCEL IS NULL
	--AND B.ANOINI <= @p_ano
	--AND B.MESINI <= CASE WHEN @p_semestre = '1' THEN 1 ELSE 7 END
	AND B.ANOFIM >= ISNULL(D.ANO,B.ANOFIM) 
	AND B.MESFIM BETWEEN CASE WHEN D.SEMESTRE = '1' THEN 1 ELSE 7 END AND CASE WHEN D.SEMESTRE = '1' THEN 6 ELSE 12 END

		UPDATE T SET T.QTD_PARCELAS = 6
		FROM ##TEMP_BOLSA T
		WHERE T.QTD_PARCELAS > 6

		DELETE FROM ##TEMP_BOLSA WHERE VALOR = 0.00

		IF OBJECT_ID('TEMPDB.DBO.##TEMP_DMP') IS NOT NULL
			BEGIN
				DROP TABLE ##TEMP_DMP
			END


		CREATE TABLE ##TEMP_DMP (
			ALUNO VARCHAR(20),
			VALOR_SEMESTRALIDADE_BRUTO DECIMAL(10,2),
			VALOR_SEMESTRALIDADE_LIQUIDO DECIMAL(10,2),
			PERC_BOLSA DECIMAL(10,2)
		)

		INSERT INTO ##TEMP_DMP
		SELECT DISTINCT ALUNO, VALOR_SEMESTRALIDADE_ESCOLHIDO, 0.00, 0.00
		FROM ##TBL_ACEITOMETRO
		WHERE SELECIONOU_DISCIPLINAS = 'S'

		DECLARE @p_aluno VARCHAR(20)
		DECLARE cursor1 CURSOR FOR
		SELECT DISTINCT ALUNO
		FROM ##TEMP_DMP
		ORDER BY ALUNO
					
		OPEN cursor1

		FETCH NEXT FROM cursor1 INTO @p_aluno

		WHILE @@FETCH_STATUS = 0
		BEGIN

			UPDATE B SET B.VALOR_SEMESTRALIDADE_LIQUIDO = CASE WHEN BO.PERC_VALOR = 'Valor' THEN B.VALOR_SEMESTRALIDADE_BRUTO - (BO.VALOR*BO.QTD_PARCELAS) ELSE B.VALOR_SEMESTRALIDADE_BRUTO*(1-(BO.VALOR*BO.QTD_PARCELAS/6)) END
			FROM ##TEMP_DMP B
			JOIN ##TEMP_BOLSA BO ON BO.ALUNO = B.ALUNO
			WHERE  B.ALUNO = @p_aluno
			
			
		FETCH NEXT FROM cursor1 INTO @p_aluno
		
		END
		CLOSE cursor1
		DEALLOCATE cursor1

		UPDATE B SET B.PERC_BOLSA = 1-(B.VALOR_SEMESTRALIDADE_LIQUIDO/VALOR_SEMESTRALIDADE_BRUTO)
		FROM ##TEMP_DMP B
		WHERE B.VALOR_SEMESTRALIDADE_BRUTO > 0.00


		UPDATE T SET T.PERC_BOLSA = B.PERC_BOLSA
		FROM ##TBL_ACEITOMETRO  T
		JOIN ##TEMP_DMP B ON B.ALUNO = T.ALUNO

		UPDATE T SET T.PERC_BOLSA = 0.00
		FROM ##TBL_ACEITOMETRO T
		WHERE 1=1
		AND (T.BOLSAS IS NULL OR T.BOLSAS = '') AND PERC_BOLSA = 1.00

		UPDATE T SET T.EFETIVOU_PAGAMENTO = 'S'
		FROM ##TBL_ACEITOMETRO  T
		WHERE 1=1
		AND SELECIONOU_DISCIPLINAS = 'S'
		AND ACEITOU_CONTRATO = 'S'
		AND PERC_BOLSA = 1.00

		--UPDATE T SET T.COMECOU_REMATRICULA = 'S'
		--FROM ##TBL_ACEITOMETRO T
		--WHERE 1=1
		--AND EXISTS (
		--			SELECT TOP 1 1 FROM LY_MATRICULA WHERE ALUNO = T.ALUNO AND ANO = T.ANO AND SEMESTRE = T.SEMESTRE
		--			)

		UPDATE T SET EFETIVOU_MATRICULA = 'S'
		FROM ##TBL_ACEITOMETRO T
		WHERE T.ACEITOU_CONTRATO = 'S' AND EFETIVOU_PAGAMENTO =  'S' AND SELECIONOU_DISCIPLINAS = 'S' AND T.COMECOU_REMATRICULA = 'S'

		SELECT * FROM ##TBL_ACEITOMETRO
		--WHERE ALUNO IN ('171040173','182040405','191040590','192040178','181051083') 
		