USE LYCEUM
GO

SELECT DISTINCT A.ALUNO, A.NOME_COMPL, dbo.Decrypt(P.SENHA_TAC)AS SENHA_ALUNO,'2018' ANO, '2' SEMESTRE, D.DISCIPLINA, T.TURMA,'CurricularObrigatoria' TIPO ,G.SERIE_IDEAL FROM LY_ALUNO A
JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
JOIN LY_GRADE G ON G.CURSO = A.CURSO AND G.TURNO = A.TURNO AND G.CURRICULO = A.CURRICULO AND G.SERIE_IDEAL = A.SERIE+1
JOIN LY_CURSO C ON C.CURSO = A.CURSO AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
JOIN LY_DISCIPLINA D ON D.DISCIPLINA = G.DISCIPLINA
JOIN LY_TURMA T ON T.DISCIPLINA = G.DISCIPLINA AND T.ANO = 2018 AND T.SEMESTRE = 2 AND T.CURSO = A.CURSO
WHERE 1=1
AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2018 AND SEMESTRE = 1)
AND NOT EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = A.ALUNO AND ANO = 2018 AND SEMESTRE = 2)
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = A.ALUNO AND (DISCIPLINA = G.DISCIPLINA OR DISCIPLINA LIKE '%'+G.FORMULA_EQUIV+'%') AND SITUACAO_HIST IN ('Aprovado','Dispensado'))
ORDER BY A.ALUNO