USE LYCEUM
GO

SELECT DISTINCT T.ANO, T.SEMESTRE, T.TURMA, T.DISCIPLINA  FROM LY_TURMA T
WHERE 1=1
AND (NOT EXISTS (SELECT TOP 1 1 FROM LY_AULA_DOCENTE AD WHERE AD.TURMA = T.TURMA AND AD.DISCIPLINA = T.DISCIPLINA AND AD.ANO = T.ANO AND AD.SEMESTRE = T.SEMESTRE)
OR NOT EXISTS(SELECT TOP 1 1 FROM LY_HOR_AULA HA WHERE HA.TURMA = T.TURMA AND HA.DISCIPLINA = T.DISCIPLINA AND HA.ANO = T.ANO AND HA.SEMESTRE = T.SEMESTRE))
AND T.ANO = 2018 AND SEMESTRE = 1
AND T.FACULDADE = 'FTC-VIC' AND T.CURSO = '731'