USE [master]
GO
CREATE LOGIN [uniftc_bolsa] WITH PASSWORD=N'!08w!H$@2PJD01e@fs', DEFAULT_DATABASE=[UNIFTC_ONE], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

USE [LYCEUM]
GO
CREATE USER [uniftc_bolsa] FOR LOGIN [uniftc_bolsa]
GO
use [LYCEUMINTEGRACAO];
GO
CREATE USER [uniftc_bolsa] FOR LOGIN [uniftc_bolsa]
GO

use [UNIFTC_ONE];
GO
CREATE USER [uniftc_bolsa] FOR LOGIN [uniftc_bolsa]
GO

GRANT SELECT ON SISTEMA TO [uniftc_bolsa]
GRANT ALL ON BOLSA  TO [uniftc_bolsa]
GRANT ALL ON BOLSA_DESCONTO TO [uniftc_bolsa]
GRANT ALL ON BOLSA_PROCESSO_SELETIVO  TO [uniftc_bolsa]

USE [LYCEUMINTEGRACAO]
GO

GRANT EXECUTE ON FTC_DATAATUAL TO [uniftc_bolsa]
GRANT SELECT ON FTC_ONE_DADOS_ACADEMICOS_ALUNO TO UNIFTC_BOLSA;

USE LYCEUM;
GO

GRANT SELECT ON LY_MATRICULA TO [uniftc_bolsa];
GRANT SELECT ON LY_ALUNO TO [uniftc_bolsa];
GRANT SELECT ON LY_PESSOA TO [uniftc_bolsa];
GRANT SELECT ON LY_RELACIONAMENTO_PESSOA TO [uniftc_bolsa];
GRANT SELECT ON LY_CURSO TO [uniftc_bolsa];
GRANT SELECT ON LY_UNIDADE_FISICA TO [uniftc_bolsa];
GRANT SELECT ON LY_UNIDADE_ENSINO TO [uniftc_bolsa];

