USE [master]
GO
CREATE LOGIN [uniftc_gera_rps] WITH PASSWORD=N'!)bnd1h42@Ds_', DEFAULT_DATABASE=[LYCEUMINTEGRACAO], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

USE [LYCEUM]
GO
CREATE USER [uniftc_gera_rps] FOR LOGIN [uniftc_gera_rps]
GO
use [LYCEUMINTEGRACAO];
GO
CREATE USER [uniftc_gera_rps] FOR LOGIN [uniftc_gera_rps]
GO

USE [LYCEUMINTEGRACAO]
GO

GRANT EXECUTE ON [LYCEUMINTEGRACAO].[DBO].[FTC_GERA_DADOS_RPS] TO [uniftc_gera_rps]
GRANT EXECUTE ON [LYCEUMINTEGRACAO].[DBO].[FTC_RELATORIO_RPS] TO [uniftc_gera_rps]
GRANT EXECUTE ON [LYCEUMINTEGRACAO].[DBO].[FTC_ENVIA_DADOS_RPS] TO [uniftc_gera_rps]
GRANT EXECUTE ON [LYCEUMINTEGRACAO].[DBO].[FTC_EXCLUSAO_SEGURA_RPS] TO [uniftc_gera_rps]
GRANT EXECUTE ON [LYCEUMINTEGRACAO].[DBO].[FTC_AGRUPA_DADOS_RPS] TO [uniftc_gera_rps]
GRANT EXECUTE ON LYCEUMINTEGRACAO.DBO.FTC_GET_DADOS_AGRUPADOS_RPS TO [uniftc_gera_rps]
GRANT EXECUTE ON FN_FTC_EH_EMAIL TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUMINTEGRACAO.DBO.FN_GET_CLIENTE TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUMINTEGRACAO.DBO.FN_GET_FILIAL TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUMINTEGRACAO.DBO.FN_GET_PRODUTO TO [uniftc_gera_rps]

GRANT SELECT ON LYCEUMINTEGRACAO..FTC_INTEGRACAO_LYCEUM_PROTHEUS_COB_DESCONSIDERAR TO [uniftc_gera_rps]
GRANT INSERT ON LYCEUMINTEGRACAO..FTC_INTEGRACAO_LYCEUM_PROTHEUS_COB_DESCONSIDERAR TO [uniftc_gera_rps]
GRANT UPDATE ON LYCEUMINTEGRACAO..FTC_INTEGRACAO_LYCEUM_PROTHEUS_COB_DESCONSIDERAR TO [uniftc_gera_rps]

GRANT ALL ON [LYCEUMINTEGRACAO].[dbo].[FTC_INTEGRACAO_LYCEUM_PROTHEUS] TO [uniftc_gera_rps]
GRANT ALL ON LYCEUMINTEGRACAO..FTC_INTEGRACAO_LYCEUM_PROTHEUS_CARGA TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[dbo].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_EMPRESAS] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[dbo].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_FATURAMENTO_SZF_040] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[DBO].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_FATURAMENTO_SZF_070] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[DBO].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_FATURAMENTO_SZF_220] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[DBO].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_FATURAMENTO_SZF_250] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[dbo].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_AGRUPAMENTO_SZF_040] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[dbo].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_AGRUPAMENTO_SZF_070] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[dbo].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_AGRUPAMENTO_SZF_220] TO [uniftc_gera_rps]
GRANT ALL ON [LYCEUMINTEGRACAO].[dbo].[FTC_INTEGRACAO_LYCEUM_PROTHEUS_AGRUPAMENTO_SZF_250] TO [uniftc_gera_rps]

USE LYCEUM;
GO

GRANT SELECT ON LYCEUM..LY_COBRANCA TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_NAO_GERA_RPS_FTC TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_COBRANCA_NOTA_FISCAL TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..AY_RESUMO_ATO TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..AY_EVENTOS_FATURAMENTO TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_UNIDADE_FISICA TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_INSTITUICAO TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_MANTENEDORA TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_ITEM_LANC TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_BOLSA TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_TIPO_BOLSA TO [uniftc_gera_rps]
GRANT SELECT ON [LYCEUM].[dbo].[LY_ALUNO] TO [uniftc_gera_rps]
GRANT SELECT ON [LYCEUM].[dbo].[LY_PESSOA] TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_CURSO TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_H_CURR_ALUNO TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_H_CURSOS_CONCL TO [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..AY_INT_UNIDADE_FILIAL to [uniftc_gera_rps]
GRANT SELECT ON LYCEUM..LY_RESP_FINAN to [uniftc_gera_rps]


GRANT SELECT ON LYCEUM..LY_COBRANCA_NOTA_FISCAL TO [uniftc_gera_rps]
GRANT INSERT ON LYCEUM..LY_COBRANCA_NOTA_FISCAL TO [uniftc_gera_rps]
GRANT UPDATE ON LYCEUM..LY_COBRANCA_NOTA_FISCAL TO [uniftc_gera_rps]


