USE LYCEUM
GO

UPDATE D SET D.ATIVO = 'S'
FROM LY_DOCENTE D
JOIN LY_DOCENTE_UNIDADE DU ON DU.NUM_FUNC = D.NUM_FUNC
WHERE D.DT_DEMISSAO IS NULL AND D.ATIVO = 'N'
AND D.NUM_FUNC IN ('265','5134','3588')

UPDATE DU SET DU.ATIVO = 'S'
FROM LY_DOCENTE D
JOIN LY_DOCENTE_UNIDADE DU ON DU.NUM_FUNC = D.NUM_FUNC
WHERE D.DT_DEMISSAO IS NULL AND D.ATIVO = 'S'
AND D.NUM_FUNC IN ('265','5134','3588')

