USE LYCEUM
GO

-- ## IDENTIFICANDO OS CASOS ## --
/*select * FROM LY_GRADE WHERE (FORMULA_EQUIV LIKE '%e%' COLLATE Latin1_General_CS_AS AND FORMULA_EQUIV IS NOT NULL) 
OR (FORMULA_PREREQ LIKE '%e%' COLLATE Latin1_General_CS_AS AND FORMULA_PREREQ IS NOT NULL)   */


--CORREÇÃO PARA "e"
UPDATE LY_GRADE 
SET FORMULA_EQUIV = REPLACE(FORMULA_EQUIV, 'e' COLLATE Latin1_General_CS_AS, 'E')
	, FORMULA_PREREQ = REPLACE(FORMULA_PREREQ, 'e' COLLATE Latin1_General_CS_AS, 'E')
WHERE (FORMULA_EQUIV LIKE '%e%' COLLATE Latin1_General_CS_AS AND FORMULA_EQUIV IS NOT NULL) 
	OR (FORMULA_PREREQ LIKE '%e%' COLLATE Latin1_General_CS_AS AND FORMULA_PREREQ IS NOT NULL)   
GO


--CORREÇÃO PARA "ou"
UPDATE LY_GRADE 
SET FORMULA_EQUIV = REPLACE(FORMULA_EQUIV, 'ou' COLLATE Latin1_General_CS_AS, 'OU')
	, FORMULA_PREREQ = REPLACE(FORMULA_PREREQ, 'ou' COLLATE Latin1_General_CS_AS, 'OU')
WHERE (FORMULA_EQUIV LIKE '%ou%' COLLATE Latin1_General_CS_AS AND FORMULA_EQUIV IS NOT NULL) 
	OR (FORMULA_PREREQ LIKE '%ou%' COLLATE Latin1_General_CS_AS AND FORMULA_PREREQ IS NOT NULL)   
GO
