USE LYCEUM
GO

UPDATE P SET NOTA_MAX = 40 FROM LY_PROVA_DISCIP P
WHERE P.NOTA_MAX = 100 AND P.PROVA IN ('V1','V2')
GO

UPDATE P SET NOTA_MAX = 20 FROM LY_PROVA_DISCIP P
WHERE P.NOTA_MAX = 100 AND P.PROVA = 'OT'
GO


UPDATE P SET NOTA_MAX = 40 FROM LY_PROVA P
WHERE P.NOTA_MAX = 100 AND P.PROVA IN ('V1','V2')
AND P.ANO = 2016 AND P.SEMESTRE = 2
GO


UPDATE P SET NOTA_MAX = 20 FROM LY_PROVA P
WHERE P.NOTA_MAX = 100 AND P.PROVA = 'OT'
AND P.ANO = 2016 AND P.SEMESTRE = 2
GO


