SELECT U.USUARIO,U.NOME,U.SETOR,U.HABILITADO,U.WINUSUARIO, UU.FACULDADE
FROM HD_USUARIO U
LEFT JOIN LY_USUARIO_UNIDADE UU ON UU.USUARIO = U.USUARIO
JOIN VW_FACULDADE VW ON VW.FACULDADE = UU.FACULDADE
WHERE WINUSUARIO LIKE 'GLOBAL\tss%'
AND VW.ENSINO = 'N'
ORDER BY 2