--select * from HD_RELATORIO where DESCRICAO like '%fecham%'
--select * from LY_ALUNO where NOME_ABREV like '%dayse%'

--select * from HD_TRANSACAO where trans like '%NotasAluno%'

-- ## Usuários que possuem acesso a determinada transação ## --

SELECT DISTINCT U.USUARIO, U.NOME, ISNULL(U.SETOR,'') AS SETOR, PT.TRANS, PU.PADACES AS PERFIL, UU.FACULDADE AS UNIDADE
FROM HD_USUARIO U
JOIN LY_USUARIO_UNIDADE UU ON UU.USUARIO = U.USUARIO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = UU.FACULDADE
JOIN HD_PADUSUARIO PU ON PU.USUARIO = U.USUARIO
JOIN HD_PADTRANS PT ON PT.PADACES = PU.PADACES
WHERE PT.TRANS IN ('TAOP007D') AND PT.PODEALT = 'S' 
ORDER BY 1

-- ## Lista de Usuarios ## --

SELECT U.NOME, ISNULL(U.SETOR,'') AS SETOR_LYCEUM, UF.NOME_COMP AS UNIDADE FROM HD_USUARIO U
JOIN LY_USUARIO_UNIDADE UU ON UU.USUARIO = U.USUARIO
JOIN LY_UNIDADE_FISICA UF ON UF.UNIDADE_FIS = UU.FACULDADE
JOIN HD_PADUSUARIO PU ON PU.USUARIO = U.USUARIO
WHERE UF.UNIDADE_FIS LIKE 'DOM%'
AND PU.PADACES = 'SEC_GERAL'
AND U.HABILITADO = 'S'