SELECT SUM(valor) FROM  VW_MOVIMENTO_CAIXA WHERE USUARIO_LYC = 'zeus' AND DATA_ABERTURA = '2016-08-03'
SELECT * FROM  FTC_VW_MOVIMENTO_CAIXA WHERE USUARIO_LYC = '06168720545' AND DATA_ABERTURA = '2017-02-07'


--valor dos créditos
SELECT ISNULL(SUM(VALOR),0)
FROM LY_LANC_CREDITO, LY_ITEM_CRED 
WHERE LY_LANC_CREDITO.LANC_CRED = LY_ITEM_CRED.LANC_CRED
  AND TIPO_ENCARGO IS NULL 
  AND TIPODESCONTO IS NULL 
  AND ID_ABERTURA IS NOT NULL 
  AND ID_ABERTURA = 26394
--18354,18348
--lista de creditos  
SELECT *
FROM LY_LANC_CREDITO, LY_ITEM_CRED 
WHERE LY_LANC_CREDITO.LANC_CRED = LY_ITEM_CRED.LANC_CRED
  AND TIPO_ENCARGO IS NULL 
  AND TIPODESCONTO IS NULL 
  AND ID_ABERTURA IS NOT NULL
  AND LY_ITEM_CRED.USUARIO = '43205402553' 
  --AND LY_LANC_CREDITO.[DATA] = '2017-10-05'
  --AND LY_LANC_CREDITO.LANC_CRED = '26394'
  --AND ID_ABERTURA = 26394
ORDER BY LY_ITEM_CRED.DATA DESC
  
  --15886,19
  
   SELECT * FROM VW_MOVIMENTO_CAIXA WHERE USUARIO_LYC = 'mbarreto' AND DATA_ABERTURA = '2017-02-21'
   
   SELECT TOP 50 * FROM VW_COBRANCA WHERE VALOR > 0 AND aluno LIKE '171%'
  
--valor devolução
SELECT ISNULL(SUM(VALOR),0) 
FROM LY_DEVOLUCAO 
WHERE ID_ABERTURA IS NOT NULL 
AND ID_ABERTURA = 33

--valor final = (valor da abertura + valor dos créditos) - valor devolução

SELECT * FROM LY_CONTROLE_CAIXA WHERE ID_ABERTURA = '26394'
SELECT * FROM LY_CONTROLE_CAIXA WHERE USUARIO_LYC = '43205402553'

select * from LY_CUSTOM_CLIENTE WHERE NOME LIKE '%MOVI%'

