--ALUNOS COM CH INTEGRALIZADA MAIOR QUE CH DO CURSO E NAO ESTAO CONCLUIDOS
select 'ALUNO NAO CONCLUIDO COM CARGA HORARIA INTEGRALIZADA MAIOR QUE A TOTAL DO CURSO' ERRO,VW.* from VW_ALUNOS_CENSO VW
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
WHERE CONVERT(NUMERIC,VW.CargaHorariaIntegralizada) >= CONVERT(NUMERIC,VW.CargaHorariaTotalCurso)
AND A.SIT_ALUNO = 'Ativo'
AND NOT EXISTS (SELECT TOP 1 1 FROM LY_H_CURSOS_CONCL WHERE ALUNO = VW.ALUNO AND MOTIVO = 'Conclusao')

UNION

--ALUNO CONCLUÍDO COM CARGA HORARIA TOTAL DO CURSO NAO CUMPRIDA

select 'ALUNO CONCLUÍDO COM CARGA HORARIA TOTAL DO CURSO NAO CUMPRIDA' ERRO,VW.* from VW_ALUNOS_CENSO VW
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
WHERE CONVERT(NUMERIC,VW.CargaHorariaIntegralizada) < CONVERT(NUMERIC,VW.CargaHorariaTotalCurso)
AND A.SIT_ALUNO = 'Concluido'
--order by UnidadeEnsino

UNION

--ALUNO COM MATRICULA TRANCADA SEM LANÇAMENTO DE TRANCAMENTO
select 'ALUNO COM LANÇAMENTO DE CONCLUSAO E ATIVO' ERRO,VW.* from VW_ALUNOS_CENSO VW
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
WHERE EXISTS (SELECT TOP 1 1 FROM LY_H_CURSOS_CONCL WHERE ALUNO = VW.ALUNO AND MOTIVO = 'Conclusao')
AND A.SIT_ALUNO = 'Ativo'
UNION

--ALUNO COM MATRICULA TRANCADA SEM LANÇAMENTO DE TRANCAMENTO
select 'ALUNO COM MATRICULA TRANCADA SEM LANÇAMENTO DE TRANCAMENTO' ERRO,VW.* from VW_ALUNOS_CENSO VW
JOIN LY_ALUNO A ON A.ALUNO = VW.ALUNO
WHERE NOT EXISTS (SELECT TOP 1 1 FROM VW_TRANC_ALUNO WHERE ALUNO = VW.ALUNO)
AND EXISTS (SELECT TOP 1 1 FROM LY_HISTMATRICULA WHERE ALUNO = VW.ALUNO AND SITUACAO_HIST = 'Trancado' AND ANO = '2017')
AND NOT EXISTS (SELECT TOP 1 1 FROM VW_MATRICULA_E_PRE_MATRICULA WHERE ANO = 2018 AND ALUNO = A.ALUNO)
--AND A.SIT_ALUNO = 'Concluido'
--AND VW.ALUNO = '122050136'
order by UnidadeEnsino

--select * FROM VW_TRANC_ALUNO WHERE ALUNO = '122050136'
--select * FROM LY_ALUNO WHERE ALUNO = '131070429'
--SELECT * FROM LY_H_CURSOS_CONCL WHERE ALUNO = '102070469'
--select * from LY_HISTMATRICULA WHERE ALUNO = '102070469'
--select * from VW_ALUNOS_CENSO WHERE PESSOA >= '113986' AND CodigoIes = '1053'
--select * from VW_ALUNOS_CENSO WHERE ALUNO = '102070469'

