DECLARE @P_CPF T_CODIGO

--SELECT PESSOA, * FROM LY_ALUNO WHERE ALUNO = '171050059'
--SELECT cpf,pessoa, * FROM ly_pessoa WHERE NOME_COMPL LIKE '%Rodrigo Rodrigues Souza%'
--SELECT cpf,pessoa, * FROM ly_pessoa WHERE PESSOA = '5839'

SET @P_CPF = '88167127591'

SELECT PESSOA, CPF,* FROM LY_PESSOA WHERE CPF = @P_CPF
SELECT PESSOA,* FROM LY_ALUNO WHERE PESSOA IN (SELECT PESSOA FROM LY_PESSOA WHERE CPF = @P_CPF)
SELECT PESSOA,CPF_TITULAR,* FROM LY_RESP_FINAN WHERE PESSOA IN (SELECT PESSOA FROM LY_PESSOA WHERE CPF = @P_CPF)
SELECT PESSOA,CPF,* FROM LY_DOCENTE WHERE PESSOA IN (SELECT PESSOA FROM LY_PESSOA WHERE CPF = @P_CPF)
SELECT PESSOA,* FROM LY_RELACIONAMENTO_PESSOA WHERE PESSOA_PAPEL IN (SELECT PESSOA FROM LY_PESSOA WHERE CPF = @P_CPF)
