USE LYCEUM
GO

declare @p_ano varchar(4),
		@p_semestre varchar(2),
		@p_aluno varchar(20)

SET @p_ano = '2020'
SET @p_semestre = '2'
SET @p_aluno= '181040711'


--6.0 VERIFICANDO PAGAMENTOS
 SELECT TOP 1 'PAGAMENTO NORMAL' AS TIPO FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = @p_aluno 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo')
UNION

--BOLSA 100% NO SEMESTRE
	SELECT TOP 1 'BOLSA 100% NO SEMESTRE' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = @p_aluno  AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND B.TIPO_BOLSA IN ('IMES','BF PCD','PARES','BAFFFTC','BINCRH')
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL)
					
UNION
--BOLSA 100% ABERTA		
	SELECT TOP 1 'BOLSA 100% ABERTA	' AS TIPO FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = @p_aluno  AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL
UNION
--BOLSA 100% FECHADA NO SEMESTRE		
	SELECT TOP 1 'BOLSA 100% FECHADA NO SEMESTRE' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = @p_aluno  AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM = @p_ano) 
					AND (B.MESFIM = CASE WHEN @p_semestre = 1 THEN 6 ELSE 12 END)
		
UNION
--BOLSA CREDEDUC
	SELECT TOP 1 'BOLSA CREDEDUC' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE (B.TIPO_BOLSA = 'CREDEDUC' OR B.TIPO_BOLSA LIKE '%QUERO%' OR B.TIPO_BOLSA LIKE '%EDUCA%')
					AND B.ALUNO = @p_aluno 
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
UNION
--BOLSA FIES TEMP *SOLICITADO POR ANDRÉ BRITTO / ANA PAULA GOMES em 25/03/2019*
	SELECT TOP 1 'BOLSA FIES TEMP ' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = @p_aluno 
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)


UNION
--ALUNO CONTRATO FIES
	SELECT TOP 1 'ALUNO CONTRATO FIES' AS TIPO FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = @p_aluno 
UNION
--COBRANÇA DE MENSALIDADE SEM SALDO A PAGAR
	SELECT TOP 1 'COBRANÇA DE MENSALIDADE SEM SALDO A PAGAR' FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS','SM','MS_EB')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = @p_aluno 
					AND VW.ANO = @p_ano
					AND VW.ESTORNO = 'N'
					AND (IL.DESCRICAO LIKE '%Acerto%' OR IL.DESCRICAO LIKE '%Restitu%')
					AND VW.VALOR <= 0 --SE O ALUNO DEVE MENOS ATÉ 50 REAIS NÃO É CONSIDERADO INADIMPLENTE
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11','3') THEN 1 WHEN @p_semestre IN ('2','22','4') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11','3') THEN 6 WHEN @p_semestre IN ('2','22','4') THEN 12 ELSE 12 END
UNION
-- BOLSA PROUNI 
	SELECT TOP 1 'BOLSA PROUNI ' AS TIPO FROM LYCEUM..LY_BOLSA B
					JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
					WHERE TB.GRUPO_BOLSA =  'PROUNI'
					AND B.ALUNO = @p_aluno 
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
	
UNION
-- RESPONSAVEL PROUNI
	SELECT TOP 1 'RESPONSAVEL PROUNI' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = '03738654000105' --RESP PROUNI/PROIES
					AND PPP.ALUNO = @p_aluno 
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre
UNION
-- RESPONSAVEL FIES 100%
	SELECT TOP 1 'RESPONSAVEL FIES 100%' AS TIPO FROM LYCEUM..LY_PLANO_PGTO_PERIODO PPP
					WHERE PPP.RESP = 'FIES' --RESP FIES
					AND PPP.ALUNO = @p_aluno 
					AND PPP.PERCENT_DIVIDA_ALUNO > 0.00
					AND PPP.ANO = @p_ano
					AND PPP.PERIODO = @p_semestre
	