SELECT CAST('' AS VARCHAR(100)) AS TIPO_PAGAMENTO ,* INTO #TEMP FROM BI_ACOMP_MATR_HIST WHERE ANO = 2020 AND SEMESTRE = 1
AND CONVERT(VARCHAR(10),DATA_HIST,103) = '28/10/2019' AND TIPO_ALUNO IN ('CALOURO','REINGRESSO')
AND PAGO = 1

AND ALUNO IN (SELECT ALUNO FROM BI_ACOMP_MATR_HIST WHERE ANO = 2020 AND SEMESTRE = 1
AND CONVERT(VARCHAR(10),DATA_HIST,103) = '26/10/2019' AND TIPO_ALUNO IN ('CALOURO','REINGRESSO')
AND PAGO = 0)

DROP TABLE #TEMP WHERE TIPO_PAGAMENTO IS NULL

UPDATE T SET T.TIPO_PAGAMENTO = (SELECT TOP 1 'Pagamento de Mensalidade / Acordo de Mensalidade' AS TIPO FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = T.ANO
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = T.SEMESTRE
				AND LD.ALUNO = T.ALUNO 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo')
UNION

--BOLSA 100% NO SEMESTRE
	SELECT TOP 1 'BOLSA 100% VIGENTE NO SEMESTRE' AS TIPO FROM LY_BOLSA B
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL)
					
UNION
--BOLSA 100% ABERTA		
	SELECT TOP 1 'BOLSA 100% ABERTA' AS TIPO FROM LY_BOLSA B 
					WHERE B.ALUNO = T.ALUNO AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL
		
UNION
--BOLSA CREDEDUC
	SELECT TOP 1 'BOLSA CREDEDUC' AS TIPO FROM LY_BOLSA B WHERE B.TIPO_BOLSA = 'CREDEDUC' 
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= YEAR(GETDATE()) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= MONTH(GETDATE()) OR B.MESFIM IS NULL)

UNION
--ALUNO CONTRATO FIES
	SELECT TOP 1 'CONTRATO FIES' AS TIPO FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = T.ANO AND CFP.PERIODO = T.SEMESTRE AND CF.ALUNO = T.ALUNO
UNION
--COBRANÇA DE MENSALIDADE SEM SALDO A PAGAR
	SELECT TOP 1 'COBRANCA COM LANÇAMENTO DE ACERTO / RESTITUIÇÃO / BOLSA / Acordo ' FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS','SM')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = T.ALUNO
					AND VW.ANO = T.ANO
					AND VW.ESTORNO = 'N'
					AND (IL.DESCRICAO LIKE '%Acerto%' OR IL.DESCRICAO LIKE '%Restitu%' OR IL.DESCRICAO LIKE '%Bolsa%')
					AND VW.MES BETWEEN CASE WHEN T.SEMESTRE IN ('1','11') THEN 1 WHEN T.SEMESTRE IN ('2','22') THEN 7 ELSE 1 END AND CASE WHEN T.SEMESTRE IN ('1','11') THEN 6 WHEN T.SEMESTRE IN ('2','22') THEN 12 ELSE 12 END 		
					AND VW.VALOR <= 50
--BOLSA FIES TEMP *SOLICITADO POR ANDRÉ BRITTO / ANA PAULA GOMES em 25/03/2019*
UNION	
	SELECT TOP 1 'BOLSA FIES TEMP' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = T.ANO AND PERIODO = T.SEMESTRE) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = T.ANO AND PERIODO = T.SEMESTRE) OR B.MESFIM IS NULL)

UNION
	SELECT TOP 1 'BOLSA PROUNI' AS TIPO FROM LYCEUM..LY_BOLSA B
					JOIN LYCEUM..LY_TIPO_BOLSA TB ON TB.TIPO_BOLSA = B.TIPO_BOLSA
					WHERE TB.GRUPO_BOLSA =  'PROUNI'
					AND B.ALUNO = T.ALUNO
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = T.ANO AND PERIODO = T.SEMESTRE) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = T.ANO AND PERIODO = T.SEMESTRE) OR B.MESFIM IS NULL)
)

FROM #TEMP T

SELECT NOME_UNIDADE_ENSINO_ALUNO,NOME_CURSO,ALUNO, NOME_ALUNO, 'CB UNIFICADA 50 REAIS' AS MOTIVO_PAGAMENTO FROM #TEMP WHERE TIPO_PAGAMENTO IS NULL
