select * FROM BI_ACOMP_MATR WHERE ALUNO = '201290132'

select * FROM LYCEUM..LY_ALUNO WHERE ALUNO = '201290132'
select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '201290132'

DROP TABLE #TEMP1
DROP TABLE #TEMP2

SELECT A.ALUNO, P.* INTO #TEMP2
FROM LYCEUM..LY_ALUNO A 
JOIN LYCEUM..LY_PESSOA P ON P.PESSOA = A.PESSOA
WHERE A.ANO_INGRESSO = 2020 
AND A.SEM_INGRESSO = 1 
--AND A.TIPO_INGRESSO = 'TransferenciaInterna'
AND A.SIT_ALUNO IN ('Cancelado','Transferido')
AND EXISTS (SELECT ALUNO INTO  #TEMP1
			FROM LYCEUM..LY_ALUNO A1 
			WHERE 1=1
			AND A1.ANO_INGRESSO = 2020 
			AND A1.SEM_INGRESSO = 1 
			--AND A1.SIT_ALUNO IN ('Cancelado','Transferido')
			AND A1.PESSOA IN (SELECT PESSOA FROM #TEMP2))

			
SELECT * INTO #TEMP3
FROM LYCEUM..LY_ALUNO A 
WHERE A.ANO_INGRESSO = 2020 
AND A.SEM_INGRESSO = 1 
--AND A.TIPO_INGRESSO = 'TransferenciaInterna'
AND A.SIT_ALUNO IN ('Cancelado')
AND A.UNIDADE_FISICA = 'FTC-LAPA'
AND EXISTS (SELECT TOP 1 1 
			FROM LYCEUM..LY_ALUNO A1 
			WHERE A1.PESSOA = A.PESSOA 
			AND A1.ALUNO <> A.ALUNO 
			AND A1.ANO_INGRESSO = 2020 
			AND A1.SEM_INGRESSO = 1 
			AND A1.SIT_ALUNO IN ('Cancelado','Transferido')
			AND A1.UNIDADE_FISICA = 'FTC-LAPA')


SELECT * FROM BI_REMATRICULA WHERE ALUNO IN (SELECT ALUNO FROM #TEMP1) AND ANO = 2020 AND SEMESTRE = 1 AND CPF IS NOT NULL AND CPF <> '' AND CPF <> '00000000000' 
ORDER BY CPF

SELECT * FROM BI_REMATRICULA BI
WHERE BI.ANO = 2020 
AND BI.SEMESTRE = 1
AND BI.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
--AND BI.STATUS_FTC NOT IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO')
AND EXISTS(SELECT TOP 1 1 FROM BI_REMATRICULA BI2 WHERE BI2.CPF = BI.CPF AND BI2.ALUNO <> BI.ALUNO
			AND BI2.ANO = 2020 AND BI2.SEMESTRE = 1 
			AND BI2.TIPO_ALUNO IN ('CALOURO','CALOURO-CONCLUINTE')
			AND BI2.CPF IS NOT NULL AND BI2.CPF <> '' AND BI2.CPF <> '00000000000' )
AND BI.CPF IS NOT NULL AND BI.CPF <> '' AND BI.CPF <> '00000000000' 
ORDER BY BI.CPF


SELECT * FROM #TEMP3 WHERE ALUNO NOT IN (SELECT ALUNO FROM BI_ACOMP_MATR WHERE ANO = 2020 AND SEMESTRE = 1)

SELECT * FROM BI_ACOMP_MATR 
WHERE NOME_UNIDADE_ENSINO_ALUNO = 'FTC-LAPA' 
AND ANO = 2020 
AND SEMESTRE = 1 
AND TIPO_ALUNO = 'CALOURO'
AND PAGO = 1