--André Luiz Vicente de Jesus (FORMADOS) -- NÃO TRAZIDO NA NOVA CARGA DE LUIZ
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%andre%luiz%vicente%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '051071348'
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%andre%luiz%vicente%'
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE cod_aluno_virtual = '298368'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '298368'
SELECT * FROM ly_matricula_provao lpm
SELECT * FROM tbl_enade
SELECT * --FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX 
from VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES
WHERE cod_aluno_virtual = '298368'

--Carine Pinheiro Franco(FORMADOS)
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%carine%pinheiro%franco%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '131071051'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '131071051'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%carine%pinheiro%franco%'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '872214'
SELECT * FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '872214' 


--Juliete Santos Cunha(FORMADOS)
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%juliete%santos%cunha%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '112071225'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '132070966'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%juliete%santos%cunha%'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '729634'
SELECT * FROM TBL_ENADE WHERE ALUNO = '729634'

--Iuri Fontes Bittencourt(FORMADOS)
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Iuri%Fontes%Bittencourt%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '092070413'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '092070413'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Iuri%Fontes%Bittencourt%'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '533479'
SELECT * FROM VIRTUALCLASS..TBL_ENADE WHERE ALUNO = '533479'

--Rodrigo Calasans de Santana Almeida(FORMADOS)
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Rodrigo%Calasans%Santana%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '111070010'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '092070413'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Rodrigo%Calasans%Santana%'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '131701'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE nome_compl LIKE '%Rodrigo%Calasans%Santana%'
SELECT * FROM VIRTUALCLASS..TBL_ENADE WHERE ALUNO = '131701'

--Adive Cardoso Ferreira Júnior(FORMADOS)
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Adive%Cardoso%Ferreira%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '111070010'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '092070413'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Adive%Cardoso%Ferreira%'

--LOIZE MATOS DE SANTANA 
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%LOIZE%MATOS%SANTANA%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '162070075'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '162070075'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%LOIZE%MATOS%SANTANA%'

--EDLENE SAMPAIO FIAZ
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%EDLENE%SAMPAIO%FIAZ%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '152070729'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '152070729'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%EDLENE%SAMPAIO%FIAZ%'

--ANDRE LUIZ DA SILVA CHAVES
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ANDRE%LUIZ%SILVA%CHAVES%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '091070261'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '091070261'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ANDRE%LUIZ%SILVA%CHAVES%'
SELECT DISTINCT disciplina, nome_disc_orig, situacao_hist FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '492513' AND ano = '2015' AND semestre = '2'

--NATALIA BARBOSA CARVALHO
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%NATALIA%BARBOSA%CARVALHO%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '142070092'
SELECT * FROM LY_HISTMATRICULA WHERE aluno = '142070092'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%NATALIA%BARBOSA%CARVALHO%'
SELECT DISTINCT disciplina, nome_disc_orig, situacao_hist FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '961432' AND ano = '2015' AND semestre = '2'

--JONATAS REZENDE SILVA
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%JONATAS%REZENDE%SILVA%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '122070797'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '122070797'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%JONATAS%REZENDE%SILVA%'
SELECT DISTINCT disciplina, nome_disc_orig, situacao_hist FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '785291' AND ano = '2015' AND semestre = '2' --AND curso = '590'
SELECT * FROM tbl_curso_matriz WHERE curso IN ('343','590')

--ROQUE ALMEIDA DOS SANTOS FILHO
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ROQUE%ALMEIDA%SANTOS%FILHO%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '122070742'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '122070742'

--ERIKA BISPO LOPES XAVIER
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ERIKA%BISPO%LOPES%XAVIER%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '162070111'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '162070111'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ERIKA%BISPO%LOPES%XAVIER%'
SELECT DISTINCT disciplina, nome_disc_orig, situacao_hist FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '975963' AND ano = '2016' AND semestre = '1' --AND curso = '590'

--AIDA DE ALMEIDA CEDRO
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%AIDA DE ALMEIDA CEDRO%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '151070408'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '151070408'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ERIKA%BISPO%LOPES%XAVIER%'
SELECT DISTINCT disciplina, nome_disc_orig, situacao_hist FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '975963' AND ano = '2016' AND semestre = '1' --AND curso = '590'

--GABRIELLA MENEZES COSTA
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%GABRIELLA%MENEZES%COSTA%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '151070408'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '151070408'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ERIKA%BISPO%LOPES%XAVIER%'
SELECT DISTINCT disciplina, nome_disc_orig, situacao_hist FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '975963' AND ano = '2016' AND semestre = '1' --AND curso = '590'

--JOABES SILVA DOS SANTOS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%JOABES SILVA DOS SANTOS%'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE lhcc.ALUNO = '132070749'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '132070749'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ERIKA%BISPO%LOPES%XAVIER%'
SELECT DISTINCT disciplina, nome_disc_orig, situacao_hist FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '975963' AND ano = '2016' AND semestre = '1' --AND curso = '590'

--BARBARA WANDERLEY AYADE SANTOS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%BARBARA%WANDERLEY%AYADE%SANTOS%'
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%BARBARA%WANDERLEY%AYADE%SANTOS%'
SELECT SUM(valor_bruto)  FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '972158' AND PERIODO_LETIVO = '20152'
SELECT SUM(valor_bruto)  FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '972158' AND PERIODO_LETIVO = '20152'
SELECT *  FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '972158' AND PERIODO_LETIVO = '20152'

SELECT * FROM MIGRACAO..VW_MIGRA_LY_COBRANCA WHERE ALUNO = '142070108' AND ANO = '2015' AND MES BETWEEN 7 AND 12





--MILLA MARINHO MORAIS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%MILLA%MARINHO%MORAIS%'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%MILA%MARINHO%'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%MILA%MARINHO%MORAIS%'

--EDINEA SILVA COSTA
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%EDINEA%SILVA%COSTA%'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%EDINEA%SILVA%COSTA%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('345')

--
--FILLIPHE SANTOS DA SILVA
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%FILLIPHE%SANTOS%SILVA%'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%FILLIPHE%SANTOS%SILVA%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('345')

--ITALO FELIPE SOUZA SANTOS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ITALO%FELIPE%SOUZA%'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ITALO%FELIPE%SOUZA%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('345')

--ADROMAHI NOVAIS DIAS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ADROMAHI%NOVAIS%DIAS%'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ADROMAHI%NOVAIS%DIAS%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('345')

--ANA BATISTA DOS SANTOS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ANA%BATISTA%DOS%SANTOS%' AND UNIDADE_ENSINO = '07'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ANA%BATISTA%DOS%SANTOS%' AND UNIDADE_ENSINO = '07'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('345')

--ANA PAULA SILVA LEAL
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ANA%PAULA%SILVA%LEAL%'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ANA%PAULA%SILVA%LEAL%'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%ANA%PAULA%SILVA%LEAL%'

--DANIELLE DIAS RAMOS FONTES
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%DANIELLE%DIAS%RAMOS%FONTES%'
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ANA%PAULA%SILVA%LEAL%'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%DANIELLE%DIAS%RAMOS%FONTES%'

--ARACELE CABRAL DOS SANTOS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ARACELE%CABRAL%DOS%SANTOS%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('747')
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ARACELE%CABRAL%DOS%SANTOS%'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%DANIELLE%DIAS%RAMOS%FONTES%'

--DEISE NOBRE SCHER
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%DEISE%NOBRE%SCHER%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('747')
SELECT * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ARACELE%CABRAL%DOS%SANTOS%'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%DEISE%NOBRE%SCHER%'

--ELOA ALMEIDA FAUSTINO
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ELOA%ALMEIDA%FAUSTINO%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('747')
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ELOA%ALMEIDA%FAUSTINO%'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%DEISE%NOBRE%SCHER%'

--EVERLLIN DE SANTANA GONCALVES
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%EVERLLIN%SANTANA%GONCALVES%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('747')
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%EVERLLIN%SANTANA%GONCALVES%'
SELECT * FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '858865'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%DEISE%NOBRE%SCHER%'

--ERICK VINICIUS PINHEIRO DE SOUSA
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ERICK%VINICIUS%PINHEIRO%SOUSA%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('590')
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ERICK%VINICIUS%PINHEIRO%SOUSA%'
SELECT * FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '858865'
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%DEISE%NOBRE%SCHER%'

--FELIPE AURELIO MARTINS AREAO
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%FELIPE%AURELIO%MARTINS%AREAO%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('590')
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%FELIPE%AURELIO%MARTINS%AREAO%'
SELECT SUM(valor_bruto) FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '961284' AND ANO = '2015' AND MES BETWEEN 7 AND 12
SELECT * FROM MIGRACAO..TBL_PESSOA_ALUNO_DOCENTE_RESP WHERE NOME_COMPL LIKE '%DEISE%NOBRE%SCHER%'

--CAIQUE IURE TELES FERREIRA
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%CAIQUE%IURE%TELES%FERREIRA%'
SELECT * FROM MIGRACAO..tbl_curso_matriz WHERE curso IN ('590')
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%WINDSOR%'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE NOME_COMPL LIKE '%Windsor%'
SELECT * FROM LY_LANC_DEBITO WHERE ALUNO = '121070691' AND ANO_REF = '2015' AND PERIODO_REF = '2'
SELECT SUM(valor_bruto) FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'
SELECT * FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'
SELECT * FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'
SELECT SUM(valor_bruto) FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'

--Claudineia Santos da Mota
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Claudineia%Santos%Mota%'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Claudineia%Santos%Mota%'
SELECT SUM(valor_bruto) FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '965106' AND PERIODO_LETIVO = '20152'
SELECT * FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'
SELECT * FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'
SELECT SUM(valor_bruto) FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'

--Eliliane de Almeida Soares
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Eliliane%Almeida%Soares%'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Eliliane%Almeida%Soares%'
SELECT SUM(valor_bruto) FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '970254' AND PERIODO_LETIVO = '20152'
SELECT * FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '970254' AND PERIODO_LETIVO = '20152'
SELECT * FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'
SELECT SUM(valor_bruto) FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'

--SERGIO SANTOS ALMEIDA
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%SERGIO%SANTOS%ALMEIDA%'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%SERGIO%SANTOS%ALMEIDA%'
SELECT SUM(valor_bruto) FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '969564' AND PERIODO_LETIVO = '20152'
SELECT * FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '970254' AND PERIODO_LETIVO = '20152'
SELECT * FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '969564' AND PERIODO_LETIVO = '20152'
SELECT SUM(valor_bruto) FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '969564' AND PERIODO_LETIVO = '20152'


--THIAGO GOMES SOARES
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%THIAGO%GOMES%SOARES%'
SELECT SUM(valor_bruto) FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '875244' AND PERIODO_LETIVO = '20152'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%THIAGO%GOMES%SOARES%'
SELECT * FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '970254' AND PERIODO_LETIVO = '20152'
SELECT * FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '805408' AND PERIODO_LETIVO = '20152'
SELECT SUM(valor_bruto) FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '875244' AND PERIODO_LETIVO = '20152'

--ACACIO FRAGA DOS REIS
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%ACACIO FRAGA DOS REIS%'
SELECT SUM(valor_bruto) FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '875244' AND PERIODO_LETIVO = '20152'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%ACACIO FRAGA DOS REIS%'
SELECT SUM(valor_bruto)  FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '922308' AND PERIODO_LETIVO = '20152'
SELECT *  FROM MIGRACAO..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '922308' AND PERIODO_LETIVO = '20152'

SELECT * FROM MIGRACAO..VW_MIGRA_LY_COBRANCA WHERE ALUNO = '142070108' AND ANO = '2015' AND MES BETWEEN 7 AND 12
SELECT SUM(valor_bruto)  FROM VIRTUALCLASS..TBL_FINANCEIRO WHERE CODIGO_ALUNO_VIRTUAL = '922308' AND PERIODO_LETIVO = '20152'

--Aline Da Silva Oliveira
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Aline Da Silva Oliveira%'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Aline Da Silva Oliveira%'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '151030339'
SELECT * FROM VIRTUALCLASS..TBL_HISTORICO WHERE CODIGO_ALUNO_VIRTUAL = '' AND ANO = '2015' AND SEMESTRE = '2'

--Caroline de Gois Goncalves
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Caroline de Gois Goncalves%'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Caroline de Gois Goncalves%'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '132030469'
SELECT SITUACAO_HIST,* FROM VIRTUALCLASS..TBL_HISTORICO WHERE ALUNO = '842142' AND DISCIPLINA = '147247'

--Rodrigo Nascimento Soares
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Rodrigo Nascimento Soares%'
SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '151030384'

--Agatha da Guia Andrade
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Agatha da Guia Andrade%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '149070'

--Agatha da Guia Andrade
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Ana Carla Santos de Oliveira%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '82145'

--Brena Ferreira da Luz
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Brena Ferreira da Luz%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '82394'

--Carla Lima Guimarães
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Carla Lima Guimarães%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '53200'

--Daiane Teixeira Matos
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Daiane Teixeira Matos%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '64550'

--Adriano de Azevedo Santos Filho
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Adriano de Azevedo Santos Filho%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '131828'

--Alana da Conceiçao Teixeira
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Alana da Conceiçao Teixeira%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '57905'

--Ana Carolina da Silva Santos
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Ana Carolina da Silva Santos%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '46531'

--Angelica Barbosa Ferreira
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Angelica Barbosa Ferreira%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '74454'

--Carlos Pereira Santos Filho
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Carlos Pereira Santos Filho%'
SELECT * FROM LY_PESSOA lp WHERE lp.PESSOA = '93162'

--Gildete Silveira dos Santos
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Gildete Silveira dos Santos%'
SELECT cpf,* FROM LY_PESSOA lp WHERE lp.PESSOA = '102950'
SELECT * FROM LY_H_CURSOS_CONCL lhcc WHERE aluno = '041291898'
SELECT * FROM LY_HISTMATRICULA lh WHERE lh.ALUNO = '041291898'
SELECT * FROM LY_HISTMATRICULA lh WHERE lh.ALUNO = '041291897'
SELECT * FROM LY_CURRICULO lc WHERE lc.CURSO = '456' AND lc.CURRICULO = '21787'

--Cesira Maccarinelli Ferre
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Cesira Maccarinelli Ferre%'
SELECT cpf,* FROM LY_PESSOA lp WHERE lp.PESSOA = '110939'

--Fabio Silva Soares
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Fabio Silva Soares%'
SELECT cpf,* FROM LY_PESSOA lp WHERE lp.PESSOA = '146908'
SELECT * FROM LY_CURRICULO lc WHERE lc.CURSO = '2209' AND lc.CURRICULO = '24351'
SELECT COD_ALUNO_VIRTUAL, * FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Fabio Silva Soares%'

--Bianca Moraes dos Santos
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Bianca Moraes dos Santos%'
SELECT cpf,* FROM LY_PESSOA lp WHERE lp.PESSOA = '146908'

--Bianca Moraes dos Santos
SELECT pessoa,* FROM ly_aluno WHERE nome_compl LIKE '%Bianca Moraes dos Santos%'
SELECT cpf,* FROM LY_PESSOA lp WHERE lp.PESSOA = '146908'