SELECT * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND SIT_MATRICULA = 'Sem-Matricula' AND STATUS_FTC NOT IN ('EVADIDO','CANCELADO','CONCLUIDO')
select * FROM BI_REMATRICULA WHERE TIPO_ALUNO = 'CALOURO' AND ANO = 2018 AND SEMESTRE = 2 AND SIT_MATRICULA = 'Sem-Matricula'
select * FROM BI_REMATRICULA WHERE ALUNo = '161040054'
select * FROM BI_REMATRICULA  
select distinct STATUS_FTC FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 1

select *from LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '161040054'

SELECT * FROM BI_REMATRICULA T 
WHERE LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(T.ALUNO,'N') = 0
AND T.ANO = 2018 AND T.SEMESTRE = 2
AND CURSO = '722'

SELECT * FROM BI_REMATRICULA T 
WHERE 1=1
--AND T.ANO = 2018 AND T.SEMESTRE = 2
AND STATUS_FTC = 'CONCLUIDO'
AND NOT EXISTS (
	SELECT TOP 1 1 FROM LYCEUM..LY_H_CURSOS_CONCL
	WHERE ALUNO = T.ALUNO
	AND MOTIVO = 'CONCLUSAO'
	AND DT_REABERTURA IS NULL
)
order by 4,8

SELECT DISTINCT MOTIVO
FROM LYCEUM..LY_H_CURSOS_CONCL


SELECT * 
FROM LYCEUM..LY_H_CURSOS_CONCL
WHERE 1=1
--AND ANO_ENCERRAMENTO = 2018
--AND SEM_ENCERRAMENTO = 2
--AND MOTIVO = 'CONCLUSAO'
AND DT_REABERTURA IS NULL
AND ALUNO = '181030512'

select * FROM BI_REMATRICULA WHERE ALUNO = '201240001' ORDER BY 1,2
select * FROM BI_REMATRICULA WHERE CPF = '81998899500'
select * FROM BI_REMATRICULA WHERE ANO = '2019' AND SEMESTRE = '1'

select * FROM BI_FINANCEIRO 
WHERE TIPO_CURSO IN ('GRADUACAO','POS-GRADUACAO','GRADUACAO-EAD','GRADUACAO-SP','TECNOLOGO','MESTRADO')
AND DATA_REF BETWEEN '2018-01-01' AND '2019-12-01'

SELECT DISTINCT UNIDADE_FISICA_ALUNO, NOME_UNIDADE_ENSINO_ALUNO, CURSO, NOME_CURSO, TURNO 
FROM BI_REMATRICULA WHERE ANO = 2020 AND SEMESTRE = 1
ORDER BY 1,3

select distinct ano,semestre from LYCEUM..LY_HISTMATRICULA ORDER BY 1,2
select * FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ALUNO = '072030149'
select * FROM LYCEUM..LY_ALUNO WHERE ALUNO = '201240001'
select * FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ALUNO = '192030550'

select top 10 * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE SIT_MATRICULA = 'Trancado'

SELECT * FROM LYCEUM..LY_UNIDADE_FISICA

SELECT * FROM LYCEUM..LY_ALUNO WHERE UNIDADE_FISICA = 'OTE-CAM'

select top 10 * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA ORDER BY DT_INSERCAO DESC
select top 10 * FROM HADES..HD_USUARIO

SELECT * FROM BI_REMATRICULA WHERE ANO = 2020 AND SEMESTRE = 1
AND TIPO_ALUNO IN ('VETERANO','REINGRESSO','VETERANO-CONCLUINTE','REINGRESSO-CONCLUINTE')
AND TIPO_FINAN = 'PROUNI PARCIAL'
AND EXISTS (SELECT TOP 1 'Pagamento de Mensalidade / Acordo de Mensalidade' AS TIPO FROM LY_ITEM_CRED IC
				JOIN LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = @p_aluno 
				AND LD.CODIGO_LANC IN ('MS','MS_EB','SM','Acordo'))



select distinct TIPO_FINAN FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 1
select count(distinct aluno) from LYCEUM..LY_MATRICULA

select * FROM LY_TURMA_CURSO WHERE ANO = 2019 AND SEMESTRE = 2
select COUNT(ALUNO), SERIE_CALCULADA FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1
AND NOME_CURSO = 'Direito'
AND SERIE_CALCULADA > 7
AND STATUS_FTC  IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') 
GROUP BY SERIE_CALCULADA

select COUNT(ALUNO), SERIE_CALCULADA FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1
AND NOME_CURSO = 'Direito'
AND SERIE_CALCULADA > 7
AND STATUS_FTC  NOT IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO') 
GROUP BY SERIE_CALCULADA


select COUNT(ALUNO), SERIE FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 
AND NOME_CURSO = 'Direito'
AND SERIE > 7
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') 
GROUP BY SERIE



select COUNT(ALUNO), CONCAT(ANO_INGRESSO,SEM_INGRESSO) FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 
AND NOME_CURSO = 'Direito'
AND CONCAT(ANO_INGRESSO,SEM_INGRESSO) IN ('20142','20151','20152')
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') 
GROUP BY CONCAT(ANO_INGRESSO,SEM_INGRESSO)




select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '141040028'
select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '141040028'

select * FROM LYCEUM..LY_GRADE WHERE CURSO = '' AND TURNO = '' AND CURRICULO = ''

select * 
FROM BI_REMATRICULA 
WHERE STATUS_FTC NOT IN ('CANCELADO','CONCLUIDO','EVADIDO','TRANSFERIDO','MATRICULADO NÃO-PAGO','MATRICULADO PAGO')
AND ANO = 2008 AND SEMESTRE = 1

select * FROM BI_REMATRICULA WHERE ALUNO = '121030179' order by 1,2
select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '061040240'
select * FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ALUNO = '061040240'

select * FROM BI_REMATRICULA BI
JOIN BASE_CEP CEP ON CEP.CEP = BI.CEP
WHERE BI.UNIDADE_FISICA_ALUNO = 'FTC-SSA' AND BI.ANO = '2018' AND BI.SEMESTRE = '2'

select distinct nome_curso from BI_REMATRICULA WHERE NOME_CURSO LIKE '%Comunicação%'
select COUNT(aluno	), cpf from BI_REMATRICULA
where ano = 2018 AND SEMESTRE = 1
GROUP BY cpf
HAVING COUNT(aluno) > 1

select * from BI_REMATRICULA WHERE CPF = '02479468500'  AND ANO = 2018 AND SEMESTRE =1 

SELECT * 
FROM  BI_REMATRICULA 
WHERE 1=1
AND ANO = 2018 AND SEMESTRE = 2  
AND TIPO_ALUNO = 'VETERANO'
--AND STATUS_FTC NOT LIKE 'MATRICULADO%' 
AND STATUS_FTC NOT IN ('CONCLUIDO','MATRICULADO PAGO','MATRICULADO NÃO-PAGO') 
ORDER BY 1,2,4,9

select *, LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(ALUNO,'N') AS QTD_PENDENTES FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2
AND TIPO_ALUNO = 'VETERANO'

select * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 --171030509

select * FROM BI_REMATRICULA WHERE ALUNO = '171030509' AND ANO = 2018 AND SEMESTRE = 1

select DISTINCT STATUS_FTC FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2

select * FROM BI_REMATRICULA WHERE SERIE = 1 AND ANO = 2018 AND SEMESTRE = 2 AND STATUS_FTC = 'Evadido'

select * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND TIPO_ALUNO = 'VETERANO' AND SERIE_CALCULADA = 1

select * 
FROM BI_REMATRICULA
 WHERE 1=1 
 AND ANO = 2018 
 AND SEMESTRE = 2 AND STATUS_FTC LIKE 'MATRICU%'
AND TIPO_ALUNO = 'VETERANO'

select * FROM BI_REMATRICULA WHERE ALUNO = '182050145'

SELECT *
DELETE BI 
FROM BI_REMATRICULA BI WHERE ANO = '2018' AND SEMESTRE = '2'
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 WHERE BI2.ALUNO = BI.ALUNo AND BI2.ANO = 2018 AND BI2.SEMESTRE = 1 AND BI2.STATUS_FTC IN ('EVADIDO','TRANCADO','CONCLUIDO','NÃO REMATRICULADO PAGO','NÃO REMATRICULADO NÃO-PAGO', 'PRE-MATRICULADO NÃO-PAGO'))

select * FROM BI_REMATRICULA 
WHERE ANO = 2017 --AND TIPO_ALUNO = 'VETERANO'
AND SEMESTRE = 2
AND STATUS_FTC NOT IN  ('Trancado','Concluido','Cancelado','Evadido','PRE-MATRICULADO NÃO-PAGO','Transferido')
AND STATUS_FTC NOT LIKE 'NAO%'
ORDER BY 1,2


UPDATE BI SET QTD_INADIMP = (SELECT count(distinct c.cobranca) FROM LYCEUM..LY_COBRANCA C
JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
WHERE C.DATA_DE_VENCIMENTO < GETDATE() AND VW.VALOR > 0
AND C.NUM_COBRANCA IN (1,5)
AND C.ESTORNO = 'N'
AND C.DT_ESTORNO IS NULL
AND C.ALUNO = BI.ALUNO
AND LD.ANO_REF = BI.ANO AND LD.PERIODO_REF = BI.SEMESTRE
AND C.RESP <> 'FIES'
)

FROM BI_REMATRICULA BI
WHERE BI.ANO = 2018
AND BI.SEMESTRE = 1 AND STATUS_FTC NOT IN ('Evadido','Cancelado')

SELECT *FROM LYCEUM..LY_COBRANCA C
JOIN LYCEUM..VW_COBRANCA VW ON VW.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
WHERE C.DATA_DE_VENCIMENTO < GETDATE() AND VW.VALOR > 0
AND C.NUM_COBRANCA IN (1,5)
AND C.ESTORNO = 'N'
AND C.DT_ESTORNO IS NULL
--AND C.ALUNO = BI.ALUNO
AND LD.ANO_REF = 2018 AND LD.PERIODO_REF = 1

SELECT * FROM LYCEUM..LY_HISTMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2
select * FROM LYCEUM..LY_MATRICULA WHERE ANO = 2019 AND SEMESTRE = 1
select * FROM LYCEUM..LY_AGENDA
select * FROM LYCEUM..LY_FALTA WHERE ANO = 2018 AND PERIODO = 2
select * FROM LYCEUM..LY_DISCIPLINA WHERE DISCIPLINA = 'SPR465'
select CONVERT(NUMERIC(10,2),18/60)

UPDATE BI2 SET BI2.PERC_FALTAS = (SELECT 1-AVG(HM.PERC_PRESENCA) 
FROM LYCEUM..LY_HISTMATRICULA HM 
WHERE HM.ANO = CASE BI2.SEMESTRE WHEN '1' THEN HM.ANO-1 WHEN '2' THEN HM.ANO WHEN '11' THEN HM.ANO-1 WHEN '22' THEN HM.ANO ELSE HM.ANO END 
	AND HM.SEMESTRE = CASE BI2.SEMESTRE WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '1' WHEN '11' THEN '2' ELSE HM.SEMESTRE END
	AND BI2.ALUNO = HM.ALUNO
	)
FROM BI_REMATRICULA BI2 

UPDATE BI_REMATRICULA SET PERC_FALTAS = 0.00 WHERE PERC_FALTAS IS NULL
UPDATE BI_REMATRICULA SET PERC_FALTAS = 0.00 WHERE TIPO_ALUNO = 'CALOURO'

select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '172040128'


CREATE TABLE TEMP_FALTAS (
	ALUNO VARCHAR(20),
	DISCIPLINA VARCHAR(20),
	TURMA VARCHAR(30),
	ANO VARCHAR(4),
	SEMESTRE VARCHAR(2),
	TOTAL_AULAS INT,
	TOTAL_FALTAS INT

)

INSERT INTO TEMP_FALTAS
SELECT VW.ALUNO, VW.DISCIPLINA, VW.TURMA, VW.ANO, VW.SEMESTRE,0,0
FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW
JOIN BI_REMATRICULA BI ON BI.ALUNO = VW.ALUNO AND BI.ANO = VW.ANO AND BI.SEMESTRE = VW.SEMESTRE

UPDATE T SET T.TOTAL_AULAS = (SELECT COUNT(*) FROM LYCEUM..LY_AGENDA A WHERE A.DISCIPLINA = T.DISCIPLINA AND A.TURMA = T.TURMA AND A.ANO = T.ANO AND A.SEMESTRE = T.SEMESTRE)
FROM TEMP_FALTAS T

UPDATE T SET T.TOTAL_FALTAS = (SELECT ISNULL(CONVERT(INT,FALTAS),0) FROM LYCEUM..LY_FALTA A WHERE A.DISCIPLINA = T.DISCIPLINA AND A.TURMA = T.TURMA AND A.ANO = T.ANO AND A.PERIODO = T.SEMESTRE AND A.ALUNO = T.ALUNO)
FROM TEMP_FALTAS T

select * FROM LYCEUM..LY_AGENDA WHERE ANO = 2019 AND SEMESTRE =1 AND CANCELADA = 'N'

select * FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE =1 AND TIPO_ALUNO = 'VETERANO' AND ALUNO = '161050679'
select * FROM BI_ACOMP_MATR WHERE ALUNO = '191220074'



select BI.*, A.ANO_INGRESSO, A.SEM_INGRESSO FROM BI_ACOMP_MATR BI
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = BI.ALUNO
 WHERE ANO = 2019 AND SEMESTRE =1 AND BI.TIPO_ALUNO = 'VETERANO' AND PAGO = 1


select DISTINCT BI.ALUNO,A.ANO_INGRESSO,A.SEM_INGRESSO FROM BI_ACOMP_MATR BI
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = BI.ALUNO
 WHERE ANO = 2019 AND SEMESTRE =1 AND BI.TIPO_ALUNO = 'VETERANO' AND PAGO = 1

EXCEPT

select COUNT(ALUNO) QTD, CPF FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE =1-- AND TIPO_ALUNO = 'VETERANO' 
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO')
GROUP BY CPF
HAVING COUNT(ALUNO) > 1
--AND STATUS_FTC NOT LIKE 'NAO%'
--AND PAGO = 1


select * FROM BI_REMATRICULA WHERE ANO = 2017 AND SEMESTRE =1-- AND TIPO_ALUNO = 'VETERANO' 
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO')

SELECT * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 1
AND CPF = '05319444508'





select * FROM LYCEUM..LY_ALUNO WHERE ALUNO = '191220074'
select * FROM LYCEUM..VW_zzAUDITORIA WHERE ESTRUTURA = 'LY_ALUNO' AND CAMPO = 'ALUNO' AND (VALOR1 = '191220074' OR VALOR2 = '191220074')
select * FROM LYCEUM..VW_zzAUDITORIA WHERE NUMERO = '94463220'

select * FROM LYCEUM..HD_USUARIO WHERE USUARIO = '05106918545'
--94463220
--94277563


select * FROM BI_REMATRICULA WHERE ANTECIP_FINAN = 'S' ORDER BY 1,2
select DISTINCT ANO,SEMESTRE,DATA_PERIODO FROM BI_REMATRICULA ORDER BY 1,2
select DISTINCT ANO,SEMESTRE, COUNT(ALUNO) QTD FROM BI_REMATRICULA WHERE ANTECIP_FINAN = 'S' 
GROUP BY ANO,SEMESTRE
ORDER By 1,2
select * FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 1 AND TIPO_CURSO <> 'POS-GRADUACAO'
select * FROM BI_ACOMP_MATR_POS

select * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND UNIDADE_ENSINO_ALUNO = '29' 
AND CURSO = '454'
AND TURNO = 'N'
AND TIPO_ALUNO = 'CALOURO'

select * FROM LYCEUM..LY_HISTMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2
select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ANO = 2019 AND SEMESTRE = 1
select * FROM LYCEUM..LY_MATRICULA WHERE ANO = 2019 AND SEMESTRE = 10,
select * FROM LYCEUM..LY_PRE_MATRICULA WHERE ANO = 2019 AND SEMESTRE = 1

ALTER TABLE BI_REMATRICULA 
	ADD ANTECIP_FINAN VARCHAR(1) NULL


UPDATE T SET ANTECIP_FINAN = 'S'
FROM BI_REMATRICULA T
WHERE EXISTS (SELECT TOP 1 1 FROM LYCEUM..FTC_VW_LANCAMENTOS_PAGAMENTOS LP
			  JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
			  JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
			  JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
			  JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
			  WHERE LP.DATA < T.DATA_PERIODO
			  AND LP.LANC_CRED IS NOT NULL
			  AND C.NUM_COBRANCA = 1
			  AND A.ALUNO = T.ALUNO
			  AND LD.ANO_REF = T.ANO
			  AND LD.PERIODO_REF = T.SEMESTRE
			  )

ALTER TABLE BI_REMATRICULA 
	ADD DT_ANTECIP VARCHAR(10) NULL

UPDATE T SET T.DT_ANTECIP = (SELECT MIN(CONVERT(VARCHAR(10),LP.DATA,103)) FROM LYCEUM..FTC_VW_LANCAMENTOS_PAGAMENTOS LP
JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
WHERE LP.DATA < T.DATA_PERIODO
AND LP.LANC_CRED IS NOT NULL
AND C.NUM_COBRANCA = 1
AND A.ALUNO = T.ALUNO
AND LD.ANO_REF = T.ANO
AND LD.PERIODO_REF = T.SEMESTRE
)
FROM BI_REMATRICULA T
WHERE ANTECIP_FINAN = 'S'

UPDATE T SET T.DT_ANTECIP = (SELECT MIN(CONVERT(VARCHAR(10),LP.DATA,103)) FROM LYCEUM..FTC_VW_LANCAMENTOS_PAGAMENTOS LP
JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
WHERE LP.DATA < T.DATA_PERIODO
AND LP.LANC_CRED IS NOT NULL
AND C.NUM_COBRANCA = 1
AND A.ALUNO = T.ALUNO
AND LD.ANO_REF = T.ANO
AND LD.PERIODO_REF = T.SEMESTRE
)
FROM BI_REMATRICULA T
WHERE ANTECIP_FINAN = 'S'

SELECT SUM(LP.VALOR), FROM LYCEUM..FTC_VW_LANCAMENTOS_PAGAMENTOS LP
JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
JOIN (SELECT DISTINCT COBRANCA,LANC_CRED,VALOR 
		FROM LYCEUM..LY_ITEM_CRED 
		WHERE TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL) X ON X.LANC_CRED = LP.LANC_CRED AND X.COBRANCA = C.COBRANCA
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
WHERE LP.DATA < '2019-01-01'
AND LP.LANC_CRED IS NOT NULL
AND C.NUM_COBRANCA = 1
AND A.ALUNO = '171040012'
AND LD.ANO_REF = '2019'
AND LD.PERIODO_REF = '1'


SELECT TOP 50 * FROM LYCEUM..FTC_VW_LANCAMENTOS_PAGAMENTOS LP
JOIN LYCEUM..LY_ITEM_CRED IC ON IC.LANC_CRED = LP.LANC_CRED AND IC.ITEMCRED = LP.ITEMCRED AND IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = LP.COBRANCA
JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IL.COBRANCA
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = C.ALUNO
WHERE LP.DATA < '2019-01-01'
AND LP.LANC_CRED IS NOT NULL
AND C.NUM_COBRANCA = 1
AND A.ALUNO = '171040012'
AND LD.ANO_REF = '2019'
AND LD.PERIODO_REF = '1'

select * FROM LYCEUM..LY_ITEM_CRED IC 
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
WHERE C.ALUNO = '171040012'
AND C.ANO = 2019 AND C.NUM_COBRANCA = 1



ALTER TABLE BI_REMATRICULA
	ADD TIPO_TRANSF VARCHAR(50)

UPDATE BI2 SET BI2.VALOR_ATENCIP = (select SUM(IC.VALOR) *-1
FROM LYCEUM..LY_ITEM_CRED IC 
JOIN LYCEUM..LY_COBRANCA C ON C.COBRANCA = IC.COBRANCA
JOIN BI_REMATRICULA BI ON BI.ALUNO = C.ALUNO
WHERE C.ALUNO = BI.ALUNO
AND C.ANO = BI.ANO AND C.MES BETWEEN CASE WHEN BI.SEMESTRE = 1 THEN 1 ELSE 7 END AND CASE WHEN BI.SEMESTRE = 1 THEN 6 ELSE 12 END
AND C.NUM_COBRANCA = 1 AND IC.TIPO_ENCARGO IS NULL AND IC.TIPODESCONTO IS NULL
AND BI.ANO = BI2.ANO AND BI.SEMESTRE = BI2.SEMESTRE
AND BI.ALUNO = BI2.ALUNO
AND IC.DATA < BI.DATA_PERIODO
)
FROM BI_REMATRICULA BI2
WHERE ANTECIP_FINAN = 'S'

select * FROM BI_REMATRICULA WHERE ANTECIP_FINAN = 'S' AND ALUNO = '172030409'
select * FROM BI_REMATRICULA WHERE ANTECIP_FINAN = 'S' AND (VALOR_ATENCIP IS NULL OR VALOR_ATENCIP = 0.00) AND ANO = 2019 AND SEMESTRE = 1

select * FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ANO_ENCERRAMENTO = 2019 AND SEM_ENCERRAMENTO = 1 AND MOTIVO = 'CONCLUSAO'

select * FROM BI_REMATRICULA WHERE ANO > 2015 AND ANO < 2019
ORDER BY 1,2

select * FROM BI_REMATRICULA WHERE TIPO_CURSO = 'GRADUACAO-EAD' AND ANO = 2018 AND SEMESTRE = 2

select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '182300063'
select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '182300063'

select * FROM BI_REMATRICULA WHERE TIPO_ALUNO = 'CALOURO' AND STATUS_FTC = 'EVADIDO'
select * FROM BI_REMATRICULA WHERE ALUNO = '142050141'
select * FROM BI_REMATRICULA WHERE ALUNO = '172040346'

select * FROM BI_REMATRICULA WHERE ANO = 2019 AND TIPO_ANTECIP = 'Acordo'
select distinct ano, semestre FROM BI_REMATRICULA

select * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 
AND STATUS_FTC NOT IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO')
AND SERIE_CALCULADA = 2 AND UNIDADE_FISICA_ALUNO = 'FTC-SSA' AND CURSO = '2076'


select * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO')
ORDER BY 1,2

select * FROM BI_REMATRICULA WHERE ALUNO = '181030717' ORDER BY 1,2
select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '181041330'
select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '181041330'


select * FROM BI_REMATRICULA WHERE SERIE_CALCULADA = 3
--AND STATUS_FTC NOT IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO')
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO')
AND ANO = 2018 AND SEMESTRE = 1

SELECT * FROM BI_REMATRICULA 
WHERE ANO = 2018 AND SEMESTRE = 2 
AND TIPO_ALUNO = 'VETERANO' 
AND SERIE_CALCULADA = '2' 
AND UNIDADE_FISICA_ALUNO = 'FTC-SSA'
AND CURSO = '722'
select * FROM BI_REMATRICULA WHERE ALUNO = '181041762' ORDER BY 1,2
select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '041043666' ORDER BY 1,2
select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '041043666' ORDER BY 1,2


select SERIE_CALCULADA, COUNT(ALUNO) FROM BI_REMATRICULA
WHERE ANO = 2018 AND SEMESTRE = 2
GROUP BY SERIE_CALCULADA ORDER BY 1

select SERIE_CALCULADA, COUNT(ALUNO) FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND ANO_INGRESSO = 2015 AND SEM_INGRESSO = 2
GROUP BY SERIE_CALCULADA ORDER BY 1

select distinct UNIDADE_ENSINO_ALUNO FROM BI_REMATRICULA

select * from BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND ALUNO = '161040029'
select * from BI_REMATRICULA WHERE ALUNO = '161040029'


SELECT * FROM #TEMP WHERE ALUNO NOT IN 
(select ALUNO from BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND CURSO = '722')
--AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO'))
--AND SERIE_CALCULADA = 1

LYCEUM..LY_MATRICULA
LYCEUM..LY_HISTMATRICULA

SELECT * FROM BI_REMATRICULA WHERE ALUNO = '162060013' ORDER BY 1,2

select TIPO_FINAN,COUNT(ALUNO) FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1
GROUP BY TIPO_FINAN

select * FROM BI_REMATRICULA WHERE UNIDADE_FISICA_ALUNO = 'OTE-JUA' AND ANO = 2018 AND SEMESTRE = 1

SELECT TIPO_FINAN,COUNT(DISTINCT ALUNO) 
FROM BI_REMATRICULA 
WHERE TIPO_FINAN IN ('FIES+PROUNI','PROIES','PROUNI INTEGRAL','PROUNI PARCIAL') 
AND ANO = 2018
GROUP BY TIPO_FINAN

SELECT * FROM BI_REMATRICULA 
WHERE STATUS_FTC  NOT IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO') 
AND ANO = 2018 AND SEMESTRE = 2

UPDATE T SET T.STATUS_FTC = 'EVADIDO'
FROM BI_REMATRICULA T
WHERE T.STATUS_FTC IN ('NÃO REMATRICULADO NÃO-PAGO','NÃO REMATRICULADO PAGO','PRE-MATRICULADO NÃO-PAGO')

select * FROM BI_REMATRICULA BI WHERE BI.ANO = 2019 AND BI.SEMESTRE = 1
AND BI.TIPO_FINAN = 'PAGANTES'
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 WHERE BI2.ALUNO = BI.ALUNO AND BI2.ANO = 2018 AND BI2.SEMESTRE = 2 AND BI2.TIPO_FINAN IN ('FIES','FIES+PROUNI'))
AND STATUS_FTC  NOT IN ('PRE-MATRICULADO PAGO','MATRICULADO NÃO-PAGO','MATRICULADO PAGO','CONCLUIDO')
ORDER BY 4,8

select * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 AND CURSO = '722'
AND STATUS_FTC   NOT IN ('PRE-MATRICULADO PAGO','MATRICULADO NÃO-PAGO','MATRICULADO PAGO','CONCLUIDO')
AND SERIE_CALCULADA > 1
ORDER BY 1,2


select * FROM BI_REMATRICULA WHERE ALUNO = '182040098' ORDER BY 1,2

select ALUNO,* FROM BI_REMATRICULA B WHERE B.STATUS_FTC = 'EVADIDO' AND B.ANO = 2019 AND B.SEMESTRE = 1
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA B2 WHERE B2.ALUNO = B.ALUNO AND B2.STATUS_FTC = 'CANCELADO' AND B2.ANO = 2018 AND B2.SEMESTRE = 2)
ORDER BY 1,2,3


select * FROM BI_REMATRICULA WHERE ANO = 2019 AND ANTECIP_FINAN = 'S'


select * from BI_REMATRICULA where nome_aluno like '%alessandro%aguiar%'


select * FROM BI_REMATRICULA BI WHERE BI.ANO > 2016 AND BI.ANO < 2019
AND BI.STATUS_FTC  NOT IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO') 
AND NOT EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 WHERE BI2.ALUNO = BI.ALUNO AND CONCAT(BI2.ANO,BI2.SEMESTRE) IN ('20182','20191') AND BI2.STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO')
ORDER BY 1,2

select count(ALUNO) QTD, ANO, SEMESTRE FROM BI_REMATRICULA
GROUP BY ANO, SEMESTRE
ORDER BY 2,3

--UPDATE MAX ULTIMA_MATRICULA
UPDATE T
	SET T.ULTIMA_MATRICULA = (SELECT MAX(CONCAT(BI.ANO,'/',BI.SEMESTRE)) FROM BI_REMATRICULA BI WHERE BI.ALUNO = T.ALUNO AND BI.STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO','CONCLUIDO') )
FROM BI_REMATRICULA T


select * FROM BI_REMATRICULA WHERE ULTIMA_MATRICULA IS NULL AND ANO = 2019 AND SEMESTRE = 1

select distinct STATUS_FTC FROM BI_REMATRICULA WHERE ANO = 2019
select * FROM BI_REMATRICULA WHERE ANO = 2019 AND STATUS_FTC IS NULL

select BI.* FROM BI_REMATRICULA BI
WHERE BI.ANO = 2018 AND BI.SEMESTRE = 2 AND BI.TIPO_FINAN IN ('FIES','FIES+PROUNI')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 WHERE BI2.ALUNO = BI.ALUNO AND BI2.ANO = 2019 AND BI2.SEMESTRE = 1 AND BI2.TIPO_FINAN = 'PAGANTES')

select BI.* FROM BI_REMATRICULA BI
WHERE BI.ANO = 2018 AND BI.SEMESTRE = 2 AND BI.TIPO_FINAN IN ('PAGANTES')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 WHERE BI2.ALUNO = BI.ALUNO AND BI2.ANO = 2019 AND BI2.SEMESTRE = 1 AND BI2.TIPO_FINAN IN ('FIES+PROUNI','FIES'))


UPDATE BI_REMATRICULA SET STATUS_FTC = 'MATRICULADO PAGO'
WHERE SIT_MATRICULA IN ('Matriculado','Dispensado') AND PAGO = 1 AND STATUS_FTC IS NULL

UPDATE BI_REMATRICULA SET STATUS_FTC = 'MATRICULADO NÃO-PAGO'
WHERE SIT_MATRICULA IN ('Matriculado','Dispensado') AND PAGO = 0 AND STATUS_FTC IS NULL

	UPDATE BI SET BI.TIPO_FINAN = BI2.TIPO_FINAN
	FROM BI_REMATRICULA BI
	JOIN BI_REMATRICULA BI2 ON BI2.ALUNO = BI.ALUNO 
	WHERE BI2.ANO = 2018
		AND BI2.SEMESTRE = 2
		AND BI2.TIPO_FINAN IN ('FIES','FIES+PROUNI')
		AND BI.TIPO_FINAN = 'PAGANTES'
		AND BI.ANO = 2019
		AND BI.SEMESTRE = 1

		select * FROM BI_REMATRICULA WHERE ANO = 2015 AND SEMESTRE = 2


		select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNo = '152040422' 


select * FROM BI_REMATRICULA WHERE ANO = 2019

select * FROM BI_ACOMP_MATR WHERE SIT_MATRICULA = 'Dispensado'

select * FROM BI_REMATRICULA BI WHERE BI.ANO = 2019 AND BI.SEMESTRE = 1
AND BI.STATUS_FTC = 'EVADIDO'
AND EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA VW WHERE VW.ALUNO = BI.ALUNO AND VW.ANO = BI.ANO AND VW.SEMESTRE = BI.SEMESTRE)
AND TIPO_ALUNO = 'VETERANO'

select * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 AND DATA_MATRICULA IS NULL

SELECT * FROM BI_REMATRICULA BI
WHERE BI.ANO = 2019 AND BI.SEMESTRE = 1
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO')
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA BI2 
			WHERE BI2.CPF = BI.CPF AND BI2.STATUS_FTC NOT IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') 
			AND BI2.ANO = 2019 AND BI2.SEMESTRE = 1 AND BI.UNIDADE_ENSINO_ALUNO <> BI2.UNIDADE_ENSINO_ALUNO)

select ALUNO,NOME_CURSO,* FROM BI_REMATRICULA WHERE CPF = '01630411566' ORDER BY ANO,SEMESTRE

select * FROM BI_REMATRICULA WHERE ANO = 2019 AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') 
AND TIPO_ALUNO = 'VETERANO'

SELECT * FROM BI_REMATRICULA WHERE ALUNO = '141290324' ORDER BY 1,2

select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '141290324'
select * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '141290324'

select * FROM BI_ACOMP_MATR WHERE ALUNO = '182040732'


select * FROM BI_ALUNOS_UNIDADE WHERE PERIODO_LETIVO = '2019/1' AND TIPO_CURSO = 'GRADUACAO SUPERIOR'
order by 8

select CENTRO_DE_CUSTO, DESCR_CENTRO_CUSTO, COUNT(ALUNO) FROM BI_ALUNOS_UNIDADE 
WHERE PERIODO_LETIVO = '2019/1' AND TIPO_CURSO = 'GRADUACAO SUPERIOR'
AND UNIDADE_ENSINO_ALUNO = 'FTC - SALVADOR'
GROUP BY CENTRO_DE_CUSTO, DESCR_CENTRO_CUSTO
ORDER BY 1

select * FROM BI_ALUNOS_UNIDADE 
WHERE PERIODO_LETIVO = '2019/1' AND TIPO_CURSO = 'GRADUACAO SUPERIOR'
AND UNIDADE_ENSINO_ALUNO = 'FTC - SALVADOR'
--GROUP BY CENTRO_DE_CUSTO, DESCR_CENTRO_CUSTO
ORDER BY 1

select * FROM BI_ALUNOS_UNIDADE WHERE PERIODO_LETIVO = '2019/1' AND TIPO_CURSO = 'GRADUACAO SUPERIOR'

select distinct TIPO_CURSO FROM BI_ALUNOS_UNIDADE
select distinct tipo_ingresso from BI_ACOMP_MATR
select * FROM BI_ACOMP_MATR WHERE TIPO_ALUNO = 'CALOURO' AND TIPO_INGRESSO IN ('Reingresso','TransferenciaInterna')

select * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO') 

select DISTINCT ANO, SEMESTRE FROM BI_REMATRICULA
select DISTINCT ANO, SEMESTRE FROM BI_ACOMP_M

SELECT * 
FROM BI_ACOMP_MATR_POS X 
WHERE TIPO_CURSO = 'POS-GRADUACAO' 
AND TIPO_ALUNO = 'CALOURO' 
AND NOME_CURSO = 'Gestão em Unidades de Alimentação e Nutrição, Merenda Escolar e Consultoria'
AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = X.ALUNO) 
AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = X.ALUNO) 


select * FROM BI_REMATRICULA WHERE SERIE_CALCULADA = 0 AND ANO = 2019



select * FROM LYCEUM..LY_CURSO WHERE FACULDADE = '29' AND TIPO IN ('TECNOLOGO','GRADUACAO')
select * FROM LYCEUM..LY_CURSO WHERE NOME LIKE '%radiologia%'
select * FROM LYCEUM..LY_UNIDADE_ENSINO WHERE UNIDADE_ENS = 29

SELECT * FROM BI_ACOMP_MATR WHERE NOME_CURSO LIKE '%Gestão Pública%'
SELECT * FROM BI_ACOMP_MATR_POS WHERE NOME_CURSO LIKE '%Gestão Pública%'

UPDATE BI_REMATRICULA SET SERIE_CALCULADA =  1 WHERE TIPO_ALUNO = 'REINGRESSO'


select * FROM BI_REMATRICULA WHERE NOME_CURSO = 'Direito' AND UNIDADE_FISICA_ALUNO = 'OTE-PET'

select * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 AND STATUS_FTC = 'Evadido'

select distinct data_cancelamento from BI_ACOMP_MATR order by 1

select * FROM LYCEUM..LY_TIPO_BOLSA WHERE GRUPO_BOLSA = 'FIES'
select * FROM LYCEUM..LY_TIPO_BOLSA WHERE TIPO_BOLSA LIKE '%FIES%'

select * FROM BI_ACOMP_MATR WHERE NOME_CURSO LIKE '%Estetica%'

select * FROM BI_ACOMP_MATR WHERE TIPO_ALUNO = 'CALOURO' AND SIT_MATRICULA = 'Cancelado' AND TIPO_CURSO IN ('GRADUACAO','TECNOLOGO')
AND TIPO_INGRESSO NOT IN ('Ouvinte','Reingresso') AND DATA_CANCELAMENTO IS NULL


select * FROM BI_ACOMP_MATR WHER

select * FROM LYCEUM..LY_PESSOA WHERE END_MUNICIPIO IS NULL OR END_MUNICIPIO = ''

select * FROM BI_REMATRICULA 
WHERE ANO = 2019 AND SEMESTRE = 1 AND TIPO_ALUNO = 'VETERANO' 
AND (TIPO_TRANSF NOT IN ('SAIDA CURSO','SAIDA UNIDADE') OR TIPO_TRANSF IS NULL)

SELECT * FROM BI_REMATRICULA 
WHERE ANO = 2019 AND SEMESTRE = 1 
AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NÃO-PAGO','PRE-MATRICULADO PAGO')

select distinct ANO,SEMESTRE FROM BI_REMATRICULA WHERE STATUS_FTC = 'CANCELADO'

select * FROM BI_REMATRICULA WHERE CPF = '02828431592' order by 1,2

select * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND TIPO_FINAN IN ('FIES','FIES+PROUNI') AND TIPO_ALUNO = 'CALOURO'

select * FROM BI_REMATRICULA WHERE ANO = 2018 AND SEMESTRE = 2 AND TIPO_ALUNO = 'CALOURO' AND STATUS_FTC IN ('CANCELADO','EVADIDO','TRANCADO','TRANSFERIDO')

select * FROM BI_REMATRICULA WHERE TIPO_FINAN = 'PROIES' AND ANO < 2017
ORDER BY 1,2

select * FROM LYCEUM..LY_BOLSA
 WHERE TIPO_BOLSA = 'PROIES100' 
AND ANOINI < 2017
ORDER BY 1,2


SELECT * FROM LYCEUM..VW_LANCAMENTOS_PAGAMENTOS WHERE ALUNO = '152040654'

SELECT * FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 0

select * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 AND ALUNO = '172070080'

select * FROM LYCEUM..LY_ITEM_LANC WHERE LANC_DEB IN (select lanc_deb FROM LYCEUM..LY_LANC_DEBITO WHERE ALUNO = '182040804' AND PERIODO_REF = 2 AND ANO_REF = 2018)
select SUM(VALOR) 
FROM LYCEUM..LY_ITEM_LANC 
WHERE LANC_DEB IN (SELECT lanc_deb 
					FROM LYCEUM..LY_LANC_DEBITO 
					WHERE ALUNO = '161030237' 
					AND PERIODO_REF = 2 
					AND ANO_REF = 2018
					AND ITEM_ESTORNADO IS NULL)

select * FROM BI_REMATRICULA WHERE  ANO >= 2018 AND STATUS_FTC IN ('EVADIDO','TRANCADO','TRANSFERIDO','CANCELADO')

select * FROM LYCEUM..LY_BOLSA WHERE ALUNO = '172070080'



select * FROM LYCEUM..LY_CENTRO_DE_CUSTO WHERE CENTRO_DE_CUSTO = '009001'
select * FROM LYCEUM..LY_CENTRO_DE_CUSTO WHERE CURSO ='4019'

select * FROM LYCEUM..LY_CURSO WHERE CURSO = '4019'

select * FROM BI_REMATRICULA B WHERE B.ANO = 2019 AND B.SEMESTRE = 1 AND B.STATUS_FTC = 'TRANCADO'
AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ALUNO = B.ALUNO)

SELECT DISTINCT MOTIVO FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ANO_ENCERRAMENTO = 2019 AND SEM_ENCERRAMENTO = 1
SELECT DISTINCT CAUSA_ENCERR FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ANO_ENCERRAMENTO = 2019 AND SEM_ENCERRAMENTO = 1

SELECT * FROM BI_REMATRICULA WHERE ANO >= 2018

select * FROM BI_ACOMP_MATR_POS WHERE SIT_MATRICULA IS NOT NULL AND SIT_MATRICULA <> ''

select * FROM LYCEUM..LY_TRANCAMENTO WHERE ANO_TRANC = 2019 AND SEM_TRANC = 1

select * FROM BI_REMATRICULA WHERE ALUNO = '181290007' AND ANO = 2019 AND SEMESTRE = 1
select * FROM BI_REMATRICULA WHERE ALUNO = '181290007' AND ANO = 2018 AND SEMESTRE = 2


SELECT ALUNO INTO #TEMP FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 1 AND CURSO = '722' AND SIT_MATRICULA NOT IN ('CANCELADO')
EXCEPT
SELECT ALUNO FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 AND CURSO = '722' AND STATUS_FTC NOT IN ('CANCELADO','DISPENSADO','EVADIDO','TRANCADO')
--DROP TABLE #TEMP


select * FROM BI_REMATRICULA WHERE ALUNO IN (SELECT ALUNO FROM #TEMP) AND ANO = 2019 AND SEMESTRE = 1
select * FROM BI_ACOMP_MATR WHERE ALUNO = '192060009' AND ANO = 2019 AND SEMESTRE = 1
select * FROM BI_REMATRICULA WHERE ALUNO = '182040102' AND ANO = 2019 AND SEMESTRE = 1

select
select * FROM LYCEUM..LY_ALUNO WHERE ALUNO = '172041045' AND ANO = 2019 AND SEMESTRE = 1
--172041045 tem no acomp e nao na remat
--182040102 contrario


SELECT * FROM LYCEUM..LY_ALUNO WHERE NOME_COMPL LIKE '%alex%bitencourt%'

select * FROM BI_REMATRICULA WHERE ALUNO = '101050138' ORDER BY 1,2
select * FROM BI_REMATRICULA WHERE ALUNO = '182041484' ORDER BY 1,2

select * FROM BI_REMATRICULA WHERE TIPO_ALUNO = 'REINGRESSO' AND ANO = 2014 AND SEMESTRE = 1

select * FROM LYCEUM..LY_CURSO WHERE CURSO = '28'

SELECT ALUNO INTO #TEMP FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 AND TIPO_FINAN = 'PROIES' AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NAO-PAGO','PRE-MATRICULADO PAGO')
EXCEPT --DROP TABLE #TEMP
SELECT ALUNO FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 1 AND TIPO_FINAN = 'PROIES' AND SIT_MATRICULA <> 'Cancelado'

SELECT * FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 1 AND ALUNO IN (SELECT ALUNO FROM #TEMP)

SELECT SUM(METAS) FROM BI_METAS WHERE ANO = 2019 AND SEMESTRE = 1 AND COD_UNIDADE = 'FCS' AND TIPO_ALUNO = 'VETERANO'


UPDATE T SET STATUS_FTC = 'CONCLUIDO'
FROM TEMP_REMATRICULA T 
WHERE LYCEUM.dbo.fn_FTC_QTD_DISC_PENDENTE(T.ALUNO,'N') = 0
AND T.ANO = @p_ano
AND T.SEMESTRE = @p_semestre
AND EXISTS (SELECT TOP 1 1 
			FROM LYCEUM..LY_HISTMATRICULA 
			WHERE ALUNO = T.ALUNO 
			AND ANO = CASE @p_semestre WHEN '1' THEN @p_ano-1 WHEN '2' THEN @p_ano WHEN '11' THEN @p_ano-1 WHEN '22' THEN @p_ano ELSE @p_ano END 
			AND SEMESTRE = CASE @p_semestre WHEN '1' THEN '2' WHEN '2' THEN '1' WHEN '22' THEN '11' WHEN '11' THEN '22' ELSE @p_semestre END)

select * FROM BI_ACOMP_MATR WHERE ALUNO = '192060009'

select * FROM BI_EVASAO_CORRENTE WHERE SOLICITOU_CANCELAMENTO = 'S'

select * FROM LYCEUM..LY_FALTA WHERE ALUNO IN (select ALUNO FROM BI_EVASAO_CORRENTE WHERE SOLICITOU_CANCELAMENTO = 'S')

SELECT ALUNO
INTO #TEMP --DROP TABLE #TEMP
FROM BI_ACOMP_MATR A
WHERE	A.ANO = 2019
		AND A.SEMESTRE = 1
		--AND TIPO_ALUNO = 'VETERANO'
		AND PAGO = 1
		AND SIT_MATRICULA NOT IN ('Cancelado','Trancado')
		AND UNIDADE_ENSINO_ALUNO NOT IN ('30','58','54','57')
		
		
		
SELECT ALUNO 
INTO #TEMP2 FROM #TEMP
EXCEPT
select ALUNO FROM BI_REMATRICULA 
	WHERE	ANO = 2019 
			AND SEMESTRE = 1 
			AND STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NAO-PAGO','PRE-MATRICULADO PAGO')
			--AND TIPO_ALUNO = 'VETERANO'
			--drop table #temp2
			select * FROM BI_ACOMP_MATR WHERE ALUNO IN (select aluno from #TEMP2)
			select * FROM BI_REMATRICULA WHERE ALUNO IN (select aluno from #TEMP2) AND ANO = 2019 AND SEMESTRE = 1

			select * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO IN (select aluno from #TEMP2) order by aluno
			select * FROM LYCEUM..LY_ALUNO WHERE ALUNO IN (select aluno from #TEMP2) order by aluno
			select * FROM LYCEUM..LY_H_CURSOS_CONCL WHERE ALUNO IN (select aluno from #TEMP2) order by aluno
UPDATE T SET SIT_MATRICULA = 'Cancelado'
FROM BI_ACOMP_MATR T
JOIN LYCEUM..LY_ALUNO A ON A.ALUNO = T.ALUNO
WHERE A.SIT_ALUNO = 'Cancelado' AND T.ANO = 2019 AND T.SEMESTRE = 1
	
	SELECT * FROM LYCEUM..LY_TRANCAMENTO A WHERE ALUNO = '191200002'

	select * FROM BI_EVASAO_CORRENTE WHERE SOLICITOU_CANCELAMENTO = 'S'

	SELECT * FROM BI_REMATRICULA WHERE STATUS_FTC IN ('MATRICULADO PAGO','MATRICULADO NAO-PAGO','PRE-MATRICULADO PAGO')
	AND TIPO_ALUNO IN ('CALOURO') AND UNIDADE_ENSINO_ALUNO <> '30'
	AND ANO = 2019 AND SEMESTRE = 1
	ORDER BY 1,2,4,8

select * FROM BI_REMATRICULA 
	WHERE	ANO = 2019 
			AND SEMESTRE = 1 

			SELECT DISTINCT ANO, SEMESTRE FROM BI_REMATRICULA ORDER BY 1,2

			select * FROM BI_ACOMP_MATR WHERE ALUNO = '192290077'

select * FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 1

select * FROM BI_GESTAO_PESSOAS WHERE ANO_COMPETENCIA = 2019 AND MES_COMPETENCIA = 6 AND CODSECAO LIKE '01.01.%'
select * FROM BI_GESTAO_PESSOAS WHERE ANO_COMPETENCIA = 2019 AND CPF = '75933748587'
select * FROM BI_GESTAO_PESSOAS WHERE ANO_COMPETENCIA = 2019 AND MES_COMPETENCIA = 6 AND CODSECAO = '01.01.1421078'


select * FROM BI_ACOMP_MATR WHERE ANO = 2019 AND SEMESTRE = 2
AND ALUNO = '192050392'

--182040093
--182041471
--191040024
--191040372

SELECT * FROM BI_ACOMP_MATR WHERE ANO = 2020 AND SEMESTRE = 1 AND TIPO_ALUNO = 'CALOURO' AND TIPO_FINAN NOT LIKE '%PRO%'

SELECT * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 2 AND ALUNO = '192290531' ORDER BY 1,2

SELECT * FROM BI_REMATRICULA WHERE CPF = '86042218590' ORDER BY 1,2
--04300852570


SELECT DISTINCT ANO,SEMESTRE FROM BI_REMATRICULA ORDER BY 1,2

SELECT * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE =2 AND ALUNO = '172070545'
select top 10 * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA ORDER BY DT_INSERCAO DESC


select * FROM BI_DMP2 WHERE ANO = 2020

SELECT * FROM BI_REMATRICULA A WHERE A.ANO = 2020 AND A.SEMESTRE = 1 AND A.TIPO_ALUNO = 'VETERANO'
AND NOT EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA B WHERE B.ALUNO = A.ALUNO AND B.ANO = 2019 AND B.SEMESTRE = 2)

SELECT TIPO_FINAN, COUNT(ALUNO) FROM BI_REMATRICULA
WHERE ANO = 2020 AND SEMESTRE = 1 AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO') AND TIPO_ALUNO = 'VETERANO'
GROUP BY TIPO_FINAN 

SELECT * FROM BI_REMATRICULA WHERE ANO = 2020 AND SEMESTRE = 1 AND UNIDADE_FISICA_ALUNO = 'UNECE-EUN'

SELECT * FROM BI_ACOMP_MATR WHERE ANO = 2020 AND SEMESTRE = 1 AND ALUNO = '201040428'

SELECT ANO,SEMESTRE,TIPO_ALUNO,COUNT(ALUNO) QTD 
FROM BI_REMATRICULA
WHERE SIT_MATRICULA IN ('Matriculado','Pre-Matriculado')
AND PAGO = 1
AND TIPO_FINAN IN ('PAGANTES','FIES')
GROUP BY ANO, SEMESTRE, TIPO_ALUNO
ORDER BY 1,2

SELECT * FROM BI_DMP2 WHERE ANO = 2019 AND SEMESTRE = 1

SELECT TIPO_FINAN, * FROM BI_REMATRICULA WHERE ANO = 2020 AND SEMESTRE = 1 AND ALUNO = '151040028'

SELECT TIPO_FINAN, * FROM BI_ACOMP_MATR WHERE ANO = 2020 AND SEMESTRE = 1 AND ALUNO = '151040028'

SELECT * FROM LYCEUM..LY_PLANO_PGTO_PERIODO WHERE ALUNO = '151040028' AND ANO = 2020 AND PERIODO = 1


SELECT * FROM BI_REMATRICULA WHERE ALUNO = '031040293' ORDER BY 1,2
SELECT * FROM BI_ACOMP_MATR WHERE ALUNO = '201040734' ORDER BY 1,2

SELECT * FROM LYCEUM..LY_ALUNO WHERE CANDIDATO = 'CAN-384351-FTC'
SELECT * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '201041249'
SELECT * FROM BI_ACOMP_MATR WHERE CANDIDATO = 'CAN-376874-FTC' ORDER BY 1,2 

SELECT * FROM LYCEUM..VW_MATRICULA_E_PRE_MATRICULA WHERE ALUNO = '201220269'
SELECT PESSOA,* FROM LYCEUM..LY_ALUNO WHERE ALUNo = '201220269'

SELECT * FROM LYCEUM..LY_PESSOA WHERE PESSOA = '182806'

SELECT * FROM LYCEUM..LY_ALUNO WHERE PESSOA IN (
SELECT PESSOA FROM LYCEUM..LY_PESSOA WHERE ISNUMERIC(END_MUNICIPIO) = 0)

SELECT DISTINCT CONVERT(DATETIME,DATA_MATRICULA,103) FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 2 ORDER BY 1


SELECT * FROM BI_REMATRICULA 
WHERE ANO = 2019 AND SEMESTRE = 2 
AND STATUS_FTC IN ('MATRICULADO PAGO','PRE-MATRICULADO PAGO','CONCLUIDO','INCONCLUIDO') 



SELECT UNIDADE_ENSINO_ALUNO, NOME_UNIDADE_ENSINO_ALUNO, TIPO_CURSO, CURSO, NOME_CURSO, TIPO_INGRESSO, ALUNO, NOME_ALUNO 
FROM BI_REMATRICULA 
WHERE ANO = 2020 AND SEMESTRE = 1 AND TIPO_INGRESSO NOT IN ('Vestibular','ENEM','MatriculaEspecial','Reingresso','TransferenciaExterna','TransferenciaInterna','PROUNI','FIES')

SELECT DISTINCT TIPO_INGRESSO FROM BI_REMATRICULA WHERE ANO = 2020 AND SEMESTRE = 1 AND TIPO_INGRESSO NOT IN ('Vestibular','ENEM')

SELECT * FROM BI_DMP2 WHERE TIPO_INGRESSO = 'VETERANO'

SELECT DISTINCT ANO, SEMESTRE FROM BI_REMATRICULA ORDER BY 1,2

SELECT DISTINCT NOME_CURSO FROM BI_REMATRICULA ORDER BY 1

SELECT * FROM BI_ACOMP_MATR WHERE ANO = 2020 AND SEMESTRE = 1 
--AND  TIPO_CREDITO IS NULL 
AND PAGO = 0
--AND DATA_PAGAMENTO IS NULL
--AND TIPO_ALUNO IN  ('CALOURO','CALOURO-CONCLUINTE','REINGRESSO','REINGRESSO-CONCLUINTE') 
--AND TIPO_FINAN = 'PAGANTES'
AND DATA_VENCIMENTO IS NULL
AND ALUNO = '201060539'


SELECT DISTINCT DATA_MATRICULA, DIA_CAMPANHA FROM BI_REMATRICULA WHERE ANO = 2020 AND SEMESTRE = 1
UNION

SELECT DISTINCT DATA_MATRICULA, DIA_CAMPANHA FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE = 1 ORDER BY 1

SELECT * FROM BI_REMATRICULA 
WHERE ALUNO IN ('192041679','192060020','192290575','192290027','192030050','192290579','192050048'
				,'192041739','192070308','192290410','192041940','192060183','192070411','192060303'
				,'192060285','192041987','192290594','192041248','192290104','192030541','192040962'
				,'192290481','192041300','192040492','192210012','192030200','192060180','192041759'
				,'192040840','192030471','192030544','192050679','192290385','192290071','192060343'
				,'192041355','192030643','192041051','192030477','192042067','192060138','192030542'
				,'192060392','192060082','192041539','192060135','192041464','192060346','192070490'
				,'192041463')
AND ANO = '2019' AND SEMESTRE = '2'
ORDER BY 1,2


select DISTINCT DATA_HIST FROM BI_REMATRICULA_HIST WHERE CONCAT(ANO,SEMESTRE) = '20191' ORDER BY 1
SELECT * FROM BI_ACOMP_MATR WHERE ANO = 2020 AND SEMESTRE = 1
SELECT * FROM BI_REMATRICULA WHERE ALUNO = '201040217 ' ORDER BY 1,2
SELECT * FROM LYCEUM..LY_HISTMATRICULA WHERE ALUNO = '151040592' AND SITUACAO_HIST NOT IN ('Aprovado')
SELECT * FROM BI_REMATRICULA_HIST WHERE ALUNO = '151040901' AND ANO = 2020 AND SEMESTRE = 1 ORDER BY 1

SELECT * FROM BI_REMATRICULA WHERE ANO = 2019 AND SEMESTRE =1
AND (DT_ENCERRAMENTO IS NULL OR CONVERT(DATETIME,DT_ENCERRAMENTO,103) > '2019-05-31')
AND CONVERT(DATETIME,DATA_MATRICULA,103) <= '2019-05-31'


SELECT * FROM LYCEUM..LY_TRANCAMENTO WHERE ALUNO = '191071196'


SELECT *FROM BI_REMATRICULA WHERE  ALUNO = '192060273' ORDER BY 1,2
SELECT * FROM LYCEUM..LY_HISTMATRICULA WHERE

SELECT * FROM BI_ACOMP_MATR BI WHERE BI.PAGO = 1 AND SIT_MATRICULA = 'Pre-Matric' 
AND TIPO_FINAN = 'PAGANTES'
AND ANO = 2020 AND SEMESTRE = 1 --AND BOLSAS LIKE '%UNIFTC_DAY 100%'
AND NOT EXISTS (SELECT TOP 1 1 FROM LYCEUM..LY_ITEM_LANC IL 
			JOIN LYCEUM..LY_ITEM_CRED IC ON IC.COBRANCA = IL.COBRANCA
			WHERE IL.ALUNO = BI.ALUNO
			AND IL.CODIGO_LANC IN ('MS','MS_EB','Acordo'))
AND BI.ALUNO = '201041511'

SELECT TOP 1 1 FROM LYCEUM..LY_LANC_CREDITO WHERE ALUNO = '201041511'

--QUERO, EDUCA, BAFFFTC, PCD, PARES, IMES



SELECT DISTINCT SIT_MATRICULA FROM BI_ACOMP_MATR WHERE ANO = 2020 AND SEMESTRE = 1

SELECT * FROM BI_REMATRICULA_HIST WHERE ALUNO IN ('172041032','191040337','191040372') and ano = 2020 and semestre = 1



SELECT C.FACULDADE, UE.NOME_COMP,C.TIPO,C.CURSO, C.NOME, C.ATIVO
FROM LY_CURSO C 
JOIN LY_UNIDADE_ENSINO UE ON UE.UNIDADE_ENS = C.FACULDADE
WHERE 1=1
AND C.TIPO IN ('GRADUACAO','GRADUACAO-EAD', 'TECNOLOGO', 'GRADUACAO-SP')
ORDER BY 1,3


SELECT * FROM BI_REMATRICULA BI WHERE BI.ANO = 2020 AND BI.SEMESTRE = 2 AND TIPO_FINAN = 'BOLSISTA'
AND EXISTS (SELECT TOP 1 1 FROM BI_REMATRICULA WHERE ALUNO = BI.ALUNO AND ANO = 2020 AND SEMESTRE = 1 AND STATUS_FTC IN ('CONCLUIDO','INCONCLUIDO','MATRICULADO PAGO','PRE-MATRICULADO PAGO','TRANCADO'))


SELECT * FROM BI_REMATRICULA WHERE ALUNO = '202030013' ORDER BY 1,2
SELECT * FROM LYCEUM..LY_BOLSA WHERE ALUNO = '191050587'