declare @p_ano varchar(4),
		@p_semestre varchar(2),
		@p_aluno varchar(20)

SET @p_ano = '2019'
SET @p_semestre = '1'
SET @p_aluno= '191030823'

SELECT TOP 1 'PAGAMENTO MENSALIDADE' AS TIPO FROM LYCEUM..LY_ITEM_CRED IC
				JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = IC.COBRANCA
				JOIN LYCEUM..LY_LANC_DEBITO LD ON LD.LANC_DEB = IL.LANC_DEB
				WHERE LD.ANO_REF = @p_ano
				AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL
				AND LD.PERIODO_REF = @p_semestre
				AND LD.ALUNO = @p_aluno 
				AND LD.CODIGO_LANC IN ('MS','MS_EB')
UNION

--BOLSA 100% NO SEMESTRE
	SELECT TOP 1 'BOLSA 100% NO SEMESTRE' AS TIPO FROM LYCEUM..LY_BOLSA B
					WHERE B.ALUNO = @p_aluno AND B.DATA_CANCEL IS NULL 
					AND PERC_VALOR = 'Percentual' AND VALOR = 1
					AND (B.ANOINI >= (SELECT YEAR(DT_INICIO) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre)
					AND (B.MESINI = CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END))
					
UNION
--BOLSA 100% ABERTA		
	SELECT TOP 1 'BOLSA 100% ABERTA' AS TIPO FROM LYCEUM..LY_BOLSA B 
					WHERE B.ALUNO = @p_aluno AND B.DATA_CANCEL IS NULL 
					AND B.PERC_VALOR = 'Percentual' AND B.VALOR = 1
					AND B.ANOFIM IS NULL
					AND B.MESFIM IS NULL
		
UNION
--BOLSA CREDEDUC
	SELECT TOP 1 'BOLSA CREDEDUC' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA = 'CREDEDUC' 
					AND B.ALUNO = @p_aluno
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)
UNION
--BOLSA FIES TEMP *SOLICITADO POR ANDRÉ BRITTO / ANA PAULA GOMES em 25/03/2019*
	SELECT TOP 1 'BOLSA FIES TEMP' AS TIPO FROM LYCEUM..LY_BOLSA B WHERE B.TIPO_BOLSA IN ('FIES_TEMP','CAIXAFIES_TEMP')
					AND B.ALUNO = @p_aluno
					AND B.DATA_CANCEL IS NULL
					AND (B.ANOFIM >= (SELECT YEAR(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.ANOFIM IS NULL) 
					AND (B.MESFIM >= (SELECT MONTH(DT_FIM) FROM LYCEUM..LY_PERIODO_LETIVO WHERE ANO = @p_ano AND PERIODO = @p_semestre) OR B.MESFIM IS NULL)


UNION
--ALUNO CONTRATO FIES
	SELECT TOP 1 'ALUNO CONTRATO FIES' AS TIPO FROM LYCEUM..LY_CONTRATO_FIES CF
					JOIN LYCEUM..LY_CONTRATO_FIES_PERIODO CFP ON CFP.ID_CONTRATO = CF.ID_CONTRATO
					WHERE CFP.ANO = @p_ano AND CFP.PERIODO = @p_semestre AND CF.ALUNO = @p_aluno
UNION
--COBRANÇA DE MENSALIDADE SEM SALDO A PAGAR
	SELECT TOP 1 'COBRANÇA DE MENSALIDADE SEM SALDO A PAGAR' FROM LYCEUM..VW_COBRANCA VW
					JOIN LYCEUM..LY_COBRANCA CO ON CO.COBRANCA = VW.COBRANCA
					JOIN LYCEUM..LY_ITEM_LANC IL ON IL.COBRANCA = VW.COBRANCA
					WHERE IL.CODIGO_LANC IN ('Acerto','MS')
					AND CO.NUM_COBRANCA = 1
					AND VW.ALUNO = @p_aluno
					AND VW.ANO = @p_ano
					AND VW.VALOR <= 50 --SE O ALUNO DEVE MENOS ATÉ 50 REAIS NÃO É CONSIDERADO INADIMPLENTE
					AND VW.MES BETWEEN CASE WHEN @p_semestre IN ('1','11') THEN 1 WHEN @p_semestre IN ('2','22') THEN 7 ELSE 1 END AND CASE WHEN @p_semestre IN ('1','11') THEN 6 WHEN @p_semestre IN ('2','22') THEN 12 ELSE 12 END