--Camila Cruzes de Andrade
SELECT * FROM ly_aluno WHERE nome_compl LIKE '%Camila%Cruzes%de%Andrade%'
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Camila Cruzes de Andrade%'
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE cod_aluno_virtual = '298368'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '562785'

--Roberta Bomfim Ramos
SELECT c.NOME,* 
	FROM ly_aluno A
	JOIN LY_CURSO C ON C.CURSO = A.CURSO 
	WHERE nome_compl LIKE '%Roberta Bomfim Ramos%'
SELECT * FROM LY_COBRANCA lc WHERE lc.ALUNO = '162050439' AND lc.ANO = 2016 AND lc.MES BETWEEN 1 AND 6
SELECT * FROM LY_ITEM_LANC WHERE COBRANCA IN (SELECT COBRANCA FROM LY_COBRANCA lc WHERE lc.ALUNO = '162050439' AND lc.ANO = 2016 AND lc.MES BETWEEN 1 AND 6)
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Roberta%Bomfim%Ramos%'
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE cod_aluno_virtual = '859513'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '859513'

--Paulinne Cerqueira Barbosa
SELECT c.NOME,* 
	FROM ly_aluno A
	JOIN LY_CURSO C ON C.CURSO = A.CURSO 
	WHERE nome_compl LIKE '%Paulinne Cerqueira Barbosa%'
SELECT * FROM LY_COBRANCA lc WHERE lc.ALUNO = '162050057' AND lc.ANO = 2016 AND lc.MES BETWEEN 1 AND 6
SELECT * FROM LY_ITEM_LANC WHERE COBRANCA IN (SELECT COBRANCA FROM LY_COBRANCA lc WHERE lc.ALUNO = '162050057' AND lc.ANO = 2016 AND lc.MES BETWEEN 1 AND 6)
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Paulinne Cerqueira Barbosa%'
SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE cod_aluno_virtual = '859513'
SELECT * FROM MIGRACAO..TMP_PESSOA_ALUNO_DOCENTE_RESP_AUX WHERE cod_aluno_virtual = '859513'

--Sharlane Souza Santos
SELECT c.NOME,* 
	FROM ly_aluno A
	JOIN LY_CURSO C ON C.CURSO = A.CURSO 
	WHERE nome_compl LIKE '%Sharlane Souza Santos%'

SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Sharlane Souza Santos%'

--Geisa Oliveira Silva
SELECT c.NOME,* 
	FROM ly_aluno A
	JOIN LY_CURSO C ON C.CURSO = A.CURSO 
	WHERE nome_compl LIKE '%Geisa Oliveira Silva%'

SELECT * FROM VW_COBRANCA vc WHERE vc.ALUNO = '151050298' AND ANO = 2016 AND MES < 7

SELECT COD_ALUNO_VIRTUAL,* FROM VIRTUALCLASS..MY_TMP_PES_ALU_DOC_RES WHERE NOME_COMPL LIKE '%Geisa Oliveira Silva%'