USE LYCEUM
GO

SELECT	DISTINCT
		TOP 1000
		C.FACULDADE
		,S.CURSO
		,C.NOME
		,S.TURNO
		,S.CURRICULO
		,S.SERIE
		,VSP.CUSTO_UNITARIO*SUM(D.CREDITOS)/6 AS VALOR_MENSALIDADE
FROM LY_SERIE S  --SERIE CONTEM O CODIGO DO SERVICO DE MENSALIDADE
JOIN LY_GRADE G	 ---GRADE TEM AS DISCIPLINAS DA SERIE 1
					ON G.CURSO = S.CURSO 
					AND G.CURRICULO = S.CURRICULO 
					AND G.TURNO = S.TURNO 
					AND G.SERIE_IDEAL = S.SERIE
JOIN LY_DISCIPLINA D --DISCIPLINA TEM OS CREDITOS PARA CALCULAR A MENSALIDADE
					ON D.DISCIPLINA = G.DISCIPLINA
JOIN LY_VALOR_SERV_PERIODO VSP --VALOR DO SERVICO NO PERIODO
								ON VSP.SERVICO = S.SERVICO_CRED
JOIN LY_CURSO C
				ON C.CURSO = S.CURSO AND C.ATIVO = 'S'
WHERE 1=1 AND C.FACULDADE = '04'
AND VSP.ANO = 2019
AND VSP.PERIODO = 1
AND S.SERIE = 1
AND C.TIPO IN ('GRADUACAO','TECNOLOGO')
GROUP BY C.FACULDADE
		,S.CURSO
		,C.NOME
		,S.TURNO
		,S.CURRICULO
		,S.SERIE
		,VSP.CUSTO_UNITARIO