altEr VIEW VW_ENTURMACAO  
  
AS  
  
/**************  
*  
*CRIADA POR FABIO ;p 21/07/2017  
*  
*****************/  
  
  
SELECT DISTINCT   
  MPM.ALUNO  
 ,MPM.ANO  
 ,MPM.SEMESTRE  
 ,MPM.DISCIPLINA  
 ,MPM.TURMA  
 ,MPM.SIT_MATRICULA  
 ,TS.TURMA_INTEGRACAO  
 ,TI.TURMA_ID  
 ,U.EADBOXID  
 ,U.EMAIL  
 FROM  MATRICULA  MPM  
 INNER JOIN LYCEUM..LY_ALUNO A ON A.ALUNO=MPM.ALUNO  
 INNER JOIN LYCEUM..LY_PESSOA P ON P.PESSOA=A.PESSOA  
 INNER JOIN USUARIO U ON U.PESSOA=P.PESSOA AND U.CPF=P.CPF  
 INNER JOIN  LYCEUM..LY_TURMA T ON T.DISCIPLINA=MPM.DISCIPLINA   
           AND T.TURMA=MPM.TURMA   
           AND T.ANO=MPM.ANO   
           AND T.SEMESTRE=MPM.SEMESTRE  
    INNER JOIN TURMA_SINCRONIZACAO TS ON TS.DISCIPLINA=MPM.DISCIPLINA  
          AND TS.TURMA=MPM.TURMA AND TS.ANO=MPM.ANO  
          AND TS.SEMESTRE=MPM.SEMESTRE  
    INNER JOIN TURMA_INTEGRACAO TI ON TI.DISCIPLINA=TS.DISCIPLINA AND TI.TURMA=TS.TURMA_INTEGRACAO  
           AND TI.ANO=TS.ANO AND TI.SEMESTRE=TS.SEMESTRE  
 WHERE 1=1  
    --AND T.NIVEL='TEORICA'  
 AND U.EADBOXID IS NOT NULL  
 AND MPM.ANO=2018  
 AND MPM.SEMESTRE=1  
 --AND MPM.DT_CRIACAO >'2018-03-05'  
  AND A.UNIDADE_FISICA NOT IN ('OTE-JUA','OTE-PET', 'OTE-SP')
  --AND A.UNIDADE_FISICA = 'FTC-SSA'
  AND U.EMAIL <>''  
  AND MPM.DT_INTEGRACAO  IS NULL  
  AND MPM.SITUACAO ='1'  
  ---AND MPM.ALUNO in ('181040157')  
  --AND  MPM.dt_criacao >'2018-03-09'   
  --AND  MPM.dt_criacao <'2017-09-13'   
 AND MPM.TURMA IS NOT NULL  
 AND MPM.MATRICULA_EADBOX IS  NULL  
 AND EXISTS(  
    SELECT 1 FROM  TURMA_SINCRONIZACAO TS WHERE   
    TS.DISCIPLINA=MPM.DISCIPLINA AND TS.TURMA=MPM.TURMA   
    AND TS.ANO=MPM.ANO AND TS.SEMESTRE=MPM.SEMESTRE  
     )