USE LYCEUM
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'V' AND OBJECT_ID = OBJECT_ID('dbo.VW_FTC_REGRA_ARRASTO_BOLETO_POS'))
   exec('CREATE VIEW [dbo].[VW_FTC_REGRA_ARRASTO_BOLETO_POS] AS SELECT 1 FIELD')
GO 
      
ALTER VIEW VW_FTC_REGRA_ARRASTO_BOLETO_POS      
AS       
SELECT ALUNO       
FROM LY_ALUNO A      
JOIN LY_CURSO C      
    ON A.CURSO = C.CURSO      
WHERE C.TIPO IN ('POS-GRADUACAO','MESTRADO')      
GO