SELECT SUM(vmc.VALOR)
  FROM VW_MOVIMENTO_CAIXA vmc WHERE vmc.USUARIO_LYC = '00794655521' AND vmc.DATA_ABERTURA = '2016-03-09'
  
SELECT *
  FROM VW_MOVIMENTO_CAIXA vmc WHERE vmc.USUARIO_LYC = '00794655521' AND vmc.DATA_ABERTURA = '2016-03-09'
  
    
  
  
SELECT SUM(IC.VALOR)
FROM LY_ALUNO A      
  JOIN LY_COBRANCA  C ON C.ALUNO  = A.ALUNO      
  JOIN LY_RESP_FINAN R ON C.RESP = R.RESP    
  JOIN LY_ITEM_CRED  IC ON IC.COBRANCA = C.COBRANCA      
  JOIN LY_LANC_CREDITO  LC ON LC.LANC_CRED = IC.LANC_CRED      
  JOIN LY_CONTROLE_CAIXA CC ON CC.ID_ABERTURA = LC.ID_ABERTURA  
  LEFT JOIN LY_UNIDADE_FISICA U ON U.UNIDADE_FIS = A.UNIDADE_FISICA
  JOIN LY_CURSO CUR ON CUR.CURSO = A.CURSO
WHERE IC.TIPODESCONTO IS NULL      
  AND IC.TIPO_ENCARGO IS NULL      
  --AND LC.TIPO_PAGAMENTO <> 'BANCO'    
  AND LC.ID_ABERTURA IS NOT NULL  
  AND 0 > (SELECT SUM(VALOR) FROM LY_ITEM_CRED WHERE LANC_CRED = IC.LANC_CRED)
  --AND CC.USUARIO_LYC = '01061359530' AND CC.DATA_ABERTURA = '2016-03-10'
  
  
  
  
SELECT IC.*
FROM LY_ALUNO A      
  JOIN LY_COBRANCA  C ON C.ALUNO  = A.ALUNO      
  JOIN LY_RESP_FINAN R ON C.RESP = R.RESP    
  JOIN LY_ITEM_CRED  IC ON IC.COBRANCA = C.COBRANCA      
  JOIN LY_LANC_CREDITO  LC ON LC.LANC_CRED = IC.LANC_CRED      
  JOIN LY_CONTROLE_CAIXA CC ON CC.ID_ABERTURA = LC.ID_ABERTURA  
  LEFT JOIN LY_UNIDADE_FISICA U ON U.UNIDADE_FIS = A.UNIDADE_FISICA
  JOIN LY_CURSO CUR ON CUR.CURSO = A.CURSO
WHERE IC.TIPODESCONTO IS NULL      
  AND IC.TIPO_ENCARGO IS NULL      
  --AND LC.TIPO_PAGAMENTO <> 'BANCO'    
  AND LC.ID_ABERTURA IS NOT NULL  
  AND 0 > (SELECT SUM(VALOR) FROM LY_ITEM_CRED WHERE LANC_CRED = IC.LANC_CRED)
  --AND CC.USUARIO_LYC = '01061359530' AND CC.DATA_ABERTURA = '2016-03-10'